### ISSUE TITLE
Add docs for DNS SVCB and HTTPS record types

### ISSUE THREAD

**Issue by dhaavi** [cloudflare/cloudflare-docs#10201]
### Which Cloudflare product(s) does this pertain to?

DNS

### Subject Matter

New esssential DNS types already in use by Cloudflare

### Content Location

Should fit quite nicely here:

https://github.com/cloudflare/cloudflare-docs/blob/fbd4a63c45fdc846cebb81fcf266d8de900f719c/content/dns/manage-dns-records/reference/dns-record-types.md?plain=1#L13

### Additional information

`dig cloudflare.com HTTPS`

RFC (current draft): https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/11/?include_text=1

**Comment by RebeccaTamachiro** [comment]
Hey! Thank you for raising this.
Addressed in #11661
