### ISSUE TITLE
Wireformat ambiguous guide

### ISSUE THREAD

**Issue by ahsandar** [cloudflare/cloudflare-docs#1020]
can anyone help explain how `www.example.com` got represented as `q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB` , what encoding is expexted/used over here 
https://github.com/cloudflare/cloudflare-docs/blob/production/products/1.1.1.1/src/content/dns-over-https/wireformat.md

**Comment by lubensakaria** [comment]
I want to withdraw my money but the code denied...allow me

**Comment by lubensakaria** [comment]
Open this issue for me pls
