### ISSUE TITLE
Is the contact email address active?

### ISSUE THREAD

**Issue by moutend** [cloudflare/cloudflare-docs#10224]
### Which Cloudflare product does this pertain to?

Queues

### Existing documentation URL(s)

https://developers.cloudflare.com/queues/platform/javascript-apis/

### What changes are you suggesting?

According to the docs, `queues@cloudflare.com` is a contact email address for Queues:

> If you have any feedback about these APIs, please [contact us](mailto:queues@cloudflare.com) and we would be happy to hear from you.

however, I've got a delivery error. Is this address active?

> Delivery Status Notification (Failure) Address not found
> 
> Your message wasn't delivered to queues@cloudflare.com because the address couldn't be found, or is unable to receive mail.

FYI, my email address domain is `@gmail.com`.

**Comment by Maddy-Cloudflare** [comment]
Hello @moutend! Thank you for reporting! I'll look into this with the team.

**Comment by Maddy-Cloudflare** [comment]
Instead of using the Queues email address, we recommend you to use the Discord channel and/or Community forum.

https://developers.cloudflare.com/queues/platform/javascript-apis/
