### ISSUE TITLE
Does R2 support unlinking presigned URLs 

### ISSUE THREAD

**Issue by kdpuvvadi** [cloudflare/cloudflare-docs#10236]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

presigned URLs

### Content Location

examples/rclone/

### Additional information

Does R2 support unlinking presigned URLs with `rclone link --unlink r2:mybucket/somefile` ? while trying to unlink already linked object with the above, generating new presigned URL for the given object.

**Comment by harshal317** [comment]
Sorry R2 doesn't support the `--unlink` flag. The presigned URL that's generated by `rclone link` for R2 can be disallowed by deleting or rolling the API token.  The URL will also expire at most a week after creating it.

**Comment by dcpena** [comment]
Thanks for the help @harshal317! @kdpuvvadi this PR updates the docs to reflect the info Harshal just shared. https://github.com/cloudflare/cloudflare-docs/pull/10726 

I'm going to mark this issue as closed.

**Comment by kdpuvvadi** [comment]
is there any plan to support this in the future?
