### ISSUE TITLE
Wrangler install and upgrade documentation missing noting new dependency that is blocking

### ISSUE THREAD

**Issue by mrbm** [cloudflare/cloudflare-docs#10230]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/install-and-update/

### What changes are you suggesting?

New dependancies for running v3 are required because of v3 now using sqlite when v2 did not. As a result on a mac m1, because there are no pre-made binaries, the sqlite has to be built which now creates dependancy on command line tools being installed as described by cloudflare dev:

https://github.com/cloudflare/workers-sdk/issues/3531#issuecomment-1658588045

This new dependency needs to be documented in the instructions until cloudflare dev team creates a new version that doesn't depend on sqlite.

The 2nd caveat is that somebody can think they have command line tools installed correctly but if they had upgraded the os or previous run a restore from a certain version and are now running osx ventura...it wont won't.

These 2 caveats need to be mentioned in the documentation for installation...many people seem to have issue with this.

I brought this issue up in June but the person managing issues prematurly closed the issue without feedback. Additionally the other thread that mentioned the issue in the sdk repo also pre-maturely closed the issue.

The solution is to properly document this issue and the work around in the installation documentation of v2 to v3.

Instructions should look like this:

1. Note: v3 gives wrangle a new dependency on sqlite which may require osx command line tools to be installed.
2. To install command line tools properly when running Ventura on an M1 chip not from a fresh install, you may need to delete command line tools and re-install. which may require 15 gb of hard drive space to complete.
A. Delete command line tools: 
sudo rm -rf /Library/Developer/CommandLineTools
B. Install command line tools:
xcode-select --install

### Additional information

Previous issue reported here: https://github.com/cloudflare/cloudflare-docs/issues/7755

**Comment by deadlypants1973** [comment]
#10241
