### ISSUE TITLE
List Durable Object instances in an existing namespace

### ISSUE THREAD

**Issue by TimoWilhelm** [cloudflare/cloudflare-docs#10273]
### Which Cloudflare product(s) does this pertain to?

Durable Objects

### Subject Matter

Document how to list instances in a namespace

### Content Location

The following API can be used to query Durable Object instances in a namespace: https://developers.cloudflare.com/api/operations/durable-objects-namespace-list-objects

This can be helpful if the IDs get lost and the DO instances have storage associated with them. Otherwise the only way to reclaim that storage is to delete the entire namespace.

I believe there should be new section under [Durable Objects/Platform](https://github.com/cloudflare/cloudflare-docs/tree/production/content/durable-objects/platform) that references this API method and how to use it to find Durable Object instances.

### Additional information

Searching for "Durable Objects List Instances" has the following outdated Forum Post as the first result: https://community.cloudflare.com/t/durable-objects-list-all-instances/314058

This post incorrectly claims that there is currently no way to query for durable object instances in a namespace. It might also make sense to update the accepted answer there.

**Comment by Zenairo** [comment]
I basically went through the same process as @TimoWilhelm here, found the forum post with outdated information first and later this github issue. It would certainly help others to follow through on updating the forum post described in Additional Information.
