### ISSUE TITLE
Document Workers's fetch() DNS resolution

### ISSUE THREAD

**Issue by markdembo** [cloudflare/cloudflare-docs#10294]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

fetch() DNS resolution

### Content Location

https://developers.cloudflare.com/workers/runtime-apis/fetch/
OR/AND
https://developers.cloudflare.com/workers/platform/known-issues/

### Additional information

Should explain the DNS resolution and resolution steps for potentially related 530 error codes in partial zone setups.

**Comment by KimJ15** [comment]
Closed by https://github.com/cloudflare/cloudflare-docs/pull/7064 and https://github.com/cloudflare/cloudflare-docs/pull/15682
