### ISSUE TITLE
Constellation verified models catalog is empty, wording seems to suggest otherwise

### ISSUE THREAD

**Issue by AdiRishi** [cloudflare/cloudflare-docs#10336]
### Which Cloudflare product does this pertain to?

Constellation

### Existing documentation URL(s)

https://developers.cloudflare.com/constellation/platform/data-model#catalog

### What changes are you suggesting?

NOTE: I am genuinely not sure if this was an oversight or not (perhaps the content is not ready yet).

#### Issue
Currently the constellation docs specify that Cloudflare will maintain a catalog of models that we can pick and run with ease.
However, the catalog doesn't have any models in it right now, even though the wording on the page heavily implies that there should be an existing list.

#### Suggestion

- If there are no maintained models for Constellation yet, perhaps it makes sense to add a line stating that this is an upcoming feature and will be updated soon
- Else if this was indeed an oversight, add the pre-trained model list to the docs.

**Comment by KimJ15** [comment]
https://developers.cloudflare.com/workers-ai/models/ includes several models so I think we have what you were looking for! Note that Workers AI is currently in Open Beta and is not recommended for production data and traffic, and limits + access are subject to change!
