### ISSUE TITLE
An error in the D1 doc

### ISSUE THREAD

**Issue by qiaoshouzi** [cloudflare/cloudflare-docs#10338]
### Which Cloudflare product does this pertain to?

D1

### Existing documentation URL(s)

https://developers.cloudflare.com/d1/platform/client-api/#return-object

### What changes are you suggesting?

According to https://github.com/cloudflare/workerd/issues/940
```
{
  results: array | null, // [] if empty, or null if it doesn't apply
  success: boolean, // true if the operation was successful, false otherwise
  meta: {
    duration: number, // duration of the operation in milliseconds
  }
}
```
In this case, success: boolean should be changed to success: true

**Comment by elithrar** [comment]
The documentation here documents the return _types_ - not the values.

`success: boolean` is correct.
