### ISSUE TITLE
Logpush API config - "logpull_options"

### ISSUE THREAD

**Issue by AbAvramidis** [cloudflare/cloudflare-docs#10365]
### Which Cloudflare product does this pertain to?

Logs

### Existing documentation URL(s)

https://developers.cloudflare.com/logs/reference/log-output-options/
https://developers.cloudflare.com/api/operations/post-zones-zone_identifier-logpush-jobs
https://developers.cloudflare.com/logs/get-started/api-configuration/#options

### What changes are you suggesting?

Can you please add also an example of how I can select all the Fields during a "logpull_options": config?
Through the UI you have the ability to check All Fields. 
Is that possible via the API? Can somewhere make it clear and give an example?
I have waste too much time trying to find the way to select all fields but does not work. 

### Additional information
I have tried several ways like: 

`“logpull_options”: “fields=ALL_Fields&timestamps=rfc3339”`

`“logpull_options”: “fields=all&timestamps=rfc3339”`

`“logpull_options”: “fields=All&timestamps=rfc3339”`

`“logpull_options”: “fields=*&timestamps=rfc3339”`

also through the new format:
`    "output_options": {
        "field_names": ["*"],
        "timestamp_format": "rfc3339"
    }`

Nothing of the above worked for me
_No response_

**Comment by cicku** [comment]
We are not able to provide an example of full fields selection because datasets are being updated but documentation, if not updated in time, can be misleading. However, all methods you have listed are invalid.

Selecting all fields basically means `“logpull_options”: “fields=fieldA,fieldB,fieldC&timestamps=rfc3339”`, where `A...C` represents all available fields listed at https://developers.cloudflare.com/logs/reference/log-fields/. Fields can be updated based on future changes.

**Comment by AbAvramidis** [comment]
Hi @cicku , 
Thanks a lot for your reply.
Just to be sure that I got it correct, 
Through the UI we can select to include "All fields" during the creation of a new Logpush Job,  but through the API I have to configured and hardcode all fields as listed at [https://developers.cloudflare.com/logs/reference/log-fields/](url) in order to include all fields? 
There is not an API parameter config to do that right?

**Comment by soheiokamoto** [comment]
Logpush UI uses Logpush API's List fields endpoint to get all fields available at that time: https://developers.cloudflare.com/logs/get-started/api-configuration/

At the moment, you'd have to construct the fields by yourself, for example, for `http_requests` dataset (zone-scoped):
 - Prepare list of fields for logpull_options fields:
  
    ```
    curl -s -D "/dev/stderr" https://api.cloudflare.com/client/v4/zones/$ZONE_TAG/logpush/datasets/http_requests/fields -X GET \
    -H "X-Auth-Email: $X_AUTH_EMAIL" \
    -H "X-Auth-Key: $X_AUTH_KEY" \
    | jq -c -r '.result | keys | @tsv' | tr '\t' ','
    ```

 - Prepare list of fields for output_options field_names:
  
    ```
    curl -s -D "/dev/stderr" https://api.cloudflare.com/client/v4/zones/$ZONE_TAG/logpush/datasets/http_requests/fields -X GET \
    -H "X-Auth-Email: $X_AUTH_EMAIL" \
    -H "X-Auth-Key: $X_AUTH_KEY" \
    | jq -c '.result | keys'
    ```

**Comment by angelampcosta** [comment]
Information added with https://github.com/cloudflare/cloudflare-docs/pull/10715
