### ISSUE TITLE
The translation should be faithful to the original English text, without adding politically inclined.

### ISSUE THREAD

**Issue by david082321** [cloudflare/cloudflare-docs#10376]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

Chinese page:
https://developers.cloudflare.com/support/other-languages/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87/%E4%BA%86%E8%A7%A3-cloudflare-%E7%9A%84%E8%90%A5%E4%B8%9A%E7%A8%8E/

Original page:
https://developers.cloudflare.com/support/account-management-billing/billing-cloudflare-plans/understanding-cloudflare-sales-tax/

### What changes are you suggesting?

I suggest use this translation.

https://github.com/david082321/cloudflare-docs/commit/0e188668392ab7c786e0568c6c40cede9b77f470

**Comment by kodster28** [comment]
Howdy @david082321, thanks for the contribution! Closing this out as we're currently deprecating our localized content (and making this issue outdated).
