### ISSUE TITLE
Is there an api for image analysis?

### ISSUE THREAD

**Issue by chenjunhua8080** [cloudflare/cloudflare-docs#10408]
### Which Cloudflare product(s) does this pertain to?

Images

### Subject Matter

Is there an api for image analysis?

### Content Location

![image](https://github.com/cloudflare/cloudflare-docs/assets/21996245/f0b22622-4c8d-44bf-b751-e99d441e388a)

**Comment by kodster28** [comment]
Looks like there's an endpoint at https://developers.cloudflare.com/api/operations/cloudflare-images-images-usage-statistics that gives you the same data.

**Comment by chenjunhua8080** [comment]
![image](https://github.com/cloudflare/cloudflare-docs/assets/21996245/cbcebf75-d70e-47ba-b677-fb54cd49ed39)
Thank you very much。Yes, the one you provided is good for checking storage capacity. I think my question is that the description is incorrect. I should have asked in the red box. So that's the delivered volume, how do you query it through the api?

**Comment by dcpena** [comment]
Hi @chenjunhua8080, thanks for filing the issue.

Just to be certain that I'm understanding the ask correctly, are you asking whether it's possible to use the API to determine the number of served images?

**Comment by dcpena** [comment]
@chenjunhua8080 the API does not currently support querying for number of served images.
