### ISSUE TITLE
Undocumented endpoint for Gateway CA

### ISSUE THREAD

**Issue by yacinehmito** [cloudflare/cloudflare-docs#10423]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/policies/gateway/network-policies/ssh-logging/#2-generate-a-gateway-ssh-proxy-ca

### What changes are you suggesting?

The section to generation a Gateway SSH proxy CA includes instructions to call an API endpoint: https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/policies/gateway/network-policies/ssh-logging.md?plain=1#L36-L39

However, this endpoint is nowhere to be found in the [API documentation](https://developers.cloudflare.com/api/).

Expected outcome: document the endpoint and link to it from the docs.

**Comment by kodster28** [comment]
Howdy @yacinehmito, we've forwarded along to the internal engineering team and relying on them to action this request.

Closing out this issue as we can't do any more on our end while we're waiting for them to take action.
