### ISSUE TITLE
Switching to cloud fare

### ISSUE THREAD

**Issue by ytbigvinny27** [cloudflare/cloudflare-docs#1044]
Need help switching to cloud fare from Bitcoin Core. Also better knowledge of what to do with codes from Multimine.io account to wallet

**Comment by KimJ15** [comment]
👋 @ytbigvinny27 Thank you for your feedback.  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
