### ISSUE TITLE
win10安装Cloudflare_WARP_Release-x64失败

### ISSUE THREAD

**Issue by 2010dainifei** [cloudflare/cloudflare-docs#10469]
### Which Cloudflare product(s) does this pertain to?

WARP

### Subject Matter

win10安装Cloudflare_WARP_Release-x64失败

### Content Location

win10系统64位，无法正常安装Cloudflare_WARP_Release-x64 V23.7.160.0，请问该如何处理？相关文件已经上传，请求帮助。需要我提供任何文件请告诉我。

### Additional information

![111](https://github.com/cloudflare/cloudflare-docs/assets/60343206/de1a2bb3-302c-4c86-ae35-df58d414afd5)
![222](https://github.com/cloudflare/cloudflare-docs/assets/60343206/fc63d623-e1c8-4bc9-92f5-5dff9f50e4cf)
![333](https://github.com/cloudflare/cloudflare-docs/assets/60343206/a5e6c715-4c9e-482c-945c-128ba23c8ecb)

**Comment by ranbel** [comment]
Hi @2010dainifei, I'm sorry but we only take care of developers.cloudflare.com documentation in this repo. Please reach out to community.cloudflare.com or support.cloudflare.com for help installing WARP.

**Comment by lowsl** [comment]
你知道怎么解决了嘛，俺也一样

**Comment by qiukuip** [comment]
遇到同样的问题🙋
