### ISSUE TITLE
Cloudflare Middleware

### ISSUE THREAD

**Issue by davidjeba** [cloudflare/cloudflare-docs#1047]
Requesting Cloudflare to consider buiding a middleware cms like Strapi.
which can power websites and mobile apps

there should be 2 options
1.API driven Widgets
2.Widgets can be dragged-dropped on Mobile-PWA layout containers

mobile pwa while loading should call the widget-id and just display it

**Comment by KimJ15** [comment]
👋 @davidjeba  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com for assistance.
