### ISSUE TITLE
rss readers whitelist

### ISSUE THREAD

**Issue by patrickdrd** [cloudflare/cloudflare-docs#1050]
hello,

please add inoreader https://www.inoreader.com/ and bazqux https://bazqux.com/ (rss readers) to the whitelist:
https://developers.cloudflare.com/firewall/known-issues-and-faq#bots-currently-detected

thanks

**Comment by KimJ15** [comment]
@pedrosousa Would you mind investigating this recommendation for rss readers in the firewall developer documentation.

**Comment by pedrosousa** [comment]
Hi @patrickdrd 

The owners of the RSS Readers you mentioned must submit a bot verification request. Cloudflare will then evaluate if they should be added to the list of detected bots.

The bot verification request form is available here:
https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform?usp=sf_link

You can find information on the bot verification process in Developer Docs:
https://developers.cloudflare.com/bots/get-started/bm-subscription#verified-bots
