### ISSUE TITLE
ipfsstore.it possible issue

### ISSUE THREAD

**Issue by charlie-x** [cloudflare/cloudflare-docs#1053]
ipfsstore.it seems to be dead

https://developers.cloudflare.com/distributed-web/ipfs-gateway/connecting-website

**Comment by charlie-x** [comment]
eternum.io is pretty much done too, they're no longer accepting  new credits and plan to shut down when all current credits are used up

**Comment by KimJ15** [comment]
@kodster28 we have some dead links on this page. Would you mind investigating and updating? Thanks.
