### ISSUE TITLE
socks-proxy is missing in the service list matrix (cloudflared)

### ISSUE THREAD

**Issue by kei0** [cloudflare/cloudflare-docs#10540]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/tunnel-guide/local/local-management/ingress/#supported-protocols

### What changes are you suggesting?

"Socks-proxy" is not listed in the supported service matrix. Since it is one of the supported services and working in field, please add it to that.

https://github.com/cloudflare/cloudflared/commit/206523344f290dcf787156348e55a17348f9569f

ingress:
  - hostname: socks.example.com
    service: socks-proxy

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request. Feel free to open a feature request with that team at https://github.com/cloudflare/cloudflared/issues.
