### ISSUE TITLE
Audit compatibility dates/flags

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#10586]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/configuration/compatibility-dates/

### What changes are you suggesting?

At least one is missing `http_headers_getsetcookie` (https://github.com/cloudflare/workerd/blob/c6c5445358cb6e34387dcd5cb3015b9d5c2e44c8/src/workerd/io/compatibility-date.capnp#L275-L278).

**Comment by aaronadamsCA** [comment]
Also `urlsearchparams_delete_has_value_arg`, it seems #9235 just never happened. I couldn't understand why I was getting new TS types that didn't correspond to any published compatibility date.
