### ISSUE TITLE
Commands in "How WARP checks for an application" are not correct

### ISSUE THREAD

**Issue by ajcollett** [cloudflare/cloudflare-docs#10593]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/devices/warp-client-checks/application-check/#how-warp-checks-for-an-application

### What changes are you suggesting?

The commands in the "How WARP checks for an application" section cannot be correct. 

`uniq -u` will not print any process that is repeated in the output. Specifically the `-u` flag will remove ALL (not just all but 1) lines which are not unique. Which means you won't pickup applications that have more than one instance running. 

However, if you configure this posture check, it DOES pickup applications that have more than one instance. 
So either the documentation is incorrect regarding the command or flags, OR the check is incorrect and mine worked for some reason that I don't know. 

I checked only on Linux, but the man page seems to say the same for MacOS.

What I expect is that if I copy this command and run it locally, I should get a list of all applciations that might be picked up by the posture check, with only 1 listing of each applications. 

### Additional information

Example:
See that gitlab-runner is running in 2 instances:
``` bash
$: ps -eo pid | awk '{print "/proc/"$1"/exe"}' | xargs readlink -f | awk '{print $1}' | sort | grep gitlab
/usr/bin/gitlab-runner
/usr/bin/gitlab-runner
```

See that this is not picked up by the current command:
```bash
$: ps -eo pid | awk '{print "/proc/"$1"/exe"}' | xargs readlink -f | awk '{print $1}' | sort | uniq -u | grep gitlab
$:
```

If we remove the `-u`:
```bash
$: ps -eo pid | awk '{print "/proc/"$1"/exe"}' | xargs readlink -f | awk '{print $1}' | sort | uniq | grep gitlab
/usr/bin/gitlab-runner
```

**Comment by ranbel** [comment]
Thanks for flagging!
