### ISSUE TITLE
Typo on Set up Cloudflare Access page

### ISSUE THREAD

**Issue by joncar** [cloudflare/cloudflare-docs#106]
products/access/src/content/getting-started/access-setup.md says:

"Choose an authentication domain. The authentication domain will represent you Cloudflare for Teams and the URL will serve as the launch page for end users."

Should that be "represent you **to** Cloudflare for Teams"? Or perhaps "represent you **on** Cloudflare for Teams"?

**Comment by TownLake** [comment]
Thanks for the catch @joncar - fix on its way.
