### ISSUE TITLE
Mention that x-amz-checksum-algorithm is not available

### ISSUE THREAD

**Issue by Southclaws** [cloudflare/cloudflare-docs#10623]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/api/s3/api/

### What changes are you suggesting?

After quite a bit of debugging I realised that we cannot use R2 yet because of this missing feature. Essentially, the lack of this feature means that clients must calculate a hash, which for some use-cases is a huge memory burden as it means reading the entire stream into memory before passing it on to R2.

Definitely worth noting in the docs that this header is not available on R2.

### Additional information

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

**Comment by kodster28** [comment]
Duplicated in #13132
(closing this one b/c that one will be fresher / more visible as it's closer to the top)
