### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by itslevir** [cloudflare/cloudflare-docs#1064]
I'm not sure about cloudflare's internal info, but it seems like workers sites is being phased out for cloudflare pages (workers.cloudflare.com/sites auto-redirects to cloudflare pages.) Should documentation be updated for cloudflare pages? (I already tried to deploy with cf pages, get a couple npm errors) Is there still some way to deploy with cloudflare workers?  
I'm curious, and I'd be happy to update cloudflare's developer docs on the docs engine if I get enough info about it.

**Comment by KimJ15** [comment]
👋 @lerichardson Hi there. I'm sorry, we only take care documentation recommendations for developers.cloudflare.com in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance with your deployment.
