### ISSUE TITLE
Ability to choose or disable preview branch

### ISSUE THREAD

**Issue by kelvinz** [cloudflare/cloudflare-docs#1066]
My development branch has way too many commits and each commit is causing a build. Is there any way to turn off the preview branch or at least select which branch should be used for preview?

**Comment by KimJ15** [comment]
👋 @kelvinz  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
