### ISSUE TITLE
Warp Cloudflare Cert installation - documentation issue

### ISSUE THREAD

**Issue by neilsmith** [cloudflare/cloudflare-docs#1067]
On this page:

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert#base-operating-system

it's recommended that you run this line to install the Cloudflare certificate in your terminal:

`sudo cat Cloudflare_CA.crt >> /usr/local/etc/openssl/cert.pem`

However, I believe the .crt file that's been downloaded is in the binary DER format, and this line would cause a problem concatenating that to a text-based PEM file?

I had success using openssl to convert it first:

`sudo openssl x509 -inform der -in Cloudflare_CA.crt >> /usr/local/etc/openssl/cert.pem`

---

(Although, as a slight aside, using Homebrew on my Mac, the correct cert file for me is /usr/local/etc/openssl@1.1/cert.pem - revealed with `brew info openssl` - but of course I realise it would be hard to get that path correct for all users.)

**Comment by KimJ15** [comment]
@abracchi-tw - here is a recommendation for Cloudflare One.

**Comment by abracchi-tw** [comment]
hi @neilsmith, we're looking into this. Thanks for bringing it up!

**Comment by kkrum** [comment]
Hey @neilsmith I've verified on my machine this step is not actually required as part of the process. We think it accidently was added as part of an early internal dogfood but it can be safely skipped. I am working to verify on one more machine and the if so will remove the step.

Thanks for bringing this to our attention
