### ISSUE TITLE
Turnstile FAQ Dummy keys

### ISSUE THREAD

**Issue by garretcharp** [cloudflare/cloudflare-docs#10681]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

- https://developers.cloudflare.com/turnstile/frequently-asked-questions/#can-i-use-turnstile-when-developing-locally

### What changes are you suggesting?

Add a link to all the test keys. The FAQ currently says

> The dummy sitekeys provided below can be used from any domain, including on localhost.

But then does not list the keys or link to the keys (https://developers.cloudflare.com/turnstile/reference/testing/)

**Comment by patriciasantaana** [comment]
Hi @garretcharp ! Thanks for bringing this to our attention. I will be closing this issue now as it has been addressed.
