### ISSUE TITLE
[workers] update v2 to v3 migration guide to reflect dev workflow changes

### ISSUE THREAD

**Issue by admah** [cloudflare/cloudflare-docs#10721]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/migration/update-v2-to-v3

### What changes are you suggesting?

- update workflow changes to persist and storage in `wrangler dev`
- update binding experience expectations in `wrangler dev`

**Comment by KimJ15** [comment]
The documentation points to updated instructions.
