### ISSUE TITLE
Links Should Open In A New Tab

### ISSUE THREAD

**Issue by mackenly** [cloudflare/cloudflare-docs#1075]
### Expected Behavior
https://developers.cloudflare.com/workers/get-started/guide#1-sign-up-for-a-workers-account
I'd expect that clicking Sign Up would open in a new tab so that I can continue to follow along.

### Actual Behavior
When you press Sign Up it opens in the same tab.

### Section that requires update
https://developers.cloudflare.com/workers/get-started/guide#1-sign-up-for-a-workers-account
The Sign Up button. Other areas may have the same issue though. Haven't tried them all.

### Additional information
![image](https://user-images.githubusercontent.com/53151058/113811089-91348380-9739-11eb-857d-062e7cf6e2ee.png)

**Comment by jrf0110** [comment]
Hey there, @mackenly - I appreciate the issue! I generally dislike target=_blank from a UX perspective (who are _you_ Mr. Website to dictate what window my links open in!) - I'm going to defer to Chris Coyer on this one https://css-tricks.com/use-target_blank/
