### ISSUE TITLE
Add language to pages docs to explain caveat on custom domains

### ISSUE THREAD

**Issue by anthonygrimes** [cloudflare/cloudflare-docs#1076]
### Expected Behavior
When adding custom domains (or subdomains) for Cloudflare pages hosted sites, it should be clear that their is a prerequisite on adding the domain to the Cloudflare pages dashboard.

### Actual Behavior
It is not clear to the user that not adding a custom domain (or subdomains) to the Cloudflare Dashboard will fail to resolve if you only associate it via a CNAME record.

### Section that requires update
[This section](https://developers.cloudflare.com/pages/getting-started#adding-a-custom-domain) requires updating to reflect the explicit addition of the custom domain (or subdomains) to the Cloudflare pages dashboard.

### Additional information
N/A

**Comment by KimJ15** [comment]
Closing as this will be fixed by #1068.
