### ISSUE TITLE
[kv] Clarify if KV namespace id is to be kept secret

### ISSUE THREAD

**Issue by AdiRishi** [cloudflare/cloudflare-docs#10762]
### Which Cloudflare product does this pertain to?

KV

### Existing documentation URL(s)

- https://developers.cloudflare.com/kv/learning/kv-namespaces/
- https://developers.cloudflare.com/kv/learning/kv-bindings/

### What changes are you suggesting?

- It's been a question swirling in my mind on whether or not KV namespace ids are limited to a specific account
- E.g if I commit a namespace id to a public repository, will someone else be able to bind their worker to my kv namespace?
- Although I'm almost certain these are account specific, I feel like this is worth clarifying in the docs

**Comment by Maddy-Cloudflare** [comment]
I added a note in the docs to address your questions, I hope it helps. https://developers.cloudflare.com/kv/learning/kv-namespaces/
