### ISSUE TITLE
Add missing pages product to README

### ISSUE THREAD

**Issue by anthonygrimes** [cloudflare/cloudflare-docs#1078]
### Expected Behavior
When navigating to the README.md I expect to see a complete listing of all products.

### Actual Behavior
When navigating to the README.md I do not see the product listing for the Pages product.

### Section that requires update
[This section](https://github.com/cloudflare/cloudflare-docs#products) requires updating to reflect the complete list of products, including Cloudfare Pages.

### Additional information
N/A

**Comment by KimJ15** [comment]
Closing as a duplicate of https://github.com/cloudflare/cloudflare-docs/pull/1079
