### ISSUE TITLE
1.1.1.1 Android Setup Page Missing DoT Domains for 1.1.1.1 Family

### ISSUE THREAD

**Issue by BRBsoup** [cloudflare/cloudflare-docs#10804]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

Information missing here:
https://developers.cloudflare.com/1.1.1.1/setup/android/

Yet included here:
https://developers.cloudflare.com/1.1.1.1/setup/#dns-over-tls-dot

### What changes are you suggesting?

Older sources all indicate that 1.1.1.1 For Families does not or only partially supports the Android Private DNS DoT capability, though there are official sources (cloudfare employees) who specifically claim that those domains (security.cloudfare-dns.com and family.cloudfare-dns.com) work for DoT in response to questions and discussion on Android Private DNS.

### Additional information

Please refer to this answer and entire thread:

https://community.cloudflare.com/t/1-1-1-3-does-not-filter-content-if-queries-are-made-via-dot-dns-over-tls/167730/33

_No response_

**Comment by RebeccaTamachiro** [comment]
Hi @BRBsoup 👋 
Thank you for flagging this. The 1.1.1.1 Android setup page has been updated.
