### ISSUE TITLE
Build Command when using Functions

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/cloudflare-docs#10841]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

- [Framework Presets](https://developers.cloudflare.com/pages/platform/build-configuration/#framework-presets)

### What changes are you suggesting?

Currently, the framework presets section notes that
> If you are not using a framework, leave the Build command field blank.

This is fine if the project is fully static. However, if the project contains functions that rely on external dependencies(installed via NPM, PNPM, Yarn, etc.), then that install command will not run, and the functions build will fail.

Update should clarify that a build command is needed to trigger an install, or, if possible, have the build image install dependencies when functions and a `package.json` are detected(which would outside the scope of this repo).

**Comment by kkukshtel** [comment]
I also encountered this (I had no build command and didn't need one). Setting the build command to just be `echo "Hello World!"` as @helloimalastair suggested on the Discord fixed it. Which is insane lol.

**Comment by kkukshtel** [comment]
@deadlypants1973 Can you provide clarity on if we can remove the echo statement from the build commands now?

**Comment by helloimalastair** [comment]
@kkukshtel the changes to the documentation here reflect no changes in functionality. You can keep the echo statement, or use the `exit 0` now suggested. Any command that is a noop should work, as you just need something present to trigger an installation.
