### ISSUE TITLE
copying codeblocks on firefox missing newlines within paragraphs 

### ISSUE THREAD

**Issue by taylorlee** [cloudflare/cloudflare-docs#1088]
### Expected Behavior
Copying codeblocks on Chrome works well. For example, https://developers.cloudflare.com/workers/learning/using-durable-objects#accessing-persistent-storage-from-a-durable-object is copied as 
```js
export class DurableObjectExample {
    constructor(state, env) {
        this.state = state;
    }

    async fetch(request) {
        let ip = request.headers.get('CF-Connecting-IP');
        let data = await request.text();
        let storagePromise = this.state.storage.put(ip, data);
        await storagePromise;
        return new Response(ip + ' stored ' + data);
    }

}
```
Copying on firefox should be the same. 

### Actual Behavior
On firefox, there are no newlines within paragraphs. The above example gets copied as 3 lines:
```js
export class DurableObjectExample {    constructor(state, env) {        this.state = state;    }
    async fetch(request) {        let ip = request.headers.get('CF-Connecting-IP');        let data = await request.text();        let storagePromise = this.state.storage.put(ip, data);        await storagePromise;        return new Response(ip + ' stored ' + data);    }
}
```
Sometimes these can be fixed afterwards with code formattters, but sometimes not (especially for whitespace sensitive languages like python).

### Section that requires update
??? Any section with a `<pre class="CodeBlock">` element.

**Comment by KimJ15** [comment]
@jrf0110 Added engineering label. Can we have an engineer who knows more about how the Docs Engine work look at it this request and maybe open an issue in that repo?

**Comment by KimJ15** [comment]
Thanks for submitting this issue @taylorlee. I created a Jira ticket for the appropriate supporting team and will close this out.
MRK-13547
