### ISSUE TITLE
Add clarifying details for editing sshd_config for short lived certs docs

### ISSUE THREAD

**Issue by benatsb** [cloudflare/cloudflare-docs#10885]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates

### What changes are you suggesting?

Clarifications directly related to editing the `sshd_config` file to support short lived certificate capabilities.

Some extra wording to clarify how and what to add.

Add in explicit note that the `match` block for user reads to either a) the end of the document or b) the start of a new match block. Just a clarification here might save someone else from adding their match block to the center of `sshd_config` and then troubleshooting why copy-paste didn't work. 😄 

> Introduces a conditional block. If all of the criteria on the Match line are satisfied, the keywords on the following lines override those set in the global section of the config file, until either another Match line or the end of the file.

[man sshd_config](https://linux.die.net/man/5/sshd_config#:~:text=sshd_config%20%285%29%20-%20Linux%20man%20page%20Name%20sshd_config,The%20file%20contains%20keyword-argument%20pairs%2C%20one%20per%20line.)

Also running `sshd -t` to verify the file integrity is very helpful.

**Comment by KimJ15** [comment]
Hi there - This is a feature request that the product team would need to review, not just a documentation request! Closing this out and informing the product team of this request!
