### ISSUE TITLE
Email Verification Broken

### ISSUE THREAD

**Issue by switchupcb** [cloudflare/cloudflare-docs#10889]
### Example URL(s)

https://developers.cloudflare.com/fundamentals/setup/account-setup/verify-email-address/#verification-issues

### Actual Behavior

Clicking the link in a different browser or an incognito window doesn't fix the verification issues of a new user.

### Expected Behavior

Clicking the link in a different browser or an incognito window fixes the verification issues of a new user.

### Additional information

I attempted to help someone create an account who faced this issue.

Relevant Community Forum Posts:
- https://community.cloudflare.com/t/i-cannot-verify-my-email-address/557345
- https://community.cloudflare.com/t/cant-verify-email-address-this-link-is-not-valid/556119
- https://community.cloudflare.com/t/this-link-is-not-valid/542968
- https://community.cloudflare.com/t/receiving-this-link-is-not-valid-attempting-email-verification/331860
- https://community.cloudflare.com/t/cloudflare-account-cannot-verify-email/331388
- https://community.cloudflare.com/t/cant-verify-my-email-address/264033

**Comment by switchupcb** [comment]
Their issue was solved in the context of this post: https://community.cloudflare.com/t/i-cannot-verify-my-email-address/557345.

You could revise the flow so user's aren't prompted to send verification emails while verified, or change the message that the user sees when a verified user clicks a verification link.

**Comment by kodster28** [comment]
Raised a ticket internally for our dash team + added a bit more context to the docs.

Thanks for raising, @switchupcb.
