### ISSUE TITLE
Improve

### ISSUE THREAD

**Issue by ytbigvinny27** [cloudflare/cloudflare-docs#1100]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by KimJ15** [comment]
Thank you for the feedback. I'm going to close it now, but feel free to open a new issue or ask any questions.
