### ISSUE TITLE
Email Event Handler runtime docs

### ISSUE THREAD

**Issue by FacundoLucci** [cloudflare/cloudflare-docs#11027]
### Example URL(s)

https://developers.cloudflare.com/email-routing/email-workers/

### Actual Behavior

Clicking the link to runtime api for email handler routes to https://developers.cloudflare.com/email-routing/email-workers/

### Expected Behavior

It used to go to doc page with description of the email event handler

**Comment by deadlypants1973** [comment]
fixed by #11043 ?
