### ISSUE TITLE
Ai model deployment, can we deploy our models to cloudflare?

### ISSUE THREAD

**Issue by syonfox** [cloudflare/cloudflare-docs#11039]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

AI workers

### Content Location

https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers-ai/models/embedding.md

### Additional information

Hello I'm exited to play around with the new workers AIon Edge GPU 

can you point me in the right direction for any blog on the infrastructure and performance of your implementation?

I'm also wondering if there are plans for allowing users to create their own ai models rather than use a list of provided ones. 

Ideally, we could define a repository or module and deploy it to Cloudflare before then being able to use it in our workers without needing a backend at all :) 

How to deploy a custom model / explicitly state it's not possible yet but planned ;) 

Thanks for the awesome platform and all your great work, this is definitely revolutionizing the way we create high-performance scalable apps 

Happy coding!

**Comment by pdwittig** [comment]
Hey @syonfox. We don't currently support bring your own model, but likely will in the mid-term future. Out of curiosity, what kind of custom models are you using and how does that fit into your product/workflow/use case.

Also, we're in early innings and dont have anything published re infra/performance, but curious what you're looking for there as well.

Lmk. Thanks.

**Comment by davystrong** [comment]
@pdwittig can you give any indication of when this is likely to be supported?

**Comment by syonfox** [comment]
I was thinking of the instruct embedding model for my platform as well as
hosting domain specific fine tuned lama models.

It would also be usefully to have a yolo based image classifier and general
purpose object detection.  A little more notch but a segmentation model
would also be useful

**Comment by jvel07** [comment]
@pdwittig any dates on when custom models will be supported?
I'd like to host a generative app but not sure how to use GPU resources on Cloudfare other than workers AI, which currently, doesn't support custom ML inference pipelines.

**Comment by kodster28** [comment]
Howdy @syonfox, checked internally and these are on the roadmap... but no firm timeline.

Closing out this issue specifically, but keep an eye on the [Workers AI changelog](https://developers.cloudflare.com/changelog/?product=workers+ai) and [Changelog RSS feed](https://developers.cloudflare.com/workers-ai/changelog/index.xml) to see when it hits.
