### ISSUE TITLE
Documentation example is out of date

### ISSUE THREAD

**Issue by chrisribe** [cloudflare/cloudflare-docs#11049]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

This page suggest code to be used for bindings but the import is invalid
https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/#use-bindings-in-your-astro-application

Code:
```
import { getRuntime } from "@astrojs/cloudflare/runtime";
```
Results in typscript errors
```
Cannot find module '@astrojs/cloudflare/runtime' or its corresponding type declarations
```
This seems to be the same issue as https://github.com/withastro/astro/issues/5222

### What changes are you suggesting?

Re-open the original issue or suggest the workaround.

**Comment by dario-piotrowicz** [comment]
Hi @chrisribe thanks for the issue 🙂

Sorry for the very late, anyways it looks like that the invalid import has been removed from the docs in https://github.com/cloudflare/cloudflare-docs/pull/10881, the current imports seem all to be valid (I just did double checked that)

So I think it should all good now and I think this issue can be closed, please let me know if you disagree 🙂

**Comment by chrisribe** [comment]
Yeah the docs where updated a bit later.
Thanks for taking the time to reply
