### ISSUE TITLE
Content type application/rss+xml listed as /xml+rss

### ISSUE THREAD

**Issue by claudiobrandt** [cloudflare/cloudflare-docs#11046]
### Which Cloudflare product does this pertain to?

Speed

### Existing documentation URL(s)

https://developers.cloudflare.com/speed/optimization/content/brotli/content-compression/

### What changes are you suggesting?

The page lists all content types that can be compressed with Gzip or Brotli by Cloudflare.

The official content type for RSS feed is:

`application/rss+xml` (and not `application/xml+rss` as is currently appearing on the page)

Source: https://www.rssboard.org/rss-mime-type-application.txt

**Comment by angelampcosta** [comment]
@claudiobrandt  Thank you for pointing this out. https://github.com/cloudflare/cloudflare-docs/pull/11054 updated the docs.
