### ISSUE TITLE
Documentation appears to contradict when workers run - please clarify

### ISSUE THREAD

**Issue by goblinfactory** [cloudflare/cloudflare-docs#11079]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

The following wording in "Fine print" is confusing and appears to contradict the sequence diagram documentation describing when workers run in the execution pipeline. 

The specific phrase that is confusing is this one ->  "**Since Cloudflare Workers runs before the Cloudflare cache**," 

Link to documentation
https://developers.cloudflare.com/workers/platform/pricing#fine-print

Afaik, there is no link to the sequence diagram, it is only visible if you open a worker and enter full screen. Even a slightly smaller window will often cause the sequence diagram to be hidden. **This is also probably a design flaw and should always be visible due to the amount of information that sequence diagram provides that is not available anywhere else.**

Screenshot of the worker sequence diagram below;
<img width="1023" alt="Screenshot 2023-10-04 at 14 23 25" src="https://github.com/cloudflare/cloudflare-docs/assets/1073487/ee360ee2-945a-43bc-8ad6-232f1b146d7d">

I'm sure this is probably just a misunderstanding on my part.

**Some background;**
This ended up being quite important for me to understand, since I am currently trying to debug an issue with a spike test worker that is unable to return content that ever gets cached by Cloudflare CDN. (seperate issue I know, but my point is that when i asked the community about this issue I was told that the worker will always run and it runs before the cache. I could not verify that claim and the only two places in the documentation that reference exactly WHEN it runs, appear to contradict each other. 

**Trace documentation**
Sorry, just realised, there is a third piece of documentation (I'm sure there are many) just the extra one I managed to find referencing the sequence was in the new beta TRACE tool which says that if a worker processes a requedst then 

this page : https://developers.cloudflare.com/fundamentals/basic-tasks/trace-request/

This page references Workers, but no workers trace information is returned. I tested this by tracing https://bugs.co.za/not-cached/foo.txt. This is important, because I could have used the output from trace to answer the question of when the workers run in the pipeline.

Screenshot of documentation from new beta TRACE tool;
<img width="732" alt="Screenshot 2023-10-04 at 14 48 09" src="https://github.com/cloudflare/cloudflare-docs/assets/1073487/430218d9-003f-4962-b6c7-8302d1da86af">

Any help clarifying this will be massively appreciated, thanks
Alan

### What changes are you suggesting?

1. Update all the texts to remove the ambiguity or apparent contradictions.
2. Update beta trace tool to show worker script executions in the output. So that the tool can be used side by side with the pipeline documentation
3. Update the worker pipeline documentation's responsive design (CSS?) so that the pipeline documentation is either always available, or when not visible, some other means e.g. a prominent button or a link to the pipeline documentation is displayed.
4. Add the worker pipeline (sequence diagram) as a first class citizen and documentation heading. i.e. make it a key concept and important part of the worker documentation so that it can be kept up to date, and referenced by developers, since in my opionion, this is a core and critical concept to understand.

**Comment by deadlypants1973** [comment]
hey @goblinfactory , thank you for submitting this issue. Workers do run before the cache! That cache learning page has been updated to remove the incorrect wording. It seems the Trace docs have been updated correctly as well. 

In regard to the diagram, after speaking to eng, cache rules do run in that particular order as it is at that stage that they are evaluated. You'll notice header modification is a few lines below. A example of this flow is if a user were writing a Cache Rule which matches particular headers: it would be crucial to know that the Cache Rule expression will see headers potentially modified by Page Rules or Origin Rules.

I am filing a ticket with design to judge whether it would be appropriate to put cache next to or after Workers in that flow.

:)

**Comment by goblinfactory** [comment]
Having a simple diagram that I can know to always be true helps set a foundation of facts that i can internalise and help me understand the more complex topics that are explained with longer paragraphs. Thank you for pursuing this; much appreciated, Alan 
_( I notice the "close" button is enabled for me. Will you close this when it's done, or am I as the OP supposed to close it? )_
