### ISSUE TITLE
[Cloudflare pages] Allow to use the same repository in multiple projects

### ISSUE THREAD

**Issue by MarlonLuan** [cloudflare/cloudflare-docs#1111]
### Expected Behavior
Cloudflare pages could allow using the same repository across multiple projects

### Actual Behavior
Currently the option is disabled, "in use" appears

### Section that requires update
https://dash.cloudflare.com/.../pages/new

### Additional information
I have in a single repository, several projects in subdirectories, each corresponding to a different site, this option would be important for me not to need to create several different repositories, each containing a single site

**Comment by KimJ15** [comment]
👋 @MarlonLuan  I'm sorry, we only take care of developers.cloudflare.com documentation requests in this repo! Please reach out to community.cloudflare.com for support.
