### ISSUE TITLE
Add Documentation for Controlling AI Temperature and Related AI Settings

### ISSUE THREAD

**Issue by burgil** [cloudflare/cloudflare-docs#11138]
### Which Cloudflare product(s) does this pertain to?

Workers AI

### Subject Matter

I would like to request documentation that explains how to control the AI temperature and other related AI settings when using the Cloudflare AI service.

### Content Location

This addition should be placed in the Workers documentation, specifically in the section that discusses how to interact with the Cloudflare AI service.
This should be a new section within the existing document that covers Cloudflare AI integration in Workers.

### Additional information

```js
export interface Env {
  AI: {
    modelId: string;
    temperature?: number; // Add temperature option
    maxTokens?: number;  // Add maxTokens option
    // Add other AI-related options here as needed
  };
}
```

As part of the Workers documentation, it would be helpful to have a dedicated section that explains how to set and use the AI temperature option and other relevant AI settings when making requests to the Cloudflare AI service. This would allow developers to have finer control over the behavior of the AI responses.

The documentation should include:

An explanation of what the AI temperature setting does.
How to set the AI temperature and other related options in the environment configuration.
Examples of how to use these options in a Workers script.
Any best practices or considerations when adjusting these settings.
This addition will be beneficial for developers who want to customize the behavior of the Cloudflare AI service according to their specific requirements.

Thank you for considering this request.

**Comment by burgil** [comment]
```js
import { Ai } from '@cloudflare/ai';

export interface Env {
  AI: {
    modelId: string;
    temperature?: number; // Add temperature option
    maxTokens?: number;  // Add maxTokens option
    // Add other AI-related options here as needed
  };
}

export default {
  async fetch(request: Request, env: Env) {
    const { modelId, temperature, maxTokens, ...otherOptions } = env.AI;
    const ai = new Ai({ modelId, temperature, maxTokens, ...otherOptions });

    const messages = [
      { role: 'system', content: 'You are a friendly assistant' },
      { role: 'user', content: 'What is the origin of the phrase Hello, World' }
    ];

    const response = await ai.run(modelId, { messages, temperature, maxTokens });

    return Response.json(response);
  },
};
```

**Comment by pdwittig** [comment]
Thanks for the feedback. Our current API does not currently support passing any optional params into the llama model, and that's why it's not documented at the moment. That said, it's on the roadmap!

**Comment by burgil** [comment]
@irvinebroque is this completed?

**Comment by boxabirds** [comment]
Wow interesting -- customising temperature and output format is pretty standard -- I'd call this service alpha until it's feature complete to offer these settings.

**Comment by milaforge** [comment]
Hey, thanks for your great work, it is clean and easy to work with.

I wish I could adjust the temperature of the Model, is it not still possible?
