### ISSUE TITLE
Dark theme of site doesn't automatically sync with OS/browser theme

### ISSUE THREAD

**Issue by rakleed** [cloudflare/cloudflare-docs#11156]
### Example URL(s)

https://developers.cloudflare.com/

### Actual Behavior

The dark theme of the site does not automatically sync with the OS/browser theme. For example, if you use the dark theme on macOS and use the Chrome browser, the Cloudflare Docs site still appears in the light theme.

### Expected Behavior

The dark theme of the site automatically syncs with the OS/browser theme. For example, when using the dark theme on macOS and the Chrome browser, the Cloudflare Docs site appears in the dark theme automatically.

**Comment by haleycode** [comment]
Thanks so much for this feedback, @rakleed! We'll raise an internal ticket to track this and close out the Github Issue for now.
