### ISSUE TITLE
AI example whisper not work

### ISSUE THREAD

**Issue by cheluskin** [cloudflare/cloudflare-docs#11153]
### Example URL(s)

curl https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/run/@cf/openai/whisper \
  -X POST \
  -H "Authorization: Bearer {API_TOKEN}" \
  --data-binary @talking-llama.mp3

### Actual Behavior

"errors":[{"code":7009,"message":"Upstream service unavailable"}]

### Expected Behavior

text in response

**Comment by Andy963** [comment]
same response

**Comment by kodster28** [comment]
Howdy @cheluskin, not sure this was the cause... but we did recently update our [models docs](https://developers.cloudflare.com/workers-ai/models/whisper/) with new examples.

Though maybe it sounds like this was related to availability issues in the CF service itself, which I'll pass along internally.

Going to close out the issue though, as this is a docs repo and we can't do much about the availability of a service (other than what I mentioned above).
