### ISSUE TITLE
O chat Brasil está com o erro 522

### ISSUE THREAD

**Issue by Maryyyzx** [cloudflare/cloudflare-docs#11154]
### Example URL(s)

www.chatbrasil.top

### Actual Behavior

tento entrar no site e está dizendo que está com erro 522

### Expected Behavior

Quero que o site volte o mais rápido possível

**Comment by WalshyDev** [comment]
Please visit our [community forums](https://community.cloudflare.com/) for community support or open a support ticket if you can.
