### ISSUE TITLE
Create a Health Check - "Health change thresholds" option does not exist

### ISSUE THREAD

**Issue by Techsurfer1981** [cloudflare/cloudflare-docs#11171]
### Which Cloudflare product does this pertain to?

Health Checks

### Existing documentation URL(s)

- https://developers.cloudflare.com/health-checks/get-started/#create-a-health-check

### What changes are you suggesting?

It is mentioned:

> * **Health change thresholds**, which specify the number of consecutive passed or failed checks before an origin changes status.

However, the "_Health change thresholds_" option does not exist upon creating a health check.
Instead, I believe this is referencing the "**Retries**" option:

![health checks retries](https://github.com/cloudflare/cloudflare-docs/assets/90766559/8837fc19-6183-4420-9dc1-2c217ab3c156)

Hence, the documentation should rather state:

> * **Retries**, which specify the number of consecutive passed or failed checks before an origin changes status.

**Comment by kodster28** [comment]
Thanks for raising, @Techsurfer1981. Should be fixed whenever the latest build goes live.
