### ISSUE TITLE
Rate limiting characteristics availability imparity

### ISSUE THREAD

**Issue by Joelsz** [cloudflare/cloudflare-docs#11185]
### Example URL(s)

Link 1: https://developers.cloudflare.com/waf/rate-limiting-rules/parameters/
Link 2: https://developers.cloudflare.com/waf/rate-limiting-rules/#availability

### Actual Behavior

On the following page (link 1) there are several values listed as an option for the Rate Limiting Rule "With the same characteristics..." section, including IP, Header Value, Response Body end more. However, under availability of features (link 2), only IP and IP With NAT Support is listed.

### Expected Behavior

List all available values in the availability table.

**Comment by pedrosousa** [comment]
Hi @Joelsz 
Perhaps you are not looking at the last column in the "Availability" table?

The column header is "Enterprise with Advanced Rate Limiting", and the counting characteristics include the characteristics mentioned on the first page you linked to:

![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/efe46825-6413-48f8-aca5-f06316fce1d2)

**Comment by Joelsz** [comment]
Thanks for clarifying @pedrosousa , the last column is hidden on my screen and didn't notice the side scrolling.

Are there any plans of making the Advanced Rate Limiting capabilities (query, header, etc.) available for the Business plan?

**Comment by Joelsz** [comment]
![Screenshot_20231010-085134](https://github.com/cloudflare/cloudflare-docs/assets/6243173/84d94415-1f50-44e9-9330-458d54079f11)

**Comment by pedrosousa** [comment]
> Are there any plans of making the Advanced Rate Limiting capabilities (query, header, etc.) available for the Business plan?

I can only provide my own view on this matter. I don't think this will happen soon, given that not even all Enterprise customers have access to it.
You can follow the [Cloudflare blog](https://blog.cloudflare.com/) for any updates on Cloudflare's rate limiting features.
