### ISSUE TITLE
Supported Python versions are unclear

### ISSUE THREAD

**Issue by sound-davo** [cloudflare/cloudflare-docs#1119]
### Expected Behavior
As per the [CloudFlare documentation](https://developers.cloudflare.com/pages/platform/build-configuration#language-support-and-tools), I should be able to set `python-3.7` in `runtime.txt` *OR* there should be a list of supported python versions somewhere.

### Actual Behavior
I tried several iterations to find a version that would work, to no avail:

```
12:17:36.031 | Initializing build environment. This may take up to a few minutes to complete
-- | --
12:18:26.970 | Success: Finished initializing build environment
12:18:26.970 | Cloning repository...
12:18:31.794 | Success: Finished cloning repository files
12:18:32.694 | Installing dependencies
12:18:32.696 | /opt/build/bin/run-build-functions.sh: line 168: /opt/buildhome/pythonpython-3.6/bin/activate: No such file or directory
12:18:32.696 | Error setting python version from runtime.txt
12:18:32.697 | Please see https://github.com/netlify/build-image/#included-software for current versions
12:18:32.697 | Failed: build command exited with code: 1
```

I initially tried `python-3.7`, and `python-3.7.x`.

### Section that requires update
I couldn't find a link to any of:
1. Which build image CloudFlare is using (Are you using Ubuntu? trusty or xenial?)
2. Which python versions the default build image supports.
3. The correct syntax for `runtime.txt` is `python-3.7` valid? What about `python-3.7.x` or do I need to specify `python-3.7.<versionInstalledOnTheCloudFlareBuildImage`.

### Additional information
Kinda hilarious that you seem to have "borrowed" one of Netlify's build images based on the link to their documentation in the build output.

**Comment by kristianfreeman** [comment]
hey @sound-davo, we're investigating this with some community members who use python as part of their build process, hope to have some answers for you in regards to `runtime.txt` - in the meantime, you should be able to set `PYTHON_VERSION` as an environment variable to the version you need for your project!

**Comment by kristianfreeman** [comment]
just to follow up on this - after some testing, we've found that you should specify the runtime.txt format _without_ the `python-` prefix, such as `3.7` instead of `python-3.7`. hope this helps!

thanks @jb3 for help debugging this!

**Comment by amithm7** [comment]
@signalnerve It would be great if versions of languages and tools be listed on this docs page: https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/platform/build-configuration.md

Assuming this is the build config: https://github.com/netlify/build-image/blob/xenial/included_software.md , this maybe linked too if possible.

The build error log rather shows a defunct page: `Please see https://github.com/netlify/build-image/#included-software for current versions`.

I had to play with 3.9, 3.6, 3, 3.8 and then finally figure out that 3.7 works.

**Comment by Brawl345** [comment]
Bumping this as I ran into exactly the same issues. First tried `python-3.10.4` then saw that I don't need the "python" part and played with 3.9, 3.8 until finally 3.7 worked. Would be great if this was listed somewhere!

Ah there is issue #3759 for this.
