### ISSUE TITLE
Blocked from Aternos site

### ISSUE THREAD

**Issue by RJackalH** [cloudflare/cloudflare-docs#11237]
### Example URL(s)

https://aternos.org/software/vanilla/

### Actual Behavior

It seems like when loading / changing site too fast results in a block

8148955a7f45beea

### Expected Behavior

I would like it to operate normally and allow my son to load a server

### Additional information

heisejrh@gmail.com

**Comment by kodster28** [comment]
Howdy @RJackalH, unfortunately we (as Cloudflare) and then our team (specifically a docs team) doesn't have the ability to act on this request.

Your best response is to contact the owner of the site and provide them with the ray ID as well.
