### ISSUE TITLE
GitHub Actions workflow to block CI if files have been moved but redirects haven't been added

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#11239]
### Which Cloudflare product(s) does this pertain to?

Style Guide

### Subject Matter

N/A

### Content Location

Whilst there is a link crawler that will alert you to dead links on the docs pages, there is nothing that stops a user from moving pages, updating links but not adding a redirect - meaning third party links (i.e search engines) will 404.

As an example, https://github.com/cloudflare/cloudflare-docs/pull/11162/ moved `/workers/runtime-apis/websockets/websockets.md` and `/workers/runtime-apis/websockets/use-websockets.md` but did not add a redirect.

This means that https://developers.cloudflare.com/workers/runtime-apis/websockets/use-websockets/ and https://developers.cloudflare.com/workers/runtime-apis/websockets/websockets/ are both dead links.

Maybe this could leverage Git's own heuristics to figure out if a file has been moved? There may be false positives with that, or sufficiently changed files that it doesn't recognize, but it would be beneficial nonetheless.

**Comment by KianNH** [comment]
cc @kodster28

**Comment by kodster28** [comment]
This has come up quite a bit recently.

a) Thanks for the fix!
b) I need to noodle on this a bit. As discussed in [this comment](https://github.com/cloudflare/cloudflare-docs/pull/11192#issuecomment-1755677967), this gets a bit hard b/c Pages supports dynamic redirects (and we use them quite a bit + wouldn't want to discourage them as an action). My initial thought would be an MVP that just comments on the PR with a checklist for all the changed / deleted files.

cc: @WalshyDev for any additional thoughts

**Comment by Erisa** [comment]
> My initial thought would be an MVP that just comments on the PR with a checklist for all the changed / deleted files.

I would love this

**Comment by kodster28** [comment]
Gotcha. Let me block off some time Friday and see how far I can get.

**Comment by WalshyDev** [comment]
I like the MVP idea.

We can just make the removal check work fully though. Supporting dynamic redirects isn't too hard, if we need any Pages code it's open source :^) - though we probably won't

Happy to contribute some eng resources for that or to help with the MVP if you need Kody :)

**Comment by kodster28** [comment]
I think I'm good on the MVP. If that gets up and we get more requests around this, might circle back to take you up on this offer though.

**Comment by kodster28** [comment]
cc @irvinebroque

**Comment by kodster28** [comment]
Note that this may not work on the `/support/` section because their filenames are non-standard.
