### ISSUE TITLE
Unclear how what exactly is returned by kv.put-

### ISSUE THREAD

**Issue by syonfox** [cloudflare/cloudflare-docs#11267]
### Which Cloudflare product(s) does this pertain to?

KV

### Subject Matter

worker kv binding put

### Content Location

Unclear how what exactly is returned 
https://github.com/cloudflare/cloudflare-docs/blob/cd3f02d391ce643ef651d373ae116f1fa27164ba/content/kv/api/write-key-value-pairs.md?plain=1#L30

It's unclear if I need to consider anything special 

maybe something like 

a void promise is returned the resolving of this signified a successful write and this local worker can now `get`

this should never fail but if it does it will throw an error so you should catch that. 

or maybe this never throws and simply will not resolve. 

is kv.put GARUNTEED to resolve. can the end developer omit the .catch(retry) logic?

aka by example
```js
let putReturn = await kv.put("mykey", "mydata")
// ok we are 100% good this code canot fail

//or do we need .catch(retryLogicHere)

//or do we need if(putReturn != 0) {retryLogicHere}
```

Thanks, happy coding

**Comment by Maddy-Cloudflare** [comment]
@syonfox are you asking what the `put()` method returns?

**Comment by syonfox** [comment]
yes in a sense. IM asking if put implements retry logic and is guaranteed to not throw an error and eventually resolve the promise or if there is a possibility of it failing and the end developer needing to do some retry logic.

as far as I can tell it resolves an empty promise aka return 0 / falsy if you are a c person. 

I would like to know if there are any failure modes to this or if its safe to assume any resolve means a succesfull push/put

**Comment by syonfox** [comment]
an a documentation level it would be nice to know A: what is resolved explicitly resolve(0) maybe

and B: if it is possible for put to throw an error

**Comment by Maddy-Cloudflare** [comment]
> an a documentation level it would be nice to know A: what is resolved explicitly resolve(0) maybe
> 
> and B: if it is possible for put to throw an error

PUT operations can fail. If you need to ensure that the operation succeeds, then you will need to retry.

Does this answer all your questions and concerns? Let me know!

**Comment by syonfox** [comment]
How does it fail by throwing an error; 

or returning a non-falsy exit code?

If you can track down the code that would be nice not sure where it is internally but we we find a good answer then its worth mentioning a one-liner in the documentation as that someone first refrence point to KV

**Comment by syonfox** [comment]
Im also sort of wondering why and how put may fail 

my curent understanding is 
```
[worker] ->[edge] -> [central]
put===================> insert
get=======[cache or]====select
```

**Comment by aplunk** [comment]
@syonfox because workerd is open source you can see the behavior yourself here: https://github.com/cloudflare/workerd/blob/main/src/workerd/api/kv.c%2B%2B#L21-L29

**Comment by syonfox** [comment]
Thanks by the looks of that kV will

Resolve undefined on successful key insert

And throw an exception on non 200 network response

Therefore perhaps the documents should say somthing along those lines

```
If resolve continue
Catch -> retry with back off

```
