### ISSUE TITLE
Mirage content security policy documentation seemingly incomplete

### ISSUE THREAD

**Issue by fredericDelaporte** [cloudflare/cloudflare-docs#11278]
### Which Cloudflare product does this pertain to?

Speed

### Existing documentation URL(s)

https://developers.cloudflare.com/speed/optimization/images/mirage/#enable-mirage
https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/#product-requirements

### What changes are you suggesting?

In the "Enable Mirage" section of the mirage documentation, the note about the content security policy does not mention Mirage also uses inline styles and even inline scripts.
There is the same issue in In the "Product requirements" of the "Content Security Policies (CSPs) and Cloudflare" documentation.

So, enabling Mirage on a Web site with a CSP disallowing inline styles and/or inline scripts raises scores of CSP violations, and may have other effects like maybe Mirage issues.

The requirement of a CSP allowing inline styles and scripts for Mirage should be documented, if that is actually a requirement. (Otherwise Mirage should be fixed to cease emitting inline styles or scripts, but then it should likely be reported somewhere else.)

### Additional information

It seems to me Mirage uses inline styles mostly for no-script support, and I rather not enable inline styles, even if it causes no-script support issues. So, if the support of inline styles is somewhat "optional" for Mirage, it would be better to state it in the documentation.

About inline scripts, I have not yet seen averse effects on Mirage of them not being allowed. If that is an optional requirement, it would be good to document it too.

Sample DevTools output on a non-public Web site page with Mirage enabled and a CSP not allowing inline styles and scripts:
![image](https://github.com/cloudflare/cloudflare-docs/assets/12201973/3e2bc498-ae5a-4220-8158-3cb839605be1)

**Comment by throny** [comment]
Bumping this one, as this got relevant for us. It would be great if this would be handled with nonce like the other Cloudflare scripts.

**Comment by KimJ15** [comment]
@angelampcosta mind taking a look?

**Comment by angelampcosta** [comment]
Moving over to @dcpena. Although Mirage is under the Speed docs, it's supported by the Images team.

**Comment by dcpena** [comment]
Thanks for the feedback - We have passed the details of this issue along to the team and it's being tracked internally. Closing this issue for now.
