### ISSUE TITLE
I do not appreciate cloud flare moving my IP address to show in Canada. I livebin Atlanta,Ga. I no way possible was traffic or anything utilizing this platform. Please remove 

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#11288]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/

### What changes are you suggesting?

I want cloudflare to stop firewalling my network and causing any changes to my private network asap. I do no

### Additional information

Need any features or security from this platform. Google is my dns, and I've been having problems receiving incoming messages. Please stop connecting to my device and IP address asap

**Comment by ghost** [comment]
![Screenshot_20231016-010027.png](https://github.com/cloudflare/cloudflare-docs/assets/147713814/5168fed9-b278-4329-b5c7-87ed7945f50e)

Why they heck would I be located in Canada? Is this the reason I'm not receiving my text messages and calls? Please go away

**Comment by haleycode** [comment]
Closing this out since it seems the user account has been deleted.
