### ISSUE TITLE
Turnstile FAQ Visitor Solve Rate explanation doesn’t make sense

### ISSUE THREAD

**Issue by printfn** [cloudflare/cloudflare-docs#11292]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

https://developers.cloudflare.com/turnstile/frequently-asked-questions/#what-is-visitor-solve-rate

### What changes are you suggesting?

This sentence doesn’t really make sense: “Visitor Solve Rate is the percentage of tokens that were issued but have not necessarily been siteverified compared to issued challenges.”

Should it be “… tokens that were ~issued~*solved* but have not …”? The sentence is kind of unclear.

**Comment by patriciasantaana** [comment]
Hi @printfn ! Thank you for the feedback about how we can make improvements with developers.cloudflare.com documentation. Closing this now as the updates are already in-progress.
