### ISSUE TITLE
 serializeAttachments and deserializeAttachment documentation are insufficient 

### ISSUE THREAD

**Issue by hacknlove** [cloudflare/cloudflare-docs#11294]
### Which Cloudflare product does this pertain to?

Durable Objects

### Existing documentation URL(s)

https://developers.cloudflare.com/durable-objects/api/websockets/#serializeattachments-hahahugoshortcode-s7-hbhb

### What changes are you suggesting?

I was not able to make this work at all.

I tried at websocket creation

```js
const { 0: clientWebSocket, 1: serverWebSocket } = new WebSocketPair();

this.state.acceptWebSocket(serverWebSocket, tags);
serverWebSocket.serializeAttachments([value])
```

and at message reception
```js
	async webSocketMessage(ws, msg) {
		ws.serializeAttachments([])
	}
```

It always says: 
```
serializeAttachments is not a function
```

### Additional information

I'm using last version of wrangler: 3.13.1

**Comment by cacheburner** [comment]
Hey sorry will get the docs updated ASAP, the correct method is `serializeAttachment()` no `s` at the end.

Thanks for the report!

**Comment by Maddy-Cloudflare** [comment]
GitHub issue solved on [this PR](https://github.com/cloudflare/cloudflare-docs/pull/11301).

**Comment by zxch3n** [comment]
Why is the doc about serializeAttachment() and deserializeAttachment() removed? They are very useful API methods when using hibernation.

**Comment by LiuN1an** [comment]
> Why is the doc about serializeAttachment() and deserializeAttachment() removed? They are very useful API methods when using hibernation.

Fucking agree. 
I can only understand the use of Attachment by reading Example codes now
