### ISSUE TITLE
update  "Deploy a static WordPress site" page to include regular-folder-upload

### ISSUE THREAD

**Issue by PaoloJr** [cloudflare/cloudflare-docs#11310]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/how-to/deploy-a-wordpress-site/
- https://developers.cloudflare.com/pages/platform/direct-upload/

### What changes are you suggesting?

the  "Deploy a static WordPress site" document omits the fact that it is possible to upload a normal (unzipped) folder in the UI ("Create an application" --> "Deploy a site by uploading your project". It is indeed possible to upload both a zipped and unzipped file. The web-application does mention "...Add a folder or zip file to get started" when executing the task. The "direct-upload" document (posted above) also mentions the capability to upload both zipped and unzipped folders. Attached an image for reference.

Glad to submit a pull-request if needed 👍 
![Screenshot 2023-10-16 170619](https://github.com/cloudflare/cloudflare-docs/assets/57420955/b3442429-a0ec-464e-a26b-5ac1cf5e5e14)

**Comment by deadlypants1973** [comment]
hey @PaoloJr90, the docs already reflect this possibility. It says here in step 4 that you can drop a zip file as part of project setup: https://developers.cloudflare.com/pages/how-to/deploy-a-wordpress-site/#deploy-your-wordpress-site-with-pages But please submit a PR on what you'd like to see if this doesn't help. Thanks :)
