### ISSUE TITLE
Incorrect S3 API in R2 Dashboard 

### ISSUE THREAD

**Issue by htdat** [cloudflare/cloudflare-docs#11313]
### Example URL(s)

https://developers.cloudflare.com/r2/api/s3/presigned-urls/#generate-presigned-urls
https://dash.cloudflare.com/{accountId}/r2/default/buckets/${bucketName}/settings

### Actual Behavior

Here https://developers.cloudflare.com/r2/api/s3/presigned-urls/#generate-presigned-urls is showing something like this to construct S3 API: 

```
const url = new URL(
      `https://${bucketName}.${accountId}.r2.cloudflarestorage.com`
    );
``` 

However, in the R2 dashboard, it's showing something like this: 

```
https://{accountId}.r2.cloudflarestorage.com/{bucketName}
``` 

### Expected Behavior

And... the correct one is the one in the doc (after a lot of testing with 403 errors), not the one in the R2 dashboard page. 

It's so confusing. Please update the R2 dashboard page.

**Comment by kodster28** [comment]
Filed an internal ticket for this, so closing out this external issue (since our team usually doesn't have control of dashboard content). Thanks for raising!
