### ISSUE TITLE
Cloudflare (Argo) Tunnel: Ingress Rules broken link

### ISSUE THREAD

**Issue by joel0** [cloudflare/cloudflare-docs#1132]
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress#supported-protocols

The Supported Protocols section of the Ingress Rules page has a link for "list of supported protocols" which links to a page that no longer exists.  I can't find an appropriate page to update the link to with that information.

**Comment by abracchi-tw** [comment]
hi @joel0, thanks for flagging this. the link is indeed outdated. #1136 should fix it
