### ISSUE TITLE
Build & deployments link not valid

### ISSUE THREAD

**Issue by 3052** [cloudflare/cloudflare-docs#11337]
### Example URL(s)

https://dash.cloudflare.com/a0f236930132796e8f429a7dbc35f0a4/pages/view/159/settings/builds-deployments

### Actual Behavior

I pushed a new Cloudflare Pages version, buts its still caching the old version. I see this link:

> ![Untitled](https://github.com/cloudflare/cloudflare-docs/assets/147215885/d86c5842-f4b7-4eb9-bd8d-97a67f9f265c)

but if I click it, I get nothing:

> ![2](https://github.com/cloudflare/cloudflare-docs/assets/147215885/067427c1-102f-4b38-9de6-02c1a43158b0)

### Expected Behavior

.

**Comment by kodster28** [comment]
This is being tracked in an internal ticket (and also sorta outside the ability of our docs team to address, since it's dash behavior), so closing this out.

Thanks for raising though, made sure it was routed to the right folks internally.
