### ISSUE TITLE
Cloudflare pages:  detail builds documentation

### ISSUE THREAD

**Issue by jlarmstrongiv** [cloudflare/cloudflare-docs#1134]
### Expected Behavior
I would like to know:
- how long a build can run until it timeouts (errors)
- the specs of the machine it’s building on (so I can estimate the build time)

### Actual Behavior
These details are [unlisted](https://developers.cloudflare.com/pages/platform/limits).

### Section that requires update
- Link: https://developers.cloudflare.com/pages/platform/limits
- Section: Builds

### Additional information
@jacebenson will have new info for https://jace.pro/post/2020-12-17-cloudflare-pages-netlify-zeit-github-pages-and-gitlab-pages-where-to-host/

**Comment by RarogCmex** [comment]
Cloudflare uses neltify buildsystem underhood, so you may take docs from here https://github.com/netlify/build-image

**Comment by kristianfreeman** [comment]
@nevikashah could someone from the pages team help out here?
