### ISSUE TITLE
Inconsistent Documentation - R2

### ISSUE THREAD

**Issue by lawfulsoftware** [cloudflare/cloudflare-docs#11358]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/r2/examples/postman.md

### Section 3

The screenshot shows `r2-access-key` however the following paragraph shows `r2-access-key-id`.
The screenshot shows `r2-secret-id` however the following paragraph shows `r2-secret-access-key`.

The latter keys are used several times in that section.

**Comment by dcpena** [comment]
Updated in the PR linked above. Thanks for the filing the issue @lawfulsoftware!
