### ISSUE TITLE
Update docs to include performance.now() = Date.now()

### ISSUE THREAD

**Issue by dave-swift** [cloudflare/cloudflare-docs#11350]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/performance/

### What changes are you suggesting?

The current documentation implies that [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) follows the MDN spec, which should return a DOMHighResTimeStamp with microsecond precision.  However, this isn't the case with `workerd`.  As commented in the [codebase](https://github.com/cloudflare/workerd/blob/1f35fc457b33783e92bd82e3186c800683c0ea33/src/workerd/api/global-scope.c%2B%2B#L681), it has been neuter to only return the same value as `Date.now()`.

While this change is understandable in production, it makes it hard to do performance testing locally.  Ideally, we would have access to microsecond precision locally somehow (particulary since CPU time is limited to only 10ms per request for free accounts).  Nonetheless, the change should at least be documented.

To be clear, this is unrelated to the timers incrementing (or not incrementing) based on I/O, which is well documented (thank you!).

### Additional information

For context, my use case is something like the code below.  I have a loop that takes ~14ms to run thru thousands of times.  The code in the loop is quick, but starts to add up after being run so many times.

```
// meaningless functions to simplify the example
let doSomething1 = ()=>{'Hello world'};
let doSomething2 = ()=>{1+1};
let doSomething3 = ()=>{Math.random()};

let test1 = [], test2 = [], test3 = [];
let start = performance.now();

//manyRows is something like an Array(10000);
for(const row of manyRows) {

    let test1Start = performance.now();
    doSomething1(row);
    test1.push(performance.now() - test1Start);

    let test2Start = performance.now();
    doSomething2(row);
    test2.push(performance.now() - test2Start);

    let test3Start = performance.now();
    doSomething3(row);
    test3.push(performance.now() - test3Start);

}

console.log({
    total: performance.now() - start,
    test1: test1.reduce((a,b) => a+b, 0),
    test2: test2.reduce((a,b) => a+b, 0),
    test3: test3.reduce((a,b) => a+b, 0)
});

// OUTPUT: { "total": 14, "test1": 0, "test2": 1, "test3": 1 }
```
Since the `doSomethingN` calls are typically <1ms each, the timers round to 0 almost every time, meaning the fractional milliseconds cannot be added up over time.

If I run the same code directly in a desktop browser, I get much more detailed data which shows me where the slow code is:
```
OUTPUT: { "total": 16.599999964237213, "test1": 3.4999999403953552, "test2": 1.399999976158142, "test3": 8.20000010728836 }
```

**Comment by KimJ15** [comment]
I think this has been updated since the issue has been closed. The docs have been updated since then. 

Closing this as resolved but if edits could improve the docs, please feel free to submit a docs recommendation.
