### ISSUE TITLE
1.1.1.1 DoH steps for FireFox outdated

### ISSUE THREAD

**Issue by mia-riezebos** [cloudflare/cloudflare-docs#11375]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

- https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/encrypted-dns-browsers/

### What changes are you suggesting?

The following diff:

```diff
(L11)
  ## Mozilla Firefox
 
  1. Select the menu button > **Settings**.
- 2. In the **General** menu, scroll down to access **Network Settings**.
- 3. Select **Settings**.
- 4. Select **Enable DNS over HTTPS**. By default, it resolves to Cloudflare DNS.
+ 2. In the **Privacy & Security** menu, scroll down to the **Enable secure DNS** section.
+ 3. Select **Increased Protection** or **Max Protection**. By default, it will use the **Cloudflare** provider.
+ 4. If this is not the case for you, select **Cloudflare** in the **Choose Provider** dropdown.

  ## Google Chrome
(L20)
```

Commit on my fork: https://github.com/mia-riezebos/cloudflare-docs/commit/41365167a14c71648f16afd6c70027054f4af511

**Comment by kodster28** [comment]
Thanks for raising (and then addressing), @mia-riezebos!
