### ISSUE TITLE
Error Code 520

### ISSUE THREAD

**Issue by Texarkan** [cloudflare/cloudflare-docs#11374]
### Example URL(s)

www.fanfiction.net

### Actual Behavior

The main issue revolves around trying read or post online stories at fanfiction.net, so I'm hoping that you could get this resolved on your end. If you please.

### Expected Behavior

If there's any expected behavior, it could very well be on either fanfiction.net or 9animetv.to, or both, just so you know.

### Additional information

This kind of thing has happened before in the past, meaning so much earlier in 2023. Whether it had something to do with 9anime or fanfiction, so I would appreciate it if the same thing could possibly be avoided.

**Comment by haleycode** [comment]
Hi @Texarkan! The 520 error code needs to be resolved by the owner of the site you are trying to access, and isn't something we can address through updates/changes to Cloudflare's developer documentation. For that reason, I'm going to close this issue for now.
