### ISSUE TITLE
Since You Don't Answer Your Phone or Give Anyone A Way to Contact You

### ISSUE THREAD

**Issue by catparkerphoto** [cloudflare/cloudflare-docs#11396]
### Example URL(s)

https://topazlabs.com
https://spacesdown.com/login
https://dash.cloudflare.com/login

### Actual Behavior

Every website I am using with your verification service on it, DOES NOT WORK! None of them. It just spins and spins and spins and gives me a failure. This is on more than one site. I can't get any work done. 

### Expected Behavior

I expect it to work and not have to fight to get into my accounts. I had never had this issue until your company's security thing popped up as the new one. 

### Additional information

https://github.com/cloudflare/cloudflare-docs/assets/94585969/b33e0ad2-7591-4939-b249-abe00b7990d2

![Screenshot 2023-10-20 121627](https://github.com/cloudflare/cloudflare-docs/assets/94585969/69d7a0f0-157a-4722-91e7-a2882438a480)

**Comment by haleycode** [comment]
Hi @catparkerphoto, I'm sorry for the inconvenience. Unfortunately this isn't an issue we can address via updates or changes to Cloudflare's developer documentation, so I'll be closing this ticket. You could try contacting the sites/services you are trying to access and requesting that they review how Cloudflare is configured.
