### ISSUE TITLE
Pages gitlab link from wrangler

### ISSUE THREAD

**Issue by syonfox** [cloudflare/cloudflare-docs#11403]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Please let me know if this is possible

### Content Location

https://developers.cloudflare.com/pages/get-started/guide/#select-your-gitlab-repository

Hello, 

I am trying to get my project bootstraps going and was looking for a way to add a Cloudflare pages project from Wrangler. 

I don't think it is possible but it would be awesome to be able to link a GitLab repository to pages from Wrangler API 

if that's not possible then it would be nice if we could configure an existing GitLab pages project from Wrangler. 

+

**Comment by deadlypants1973** [comment]
Hi @syonfox , this is not planned anytime in the future. I am closing this issue as it is not a documentation request. You can check out https://community.cloudflare.com/c/feedback/feature-request/30 if you'd like to submit a feature request.
