### ISSUE TITLE
Is it expirationTTL or expirationTtl

### ISSUE THREAD

**Issue by smebberson** [cloudflare/cloudflare-docs#11414]
### Which Cloudflare product does this pertain to?

KV

### Existing documentation URL(s)

https://developers.cloudflare.com/kv/api/write-key-value-pairs/

### What changes are you suggesting?

Setting the key's expiration time to live is referenced as both `expirationTTL` and `expirationTtl `. It is not obvious which key name to use.

**Comment by Maddy-Cloudflare** [comment]
It's `expirationTTL`. 

https://github.com/cloudflare/cloudflare-docs/pull/11417

**Comment by smebberson** [comment]
@Maddy-Cloudflare, awesome, thank you!
