### ISSUE TITLE
More detailed instructions

### ISSUE THREAD

**Issue by schack** [cloudflare/cloudflare-docs#1141]
When arriving at "Refreshing fields and filters manually" the report pages just contains a lot of empty graphs.
It's pretty hard to figure out what to change where.

**Comment by KimJ15** [comment]
👋 @schack  Thank you for the feedback about how we can make improvements with developers.cloudflare.com documentation. Would you mind providing a link to the documentation you are referring to? Thanks!

**Comment by minuk0612** [comment]
> When arriving at "Refreshing fields and filters manually" the report pages just contains a lot of empty graphs.
> It's pretty hard to figure out what to change where.

**Comment by minuk0612** [comment]
The code provided here does not show any output after giving creds for me and its really really difficult to trace the bug
https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics
it doesnot show any graph

**Comment by KimJ15** [comment]
Great suggestion. We are working on some other updates to this section of dev docs, so I will share your post with the team. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
