### ISSUE TITLE
Set paranoia level documentation

### ISSUE THREAD

**Issue by qwilr-altonius** [cloudflare/cloudflare-docs#11429]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/

### What changes are you suggesting?

I tried using the terraform code snippet listed to [update the paranoia level ](https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/#configure-the-owasp-paranoia-level-score-threshold-and-action).
Unfortunately the instruction for `status = "disabled"` was not allowed by terraform, giving the below error.

```
on file.tf line xx, in resource "cloudflare_ruleset" "zone_level_managed_waf":
--
48:           status = "disabled"
An argument named "status" is not expected here.

ERRO[0019] 1 error occurred:
* exit status 1
```

Instead I used `enabled = false`.  

If this is correct, can the documentation be updated to reflect this.

**Comment by pedrosousa** [comment]
Hi @qwilr-altonius 
You're absolutely right: the Cloudflare Terraform provider changed a while ago, and these examples were not up to date. Thanks for flagging!
