### ISSUE TITLE
Error in Browser Rendering example code

### ISSUE THREAD

**Issue by evanderkoogh** [cloudflare/cloudflare-docs#11428]
### Which Cloudflare product does this pertain to?

Browser Rendering

### Existing documentation URL(s)

https://developers.cloudflare.com/browser-rendering/platform/wrangler/#bindings

### What changes are you suggesting?

In the example wrangler.toml file you specify

```
# Top-level configuration
name = "browser-rendering"
main = "src/index.ts"
node_compat = true
workers_dev = true

browser = { binding = "MYBROWSER" }
```

But in the example code you have: 

```
const browser = await puppeteer.launch(env.BROWSER);
```

and `MYBROWSER` !== `BROWSER`

**Comment by deadlypants1973** [comment]
This looks fixed now so closing this issue: https://developers.cloudflare.com/browser-rendering/platform/wrangler/#bindings
