### ISSUE TITLE
Instructions Reference Deprecated Commands

### ISSUE THREAD

**Issue by lawfulsoftware** [cloudflare/cloudflare-docs#11454]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/wrangler/commands.md

### What changes are you suggesting?

`init` does not warn that has been deprecated and will soon be removed.

**Comment by deadlypants1973** [comment]
hi @lawfulsoftware , `init` will not be deprecated. Modifying docs to reflect this. Thank you!
