### ISSUE TITLE
Problem with the domain or scope

### ISSUE THREAD

**Issue by A1dossari** [cloudflare/cloudflare-docs#11466]
### Example URL(s)

https://dash.cloudflare.com/126a1759069a7e721164748a3a34e42a/turnstile

### Actual Behavior

I registered a domain in my name and the purchase was completed. How can I do so?
Knowing my knowledge and my data

ina1dossari@icloud.com

### Expected Behavior

a1dossari.net 

cpanbel

Control panel linked to space

**Comment by kodster28** [comment]
Howdy @A1dossari, closing as it's very unclear what the ask is here.

Feel free to re-open with more details though.

**Comment by A1dossari** [comment]
اسف كان يجهلني التواصل معكم
