### ISSUE TITLE
Please, add changelog for Linux warp client

### ISSUE THREAD

**Issue by Olegf13** [cloudflare/cloudflare-docs#11478]
### Which Cloudflare product(s) does this pertain to?

WARP Client

### Subject Matter

Linux client changelog

### Content Location

some github page with link to it from https://pkg.cloudflareclient.com/

**Comment by haleycode** [comment]
Hi @Olegf13! Could you provide more detailed information on which page(s) in the developer documentation you would like us to update, and what information you would like us to add? Thank you!

**Comment by haleycode** [comment]
Going to close this out for now; we can always reopen later with more information.

**Comment by Olegf13** [comment]
Hi @haleycode ! Sorry, missed a notification update for the issue.
What I've meant is a list of changes for a specific version (e.g. version history).

Here are examples for Mac OS and iOS clients I'm also using for work purposes:
Mac OS client changelog: https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release

Couldn't find the same information for a Linux warp client.

<details><summary>Some screenshots</summary>

![Screenshot from 2023-11-02 10-38-21](https://github.com/cloudflare/cloudflare-docs/assets/2501447/311aa159-5b3d-4ed9-a9a0-098ad3698dce)

![Screenshot from 2023-11-02 10-36-50](https://github.com/cloudflare/cloudflare-docs/assets/2501447/693c6c21-129e-464f-8a15-9870d1cda121)

</details>
