### ISSUE TITLE
Outdated information in "Gathering information for troubleshooting sites" Support article

### ISSUE THREAD

**Issue by dfidalgoc** [cloudflare/cloudflare-docs#11512]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/troubleshooting/general-troubleshooting/gathering-information-for-troubleshooting-sites/

### What changes are you suggesting?

The page says "Currently, only Chrome and Firefox can access the HAR feature by default." but later on, it offers information on how to create HAR files in Edge and Safari. The above sentence should be rewritten or removed.

**Comment by JamieEE14** [comment]
This text has now been removed. Thank you!
