### ISSUE TITLE
Can 1.1.1.1 for families be manually configured on Android? Can it be locked?

### ISSUE THREAD

**Issue by bbsimonbb** [cloudflare/cloudflare-docs#11527]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

The question's in the title. Can 1.1.1.1 for families be manually configured on Android? Can it be locked?

### Content Location

https://developers.cloudflare.com/1.1.1.1/setup/android/

**Comment by RebeccaTamachiro** [comment]
Hi @bbsimonbb 👋 Thanks for reaching out!
Yes, you can configure 1.1.1.1 for Families on Android manually, we have updated the page you linked.
