### ISSUE TITLE
No more firewall rules, please update

### ISSUE THREAD

**Issue by lazyrabbit65** [cloudflare/cloudflare-docs#11540]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/firewall/cf-firewall-rules/order-priority/

### What changes are you suggesting?

Is the order priority still valid?

please update this page, i no longer see firewall rules

**Comment by haleycode** [comment]
Hi @lazyrabbit65, thank you for raising this! We have an internal ticket where we're tracking the work that needs to be done for this update, so I'll close this one since it's a duplicate.
