### ISSUE TITLE
Kill processes bound to port 53 - Insufficient documentation + Solution

### ISSUE THREAD

**Issue by Explosion-Scratch** [cloudflare/cloudflare-docs#11548]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors/#CF_DNS_PROXY_FAILURE

### What changes are you suggesting?

I was getting the error that `mDNSResponder` was bound to port 53, and I had to run this to find the offending process that was bound to port 53:
```
sudo netstat -vanp tcp | grep ".53 "
netstat -vanp tcp | grep ".53 " | awk '{print $9}' | xargs ps -p
```
Then look at the logs and find what app is on port 53, in my case this was Fig.

Also quit Docker, disable sharing in System Settings (mac) and kill mDNSResponder before and after: `sudo killall -HUP mDNSResponder`

### Additional information

This was the error the WARP Client gave me:
```
The WARP Agent must be the only process responsible for DNS resolution on the device. One or more processes are already bound to port 53: mDNSResponder.
```

**Comment by ranbel** [comment]
Hi @Explosion-Scratch, thanks for opening this issue. Could you provide the command output that shows which app is on port 53?

**Comment by Explosion-Scratch** [comment]
```
sudo netstat -vanp tcp | grep ".53 "
netstat -vanp tcp | grep ".53 " | awk '{print $9}' | xargs ps -p
tcp4       0      0  127.0.2.3.53           *.*                    LISTEN       131072  131072   4174      0 00180 00000002 00000000001447aa 00000001 00000900      1      0 000001
tcp4       0      0  127.0.2.2.53           *.*                    LISTEN       131072  131072   4174      0 00180 00000002 00000000001447a5 00000001 00000900      1      0 000001
tcp6       0      0  *.53                   *.*                    LISTEN       131072  131072    252      0 00100 00000006 00000000001295e0 00000000 00000800      1      0 000001
  PID TTY           TIME CMD
  252 ??         2:54.14 /usr/sbin/mDNSResponder
 4174 ??         7:38.24 /Applications/Cloudflare WARP.app/Contents/Resources/CloudflareWARP
```
But it had showed Docker.app and Fig.app on there before I killed them.

**Comment by ranbel** [comment]
From a documentation perspective, the command output should match what a user sees when they are experiencing the error. So it should show an example of third-party processes bound to port 53 instead of CloudflareWARP.

**Comment by ranbel** [comment]
@dh-cf

**Comment by dcorking** [comment]
For me, on macOS Ventura 13.6.4, there is no way for an ordinary user to stop mdnsresponder. It is protected by System Integrity Protection, and restarts automatically, so would require a reboot to the Recovery image to temporarily disable SIP. That should probably me mentioned in the troubleshooting docs for macOS.

**Comment by Explosion-Scratch** [comment]
> For me, on macOS Ventura 13.6.4, there is no way for an ordinary user to stop mdnsresponder. It is protected by System Integrity Protection, and restarts automatically, so would require a reboot to the Recovery image to temporarily disable SIP. That should probably me mentioned in the troubleshooting docs for macOS.

Sometimes it shows as mDNSResponder but try killing other things like Docker and anything else network/vm/daemon/dns related

**Comment by dcorking** [comment]
Thank you @Explosion-Scratch . Athough mDNSResponder still runs on my machine, and, according to netstat, is listening on tcp6 port 53, WARP today connected successfully. A few days ago I upgraded Docker Desktop to 4.27.1 (136059), engine 25.0.2 and I wonder if that has fixed it: that or the fact that I am running on an IPv6-capable host network today (and was on IPv4 last week). The WARP client version is unchanged from the one above that blamed mDNSResponder.
```shell
$ warp-cli status
Status update: Connected
Success
)$ ps ax | grep -i mdnsre
67680   ??  Ss     0:00.36 /usr/sbin/mDNSResponder
67681   ??  Ss     0:00.07 /usr/sbin/mDNSResponderHelper
68300 s000  R+     0:00.00 grep -i mdnsre
$ sudo netstat -vanp tcp | grep ".53 "
...
tcp6       0      0  *.53                   *.*                    LISTEN       131072  131072  67680      0 00100 00000006 0000000000696b0f 00000000 00000800      1      0 000001
...
```

**Comment by dcorking** [comment]
The WARP client is now showing a different error on IPv4 than this one, ( mDNSResponder is still listening on tcp6 but not 4) so I can no longer reproduce the issue described here.

OP: have you come up with a way for other users to reproduce this behaviour in the WARP client?

**Comment by Explosion-Scratch** [comment]
> The WARP client is now showing a different error on IPv4 than this one, ( mDNSResponder is still listening on tcp6 but not 4) so I can no longer reproduce the issue described here.

It happens sometimes when I restart if Docker opens and starts before WARP starts but not reliably. It's only occasionally

**Comment by 774649283** [comment]
Thank you, it was indeed caused by docker startup. After I closed docker, I started WARP again and it was fine.

**Comment by omniconvert** [comment]
Can confirm to be Docker related. Had the same error message. Quick Docker (desktop) on mac and Warp clien connected immediately.

**Comment by ranbel** [comment]
Updated docs with more information on mDNSResponder:
#13983
