### ISSUE TITLE
Problem emails do not get to gmail addresses

### ISSUE THREAD

**Issue by ElenaVerbtskaya** [cloudflare/cloudflare-docs#11542]
### Example URL(s)

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [Elena.verbitskaya@gmail.com](mailto:Elena.verbitskaya@gmail.com)
    host gmail-smtp-in.l.google.com [2a00:1450:4010:c0b::1a]
    SMTP error from remote mail server after pipelined end of data:
    550-5.7.26 This mail has been blocked because the sender is unauthenticated.
    550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM.
    550-5.7.26
    550-5.7.26  Authentication results:
    550-5.7.26  DKIM = did not pass
    550-5.7.26  SPF [clinpharm-spbgmu.ru] with ip:
    [2a02:408:7722:1:77:222:41:79] =
    550-5.7.26 did not pass
    550-5.7.26
    550-5.7.26  To mitigate this issue, please visit Gmail's authentication guide
    550-5.7.26 for instructions on setting up authentication:
    550 5.7.26  https://support.google.com/mail/answer/81126#authentication f18-20020a2e1f12000000b002c50bd6d1c8si1069648ljf.488 - gsmtp
Reporting-MTA: dns; smtpout13.sweb.ru

Action: failed
Final-Recipient: rfc822;[Elena.verbitskaya@gmail.com](mailto:Elena.verbitskaya@gmail.com)
Status: 5.0.0
Remote-MTA: dns; gmail-smtp-in.l.google.com
Diagnostic-Code: smtp; 550-5.7.26 This mail has been blocked because the sender is unauthenticated.
 550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM.
 550-5.7.26
 550-5.7.26  Authentication results:
 550-5.7.26  DKIM = did not pass
 550-5.7.26  SPF [clinpharm-spbgmu.ru] with ip: [2a02:408:7722:1:77:222:41:79] =
 550-5.7.26 did not pass
 550-5.7.26
 550-5.7.26  To mitigate this issue, please visit Gmail's authentication guide
 550-5.7.26 for instructions on setting up authentication:
 550 5.7.26  https://support.google.com/mail/answer/81126#authentication f18-20020a2e1f12000000b002c50bd6d1c8si1069648ljf.488 - gsmtp

### Actual Behavior

emails from admin@clinpharm-spbgmu.ru do not get to all gmail  addresses    (ex. Elena.verbitskaya@gmail.com)
Displaied error:

[Elena.verbitskaya@gmail.com](mailto:Elena.verbitskaya@gmail.com)
    host gmail-smtp-in.l.google.com [2a00:1450:4010:c0b::1a]
    SMTP error from remote mail server after pipelined end of data:
    550-5.7.26 This mail has been blocked because the sender is unauthenticated.
    550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM.
    550-5.7.26
    550-5.7.26  Authentication results:
    550-5.7.26  DKIM = did not pass
    550-5.7.26  SPF [clinpharm-spbgmu.ru] with ip:
    [2a02:408:7722:1:77:222:41:79] =
    550-5.7.26 did not pass
    550-5.7.26
    550-5.7.26  To mitigate this issue, please visit Gmail's authentication guide
    550-5.7.26 for instructions on setting up authentication:
    550 5.7.26  https://support.google.com/mail/answer/81126#authentication f18-20020a2e1f12000000b002c50bd6d1c8si1069648ljf.488 - gsmtp
Reporting-MTA: dns; smtpout13.sweb.ru

Action: failed
Final-Recipient: rfc822;[Elena.verbitskaya@gmail.com](mailto:Elena.verbitskaya@gmail.com)
Status: 5.0.0
Remote-MTA: dns; gmail-smtp-in.l.google.com
Diagnostic-Code: smtp; 550-5.7.26 This mail has been blocked because the sender is unauthenticated.
 550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM.
 550-5.7.26
 550-5.7.26  Authentication results:
 550-5.7.26  DKIM = did not pass
 550-5.7.26  SPF [clinpharm-spbgmu.ru] with ip: [2a02:408:7722:1:77:222:41:79] =
 550-5.7.26 did not pass
 550-5.7.26
 550-5.7.26  To mitigate this issue, please visit Gmail's authentication guide
 550-5.7.26 for instructions on setting up authentication:
 550 5.7.26  https://support.google.com/mail/answer/81126#authentication f18-20020a2e1f12000000b002c50bd6d1c8si1069648ljf.488 - gsmtp

### Expected Behavior

Other

**Comment by kodster28** [comment]
Howdy @ElenaVerbtskaya, it seems like you're experiencing issues... but unfortunately as a Docs team, this isn't something we can truly help out with.

You might be able to find your answer with this [Email troubleshooting](https://developers.cloudflare.com/dns/troubleshooting/email-issues/) guide.

If not, recommend you reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/troubleshooting/general-troubleshooting/contacting-cloudflare-support/) or looking in the [Cloudflare community](https://community.cloudflare.com).
