### ISSUE TITLE
Need to wrap env.NAMESPACE.get(key) with try catch block

### ISSUE THREAD

**Issue by ericphambunnings** [cloudflare/cloudflare-docs#11574]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

Hi Cloudflare,
Regarding this document: https://developers.cloudflare.com/kv/api/read-key-value-pairs/
We had experience a KV issue today. It seems like when this happened this function env.NAMESPACE.get(key) has thrown an exception "KV GET failed: 401 Unauthorized"

Id suggest wrapping this call will try catch for better error handling

### What changes are you suggesting?

modify the example function to
```
export default {
    async fetch(request, env, ctx) {
        try {
            const value = await env.NAMESPACE.get("first-key");

            if (value === null) {
                return new Response("Value not found", {status: 404});
            }
            return new Response(value);
        }
        catch (e)
        {
            return new Response(e.message, {status: 500});
        }
    },
};
```

**Comment by syonfox** [comment]
```js


async function kvGetRetry(key, opts) {
  let retry = 40 // ms
  
  let result = false;
  let noRet = true
  while(noRet && retry < 1000) {
  try {
    let result = await kv.get(key, opts) 
    noRet = false;
  } catch(e) {
     console.error("KV FAILED :(", e)
     let c = retry * 2000
     while(c > 0 )
      c-- // spin for some time
     } 
     retry *= 2;
  }
  return result
}

// what do you guys think is it better to set timeout in a promis loop or spin a bit or just retry 

```

**Comment by Maddy-Cloudflare** [comment]
> ### Which Cloudflare product does this pertain to?
> 1.1.1.1
> 
> ### Existing documentation URL(s)
> Hi Cloudflare, Regarding this document: https://developers.cloudflare.com/kv/api/read-key-value-pairs/ We had experience a KV issue today. It seems like when this happened this function env.NAMESPACE.get(key) has thrown an exception "KV GET failed: 401 Unauthorized"
> 
> Id suggest wrapping this call will try catch for better error handling
> 
> ### What changes are you suggesting?
> modify the example function to
> 
> ```
> export default {
>     async fetch(request, env, ctx) {
>         try {
>             const value = await env.NAMESPACE.get("first-key");
> 
>             if (value === null) {
>                 return new Response("Value not found", {status: 404});
>             }
>             return new Response(value);
>         }
>         catch (e)
>         {
>             return new Response(e.message, {status: 500});
>         }
>     },
> };
> ```
> 
> ### Additional information
> _No response_

https://github.com/cloudflare/cloudflare-docs/pull/11770
