### ISSUE TITLE
Fix link to cloudflared Docker image

### ISSUE THREAD

**Issue by bradobro** [cloudflare/cloudflare-docs#11584]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/#docker

### What changes are you suggesting?

The current content reads:

## Docker

A Docker image of cloudflared is available on DockerHub [link-icon](https://hub.docker.com/r/cloudflare/cloudflared).

However, the docker hub page referenced returns a 404, as does the Cloudflare Docker Hub page (https://hub.docker.com/u/cloudflare).

<img width="1095" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/354176/86b9c94b-a2e2-44cd-b013-1d8a18eb9a99">

**Comment by ranbel** [comment]
The links are working fine for me.  Feel free to reopen if this is still an issue.
<img width="873" alt="Screenshot 2023-10-31 at 1 24 49 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/101146722/9295137b-d662-46da-92cf-f2b36a5f5949">
<img width="1181" alt="Screenshot 2023-10-31 at 1 25 37 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/101146722/62391de6-1cc8-46f5-bd2f-2df8811739fd">
