### ISSUE TITLE
Link to report in-use IPv4 for Cloudflare Gateway location broken

### ISSUE THREAD

**Issue by chasestech** [cloudflare/cloudflare-docs#1160]
### Expected Behavior
Users should be directed to the correct form to submit a support case regarding in-use IPv4 for Cloudflare Gateway location.

### Actual Behavior
The documentation on how to report an in-use IPv4 address for a Cloudflare Gateway location leads to an inaccessible Google Form. 

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blame/production/products/cloudflare-one/src/content/connections/connect-networks/locations/index.md#L59

**Comment by abracchi-tw** [comment]
thanks for raising this, @chasestech. we're looking into it.

**Comment by abracchi-tw** [comment]
@chasestech link should be fixed now.  thanks again. 
https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/locations#source-ipv4-address
