### ISSUE TITLE
How do I block or disable IP addresses that cause packet loss

### ISSUE THREAD

**Issue by kkood** [cloudflare/cloudflare-docs#11611]
### Which Cloudflare product(s) does this pertain to?

DNS

### Subject Matter

How do I block or disable IP addresses that cause packet loss

### Content Location

After proxying my domain, there are two IP addresses being resolved. However, one of the IP addresses experiences packet loss when accessed. How can I block or disable the IP address that is causing packet loss?

**Comment by RebeccaTamachiro** [comment]
👋 @kkood. I'm sorry, we only take care of [developers.cloudflare.com](http://developers.cloudflare.com/) documentation in this repo, and this seems like a specific issue you are facing. Please reach out to [community.cloudflare.com](http://community.cloudflare.com/) or [support.cloudflare.com](http://support.cloudflare.com/) for assistance!
