### ISSUE TITLE
Pricing missing for Cloufflare Images 'Resizing' and 'Polish' add-ons

### ISSUE THREAD

**Issue by Maxhodges** [cloudflare/cloudflare-docs#11619]
### Which Cloudflare product(s) does this pertain to?

Images

### Subject Matter

pricing is missing

### Content Location

there's no providing for CLoudflare images Resizing or Polish
https://developers.cloudflare.com/images/pricing/
https://developers.cloudflare.com/images/image-resizing/
https://developers.cloudflare.com/images/polish/activate-polish/

### Additional information

For years I've had a hard time getting pricing from Cloudflare. even talking to someone on live chat it was just impossible. This has gotta be hurting your sales cycle! I just don't get it.

**Comment by Maxhodges** [comment]
For example, you can read here how other visitors complain that Resizing pricing is opaque. I confer!

>  Image Resizing pricing has always been a rather muddy territory.

https://community.cloudflare.com/t/webp-images/511638/6

It's a great mystery why someone at Cloudflare doesn't ensure pricing is easy to find, clear, and transparent. I'm storing 13 Million images and going 200K resizing per month on IMGIX. I might move to Cloudflare it is cheaper, but without clarity around pricing, I can't know if it would cost more or less!

**Comment by dcpena** [comment]
Hi @Maxhodges, thanks for opening the issue and sharing the confusion around pricing. 

There are some changes coming soon to Images that I think might help. There's a blog post titled [Image optimization made simpler and more predictable: we’re merging Cloudflare Images and Image Resizing](https://blog.cloudflare.com/merging-images-and-image-resizing/) that I think you might find helpful about some upcoming changes to the pricing, and the docs will definitely be updated to reflect the changes mentioned.
