### ISSUE TITLE
cloudflare tunnels docs update

### ISSUE THREAD

**Issue by Roguito** [cloudflare/cloudflare-docs#11623]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/

My dashboard has nothing like what is described here.

"Select Create a tunnel."

Where? I see an add location. Extremely confusing when the documentation does not match what is presented.

### What changes are you suggesting?

update documentation to reflect the current implementation or a header or banner which explains what version of the documentation you are viewing and a link to updated docs.

**Comment by ranbel** [comment]
Hi @Roguito, thanks for flagging! We've updated the docs in #11626.
