### ISSUE TITLE
Incorrect reference to "try cloudflare" in the "Quick Tunnels" doc

### ISSUE THREAD

**Issue by sarahec** [cloudflare/cloudflare-docs#11624]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/

### What changes are you suggesting?

trycloudflare.com should be try.cloudflare.com. The first address returns a DNS error.

**Comment by ranbel** [comment]
Hi @sarahec, thanks for the feedback. 
`trycloudflare.com` is the correct Quick Tunnels domain, but it's currently down due to an incident: https://www.cloudflarestatus.com/incidents/hm7491k53ppg
`try.cloudflare.com` only hosts the marketing site.
