### ISSUE TITLE
Some ISO PDF files have problems

### ISSUE THREAD

**Issue by gokselozkaya** [cloudflare/cloudflare-docs#11633]
### Example URL(s)

https://cloudflare-ipfs.com/ipfs/bafykbzacedpku3duvucdb3nfbfrlirxqjeas4sld4phi2qti6tfrwxadnr4fa/standards/ISO/05001-10000/ISO%2007573-2008.pdf

### Actual Behavior

Some PDF files on the link (https://cloudflare-ipfs.com/ipfs/bafykbzacedpku3duvucdb3nfbfrlirxqjeas4sld4phi2qti6tfrwxadnr4fa/standards/)  cannot be opened by several users like me. 

### Expected Behavior

I can open and download some PDF files yet I expect to reach all documents without any kind of errors.

**Comment by haleycode** [comment]
Hi @gokselozkaya, thanks for raising this. This content is not something our team owns, but I'll be sure to forward it along internally to the correct team.

**Comment by kodster28** [comment]
Hey, did a bit of digging and seems like the availability issues are related to an ongoing incident.

To keep up to date on this, you can refer to https://www.cloudflarestatus.com/.

**Comment by gokselozkaya** [comment]
FYI: I still cannot reach the files which is desperately needed after clicking on the links which we were mentioning.
