### ISSUE TITLE
API Request Failed: GET /api/v4/accounts/a1997e54a29d52f355262fd649879200/stream (503)

### ISSUE THREAD

**Issue by candicenuco** [cloudflare/cloudflare-docs#11634]
### Example URL(s)

API Request Failed: GET /api/v4/accounts/a1997e54a29d52f355262fd649879200/stream (503)

### Actual Behavior

API Request Failed: GET /api/v4/accounts/a1997e54a29d52f355262fd649879200/stream (503)

### Expected Behavior

API Request Failed: GET /api/v4/accounts/a1997e54a29d52f355262fd649879200/stream (503)

### Additional information

API Request Failed: GET /api/v4/accounts/a1997e54a29d52f355262fd649879200/stream (503)

**Comment by pedrosousa** [comment]
Hi @candicenuco,
Due to an ongoing incident, the Stream API is currently unavailable.
You can check for updates on this situation at https://www.cloudflarestatus.com/.

**Comment by candicenuco** [comment]
Hi Pedro

 

Thanks for the quick response. What is the lead time for this fix please and how often does this happen please ?

 

 



 <https://nucoauctioneers.com/> 

	Candice van Staden

IT & Marketing Manager | NUco Auctioneers

			

  <https://www.mailer.nucoauctioneers.com/email-signature/phone.png> 

 <tel:0112068963> +27 11 206 8963/4/5 



  <https://www.mailer.nucoauctioneers.com/email-signature/email.png> 

 ***@***.***> ***@***.*** 



  <https://www.mailer.nucoauctioneers.com/email-signature/link.png> 

 <https://www.nucoauctioneers.com> www.nucoauctioneers.com 



  <https://www.mailer.nucoauctioneers.com/email-signature/pin.png> 

 <https://g.page/Nucoauctioneers?share> 127 Sterkfontein Avenue, Centurion, 1665, South Africa


	


 <https://auction.nucoauctioneers.com/> 




 <https://www.facebook.com/nucoauctioneer> 

	 <https://twitter.com/NucoAuctions> 

	 <https://za.linkedin.com/company/nuco-auctioneers> 

	 <https://www.instagram.com/nuco_auctioneers> 

	 <https://www.youtube.com/channel/UC_pZrFYdg3Oak9pBQ7P2N9Q> 



TRANSMITTED ELECTRONICALLY WITH NO SIGNATURE. The information in this email is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking action in reliance on the contents of this information is strictly prohibited and may be unlawful. NUco Auctioneers is neither liable for the proper, complete transmission of the information contained in this communication nor any delay in its receipt. This notice is deemed to form part of this communication in terms of Section 11 of the Electronic Communications Act 25 of 2002 of South Africa.

**Comment by pedrosousa** [comment]
I'm afraid we can't provide status updates in this repository, since we only address documentation updates. 

You can check the following page for any news regarding this incident:
https://www.cloudflarestatus.com/incidents/hm7491k53ppg
