### ISSUE TITLE
D1 Get-Started page example code error 

### ISSUE THREAD

**Issue by phg98** [cloudflare/cloudflare-docs#11644]
### Which Cloudflare product does this pertain to?

D1

### Existing documentation URL(s)

- https://developers.cloudflare.com/d1/get-started/

### What changes are you suggesting?

Example command saids 
```
wrangler d1 execute <DATABASE_NAME> --command='SELECT * FROM Customers'
```
But it gave me following error on my Windows PC with cmd terminal
```
X [ERROR] Unknown arguments: *, FROM, Customers'
```
Changing ' to " works fine.
```
wrangler d1 execute <DATABASE_NAME> --command="SELECT * FROM Customers"
```

### Additional information

There are two example command in the 'get-started' page. 
Both should be fixed.
I didn't test it on other machine.

**Comment by Maddy-Cloudflare** [comment]
> ### Which Cloudflare product does this pertain to?
> D1
> 
> ### Existing documentation URL(s)
> * https://developers.cloudflare.com/d1/get-started/
> 
> ### What changes are you suggesting?
> Example command saids
> 
> ```
> wrangler d1 execute <DATABASE_NAME> --command='SELECT * FROM Customers'
> ```
> 
> But it gave me following error on my Windows PC with cmd terminal
> 
> ```
> X [ERROR] Unknown arguments: *, FROM, Customers'
> ```
> 
> Changing ' to " works fine.
> 
> ```
> wrangler d1 execute <DATABASE_NAME> --command="SELECT * FROM Customers"
> ```
> 
> ### Additional information
> There are two example command in the 'get-started' page. Both should be fixed. I didn't test it on other machine.

Change addressed here: https://github.com/cloudflare/cloudflare-docs/pull/11776

Thank you!
