### ISSUE TITLE
Build your own Analytics dashboard

### ISSUE THREAD

**Issue by minuk0612** [cloudflare/cloudflare-docs#1164]
https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics

my graphql endpoints asks for self generated certificate
 i tried the following but then also i was not able to ignore ssl certificate from webpage where am i going wrong 
`function fetchAPI(url, email, apiKey, zoneTag) {
          let request = new Request(url, {rejectUnauthorized: false})

            let query = {"query":"{\n  viewer {\n    zones(filter: { zoneTag: " + zoneTag + " }) {\n      httpRequests1dGroups(\n        orderBy: [date_ASC]\n        limit: 1000\n        filter: { date_gt: \"2019-07-15\" }\n      ) {\n        date: dimensions {\n          date\n        }\n        sum {\n          cachedBytes\n          bytes\n        }\n      }\n    }\n  }\n}","variables":{}}
		
	    
            let init = {
                method: 'POST',
		body: JSON.stringify(query),
                strictSSL: false
    
        }
            request.headers.set('x-auth-key', apiKey)
            request.headers.set('x-auth-email', email)
		

            return fetch(request, init)
        }`
using curl to access those endpoint it was working fine with the use of -k same thing how can i do it here please help on this.
its showing following error

(index):128 POST https://api.cloudflare.com/client/v4/graphql net::ERR_CERT_INVALID

**Comment by KimJ15** [comment]
👋 @minuk0612  I'm sorry, we only take care of improvements to developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
