### ISSUE TITLE
Second and third graphs in WAE's "How is data sampled" are swapped

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/cloudflare-docs#11652]
### Which Cloudflare product does this pertain to?

Analytics

### Existing documentation URL(s)

https://developers.cloudflare.com/analytics/analytics-engine/sampling/#how-is-data-sampled
https://github.com/cloudflare/cloudflare-docs/blob/production/content/analytics/analytics-engine/sampling.md#how-is-data-sampled

### What changes are you suggesting?

The second and third graphs in the linked Workers Analytics Engine documentation are swapped. The third graph exhibits clear quantization, so it should go above the prose which reads "Notice that the larger bars look more or less unchanged, and yet they are still quite accurate. But as you analyze smaller customers, results get quantized and may even be rounded to 0 entirely."

The second graph looks nearly (but not quite) identical compared to the first graph, so it should go above the prose which reads "You may notice that this graphic is very similar to the first graph."

**Comment by angelampcosta** [comment]
Corrected in https://github.com/cloudflare/cloudflare-docs/pull/11654
