### ISSUE TITLE
Google Suite documentation doesn't include instructions for enabling trust for domain-owned apps

### ISSUE THREAD

**Issue by bdwilson** [cloudflare/cloudflare-docs#1169]
When using Google Suite, you must make sure the admin on the domain has enabled this feature prior to finishing the setup, if not, they will get: Error 400: admin_policy_enforced error (https://customerfx.com/article/how-to-resolve-error-400-admin_policy_enforced-when-connecting-creatio-bpmonline-to-your-google-g-suite-email-or-calendar/) 

400 error looks like so:
![image](https://user-images.githubusercontent.com/317946/115276579-3162b300-a111-11eb-913a-3a4b7f946c04.png)

Current location for this in Google Admin to change this is in Security -> API Controls
![image](https://user-images.githubusercontent.com/317946/115275679-1ba0be00-a110-11eb-87eb-914c9f4a18b4.png)

Thanks for making this service part of the free tier. If it wasn't free, I wouldn't have been able to contribute.

**Comment by abracchi-tw** [comment]
hi @bdwilson thanks for flagging this. we've added a question to the FAQ > Troubleshooting section covering this. https://developers.cloudflare.com/cloudflare-one/faq/teams-troubleshooting/#i-see-error-400-admin_policy_enforced-when-using-gsuite-as-an-identity-provider

**Comment by chripede** [comment]
@abracchi-tw actually the guidance in this issue is much better than what you've inserted into the FAQ.

**Comment by emiljoensson** [comment]
Thanks! Indeed this is the correct fix and the information in your FAQ is outdated/misleading  (https://developers.cloudflare.com/cloudflare-one/faq/teams-troubleshooting#i-see-error-400-admin_policy_enforced-when-using-gsuite-as-an-identity-provider)
