### ISSUE TITLE
List of logs

### ISSUE THREAD

**Issue by Cristian-Vt** [cloudflare/cloudflare-docs#11698]
### Which Cloudflare product(s) does this pertain to?

Logs

### Subject Matter

List of logs that can be copied in IAC

### Content Location

Hello,

Here are all the logs that you can get for HTTP_REQUEST LogPush JOB

ContentScanObjResults,ContentScanObjTypes,Cookies,LeakedCredentialCheckResult,ParentRayID,RayID,RequestHeaders,ResponseHeaders,SecurityAction,SecurityActions,SecurityRuleDescription,SecurityRuleID,SecurityRuleIDs,SecuritySources,SmartRouteColoID,UpperTierColoID,ZoneName,CacheCacheStatus,CacheReserveUsed,CacheTieredFill,CacheResponseBytes,CacheResponseStatus,ClientASN,ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientMTLSAuthCertFingerprint,ClientMTLSAuthStatus,ClientRegionCode,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,ClientTCPRTTMs,ClientXRequestedWith,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestProtocol,ClientRequestReferer,ClientRequestScheme,ClientRequestSource,ClientRequestURI,ClientRequestUserAgent,EdgeCFConnectingO2O,EdgeColoCode,EdgeColoID,EdgeEndTimestamp,EdgePathingOp,EdgePathingSrc,EdgePathingStatus,EdgeRequestHost,EdgeResponseBodyBytes,EdgeResponseBytes,EdgeResponseCompressionRatio,EdgeResponseContentType,EdgeResponseStatus,EdgeServerIP,EdgeStartTimestamp,EdgeTimeToFirstByteMs,OriginDNSResponseTimeMs,OriginIP,OriginRequestHeaderSendDurationMs,OriginSSLProtocol,OriginTCPHandshakeDurationMs,OriginTLSHandshakeDurationMs,OriginResponseBytes,OriginResponseDurationMs,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseHeaderReceiveDurationMs,OriginResponseStatus,OriginResponseTime,WAFAttackScore,WAFFlags,WAFMatchedVar,WAFRCEAttackScore,WAFSQLiAttackScore,WAFXSSAttackScore,WorkerCPUTime,WorkerStatus,WorkerSubrequest,WorkerSubrequestCount,WorkerWallTimeUs

Would be great to get this list copied on the clipboard to bring it in IAC in CloudFlare UI https://developers.cloudflare.com/logs/reference/log-fields/zone/ for each zone scoped data set. 

Here's a snippet of code where this can be used

`    new logpushJob.LogpushJob(this, "logpush-job", {
      dataset: "http_requests",
      destinationConf: "https://log-api.eu.newrelic.com/log/v1?Api-Key=&format=cloudflare",
      zoneId: "",
      enabled: true,
      name: "httpRequests",
      logpullOptions: "fields=ContentScanObjResults,ContentScanObjTypes,Cookies,LeakedCredentialCheckResult,ParentRayID,RayID,RequestHeaders,ResponseHeaders,SecurityAction,SecurityActions,SecurityRuleDescription,SecurityRuleID,SecurityRuleIDs,SecuritySources,SmartRouteColoID,UpperTierColoID,ZoneName,CacheCacheStatus,CacheReserveUsed,CacheTieredFill,CacheResponseBytes,CacheResponseStatus,ClientASN,ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientMTLSAuthCertFingerprint,ClientMTLSAuthStatus,ClientRegionCode,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,ClientTCPRTTMs,ClientXRequestedWith,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestProtocol,ClientRequestReferer,ClientRequestScheme,ClientRequestSource,ClientRequestURI,ClientRequestUserAgent,EdgeCFConnectingO2O,EdgeColoCode,EdgeColoID,EdgeEndTimestamp,EdgePathingOp,EdgePathingSrc,EdgePathingStatus,EdgeRequestHost,EdgeResponseBodyBytes,EdgeResponseBytes,EdgeResponseCompressionRatio,EdgeResponseContentType,EdgeResponseStatus,EdgeServerIP,EdgeStartTimestamp,EdgeTimeToFirstByteMs,OriginDNSResponseTimeMs,OriginIP,OriginRequestHeaderSendDurationMs,OriginSSLProtocol,OriginTCPHandshakeDurationMs,OriginTLSHandshakeDurationMs,OriginResponseBytes,OriginResponseDurationMs,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseHeaderReceiveDurationMs,OriginResponseStatus,OriginResponseTime,WAFAttackScore,WAFFlags,WAFMatchedVar,WAFRCEAttackScore,WAFSQLiAttackScore,WAFXSSAttackScore,WorkerCPUTime,WorkerStatus,WorkerSubrequest,WorkerSubrequestCount,WorkerWallTimeUs,EdgeStartTimestamp&timestamps=rfc3339,CacheReserveUsed",
      ownershipChallenge: challange.ownershipChallengeFilename,
    });`
    
    

### Additional information

Please consider doing the same for all LogPush Jobs.
Thanks for your hard work!

**Comment by cmackenzie1** [comment]
Thanks for the issue @Cristian-Vt! We have an endpoint that provides a list of fields and their descriptions available for each dataset. 

https://developers.cloudflare.com/api/operations/get-zones-zone_identifier-logpush-datasets-dataset-fields

Let us know if this meets your use case!
