### ISSUE TITLE
Accessible adult website

### ISSUE THREAD

**Issue by benkrmhe** [cloudflare/cloudflare-docs#11714]
### Example URL(s)

https://video.union.fr/

### Actual Behavior

This website is accessible unless couldflare DNS "Malware Blocking Only" is enhanced

### Expected Behavior

Website blocked

**Comment by kodster28** [comment]
Howdy @benkrmhe, this is actually a documentation repo so we don't have the ability to act on those requests.

I'd encourage you to [use Cloudflare Radar](https://radar.cloudflare.com/categorization-feedback/) to report the categorization issue you're seeing.
