### ISSUE TITLE
Add Email Worker Timeout to Limits

### ISSUE THREAD

**Issue by JacobLinCool** [cloudflare/cloudflare-docs#11723]
### Which Cloudflare product(s) does this pertain to?

Email Routing, Workers

### Subject Matter

Email Worker Timeout

### Content Location

https://developers.cloudflare.com/email-routing/limits/

### Additional information

It seems that the email worker has a wall-clock timeout (about 30 seconds) that was not documented before.

I can verify the behavior by using the following sample code:

```ts
export default {
	email: async (msg) => {
		const T = 60;
		for (let i = 0; i < T; i++) {
			console.log(`${i} seconds have passed`);
			await new Promise((resolve) => setTimeout(resolve, 1000));
		}
		console.log("done");
		msg.setReject("Solved");
	},
} satisfies ExportedHandler;
```

The request is being "Canceled" as the log says:
```
Email from:[email] to:[email] size:5602 @ 11/9/2023, 4:27:16 PM - Canceled
  (log) 0 seconds have passed
  (log) 1 seconds have passed
  (log) 2 seconds have passed
  (log) 3 seconds have passed
  (log) 4 seconds have passed
  (log) 5 seconds have passed
  (log) 6 seconds have passed
  (log) 7 seconds have passed
  (log) 8 seconds have passed
  (log) 9 seconds have passed
  (log) 10 seconds have passed
  (log) 11 seconds have passed
  (log) 12 seconds have passed
  (log) 13 seconds have passed
  (log) 14 seconds have passed
  (log) 15 seconds have passed
  (log) 16 seconds have passed
  (log) 17 seconds have passed
  (log) 18 seconds have passed
  (log) 19 seconds have passed
  (log) 20 seconds have passed
  (log) 21 seconds have passed
  (log) 22 seconds have passed
  (log) 23 seconds have passed
  (log) 24 seconds have passed
  (log) 25 seconds have passed
  (log) 26 seconds have passed
  (log) 27 seconds have passed
  (log) 28 seconds have passed
  (log) 29 seconds have passed
  (log) 30 seconds have passed
  (log) 31 seconds have passed
  (log) 32 seconds have passed
  (log) 33 seconds have passed
```

**Comment by celso** [comment]
This is a global limit of any Worker, not specific to Email triggered ones. See https://developers.cloudflare.com/workers/platform/limits

**Comment by JacobLinCool** [comment]
Hello @celso, thank you for your response.
However, what I mentioned was the wall-clock timeout (i.e., duration limit), which I believe is not what you pointed out in the documentation. I tested this with bundled/unbounded plans months ago before the standard plan was introduced. 
According to the documentation, bundled workers have no duration limit, just like the new standard one. The only limit is on CPU time, and I think that using `Promise` for sleep is not the busy waiting for the CPU.

Update: I might have misunderstood the limit you mentioned. Are you referring to the [30-second HTTP request](https://developers.cloudflare.com/workers/platform/limits#worker-limits) limit for unbound and standard plans? If so, it should be noted that email workers are also treated as if they are receiving an HTTP request. Thank you.

**Comment by celso** [comment]
Yes, that's the limit. Email Workers do not technically exist, we share the exact same platform, pipelines and limits. The technically correct name would be Email triggered workers. I'll see how we can improve the documentation to make this clear.

**Comment by guiruggiero** [comment]
Hi, Cloudflare team (incl. @celso). I know this is an old thread. Looks like the information above changed - per https://developers.cloudflare.com/workers/platform/limits/#duration, "There is no hard limit on duration for HTTP-triggered Workers".

I understand the above comment says email workers share the same runtime, but it's still a bit unclear to me if the no duration limit also applies to email workers (wall-clock time until `message.reply`) - there's no mention in the above link, nor in the Email Routing Limits page in this issue description. Can you please confirm or clarify?

Happy to open a new issue if correcting the documentation is the way to go. Thank you!
