### ISSUE TITLE
Domain redirect

### ISSUE THREAD

**Issue by omeron-the-alien** [cloudflare/cloudflare-docs#11722]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/setup/manage-domains/redirect-domain

### What changes are you suggesting?

Seems like that if the redirect isn't explictly to https://newdomain it doesn't work. 
e.g. redirect olddomain to newdomain.com doesn't work, whereas redirect oldomain to https://newdomain.com does work.
Maybe eveyrone can figure this out, but for me it was taken for granted that you'd add the http part.

**Comment by kodster28** [comment]
Howdy @omeron-the-alien, a bit confused what changes you're requesting here.

The scenario you're describing -- making sure to specify the protocol of the target URL -- is what's in the current documentation (step 3 of the page you're referencing).

Mind elaborating on what change you'd like to see there?

**Comment by kodster28** [comment]
Feel free to re-open with more information, but we don't have enough to know what to change atm.
