### ISSUE TITLE
HLS stream ID3 metadata preservation

### ISSUE THREAD

**Issue by marekdziem** [cloudflare/cloudflare-docs#11725]
### Which Cloudflare product(s) does this pertain to?

Stream

### Subject Matter

HLS header metadata preservation

### Content Location

Ingesting a live stream into cloudflare for distribution doesn't preserve custom HLS header / chunklist metadata inserted at the source

**Comment by kodster28** [comment]
Howdy @marekdziem, this sounds less like a "documentation request" and more like a "feature request".

For this reason, closing out and forwarding along to our internal team as a point of feedback.

**Comment by marekdziem** [comment]
ah great stuff - thanks man!
