### ISSUE TITLE
All `wrangler r2 bucket create` examples are incorrect/misleading

### ISSUE THREAD

**Issue by jake-danton** [cloudflare/cloudflare-docs#11734]
### Example URL(s)

- https://developers.cloudflare.com/browser-rendering/get-started/browser-rendering-with-do/#4-create-a-r2-bucket
- https://developers.cloudflare.com/workers/tutorials/create-finetuned-chatgpt-ai-models-with-r2/#2-upload-a-fine-tune-document-to-r2

### Actual Behavior

`wrangler r2 bucket create` only accepts names that are lowercase and dashes so `wrangler r2 bucket create SCREENSHOTS` should actually be `wrangler r2 bucket create screenshots` and entries like `wrangler r2 bucket create <BUCKET_NAME>` should be clarified by having `wrangler r2 bucket create <bucket-name>`

### Expected Behavior

The docs should have working commands

**Comment by dcpena** [comment]
Hi @JacobDanton, thanks for creating the issue. The all caps for the bucket name is intentional and part of our style guide for how we identify placeholder text; however, I added a note to both pages you mentioned about needing to use lowercase and dashes to help with clarity.
