### ISSUE TITLE
Update Workers AI icon and display AI on the docs "Developer products" home page section

### ISSUE THREAD

**Issue by neynah** [cloudflare/cloudflare-docs#11759]
### Example URL(s)

- https://developers.cloudflare.com/ai/
- https://developers.cloudflare.com/

### Actual Behavior

1. Docs are using brain icon for AI
<img width="1198" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/855341/28146173-092c-4106-8741-f413df6307d2">

2. AI is a new offering on the platform, hasn't been added to "Developer products" yet. Also, "View all" text wraps at too narrow of a width even at full screen size
<img width="1032" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/855341/8c5cea03-f208-4a39-98f7-728c20976324">

3. Nit, load balancing icon is larger than the other icons:
<img width="912" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/855341/70d14ea8-0ba7-4e15-bb28-9564f31914c4">

CC @pdwittig 

### Expected Behavior

1. Docs should be using official sparkly icon for AI
2. Add AI to the Developer products section below R2, reduce grid spacing so the "View all.." text has more width before wrapping
<img width="1445" alt="Welcome to Cloudflare" src="https://github.com/cloudflare/cloudflare-docs/assets/855341/0f372fd2-24b2-4ac7-99ae-2b965e522572">
3. Reduce load balancing icon to match size of other icons

### Additional information

AI icon can be exported from this [figma file](https://www.figma.com/file/lTdLzsapgSCs6MqxZXM6QL/icons_source?type=design&node-id=199-0&mode=design&t=JfVa7f6Y8ClKy2Jt-0), happy to help with that if we need a specific icon size.

**Comment by kodster28** [comment]
Howdy @neynah, for your first suggestion.... the homepage isn't intended to be an exhaustive list of products (both strategically + stylistically). 

So if we added AI, we'd probably need to remove something.

**Comment by neynah** [comment]
Thanks for taking a look at this @kodster28 ! I understand we can't highlight all the products up there but we do think that AI is an important one to include. It's not more critical than what is already there though so if it's not possible we can omit that specific change for now. The icon and visual adjustments would still be important to improve, let me know if the request is clear or the team would like to work with a designer on that.
