### ISSUE TITLE
about the problem of accessing OpenAI website

### ISSUE THREAD

**Issue by lyh648** [cloudflare/cloudflare-docs#11763]
### Example URL(s)

 when I tried to access OpenAI, I encountered a page that said I was banned from accessing. 

### Actual Behavior

I don’t know why this is, I didn’t do anything that violates your rules or laws.

### Expected Behavior

 I really hope to be able to use your website and services, to learn and experience the charm of artificial intelligence. I admire and support your work very much, and I appreciate your time and help.
Looking forward to your reply.
Sincerely yours,
my cloudflare ray ID:8245c75d399f2d44

**Comment by haleycode** [comment]
Hi @lyh648, unfortunately this isn't something the Cloudflare developer documentation team can assist with. You may have better luck reaching out to the site you're trying to access.
