### ISSUE TITLE
I can't find documentation for using Cloudflare as a DNS and Google Workspace (with Google Sites) to make web pages

### ISSUE THREAD

**Issue by neuroradiology** [cloudflare/cloudflare-docs#11760]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Google sites interoperation with Cloudflare DNS and Cloudflare pages

### Content Location

I think there is a need to describe the functionality that Google Sites provides to the Google Workspace customers.

The Google Workspace product is 99% of what my clients need, but the ability to _deploy_ the web pages created in the Google Sites product (especially with a consistent custom naming system) is both difficult and (as far as I can glean) undocumented.

I end up with circular DNS reference errors, SSL errors, and more. 

The ideal solution would be if Cloudflare pages could **directly serve the html documents that I created with Google Sites** (and if you look at the platform, Google Sites are basically just a "document type" with Google Drive).

This is even more challenging due to the intrinsic latency when troubleshooting DNS problems.

**Comment by nevikashah** [comment]
Hey there we don't support and likely won't as Google Sites is its own platform. However, if you can get the output content (html, css, and js files) you can use the Pages Direct Upload feature and bring those to Pages
