### ISSUE TITLE
Clarification of exactly when Cloudflare starts using Cloudflare DNS configuration

### ISSUE THREAD

**Issue by guydawson-xft** [cloudflare/cloudflare-docs#11797]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/setup/account-setup/add-site/

### What changes are you suggesting?

After set 7 of section 1 "When you have finished the Quick Start Guide, click Finish."

presumably at that point while the new DNS configuration will be loaded into Cloudflare it won't be operational until the steps in section 2 are completed. This means there's plenty of time to ensure the new DNS configuration is accurate before progressing to sectioin 2 and making Cloudflare the authorative DNS servers.

Is that correct?

**Comment by kodster28** [comment]
Correct, if you're looking a bit further down the page, DNS resolution only happens after you [update your nameservers](https://developers.cloudflare.com/fundamentals/setup/account-setup/add-site/#2--update-nameservers).
