### ISSUE TITLE
Add pricing example for when using Durable Objects Hibernatable WebSockets API

### ISSUE THREAD

**Issue by nickchomey** [cloudflare/cloudflare-docs#11802]
### Which Cloudflare product does this pertain to?

Durable Objects

### Existing documentation URL(s)

https://developers.cloudflare.com/durable-objects/platform/pricing/#durable-objects-billing-examples

### What changes are you suggesting?

Durable Objects are somewhat expensive, and the pricing structure is difficult to understand. This makes me hesitant to even try to use them. 

So, it would be extremely helpful if you could add a pricing example that makes use of the Hibernatable Websockets API to show how much money you can save.

Ideally it would be an iteration of one of the existing examples - say, the 2nd or 3rd examples

Even better would be if you could create a working code example that we could test and observe the resource usage and cost!

Thanks!

**Comment by Maddy-Cloudflare** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/10826/files#r1334792880
