### ISSUE TITLE
O2O Setup requirements

### ISSUE THREAD

**Issue by rapharochax** [cloudflare/cloudflare-docs#11808]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/saas-customers/provider-guides/wpengine/

### What changes are you suggesting?

I am actually just looking for clarification. 

In that documentation it is said:
"If you use WP Engine and also have a Cloudflare Enterprise plan, you can use your own Cloudflare Zone to proxy web traffic to your Zone first, then WP Engine’s (the SaaS Provider) Zone second"

Is an Enterprise account required by the customer to be able to use O2O when pointing to the SaaS zone? Or is this now enabled for all account levels as long as it is enabled on the SaaS zone?

I ran some tests and it seems to be enabled by default, but my zones are a couple of years old and I might not remember asking to have this enabled, so I wanted to check and if an Enterprise account is not needed, perhaps you could update the doc as well.

Cheers!

**Comment by kodster28** [comment]
Howdy @rapharochax, poked around internally and seems like the documentation is accurate.

If you had any further questions, you might be able to reach out to your account team.

**Comment by hulet** [comment]
If anyone finds this issue in the future 7e9a2d46dd7d35952a65152a39ee4414f0055d8b / #12459 has commit message "Clarified that O2O for WPEngine does not need Enterprise".
