### ISSUE TITLE
Missing indentation for method options

### ISSUE THREAD

**Issue by danbars** [cloudflare/cloudflare-docs#11819]
### Example URL(s)

- https://developers.cloudflare.com/durable-objects/api/transactional-storage-api/#methods

### Actual Behavior

Method options are documented in the same level as the method itslef, and the headers (option names) look the same as the method names.
This makes it hard to scroll through the page and find the content that you look for, especially In pages where there are multiple methods documented, which is most of the pages.

### Expected Behavior

Method options should be indented.
Also consider using different header levels.
See example screenshot

### Additional information

<img width="1294" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/6115771/ee3db942-e6ef-428e-989f-ba1ef0d42af8">

**Comment by Maddy-Cloudflare** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/11897
