### ISSUE TITLE
Potentially malicious domain in address bar of screenshot

### ISSUE THREAD

**Issue by stevennyman** [cloudflare/cloudflare-docs#1181]
The screenshot near the bottom of https://developers.cloudflare.com/workers/tutorials/configure-your-cdn has a potentially malicious domain in the address bar: when I visited workers-tooling[.]cf, I was redirected to a domain that was blocked by uBlock Origin's Badware Risks filter.

**Comment by jrf0110** [comment]
@pedrosousa can we just crop out the address bar?

**Comment by pedrosousa** [comment]
I'd rather keep the address bar, since the text mentions how the URL structure should look like. I'll blur the domain name.
