### ISSUE TITLE
UI/UX Issue: Unreadable three dots in WARP Connector docs

### ISSUE THREAD

**Issue by ikhwanperwira** [cloudflare/cloudflare-docs#11812]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/

### Actual Behavior

I think this screenshot explain that when I click three dots, it shows bug UI/UX. I'm using Mozilla.
![image](https://github.com/cloudflare/cloudflare-docs/assets/72451078/b4f90e2a-529c-4f6d-9a49-e18151f7282d)
 

### Expected Behavior

I expect it will be fixed.

**Comment by kodster28** [comment]
Howdy @wawan-ikhwan, think this should be addressed by the associated PR.

In the meantime, usually you can fix the issue by refreshing the page.
