### ISSUE TITLE
OSX mDNSResponder / Docker Virtualization Framework hogs port 53

### ISSUE THREAD

**Issue by avertx** [cloudflare/cloudflare-docs#11820]
### Which Cloudflare product does this pertain to?

Zero Trust / 1.1.1.1

### Existing documentation URL(s)

cloudflared/ other notes about port 53 usage

### What changes are you suggesting?

might want to mention OSX users for things running on port 53 (cloudflared?) or other DNS forwarders... If Docker is running with Virtualization Framework enabled, OSX runs mDNSResponder is also taking port 53.  Turning it off allows for DNS forwarders/ local DNS servers to run.   Docker folks say its Apple's problem

**Comment by avertx** [comment]
whoops, I think this is more appropriate for 1.1.1.1

**Comment by ranbel** [comment]
@dh-cf

**Comment by ranbel** [comment]
Updated docs with more information on mDNSResponder:
#13983
