### ISSUE TITLE
@cf/stabilityai/stable-diffusion-xl-base-1.0  need support image-to-image & inpaint model & support more parameters.

### ISSUE THREAD

**Issue by mylovelycodes** [cloudflare/cloudflare-docs#11835]
### Which Cloudflare product(s) does this pertain to?

Workers AI

### Subject Matter

@cf/stabilityai/stable-diffusion-xl-base-1.0 

### Content Location

Cloudflare’s AI is fantastic. I am testing the text-to-image model @cf/stabilityai/stable-diffusion-xl-base-1.0 and encountered some issues, so I would like to ask:

Does it only support the parameters ‘prompt’ and ‘num_steps’, or are there other parameters available as well? For example, ‘negative_prompt’? I couldn’t find this information in the Cloudflare AI documentation.

The official XL model supports inpainting mode and image-to-image mode. Are there any plans to support these?

thanks

**Comment by kodster28** [comment]
Out of curiosity, does the new [model page](https://developers.cloudflare.com/workers-ai/models/stable-diffusion-xl-base-1.0/) answer your question?
