### ISSUE TITLE
R2 Product behavior for DLS seems outdated

### ISSUE THREAD

**Issue by throny** [cloudflare/cloudflare-docs#11836]
### Which Cloudflare product does this pertain to?

Data Localization

### Existing documentation URL(s)

https://developers.cloudflare.com/data-localization/

### What changes are you suggesting?

It seems, that it is already possible to specify a jurisdiction or locations for R2 buckets.

**Comment by angelampcosta** [comment]
Docs updated in https://github.com/cloudflare/cloudflare-docs/pull/11869
