### ISSUE TITLE
Please assist me to stop cloudflares

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#11856]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

I have no clue. I want cloudflare to detach from my network and device. My entire goal is to regain my independences, so that calls, web messages, and all sms text messages flow to my device smoothly. I keep seeing orange on my contacts and various places on my device, which indicates cloudflare presences.

### What changes are you suggesting?

I do not work for the penguin, so all the security and big brother watching is unnecessary via cloudflare. What must I do to allow my DNS Remain Google. I seriously want cloudflare to back off. I've called customer service, and deleted Gmail accounts once associated with this platform. This is getting depressing

### Additional information

It's moving my server to Toronto and Canada. I'm in Atlanta, GA 30311. Please let my IP address go free. 
![Screenshot_20231117-070138](https://github.com/cloudflare/cloudflare-docs/assets/151109102/b754f18d-29ff-4166-a242-c1ab961ce8c5)

**Comment by ghost** [comment]
![Screenshot_20231117-073045](https://github.com/cloudflare/cloudflare-docs/assets/151109102/b4158792-3049-49d7-a6e5-ae9c17754492)

**Comment by ghost** [comment]
Another example. Not sure why my device show's as chrome, but to clarify. Does the orange dot represent cloudflare  over my map area. I'm so over it. Why is this happening to me? My social apps are working because my device location isn't available to show. :::::::::(((((

**Comment by haleycode** [comment]
Hi @Jayboyok23, unfortunately as you noted this isn't something that updates to our technical documentation can resolve, so I'll be closing this issue for now.

**Comment by ghost** [comment]
Any suggestions? How can I reach them?
