### ISSUE TITLE
Please allow eval

### ISSUE THREAD

**Issue by brr53** [cloudflare/cloudflare-docs#11891]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

I understand that eval is disabled due to security concern. However, please consider allowing the developer to decide if he/she wants to enable eval.

### Content Location

https://developers.cloudflare.com/workers/runtime-apis/web-standards/

### Additional information

Eval is very useful in many NodeJS applications. I suggest perhaps just displaying a warning to developers who want to use eval instead of completely blocking the feature.

**Comment by kodster28** [comment]
Howdy @brr53, thanks for the request!

I'll forward this along internally... but closing out this issue since it isn't exactly an issue with our documentation.
