### ISSUE TITLE
MAC OS Not functioning properly

### ISSUE THREAD

**Issue by admin-xoxo** [cloudflare/cloudflare-docs#11890]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

Unable to connect to MAC OS after installation

### Content Location

Unable to connect to MAC OS after installation

**Comment by haleycode** [comment]
Hi @admin-xoxo, if you can provide more details on the specific section of Cloudflare's developer documentation that you believe need an update, we'd be happy to take a look. If we don't hear back, I'll need to close out this Issue. Thanks so much!
