### ISSUE TITLE
Product:Cloudflare WARP — Error 1722 MsiInstaller

### ISSUE THREAD

**Issue by 62f** [cloudflare/cloudflare-docs#1190]
### Expected Behavior
Cloudflare WARP service is registered and its TSR-product is entered into Windows 8.1's startup configuration complete their installation (while internet is OFFLINE*) & without errors from execution of supplied 77~Mb file: ```Cloudflare_WARP_Release-x64.msi``` 'Setup Wizard';
eg. ```Click the Finish button to exit the Setup Wizard.
Completed the CloudFlare WARP Setup Wizard```

### Actual Behavior
Dialog: The Setup Wizard allows you to change the way Cloudflare features are inatalled on your computer or to remove it from your computer. Click Next to continue or Cancel to exit the Setup Wizard. You're seconds away from a safer internet.
(many seconds away, in fact)

### Section that requires update
Computer Management.msc says:
There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor. Action InvokeWebview2Bootstrapper, location C:\WINDOWS\Installer\MSI5A98.tmp, command: /silent /install
Log Name: Application
Source:   MsiInstaller
Level:    Error
Keywords: Classic
OpCode:   

### Additional information
</details>
Validating Install
Please wait while Setup Wizard repairs Cloudflare WARP
Status: Installing Windows Firewall Configuration
Registering components
etc...
*failure, backing out installation*
</details>

**Comment by 62f** [comment]
Level    2

Keywords 0x80000000000000

7B35393741364237392D4237392D423242452D344344392DD423835452D3843304237423333323230417D

In Words:
0000: 373935B 37423641 32422D39 342D4542
0010: 2D394443 45353842 3043382D 33423742
0020: 30323233 7D41

In Bytes:
{597A6B79-B2BE-4CD9-B85E-8C0B7B33220A}

**Comment by abracchi-tw** [comment]
Hi @62f! this doesn't seem related to our documentation. closing this issue for now
