### ISSUE TITLE
Program Compatibility Assistant

### ISSUE THREAD

**Issue by 62f** [cloudflare/cloudflare-docs#1191]
### Expected Behavior
CloudFlare WARP 1.1.1.1 TSR during installation should provide complete and useful hyperlinked URLs to correct errors, not truncated, tersely-worded spartan banners whose textual-contents can neither be wholly viewed nor clicked-on ie. hilight/selected for reuse by copy/paste.

### Actual Behavior

###Program Compatibility Assistant
## A digitally signed driver is required

```The WinDivert 2.2 driver [URL: ](https://reqrypt.org/wind)
Basil

Windows blocked the installation of a digitally unsigned
driver. Uninstall the program or device that uses the driver
and check the publisher's website for a digitally signed
version of the driver.```

### Section that requires update
Incomplete URL in popup is not selectable to copy/paste nor is its content functionally as a hyperlink.

### Additional information
<details>
![image](https://user-images.githubusercontent.com/68332197/115702875-72d4a780-a337-11eb-9666-4764dfca3ad2.jpeg)
</details>

**Comment by kkrum** [comment]
I don't believe this is an issue anymore
