### ISSUE TITLE
> @mobicycle do you have a question? It seems like you have pasted irrelevant ChatGPT output into the issue description.

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#11925]
> @mobicycle do you have a question? It seems like you have pasted irrelevant ChatGPT output into the issue description.

As a paying customer, I expect a certain level of professionalism and courtesy, something neither @rozenmd nor @kodster28 have. This type of service appears to be typical of Cloudflare staff. I request to hear from a manager to file a formal complaint about the poor customer service outlined in the response above. If my concerns are not addressed satisfactorily, I will be compelled to cancel all my paid subscriptions.

_Originally posted by @mobicycle in https://github.com/cloudflare/cloudflare-docs/issues/11911#issuecomment-1823266925_

**Comment by kodster28** [comment]
Can you elaborate on your question? Your previous issue did not specify any concern or question.

(I am a manager on the team, btw.)

**Comment by kodster28** [comment]
Howdy @mobicyle, going to close this out as we haven't heard anything from you.

Feel free to re-open with more details.
