### ISSUE TITLE
Add info about Domain Lockdown for Mailchannels

### ISSUE THREAD

**Issue by iBobik** [cloudflare/cloudflare-docs#11945]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/functions/plugins/mailchannels/

### What changes are you suggesting?

Add info about new requirements for Domain Lockdown:
https://support.mailchannels.com/hc/en-us/articles/16918954360845-Secure-your-domain-name-against-spoofing-with-Domain-Lockdown-

### Additional information

> Note that participation in Domain Lockdown is now mandatory for Cloudflare Workers users.

**Comment by deadlypants1973** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/12682
