### ISSUE TITLE
Unclear instructions for nginx in "Restoring original visitor IPs"

### ISSUE THREAD

**Issue by jcerjak** [cloudflare/cloudflare-docs#11954]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

- https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/#nginx
- https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/#web-server-instructions

## Expected outcome

Clear instructions what is currently supported solution to restore original visitor IP with Nginx.

## Current state

Current instructions for Nginx are not clear to me.

In the [nginx section](https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/#nginx) it currently says:

![image](https://github.com/cloudflare/cloudflare-docs/assets/191024/76648074-8146-4941-b25d-4df8ab3d3b61)

Based on this text, it looks like `mod_cloudflare` is a dependency of `ngx_http_realip_module`? This is weird, because I cannot find any reference to nginx in the [mod_cloudflare repo](https://github.com/cloudflare/mod_cloudflare) (it mentions only Apache), or any reference to `mod_cloudflare` in [nginx repo](https://github.com/nginx/nginx/tree/master).

It's unclear whether `ngx_http_realip_module` is still a valid solution for Nginx. Based on text in [web server instruction section](https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/#web-server-instructions), it would appear so. There is a warning that `mod_cloudflare` is deprecated, but it only mentions Apache:

![image](https://github.com/cloudflare/cloudflare-docs/assets/191024/5c2c6a14-3368-4769-a566-28794071e479)

**Comment by zeinjaber** [comment]
@jcerjak - thanks for your feedback!

Please follow https://github.com/cloudflare/cloudflare-docs/pull/13114 for an update.
