### ISSUE TITLE
DNS over HTTPS URL resolves to bizarre IP addresses

### ISSUE THREAD

**Issue by qdm12** [cloudflare/cloudflare-docs#11951]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

- https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-tls/
- https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/

### What changes are you suggesting?

`cloudflare-dns.com` currently resolves to:

- the IPv6 addresses `2606:4700::6810:f8f9` and `2606:4700::6810:f9f9`
- the IPv4 addresses `104.16.248.249` and `104.16.249.249`

This is the case also from different locations, see https://mxtoolbox.com/SuperTool.aspx?action=a%3acloudflare-dns.com&run=toolpage.

These work for DNS over HTTPs, but the documentation seems to point out it should be `1.1.1.1`, `1.0.0.1`, `2606:4700:4700::1111` and `2606:4700:4700::1001`, which is also more consistent with other DNS servers such as Cloudflare Family `family.cloudflare-dns.com` resolving to `1.1.1.3`, `1.0.0.3`, `2606:4700:4700::1113` and `2606:4700:4700::1003`.

In addition, although it likely does not really matter, accessing directly `https://[2606:4700:4700::1111]/dns-query` works without a certificate warning, whereas `https://[2606:4700::6810:f8f9]/dns-query` brings up a certificate warning, and the same goes for the IPv4 addresses such as `104.16.248.249` vs `1.1.1.1`.

Is this meant to be? Can we assume these 4 bizarre IP addresses to be valid, permanent DoH addresses? Is there a reason behind not returning `1.1.1.1`, `2606:4700:4700::1111`, etc. instead?

Thanks!!

**Comment by RebeccaTamachiro** [comment]
Hi @qdm12! I have checked internally and the addresses you mention in the beginning (`2606:4700::6810:f8f9` and `2606:4700::6810:f9f9`, `104.16.248.249` and `104.16.249.249`) are valid, but not permanent. This is expected for the hostname `cloudflare-dns.com`. To configure 1.1.1.1 using a direct IP, use the ones listed on https://developers.cloudflare.com/1.1.1.1/ip-addresses/.
