### ISSUE TITLE
go-tus example on stream upload documentation is incomplete

### ISSUE THREAD

**Issue by gdespirito** [cloudflare/cloudflare-docs#11969]
### Which Cloudflare product does this pertain to?

Stream

### Existing documentation URL(s)

https://developers.cloudflare.com/stream/uploading-videos/upload-video-file/

### What changes are you suggesting?

Innthe go example, using go-tus, is not possible to obtain the stream id of the video, so, the upload works fine, but i can not know where it was uploaded xD

in Node.js exists a 'onAfterResponse' callback that enables the retrieve of the stream-id header, but in go-tus that is not possible. I would appreciate any suggestions to b documented in that page. 

### Additional information

a

**Comment by tsmith512** [comment]
There was an internal discussion here between me, @megaconfidence, and @austin-mc . The go-tus library doesn't reveal the HTTP response headers to the calling function. You can replicate the entire tus.Create() method and catch the `stream-media-id` header when the upload is initially provisioned, or you can use a Direct Creator Upload instead. That feature is an API call which will return a TUS endpoint as well as the video id. I've added the latter as an edit in #18421

**Comment by megaconfidence** [comment]
Thanks @tsmith512, closing this issue for now.
