### ISSUE TITLE
Outdated references

### ISSUE THREAD

**Issue by maxgashkov** [cloudflare/cloudflare-docs#11962]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/

### What changes are you suggesting?

> 1. Log in to Zero Trust and go to Networks > Tunnels.

There is no longer a Network menu entry in the Zero Trust dashboard. It's called Access instead.

**Comment by ranbel** [comment]
![Screenshot 2023-12-04 at 12 46 09 PM](https://github.com/cloudflare/cloudflare-docs/assets/101146722/d0303fe1-ca67-4f95-9cba-ee6e14ab2300)
This was a dashboard bug that has since been fixed.
