### ISSUE TITLE
Documenting Application Cloudflare Access Token duration

### ISSUE THREAD

**Issue by jamesbraza** [cloudflare/cloudflare-docs#12005]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/tutorials/cli/#using-the-token-as-an-environment-variable

### What changes are you suggesting?

Let's add the lifetime of application tokens generated by `cloudflared access token` (e.g. 12-hrs, 24-hrs, infinite)

**Comment by ranbel** [comment]
We can link to the token duration documentation: https://developers.cloudflare.com/cloudflare-one/identity/users/session-management/#session-duration

**Comment by jamesbraza** [comment]
Yeah that would be great!  Also clarifying if `cloudflared access token` makes a global session token or application token in https://developers.cloudflare.com/cloudflare-one/tutorials/cli/#token
