### ISSUE TITLE
(Causa più comune)  502/504 dal server web di origine 502/504 di Cloudflare ​​502/504 dal tuo server web di origine Cloudflare restituisce un errore HTTP 502 o 504 con marchio Cloudflare quando il server Web di origine risponde con un gateway non valido HTTP 502 standard o un errore di timeout del gateway 504:

### ISSUE THREAD

**Issue by Fiori1960** [cloudflare/cloudflare-docs#12021]
### Which Cloudflare product(s) does this pertain to?

Bots

### Subject Matter

https://capitalflow.club/sign

### Content Location

(Causa più comune)  [502/504 dal server web di origine](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-your-origin-web-server)
[502/504 di Cloudflare](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-cloudflare)
[​​](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-your-origin-web-server)502/504 dal tuo server web di origine
Cloudflare restituisce un errore HTTP 502 o 504 con marchio Cloudflare quando il server Web di origine risponde con un gateway non valido HTTP 502 standard o un errore di timeout del gateway 504:

### Additional information

(Causa più comune)  [502/504 dal server web di origine](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-your-origin-web-server)
[502/504 di Cloudflare](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-cloudflare)
[​​](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-your-origin-web-server)502/504 dal tuo server web di origine
Cloudflare restituisce un errore HTTP 502 o 504 con marchio Cloudflare quando il server Web di origine risponde con un gateway non valido HTTP 502 standard o un errore di timeout del gateway 504:

**Comment by kodster28** [comment]
Howdy @Fiori1960, unfortunately we (as Cloudflare) and then our team (specifically a docs team) doesn't have the ability to act on this request.

Your best response is to contact the owner of the site and provide them with the ray ID as well.
