### ISSUE TITLE
Durable Objects example: Remove `await` from call to `storage.put()`?

### ISSUE THREAD

**Issue by mmorearty** [cloudflare/cloudflare-docs#12037]
### Which Cloudflare product does this pertain to?

Durable Objects

### Existing documentation URL(s)

https://developers.cloudflare.com/durable-objects/examples/build-a-counter/

### What changes are you suggesting?

Near the bottom of the example is this line of code:

```js
await this.state.storage.put("value", value);
```

Based on your explanation of [Output Gates](https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/#part2outputgates), I think the `await` at the start of the line here can be safely removed, right?

**Comment by Maddy-Cloudflare** [comment]
Addressed here: https://github.com/cloudflare/cloudflare-docs/pull/12047

Thank you!
