### ISSUE TITLE
Add instructions on how to access bindings with various frameworks using Javascript

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/cloudflare-docs#12041]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Various framework guides

### Content Location

Where applicable in our [framework guides](https://developers.cloudflare.com/pages/framework-guides/) we provide instructions on how to access bindings.

Such instructions currently only use TypeScript, they should be updated so that they show both Javascript and Typescript (each with its own separate section).

**Comment by KimJ15** [comment]
Hi @dario-piotrowicz is this an issue you'd like to keep open? We'll provide JS automatically when Kian rebases https://github.com/cloudflare/cloudflare-docs/pull/16357

**Comment by dario-piotrowicz** [comment]
Hi @KimJ15, thanks for the ping! Kian's component looks amazing! it is most likely going to solve the issue here

I'll close this for now and will reopen it if needed! thanks again! 😄
