### ISSUE TITLE
WARP intune deployment

### ISSUE THREAD

**Issue by YQX77** [cloudflare/cloudflare-docs#12044]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com:2083/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/#windows

### What changes are you suggesting?

Intune deployment not accurate; please work to correct it

### Additional information

not able to deploy based on the process outlined

**Comment by ranbel** [comment]
Hi @YQX77, we have updated the instructions in #12298. Feel free to open a new issue if you have additional documentation suggestions!
