### ISSUE TITLE
How to add subdomain to preview branch without removing production

### ISSUE THREAD

**Issue by paul-nallet** [cloudflare/cloudflare-docs#12053]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

 subdomain to preview branch

### Content Location

https://developers.cloudflare.com/pages/platform/custom-domains/#add-a-custom-domain

**Comment by WalshyDev** [comment]
Hey,

You can follow this guide to do that: https://developers.cloudflare.com/pages/how-to/custom-branch-aliases/

Let us know if this helped or wasn't what you were looking for :)

**Comment by paul-nallet** [comment]
Kind of,I would manage a primary domain app.mydomain.com and a second one Develop.app.mydomain.com I guess In this part of documentation it’s limited to just a subdomain and only one entry point ? ILe 1 déc. 2023 à 21:59, Daniel Walsh ***@***.***> a écrit :﻿
Hey,
You can follow this guide to do that: https://developers.cloudflare.com/pages/how-to/custom-branch-aliases/
Let us know if this helped or wasn't what you were looking for :)

**Comment by WalshyDev** [comment]
You can have both, there's no restriction there :)

I assume you already have your production one setup so just add a new domain for the develop branch per that guide.
