### ISSUE TITLE
Are there earlier versions WARP?

### ISSUE THREAD

**Issue by Kotofisa** [cloudflare/cloudflare-docs#12055]
### Example URL(s)

https://1.1.1.1/

### Actual Behavior

Please excuse my English - it is not my native language, I live in Ukraine and use a translator program.
On my iMac the operating system version is 10.11.6. Warp, which I downloaded from your site https://1.1.1.1/, is intended for a later version of Mac OS. Please tell me if you have a version that is suitable for my Mac OS X EL Capitan? 
Unfortunately, I cannot install the latest version of the operating system on my computer - the hardware does not allow it.
Thank you!
![Знімок екрана 2023-12-02 о 22 03 16](https://github.com/cloudflare/cloudflare-docs/assets/152735652/8adb3d6f-778f-48ea-81c4-7a973634088f)

### Expected Behavior

Older version of the program

**Comment by cascadingstyletrees** [comment]
Not at this time, the earliest possible MacOS release is Mojave 10.14.

Please see: https://developers.cloudflare.com/warp-client/get-started/

**Comment by Kotofisa** [comment]
> Not at this time, the earliest possible MacOS release is Mojave 10.14.
:(((
