### ISSUE TITLE
Cloudflare Workers OpenAI stream example isn't streaming

### ISSUE THREAD

**Issue by ianschmitz** [cloudflare/cloudflare-docs#12060]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/examples/openai-sdk-streaming/

### What changes are you suggesting?

This example should pipe the stream to the response. It is currently awaiting the entire stream before returning the response which defeats the whole purpose of using a stream.

Your worker streams docs has the right idea: https://developers.cloudflare.com/workers/runtime-apis/streams/#streams

**Comment by toastli** [comment]
For anyone else who is struggling to do this i achieved it by using `ctx.waitUntil`:
```javascript

export default {
    async fetch(request, env, ctx) {

        const openai = new OpenAI({
            apiKey: env.OPENAI_API_KEY,
        });

        // Create a TransformStream to handle streaming data
        let { readable, writable } = new TransformStream();
        let writer = writable.getWriter();
        const textEncoder = new TextEncoder();

        ctx.waitUntil((async () => {
            const stream = await openai.chat.completions.create({
		    model: 'gpt-3.5-turbo',
		    messages: [{ role: 'user', content: 'Tell me a story' }],
                    stream: true,
            });

            // loop over the data as it is streamed and write to the writeable
            for await (const part of stream) {
                writer.write(textEncoder.encode(part.choices[0]?.delta?.content || ''));
            }
            writer.close();
        })());

        // Send the readable back to the browser
        return new Response(readable, {
            headers: {
                "content-Type": "text/plain"
            },
            status: 200,
        });
    },
};

```

**Comment by josealvarez97** [comment]
@ianschmitz @Bradovman At work we have a situation where the example in https://developers.cloudflare.com/workers/runtime-apis/streams/#streams works in production, but not locally. Similarly, we have our own product's codebase which is able to stream in production, but not locally. In both cases we're fetching OpenAI's API (a chat completion). 

I suspect this might be an issue closely related to OpenAI's API, given that the same pattern occurs with different approaches to streaming the code. In one case we do it with the TransformStream class like in the toy example, but in another we simply forward the response via our proxy.

Do you have any insights?

**Comment by ianschmitz** [comment]
@josealvarez97 i'd suggest you open a new issue so as to not confuse this one.

**Comment by kodster28** [comment]
> @ianschmitz @Bradovman At work we have a situation where the example in https://developers.cloudflare.com/workers/runtime-apis/streams/#streams works in production, but not locally. Similarly, we have our own product's codebase which is able to stream in production, but not locally. In both cases we're fetching OpenAI's API (a chat completion).
> 
> I suspect this might be an issue closely related to OpenAI's API, given that the same pattern occurs with different approaches to streaming the code. In one case we do it with the TransformStream class like in the toy example, but in another we simply forward the response via our proxy.
> 
> Do you have any insights?

@josealvarez97, I believe that's related to the work happening in https://github.com/cloudflare/workers-sdk/pull/5713.

We've added a warning to our docs temporarily in #14240
