### ISSUE TITLE
failed to recognize JSON request: ‘json: cannot unmarshal string into Go value of type graphql.httpPostBody

### ISSUE THREAD

**Issue by minuk0612** [cloudflare/cloudflare-docs#1207]
`function fetchAPI(url, email, apiKey, zoneTag) {

let request = new Request(url)
let query = {“query”:"{\n viewer {\n zones(filter: { zoneTag: " + zoneTag + " }) {\n httpRequests1dGroups(\n orderBy: [date_ASC]\n limit: 1000\n filter: { date_gt: “2019-07-15” }\n ) {\n date: dimensions {\n date\n }\n sum {\n cachedBytes\n bytes\n }\n }\n }\n }\n}",“variables”:{}}`

       let init = {
            method: 'POST',
            body: JSON.stringify(query)
        }
        request.headers.set('x-auth-key', apiKey)
        request.headers.set('x-auth-email', email)

        return fetch(request, init)
    }`
it is giving me following error for graphql query

{“data”:null,“errors”:[{“message”:“failed to recognize JSON request: ‘json: cannot unmarshal string into Go value of type graphql.httpPostBody’”,“path”:null,“extensions”:{“timestamp”:“2021-04-23T10:51:47.131471437Z”}}]}

i referred this https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics

I cannot understand where the problem is it showing same for every query

**Comment by KimJ15** [comment]
👋 @minuk0612   I'm sorry, we only take care of improvements to developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com for assistance with your question!
