### ISSUE TITLE
openAI worker guide is outdated

### ISSUE THREAD

**Issue by freezerain** [cloudflare/cloudflare-docs#12080]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/tutorials/openai-function-calls-workers/

### What changes are you suggesting?

openAi reworked their sdk to v4 
for example this importing statement produce error on wrangler deploy
```
import { Configuration, OpenAIApi } from "openai";
import fetchAdapter from "@vespaiach/axios-fetch-adapter";
```

as for date current schema is 
```
import OpenAI from 'openai';
```
The docs should use new api or target old v3 api when ```npm install openai```
migration example:
https://github.com/openai/openai-node/discussions/217

### Additional information

also using 3d party adapter lib that was not updated for more then a year in official docs is a strange choise but whatever

**Comment by kodster28** [comment]
Howdy @freezerain, this should've been addressed by #12412 (and the live guide should be updated).
