### ISSUE TITLE
You are interfering with the work of an international human rights lawyer

### ISSUE THREAD

**Issue by cdoebbler** [cloudflare/cloudflare-docs#12101]
### Example URL(s)

I am trying to access the website of the Inter-American Court of Human Rights at https://corteidh.or.cr/ but constantly get an error saying I am blocked. I am an American attorney and member of the bars of several states and a litigator before the Inter-American Court of Human Rights. I am currently in Dubai, UAE at the climate conference (COP28) and trying to urgently access the Court's website for an urgent filing. You blocking my access causes me and my clients serious harm and substantial damages. You have now been informed of your wrongful action and how it continues to cause damages.     

### Actual Behavior

Website does not open, error message says my access is blocked. Below I have uploaded a link to the website.
![20231206_130438](https://github.com/cloudflare/cloudflare-docs/assets/35331089/fc5cb0a6-3a48-488d-a3dd-7da24793cc73)

### Expected Behavior

Should open website.

### Additional information

Cloudflare Ray ID: 831355e9194d12be • Your IP: 5.195.84.238 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

**Comment by kodster28** [comment]
Howdy @cdoebbler, understand the frustration on your end.... but there's nothing we (as Cloudflare) and then our team (specifically a docs team) can do for this request.

Your best response is to contact the **owner of the site** (as mentioned in the `What can I do to resolve this` section) and provide them with the ray ID as well. Then, they'd need to follow the process described in [this guide](https://developers.cloudflare.com/waf/managed-rules/handle-false-positives/).

**Comment by cdoebbler** [comment]
Dear Kody,

You were contacted because the owner has indicated your company is
responsible for security of the site.

Regards,
Curtis Doebbler
