### ISSUE TITLE
Cloudflare is out of date, NOT my browser

### ISSUE THREAD

**Issue by Dan-Essin** [cloudflare/cloudflare-docs#12123]
### Example URL(s)

https://dash.cloudflare.com/login

### Actual Behavior

UPdated Firefox to 120.0.1
Went to ChatGPT
Got this message:
Your browser is out of date!
Update your browser to view this website correctly. [More Information.](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#browser-support)
![2023-12-06_10h41_09](https://github.com/cloudflare/cloudflare-docs/assets/1776053/b4f0ffc9-ffc2-4612-8fbc-b775317e93c8)

### Expected Behavior

I expect that web sites will work as expected and not be denied access because of bugs in the middleware that they have chosen to use,

### Additional information

Cloudflare is obviously out of touch with reality or lacks sufficient staff to keep up with the rapidly changing browser environment.
Perhaps, if they can't keep up with the changes, they should be less restrictive about what browsers are acceptable. 
Either that, or someone has just broken cloudflare by introducing some new "feature" without adequate testing.

**Comment by kodster28** [comment]
Howdy @Dan-Essin, noted and hear your frustration. I'll forward internally.

Unfortunately, we -- as a documentation team -- don't exactly have the ability to address this, so closing out this issue.

**Comment by kodster28** [comment]
Not entirely sure this helps, solves your issue, but sometimes browser extensions can cause you to get flagged by Cloudflare security.

We're adding more details in #12143
