### ISSUE TITLE
How to measure specificity in  route pattern

### ISSUE THREAD

**Issue by andreas-lundgren-storytel** [cloudflare/cloudflare-docs#1212]
### Expected Behavior
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/platform/routes.md#matching-behavior

Section _When more than one route pattern could match a request URL, the most specific route pattern wins. For example, the pattern www.example.com/* would take precedence over *.example.com/* when matching a request for https://www.example.com/._

Could we please clarify how specificity is calculated? If it is the number of wildcards and/or also the number of URL segments? Will `https://www.example.com/path1/*` win over `https://www.example.com/*`? It's a struggle that several workers cannot be applied in order, such as Java Servlets, and defining this better would really help. We can just guess by testing several times what are rules and what is random coincidences.

### Actual Behavior
Expect documentation to describe a deterministic behaviour for more scenarios.

### Section that requires update
The section about specificity under "Matching BEhaviour" as linked above.

### Additional information
-

**Comment by andreas-lundgren-storytel** [comment]
A more logically hard example is `*.example.com/path1/*` vs `www.example.com/*`

**Comment by kristianfreeman** [comment]
cc @rita3ko who would be the right person to document the specifics of route matching here?
