### ISSUE TITLE
configure-bucket-policies-to-allow-cloudflare-ip-addresses example error

### ISSUE THREAD

**Issue by charlesmims** [cloudflare/cloudflare-docs#12182]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/third-party-software/others/configuring-an-amazon-web-services-static-site-to-use-cloudflare/#configure-bucket-policies-to-allow-cloudflare-ip-addresses

I wasn't sure what Product to list for this.

### What changes are you suggesting?

It looks like the example got changed by mistake.

It says "For the step where you enter the policy in the Bucket policy editor, use this sample to fill out the needed JSON code..."
but the example is `curl -I -L example.com` with a 301 response message.

**Comment by kodster28** [comment]
This is now fixed!
