### ISSUE TITLE
Does the wrangler CLI still work this way?

### ISSUE THREAD

**Issue by pcmill** [cloudflare/cloudflare-docs#12188]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/get-started/direct-upload/#wrangler-cli

### What changes are you suggesting?

When I run the command to deploy my website I get:
```
$ npx wrangler pages deploy .svelte-kit/cloudflare --branch=production
error: Found argument 'pages' which wasn't expected, or isn't valid in this context

USAGE:
    wrangler [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help
```

I have deployed my website many times with this but now it does not work anymore.

**Comment by KianNH** [comment]
That error looks like it's from Wrangler 1, which is legacy and deprecated. You will want to upgrade to Wrangler 3.

https://developers.cloudflare.com/workers/wrangler/install-and-update/

**Comment by pcmill** [comment]
Thank you! I missed this:
```
Running npx wrangler will use the latest version of Wrangler except when there is already a Wrangler version installed in the current folder. In this case, it will use the locally installed version instead.
```

On this page: https://developers.cloudflare.com/workers/wrangler/install-and-update

**Comment by deadlypants1973** [comment]
Hi @pcmill , unless there's more context here, looks like issue has been solved and I can close this? :)
