### ISSUE TITLE
Different models and ai.run parameters documentation.

### ISSUE THREAD

**Issue by gerhardcit** [cloudflare/cloudflare-docs#12184]
### Which Cloudflare product does this pertain to?

Workers AI

### Existing documentation URL(s)

https://developers.cloudflare.com/workers-ai/tutorials/build-a-retrieval-augmented-generation-ai/

### What changes are you suggesting?

You are using: `@cf/meta/llama-2-7b-chat-int8` in the general query, 
but using `cf/baai/bge-base-en-v1.5` in the `pp.post('/notes', async (c) => {` sections

and no explanation why and how the `ai.run` paramaters are different for the two.

Can you explain the reasons why better and assist in deciding which models to use in which use cases.

**Comment by kodster28** [comment]
Howdy @gerhardcit, apologies this took a while to get to, but updated the tutorial to provide more details around the distinctions between the two models (and why they're used).
