### ISSUE TITLE
I moved DNS to cloudflare. Now it is not working anymore. But it was working. I didnt changed anything. 

### ISSUE THREAD

**Issue by reinterpret** [cloudflare/cloudflare-docs#12189]
### Example URL(s)

https://neurologinnen-netzwerk.com

### Actual Behavior

Browser Message: "Not Found"

### Expected Behavior

Show Site

**Comment by kodster28** [comment]
Howdy @reinterpret, as this is a documentation repo, we can't really do much for troubleshooting your issues. I'd suggest [contacting Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or creating a topic in the [Cloudflare Community](https://community.cloudflare.com).

That being said, if you're experiencing issues, sometimes it can be helpful to [pause Cloudflare](https://developers.cloudflare.com/fundamentals/setup/manage-domains/pause-cloudflare/) and see if that fixes your issue.
