### ISSUE TITLE
Restoring visitor IPs instruction for Envoy Gateway

### ISSUE THREAD

**Issue by robd003** [cloudflare/cloudflare-docs#12196]
### Which Cloudflare product(s) does this pertain to?

Reference Architecture

### Subject Matter

How to limit X-Forwarded-For to CloudFlare IPs only in Envoy Gateway config

### Content Location

https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/

### Additional information

https://github.com/envoyproxy/gateway
https://www.cloudflare.com/ips/

**Comment by kodster28** [comment]
Heyo @robd003, _think_ I'm addressing this in #14371... any issues you see with the verbiage / process there?

**Comment by robd003** [comment]
@kodster28 I'd really like to limit the parsing to *only* CloudFlare IP ranges. My issue is if someone is connecting to the servers directly without CloudFlare I wouldn't want to give them the ability to spoof the client IP.

Example issue: imagine a bot scanning the web for https://a.random.ip.here/login/ and just trying random user / pass combos

If they send a spoofed CF-Connecting-IP then it would be hard to ban / report that bad actor.

**Comment by kodster28** [comment]
Howdy @robd003, from your question and poking around in [GitHub](https://github.com/envoyproxy/gateway/issues/2288), sounds like this is really more of a feature request for the Envoy Gateway itself.

We do offer some recommendations on [protecting your origin server more generally](https://developers.cloudflare.com/fundamentals/basic-tasks/protect-your-origin-server/) that talks through how to restrict access... but what you're describing sounds out of the scope of what we currently do or would in the future have a documented solution for.

In addition to following up with the Envoy Gateway folks, you might try reaching out in the [Cloudflare Community](https://community.cloudflare.com). Can't guarantee anything'll happen from that, but it'd at least have more visibility than an issue in our repo.

**Comment by kodster28** [comment]
Based on ^^^, going to close this out as completed w/ the associated PR (which adds instructions on restoring visitor IPs, but not on limiting parsing)
