### ISSUE TITLE
Cloudflare Stream documentation and API reference are in big disconnect from each other

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [cloudflare/cloudflare-docs#12221]
### Which Cloudflare product does this pertain to?

Stream

### Existing documentation URL(s)

- The more article-like version: https://developers.cloudflare.com/stream/
- Technical API reference: https://developers.cloudflare.com/api/operations/stream-videos-list-videos

### What changes are you suggesting?

The guide-style documentation and api reference do not seem to portray the same version of an API. For example, API reference doesn't have direct file uploads that are not using tus. But the documentation does show an example of such request but doesn't say anything about the response format.

This simple and upfront issue might indicate that there are more inconsistencies between documentation and api reference, but I have not researched it deeper yet.

**Comment by kodster28** [comment]
Howdy @JohnTheCoolingFan, _technically_ the teams that own this repo & the API docs are separate from each other.

Passing this feedback along to that team... but closing out this issue as that's as much as we can do on our end.
