### ISSUE TITLE
Not able to install in ubuntu 23.10

### ISSUE THREAD

**Issue by karthikvijay5227** [cloudflare/cloudflare-docs#12240]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1, WARP Client

### Subject Matter

Installation in Ubuntu 23.10

### Content Location

Under linux installation

**Comment by RebeccaTamachiro** [comment]
👋 @karthikvijay5227 Thanks for reaching out. We only take care of [developers.cloudflare.com](http://developers.cloudflare.com/) documentation in this repo. 
Would you mind clarifying which of the following guides you were trying to use and providing more details on what difficulties you've been having? Are you getting any error messages, for example?

https://developers.cloudflare.com/1.1.1.1/setup/linux/
https://developers.cloudflare.com/warp-client/get-started/linux/

**Comment by igor-sx** [comment]
Instructions followed: https://developers.cloudflare.com/warp-client/get-started/linux/
Error message: `E: Unable to locate package cloudflare-warp
`
OS: Ubuntu 23.10 x86_64
