### ISSUE TITLE
[D1] Remix + Pages local dev

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/cloudflare-docs#12250]
### Which Cloudflare product does this pertain to?

D1

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/functions/bindings/#interact-with-your-d1-databases-locally

### What changes are you suggesting?

The webpage [here](https://developers.cloudflare.com/pages/functions/bindings/#interact-with-your-d1-databases-locally) recommends you set `--d1=NORTHWIND_DB` when running `npx wrangler pages dev`. If you do this, you won't be using the same DB for `wrangler d1` CLI calls as the DB that Pages uses.

What you should actually do is set `--d1` to a real UUID, that you use in your wrangler.toml.

For example:
```
# wrangler.toml
[[d1_databases]]
binding = "DB"                                        
database_name = "videos"
database_id = "aacb0eb1-2b7f-4b13-a456-bad11ebb1a78"   
preview_database_id = "aacb0eb1-2b7f-4b13-a456-bad11ebb1a78" 
```

Then your package.json `start` command becomes:
```
// package.json
"start": "wrangler pages dev --compatibility-date=2023-06-21 ./public --d1=aacb0eb1-2b7f-4b13-a456-bad11ebb1a78",
```

Loading your data becomes
```
npx wrangler d1 execute videos --file=./schema.sql --local 
```

The downside is `context.env` becomes gross:
```
//index.tsx

export interface Env {
  "aacb0eb1-2b7f-4b13-a456-bad11ebb1a78": D1Database;
}

export const loader = async ({ context }: LoaderFunctionArgs) => {
  const DB = (context.env as Env)["aacb0eb1-2b7f-4b13-a456-bad11ebb1a78"];
  const result = await DB.prepare(
    `SELECT 
    name
FROM 
    sqlite_schema
WHERE 
    type ='table' AND 
    name NOT LIKE 'sqlite_%';
`
  ).all();
  console.log("result: ", result);
  return json({ ...result });
};
```

### Additional information

What we should actually do is fix the name wrangler uses to be the same, though.

**Comment by kodster28** [comment]
Addressed by #12283
