### ISSUE TITLE
WARP install on macOS: add instructions on how to disable mDNSResponder

### ISSUE THREAD

**Issue by joaocc** [cloudflare/cloudflare-docs#12269]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

* https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/troubleshooting/client-errors/#cf_dns_proxy_failure

Current documentation is not specific on how to disable common cases (mDNSResponder, docker, ...) which is a blocker on WARP deployments

### What changes are you suggesting?

The documentation doesn't mention anything concrete for mDNSResponder which is a common component of macOS.

There is a community solution that may work (https://community.cloudflare.com/t/zerotrust-unable-to-connect-port-53-bound/486081/16) but it would be better to have it as a cloudflare-vetted solution, as it relates to an OS component.

**Comment by ranbel** [comment]
@dh-cf

**Comment by ranbel** [comment]
Updated docs with more information on mDNSResponder:
#13983
