### ISSUE TITLE
Issues with DMARC wizard when an existing DMARC record already exists

### ISSUE THREAD

**Issue by f3575115-4ae9-4a6c-a2ad-8bf54ce2cbb3** [cloudflare/cloudflare-docs#12267]
### Example URL(s)

```
https://dash.cloudflare.com/<account-id>/<zone-name>/email/dmarc-management/dmarc-reports/dmarc/wizard
```

### Actual Behavior

1. The displayed value of the updated record is truncated.  On hover there is no tooltip to show the full value.  Because the new `rua` value is shown first, there's no way to verify that the existing `rua` is still present.
2. When editing the updated entry (via the ellipsis menu -> Edit at the right edge of the new entry), the user is taken to the DNS records screen with no records highlighted/editable. 

### Expected Behavior

1. There would be some way to see the full value of the updated record, to let the user confirm both the new and existing `rua` values are still present.
2. The updated record's edit link would open the DNS console with the new record editable.

**Comment by kodster28** [comment]
Howdy @f3575115-4ae9-4a6c-a2ad-8bf54ce2cbb3, can pass along this feedback internally... but going to close out this issue b/c this is a documentation repo and the scope of that fix is outside our docs or anything in GitHub.
