### ISSUE TITLE
Fundamentals incorrectly state only `cdn-cgi` is added

### ISSUE THREAD

**Issue by Le0Developer** [cloudflare/cloudflare-docs#12290]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/#using-a-csp-with-cloudflare

### What changes are you suggesting?

The section states: `Cloudflare does not: [...] Modify URLs (besides adding the /cdn-cgi/ endpoint).`

This is no longer correct, as [Cloudflare Fonts](https://developers.cloudflare.com/speed/optimization/content/fonts/#cloudflare-fonts) is adding an additional `/cf-fonts/` endpoint.

**Comment by angelampcosta** [comment]
@Le0Developer Thank you for bringing this up. We addressed the issue in this PR https://github.com/cloudflare/cloudflare-docs/pull/12313
