### ISSUE TITLE
coingecko is not loading

### ISSUE THREAD

**Issue by ArnoudvanderPlas** [cloudflare/cloudflare-docs#12294]
### Example URL(s)

coingecko.com

### Actual Behavior

can't reach website

### Expected Behavior

n

### Additional information

n

**Comment by kodster28** [comment]
Howdy @ArnoudvanderPlas, understand the frustration on your end.... but there's nothing we (as Cloudflare) and then our team (specifically a docs team) can do for this request.

Your best response is to contact the **owner of the site** (as mentioned in the `What can I do to resolve this` section) and provide them with the ray ID as well. Then, they'd need to follow the process described in [this guide](https://developers.cloudflare.com/waf/managed-rules/handle-false-positives/).
