### ISSUE TITLE
The Deploy A Hono Site Guide is missing instructions to install a NodeJs package, `npm-run-all`

### ISSUE THREAD

**Issue by wasmithee** [cloudflare/cloudflare-docs#12306]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-hono-site/#create-a-new-project

### What changes are you suggesting?

Instruct the user to run the following NPM command after updating the scripts portion of their package.json file:
` npm install npm-run-all --save-dev`

**Comment by kodster28** [comment]
Thanks for reporting, @wasmithee. Definitely feel free to forward any feedback to me internally as well :)
