### ISSUE TITLE
Improve docs on local dev with Pages and D1

### ISSUE THREAD

**Issue by davidysoards** [cloudflare/cloudflare-docs#12360]
### Which Cloudflare product does this pertain to?

Pages and D1

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/functions/bindings/#interact-with-your-d1-databases-locally
and
https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages

### What changes are you suggesting?

The 2 sections above are not directly linked and it would be nice if they were.
Working thru the Pages docs [here](https://developers.cloudflare.com/pages/functions/bindings/#interact-with-your-d1-databases-locally) this statement:

> While developing locally, interact with a D1 database by adding --d1 <BINDING_NAME>=<DATABASE_ID> to your run command.

led me to believe I needed to add the `--d1` arg to my start script like so
```
npx wrangler pages dev --d1 DB=the-id-of-your-D1-database-goes-here -- pnpm run dev
```
which does not work, but the terminal output makes it seem like it did, which definitely added to my confusion.

<img width="824" alt="Screenshot 2023-12-23 at 1 44 54 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/26875701/4b840bfe-1734-4aba-abe0-a07579adef34">

A couple lines later the `wrangler.toml` file is suddenly mentioned even tho it hasn't been before. At that point a link to [this section](https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages) would be super helpful.

Thank you!

D1 on Pages are so cool, along with wrangler dev the DX is just 🤌

**Comment by ibrahimkhled** [comment]
# If you are only using Pages + D1, you only need the below in your wrangler.toml to interact with D1 locally.
[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "YOUR_DATABASE_NAME"
database_id = "the-id-of-your-D1-database-goes-here" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development

**Comment by davidysoards** [comment]
Thank you!
