### ISSUE TITLE
Is this still valid?  It takes down my site every time I try it. 

### ISSUE THREAD

**Issue by jajanes** [cloudflare/cloudflare-docs#12370]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/waf/custom-rules/use-cases/allow-traffic-from-specific-countries/

### What changes are you suggesting?

When I try this, my web application is completely blocked from all points.

**Comment by pedrosousa** [comment]
Hi @jajanes 
Yes, the example is still valid.

Some troubleshooting tips:
- If you are following the provided example, make sure you include `not` in your expression:
    `(not ip.geoip.country in {"<COUNTRY_1>" "<COUNTRY_2>" ...})`

- Geolocation data might be outdated. This data is provided by MaxMind, Inc. 
    You can test country identification using their demo — enter the visitor IP address you wish to test in [GeoIP2 Web Service Demo](https://www.maxmind.com/en/geoip2-precision-demo).
    If the country information is incorrect, you should report it to MaxMind using [Submit GeoIP Data Corrections](https://www.maxmind.com/en/geoip-data-correction-request).
