### ISSUE TITLE
Add a documentation link to R2 "Getting Started" page

### ISSUE THREAD

**Issue by rg3h** [cloudflare/cloudflare-docs#12373]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://dash.cloudflare.com/7911e706875d964e496227e06943c10e/r2/plans

### What changes are you suggesting?

https://dash.cloudflare.com/7911e706875d964e496227e06943c10e/r2/plans  is titled "Getting Started with R2" and describes the low costs for using R2, but does not explain what R2 is/gets you.
This link is accessible from the sidebar and may be the first path new developers access when exploring R2
I suggest you add a link on this page to your documentation on R2. Specifically:
https://developers.cloudflare.com/r2/

**Comment by kodster28** [comment]
Howdy @rg3h, thanks for the feedback!

This _technically_ is a request to update the dashboard UI which is outside of the scope of our repo.

Created an internal ticket for your request, but closing out this external one as I've addressed it as best I can.

**Comment by rg3h** [comment]
Thanks!
