### ISSUE TITLE
I need help to connect my website to my domain

### ISSUE THREAD

**Issue by webuypropertiesllc** [cloudflare/cloudflare-docs#12392]
### Example URL(s)

https://webuypropertiesllc.com

### Actual Behavior

Please i want to connect my website to my Domain and also have access to my email 
www.webuypropertiesllc.com
I need IP Address
MX Record for my email
Website IP address:
CNAME record entry
Please I want you to help me, i have been on this for two weeks 
Thanks 
Michael
3177015155

### Expected Behavior

Please i want to connect my website to my Domain and also have access to my email 
www.webuypropertiesllc.com
I need IP Address
MX Record for my email
Website IP address:
CNAME record entry
Please I want you to help me, i have been on this for two weeks 
Thanks 
Michael
3177015155

### Additional information

https://domains.google.com/registrar/webuypropertiesllc.com/dns?pli=1&authuser=2&ci=1

Hi Oluwaseyi,

My name is Paul and I took over my colleagues' case since she's out of the office. Using custom name servers from cloudflare disabled your domain DNS control panel. If you want to connect the website without cancelling the Google Workspace DNS records(which affected and stopped your emails), Please get the following from CloudFlare:

Website IP address:
CNAME record entry:
If you have other questions or if your concern was not answered to your satisfaction, feel free to [contact us](http://domains.google.com/contactus) again.

Thanks!
Paul
The Google Domains Support Team

**Comment by kodster28** [comment]
Howdy @webuypropertiesllc, unfortunately as a documentation repo we can't provide technical support.

I'd recommend reviewing the following:
- Our guided Learning Path on [getting started with Cloudlare](https://developers.cloudflare.com/learning-paths/get-started/)
- The [Cloudflare Community](https://community.cloudflare.com), where you can get support from fellow users or community MVPSs
- How to [contact Cloudflare support](https://developers.cloudflare.com/support/contacting-cloudflare-support/)

**Comment by webuypropertiesllc** [comment]
Hello I don't understand as you PRO customer you tell me you cant help me
DO you know how many days i have been roam on your website trying to figure
out how to help myself just because i'm not a tech savvy
There was no customer service to cnumber to call still i still manage to
create my issue and then What????????? , you telling me Whatttttttt
I don't understand, please
Can you explain it to me
I register with google and they moved my domain to you. The next thing is I
have wanted to connect my website to my domain for over two weeks now and
it has become a problem and you tell me you can't help . Who does that
??????/
Even on your site they asked my to subscribe to what i don't need still i
did just to have a solution to my two weeks plus problem
All i need is my IP Address, CNAME and my MX record for two week no where
to get this
Its from one page to another and still not get the solution
I'm tired and i need this fixed to be able to move my business forward
So help

Otunba

3177015155
