### ISSUE TITLE
Playground Preview Failure

### ISSUE THREAD

**Issue by vindicatorr** [cloudflare/cloudflare-docs#12414]
### Example URL(s)

https://workers.cloudflare.com/playground

### Actual Behavior

`{"error":"PreviewRequestFailed","message":"Token not found","data":{}}`

### Expected Behavior

Preview of default worker template

### Additional information

![20240105011519_TokenNotFound_Screenshot](https://github.com/cloudflare/cloudflare-docs/assets/4075850/69b950b7-839b-4270-84cd-feb983604189)
https://www.reddit.com/r/CloudFlare/comments/176a1zu/cloudflare_workers_issue_help/

**Comment by kodster28** [comment]
Howdy @vindicatorr, thanks for raising and going to pass this along internally.

As this _technically_ falls out of the scope of our team's responsibilities and this repo's code, going to close as completed on our end.

cc: @admah
