### ISSUE TITLE
Broken link on Cloudflare Pages docs home

### ISSUE THREAD

**Issue by ChandlerSwift** [cloudflare/cloudflare-docs#1242]
### Expected Behavior
https://developers.cloudflare.com/pages/ "Your Cloudflare Pages dashboard" button should go to my cloudflare pages dashboard (https://dash.cloudflare.com/[something that may be a userid]/pages)

Seems like the offending line is https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/index.md#L15

### Actual Behavior
The link goes to https://pages.dev, which redirects https://pages.cloudflare.com/. (I can, from there, click the sign in button (this occurs whether or not I'm signed in) and get to my dashboard, but it seems odd that clicking a "take me to the dashboard" link wouldn't just...take me to the dashboard!)

**Comment by KimJ15** [comment]
Thanks for the feedback @ChandlerSwift. We are looking at making significant changes to the this experience in the near future and your comment is noted. Closing this ticket given the work is not being done in Github at this time.
