### ISSUE TITLE
Error code 521

### ISSUE THREAD

**Issue by Texarkan** [cloudflare/cloudflare-docs#12422]
### Example URL(s)

www.behindthevoiceactors.com

### Actual Behavior

Earlier this morning; the problem started when the connection suddenly timed out with an Error Code 522, which is what it looked like, at first. But then, it only got worse with an Error Code 521, which meant that the web server was down.

### Expected Behavior

I can only fathom that it's going to continue with the different webpages of the whole "behind-the-voice-actors" website; that's as far as I'M concerned. 'Course, you'll never when it might start up again, with either fanfiction.net or 9anime.

### Additional information

Just so you know, any further details might be sketchy; it's just that I really, really hate it when something like this happens. Of course, I'm pretty sure that ANYBODY would wind up getting so irritated and frustrated whenever this occurs. However, I would just like to enjoy every aspect of 9anime, fanfiction.net, AND behindthevoiceactors.com every single day, without having any particular problems.

**Comment by kodster28** [comment]
Howdy @Texarkan, understand the frustration on your end.... but there's nothing we (as Cloudflare) and then our team (specifically a docs team) can do for this request.

Your best response is to contact the owner of the site (as mentioned in the `What can I do to resolve this` section of that error page) and provide them with the ray ID listed on the page. Then, they'd need to follow the process described in [this guide](https://developers.cloudflare.com/waf/managed-rules/handle-false-positives/).
