### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by kotori2** [cloudflare/cloudflare-docs#12425]
### Example URL(s)

https://developers.cloudflare.com/workers/examples/signing-requests/

### Actual Behavior

the "enable the nodejs_compat compatibility flag" hyperlink pointed to `http://localhost:5173/`
![image](https://github.com/cloudflare/cloudflare-docs/assets/17663689/c0ff8a8a-94fd-4244-92b1-b96ceb788afb)

### Expected Behavior

it should be pointed to developers.cloudflare.com

**Comment by pedrosousa** [comment]
There's another occurrence of `http://localhost:5173/` in https://developers.cloudflare.com/workers/examples/basic-auth/ ([source](https://github.com/cloudflare/cloudflare-docs/blob/a2ba41649127304ffd0decd9fb2c1c7f51fd161d/content/workers/examples/basic-auth.md?plain=1#L17)).

**Comment by aiednt** [comment]
October
