### ISSUE TITLE
Document Wrangler's bundling behaviour, dynamic imports, sourcemaps

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#12435]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

Bundling, how to use dynamic imports, how to use sourcemaps, undocumented configuration like find_additional_modules

### Content Location

- https://developers.cloudflare.com/workers/wrangler/bundling/

### Additional information

- How Wrangler bundles files (or a separate page for frameworks targeting Pages support so they know how to line up with Wrangler, like marking `cloudflare:` modules as external)
- What files does Wrangler upload separately, i.e WASM (and why it is uploaded separately (as a Module), as the error that tells users they can't instantiate from a buffer isn't useful for most people).
- How and when to use minification (pros, cons, ties into sourcemaps)
- How to generate and use sourcemaps
- How `--no-bundle` works (still talks about the D1 shim despite that being removed a long time ago)
- How `find_additional_modules` works (undocumented Wrangler flag, required for `[[rules]]` to do anything)

**Comment by kodster28** [comment]
Question @KianNH, is this addressed fully / partially / not at all by #12980?

**Comment by KianNH** [comment]
It looks like it covers the last two bullet points, and partially the second one.

Externals, specifically calling out that WASM cannot be inlined, minification and sourcemaps are still areas where it isn't really documented anywhere.

Minifying and sourcemaps are technically very briefly mentioned in the Wrangler commands page.

I guess there could be arguments against documenting how to be close to Wrangler's esbuild setup, like targeting esnext and the cloudflare: externals, but I think that's helpful information for framework authors.

**Comment by KimJ15** [comment]
This issue is pretty stale. Closing as won't do for now.

**Comment by mb21** [comment]
Came here googling "cloudflare pages why bundle", and after reading the whole docs page, I still don't know why it's recommended. (Bundling adds a lot of complexity but I don't know enough about workers performance characteristics to see why bundling should be beneficial. Is it just about the bundle size limit, or..? On a node.js server it doesn't seem beneficial at all?) So this point definitely resonates with me:

> How and when to use minification (pros, cons, ties into sourcemaps)
