### ISSUE TITLE
Other security products cannot be used to skip Bot Fight Mode. Learn more

### ISSUE THREAD

**Issue by JC5** [cloudflare/cloudflare-docs#12449]
### Which Cloudflare product does this pertain to?

Bots

### Existing documentation URL(s)

- https://developers.cloudflare.com/bots/troubleshooting/#5KX8t3C6SObnoWs5F6YOlU

### What changes are you suggesting?

In my dashboard, under Security > Bots, I can enable some kind of bot fighting mode:

> Bot Fight Mode

> Challenge requests that match patterns of known bots, before they access your site. This feature includes [JavaScript Detections](https://developers.cloudflare.com/bots/reference/javascript-detections).

> Note: Other security products cannot be used to skip Bot Fight Mode. [Learn more](https://support.cloudflare.com/hc/en-us/articles/360035387431#5KX8t3C6SObnoWs5F6YOlU)

But when you follow the link, none of the questions teach me why "other security products cannot be used to skip Bot Fight Mode.". It says "Learn more" but I'm not learning the only thing I want to learn.

**Comment by patriciasantaana** [comment]
Hi @JC5  ! Thank you for bringing this to our attention. Closing this issue now as our team is working on updating the _Learn more_ link in the dashboard. In the meantime, you can refer to our [Bots documentation](https://developers.cloudflare.com/bots/get-started/free/#limitations) or the [Bots FAQ](https://developers.cloudflare.com/bots/troubleshooting/#what-should-i-do-if-i-am-getting-false-positives-caused-by-bot-fight-mode-bfm-or-super-bot-fight-mode-sbfm) for more information about Bot Fight Mode.
