### ISSUE TITLE
DNS filtering

### ISSUE THREAD

**Issue by cmartoff** [cloudflare/cloudflare-docs#12447]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

not really a documentation request

### Content Location

It's off topic, but it would sure be nice if you offered "parental controls" filtering via DNS.  OpenDNS does this but since they require a fixed IP they are not usable on mobile networks.

Just sayin'.

Thank you.

**Comment by kodster28** [comment]
Howdy @cmartoff, you're right :), this isn't a docs request.

I'm not sure if it works for your exact situation, but Cloudflare does offer [1.1.1.1 for Families](https://developers.cloudflare.com/1.1.1.1/setup/#1111-for-families) which can automatically block malware + adult content.
