### ISSUE TITLE
Spelling bug in geolocation example

### ISSUE THREAD

**Issue by Vladi-ed** [cloudflare/cloudflare-docs#1246]
### Expected Behavior
In geolocation example the Region Code command should provide the 2-letters code.

### Actual Behavior
Provides 'undefined'

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/geolocation-hello-world.md
- String 34:
request.cf.regioncode
- Should be:
request.cf.regionCode

**Comment by KimJ15** [comment]
Duplicates the #1247. Closing this issue and will work from the PR.
