### ISSUE TITLE
Enable DNSSEC

### ISSUE THREAD

**Issue by isihussain** [cloudflare/cloudflare-docs#12472]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/dns/dnssec/#enable-dnssec

### What changes are you suggesting?

Need Tutorial how add or Enable DNSSEC on Hostinger (hosting company)

**Comment by kodster28** [comment]
Howdy @isihussain, looks like you can find that info at https://support.hostinger.com/articles/3667267-how-to-use-dnssec-records-at-hostinger (adding in the attached PR).

**Comment by isihussain** [comment]
Thank you for showing the help link, but it didn't help me that much, what interests me is that it is on Cloudflare's website, to see how this issue can be solved from their perspective.
