### ISSUE TITLE
[D1] SvelteKit update

### ISSUE THREAD

**Issue by ruckc** [cloudflare/cloudflare-docs#12508]
### Which Cloudflare product does this pertain to?

D1

### Existing documentation URL(s)

https://developers.cloudflare.com/d1/examples/d1-and-sveltekit/

### What changes are you suggesting?

The `platform` request parameter doesn't contain an `env` value.  It should use `$env` to access environment variables... but that export string values, so 'prepare' doesn't exist on type 'string'.

**Comment by kodster28** [comment]
Howdy @ruckc, tested this in development mode and not seeing the issues you're mentioning. 

Any other background you have on when / where you encountered this issue?

**Comment by ruckc** [comment]
@kodster28 - at this point... 5 months later, I don't recall what/who/anything I was doing.

**Comment by kodster28** [comment]
Gotcha gotcha. Apologies it took us so long to get to this feedback, @ruckc.

Going to close this out as there's not much we can do to action at this point... but realize that's entirely b/c of the delay in getting to this.
