### ISSUE TITLE
Domain registrar

### ISSUE THREAD

**Issue by Gerrime** [cloudflare/cloudflare-docs#12511]
### Which Cloudflare product(s) does this pertain to?

Email Routing

### Subject Matter

Type MX Host @ Value mx02.mail.icloud.com. Priority 10 TXT: Type TXT Host @ Value apple-domain=FtKxyymI4MF4E5DG SPF: Type TXT Host @ Value "v=spf1 include:icloud.com ~all" DKIM: Type CNAME Host sig1._domainkey Value sig1.dkim.xxxg00.com.at.icloudmailadmin.com.

### Content Location

New documents 
![IMG_0086](https://github.com/cloudflare/cloudflare-docs/assets/99726752/3c6d65ad-5aa3-4420-945c-75a04d3e1f9e)

### Additional information

Type
MX
Host
@
Value
mx02.mail.icloud.com.
Priority
10
TXT:
Type
TXT
Host
@
Value
apple-domain=FtKxyymI4MF4E5DG
SPF:
Type
TXT
Host
@
Value
"v=spf1 include:icloud.com ~all"
DKIM:
Type
CNAME
Host
sig1._domainkey
Value
sig1.dkim.xxxg00.com.at.icloudmailadmin.com.
![IMG_0085](https://github.com/cloudflare/cloudflare-docs/assets/99726752/f31aaa60-a68c-4ea6-8be3-ed9c1546d5ce)
Domain registrar

**Comment by kodster28** [comment]
Howdy @Gerrime, it's unclear what changes you want in our documentation based on your issue.

As best I can guess, you might want to check out [iCloud custom email domains](https://developers.cloudflare.com/registrar/account-options/icloud-domains/).

If you're still experiencing issues, I'd encourage you to post in the [Cloudflare community](https://community.cloudflare.com) or open an issue with [Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
