### ISSUE TITLE
Cloudflare Pages "Forum" Link to private page

### ISSUE THREAD

**Issue by zwezheng** [cloudflare/cloudflare-docs#1253]
### Expected Behavior
The Pages community should exist.

### Actual Behavior
Click "Forum" link at the bottom of https://pages.cloudflare.com/  links to https://community.cloudflare.com/c/developers/pages
which doesn't exist

### Additional information
Hi guys, I started using Cloudflare Page last night, my site loaded but all pngs gave 500 error.
https://a0fff39e.77566302-dist.pages.dev/

I was trying to visit the community page for some help but got community doesn't exist error.

![Cloudflare_Pages](https://user-images.githubusercontent.com/1361054/116635421-4fda7100-a991-11eb-906c-046ca4514ee0.jpg)
![Cloudflare_Community](https://user-images.githubusercontent.com/1361054/116635432-5537bb80-a991-11eb-9a8b-3bdf8c94b503.jpg)

**Comment by KimJ15** [comment]
Thanks for letting us know about the broken link @zwezheng.
@rita3ko @signalnerve - this broken link is for pages.cloudflare.com, not the docs repo. Closing given we can't fix it, but wanted you to know.
