### ISSUE TITLE
Warp macOS download points to Microsoft store

### ISSUE THREAD

**Issue by 32mbbm23** [cloudflare/cloudflare-docs#12586]
### Example URL(s)

https://developers.cloudflare.com/warp-client/get-started/macos/

### Actual Behavior

it's the wrong URL

### Expected Behavior

Apple Store URL

**Comment by haleycode** [comment]
Hi @32mbbm23, the link mentioned in the documentation does direct users to download the correct .pkg file, so I am closing this request for now. Thanks!
