### ISSUE TITLE
`ct` url parameter ignored

### ISSUE THREAD

**Issue by Quezler** [cloudflare/cloudflare-docs#12600]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/#valid-mime-types

https://github.com/cloudflare/cloudflare-docs/blob/production/content/1.1.1.1/encryption/dns-over-https/make-api-requests/_index.md

### What changes are you suggesting?

Either fixing the documentation stating `ct` in the url is no longer supported for simple (uri-only, no headers) GET requests, or fixing the bug that broke it.

### Additional information

Previously `https://1.1.1.1/dns-query?name=google.nl&ct=application/dns-json` used to work, but at some time in the past (easily months+) the `ct` part in the url seems to no longer work, requiring the `Accept` header thus preventing simple requests.

The documentation page doesn't seem to have posted a changelog and reading over the text still hints as to this should work.

**Comment by RebeccaTamachiro** [comment]
Hi @Quezler  👋 Thanks for raising this. 
That parameter has indeed been deprecated. I've updated the documentation.

**Comment by Quezler** [comment]
Thanks for confirming @RebeccaTamachiro, a little unfortunate that it broke some software on my end, but i appreciate the documentation being updated to reflect how it currently works 👍
