### ISSUE TITLE
How to open Graphiql

### ISSUE THREAD

**Issue by srivraj** [cloudflare/cloudflare-docs#12616]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/analytics/graphql-api/getting-started/authentication/graphql-client-headers/

### What changes are you suggesting?

All your documentation related to Graphiql send it to an external link where it is not clear how to run the graphiql client. It's very frustrating. I have spent days  but could not figure it out.

**Comment by jimhawkridge** [comment]
If you're having trouble with Graphiql you could try a different client. We suggest a couple of other ones at the bottom of this page: https://developers.cloudflare.com/analytics/graphql-api/
Personally I use [Altair](https://altairgraphql.dev/) and it works well with Cloudflare GraphQL API.
