### ISSUE TITLE
1.1.1.1 For Families is not blocking a porn site

### ISSUE THREAD

**Issue by Ahmad091K** [cloudflare/cloudflare-docs#12624]

**Comment by haleycode** [comment]
Hi @Ahmad091K, the following docs may be helpful to make sure you've set up 1.1.1.1 for Families correctly. It also links out to a form where you can report a miscategorized domain, which may be what is happening here: https://developers.cloudflare.com/1.1.1.1/setup/#1111-for-families

I am going to close this ticket for the time being. Please feel free to open a new ticket if you have specific updates you'd like to proposed to the developer documentation. Thanks!
