### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by sebatrino** [cloudflare/cloudflare-docs#12634]
### Example URL(s)

https://1337x.to/cat/Apps/1/

https://1337x.to/

### Actual Behavior

https://1337x.to/cat/Apps/1/

'Icon for 1337x.to1337x.to
1337x.to needs to review the security of your connection before proceeding.
Your browser is out of date!
Update your browser to view this website correctly. More Information.'

This appeared a couple of days back with no way to bypass it.
We use brave 64, its autoupdated and we have no problems accesing any other websites, also we dont use any vpn.

We can acess any of the mirror links of this website which use different types of cloudfare protection, but mnot this one and brave has no issues with them.
The thing is that these mirror websites for some reason dont have all the files which this one has.

Whats the reason for this type of cloudfare blocking this website - or our browser if there are no issues with our browser?

### Expected Behavior

The website should load as does any other website we visit.

**Comment by kodster28** [comment]
Howdy @sebatrino, understand the frustration on your end.... but there's nothing our team (as a docs team) can do for this request.

Your best first bet would be to check out the details we provide on [browser support](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#browser-support).

If that doesn't help, you might want to reach out in the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

**Comment by lukaspavelka** [comment]
issue here as well

**Comment by LazerDickMcCheese** [comment]
Same issue here. Would love someone to advise on how to fix this.
