### ISSUE TITLE
No "network" element in dashboard

### ISSUE THREAD

**Issue by bfab** [cloudflare/cloudflare-docs#12640]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/network/websockets/

### What changes are you suggesting?

The documentation should be updated so that any dashboard user would be able to find how to enable WebSockets; current instructions direct to a "network" section which is missing (at least in my case).

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/4320199/d802d656-63f3-4006-8609-1abeb0038428)
![image](https://github.com/cloudflare/cloudflare-docs/assets/4320199/ebb18d5a-0351-478d-96d3-760bf5e5dc44)

**Comment by kodster28** [comment]
Howdy @bfab, as stated in the docs, you need to select a `specific domain` (one of your zones/websites) after selecting your account.

Once within a zone, you will see the `Network` navigation and Websockets.
