### ISSUE TITLE
broken link to dnssec blog post

### ISSUE THREAD

**Issue by yekta-flink** [cloudflare/cloudflare-docs#12653]
### Example URL(s)

https://developers.cloudflare.com/dns/dnssec/dnssec-states/

### Actual Behavior

The sentence ``Refer to How DNSSEC works to learn more about the authentication process and records involved.` has a link to https://www.cloudflare.com/dns/dnssec/how-dnssec-works/ . This link is broken and currently leads to a 404 page.

### Expected Behavior

The link in `Refer to How DNSSEC works to learn more about the authentication process and records involved.` actually points to a document.

**Comment by kherrera-cf** [comment]
Hello,
This is Kevin Herrera from mrkeng. We fixed the 404 page. It is now live https://www.cloudflare.com/dns/dnssec/universal-dnssec/

The url can be added back to the docs. Apologies for creating a 404 for yall.
