### ISSUE TITLE
Wrong password for no reason.

### ISSUE THREAD

**Issue by liyuchuan518** [cloudflare/cloudflare-docs#12669]
### Which Cloudflare product(s) does this pertain to?

Registrar

### Subject Matter

Wrong password for no reason.

### Content Location

Wrong password for no reason.

### Additional information

Wrong password for no reason.

**Comment by kodster28** [comment]
Howdy @liyuchuan518, if you're experiencing password issues, I'd encourage you to check out [Login and account issues](https://developers.cloudflare.com/fundamentals/account-and-billing/account-security/login-and-account-issues/).

If that doesn't help, you might want to reach out in the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
