### ISSUE TITLE
workers-kv-from-rust tutorial obsolete

### ISSUE THREAD

**Issue by i-infra** [cloudflare/cloudflare-docs#12668]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/tutorials/workers-kv-from-rust/

### What changes are you suggesting?

A callout indicating this strategy is no longer used / the tutorial is obsoleted by the publication of [worker-rs](https://github.com/cloudflare/workers-rs) and [worker-kv](https://docs.rs/worker-kv/latest/worker_kv/). 

### Additional information

This diff shows the changes needed

essentially, this tutorial / dev project are entirely obsolete. 

https://github.com/fkettelhoit/workers-kv-from-rust/compare/main...i-infra:workers-kv-from-rust:main#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759

The latest version could look something like: https://github.com/i-infra/workers-kv-from-rust

**Comment by kodster28** [comment]
Additional comment (likely addressed by previous).

```
https://developers.cloudflare.com/workers/tutorials/workers-kv-from-rust/: points to updated https://github.com/cloudflare/rustwasm-worker-template/ template using `workers-rs`, but contains references to `type="rust"` `worker/worker.js` file in tutorial
```
