### ISSUE TITLE
Missing JSON Example

### ISSUE THREAD

**Issue by ChrisLopezTide** [cloudflare/cloudflare-docs#12674]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/third-party-software/others/configuring-an-amazon-web-services-static-site-to-use-cloudflare/#configure-bucket-policies-to-allow-cloudflare-ip-addresses

### What changes are you suggesting?

The JSON example seems to be missing from the docs. Instead there is a curl command.

**Comment by kodster28** [comment]
Thanks for raising, @ChrisLopezTide.

Should be addressed once the latest build goes live (which is usually ~5 minutes).
