### ISSUE TITLE
Please provide a list of countries which are in the WAF Continent rules

### ISSUE THREAD

**Issue by jhford** [cloudflare/cloudflare-docs#12689]
### Which Cloudflare product(s) does this pertain to?

WAF

### Subject Matter

List of countries included in continents is not clear

### Content Location

https://developers.cloudflare.com/waf/tools/ip-access-rules/#ip-access-rules

I would expect this information to be included directly or linked.  Even an explanation of an IANA or similar body's categorization would be great.

For example, Is Turkey in Asia, Europe or Both?  What about Russia?  What about parts of countries which are primarily in Europe but have portions elsewhere.  For example, Wikipedia shows Hawaii as being included in Oceania but it's part of a country that's primarily in North America.  What about parts of France which are in the Caribbean?

My specific question is whether Turkey, Georgia, Armenia and Azerbaijan are considered to be in Europe or Asia.

I know this is a difficult question, but since your tooling must be categorizing the countries to be able to evaluate the WAF rule, it needs to be done somewhere in the codebase.

**Comment by pedrosousa** [comment]
Hi @jhford 
Cloudflare currently uses third-party geolocation data from [MaxMind](https://www.maxmind.com), so they are the actual source of truth for this kind of information. 

You can register on their website and download their free [GeoLite2 database](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data), which includes country and continent information.

Answering your query, here's the data (as of 2023-12-01) for those specific countries:

Country | Continent
---|---
Turkey | Asia
Georgia | Asia
Armenia | Asia
Azerbaijan | Asia

This information may change in the future. All updates are managed by MaxMind.

**Comment by jhford-scout24** [comment]
@pedrosousa thats really good info. How about adding a link in the docs and an explanation that about maxmind being the source?

**Comment by pedrosousa** [comment]
Currently we mention it only for the `ip.src.is_in_european_union` field, but I'll add a reference to the other geolocation fields.
