### ISSUE TITLE
Improve documentation as to how to deploy to preview without production from GitHub Actions

### ISSUE THREAD

**Issue by simonheimlicher** [cloudflare/cloudflare-docs#12680]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Explain how to deploy to preview without production

### Content Location

On this page https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/ it appears that it would explain, how I can use GitHub Actions to control deployment to CF Pages.

While the explanation is sufficient to do a direct deployment to production, I cannot figure out how to indicate in my GitHub workflow, how to deploy only to the preview host but not production.

### Additional information

Here is the workflow I built, which works great aside from its insistence on always deploying directly to production:

https://github.com/simonheimlicher/claris-gh-actions/blob/main/.github/workflows/deploy-cloudflare-pages.yml

**Comment by kodster28** [comment]
Howdy @simonheimlicher, updating the docs in the tagged PR to explicitly call out that the action happens w/in the context of the current git branch.

So, you'd get preview deployments for free, so long as the action is triggered by a branch (and not production).

Also... apologies this sat for quite a while w/o a response!
