### ISSUE TITLE
Turnstile Analytics page Help very confusing.

### ISSUE THREAD

**Issue by GlennPresentsofMind** [cloudflare/cloudflare-docs#12690]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

https://developers.cloudflare.com/turnstile/reference/turnstile-analytics/#turnstile-analytics

### What changes are you suggesting?

The terminology/wording you are using is confusing.  When I am looking at the Turnstile Analytics page I want to know the number of events that Turnstile was active for e.g., 35 checkouts.  Then for this number how many challenges were issued and how many were solves with API or user or failed.  The number of events (35 checkouts) is either not shown or not described adequately

### Additional information

no

**Comment by patriciasantaana** [comment]
Hi @GlennPresentsofMind ! Thank you for bringing this to our attention. Closing this out as this not something that documentation can address since we are not in charge of the Cloudflare dashboard. I’ve passed your issue along internally and the team is working on improving Turnstile Analytics.
