### ISSUE TITLE
Missing clarity around Permissions to API endpoints

### ISSUE THREAD

**Issue by jasonwbarnett** [cloudflare/cloudflare-docs#12705]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/fundamentals/api/reference/permissions/

### What changes are you suggesting?

The current document has mostly Product/Feature Titles that don't directly map to API endpoints which makes it very difficult to understand which permission is required to gain access to a particular API endpoint. In my case I'm trying to use the `POST /client/v4/accounts/{account_id}/devices/policy` ([cloudflare_device_settings_policy Terraform Resource][1]) API endpoint and I've spent over an hour trying to determine which Permission is required without success. The most obvious one to me would be `Zero Trust:Edit` but it did not work as I would expect.

[1]: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/device_settings_policy

**Comment by kodster28** [comment]
Howdy @jasonwbarnett, definitely hear the frustration here and -- unfortunately -- don't have a super satisfying answer here. It's is a known limitation in our Terraform resources, API docs, and product docs.

At the moment, your best bet for getting an answer would be to reach out in the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

**Comment by jasonwbarnett** [comment]
In case anyone stumbles upon this thread. I started searching API endpoints in https://github.com/cloudflare/cloudflare-go and then once I found the function that I would expect to be called in the Terraform provider I then search that in https://github.com/cloudflare/terraform-provider-cloudflare

For example, 

1. I first visit the page in Cloudflare's portal, i.e. https://one.dash.cloudflare.com/{account_id}/settings/devices/profile-settings/{profile_id}/edit/fallback-domains

2. While the chrome developer tools are opened I refresh the page while holding shift.
3. I identify the API endpoint (using intuition and filtering on `/api/`), i.e. https://dash.cloudflare.com/api/v4/accounts/{account_id}/devices/policy/{policy_id}/fallback_domains
4. Next, I search for `/fallback_domains` in https://github.com/cloudflare/cloudflare-go
5. I look for the create or update functions, i.e. `UpdateFallbackDomainDeviceSettingsPolicy`
6. Then I search for `UpdateFallbackDomainDeviceSettingsPolicy` in https://github.com/cloudflare/terraform-provider-cloudflare

This has given me a fool proof way of identifying what Terraform resource should be used to configure Cloudflare.
