### ISSUE TITLE
Add documentation for Java

### ISSUE THREAD

**Issue by dcpilham** [cloudflare/cloudflare-docs#12716]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Upload Object using AWS S3 Java SDK

### Content Location

https://developers.cloudflare.com/r2/examples/aws/

### Additional information

Please add a documentation to upload object using Java, for example, what are the attributes that need to be set. This may give user more understanding and clarity instead of just reading other language's code

**Comment by harshil1712** [comment]
Thank you for opening the issue. A new example for Java is now available https://github.com/cloudflare/cloudflare-docs/pull/17850
