### ISSUE TITLE
Attribute name in terraform SSL example needs updating

### ISSUE THREAD

**Issue by gtebbutt** [cloudflare/cloudflare-docs#12711]
### Which Cloudflare product does this pertain to?

Terraform

### Existing documentation URL(s)

https://developers.cloudflare.com/terraform/tutorial/configure-https-settings/

### What changes are you suggesting?

The current docs say that the sample script will enable "Always use HTTPS", but it actually enables `automatic_https_rewrites` (which I believe rewrites the scheme in the cached HTML pages, not the incoming requests) - there's a separate setting on the same resource named `always_use_https`, but the two names are similar enough that it's very easy to miss, especially as terraform resource names don't always precisely match the user-facing product name anyway.

**Comment by kodster28** [comment]
Howdy @gtebbutt, thanks for raising!

Updated to point to the correct SSL setting (and related docs).
