### ISSUE TITLE
Enable flexible variants missing exampels of what query params we can actually use

### ISSUE THREAD

**Issue by 1mike12** [cloudflare/cloudflare-docs#12734]
### Which Cloudflare product(s) does this pertain to?

Images

### Subject Matter

there's one example of the type of urls we can construct but no list or pointer to what the available query params are

### Content Location

https://developers.cloudflare.com/images/manage-images/enable-flexible-variants/

### Additional information

80% of the docs are reserved for explaining how to enable the variants, but there is literally one line showing one limited example of how it's used

What else other than 
`https://imagedelivery.net/<ACCOUNT_HASH>/<IMAGE_ID>/w=400,sharpen=3`

is possible?

**Comment by 1mike12** [comment]
I think I found where these are listed out

https://developers.cloudflare.com/images/transform-images/transform-via-url/

**Comment by kodster28** [comment]
Howdy @1mike12, sounds like you answered your own issue here.

Closing this out!
