### ISSUE TITLE
"LogPush Jobs to Splunk" document does not provide how to configure without a Channel GUID.

### ISSUE THREAD

**Issue by arnav-bnrj** [cloudflare/cloudflare-docs#12757]
### Which Cloudflare product does this pertain to?

Logs

### Existing documentation URL(s)

https://developers.cloudflare.com/logs/get-started/enable-destinations/splunk/

### What changes are you suggesting?

Disable HEC Acknowledgement Channel requirement when configuring LogPush jobs for Splunk Indexing.

### Additional information

We recently reached out to Splunk Support for all our HEC Acknowledgement Indexer connections failing. We were informed that HEC configurations with the acknowledgement channel require the senders to confirm acknowledgement of Indexing. If this does not happen the connection stops working and related indices are disabled from Splunk. CF LogPush configuration requires Channel GUID to be set to confirm the settings. There's no information in the documentation as to how to configure LogPush without Channel GUID.

**Comment by angelampcosta** [comment]
Hi @arnav-bnrj Thank your for opening this issue. We are following up on this with an internal ticket.
