### ISSUE TITLE
Update Page to Include payment restriction information 

### ISSUE THREAD

**Issue by matt3948** [cloudflare/cloudflare-docs#12769]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/registrar/get-started/transfer-domain-to-cloudflare

### What changes are you suggesting?

Add the following: _"Currently, we only support Credit Card payments for Registrar purchases."_ or similar to the page so that when users are troubleshooting the error:

` _"<domain name> An internal system error has occurred while trying to process the transaction. Please wait a few minutes and try again. If the issue persists please contact support for assistance."_ `

they can self solve the issue rather than contacting support.

### Additional information

This was an error I ran into that I could have solved on my own had the documentation mentioned that Paypal was not an acceptable payment method for Registrar purchases.

My ticket: 
    #3124520

**Comment by kodster28** [comment]
Howdy @matt3948, I've filed an internal ticket to have the ENG team update this error message directly in the dashboard.

Closing this issue out as that the scope of work has moved beyond our docs.
