### ISSUE TITLE
Missing "API Tokens" in User Permissions

### ISSUE THREAD

**Issue by gar1t** [cloudflare/cloudflare-docs#12777]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/api/reference/permissions/

### What changes are you suggesting?

Per the docs, I would expect to see an "API Tokens" in the second dropdown list when I select User when adding a permission for a token. I only see Memberships and User Details.

**Comment by patriciasantaana** [comment]
Hi @gar1t ! Thank you for bringing this to our attention. You can create a token with the User-level API Tokens permission using the **Create Additional Token** template on the [Cloudflare dashboard](https://dash.cloudflare.com/). Please feel free to ask any questions or open another issue.

**Comment by gar1t** [comment]
Thank you - I was indeed able to do this. Nonetheless, the manual interface is *missing the API Tokens option*. This I believe is a bug. That a non-obvious workaround exists is does not ultimately address this issue.

**Comment by gar1t** [comment]
This should not be closed as the issue was not addressed, unless you're making the case that this option should be omitted from the manual interface. Of course it should be included - this is an obvious bug.

**Comment by fermentfan** [comment]
Guys this is extremely confusing. I can only agree to @gar1t that this is missing from the manual token creation input drop downs. There is no way to create such a token in the UI when not using exactly that template.

**Comment by fermentfan** [comment]
@patriciasantaana You have completely ignored the point of OP here.

**Comment by kodster28** [comment]
Howdy @gar1t / @fermentfan, we can pass along this feedback to the dashboard UI team... but -- as a docs team -- we're limited in the scope of what we can address here.
