### ISSUE TITLE
Update docs for getBindingsProxy() 

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#12783]
> Does `getBindingsProxy()` have docs that will need updating too?

Yes (and thanks for reminding me! ❤️): https://developers.cloudflare.com/workers/wrangler/api/#getbindingsproxy

I will update them later if that's ok by you 🙏

_Originally posted by @dario-piotrowicz in https://github.com/cloudflare/workers-sdk/issues/4847#issuecomment-1916712554_

**Comment by dario-piotrowicz** [comment]
Also to do:
 - [x] add docs for the input options
 - [x] mention the `dispose` function that is returned and its usage
 - [x] mention how to use the AI bindings (via env variables)
