### ISSUE TITLE
Workers Protocols page outdated regarding inbound TCP connections?

### ISSUE THREAD

**Issue by mwisnicki** [cloudflare/cloudflare-docs#12807]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/reference/protocols/

### What changes are you suggesting?

Above page says that "Support for handling inbound TCP connections is coming soon" and points to blog article from 2021 with no updates.

If this is no longer being worked on then the page should be updated.

**Comment by arunesh90** [comment]
> If this is no longer being worked on then the page should be updated.

This blog post from 2023, in which outbound TCP support got announced, mentions that support for inbound is still being worked on.

https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/

> Supporting outbound TCP connections is only one half of the story — we plan to support **_inbound_** TCP and UDP connections, as well as new emerging application protocols based on QUIC, so that you can build applications beyond HTTP with [Socket Workers](http://blog.cloudflare.com/introducing-socket-workers/).

**Comment by mwisnicki** [comment]
Good to know it wasn't dropped!
The page might use an update to link to latest blog post.

**Comment by dticson** [comment]
It's 2025 now. Seems like inbound tcp has been dropped as a priority

**Comment by ConProgramming** [comment]
Bumping this again. Any future for inbound TCP?

**Comment by zidokobik** [comment]
beep
