### ISSUE TITLE
Hide service in task manager

### ISSUE THREAD

**Issue by zsvendo** [cloudflare/cloudflare-docs#12828]
### Which Cloudflare product(s) does this pertain to?

WARP Client, Zero Trust

### Subject Matter

Hide service in task manager

### Content Location

I installed Warp to manage some computers from malicious access, but there is a problem where the user can go to the task manager and close the warp so he can browse smoothly or even go to the Windows control panel and remove the warp.
Is there any way to hide the service or hide it?
![preent](https://github.com/cloudflare/cloudflare-docs/assets/28624361/fd9aec83-5915-4b1d-80c7-f3a8f67eaec7)

**Comment by ranbel** [comment]
Hi @zsvendo, I'm sorry but this issue is not specific to WARP and beyond the scope of developers.cloudflare.com. You may want to look into Windows endpoint management solutions to ensure that users have the required software installed on their device.

**Comment by ranbel** [comment]
As a note, closing the task manager process only closes the GUI application. The WARP daemon service should still be running, which you can check by typing `warp-cli status` in the terminal.
