### ISSUE TITLE
Need add mantic support.

### ISSUE THREAD

**Issue by makhnanov** [cloudflare/cloudflare-docs#12830]
### Which Cloudflare product(s) does this pertain to?

WARP Client

### Subject Matter

Installation documentation.

### Content Location

https://pkg.cloudflareclient.com/

### Additional information

lsb_release -cs === mantic unsupport.

**Comment by ranbel** [comment]
Hi @makhnanov, we are planning to add Mantic support sometime this year and will update https://pkg.cloudflareclient.com/ once it's ready.

**Comment by ranbel** [comment]
This feature request is being tracked internally.
