### ISSUE TITLE
Windows11家庭中文版安装时出现错误

### ISSUE THREAD

**Issue by imrockbiao** [cloudflare/cloudflare-docs#12835]
### Which Cloudflare product(s) does this pertain to?

WARP Client

### Subject Matter

出现了暗转win32程序出错，导致应用程序安装不成功

### Content Location

出现了暗转win32程序出错，导致应用程序安装不成功

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/65006728/b66f7574-305e-4bdc-a183-c0f1a63a8a6d)

**Comment by kodster28** [comment]
Howdy @imrockbiao, from this issue it sounds like you're looking for help with a setup error, which is a bit outside the scope of issues in this repo.

I'd encourage you to check out the [FAQ](https://developers.cloudflare.com/warp-client/known-issues-and-faq/) to see if it helps address your issue and -- if not -- look for help in the [Cloudflare Community](https://community.cloudflare.com/).
