### ISSUE TITLE
How can I share my AI Gateway with my team?

### ISSUE THREAD

**Issue by MathiasGilson** [cloudflare/cloudflare-docs#12879]
### Which Cloudflare product(s) does this pertain to?

Workers AI

### Subject Matter

it makes sense to be able to share a gateway with multiple users, especially the dashboard

### Content Location

This should be a new section in the current ai gateway config page https://developers.cloudflare.com/ai-gateway/configuration/

**Comment by kodster28** [comment]
Howdy @MathiasGilson, that's not currently functionality, but I believe something the team is working on.

Pay attention to the [product changelog](https://developers.cloudflare.com/ai-gateway/changelog/) for any future product announcements.
