### ISSUE TITLE
Enable Warp-to-Warp

### ISSUE THREAD

**Issue by rch** [cloudflare/cloudflare-docs#12891]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/#3-enable-cgnat-routing

### What changes are you suggesting?

The following steps are not correct:
1. In Zero Trust, go to Settings > Network.
2. Enable Warp-to-Warp. This allows Cloudflare to route traffic to the CGNAT IP space.

It is not clear how to enable "Warp-to-Warp" connectivity. The next two steps to enable override local interface IP appear to be correct.

**Comment by rch** [comment]
I continued the process and found this in WARP connector prerequisites:

3. Turn on WARP to WARP
Navigate to Settings > Network > Firewall and toggle on WARP to WARP. This will allow the WARP connector to off-ramp traffic to WARP devices.

**Comment by ranbel** [comment]
<img width="1059" alt="Screenshot 2024-02-07 at 4 25 56 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/101146722/8b8f8b9c-7f57-499a-8b18-e52b8582c2b3">
Hi @rch, you should be able to find the **WARP to WARP** setting below *Proxy**.

**Comment by rch** [comment]
It doesn't look like that option is available for me.

<img width="1083" alt="Screenshot 2024-02-07 at 14 42 51" src="https://github.com/cloudflare/cloudflare-docs/assets/80840/8091d78c-6fac-4b18-823c-b52db59941cb">

**Comment by ranbel** [comment]
Apparently you need to enable **Proxy** first before the WARP-to-WARP setting will show up. 

We will add this step to the docs. Thanks for flagging the issue!

**Comment by rch** [comment]
That works! Thanks for your help :)
