### ISSUE TITLE
[Pages] Document how to integrate existing SvelteKit app with Cloudflare Pages

### ISSUE THREAD

**Issue by Jaakkonen** [cloudflare/cloudflare-docs#12897]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/

### What changes are you suggesting?

Currently the documentation only covers creating new app with `create-cloudflare` tool but it doesn't give any guidance on how to deploy existing SvelteKit app to Cloudflare

**Comment by deadlypants1973** [comment]
Hi @Jaakkonen :) We are reviewing all the framework guides now and this update will be up soon.

**Comment by craigsdennis** [comment]
Came across this yesterday if it helps: https://kit.svelte.dev/docs/adapter-cloudflare

**Comment by KimJ15** [comment]
Closed by https://github.com/cloudflare/cloudflare-docs/issues/13539 and https://github.com/cloudflare/workers-sdk/pull/5027
