### ISSUE TITLE
Human verification

### ISSUE THREAD

**Issue by TaylormadeStudios** [cloudflare/cloudflare-docs#12904]
### Example URL(s)

https://nijijourney.com/en/account/  or anywhere where Cloudflare asks for verification

### Actual Behavior

"please verify you are human"

### Expected Behavior

"We are fighting spambots - please help us by clicking here"

### Additional information

think of the USER EXPERIENCE - it is offensive for an algorithm to ascertain humanity. It's a bit like a woman verifying if you're "man enough" or a man verifying if you are "woman enough".  enough is enough.  Ask the end user to help YOU in the fight against spambots and fake profiles, and see the difference

**Comment by kodster28** [comment]
Howdy @TaylormadeStudios, thanks for the feedback + I'll pass along it along internally... but there's nothing our team can do about the text on those challenge pages directly.
