### ISSUE TITLE
Manage Domains -> select a domain -> click manage , 404 page shows up.

### ISSUE THREAD

**Issue by rwang220** [cloudflare/cloudflare-docs#12920]
### Example URL(s)

https://dash.cloudflare.com/1e7fc656a8e6916a111f566065865eb1/domains/lucene-solr.com
https://dash.cloudflare.com/1e7fc656a8e6916a111f566065865eb1/domains/lucene-solr.org
https://dash.cloudflare.com/1e7fc656a8e6916a111f566065865eb1/domains/lucene-solr.net

### Actual Behavior

Manage Domains -> select the 3 domains -> click "manage"
![截屏2024-02-09 22 02 11](https://github.com/cloudflare/cloudflare-docs/assets/934404/6f552ac3-b1ff-440e-adeb-2f46cda85c02)

### Expected Behavior

404 pages shows up
![截屏2024-02-09 22 02 11](https://github.com/cloudflare/cloudflare-docs/assets/934404/e938c748-8205-43c4-9b11-d47791910fbb)

**Comment by kodster28** [comment]
Howdy @wangwindows, I'll forward this along internally.... but our team can't really do much about things in the dashboard. All of the issues / PRs in this issue are for our documentation at developers.cloudflare.com, not for engineering issues associated with the CF dash.

**Comment by kodster28** [comment]
If you're still experiencing issues, you can always reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
