### ISSUE TITLE
Renewal

### ISSUE THREAD

**Issue by Sormouas** [cloudflare/cloudflare-docs#12973]
### Which Cloudflare product(s) does this pertain to?

Magic Firewall, Network Interconnect

### Subject Matter

How to renew domain name when it expires?

### Content Location

How to renew domain name when it expires?

### Additional information

How to renew domain name when it expires?

**Comment by kodster28** [comment]
Howdy @Sormouas, from your issue description, it sounds like you're looking for [Renew domains](https://developers.cloudflare.com/registrar/account-options/renew-domains/).

If that doesn't help, I'd suggest you reach out to the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
