### ISSUE TITLE
[Hyperdrive] Typo in Hyperdrive docs

### ISSUE THREAD

**Issue by kunalmodi** [cloudflare/cloudflare-docs#12994]
### Which Cloudflare product does this pertain to?

Hyperdrive

### Existing documentation URL(s)

https://developers.cloudflare.com/hyperdrive/configuration/query-caching/

### What changes are you suggesting?

The SQL example on this page:
```
-- Cacheable
SELECT * FROM articles
WHERE published_date = CURRENT_DATE()
ORDER BY CURRENT_DATE() DESC
LIMIT 50
```

Should order by `published_date` field instead.

Suggestion:
```
-- Cacheable
SELECT * FROM articles
WHERE published_date = CURRENT_DATE()
ORDER BY published_date DESC
LIMIT 50
```

**Comment by a-robinson** [comment]
The ORDER BY kind of doesn't make sense in either case. Given that the WHERE clause already filtered down to just the rows where `published_date` is the current date, neither option would provide any useful ordering.

I'll push up a quick fix though, thanks for pointing it out @kunalmodi

**Comment by a-robinson** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/13009
