### ISSUE TITLE
Inaccurate custom domain restrictions

### ISSUE THREAD

**Issue by LukeLambert** [cloudflare/cloudflare-docs#13046]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/buckets/public-buckets/#connect-a-bucket-to-a-custom-domain

### What changes are you suggesting?

**"Use of a domain with CNAME flattening enabled is not supported. You will need to disable CNAME flattening before enabling domain access."**
In my testing, custom domains work at the apex (example.com) and at subdomains (r2.example.com) on domains with CNAME flattening enabled.

**"Object access is only available via HTTPS; plaintxt [sic] HTTP is not supported."**
In my testing, objects are available via both HTTP and HTTPS if the account has Always Use HTTPS disabled. It even works with Encryption Mode set to Full (Strict).

**Comment by harshil1712** [comment]
Hello,

Thank you for addressing this. I have opened up a PR to fix this.

**Comment by harshil1712** [comment]
Fixed in https://github.com/cloudflare/cloudflare-docs/pull/17909
