### ISSUE TITLE
注册时因为不理解贵网站域的要求，使我无法通过贵网站浏览网页。贵网站提示我是无效的域，请给予帮助。

### ISSUE THREAD

**Issue by jianghezhong** [cloudflare/cloudflare-docs#13053]
### Which Cloudflare product(s) does this pertain to?

China Network, Network Interconnect

### Subject Matter

注册的域是无效的。

### Content Location

我注册的用户名是395434078@qq.com.在注册域时，填写的是“qq.com”.由于这个域名是无效的，我无法使用贵网站的翻墙功能。我应该如何解决这个问题

### Additional information

我注册的用户名是395434078@qq.com.在注册域时，填写的是“qq.com”.由于这个域名是无效的，我无法使用贵网站的翻墙功能。我应该如何解决这个问题

**Comment by kodster28** [comment]
Howdy @jianghezhong, this sounds more like a question for the [Cloudflare Community](https://community.cloudflare.com/) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/), as it's troubleshooting a specific issue.

That being said.... from a touch of research it sounds like that domain is [already registered](https://www.whois.com/whois/qq.com).
