### ISSUE TITLE
Connecting to Virtual Networks

### ISSUE THREAD

**Issue by boutzamat** [cloudflare/cloudflare-docs#13078]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/cloudflared/tunnel-virtual-networks/#connect-to-a-virtual-network

### What changes are you suggesting?

On this page it says: **Go to Settings > Gateway with WARP > Virtual Networks.**
There is no such option in the client App. I have attached a screenshot.
Generally, the docs are very confusing because there are no screenshots. I really wish a service as big as Cloudflare with so many features, would use screenshots to make it more easy to understand.

![image](https://github.com/cloudflare/cloudflare-docs/assets/4305046/a3d0c1dc-da10-4562-8c6d-080691edcc02)

![image](https://github.com/cloudflare/cloudflare-docs/assets/4305046/e0c31d80-568a-4ae8-9261-f9d276418dbc)

**Comment by boutzamat** [comment]
Apparently, i was running on an older version of WARP on Windows.
After updating, it worked as described. However, on mobile clients, there is no such option, even on the latest version of the app.

**Comment by ranbel** [comment]
Hi @boutzamat, sorry to hear you're having issues. Unfortunately virtual network selection is not supported on mobile clients. We'll add a note about this to the docs in #13080.

**Comment by ranbel** [comment]
Hi @boutzamat, thanks for opening this issue! We are adding the missing mobile client instructions to #13080.
