### ISSUE TITLE
none of this works. the location of home-brew on  a Mac is actually /usr/local/Cellar . I've wasted an entire day and still get no SSH just a constant UNKOWN port 65535

### ISSUE THREAD

**Issue by PygBear** [cloudflare/cloudflare-docs#13082]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/use-cases/ssh/

### What changes are you suggesting?

Give correct information to connect SSH to a server using WARP

**Comment by ranbel** [comment]
Hi @PygBear, sorry to hear you're having issues. Can you provide more information on:

- How to replicate the error
- The troubleshooting steps (https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/troubleshoot-tunnels/private-networks/) that you have already tried

The SSH instructions work as written on my M1 Mac. The Homebrew path may be different if you're on an Intel Mac.

**Comment by PygBear** [comment]
GitHub just dumped my whole message. More frustration and my Parkinson's is starting to kick in. Easiest explanation is I followed the guide to the letter 4-5 times and ended in utter failure every time. I can reproduce and had it documented but frustration level just led me to delete and start over. So far every attempt is a fail. I am a software engineer in the medical field and have been writing on a Mac for 30 years and just cannot grasp what is missing. It seems straightforward, but every attempt has gotten so bad I have to wipe and rebuild. I am attempting to make the following products work so that I may reconnect with my other devs:

GitLab 16.9.1
GitKraken 9.12.0
NextCloud 28
NextCloud 28 Client

All have been tried in Windows 11 and MacOS 14.4. Windows is waaaaay worse. That just makes me not be able to use my trackpad anymore. Yes I am on Intel Mac still. Working on updating USB drivers for M series but can't really get to anything right now because I can't get any of this to work.

**Comment by PygBear** [comment]
One more note....I will try again but document with detail once my arms and hands stop shaking. This process hasn't been easy
