### ISSUE TITLE
Fix Cloudflare Images Batch API Documentation

### ISSUE THREAD

**Issue by fiyazbinhasan** [cloudflare/cloudflare-docs#13087]
### Which Cloudflare product does this pertain to?

Images

### Existing documentation URL(s)

https://developers.cloudflare.com/images/upload-images/images-batch/

### What changes are you suggesting?

The documentation says,

```
Example request using a batch token

$ curl -H "Authorization: Bearer <BATCH_TOKEN>" \
  "https://batch.imagedelivery.net/images/v2"
```

The URL should be:

```
https://batch.imagedelivery.net/images/v1
```

> NOTE: The `v2` endpoint returns `{"code":"103","message":"forbidden endpoint"}`. If there is a `v2` endpoint then please add instructions on how to use that. Thanks

**Comment by KimJ15** [comment]
Content now provides more clarity. https://developers.cloudflare.com/images/upload-images/images-batch/
