### ISSUE TITLE
Missing Magic Transit as an Origin Protection Method

### ISSUE THREAD

**Issue by jeffsani** [cloudflare/cloudflare-docs#13095]
### Which Cloudflare product(s) does this pertain to?

Magic Transit

### Subject Matter

Where Magic Transit can be positioned as a method to protect origin servers - i,e. Network layer

### Content Location

https://developers.cloudflare.com/fundamentals/basic-tasks/protect-your-origin-server/

**Comment by marciocloudflare** [comment]
Closed in PR-14169
