### ISSUE TITLE
Very difficult to find full reference for Cloudflare Tunnel YML file format

### ISSUE THREAD

**Issue by simeyla** [cloudflare/cloudflare-docs#13099]
### Which Cloudflare product(s) does this pertain to?

WARP Client

### Subject Matter

Full schema for config.yml files

### Content Location

It is very difficult to find explanation of certain options like the following for `yml` files for Cloudflare Tunnel:

```
no-tls-verify: true
logfile: filename.txt
loglevel: warn
```

The [configuration file documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/) makes no mention of any of them. I had to look at the [source code](https://github.com/cloudflare/cloudflared/blob/110b2b4c807f707fdd973ede6bdb8890f48bc81e/management/events.go#L142) to figure out how to change log level.

There is an option `noTlsVerify` that is documented under [Origin Configuration](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/origin-configuration/#notlsverify) but there is no additional explanation that it needs to be `no-tls-verify` in the `yml` file.

I'm sure I'm missing useful options but it's too hard to figure out one by one what they need to be called.

### Additional information

PS. I think 'Warp Client' is what is now called 'Cloudflare Tunnel' - so you also need to update the dropdown on this page (where I am creating the issue).

See also [community issue](https://community.cloudflare.com/t/cloudflare-tunnel-yml-file-format-schema-full-reference/618809) I opened

**Comment by ranbel** [comment]
Thanks for the feedback! I've opened an internal ticket to get this updated.

**Comment by ranbel** [comment]
Hey @simeyla, Cloudflare is deprioritizing locally-managed tunnels (i.e. YML file configuration) and recommending that customers use [remotely-managed tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-remote-tunnel/). For a remotely-managed tunnel, noTLSVerify and [loglevel ](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/monitor-tunnels/logs/#dashboard)are configured in the dashboard.
The `cloudflared` CLI is the source of truth for locally-managed tunnels. We won't be adding a full reference to the dev docs, but I've added a note in #14801 that refers users to the CLI help text.

**Comment by simeyla** [comment]
Great, thanks for clarifying. 

I only look at my tunnels about twice a year (!) - so good to know the direction, and thanks for adding the note.
