### ISSUE TITLE
[Pages] Update Astro framework guide

### ISSUE THREAD

**Issue by jculvey** [cloudflare/cloudflare-docs#13093]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/

### What changes are you suggesting?

Update the page to have latest guidance on creating projects with c3 and accessing bindings in dev given recent updates.

See also:
https://github.com/cloudflare/cloudflare-docs/pull/12901
https://github.com/cloudflare/cloudflare-docs/pull/12953

**Comment by KimJ15** [comment]
Closed by https://github.com/cloudflare/workers-sdk/pull/5072 and https://github.com/cloudflare/workers-sdk/pull/5079
