### ISSUE TITLE
Regarding the issue of redirection rules

### ISSUE THREAD

**Issue by hao235689** [cloudflare/cloudflare-docs#13109]
### Example URL(s)

For example, I want to https://gt37421.com and https://www.gt37421.com Set to globally accessible. And visiting in China https://gt37421.com and https://www.gt37421.com Automatically jump to https://china.gt37421.com But this setting is incorrect! I don't support it, I don't know what the reason is.

### Actual Behavior

I want to https://gt37421.com And https://www.gt37421.com Set 301 to redirect to https://china.gt37421.com When, the result obtained is incorrect. Error result display:

This page cannot be redirected correctly

An error occurred while connecting to china.gt37421.com.

Sometimes disabling or rejecting cookies can cause this issue.

### Expected Behavior

https://gt37421.com and https://www.gt37421.com Global normal access (except for China), while China visits https://gt37421.com and https://www.gt37421.com Automatically redirect to https://china.gt37421.com ,

### Additional information

![QQ图片20240223001344](https://github.com/cloudflare/cloudflare-docs/assets/139842865/a58d00f5-6e04-4143-838d-7cf9dadb8d84)

**Comment by kodster28** [comment]
Howdy @hao235689, this sounds like more of an issue for the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

**Comment by hao235689** [comment]
Hello, I don't know how to do redirection redirection. Where can I find a tutorial? Could you please send it to me? Is it possible? I spent a week on this matter! There's no way to solve it either!

**Comment by hao235689** [comment]
Hello @kodster28, I have been working on this matter for a week now! There's no way to solve it either! Do you have a solution? May I ask for your advice?
