### ISSUE TITLE
How to parse a UDP address with a port number, for example: 192.170.6.123:4005？

### ISSUE THREAD

**Issue by niwawa2020** [cloudflare/cloudflare-docs#13101]
### Which Cloudflare product(s) does this pertain to?

DNS

### Subject Matter

How to parse a UDP

### Content Location

How to parse a UDP address with a port number, for example: 192.170.6.123:4005？

**Comment by kodster28** [comment]
Howdy @niwawa2020, that's a bit more foundational than a lot of the info we include in our docs.

For help understanding how UDP works in general, I'd refer you to the [Cloudflare Blog](https://blog.cloudflare.com/everything-you-ever-wanted-to-know-about-udp-sockets-but-were-afraid-to-ask-part-1) or [this article](https://www.bleepingcomputer.com/tutorials/tcp-and-udp-ports-explained/).
