### ISSUE TITLE
Restoring original visitor IPs - A correction 

### ISSUE THREAD

**Issue by odysseyalive** [cloudflare/cloudflare-docs#13116]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/#mod_remoteip

### What changes are you suggesting?

RemoteIP is a module, not a site config file. The line needs to say:
```
sudo a2enmod remoteip
```
not
```
sudo a2enconf remoteip
```

**Comment by kodster28** [comment]
Howdy @bridgesense, upon talking with a few internal folks, don't think we'd want to make that change.

From their experience, the `a2enconf` is important so that your server doesn't ignore the `remoteip.conf`, which can lead to an insecure configuration for your server.

**Comment by odysseyalive** [comment]
remoteip.conf is a module, not a website

**Comment by odysseyalive** [comment]
You can decide to do it that way, but you won't be using a2enconf to bring that file onboard without a custom configuration, which your instructions don't provide. I've been shoving Apache around for 15 years.  You might want to double check your sources.

However, repoteip.conf usually comes stock in most Apache configurations, which you'll need a2enmod to deploy. There aren't any security ramifications here unless you're worried about offending GDPR, but what web servers aren't logging IP's for security? The phone companies delete ipv6 traffic anyway so that they aren't obligated to hand them over to subpoenas.
