### ISSUE TITLE
Could not lookup srv records on _v2-origintunneld._tcp.argotunnel.com: lookup _v2-origintunneld._tcp.argotunnel.com on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by woshichenghaibo** [cloudflare/cloudflare-docs#13139]
### Example URL(s)

pan.fo.ax

### Actual Behavior

stderr: 2024-02-24T12:30:04Z INF Starting tunnel tunnelID=c4a2cb84-b434-4ae9-9d23-64750461f666
stderr: 2024-02-24T12:30:04Z INF Version 2024.2.1
stderr: 2024-02-24T12:30:04Z INF GOOS: linux, GOVersion: go1.21.5-devel-cf, GoArch: arm64
stderr: 2024-02-24T12:30:04Z INF Settings: map[no-autoupdate:true token:*****]
stderr: 2024-02-24T12:30:04Z INF Generated Connector ID: 664a7c35-4c0c-4c40-89ca-0b6f91760dc4
stderr: 2024-02-24T12:30:14Z ERR Failed to fetch features, default to disable error="lookup cfd-features.argotunnel.com on 8.8.4.4:53: dial udp 8.8.4.4:53: i/o timeout"
stderr: 2024-02-24T12:30:34Z WRN Unable to lookup protocol percentage.
stderr: 2024-02-24T12:30:34Z INF Initial protocol quic
stderr: 2024-02-24T12:30:34Z INF ICMP proxy will use 172.17.0.2 as source for IPv4
stderr: 2024-02-24T12:30:34Z INF ICMP proxy will use :: as source for IPv6
stderr: 2024-02-24T12:31:09Z ERR edge discovery: error looking up Cloudflare edge IPs: the DNS query failed error="lookup _v2-origintunneld._tcp.argotunnel.com on 8.8.8.8:53: no such host" event=0
stderr: 2024-02-24T12:31:09Z ERR Please try the following things to diagnose this issue: event=0
stderr: 2024-02-24T12:31:09Z ERR   1. ensure that argotunnel.com is returning "origintunneld" service records. event=0
stderr: 2024-02-24T12:31:09Z ERR      Run your system's equivalent of: dig srv _origintunneld._tcp.argotunnel.com event=0
stderr: 2024-02-24T12:31:09Z ERR   2. ensure that your DNS resolver is not returning compressed SRV records. event=0
stderr: 2024-02-24T12:31:09Z ERR      See GitHub issue https://github.com/golang/go/issues/27546 event=0
stderr: 2024-02-24T12:31:09Z ERR      For example, you could use Cloudflare's 1.1.1.1 as your resolver: event=0
stderr: 2024-02-24T12:31:09Z ERR      https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ event=0
stderr: 2024-02-24T12:31:09Z INF Starting metrics server on 127.0.0.1:44187/metrics
stderr: 2024-02-24T12:31:44Z ERR edge discovery: error looking up Cloudflare edge IPs: the DNS query failed error="lookup _v2-origintunneld._tcp.argotunnel.com on 8.8.8.8:53: no such host" event=0
stderr: 2024-02-24T12:31:44Z ERR Please try the following things to diagnose this issue: event=0
stderr: 2024-02-24T12:31:44Z ERR   1. ensure that argotunnel.com is returning "origintunneld" service records. event=0
stderr: 2024-02-24T12:31:44Z ERR      Run your system's equivalent of: dig srv _origintunneld._tcp.argotunnel.com event=0
stderr: 2024-02-24T12:31:44Z ERR   2. ensure that your DNS resolver is not returning compressed SRV records. event=0
stderr: 2024-02-24T12:31:44Z ERR      See GitHub issue https://github.com/golang/go/issues/27546 event=0
stderr: 2024-02-24T12:31:44Z ERR      For example, you could use Cloudflare's 1.1.1.1 as your resolver: event=0
stderr: 2024-02-24T12:31:44Z ERR      https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ event=0
stderr: 2024-02-24T12:31:44Z INF Tunnel server stopped
stderr: 2024-02-24T12:31:44Z ERR Initiating shutdown error="Could not lookup srv records on _v2-origintunneld._tcp.argotunnel.com: lookup _v2-origintunneld._tcp.argotunnel.com on 8.8.8.8:53: no such host"
stderr: 2024-02-24T12:31:44Z INF Metrics server stopped
stderr: Could not lookup srv records on _v2-origintunneld._tcp.argotunnel.com: lookup _v2-origintunneld._tcp.argotunnel.com on 8.8.8.8:53: no such host

### Expected Behavior

docker with no errors

**Comment by kodster28** [comment]
Howdy @woshichenghaibo, this repo can only help with issues related to our documentation itself (not product functionality or bugs unfortunately).

Your best bight might be reaching out in the [Cloudflare Community](https://community.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
