### ISSUE TITLE
Mention that x-amz-checksum-algorithm is not available

### ISSUE THREAD

**Issue by jhonyrdesouza** [cloudflare/cloudflare-docs#13132]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/api/s3/api/

### What changes are you suggesting?

After a bit of debugging, I realized that we still can't use R2 because of this missing feature. Essentially, the lack of this feature means that clients must calculate a hash, which for some use cases is a huge memory load, as it means reading the entire stream into memory before passing it to R2. 

Definitely worth noting in the docs that this header is not available on R2.

### Additional information

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

**Comment by Farrukhraz** [comment]
any updates here?

**Comment by dcpena** [comment]
Hi @jhonyrdesouza, thanks for creating the issue! The S3 API compatibility page you linked has `x-amz-checksum-algorithm` listed as an unimplemented feature for multiple bucket and object-level operations. Because it's documented in the lists, I'm going to go ahead and mark this as closed.
