### ISSUE TITLE
[Workers] Callout AsyncLocalStorage as a Workers alternative for getPlatformProxy

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#13146]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

ALS as a way to get req/env/ctx anywhere in Workers

### Content Location

getPlatformProxy allows users to access their Workers bindings and mock information like `req.cf` and `ctx.waitUntil()`, allowing them to write code for Workers without using Wrangler's development emulation (i.e `next dev` when using [`next-on-pages`](https://github.com/cloudflare/next-on-pages/tree/main/internal-packages/next-dev))

The availability of these variables, without having to pipe them from a handler, is a common request on Workers and can be done with [AsyncLocalStorage](https://developers.cloudflare.com/workers/runtime-apis/nodejs/asynclocalstorage/).

The [current documentation for getPlatformProxy](https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy) states...

> getPlatformProxy cannot be run inside the Workers runtime.

It would be helpful if there was a guide on using AsyncLocalStorage to do the same, and link out to it - I suspect people will come across this page when trying to figure out if that use-case is possible.

The top 5 results for a Google search of "cloudflare workers asynclocalstorage for env" are:

1. [process.env docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/) (doesn't work for bindings)
2. [a community post](https://community.cloudflare.com/t/how-to-access-environment-variables-from-libraries/480041) (talks about using AsyncLocalStorage to implement this)
3. [environment variables docs](https://developers.cloudflare.com/workers/configuration/environment-variables/) (no mention of AsyncLocalStorage)
4. [AsyncLocalStorage docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/asynclocalstorage/) (no mention of using it within imports, libraries or using it to store per-request state)
5. [a next-on-pages issue](https://github.com/cloudflare/next-on-pages/issues/1) (talks about using AsyncLocalStorage to implement this).

**Comment by KimJ15** [comment]
This issue is pretty stale. Closing as won't do for now.
