### ISSUE TITLE
warp-client license info

### ISSUE THREAD

**Issue by xpufx** [cloudflare/cloudflare-docs#13150]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/warp-client/

### What changes are you suggesting?

I can't find the license information for cloudflare's client software, including the warp desktop client. What license is the software distrubuted as?  The above url is a suggested place to add the info.

### Additional information

No more details at this time.

**Comment by kodster28** [comment]
Howdy @xpufx, it sounds like the information you're looking for might be at https://developers.cloudflare.com/warp-client/legal/?
