### ISSUE TITLE
Purge Cache History

### ISSUE THREAD

**Issue by landsman** [cloudflare/cloudflare-docs#13175]
### Which Cloudflare product(s) does this pertain to?

Cache

### Subject Matter

Purge Cache History

### Content Location

There is no info on how can I see when Purge Cache was done, and by which API token.

### Additional information

I would love to see this audit for debugging.

**Comment by angelampcosta** [comment]
Hi @landsman Thank you for raising this issue.  At the moment this feature is not available but it's on the roadmap.

**Comment by landsman** [comment]
Hi @angelampcosta thanks for the reply. Is the roadmap somewhere visible, can I vote there, or subscribe to know about updates on it? 🙏

**Comment by angelampcosta** [comment]
Currently, those options are not unavailable. However, please refer to our documentation for any forthcoming updates.
