### ISSUE TITLE
Jekyll npm requirements

### ISSUE THREAD

**Issue by stuartmau** [cloudflare/cloudflare-docs#13174]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Cloudflare Jekyll deploy fails without vaild npm package.json

### Content Location

On the Deploy a Jekyll site page, please add a note that Cloudflare Pages Deploy will call npm in addition to the Jekyll build commands and therefore a vaild package.json file is required

Cloudflare will run "npm clean-install --progress=false" which will fail if a valid package.json is not found.

https://developers.cloudflare.com/pages/framework-guides/deploy-a-jekyll-site/

### Additional information

Adding an valid empty json file resolved the failure.

**Comment by kodster28** [comment]
Howdy @stuartmau, did some testing and cannot reproduce your issue.

Testing via this [base repo](https://github.com/kodster28/jekyll-test) led to the successful creation of [this live site](https://jekyll-test-d6d.pages.dev/).

Going to close out this issue for now, but if you experience further issues feel free to open a new one or ask for help in the [Cloudflare discord](https://discord.cloudflare.com/).
