### ISSUE TITLE
Instructions on Git integration guide for accessing a git repo for pages that you are a collaborator of but belongs to someone else

### ISSUE THREAD

**Issue by tylerdurton** [cloudflare/cloudflare-docs#13189]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Whether you can see other repos that you are collaborator on when authorising github

### Content Location

https://developers.cloudflare.com/pages/get-started/git-integration/#select-your-github-repository

### Additional information

I would like to access a repo that belongs to another user but i am an authorised collaborator. When trying to set this up in pages, i only see my own repos. If this is not possible, it should be mentioned in this document. Thanks.

**Comment by kodster28** [comment]
Howdy @tylerdurton, it sounds like that is addressed in the current text there:

> You can select a GitHub project from your personal account or an organization you have given Pages access to. This allows you to choose a GitHub repository to deploy using Pages. Both private and public repositories are supported.

So it's either from your personal account or an organization you're a part of.

**Comment by kodster28** [comment]
Closing this out due to a lack of information. If this is still an issue and I'm closing this out in error, feel free to re-open another issue (and tag me!).
