### ISSUE TITLE
GraphQL Variable Substitution example is incorrect

### ISSUE THREAD

**Issue by third774** [cloudflare/cloudflare-docs#13242]
### Which Cloudflare product does this pertain to?

Analytics

### Existing documentation URL(s)

https://developers.cloudflare.com/analytics/graphql-api/getting-started/compose-graphql-query/#variable-substitution

### What changes are you suggesting?

![graphiql-query-variables_hu469b185c0e3070a2a5345f27c06e1508_51033_631x461_resize_q75_box_3-3929058f](https://github.com/cloudflare/cloudflare-docs/assets/8732191/2725e3c7-5d5a-4f41-9eac-27652f03a39b)

`"$zoneTag"` being in quotes here causes this to be interpreted as the literal string. It should be `$zoneTag` in order for variable substitution to work correctly.

**Comment by angelampcosta** [comment]
@third774 Thank you for bringing this up. I'll follow up with an internal ticket.
