### ISSUE TITLE
[Workers KV] Documentation pretty confusing for me

### ISSUE THREAD

**Issue by angel-luis** [cloudflare/cloudflare-docs#13271]
### Which Cloudflare product does this pertain to?

KV

### Existing documentation URL(s)

- https://developers.cloudflare.com/kv/get-started/

### What changes are you suggesting?

First of all, my experience with Cloudflare's documentation is overall a 10 out of 10, but wasn't the case of Workers KV documentation.

As usual, to start learning a new tool, I started with Get started. From my experience with other key-value systems, I expected to get working in less of 10 minutes. So I created a namespace from the Dashboard, then I created a new key-value pair, and then I tried to fetch it from the Worker. At first, I thought I had a problem with my code, then I checked the documentation of the framework I'm using (Hono), and I spend a lot of time trying to figure out why it didn't work. So then, I tried to create the namespace and the pairs with Wrangler. I got the same result. I read the steps 3 and 4 several times. To be honest, I didn't move to the 5 step. Then, I created inside the code of the Worker another key-value pair and I found it worked, so I started to look for other pages in the documentation trying to find a response (without know exactly what to look for), and then I asked in the Discord community for more clarification.

At this point I haven't clear what workflow to follow, to have the same namespace both in cloud and local. This night I will test more and I will try to figure out what's the workflow that is best suited for my needs, but, as I described, the documentation it wasn't help me.

My suggestion is to clarify the workflow of local and production development using KV's **before** the steps 3 and 4. I think it will help a lot to new users of the platform.

**Comment by Maddy-Cloudflare** [comment]
Addressed on here: https://github.com/cloudflare/cloudflare-docs/pull/13990
