### ISSUE TITLE
[Docs Site] Review Hugo templates

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#13278]
### Example URL(s)

N/A

### Actual Behavior

N/A

### Expected Behavior

N/A

### Additional information

Hugo's CLI has two options, `--templateMetrics` and `--templateMetricsHints`, which let you see how much runtime is being spent per template (i.e `partials/sidebar.navitem.html`). It also shows `cache potential` which is an indication of how many calls you could save by swapping to `cachedPartial`.

```
Template Metrics:

     cumulative       average       maximum      cache  percent  cached  total  
       duration      duration      duration  potential   cached   count  count  template
     ----------      --------      --------  ---------  -------  ------  -----  --------
  1m56.892661728s     356.311µs  146.043583ms         45        0       0  328063  partials/sidebar.navitem.html
  58.981134694s   18.437366ms  185.075833ms         12        0       0   3199  partials/sidebar.nav.html
  57.361511467s   26.409535ms  263.023042ms          0        0       0   2172  _default/single.html
  16.563078203s   28.655844ms  180.659541ms          0        0       0    578  _default/list.html
  12.369682814s    3.625346ms  251.895833ms         20        0       0   3412  partials/head.meta.html
  ```
  
As you can see here, `sidebar.navitem.html` is called 328,063 times but 45% of those invocations could be cached - I did this locally and halved the rebuild times, although that is rendered mostly moot by the partial rebuild logic added to Hugo v0.123.0 (PR @ https://github.com/cloudflare/cloudflare-docs/pull/13277).
  
It still makes sense to take a look at these metrics though, as it will still improve build speeds (and generally gives you a good insight into which templates could be cleaned up).

**Comment by kodster28** [comment]
Based on Discord discussions, sounds like the biggest benefit would be rewriting our sidebar component to benefit from caching.

Other problems noted here are also partially addressed by #13277.

**Comment by KianNH** [comment]
As seen in https://github.com/cloudflare/cloudflare-docs/pull/13321, Hugo's GetPage function used to accept our incorrect usage where we included the `/content/` directory in the path.

> When using the GetPage method on a Site object, specify a path relative to the content directory.
https://gohugo.io/methods/site/getpage/

Since they stopped that in 0.123.0 (https://github.com/gohugoio/hugo/issues/12174#issuecomment-1971174394), it broke the Pages build configuration partials.

Hugo didn't throw an error or fail the build, it just silently continued. We should add error handling to make sure that if we can't fetch a page, it fails. i.e:

```html
{{ $shortcodeParams := . }}
{{ $path := "content/pages/_partials/_build-configuration.md" }}
{{- with $.Site.GetPage $path -}}
  <div class="DocsMarkdown--table-wrap">
    <div class="DocsMarkdown--table-wrap-inner">
      <table>
        <thead>
          <tr>
            <th>Configuration option</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Production branch</td>
            <td><code>main</code></td>
          </tr>
          <tr>
            <td>Build command</td>
            <td><code>{{(index .Params.build_configs ($shortcodeParams.Get "framework")).build_command}}</code></td>
          </tr>
          <tr>
            <td>Build directory</td>
            <td><code>{{(index .Params.build_configs ($shortcodeParams.Get "framework")).build_output_directory}}</code></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{{ else }}
  {{ errorf "Unable to get page '%s'" $path }}
{{ end }}
```

**Comment by kodster28** [comment]
Part of #13376

**Comment by KianNH** [comment]
Some Tab Switcher fixes: https://github.com/cloudflare/cloudflare-docs/pull/13735

**Comment by kodster28** [comment]
Going to close this out of the public repo as we're tracking the issue internally.
