### ISSUE TITLE
Add instructions for reporting malicious usage of Cloudflare Turnstile

### ISSUE THREAD

**Issue by alexismongo** [cloudflare/cloudflare-docs#13286]
### Which Cloudflare product(s) does this pertain to?

Turnstile

### Subject Matter

Let us report malicious usage of Turnstile so it can be disabled

### Content Location

This should be a new document, discussing malicious use of turnstile to protect attacker infrastructure, like malware or phishing sites. This is surely against your terms of service, and detection should lead to the Turnstile service being disabled for the malicious resources being protected. 

Allowing Turnstile to be removed from malicious sites would render those sites available to automated analysis, which could then better protect users from abuse, credential theft, and malware outbreak.

**Comment by kodster28** [comment]
Howdy @alexismongo, I think your best bet might be reading [Report abuse](https://developers.cloudflare.com/fundamentals/reference/report-abuse/), which provides links to Cloudflare's abuse policy and available actions.

**Comment by alexismongo** [comment]
No, I have found the report abuse page at abuse.cloudflare.com to be lacking in ability to report an abusive Turnstile user. When I attempt to do that for a site using Turnstile, it rejects my submission with the message that the page is not hosted by cloudflare or is not a cloudflare customer. If there is a way to submit Turnstile abuse already, I would be happy to use it.

If you want an example, see login.vision-pet[.]com with the brackets removed. That is a phishing site.
