### ISSUE TITLE
How can I interface with CLOUDFLARE and my ICLOUD mail account?

### ISSUE THREAD

**Issue by Suhyeon-Eom** [cloudflare/cloudflare-docs#13290]
### Which Cloudflare product(s) does this pertain to?

DNS, Email Routing

### Subject Matter

Domain modification

### Content Location

I want to interface with my ICLOUD account and CLOUDFLARE. But there are prohibit to modify CLOUDFLARE Domain. I need to change CLOUDFLARE domain. Please guide me a how to interface with ICLOUD.

**Comment by kodster28** [comment]
Howdy @Suhyeon-Eom, not sure if you've seen it, but we do have some [general guidance around iCloud accounts](https://developers.cloudflare.com/registrar/account-options/icloud-domains/).

If that doesn't help you, you might try reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/)
