### ISSUE TITLE
website always down every minute after install lates versionarm64

### ISSUE THREAD

**Issue by gerandonk** [cloudflare/cloudflare-docs#13297]
### Example URL(s)

http://demo.igrwifi.my.id/

### Actual Behavior

after downgrade to version version 2023.8.2 web back normaly without downtime

### Expected Behavior

i hope lates version still stable like old version and make hight perfomance

**Comment by kodster28** [comment]
Howdy @gerandonk, that's not really something we can help with given that this repo (and team) are responsible for documentation.

Forwarding to the internal team responsible for WARP ENG.
