### ISSUE TITLE
How to append an element to element 

### ISSUE THREAD

**Issue by yifan97** [cloudflare/cloudflare-docs#133]
So the below handler allows us to do things with `element`.  I am wondering how can we append a nested/child element to  `element`?
```
class ElementHandler {
  element(element) {
    // An incoming element, such as `div`
    console.log(`Incoming element: ${element.tagName}`)
  }
}
```

**Comment by adamschwartz** [comment]
According to the docs, [the `Content` type](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#global-types) must be a `string`. Though it’s not the same, you _can_ append a string and have it be treated as HTML:

```js
element.append(htmlString, { html: true })
```

But as far as the docs say, you cannot hold onto an element and append it later to another element, e.g.

cc @ispivey 

Sources:
https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#methods
https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#global-types

**Comment by KimJ15** [comment]
Given the last comment, this question has been resolved. Please reach out to community.cloudflare.com or support.cloudflare.com for additional assistance!
