### ISSUE TITLE
1323 error

### ISSUE THREAD

**Issue by bjxc20230318** [cloudflare/cloudflare-docs#13327]
### Which Cloudflare product(s) does this pertain to?

DNS

### Subject Matter

1323 error

### Content Location

Make payments for your unpaid invoices to proceed. Your account is locked due to the unpaid invoices. (Code: 1323)

### Additional information

1323 error

**Comment by bjxc20230318** [comment]
1323 error

**Comment by bjxc20230318** [comment]
Make payments for your unpaid invoices to proceed. Your account is locked due to the unpaid invoices. (Code: 1323)

**Comment by bjxc20230318** [comment]
Make payments for your unpaid invoices to proceed. Your account is locked due to the unpaid invoices. (Code: 1323)

**Comment by kodster28** [comment]
Related to https://www.cloudflarestatus.com/incidents/36b3bn7j3mqh

**Comment by le2Ks** [comment]
Got same issue. No unpaid invoices so far tho.. this is retarded. Gotta switch from CloudFlare to another similar company. CloudFlare is broken.

**Comment by frossi85** [comment]
I have the same issue and not solution so far, we need to do a domain migration and we are blocked, it says we have a debt but we have no unpaid invoices so far like @le2Ks If this is not solved soon we will need to migrate to another company too

**Comment by bryn1u** [comment]
Same here. CF sucks.
