### ISSUE TITLE
[D1] Pricing for writes + index

### ISSUE THREAD

**Issue by ManasMadrecha** [cloudflare/cloudflare-docs#13334]
### Which Cloudflare product does this pertain to?

D1

### Existing documentation URL(s)

- https://developers.cloudflare.com/d1/platform/pricing/#frequently-asked-questions

### What changes are you suggesting?

In the docs, it is mentioned that

> Can I use an index to reduce the number of rows read by a query?
> 
> Yes, you can use an index to reduce the number of rows read by a query. [Creating indexes (https://developers.cloudflare.com/d1/build-databases/use-indexes/) for your most queried tables and filtered columns reduces how much data is scanned and improves query performance at the same time. If you have a read-heavy workload (most common), this can be particularly advantageous. Writing to columns referenced in an index will add at least one (1) additional row written to account for updating the index, but this is typically offset by the reduction in rows read due to the benefits of an index.

But it does not clarify how many writes will be counted if I add rows to a table which contain an indexed column.

For example, if I write 20 new rows in a table, that has a city column (which is indexed), but in my 20 new rows, there are only 5 unique cities. so, how many rows will I be charged for the writes? 20 or 21 or 25?

Another example, if I add more 10 rows to this table but these rows have the city names already present in the existing table. So, will I charged for only 10 rows as no index needs to be updated? Or 11?

Kindly clarify in the docs regarding this.

**Comment by Maddy-Cloudflare** [comment]
"5. Indexes will add an additional written row when writes include the indexed column, as there are two rows written: one to the table itself, and one to the index. The performance benefit of an index and reduction in rows read will, in nearly all cases, offset this additional write."
