### ISSUE TITLE
docs(R2): clarify resumablity / TUS support

### ISSUE THREAD

**Issue by MentalGear** [cloudflare/cloudflare-docs#13342]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

Your object storage docs  (R2) do not mention whether file upload resumable / TUS is supported. The only TUS mention is for the video 'stream' service. Resumable / TUS is elementary for large file uploads.

### What changes are you suggesting?

 Please indicate whether cloudflare R2 supports this and how.

### Additional information

e.g. support for uppy (popular upload js client)

**Comment by petetak** [comment]
Are there any updates on this please?

**Comment by helloimalastair** [comment]
R2 does not support TUS at the moment, though it should at least be implementable with a Worker.
