### ISSUE TITLE
how can i  use pip3 in cloudflare pages ?

### ISSUE THREAD

**Issue by fengzhao** [cloudflare/cloudflare-docs#1336]
### Expected Behavior
I  want to use python3 and pip3 to build my mkdocs 

### Actual Behavior
I set the variable PYTHON_VERSION to 3.7 and import my github repo to build my mkdocs , but when i build it , it actualy use the default python2's package tool pip to install my requirements package 

### Section that requires update
I want to use pip3 , please support the pip variables

**Comment by RarogCmex** [comment]
It settings up automatically when you setting up python version
https://github.com/netlify/build-image/blob/trusty/included_software.md

And
https://github.com/netlify/build-image

Code:
https://github.com/netlify/build-image/blob/xenial/run-build-functions.sh

**Comment by yarzarsoe** [comment]
https://github.com/cloudflare/.github/blob/05b74655c8178e7d08913bca86f18d03352eed55/CODE_OF_CONDUCT.md

**Comment by fengzhao** [comment]
> It settings up automatically when you setting up python version
> https://github.com/netlify/build-image/blob/trusty/included_software.md
> 
> And
> https://github.com/netlify/build-image
> 
> Code:
> https://github.com/netlify/build-image/blob/xenial/run-build-functions.sh

my mkdoc works well on my ununtu18.04 server  with python3.7 and pip3 , but it report "List index out of range" 

`
<html>
<body>
<div class="c_cn" style="box-sizing: border-box; margin: 63px 0px 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; vertical-align: baseline; color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><article class="c_du c_dv c_dw c_cv c_cw c_ax c_ay" style="box-sizing: border-box; margin: 0px auto; padding: 64px 16px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; display: block; min-height: 411px;"><div class="c_cv c_cw c_dx c_dy" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; width: 1024px; max-width: 64em;"><div class="" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline;"><div class="c_as c_df c_cz c_bx c_gb c_ga c_il c_eo" style="box-sizing: border-box; margin: 16px 0px; padding: 0px; border: 1px solid rgb(182, 182, 182); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; position: relative; border-radius: 5px;"><pre class="c_fd c_ar c_av c_aw c_nw c_nx c_bk c_ld c_hs c_hq c_hr c_kt c_ht c_cg c_ny" style="box-sizing: border-box; margin: 0px; padding: 16px 32px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(213, 215, 216) rgb(213, 215, 216) rgb(217, 217, 217); border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monaco, courier, monospace; font-size: 12px; vertical-align: baseline; background-color: rgb(242, 242, 242); border-radius: 0px; color: rgb(54, 57, 58); display: block; overflow: auto; width: 1022px; height: 500px;">

12:08:51.192 | Using Swift version 5.2
-- | --
12:08:51.192 | Installing Hugo 0.54.0
12:08:51.708 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
12:08:51.709 | Started restoring cached go cache
12:08:51.711 | Finished restoring cached go cache
12:08:52.090 | go version go1.14.4 linux/amd64
12:08:52.106 | go version go1.14.4 linux/amd64
12:08:52.114 | Installing missing commands
12:08:52.114 | Verify run directory
12:08:52.114 | Executing user command: mkdocs build
12:08:52.731 | INFO    -  Cleaning site directory
12:08:52.732 | INFO    -  Building documentation to directory: /opt/buildhome/repo/site
12:08:52.817 | ERROR   -  Error reading page 'index.md': list index out of range
12:08:52.819 | Traceback (most recent call last):
12:08:52.819 | File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
12:08:52.819 | sys.exit(cli())
12:08:52.819 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
12:08:52.819 | return self.main(*args, **kwargs)
12:08:52.819 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1059, in main
12:08:52.820 | rv = self.invoke(ctx)
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
12:08:52.820 | return _process_result(sub_ctx.command.invoke(sub_ctx))
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
12:08:52.820 | return ctx.invoke(self.callback, **ctx.params)
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 767, in invoke
12:08:52.820 | return __callback(*args, **kwargs)
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
12:08:52.820 | build.build(config.load_config(**kwargs), dirty=not clean)
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 271, in build
12:08:52.820 | _populate_page(file.page, config, files, dirty)
12:08:52.820 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 168, in _populate_page
12:08:52.821 | 'page_markdown', page.markdown, page=page, config=config, files=files
12:08:52.821 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
12:08:52.821 | result = method(item, **kwargs)
12:08:52.821 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 155, in on_page_markdown
12:08:52.821 | is_first_commit=False,
12:08:52.821 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 106, in get_git_commit_timestamp
12:08:52.821 | git = self._get_repo(realpath)
12:08:52.821 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 43, in _get_repo
12:08:52.821 | raise_ci_warnings(self.repo_cache[path])
12:08:52.821 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 21, in raise_ci_warnings
12:08:52.821 | n_commits = commit_count(repo)
12:08:52.822 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 88, in commit_count
12:08:52.822 | refs = [x.split()[0] for x in refs]
12:08:52.822 | File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/ci.py", line 88, in <listcomp>
12:08:52.822 | refs = [x.split()[0] for x in refs]
12:08:52.822 | IndexError: list index out of range
12:08:52.880 | Failed: build command exited with code: 1

</pre><div class="c_mx c_c" style="box-sizing: border-box; margin: 0px; padding: 32px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; display: flex;"><button type="button" class="c_hb c_hc c_hd c_he c_hf c_hg c_hh c_hi c_hj c_hk c_hl c_v c_q c_hm c_gh c_hn c_ho c_hp c_hq c_hr c_hs c_ht c_ct c_hu c_hv c_hw c_hx c_hy c_hz c_ia c_ib c_bx c_ic c_id c_ie c_if c_u c_ig c_ih c_ap c_ds c_gt c_dt c_cv c_ax c_ay c_bi c_bj c_ii c_aj c_ij c_dd c_en c_ik" style="box-sizing: border-box; color: rgb(255, 255, 255); font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 14px; line-height: 1.2; -webkit-font-smoothing: subpixel-antialiased; border: 0px solid currentcolor; cursor: pointer; -webkit-text-stroke: 0px; user-select: none; display: inline-flex; vertical-align: middle; align-items: center; -webkit-box-align: center; white-space: nowrap; padding: 8px 16px; position: relative; margin: 0px 0px 0px auto; justify-content: center; -webkit-box-pack: center; font-weight: 400; border-radius: 5px; opacity: inherit; pointer-events: auto; text-align: center; transition-property: background-color, border-color, color; transition-duration: 200ms; transition-timing-function: ease; max-width: initial; float: none; background-color: rgb(0, 81, 195); width: auto;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline;">重试部署</span></button></div></div></div></div></article></div><footer class="c_b c_cp c_cq c_ax c_ay c_cr c_cs c_ct c_cu" style="box-sizing: border-box; margin: 32px 0px 0px; padding: 32px 16px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(217, 217, 217); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; vertical-align: baseline; display: block; background-color: rgb(255, 255, 255); color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="c_cv c_cw c_c c_cx c_cy" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; display: flex; max-width: 64rem; flex-wrap: wrap;"><div class="c_cz c_da c_db c_dc" style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; width: 204.797px;"><br class="Apple-interchange-newline">
</body>
</html>`

**Comment by KimJ15** [comment]
👋 @fengzhao  Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! Please reach out to community.cloudflare.com for additional assistance!
