### ISSUE TITLE
Link to 'Using Service Bindings' from dashboard is broken

### ISSUE THREAD

**Issue by ryan0x44** [cloudflare/cloudflare-docs#13372]
### Example URL(s)

- https://dash.cloudflare.com/ACCOUNT_ID_HERE/workers/services/view/WORKER_NAME_HERE/WORKER_ENV_HERE/triggers

### Actual Behavior

<img width="791" alt="Screenshot 2024-03-12 at 12 17 45 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/1902353/0f2aeb0d-d3ee-4b66-ad88-7994b7a8994e">

Under 'Bound Services' there's a link pill 'Using Service Bindings' which currently points at <https://developers.cloudflare.com/workers/learning/using-services/#workers-service-bindings>

### Expected Behavior

The correct URL for the relevant docs I believe would be <https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/#service-bindings> instead.

**Comment by kodster28** [comment]
Created an internal ticket to have this addressed by our dashboard team. Closing this out as it's _technically_ outside of the scope of the content in this repo.
