### ISSUE TITLE
docs(error): createmultipartupload text contains text of above createBucket text

### ISSUE THREAD

**Issue by MentalGear** [cloudflare/cloudflare-docs#13398]
### Example URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/r2/api/s3/extensions.md#createmultipartupload

### Actual Behavior

createmultipartupload text contains text of above cf-create-bucket-if-missing text

### Expected Behavior

Text describing createmultipartupload, currently it's just replicating the text above it.

**Comment by KianNH** [comment]
Resolved by https://github.com/cloudflare/cloudflare-docs/pull/15232
