### ISSUE TITLE
I am getting authentication issue. 

### ISSUE THREAD

**Issue by berisrikanth77** [cloudflare/cloudflare-docs#13405]
### Which Cloudflare product(s) does this pertain to?

Terraform

### Subject Matter

cf-terraforming issue

### Content Location

I am trying to fetch Cloudflare record using cf-terraform. but I am getting below error while following the instructions provided by cf terraform.

With same api token and zone id I am able write the records in Cloudflare. 

terraform --version
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.26.0

Your version of Terraform is out of date! The latest version
is 1.7.4. You can update by downloading from https://www.terraform.io/downloads.html

"cf-terraforming generate   --zone $CLOUDFLARE_ZONE_ID  --resource-type "cloudflare_record" -v" 
error

2024/03/13 17:16:57 
HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: 863bc951ce9d9abd-MIA
Content-Type: application/json
Date: Wed, 13 Mar 2024 11:46:57 GMT
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGUFqYFDiSDreGJnUyNeiqPcQoN5; SameSite=Lax; path=/; expires=Wed, 13-Mar-24 14:16:58 GMT; HttpOnly
Set-Cookie: __cfruid=656d1f95884b4bf173229b4d18bd23094f4e7b25-1710330417; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding

{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
FATA[0001] Authentication error (10000)

**Comment by ranbel** [comment]
Hi @berisrikanth77, thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo. Please reach out to community.cloudflare.com or support.cloudflare.com for troubleshooting assistance!
