### ISSUE TITLE
Issues with Cloudflare CA certificate installation instructions for RubyGems

### ISSUE THREAD

**Issue by lukevalenta** [cloudflare/cloudflare-docs#13412]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/install-cloudflare-cert/#rubygems

### What changes are you suggesting?

There are two issues with the instructions for installing the Cloudflare root CA in rubygems.

1. See https://gist.github.com/joseluisq/e3b2f43e7e2453b2a84c for details, but the command `gem which rubygems` returns a file `rubygems.rb`, and the suffix needs to be trimmed. In bash or zsh, the following change should work:
```
export RUBY_DIR=$(gem which rubygems)
```
to
```
export RUBY_DIR=${$(gem which rubygems)%.rb}
```
The corresponding instructions for Windows should also be fixed.

2. On macOS Sonoma (14.3.1), my rubygems path is as follows:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ssl_certs/rubygems.org/
```
However, I get `Operation not permitted` when trying to copy a file into that directly (even when run with `sudo` and enabling `Full Disk Access` to my terminal application). Based on https://cleanmymac.com/blog/operation-not-permitted-terminal, this seems to require disabling System Integrity Protection (SIP), but I haven't tried it. I'm not sure if we _should_ recommend these steps, but I just wanted to report this issue.

**Comment by crwaters16** [comment]
Hey Luke - tagging you on the internal ticket to track the work there!
