### ISSUE TITLE
Are comments secret?

### ISSUE THREAD

**Issue by shapeh** [cloudflare/cloudflare-docs#13430]
### Existing documentation URL(s)

https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/

### What changes are you suggesting?

Page says:

> The information in record attributes will not impact DNS record resolution or propagation timing and is only meant for your reference.

 That's fine but are `DNS record comments` secret, i.e. whatever is the comment won't be shared in public?

**Comment by Erisa** [comment]
DNS record comments are only visible privately to members of your Cloudflare account, and are never shown publicly.

**Comment by shapeh** [comment]
Okay thank you. I suggest the docs be updated and the dashboard as well with this info.

**Comment by Erisa** [comment]
Opened #13433
