### ISSUE TITLE
Origin Rules send wrong request to server

### ISSUE THREAD

**Issue by cmal** [cloudflare/cloudflare-docs#13464]
### Example URL(s)

https://ttrss.agquantonline.com

### Actual Behavior

![image](https://github.com/cloudflare/cloudflare-docs/assets/1773318/e69f7a2a-94ed-4280-a356-4931fe442e1e)
![image](https://github.com/cloudflare/cloudflare-docs/assets/1773318/ad0c25d1-630e-45f2-b350-cc3d644cf131)

visit url https://ttrss.agquantonline.com with a GET request in browser, actually send a POST request of https://ttrss.agquantonline.com/backend.php  to server. (It is so strange)

### Expected Behavior

should send a GET request of https://ttrss.agquantonline.com

**Comment by kodster28** [comment]
Howdy @cmal, unfortunately this is a documentation repo (and not an avenue to [contact Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

If you needed help, you could also reach out in the [Cloudflare Community](https://community.cloudflare.com/).
