### ISSUE TITLE
Document that Wasm code generation is disallowed

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/cloudflare-docs#13469]
### Proposed changes

In our [Javascript standards section](https://developers.cloudflare.com/workers/runtime-apis/web-standards/#javascript-standards) we document that `eval()` and  `new Function` are not allowed for security reasons.

We should also add that wasm code generation is also disallowed.

___

Is the Javascript Standards section the best place for this information? or is there a different more proper location for this?

**Comment by dario-piotrowicz** [comment]
I'd likely follow this page from the Next.js docs: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

and mention:
- `WebAssembly.compile` and
- `WebAssembly.instantiate`

([source](https://github.com/vercel/next.js/blob/f1a999ee7388ead52fe4bddfede8e2915544659c/errors/edge-dynamic-code-evaluation.mdx#L12-L13))

**Comment by irvinebroque** [comment]
Just make a PR, can always move it. https://developers.cloudflare.com/workers/runtime-apis/webassembly/
