### ISSUE TITLE
Multiple engineers can't comprehend the difference this section is attempting to communicate with the multiple use cases

### ISSUE THREAD

**Issue by ryanhos** [cloudflare/cloudflare-docs#13478]
### Existing documentation URL(s)

https://developers.cloudflare.com/waf/reference/legacy/old-rate-limiting/#order-of-rule-execution

### What changes are you suggesting?

This passage is attempting to communicate the details about a difference in behavior, but doesn't quite get there.  Could the examples be clarified, or could additional examples be added to illustrate the difference that we need to understand here?

**Comment by pedrosousa** [comment]
Hi @ryanhos 
Thank you for your feedback.

I've clarified the text in the section you mentioned in PR #13531.
