### ISSUE TITLE
Worst human verification  ever

### ISSUE THREAD

**Issue by OscarPhilips** [cloudflare/cloudflare-docs#13479]
### Example URL(s)

Every website I go to that uses Cloudflare Human verification fails with Microsoft Edge on three different computers forcing the use of other browsers ... any other browser.

### Actual Behavior

Cloudflair continues to cycle back to click to verify

### Expected Behavior

I would expect verification when I click the box

### Additional information

I am so disappointed I am start to write each web master using your system that the system sucks.   If I have this problem on three separate systems there must be hundreds of not thousands of users equally frustrated.

**Comment by kodster28** [comment]
Apologies @OscarPhilips, but there's not much we can do about this from the docs repo or docs team side.

You might be able to find some information either in [Cloudflare challenges](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#browser-support) or the [Cloudflare community](https://community.cloudflare.com).
