### ISSUE TITLE
[Cloudflare Zero Trust] A link in a guide is incorrect

### ISSUE THREAD

**Issue by itaquito** [cloudflare/cloudflare-docs#13483]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#verify-the-jwt-manually

### What changes are you suggesting?

Hello! This issue is located on Cloudflare Zero Trust > Identity > Authorization Cookie > Validate JWTs > ​​[Verify the JWT manually](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#verify-the-jwt-manually) > Step 6 > a)

In this step, an invalid URL is shown. Currently, it says `Go to https://<your-team-name>/cdn-cgi/access/certs.`. First, `<your-team-name>` is an invalid domain name. But also, the correct domain should be `<your-team-name>.cloudflareaccess.com` as described in the [Access signing keys](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#access-signing-keys) section on the same page.

Hope this issue makes the documentation a little better. Thanks for your hard work!

**Comment by ranbel** [comment]
Thanks for flagging the issue!
