### ISSUE TITLE
Pages, Git Intergation, Pausing Automatic Builds is not showing in the UI

### ISSUE THREAD

**Issue by NV** [cloudflare/cloudflare-docs#13480]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/configuration/git-integration/#pausing-automatic-builds

### What changes are you suggesting?

> To pause automatic deployments, go to the Pages project’s **Settings** > **Builds & deployments** > select **Pause deployments** at the end of the page.

![](https://developers.cloudflare.com/assets/git.pause_hua2ac0dbefc682cddc77fa53b6111f68d_25980_1602x520_resize_q75_box_3-b351c6dc.png)

I don't see such section at all.

I don't know if feature was removed for some reason (that would be unfortunate) or it migrated elsewhere (than the documentation should be updated).

**Comment by GregBrimble** [comment]
![image](https://github.com/cloudflare/cloudflare-docs/assets/8484333/70d06ef2-dcc7-41a6-aad2-db56a57112eb)

Looks like you're on the Manage tab rather than Settings. You should go Settings > Builds & deployments > Configure Production deployments > Enable automatic production branch deployments.

**Comment by NV** [comment]
I see, thank you.

I was showing the screenshot from the (documentation)[https://developers.cloudflare.com/pages/configuration/git-integration/#pausing-automatic-builds]. It's not up-to-date with the current UI, it seems.
