### ISSUE TITLE
Add documentation on how to migrate a Next.js application to Cloudflare Pages

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/cloudflare-docs#13510]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/nextjs/

### What changes are you suggesting?

We have documentation that guide people to create a brand new Next.js project and deploy it to Pages, it could be beneficial t o also have a migration guide that could guide people on how to migrate to Pages a Next.js project deployed on Vercel or self hosted (those two being the only two alternatives as per the Next.js docs: https://nextjs.org/docs/pages/building-your-application/deploying).

### Additional information

- Where could such documentation live in a way that is discoverable but does not get in the way of people trying to create new Next.js Pages application?

- Should this also be done for other frameworks too?

**Comment by kodster28** [comment]
This appears to have been addressed in the new revisions to https://developers.cloudflare.com/pages/framework-guides/nextjs/ssr/get-started/#existing-apps
(feel free to re-open if I'm mistaken here)
