### ISSUE TITLE
Missing command to install 'iptables-persistent'

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#13538]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/

### What changes are you suggesting?

In section 5 step 2, we are required to add iptables mangle rules for MTU clamping.
But the path 'etc/iptables/rules.v4' only exists if you install the package 'iptables-persistent', and there is no mention this is needed in this section.
Please add that.

**Also, please add a mention that the user should actually execute the script saved to /usr/local/bin/apply_iptables_rules.sh, else rules.v4 will not be written. (Don't forget `sudo chmod +x /usr/local/bin/apply_iptables_rules.sh` ;) )**

**Comment by ranbel** [comment]
Hi, thanks for opening this issue. 
1.`iptables-persistent` is in the prereqs: 
<img width="672" alt="Screenshot 2024-03-20 at 11 26 51 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/101146722/9ff5591f-4b54-4e3b-b73b-0a2fc538e3a9">
2. Here are the instructions for updating `/usr/local/bin/apply_iptables_rules.sh`: 
<img width="661" alt="Screenshot 2024-03-20 at 11 27 14 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/101146722/f87cf13e-ab5b-4568-b660-779b41e6ed3e">
(We're investigating if we can automate this step and simplify the WARP Connector installation.)

**Comment by etec-masterofsynapse** [comment]
@ranbel Thanks for the comment.
I didn't even see that there was a button that shows the prerequisite button, so maybe the UI should be improved so that it stands out more.
Additionally, your second screenshot exactly shows that there is info missing, because there is no mention that you should actually RUN the script. The snippet just creates it.

**Comment by ranbel** [comment]
Sorry the second screenshot did not capture the entire instructions. Step b covers how to create a systemd service to load the script. So it should run when you reboot the machine.

**Comment by etec-masterofsynapse** [comment]
> Sorry the second screenshot did not capture the entire instructions. Step b covers how to create a systemd service to load the script. So it should run when you reboot the machine.

I just went through these steps for a deployment and it isn't run, here is why:

In the bash script, there are instructions to create a rules.v4 file, containing the persistent mangle rules the WARP agent needs.
But the systemd file only instructs iptables to restore the rules from the rules.v4 file.
So, the missing step here is to run the apply_iptables_rules.sh script so the rules.v4 file actually gets written, so that systemd can restore them on boot.

**Comment by ranbel** [comment]
Ok thanks for the explanation! I've opened a PR and have requested a review from the folks who originally provided these commands. Do the updates make sense to you?

**Comment by etec-masterofsynapse** [comment]
> Ok thanks for the explanation! I've opened a PR and have requested a review from the folks who originally provided these commands. Do the updates make sense to you?

Yes, but additional input:
I think, since the user isn't in the respective directory, we shouldn't call `sudo apply_iptables_rules.sh`, `sudo /usr/local/bin/apply_iptables_rules.sh` makes more sense to me.
Additionally, please check if its possible to not copy the $ from steps a and c, since the CLI can't handle them.
In b they are excluded from the copy.

**Comment by etec-masterofsynapse** [comment]
@ranbel Sorry to necro this issue, but during a recent deployment, I noticed that the codeblocks of steps 5.2a and c dont work right.
The copy button in both cases only copies very few of the actual text, and selecting everything via mouse is also not possible.

Here are a few screenshots to explain what I mean:

![image](https://github.com/cloudflare/cloudflare-docs/assets/59238423/21b70028-a085-4929-ac70-2419747e1f7e)
![image](https://github.com/cloudflare/cloudflare-docs/assets/59238423/322d6a5a-0f04-4d06-83e9-2f59a1718e53)

![image](https://github.com/cloudflare/cloudflare-docs/assets/59238423/58ea80ca-edda-4246-867c-10db4c98ebde)
![image](https://github.com/cloudflare/cloudflare-docs/assets/59238423/952da7b4-c6d5-4998-b07f-f060aa0c0180)
