### ISSUE TITLE
C3 CLi to EXISTING project (svelte)

### ISSUE THREAD

**Issue by marksteven** [cloudflare/cloudflare-docs#13539]
### Proposed changes

documentation on how to add C3-CLi-wrangler to existing project (sveltekit) 

### Subject Matter

How to add Cloudflare C3 to exisitng project

### Content Location

Plenty of documentation on building new project from C3 but nothing I can find to add to existing project other than using Git when I would rather use the direct npm run deploy commands

### Additional information

Thankyou

**Comment by kodster28** [comment]
Closing in favor of #12897, which is on the same topic.
