### ISSUE TITLE
Verification error

### ISSUE THREAD

**Issue by alex0314gfd** [cloudflare/cloudflare-docs#13594]
### Example URL(s)

https://pcpartpicker.com/

### Actual Behavior

In all the web site that works whit clodflare for privacity, i have an error on the robot verification, never works and y cant acces to te website i want to.
I dont know if its a problem whit my antivirus or the web navegator.

![WhatsApp Image 2024-03-24 at 10 19 18 PM](https://github.com/cloudflare/cloudflare-docs/assets/164836636/a4809dbe-21a2-4baf-b0b6-26cb0788bbc5)
![WhatsApp Image 2024-03-24 at 10 19 07 PM](https://github.com/cloudflare/cloudflare-docs/assets/164836636/c1cb6469-151d-401b-8207-196d0d3a34ca)
![WhatsApp Image 2024-03-24 at 10 17 16 PM](https://github.com/cloudflare/cloudflare-docs/assets/164836636/7f843481-b639-44f0-aede-81b0906b4295)

### Expected Behavior

Have acces to the website i want to

**Comment by kodster28** [comment]
Howdy @alex0314gfd, unfortunately that's not something we (as a docs team) or Cloudflare more generally can help with.

Your best bet would be to learn more about [browser support](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#browser-support) for our challenges or drop a thread in the [Cloudflare community](https://community.cloudflare.com).
