### ISSUE TITLE
Simplify the API to set cipher suites

### ISSUE THREAD

**Issue by wUEZRs** [cloudflare/cloudflare-docs#13615]
### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/reference/cipher-suites/recommendations/

### What changes are you suggesting?

One should be able to just set the value Modern (or the other two options)

Additionally this should also just be a button in the Portal GUI

**Comment by kodster28** [comment]
Howdy @wUEZRs, definitely able to pass along that feedback to the UI team... but closing as we can't do anything more to address in the current repo.
