### ISSUE TITLE
Document request size limits for Workers

### ISSUE THREAD

**Issue by danielcompton** [cloudflare/cloudflare-docs#1361]
### Expected Behavior

https://developers.cloudflare.com/workers/platform/limits includes documentation about the maximum size of an HTTP request to Workers (e.g. 30MB, 500MB, unlimited).

### Actual Behavior

There is no documentation explaining what the maximum size for a request can be.

### Section that requires update

https://developers.cloudflare.com/workers/platform/limits#worker-limits

### Additional information

Google App Engine [documents](https://cloud.google.com/appengine/docs/standard/php/how-requests-are-handled#quotas_and_limits) the max request and response size.

**Comment by Mooshua** [comment]
Trial-and-error on my own worker indicates that, for a paid account, the limit is above 100 MB and below 200 MB. I don't have the hard numbers and don't know where to find them, but I'll have more time to bounce files around later.

Good luck with this.

**Comment by Mooshua** [comment]
~~Alright, both free and paid workers throw 413's (Request entity too large) above 100 MB, with an error margin of 1 MB. I'll make a pr declaring 100 MB as the maximum body size in the limits chart :^)~~

Request size is limited by your cloudflare plan (100MB for Free/Pro, 200MB for Business, 500MB+ for enterprise.

**Comment by kristianfreeman** [comment]
> ~Alright, both free and paid workers throw 413's (Request entity too large) above 100 MB, with an error margin of 1 MB. I'll make a pr declaring 100 MB as the maximum body size in the limits chart :^)~
> 
> Request size is limited by your cloudflare plan (100MB for Free/Pro, 200MB for Business, 500MB+ for enterprise.

where did you get this info from?

**Comment by Mooshua** [comment]
Information from here https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN

Reasoning is: If Pages runs after entry to the CDN, and tested upload limits match the CDN's, then the cloudflare CDN should set the upload limit. I also noticed the response for POSTs that were too big (413) responded 3-10x quicker than a 200 response which reaches the worker, indicating that Cloudflare's _gateway_ and not the workers server rejected this request. Unsure of internal limits the workers server may impose, but this should be a good start.

**Comment by kristianfreeman** [comment]
> Information from here https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN
> 
> Reasoning is: If Pages runs after entry to the CDN, and tested upload limits match the CDN's, then the cloudflare CDN should set the upload limit. I also noticed the response for POSTs that were too big (413) responded 3-10x quicker than a 200 response which reaches the worker, indicating that Cloudflare's _gateway_ and not the workers server rejected this request. Unsure of internal limits the workers server may impose, but this should be a good start.

sounds good! remember to rebase :) https://github.com/cloudflare/cloudflare-docs/pull/1372#issuecomment-862537763
