### ISSUE TITLE
The "File" row in the supported languages table shows some (possibly unintentional) HTML tags

### ISSUE THREAD

**Issue by Trip7274** [cloudflare/cloudflare-docs#13614]
### Example URL(s)

https://developers.cloudflare.com/pages/configuration/language-support-and-tools/#supported-languages-and-tools

### Actual Behavior

In both the V2 and V1 view, the Node.js and Python "File" rows currently contain:
`.nvmrc</code>, <code>.node-version`
And:
`.python-version</code>, <code>runtime.txt`

### Expected Behavior

I'd expect the rows to contain:
`.nvmrc`, `.node-version`
And:
`.python-version`, `runtime.txt`

### Additional information

The HTML \<code\> tags aren't escaped properly, and I've found from my (limited) local testing that wrapping them all in a \<p\> tag would fix it (but I'm sure it's not quite that simple to actually fix)
I apologize if this was intentional, as I dont have too much experience with node or JS, but I doubt their file extensions would include \</code\> and \<code\>, so I thought to make this issue just in case :P

**Comment by pedrosousa** [comment]
Thank you for reporting, @iGamerTrip!
