### ISSUE TITLE
reporting phishing attemp

### ISSUE THREAD

**Issue by mattknowles** [cloudflare/cloudflare-docs#13636]
### Example URL(s)

https://abuse.cloudflare.com/?_gl=1*1niqcpq*_ga*NDc1MjM0MjY1LjE3MTE1MTk3MDM.*_ga_SQCRB0TXZW*MTcxMTUxOTcwMy4xLjEuMTcxMTUyMDcwNy4wLjAuMA..

### Actual Behavior

Trying to report a phishing attempt. Both the email address it was sent from and the link for the phishing attempt have domains that are using DNS servers that point to cloudflare servers. But the abuse form doesn't accept them saying cloudflare doesn't serve those domains.
![Screenshot 2024-03-26 at 11 33 22 PM](https://github.com/cloudflare/cloudflare-docs/assets/6899958/1c6e451c-9561-41e0-bc81-9c93b0916063)
![Screenshot 2024-03-26 at 11 32 47 PM](https://github.com/cloudflare/cloudflare-docs/assets/6899958/2d36b37b-5407-4427-9e67-ef0005e21aad)

The abuse form also says it supports upto 5000 characters, but it wouldn't process. Kept getting an error saying it was over 2000 even though it wasn't close to that.

### Expected Behavior

The abuse form should have a way to attach files, and not rule out submissions when the DNS does point to cloudflare

**Comment by kodster28** [comment]
Howdy @mattknowles, forwarding this along internally... but closing out the issue as this is a documentation repo and our team doesn't have any influence over `abuse.cloudflare.com`.
