### ISSUE TITLE
workers and pages : alert : Something went wrong while fetching the account analytics data. Please try again later.

### ISSUE THREAD

**Issue by wsry888** [cloudflare/cloudflare-docs#13635]
### Example URL(s)

https://dash.cloudflare.com/accountid/workers-and-pages
alert ：Something went wrong while fetching the account analytics data. Please try again later.
![image](https://github.com/cloudflare/cloudflare-docs/assets/21898282/c7211e9c-6115-469f-91c9-3631c09210a8)

### Actual Behavior

Something went wrong while fetching the account analytics data. Please try again later.

### Expected Behavior

account analytics data issue

**Comment by pedrosousa** [comment]
Hi @wsry888 
These errors were due to [an incident that occurred yesterday](https://www.cloudflarestatus.com/incidents/b31dxdz60366). Service has been restored, but Cloudflare is still monitoring the services. You can track the progress on the incident page.
