### ISSUE TITLE
Remix build_output_directory incorrect

### ISSUE THREAD

**Issue by jasperdunn** [cloudflare/cloudflare-docs#13637]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/

### What changes are you suggesting?

`content/pages/_partials/_build-configuration.md`

The `build_output_directory` for Remix should be set to `build` instead of `public`.

**Comment by kodster28** [comment]
Believe this was solved by #13829

**Comment by IgorMinar** [comment]
yes, this has been fixed already. Thank you.
