### ISSUE TITLE
EmailMessage object does not actually have a reply function

### ISSUE THREAD

**Issue by britt** [cloudflare/cloudflare-docs#13642]
### Existing documentation URL(s)

- https://developers.cloudflare.com/email-routing/email-workers/runtime-api/#emailmessage-definition

### What changes are you suggesting?

This page suggests that the EmailMessage object has a reply function however that does not seem to be the case as of @cloudflare/workers-types version 4.20240320.1. It might just be an omission in the types file.

**Comment by KianNH** [comment]
Hey there, thanks for raising this.

It looks like it's just an issue with the `reply` method missing from the types, there's an open issue tracking that on the workerd repo where the types live: https://github.com/cloudflare/workerd/issues/2283

Thanks!
