### ISSUE TITLE
missing CSS

### ISSUE THREAD

**Issue by dougba** [cloudflare/cloudflare-docs#13659]
### Example URL(s)

www.easygcloud.com

### Actual Behavior

When loading the website on my mobile phone, the CSS is missing. This appears to be related to CAPTCHA

### Expected Behavior

I expect the site to load with images, but it does not. The workaround is to run a search on the site itself.

### Additional information

The site is hosted as a Cloudflare Page

**Comment by kodster28** [comment]
Howdy @dougba, unfortunately there's nothing we (as Cloudflare) or we (as a docs team) can do about that. Sounds like a misconfiguration of their settings or problems with their build pipelines?

Your best bet would be to reach out to the site owner and let them know that you're experiencing problems with their site.
