### ISSUE TITLE
Cloudflare Images API use batch_token results in authentication errors

### ISSUE THREAD

**Issue by twodft** [cloudflare/cloudflare-docs#13662]
### Existing documentation URL(s)

https://developers.cloudflare.com/images/upload-images/images-batch/

### What changes are you suggesting?

The [documentation](https://developers.cloudflare.com/images/upload-images/images-batch/) suggests obtaining a `BATCH_TOKEN` via the images/v1/batch_token endpoint for various API requests.

> After getting your token, you can use it to make requests for:

- [Uploading an image](https://developers.cloudflare.com/api/operations/cloudflare-images-upload-an-image-via-url) - `POST /images/v1`
- [Retrieving image details](https://developers.cloudflare.com/api/operations/cloudflare-images-image-details) - `GET /images/v1/{identifier}`
- [Updating an image](https://developers.cloudflare.com/api/operations/cloudflare-images-update-image) - `PATCH /images/v1/{identifier}`
- [Listing images V2](https://developers.cloudflare.com/api/operations/cloudflare-images-list-images-v2) - `GET /images/v2`
- [Creating a direct upload URL V2](https://developers.cloudflare.com/api/operations/cloudflare-images-create-authenticated-direct-upload-url-v-2) - `POST /images/v2/direct_upload`

However, in my testing, using the suggested `BATCH_TOKEN` for these API endpoints results in authentication errors, specifically:

```json
{
  "success": false,
  "errors": [
    {
      "code": 10000,
      "message": "Authentication error"
    }
  ]
}
```

In contrast, when using a CLOUDFLARE_API_TOKEN, the authentication process succeeds, and I receive a successful response.

Actually, those API endpoints works while use `BATCH_TOKEN` for auth
- For listing images V2: https://batch.imagedelivery.net/images/v2
- For uploading images V1: https://batch.imagedelivery.net/images/v1

### Additional information

I have also submit a post in the community, at https://community.cloudflare.com/t/cloudflare-images-batch-api-not-work-for-doc-api-endpoint/634841

**Comment by megaconfidence** [comment]
Hi @twodft, thanks for raising this issue with our docs. I just checked and I can confirm that [Updating an image](https://developers.cloudflare.com/api/operations/cloudflare-images-update-image) - `PATCH /images/v1/{identifier}` doesn't work with the batch api. All other operations worked except updating an image

I'll sync internally with the team to get this sorted. Thanks

**Comment by megaconfidence** [comment]
I had a chat internally and can confirm that this was already addressed here
https://github.com/cloudflare/cloudflare-docs/commit/91abdd983e7189b0aa40ff95304700067cf8f107

Closing this issue for now
