### ISSUE TITLE
blocked on vyvymanga supported by cloudfare

### ISSUE THREAD

**Issue by shadeshad** [cloudflare/cloudflare-docs#13695]
### Example URL(s)

https://vyvymanga.net/

### Actual Behavior

i was reading yaoi on vyvymanga and closed my laptop then reopened and i was blocked 
please unblock me

### Expected Behavior

unblock me on vyvymanga . please

**Comment by kodster28** [comment]
Howdy @shadeshad, that's at the discretion of the site owner. Your best course of action would be to reach out to them and provide details about how you were blocked (the page, Cloudflare Ray ID, etc.).

We (as a docs team) and then more broadly we (as Cloudflare) can't override the settings on a domain to prevent someone from being blocked.
