### ISSUE TITLE
S3 IP Limit Policy Example Code Is Wrong

### ISSUE THREAD

**Issue by origami-z** [cloudflare/cloudflare-docs#13697]
### Existing documentation URL(s)

https://developers.cloudflare.com/support/third-party-software/others/configuring-an-amazon-web-services-static-site-to-use-cloudflare/#configure-bucket-policies-to-allow-cloudflare-ip-addresses

### What changes are you suggesting?

The current example code `curl -I -L example.com` is completely irrelevant to the topic of allowing IP address for bitbucket policy, should be something like below in AWS doc

https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html?icmpid=docs_amazons3_console#example-bucket-policies-IP

**Comment by kodster28** [comment]
Howdy @origami-z, apologies for the error here (+ thanks for raising).

This was just addressed in #14211.
