### ISSUE TITLE
Pages Functions "Local development" section recommends deprecated proxy command

### ISSUE THREAD

**Issue by SyntaxColoring** [cloudflare/cloudflare-docs#13698]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/functions/local-development/

### What changes are you suggesting?

The page currently says:

> If you are using a framework, you can pass through the framework-provided dev command (such as, `npm run dev`) to run development. This enables you to benefit from the framework hot-reloading and any special build process around it. To run a framework-provided dev command:
>
> ```
> npx wrangler pages dev -- <COMMAND>
> ```

This `-- <COMMAND>` thing was apparently deprecated in https://github.com/cloudflare/workers-sdk/pull/5317.

According to https://github.com/cloudflare/workers-sdk/issues/5315#issuecomment-2009763632, there's no direct replacement, and the best we can do for now is to use `wrangler pages dev <DIRECTORY-OF-ASSETS>`, which is already described elsewhere on the page.

So unless you all have found a better way to do this since https://github.com/cloudflare/workers-sdk/issues/5315#issuecomment-2009763632, or the `-- <COMMAND>` form will be reinstated, I guess this section should just be removed?

**Comment by GregBrimble** [comment]
Fixed by #13540
