### ISSUE TITLE
Can't install Cloudflare_WARP_Release-x64

### ISSUE THREAD

**Issue by JohnJSadie** [cloudflare/cloudflare-docs#13705]
### Example URL(s)

![Cloudflare_WARP_Release-x64](https://github.com/cloudflare/cloudflare-docs/assets/165573477/5bae96b8-148f-463d-9f5d-e64229e46c85)

### Actual Behavior

Get the above error when clicking on the install file (Cloudflare_WARP_Release-x64.msi)

### Expected Behavior

It should start the installation procedure.

**Comment by ranbel** [comment]
Hi @JohnJSadie, have you tried downloading the latest WARP release? https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/

If that doesn't work, please reach out to community.cloudflare.com or support.cloudflare.com for assistance. (I'm closing this issue as we only take care of developers.cloudflare.com documentation in this repo.)
