### ISSUE TITLE
Domain transfer payment

### ISSUE THREAD

**Issue by sdobke** [cloudflare/cloudflare-docs#13717]
### Existing documentation URL(s)

No documentation

### What changes are you suggesting?

I need to know when the domain transfer process is stopped at the payment when payment method is set up
![payment](https://github.com/cloudflare/cloudflare-docs/assets/29412756/9dc36c71-7ead-4c6d-8cd5-135cf0116be9)

**Comment by kodster28** [comment]
Howdy @sdobke, it sounds like you're at [Step 8](https://developers.cloudflare.com/registrar/get-started/transfer-domain-to-cloudflare/#8-approve-the-transfer) of the transfer process, where the payment itself isn't the blocker... it's that you need to approve the transfer at your registrar.

That being said... this isn't a support channel, so I'd recommend you open a ticket with [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) for more troubleshooting help.
