### ISSUE TITLE
Keys differences between Core Web Vitals data from Web Analytics and Browser Insights 

### ISSUE THREAD

**Issue by pedddro** [cloudflare/cloudflare-docs#1373]
I'm writing an article on how to set up Cloudflare Web Analytics to get instant Core Web Vitals data. Currently, it's clear that both Core Web Vitals data from Web Analytics and Browser Insights are instant, but using them shows another result on my end. Web Analytics seems to be way more accurate and shows live user data(you can filter recent users on the graph and it will show their CWV data), while Browser Insights doesn't show the same recent data as Web Analytics. Is it be due to the Cloudflare Browser Insights sampling rate? 

What is the key difference between both, from the Core Web Vitals data perspective? I know one of the differences is that if you’re not proxying sites through Cloudflare you can just use Web Analytics to get CWV data.

**Comment by KimJ15** [comment]
👋 @pedddro Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! Please reach out to community.cloudflare.com for assistance!
