### ISSUE TITLE
Cloudflare WARP 1.1.1.1 doesn't start up at all

### ISSUE THREAD

**Issue by Choshako** [cloudflare/cloudflare-docs#13744]
### Example URL(s)

https://community.cloudflare.com/t/cloudflare-warp-doesnt-launch/415915

### Actual Behavior

As the title says, nothing happens when I click the icon. I see the loading circle by my mouse for a second, then it's gone, and nothing happens. The app does not work.

### Expected Behavior

I'd like the app to work, that'd be cool.

**Comment by kodster28** [comment]
Howdy @Choshako, I'll pass this along internally... but can't do anything on product functionality as this is a docs repo (and a docs team).
