### ISSUE TITLE
Chromebook compatibility OS link is broken

### ISSUE THREAD

**Issue by ewong-cloudflare** [cloudflare/cloudflare-docs#13823]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/

### What changes are you suggesting?

Chromebooks are supported by our Android app. All Chromebooks made after 2019 should fully support our Android app. If you have a Chromebook made before 2019, refer to this list to verify that your device is supported.

^ To edit the List linked

**Comment by pedrosousa** [comment]
Thank you for letting us know, @ewong-cloudflare! The updated URL should be live in a few minutes.
