### ISSUE TITLE
[Pages] Update Remix deployment guide to reflect Remix Vite setup

### ISSUE THREAD

**Issue by AdiRishi** [cloudflare/cloudflare-docs#13820]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/

### What changes are you suggesting?

- Remix vite is the new default setup since Remix 2.8.0
- The `c3` (create-cloudflare) CLI also uses this template now since the default Remix Cloudflare template (`remix-run/remix/templates/cloudflare`) now uses Vite
- Due to the above changes, the documentation around `Create and add a binding to your Remix application` along with `Deploy via the Cloudflare dashboard` are outdated. There are other small inconsistencies in the docs too.

### Additional information

- **I would like to make a PR to fix this.**
- In the changes I will update all sections to reflect the latest guides around how to deploy Remix applications on Cloudflare
- If it's ok with the Cloudflare team, I would also like to add information around Typescript and how to ensure accessing env variables like `context.env.KV` (if you had KV setup) have the correct typing

**Comment by dario-piotrowicz** [comment]
Hi @AdiRishi 🙂👋 

Thanks a lot for the issue, yeah, updating the guide must has slipped our minds, thanks a lot for pointing out that the docs is outdated

And thanks a lot for offering to open a PR 🙏

Please do go right ahead 🙂, we're thinking of updating the various framework guides soon-ish, but any information you'd be adding would most likely just be shuffled around at most so none of your hard work would be lost 😄 (but I figured I should mention the above anyways)

**Comment by AdiRishi** [comment]
@dario-piotrowicz thank you 🙏 
I'll get started with the PR.
