### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by kathayl** [cloudflare/cloudflare-docs#13860]
### Example URL(s)

[ the Developer Platform in this module.](http://localhost:5173/learning-paths/workers/concepts/developer-platform/)

### Actual Behavior

Link for "learn more about the Developer Platform in this module." doesn't work

### Expected Behavior

should open right page

**Comment by kodster28** [comment]
referring to https://developers.cloudflare.com/learning-paths/workers/concepts/cloudflare-intro/
