### ISSUE TITLE
[Pages] Document Advanced Folder Mode

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/cloudflare-docs#13871]
### Existing documentation URL(s)

- [Advanced Mode - Pages](https://developers.cloudflare.com/pages/functions/advanced-mode/)

### What changes are you suggesting?

Document support for the `_worker.js/` directory, which does support TypeScript/Bundling.

Example mentions
> You would need to compile your TS into JS and output it as a `_worker.js` file. We do not read `_worker.ts`

Which, while true for `_worker.js`, can be circumvented with `_worker.js/index.ts`.

**Comment by KimJ15** [comment]
Page has been updated: https://developers.cloudflare.com/pages/functions/advanced-mode/

**Comment by helloimalastair** [comment]
I'm not sure this should be closed? While it no longer mentions a `_worker.ts` file, it still doesn't mention that you can use `_worker.js` as a directory.
