### ISSUE TITLE
Acess - Zero Trust não funciona, para criar politica de acesso a um site

### ISSUE THREAD

**Issue by marcielcorado** [cloudflare/cloudflare-docs#13887]
### Proposed changes

Acess - Zero Trust não funciona, para criar politica de acesso a um site

### Subject Matter

Acess - Zero Trust não funciona, para criar politica de acesso a um site

### Content Location

Acess - Zero Trust não funciona, para criar politica de acesso a um site

**Comment by kodster28** [comment]
Howdy @marcielcorado, your best bet would be reaching out to the [Cloudflare Community](https://community.cloudflare.com/) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

This is a docs repo, so we can't provide any troubleshooting guidance.
