### ISSUE TITLE
Firewall 

### ISSUE THREAD

**Issue by Jorgeeduardoc902** [cloudflare/cloudflare-docs#13893]
### Existing documentation URL(s)

[73, 6809, 291, 11280, 511, 21026, 10591, 916]

### What changes are you suggesting?

Auto certified 

### Additional information

1. 
[Performance_Data_Report_FY24-25_FY22-23.xlsx](https://github.com/cloudflare/cloudflare-docs/files/14894994/Performance_Data_Report_FY24-25_FY22-23.xlsx)

**Comment by kodster28** [comment]
Howdy @Jorgeeduardoc902, not entirely clear what you're asking for here. If you have it, please open an issue with more detail.
