### ISSUE TITLE
[QUEUES] Queues Batch timeout inconsistencies

### ISSUE THREAD

**Issue by demosjarco** [cloudflare/cloudflare-docs#13894]
### Existing documentation URL(s)

- https://developers.cloudflare.com/queues/platform/limits/#limits
- https://developers.cloudflare.com/queues/tutorials/web-crawler-with-browser-rendering/#3-configure-your-worker

### What changes are you suggesting?

Is the correct max value 30 or 60?

### Additional information

- Miniflare validator of `wrangler.toml` says `Number must be less than or equal to 30`3
- [Limits doc](https://developers.cloudflare.com/queues/platform/limits/#limits) page says max `30`
- [Browser rendering example](https://developers.cloudflare.com/queues/tutorials/web-crawler-with-browser-rendering/#3-configure-your-worker) shows `60`
- dashboard says max `60`
![image](https://github.com/cloudflare/cloudflare-docs/assets/1209494/ee82d145-f9de-40c0-b5e9-8a51b3d06cf4)

**Comment by Maddy-Cloudflare** [comment]
Addressed here https://github.com/cloudflare/cloudflare-docs/pull/14049
