### ISSUE TITLE
Please provide a more targetted AWS policy for Sippy

### ISSUE THREAD

**Issue by viraptor** [cloudflare/cloudflare-docs#13904]
### Existing documentation URL(s)

https://developers.cloudflare.com/r2/data-migration/sippy/#amazon-s3

### What changes are you suggesting?

The current example policy includes:
```
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
```
But we can assume Sippy doesn't actually use `GetObjectTorrent` or `GetObjectLegalHold`. It would be great to have a policy which only lists the actions which are actually used.

**Comment by harshil1712** [comment]
Thank you for opening the issue. The docs are updated with more targeted policy.
