### ISSUE TITLE
Я ЧЕЛОВЕК БЛЯТЬ, ИДИТЕ НАХУЙ

### ISSUE THREAD

**Issue by ubuK1257** [cloudflare/cloudflare-docs#13944]
### Example URL(s)

![Uploading Снимок экрана (419).png…]()

### Actual Behavior

ДОРОГИЕ РАЗРАБОТЧИКИ, данный виджет уже который год мешает мне, как порядочному пользователю, пользоваться многими другими инструментами, ведь ваш виджет НЕ СЧИТАЕЬ МЕНЯ ДОСТАТОЧНО ЧЕЛОВЕЧНЫМ

### Expected Behavior

пожалуйста, исправьте это.....пожалуйста

**Comment by kodster28** [comment]
Howdy @ubuK1257, unfortunately there's nothing we (as a docs team) can do about that.

Your best bet would probably be reaching out in the [Cloudflare Community](https://community.cloudflare.com).

**Comment by ubuK1257** [comment]
я даже не могу им на сайте написать в поддержку, все из-за той же проверки...не знаю, плакать или смеяться
