### ISSUE TITLE
Update suggestion on RPC documentation

### ISSUE THREAD

**Issue by hoshikawa** [cloudflare/cloudflare-docs#13969]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/rpc/#promise-pipelining

### What changes are you suggesting?

https://github.com/cloudflare/cloudflare-docs/blob/c070a71340de9ccaea5fa50297e79f7d0893efe6/content/workers/runtime-apis/rpc/_index.md?plain=1#L203-L207

Would it make more sense if the first line had no `await`, since this code shows the example of "promise pipelining"?

**Comment by KianNH** [comment]
Thanks for pointing this out! I've raised a PR that'll fix the example.
