### ISSUE TITLE
Waiting Room Rules

### ISSUE THREAD

**Issue by Mrjprez** [cloudflare/cloudflare-docs#13976]
### Proposed changes

https://developers.cloudflare.com/waiting-room/additional-options/waiting-room-rules/

### Subject Matter

Waiting Room Rules

### Content Location

https://developers.cloudflare.com/waiting-room/additional-options/waiting-room-rules/

### Additional information

It looks like the information is missing from this page as it only links out to the bypass rules. 

I would like to know if users will lose their place in line if they close our page and return when a waiting room is active.

**Comment by angelampcosta** [comment]
@Mrjprez you can refer to our FAQs section for information on [​​what happens if a user refreshes their tab when in a waiting room](https://developers.cloudflare.com/waiting-room/troubleshooting/#what-happens-if-a-user-refreshes-their-tab-when-in-a-waiting-room)
