### ISSUE TITLE
525

### ISSUE THREAD

**Issue by icrs-max** [cloudflare/cloudflare-docs#13970]
### Example URL(s)

https://insuranceclaimrecoverysupport.com/

### Actual Behavior

SSL HANDSHAKE FAILED HOST ERROR 525

### Expected Behavior

SSL HANDSHAKE FAILED HOST ERROR 525

### Additional information

How do I get site back up or is this a maintenance issue?

**Comment by kodster28** [comment]
Howdy @icrs-max, that's something the site owner would need to fix (unclear of your role by your comment).

The site owner should look at our [525 troubleshooting guide](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-525-ssl-handshake-failed) and -- if that doesn't work -- either reach out in the [Cloudflare Community](https://community.cloudflare.com) or file a ticket with [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
