### ISSUE TITLE
include list type available on gateway policy in dev docs

### ISSUE THREAD

**Issue by thestarrypage** [cloudflare/cloudflare-docs#14009]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/policies/gateway/lists/

### What changes are you suggesting?

list out the list type available

URLs
Hostname
serial numbers
User email
Ip addresses
device Ids

### Additional information

na

**Comment by maxvp** [comment]
Addressed in PR #14188. Thanks for reporting!
