### ISSUE TITLE
IPv6 formatting for Cloudflare dashboard DNS records, Learning page, and docs

### ISSUE THREAD

**Issue by MaximilianKohler** [cloudflare/cloudflare-docs#14001]
### Proposed changes

Add info to:

* https://www.cloudflare.com/learning/dns/dns-records/dns-aaaa-record/
* https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/

Showing the proper format for IPv6 addresses to input into `https://dash.cloudflare.com/xxx/mydomain.com/dns/records`.

This page https://www.cloudflare.com/learning/dns/dns-records/dns-aaaa-record/ is the primary result that comes up in searches, and https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/ is linked to at the top of `https://dash.cloudflare.com/xxx/mydomain.com/dns/records`.

Neither one shows what I'm looking for. Eg: My server provider (Hetzner) shows my IPv6 address as "**xxxx:xxx:xx:xxxx::/64**", and Cloudflare says that's invalid. 

>Valid IPv6 address is required

I searched the web and could only find https://community.cloudflare.com/t/ipv6-not-valid-ip-6-address-wrong/17493, which says to use "xxxx:xxx:xx:xxxx:0000:0000:0000:64". When I went to edit the record Cloudflare accepted "xxxx:xxx:xx:xxxx::64", but I'm trying to set up SPF records, and using that format didn't give me a valid SPF result. The emails being sent show "SOFTFAIL with IP xxxx:xxx:xx:xxxx:0:0:0:1".

### Subject Matter

Proper formatting for IPv6 records in the Cloudflare dash

### Content Location

* https://www.cloudflare.com/learning/dns/dns-records/dns-aaaa-record/
* https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/

**Comment by MaximilianKohler** [comment]
I changed the AAAA record to the one showing up as "SOFTFAIL" -- "xxxx:xxx:xx:xxxx:0:0:0:1", and SPF now passes. So there's apparently some issue with the "xxxx:xxx:xx:xxxx::64" format.

Since none of your docs cover this, I'm not even sure if changing "xxxx:xxx:xx:xxxx:0:0:0:1" to "xxxx:xxx:xx:xxxx:0:0:0:64" is valid or appropriate, or if it means that everything from 1-64 will work.

EDIT: I tried 64 instead of 1, and SPF failed.

**Comment by RebeccaTamachiro** [comment]
Hi @MaximilianKohler I'm sorry, we only take care of [developers.cloudflare.com](http://developers.cloudflare.com/) documentation in this repo. You might want to reach out to [community.cloudflare.com](http://community.cloudflare.com/) or [support.cloudflare.com](http://support.cloudflare.com/) for assistance with your case.

SPF records are covered in https://developers.cloudflare.com/dmarc-management/security-records/ and the specific values to input in them depend on your email service provider. Information on IPv6 notation is available in https://developers.cloudflare.com/dns/manage-dns-records/reference/dns-record-types/#a-and-aaaa

**Comment by MaximilianKohler** [comment]
>I'm sorry, we only take care of [developers.cloudflare.com](http://developers.cloudflare.com/) documentation in this repo

My OP referenced a developers.cloudflare.com page. 

>Information on IPv6 notation is available in https://developers.cloudflare.com/dns/manage-dns-records/reference/dns-record-types/#a-and-aaaa

This is helpful and should be referenced & linked to on https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/.

However, even that page doesn't cover ranges, so it's incomplete/inadequate.
