### ISSUE TITLE
Automatic night mode

### ISSUE THREAD

**Issue by flexchar** [cloudflare/cloudflare-docs#14017]
### Example URL(s)

Site-wide.

### Actual Behavior

Night or day mode relies on the button click, which is fully static.

### Expected Behavior

I would like the button to have the system option so it matches the system setting which automatically turns dark in the evening but is back bright in the morning. 

### Additional information

For use with https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by kodster28** [comment]
Howdy @flexchar, thanks for the suggestion.

We may circle back around on this one, but not going to be prioritizing against other initiatives in the near future.
