### ISSUE TITLE
Cloudflare Pages API permission names do not match what the API returns

### ISSUE THREAD

**Issue by rhodesn** [cloudflare/cloudflare-docs#14013]
### Existing documentation URL(s)

- https://github.com/cloudflare/cloudflare-docs/blob/production/content/fundamentals/_partials/_account-permissions-table.md

The above lists the following under the API tab
```
Cloudflare Pages Read
Cloudflare Pages $1
```

Which does not match the names returned by the API result:
```
$ curl -fSs https://api.cloudflare.com/client/v4/user/tokens/permission_groups $headers | jq '.result[] | select(.description | test("Cloudflare Pages"))'
{
  "id": "e247aedd66bd41cc9193af0213416666",
  "name": "Pages Read",
  "description": "Grants read access to Cloudflare Pages",
  "scopes": [
    "com.cloudflare.api.account"
  ]
}
{
  "id": "8d28297797f24fb8a0c332fe0866ec89",
  "name": "Pages Write",
  "description": "Grants write access to Cloudflare Pages",
  "scopes": [
    "com.cloudflare.api.account"
  ]
}
$
```

### What changes are you suggesting?

The "Cloudflare" prefix needs removing from the names under the API tab.

### Additional information

Using the docs name results in Terraform complaining about an unknown map key in `cloudflare_api_token_permission_groups`.

**Comment by rhodesn** [comment]
Unfortunately the Dash returns "Cloudflare Pages xx"
<img width="889" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/3129408/ab8034dd-4e72-4ecf-b1d4-3644dde257f6">

**Comment by kodster28** [comment]
Should be updated in ~5 min, thanks for flagging @spiraltaap
