### ISSUE TITLE
It is not clear which credentials should be used for TURN requests

### ISSUE THREAD

**Issue by justin0mcateer** [cloudflare/cloudflare-docs#14011]
### Existing documentation URL(s)

- https://developers.cloudflare.com/calls/turn/

### What changes are you suggesting?

Should the Calls App Id be used? Does a general API token need to be created? If so, what are the minimum permissions the API token must be granted? Is there any special encoding for the API token values when using as TURN user name and password, etc?

### Additional information

I've tried creating an API token with the Calls: Read permissions and using that with turnutils_client, all combinations return 400 errors from the TURN service. I also tried using the App Id for the TURN username. No luck.

**Comment by justin0mcateer** [comment]
To clarify, I can provide the same turnutils_client command (with different credentials, server address and port numbers) to access a different well known TURN service provider and the command works without issue.

**Comment by renandincer** [comment]
TURN is rolling out between April 4 and 24, 2024 in batches. If not clear to you, it is likely because it's not available on your dashboard yet.

**Comment by renandincer** [comment]
(please reach out to me at renan@cloudflare if you'd like to try sooner or your account team if you're a enterprise customer)
