### ISSUE TITLE
Clarify the Virtual Network selector in firewall policies

### ISSUE THREAD

**Issue by lucasan1** [cloudflare/cloudflare-docs#14020]
### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/policies/gateway/network-policies/#virtual-network

### What changes are you suggesting?

The documentation for the Virtual Network ([here](https://developers.cloudflare.com/cloudflare-one/policies/gateway/network-policies/#virtual-network)) selector says:
> The [Tunnel Virtual Network](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/cloudflared/tunnel-virtual-networks/) that the device is connected to via the WARP client.

It's not fully clear if this means that the destination of the traffic is within the virtual network (basically equal to "destination IP in <virtual network>") or if it matches all traffic when an user is simply connected to that virtual network via WARP. Doing some tests i expected the former case to be the correct behaviour for this selector, but apparently is the latter; hence why i think it will be helpful to clarify how this selector works in the docs.

**Comment by ghost** [comment]
Thx

**Comment by ghost** [comment]
Thx
