### ISSUE TITLE
Limit mismatch between workers document and d1 document

### ISSUE THREAD

**Issue by b0unt9** [cloudflare/cloudflare-docs#14067]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/storage-options/#performance-and-consistency
https://developers.cloudflare.com/d1/platform/limits/

### What changes are you suggesting?

The new limits of D1 and the data in the tables in the `Performance and consistency` section of Workers' `Choose a data or storage product for your use-case` page do not match

### Additional information

I fixed the problem after forking

**Comment by Maddy-Cloudflare** [comment]
I'm closing this since it looks like you fixed it. Feel free to raise another GitHub issue if you encounter anything. Thanks.

**Comment by rozenmd** [comment]
@Maddy-Cloudflare fyi issues close themselves once a PR gets merged
