### ISSUE TITLE
[D1] Add Sutando ORM & knex-cloudflare-d1 to D1 "Community projects" page

### ISSUE THREAD

**Issue by kiddyuchina** [cloudflare/cloudflare-docs#14088]
### Existing documentation URL(s)

https://developers.cloudflare.com/d1/platform/community-projects/

### What changes are you suggesting?

It is recommended to add Sutando ORM and knex-cloudflare-d1 to the community project list.

Sutando ORM and knex-cloudflare-d1 are both community projects of D1, providing support for Cloudflare Workers and D1.

### Additional information

Sutando is an ORM that supports multiple databases, similar to Active Record.

Repo page: https://github.com/sutandojs/sutando

knex-cloudflare-d1 is the Cloudflare D1 dialect for Knex.js.

Repo page: https://github.com/kiddyuchina/knex-cloudflare-d1

An example repo using D1 with Sutando ORM: https://github.com/sutandojs/sutando-examples/tree/main/typescript/rest-hono-cf-d1

**Comment by Oxyjun** [comment]
Tracking via this PR: https://github.com/cloudflare/cloudflare-docs/pull/17368

**Comment by Oxyjun** [comment]
Closing, as this has been merged.
