### ISSUE TITLE
slowest upload

### ISSUE THREAD

**Issue by rchilders214** [cloudflare/cloudflare-docs#14097]
### Example URL(s)

https://speed.cloudflare.com/

### Actual Behavior

My upload shows dallas to irving on the map, 25 miles, upload 465mbs (only cloudfare), download 625mbs. att overprovisions both sides to 650/640. Latency download 0-4.5ms provider, others 22ms-38ms avg.

I have my tcp optimizer at 720 bandwidth for peaks, 34
![2024-04-17_15-15-28](https://github.com/cloudflare/cloudflare-docs/assets/105776159/15dfa321-6ad5-4194-8bd0-72b61d37f7b8)
![2024-03-14_16-48-51](https://github.com/cloudflare/cloudflare-docs/assets/105776159/428de3a8-fc61-49b6-abee-93d046367eb8)
 for delay. Most features disabled on realtek gaming controller except rss.   Thank You

### Expected Behavior

usually upload/download 10-25mbs difference. fastest tower att, windspeed

**Comment by rchilders214** [comment]
I dont use v6 connection.

**Comment by kodster28** [comment]
Howdy @rchilders214, this is a repo for Cloudflare's docs.

Not much we can do to diagnose / provide support on Cloudflare's speed test. You might be able to get help by posting in the [Cloudflare Community](https://community.cloudflare.com) though.

**Comment by rchilders214** [comment]
Kody,
How about other reports just like it, if it was my settings what should I look at. 

Only 20% of speed tests do this, att and ookla are sequential, verizon used to hit 7500, then followed ooklas footsteps, leaving verizon with extremely high peaks but settling to whats "expected'. 
Linode is the fastest currently. M lab is slower than att and the same test. Ookla is ALWAYS 621/628, hmm.
    On Wednesday, April 17, 2024 at 03:52:26 PM CDT, Kody Jackson ***@***.***> wrote:  
 
 


Howdy @rchilders214, this is a repo for Cloudflare's docs.

Not much we can do to diagnose / provide support on Cloudflare's speed test. You might be able to get help by posting in the Cloudflare Community though.
