### ISSUE TITLE
Request clouflare be removed as dns.

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#14102]
### Existing documentation URL(s)

Please 

### What changes are you suggesting?

I'm not receiving web messages and seems most my web apps aren't receiving notifications. I'd like to request clouflare be removed as dns, and please stop blocking and restricting any of my pages, ip and notifications. I'm so tired of having to spend hours just to receive messages via my Google voice 

### Additional information

Seems like my Google play service isn't allowing web messages to come through.

**Comment by kodster28** [comment]
Howdy @Vonjj24, it sounds like you might benefit from reading [Remove a domain from Cloudflare](https://developers.cloudflare.com/fundamentals/setup/manage-domains/remove-domain/) OR following the reverse of the [1.1.1.1 setup guide](https://developers.cloudflare.com/1.1.1.1/setup/). Can't quite tell which version of Cloudflare you're referring to (website or DNS resolver).

If you're still having issues, I'd direct you to post in the [Cloudflare Community](https://community.cloudflare.com) or reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).

**Comment by ghost** [comment]
I have long since deleted cloud flare account associated with my device,
but I'm yet seeing orange, and I'm familiar with cloud flare big bothering.
I just want to to stop. I'm not receiving incoming messages via Google
voice. Nor are my dating social apps operating. Please give me insight as
to which platform is stagnanting my services. This isn't right. Can you
imagine not being able to communicate with friends and love one's due to a
platform big bothering your device
