### ISSUE TITLE
What counts as a "db write"

### ISSUE THREAD

**Issue by aRustyDev** [cloudflare/cloudflare-docs#14139]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/platform/pricing/#d1

### What changes are you suggesting?

Could you add some clarification to `pricing`, specifically what counts as a "write". 
The way its described currently, it sounds like if I created 10k rows and then deleted them thats either 0 or 10k writes. 

1. is that true? or is that 20k writes?
2. what happens if I delete a row? (write allowance wise)
3. what happens if I update/modify a row?

**Comment by KianNH** [comment]
Whilst I haven't checked your specific scenarios, there is a [`meta` object](https://developers.cloudflare.com/d1/build-with-d1/d1-client-api/#return-object) returned that includes 'rows_read' and 'rows_written'. You can also use the [`wrangler d1 insights`](https://developers.cloudflare.com/d1/observability/metrics-analytics/#query-insights) command to see your top queries and what their duration/rows_read/rows_written are.

You should be able to use those to test the cost of a given query.

**Comment by Oxyjun** [comment]
This has been actioned via https://github.com/cloudflare/cloudflare-docs/pull/16658.

**Comment by KimJ15** [comment]
Closing per https://github.com/cloudflare/cloudflare-docs/pull/16658.
