### ISSUE TITLE
Supported cloudflared versions info is outdated

### ISSUE THREAD

**Issue by CorralPeltzer** [cloudflare/cloudflare-docs#1414]
https://github.com/cloudflare/cloudflare-docs/blob/efc3bab515455044b6d87d2bb113c2f0982df3b0/products/cloudflare-one/src/content/connections/connect-apps/install-and-setup/installation.md#L162

March 2021 has already passed, this should probably be updated

**Comment by abracchi-tw** [comment]
hi there, this is being addressed in the `cloudflared` repo https://github.com/cloudflare/cloudflared
