### ISSUE TITLE
Clarify if rate limits work or don't with next-on-pages (or roadmap)

### ISSUE THREAD

**Issue by cheraff** [cloudflare/cloudflare-docs#14186]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/bindings/rate-limit/

### What changes are you suggesting?

I spent a good few hours trying to get rate limiting to work on deploy with my next-on-pages project (via a worker api route within the project), before going to the discord and finding others with the same issue. 

The rate limiting actually worked locally based on my .toml file (hence my confusion). Apparently  there is no option to enable this in pages & worker project settings, so my understanding is it can't work with next-on-pages yet. Will this be added at any point in a beta mode?

Clarification on a roadmap in the docs for next-on-pages, would be appreciated and save a lot of headache

### Additional information

Messed into discord about it but couldn't get clarification
https://discord.com/channels/595317990191398933/1225429769219211436/1231714034445979718

**Comment by dario-piotrowicz** [comment]
Hi @cheraff 👋 

Thank you very much for the issue 🙂 (and sorry for the headache this caused you 😓)

Rate limit bindings are indeed not supported by Pages applications, and I think you're right that we can make this more clear for users.

Generally we should make it more clear which bindings are available there and which are not.

I've opened https://github.com/cloudflare/cloudflare-docs/pull/14353 to clarify that not all Workers bindings are available in Pages applications, hopefully this helps 🙂 

I've also opened https://github.com/cloudflare/workers-sdk/issues/5742 to improve the validation of `getPlatformProxy` in regards to Pages bindings (which is used by `next-on-pages` under the hood). This should hopefully help avoiding confusion 👍
