### ISSUE TITLE
Fix deobfuscated stack trace availability information

### ISSUE THREAD

**Issue by AndrewJDR** [cloudflare/cloudflare-docs#14194]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/observability/source-maps/#stack-traces

### What changes are you suggesting?

The stack traces section mentions that deobfuscated stack traces entered open beta on April 15th:
> Stack traces support is going to be in open beta on April 15.

However, they still do not appear to work. It would be good to have an updated date, or even just leave it more vague like "Stack traces support is not yet available, but will be entering open beta soon. Please check back to learn when it becomes available."

### Additional information

Additionally, the [announcement blog post](https://blog.cloudflare.com/workers-production-safety/) for this feature mentions:

> And starting on April 15th , the Workers runtime will start using source maps to deobfuscate stack traces. We’ll post a notification in the Cloudflare dashboard and post on our [Cloudflare Developers X account](https://twitter.com/CloudflareDev?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) when source mapped stack traces are available.

There hasn't been any such announcement on the linked twitter account, so this further indicates that the feature isn't yet available in open beta.

**Comment by irvinebroque** [comment]
Soon! Getting close.

**Comment by KimJ15** [comment]
Looks like the page has been updated. https://developers.cloudflare.com/workers/observability/source-maps/#stack-traces
