### ISSUE TITLE
SolidStart guide is missing info on how to access `env`

### ISSUE THREAD

**Issue by transbitch** [cloudflare/cloudflare-docs#14222]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.47.1

### What version of Node are you using?

21.5.0

### What operating system and version are you using?

Doesn't matter

### Describe the Bug

Documentation refers to `createServerData$` to access `env` (which includes D1 bindings, among other things). `createServerData$` has been removed. What do I use to access `env`?

**Comment by transbitch** [comment]
UPDATE: I found it in `apiEvent.nativeEvent.context.cloudflare.env`. The docs should be updated, would have saved me a few hours...

Edit: Also, it should be noted whether this is the "proper" way to access it (e.g. is this stable/an api boundary)? there seems to be little documentation here.

**Comment by dario-piotrowicz** [comment]
Hi @transbitch 🙂 

Thanks a lot for the issue 🙏 

It seems like our SolidStart guide is very outdated... I've opened a PR to update the guide: https://github.com/cloudflare/cloudflare-docs/pull/14221

The PR amends the outdated info and removes the section regarding how to access bindings, as you said, bindings can still be accessed via `nativeEvent.context.cloudflare.env` but I am not sure if that's the "proper" way to access them... or even if there is a "proper" way... (either way this it's unlikely to work in dev mode any time soon 😓)

The PR is tentatively removing the section until we figure this one out.... or maybe it should just inform users to use `nativeEvent` although I am not completely sure if that's always the proper/viable way of doing so (maybe we need to do a quick investigation....), I'll check with the team and keep you updated

**Comment by dario-piotrowicz** [comment]
(PS: I've transferred the issue to the docs repo as that is the proper place for this)

**Comment by CarmenPopoviciu** [comment]
@dario-piotrowicz are we good to close this? seems like original request was addressed by your docs PR?

**Comment by dario-piotrowicz** [comment]
@CarmenPopoviciu I am not sure what PR you're referring to, do you mean issue https://github.com/cloudflare/workers-sdk/issues/5912?
(if that's the case I believe that it's good to have both issues in both repos as those are two (although very related) different issues no?)

**Comment by KimJ15** [comment]
Closing per https://github.com/cloudflare/cloudflare-docs/pull/14221
