### ISSUE TITLE
Warp versions release note on change log

### ISSUE THREAD

**Issue by makotocf** [cloudflare/cloudflare-docs#14247]
### Proposed changes

https://developers.cloudflare.com/changelog/?

Under the product drop down field, can we add new product field - Warp where users can track 
Warp new version's release for Windows, Mac, Linux etc

https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release
https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-windows-1/distribution_groups/release

### Subject Matter

Warp versions release note on change log

### Content Location

https://developers.cloudflare.com/changelog/?
or 
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/

**Comment by crwaters16** [comment]
Hey @makotocf - tagged you in the internal ticket where we're tracking this work!
