### ISSUE TITLE
The feedback page is not fully displayed

### ISSUE THREAD

**Issue by chengkailiu** [cloudflare/cloudflare-docs#14262]
### Example URL(s)

https://developers.cloudflare.com

### Actual Behavior

I'm having trouble clicking. The feedback interface cannot be displayed in the center or in full.

### Expected Behavior

Full display of feedback page

**Comment by kodster28** [comment]
Can you elaborate on what you mean by the "feedback page"?

**Comment by kodster28** [comment]
Closing this out b/c of lack of detail. Feel free to re-open a new issue providing more context.
