### ISSUE TITLE
migrations_dir not documentated for d1_databases

### ISSUE THREAD

**Issue by gerhardcit** [cloudflare/cloudflare-docs#14285]
### Proposed changes

https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases

Add documentation for migrations_dir in [[d1_databases]] section for wrangler.toml

### Subject Matter

migrations_dir

### Content Location

https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases

### Additional information

When using something like drizzle, you can have a different migrations dir.
It works to set it. eg: migrations_dir = "drizzle"
But its not documented.

**Comment by Khorous** [comment]
> ### Proposed changes
> 
> https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
> 
> Add documentation for migrations_dir in [[d1_databases]] section for wrangler.toml
> 
> ### Subject Matter
> 
> migrations_dir
> 
> ### Content Location
> 
> https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
> 
> ### Additional information
> 
> When using something like drizzle, you can have a different migrations dir.
> It works to set it. eg: migrations_dir = "drizzle"
> But its not documented.

**Comment by gshirescf** [comment]
cc: @harshil1712

**Comment by Oxyjun** [comment]
Now tracking here https://github.com/cloudflare/cloudflare-docs/pull/17405

**Comment by Oxyjun** [comment]
Relevant PR merged, closing this issue.
