### ISSUE TITLE
The `Get Started` button in Workers & Pages / ProjectName / Settings / Functions / Service Binding points to `account_id/workers/d1`

### ISSUE THREAD

**Issue by clmnin** [cloudflare/cloudflare-docs#14313]
### Example URL(s)

- https://dash.cloudflare.com/account_id/pages/view/project_name/settings/functions

Replace `account_id` with your account ID and `project_name` with your pages project name

### Actual Behavior

Goes to `account_id/workers/d1`

### Expected Behavior

Should go to the service binding page

**Comment by kodster28** [comment]
Howdy @clmnin, the scope of this change is outside our docs repo.

Forwarding to another, internal team, but closing it out as there's nothing we can update in our docs to fix this.
