### ISSUE TITLE
Access documentation assumes I already know what the team name is

### ISSUE THREAD

**Issue by kornelski** [cloudflare/cloudflare-docs#14318]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/

uses `<your-team-name>` in multiple places, but never explains what the team is, and how to find this value.

> The public key for the signing key pair is located at `https://<your-team-name>.cloudflareaccess.com/cdn-cgi/access/certs`.

The dashboard at `https://one.dash.cloudflare.com/…/access/apps` does not use the "team" term anywhere. It has "application name" and "application URL". I'd expect the URL to be specific to the application, since logins are application-specific.

There's also "My Team" section in the dashboard, but it doesn't say what is the team name.

"Zero trust overview" page doesn't have the team name. There's no team name configuration in Settings -> Account, nor Settings -> Authentication where I'd expect such setting to exist.

Even the FAQ entry: https://developers.cloudflare.com/cloudflare-one/faq/teams-getting-started-faq/#whats-a-team-domain%2fteam-name is not that useful at the first glance, because it repeats `<your-team-name>.cloudflareaccess.com`, without saying what the name is. 

> You can sign up today at [this link](https://dash.cloudflare.com/sign-up/teams). Follow the onboarding steps, choose a 
team name

This link doesn't lead to the team name for users who already have an account.

Link to "App Launcher" shows `mycompany.cloudflareaccess.com`.

Finally there is a sentence " You can view your team name and team domain in Zero Trust under Settings > Custom Pages.", but "Settings > Custom Pages" is not a link. And "Custom Pages" is a *very surprising* location for the team name. A team is not a page. I don't want to set up any pages, I want to setup login to an application. Without this instruction I would have actively avoided looking at "Custom Pages" section, as it looks completely irrelevant to the JWT validation that I'm trying to implement.

### What changes are you suggesting?

It would be ideal if the documentation was personalized (when I'm logged in to the dashboard) and could display actual real team name for my account instead of `<your-team-name>` placeholder.

Second best would be link to the place in the dashboard that shows the team name, linked from every page that uses `<your-team-name>`, so that I don't have to search through other pages in the documentation to find this information.

And it'd be helpful to display the team name in other places in the dashboard, like the Overview section and Applications section (since implementing Access for an application requires knowing the team name).

**Comment by kodster28** [comment]
Howdy @kornelski, to your first point, hear the frustration... but we aren't going to have personalization on the docs in any sort of near future. It'd require a lot of engineering work and likely less benefit than other things on our roadmap.

To the 2nd, displaying more prominently in the dash probably makes sense... but that's outside the scope of this repo, so closing out this issue. You might want to bring it up with the ZT team as a request more generally.

**Comment by ranbel** [comment]
I've passed along your suggestions to the ZT UX team. They are actively looking into reorganizing the dashboard settings. In the meantime, I've added a glossary link to https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/ in #14323.
