### ISSUE TITLE
How do you get to CloudFlare Tunnels / Argo Tunnels settings? No mention in Docs or Dashboard UI

### ISSUE THREAD

**Issue by pirate** [cloudflare/cloudflare-docs#14326]
### Proposed changes

The options to get to my cloudflare Tunnels UI in the dashboard completely dissappeared.

Searching "tunnel" or "tunnels" or "argo tunnel" in the Dashboard yields no results, and there is nothing in the sidebar anymore to get to it.

I tried looking in the docs, and there's no mention in the Docs of how to get to the tunnels dashboard. Our whole company is built on tunnels, did it just get removed overnight? What happened?

https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/

<img width="800" alt="Screenshot 2024-04-30 at 4 14 51 PM" src="https://github.com/cloudflare/cloudflare-docs/assets/511499/30997515-6dcc-41d7-afec-c103f3115a03">

<img width="773" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/511499/176729c2-2062-406f-a018-50682eb6d832">

<img width="394" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/511499/71a3ab68-5461-41ed-bc78-79940b385913">

### Subject Matter

Tunnels

### Content Location

https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/

**Comment by ranbel** [comment]
Hey @pirate, sorry to hear you're having issues. When was the last time this worked? Were you running a legacy tunnel? https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/migrate-legacy-tunnels/

**Comment by pirate** [comment]
All my tunnels are "named tunnels", legacy stopped worked a long time ago for us. There used to be an option in the sidebar next to Argo for Tunnels. I think it may be related to "Zero Trust" or something like that now but I don't see any option for that anywhere in the sidebar either (see screenshots above).

**Comment by ranbel** [comment]
According to https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/migrate-legacy-tunnels/#check-for-legacy-tunnels, the "named tunnels" should appear in https://one.dash.cloudflare.com/ under Networks > Tunnels. Do you see your tunnels there?

**Comment by pirate** [comment]
Ah yes they are there but how am I supposed to get there without opening a support ticket to find that URL? there's nothing in the dashboard/sidebar with that name, and search doesn't have any indication of those terms existing:

<img width="691" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/511499/bb00f28a-fe82-4c75-97f7-f8c94c1862c7">
<img width="713" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/511499/3b600db5-628b-41a2-ae6e-5168c4fb16c0">

It seems like every UI update renames it, buries it a bit more, and makes tunnels harder and harder to find. Is it a loss leader you're trying to discourage people from using?

If I'm following this correctly this is now the 5th rename / UI move!
`Warp` -> `Argo` -> `Argo Tunnels` -> `Zero Trust Tunnels` -> `Cloudflare One Networks Tunnels`

Are users just supposed to guess that it's been moved to yet another new dashboard that's not linked to anywhere from the domain dashboard, buried under a sub-tab with a generic name like "Networks"? There's no searchability/discoverability from any of the previous locations where it was in the UI (or via search), so from a user's perspective it looks like it was just removed outright. If I'm getting this wrong somehow can you help clarify, what is the difference between "Cloudflare One" and "Cloudflare Zero Trust" and ["Zero Trust Networks"](https://one.dash.cloudflare.com/413ad3842c5a82a780b582d8de8dc903/networks/tunnels) and ["Zero Trust Connections"](https://developers.cloudflare.com/cloudflare-one/connections/)? What names are completely deprecated and what names are duplicates that refer to the same concept/products? If they are part of the "Networks" umbrella term why is there no link to them from the sidebar area labeled `Network`?


Sorry for the frustration it's just that Tunnels are such good underlying tech, I'm baffled at why it's getting so much harder to find/manage them in the UI.

**Comment by ranbel** [comment]
Those are all valid points -- it would definitely help to have better search functionality in the UI.

> what is the difference between "Cloudflare One" and "Cloudflare Zero Trust" and ["Zero Trust Networks"](https://one.dash.cloudflare.com/413ad3842c5a82a780b582d8de8dc903/networks/tunnels) and ["Zero Trust Connections"](https://developers.cloudflare.com/cloudflare-one/connections/)? What names are completely deprecated and what names are duplicates that refer to the same concept/products?

If you think of a Venn Diagram, Cloudflare One is the biggest circle. It encompasses Cloudflare Zero Trust along with Magic WAN and other products. Within Cloudflare Zero Trust, there are features related to connectivity (Zero Trust Connections) as well as features for security policies, browser isolation, and more. Within Zero Trust Connections, we have Cloudflare Tunnel (Zero Trust Networks) along with the WARP client and clientless connectivity methods. In summary, the hierarchy is: Cloudflare One > Cloudflare Zero Trust > Connections > Networks > Tunnel. 

Hope this helps. I'm going to close this issue since we only take care of docs in this repo. I recommend submitting your UI feedback via the "Give feedback" button in the search bar.

**Comment by pirate** [comment]
To be clear this ticket is specifically for improving this page of the Docs:

[developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq](https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/)

I think you add everything you said in your replies here to that page, and prominently show how to get to the proper "Coudflare One Zero Trust Networks Tunnels" dashboard UI.

Also explain the re-name history / product venn diagram, that way it'll show up when users search any of the previous names (e.g. `Argo`/`Warp`).

**Comment by ranbel** [comment]
I've added a link to the legacy tunnels page in #14337. We'll consider a bigger update to the FAQ if we start seeing other similar doc requests.
