### ISSUE TITLE
Conflicting descriptions regarding DCV Delegation

### ISSUE THREAD

**Issue by ushuz** [cloudflare/cloudflare-docs#14327]
### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/methods/delegated-dcv/
https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/enable-universal-ssl/#partial-dns-setup
https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/#non-wildcard-certificates

### What changes are you suggesting?

The "Delegated DCV" page states it's only available with Advanced Certificate Manager:
<img width=600 src=https://github.com/cloudflare/cloudflare-docs/assets/1430856/ccc6f210-4da1-43cc-917e-a5c6146b02dd >

While several other docs and the dashboard suggest Universal SSL can use DCV Delegation.

<img width=600 src=https://github.com/cloudflare/cloudflare-docs/assets/1430856/bbe5f918-60b0-414d-accb-ebc76939963a>

Source: https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/enable-universal-ssl/#partial-dns-setup

<img width=600 src=https://github.com/cloudflare/cloudflare-docs/assets/1430856/ec11443e-f302-44f1-9734-bb76abe0f88c>

Source: https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/#non-wildcard-certificates

Question: Which statement is true and up-to-date? Can DCV Delegation be used for Universal SSL?

**Comment by kodster28** [comment]
Howdy @ushuz, all of those docs are correct. 

Delegated DCV one of [several methods](https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/methods/) for DCV.

You can do other methods of DCV with universal certificates (as those docs state), but then Delegated DCV is only allowed with Advanced certs.
