### ISSUE TITLE
The doc is not clear. Account level Advanced Certificate Manager is needed. 

### ISSUE THREAD

**Issue by cjcfcode** [cloudflare/cloudflare-docs#14341]
### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/additional-options/certificate-signing-requests/

### What changes are you suggesting?

The doc is not clear. Account level Advanced Certificate Manager is needed. 

With only zone - level Advanced Certificate Manager, users cannot see "Step - 3, On Certificate Signing Request (CSR), select Generate."

Account Level CSR:
Customers who have Advanced Certificate Manager (ACM) enabled on their account can generate a CSR that includes hostnames from other zones in the SANs field. Keep in mind that you will still be responsible for uploading certificates to each zone individually

**Comment by kodster28** [comment]
Howdy @cjcfcode, tracking this via an internal issue (PCX-10721), so closing out this external one.

If you're part of CF, the general preference is to have internal stuff submitted via tickets.
