### ISSUE TITLE
How to hide calls api credentials?

### ISSUE THREAD

**Issue by Zibri** [cloudflare/cloudflare-docs#14342]
### Proposed changes

https://dash.cloudflare.com/xxxxx/calls

### Subject Matter

Calls api credentials.

### Content Location

nowhere I could find.

### Additional information

In calls api, when generating a key it states: When deploying to production, your secret key should be kept server-side.
After, there is a sample html file for a call. Inside it the is the secret api key.
If the api call application is HTML where could the api key be hidden?
I don't understand.

**Comment by Zibri** [comment]
Also: if a webrtc call is between 2 people both behind firewalls (for example connected by 4g/5g providers), STUN alone won't be enough. TURN is needed too.
And I see no mention of turn servers.

**Comment by third774** [comment]
We're going to have a TURN service available soon, so stay tuned for that!
As for where the secret should be — in order for it to be kept server-side, you need to have an API that is making requests to the Calls API on behalf of your browser clients.

**Comment by Zibri** [comment]
ok.. I though there was some other method "cloudflare-style" for that... ok then.. all clear.

**Comment by kodster28** [comment]
Closing this out as it seems this question was resolved w/o needing any doc updates.
