### ISSUE TITLE
No actual place (besides in documentation,) to transfer domain name!

### ISSUE THREAD

**Issue by johdough** [cloudflare/cloudflare-docs#14386]
### Example URL(s)

[Screenshot_20240503-114844](https://github.com/cloudflare/cloudflare-docs/assets/105259217/26b1e376-aa64-4e3e-b05a-29a3a7935d44)
![Screenshot_20240503-114604](https://github.com/cloudflare/cloudflare-docs/assets/105259217/6a8cc52b-a637-4c90-8dbc-a8d76e7d1716)

### Actual Behavior

No actual place (besides only in documentation,) to transfer domain name so I can transfer my domain!

### Expected Behavior

No actual place (besides in the documentation,) to transfer domain name so I can transfer my domain!

### Additional information

No actual place (besides in documentation,) to transfer domain name so I can transfer my domain!

And one screenshot above shows my domain **NOT registered** and the other shows not registered, but needs namservers updated at my hoster?

I need to TRANSFER to be able to actually be able to *manage** my domain, without conflicting how tos! 
And I do NOT know what is supposed to be input into all the boxes?????
THANK YOU!

**Comment by kodster28** [comment]
Howdy @johdough, I'd encourage you to submit a ticket to our [Support team](https://dash.cloudflare.com/?to=/:account/support) about this issue.

We can't do much to help with troubleshooting issues around the interface itself.
