### ISSUE TITLE
[Turnstile] Pre clearance implementation

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#14384]
### Existing documentation URL(s)

https://developers.cloudflare.com/turnstile/concepts/pre-clearance-support/

### What changes are you suggesting?

honestly I'm completely lost by the docs.

1) I think that the blog post should not be the only place with code or how-to
2) I see no way to verify a pre clearance token (All I see is mention of a WAF rule).

In a SPA with SSR framework (for example, we're using Qwik), each page is dynamically loaded as JSON chunks by a service worker and the url bar is rewritten "placebo" style (no actual GET/POST requests - all intercepted by the framework router as if they really were), WAF doesn't reliably intercept it (only if that specific page is directly visited from the start or refresh). However as part of SSR, a check (like normal turnstile) can be manually done.

### Additional information

Feedback collected from Discord user

**Comment by patriciasantaana** [comment]
Closing this since we are tracking the issue via an internal PCX ticket.
