### ISSUE TITLE
Ports and IP's Burried

### ISSUE THREAD

**Issue by rderewianko** [cloudflare/cloudflare-docs#1438]
### Expected Behavior
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation
Links the FAQ page for ports 
https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq#what-are-the-ports-and-ips-used-by-cloudflared

### Actual Behavior
This page does not, and if you're installing i feel its missing info that is crucial to success.
### Section that requires update
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation

### Additional information
Any other details or screenshots you think are relevant.

**Comment by KimJ15** [comment]
We have made several updates to this page since the issue was opened. Closing, although feel free to open another issue should there be any specific requests to clarify content.
