### ISSUE TITLE
Store data with Fauna --> Wrangler 1 to 2

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#14418]
https://developers.cloudflare.com/workers/tutorials/store-data-with-fauna/: https://github.com/fauna-labs/fauna-workers/blob/master/wrangler.toml contains the redundant `type="javascript"`, and the tutorial references (but doesn't actually use `type="webpack"`).

Likely makes sense to update with Hono as well

**Comment by yusukebe** [comment]
Hi @kodster28 

> https://developers.cloudflare.com/workers/tutorials/store-data-with-fauna/

I think this tutorial uses the latest tools - Hono, TypeScript, and Wrangler v3. This refers to  https://github.com/yusukebe/fauna-workers instead of https://github.com/fauna-labs/fauna-workers/tree/master. Can you check it?

**Comment by kodster28** [comment]
> Hi @kodster28
> 
> > https://developers.cloudflare.com/workers/tutorials/store-data-with-fauna/
> 
> I think this tutorial uses the latest tools - Hono, TypeScript, and Wrangler v3. This refers to https://github.com/yusukebe/fauna-workers instead of https://github.com/fauna-labs/fauna-workers/tree/master. Can you check it?

Oh... you're totally right!

You already did this work in #10050. Thanks past @yusukebe for doing the work and present @yusukebe for letting me know!
