### ISSUE TITLE
Why would Cloudfare nameservers be changed without my knowledge

### ISSUE THREAD

**Issue by ttrusty** [cloudflare/cloudflare-docs#14435]
### Example URL(s)

https://westherimerre.com

### Actual Behavior

Hi. The nameservers for this site were changed from amit.ns.cloudflare.com and nicole.ns.cloudflare.com to ivan.ns.cloudflare.com and tara.ns.cloudflare.com without my knowledge or notification resulting in the Cloudflare account for that domain being deleted. Why would this happen? Are these legit CF nameservers? Have I been compromised? FYI—the domain is registered with GoDaddy. Thanks in advance, Tom

### Expected Behavior

See above.

### Additional information

See above.

**Comment by kodster28** [comment]
Howdy @ttrusty, sorry to redirect you... but this sounds like a question you might want to send over to [Cloudflare Support](https://dash.cloudflare.com/?to=/:account/support) or post about in the [Cloudflare Community](https://community.cloudflare.com/).

**Comment by ttrusty** [comment]
No problem Kody. I appreciate your help and the links. Thanks.
