### ISSUE TITLE
Sphinx deployment does not work with Python >= 3.8

### ISSUE THREAD

**Issue by jeffh-cloudflare** [cloudflare/cloudflare-docs#1443]
### Expected Behavior
Deploy a Sphinx site
https://developers.cloudflare.com/pages/framework-guides/deploy-a-sphinx-site

### Actual Behavior
When deploying a Sphinx site and using pipenv in conjunction with Python 3.8 (or newer), the deployment via Pages fails. 

### Section that requires update
After installing pipenv, but before installing Sphinx, there should be a section that covers checking the installed version of Python. Then, if the version of Python is >= 3.8, the documentation needs to cover the process of installing an earlier version of Python (3.7 works without issue), as well as show how to instruct pipenv to use Python 3.7:

python --version
--or--
python3 --version

Depending on the OS, it's possible that 'python' is still Python 2.x and you need to run 'python3' to determine the version of Python 3.x that's installed.

pipenv --python 3.7 (this will force pipenv to use Python 3.7

Once Python 3.7 is enforced, continue with installing Sphinx, running sphinx-quickstart, and the rest just goes from there...with ONE exception.

There is a section that speaks to configuring the environment variable for PYTHON_VERSION:

```
Below the configuration, make sure to set the environment variable for specifying the PYTHON_VERSION.

For example, PYTHON_VERSION: 3.7.
```

PYTHON_VERSION should not have a trailing colon ":" and there should not be a period "." after 3.7. A screenshot or code-snip would be ideal.

### Additional information
The documentation assumes the user is well-versed with git. I will open another "Issue" to cover my recommendations around how to enhance the documentation.

**Comment by kristianfreeman** [comment]
@jeffh-cloudflare would you be interested in submitting a pull request to fix this?

**Comment by jeffh-cloudflare** [comment]
Sure! I can do that.

**Comment by kristianfreeman** [comment]
@jeffh-cloudflare any interest in doing a PR here still?

**Comment by jeffh-cloudflare** [comment]
Creating pull request now.
