### ISSUE TITLE
Pages - Documentation References to Git Should Provide More 

### ISSUE THREAD

**Issue by jeffh-cloudflare** [cloudflare/cloudflare-docs#1444]
### Expected Behavior
The Cloudflare Pages documentation tends to make assumptions that users are well-versed in Git. In cases where they are not,  it  will likely be very difficult for the user to successfully deploy a site with Cloudflare Pages.

Today, the following three lines are indicative of what the documentation states needs to be done:

```
git remote add origin https://github.com/yourgithubusername/githubrepo
git branch -M main
git push -u origin main
```
That is barely enough to get the job done.

The Sphinx documentation is only one example of this.
https://developers.cloudflare.com/pages/framework-guides/deploy-a-sphinx-site

### Actual Behavior
The first command in above section will fail if the user has not taken several other steps beforehand.

Navigate to GitHub.com and create a repository (as currently indicated in the documentation).
Ensure that SSH key-based authentication is working:

```
ssh-keygen -t ecdsa -C "me@company.com"
Save file in ~/.ssh/<id_rsa>
``` <-- desired file name

Start SSH Agent:

`eval "$(ssh-agent -s)"`

Add SSH key to ssh-agent:

`ssh-add ~/.ssh/id_rsa`

Confirm SSH key loaded into ssh-agent:

`ssh-add -l
`
Test SSH authentication against GitHub:

```
ssh -T git@github.com
"Hello <USERNAME>! You've successfully authenticated, but GitHub does not provide shell access."
```

MISSION SUCCESSFUL! Move on to next steps....

In the case of Sphinx, once the user runs sphinx-quickstart, they should change to the directory for the Sphinx site and perform the following:

```
git init
git config user.name = "Your Name"
git config user.email = "me@company.com"
```

Create a README.md file

`nano README.md`

Add the README.md via git and commit:

```
git add README.md
git commit -m "First commit"
git branch -M main
git remote add origin git@github.com:<GITHUB USERNAME>/<GITHUB REPONAME>.git
git push -u origin main

```
Then, include the rest of the Sphinx site in the git commit:

```
git add *
git commit -m "Commit initial Sphinx site"
git push -u origin main
```

Then proceed with Cloudflare Pages deployment - the user will be FAR more successful! :-)

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kristianfreeman** [comment]
note to self - update all how-to guides with collapsible git instructions (set up ssh key - or at least link to guide on it + init repo, etc etc) - use BeforeYouStart style component

**Comment by kristianfreeman** [comment]
Potentially link to:

- https://guides.github.com/introduction/git-handbook/
- https://git-scm.com/book/en/v2

**Comment by kristianfreeman** [comment]
after issue triage, our current plan is to update the Getting Started guide with more info, to help people get started with Git. leaving this assigned to me for now, though this is a #goodfirstissue for obinna when he joins :)

**Comment by Ekwuno** [comment]
Closing this issue because #2186 address it. Thanks for pointing this out @jeffh-cloudflare
