### ISSUE TITLE
Add SquareSpace Instructions as a provider

### ISSUE THREAD

**Issue by altonbrailovskiy** [cloudflare/cloudflare-docs#14452]
### Proposed changes

With Squarespace acquiring google domains, I have decided to switch to Cloudflare. It'd be helpful to have instructions for Squarespace configurations both for setting up DNS and transferring the domain entirely.

### Subject Matter

DNS + Transfers + DNSEC

### Content Location

https://developers.cloudflare.com/fundamentals/setup/manage-domains/add-site/
https://developers.cloudflare.com/dns/dnssec/#disable-dnssec

**Comment by nrdevau** [comment]
I have also been hit by a force to Squarespace. :+1:  as I'd love to migrate to Cloudflare as well

**Comment by RebeccaTamachiro** [comment]
Hey there 👋 Thanks for reaching out. Apart from the referred pages (which now contain links to Squarespace instructions) you may also want to consider the following docs, depending on your needs. Hope it helps!

- https://developers.cloudflare.com/registrar/get-started/transfer-domain-to-cloudflare/
- https://developers.cloudflare.com/dns/manage-dns-records/reference/vendor-specific-records/#squarespace
