### ISSUE TITLE
Issues with Installing gatsby-cli and Creating Lumen Site

### ISSUE THREAD

**Issue by jeffh-cloudflare** [cloudflare/cloudflare-docs#1445]
### Expected Behavior

https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site#installing-gatsby

The guide states the following is all that's required to install the gatsby-cli:

npm install -g gatsby-cli

This will fail consistently due to numerous dependency checks not completing successfully and it also tends to install an older version of gatsby-cli (2.x).

Additionally, the section on creating a new project based on the Lumen theme will attempt to install additional packages in the context of the user and also fails dependency checks.

https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site#creating-a-new-project

### Actual Behavior

The following assumes Node 14.x is installed along with the included version of npm (7.x):

curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh

```
node --version
v14.17.0
``` (at the time of this issue)

```
npm --version
7.14.0
```

On Linux, any global installation via npm (npm install -g) must be preceded with sudo:

`sudo npm install -g`

If using npm version 7 or newer, it's also best to use the legacy peer dependencies option and specify the most current version of gatsby-cli:

`sudo npm install -g gatsby-cli@latest --legacy-peer-deps`

When creating a new project,, once gatsby-cli is installed, it's far simpler to do the following:

```
gatsby new cfpages-gatsby (where cfpages-gatsby is the name of the Gatsby site.
cd cfpages-gatsby
```

This defaults to a basic Gatsby theme with the existing npm global packages that can be modified at a later time.

Then follow the git-specific recommendations I made in:

https://github.com/cloudflare/cloudflare-docs/issues/1444

And proceed with the Gatsby build process via Cloudflare Pages as delineated in:

https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site#deploying-with-cloudflare-pages

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kristianfreeman** [comment]
this is more of a gatsby installation issue - PR welcome to mention required node version on your local machine but generally we should encourage ppl to interact with gatsby's docs/support team
