### ISSUE TITLE
[D1] Test an index should call-out the `rows_read` meta property

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#14464]
### Existing documentation URL(s)

- https://developers.cloudflare.com/d1/build-with-d1/use-indexes/#test-an-index

### What changes are you suggesting?

Users are directed to use indexes for cost optimization, it'd be helpful if users who land on the indexes page directly are told how to test how effective their indexes are for their workload.

A good example is under the "How can I estimate my (eventual) bill?" heading on https://developers.cloudflare.com/d1/platform/pricing/#frequently-asked-questions

**Comment by KimJ15** [comment]
This issue is pretty stale. Closing as won't do for now.

**Comment by Oxyjun** [comment]
Retrospectively actioning this to close internal ticket. Linked relevant FAQ section.

https://github.com/cloudflare/cloudflare-docs/pull/18169
