### ISSUE TITLE
[Workers] Postmark example issues

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#14467]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/tutorials/send-emails-with-postmark/

### What changes are you suggesting?

* Formatting
  * There is a newline at the start of the `fetch` handlers, it'd be good if we could run the examples through Prettier.

* Code issues
  * Whilst it is functional, `return Response.json(await response.json())` is redundant. It is parsing a JSON string into a JS object, and then stringifying that JS object back into a JSON string. It would be sufficient to just `return response`.
  
* Possible additions
  * It'd be cool to have an example of taking user input (query params, JSON body, etc) and including that in the emails, so users can have a Worker as an "email sending" API.

**Comment by kodster28** [comment]
@megaconfidence, mind taking a look at this one?

**Comment by megaconfidence** [comment]
Hi @KianNH, I'll update the response line as you've suggested. The new line before and after the fetch block helps with readability. Thanks for your feedback.

**Comment by Cherry** [comment]
> Hi @KianNH, I'll update the response line as you've suggested. The new line before and after the fetch block helps with readability. Thanks for your feedback.

Out of interest, what makes you think that helps with readability?

It's not a standard across any other workers tutorials, or workers templates with C3, etc. I would argue that consistent code style is more important in the docs than personal preferences.

**Comment by megaconfidence** [comment]
Hi @Cherry, this fixed in #14583
