### ISSUE TITLE
[Wrangler] Undocumented configuration options

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#14468]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/wrangler/configuration/

### What changes are you suggesting?

Based on [environment.ts](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/config/environment.ts) and [config.ts](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/config/config.ts), there are several undocumented configuration options:

* `find_additional_modules`
* `base_dir`
* `version_metadata`
* `pages_build_output_dir`

**Comment by KimJ15** [comment]
This issue is pretty stale. Closing as won't do for now.
