### ISSUE TITLE
[Durable Objects] Include RPC as an alternative to `fetch`ing a stub

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#14471]
### Existing documentation URL(s)

- https://developers.cloudflare.com/durable-objects/best-practices/access-durable-objects-from-a-worker/#3-use-fetch-handler-method

### What changes are you suggesting?

It'd be good to showcase RPC here, since fetching a Durable Object class instance is sometimes confusing for new users.

**Comment by KianNH** [comment]
Maybe step 3 could be removed and instead point to https://developers.cloudflare.com/durable-objects/best-practices/create-durable-object-stubs-and-send-requests/#call-a-durable-object which already covers RPC and `fetch()`

**Comment by KimJ15** [comment]
This issue is pretty stale. Closing as won't do for now.
