### ISSUE TITLE
Outdated docs: Override URL or IP address 

### ISSUE THREAD

**Issue by CoreyH** [cloudflare/cloudflare-docs#14503]
### Existing documentation URL(s)

https://developers.cloudflare.com/rules/page-rules/how-to/override-url-or-ip-address/

### What changes are you suggesting?

This content seems to be outdated and I can't figure out how to do this anymore. None of the options allow the host header to be changed. Redirect rules don't allow different records.

**Comment by pedrosousa** [comment]
Host header overrides only are available on Enterprise plans, either through [Origin Rules](https://developers.cloudflare.com/rules/origin-rules/#availability) (recommended) or Page Rules.
Can you check if you're trying to configure one of these rules on an Enterprise zone?
