### ISSUE TITLE
Updating the help page "Add an IP address or prefix to the allowlist"

### ISSUE THREAD

**Issue by Korb** [cloudflare/cloudflare-docs#14538]
### Example URL(s)

https://developers.cloudflare.com/ddos-protection/tcp-protection/how-to/add-prefix-allowlist/

### Actual Behavior

> 1. Log in to the Cloudflare dashboard and select your account.
> 2. Go to Account Home > L3/4 DDoS > Advanced TCP Protection.
> 3. Under General settings > Allowlist, select Edit.

### Expected Behavior

The path to setting up your custom rules should match Cloudflare's current web interface. Apparently, the location of the corresponding section changed at some point, and the documentation was not updated taking into account the new section names and settings location. It seems to me that now these settings are located at `https://dash.cloudflare.com/0fe...28d/%sitename%/security/waf/tools`

### Additional information

![image_2024-05-13_12_17_26](https://github.com/cloudflare/cloudflare-docs/assets/3509797/fca7f9e8-bd6e-4daa-87c3-6b9719677d77)

**Comment by pedrosousa** [comment]
Hi @Korb 

I just checked and the instructions are still up to date, reflecting the current location in the dashboard where you configure Advanced TCP Protection (only available to Magic Transit customers).

![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/c702330b-3ad0-45dd-a0bb-d00181497b20)

Note that the **L3/4 DDoS** menu entry is available at the **account** level -- your screenshot shows the **zone**-level sidebar.

To go to the the Account Home from the zone-level dashboard, select the arrow next to **Back to Sa@stomdev...** (in your screenshot).

**Comment by Korb** [comment]
@pedrosousa, thank you for the clarification. It seems our subscription does not include Magic Transit. Because in the location you specified on the sidebar we only have the following items:

1. Websites
2. Discover
3. Domain Registration
4. Analytics & Logs
5. Security Center
6. Trace
7. WAF
8. Turnstile
9. Zero Trust
10. Area 1
11. Workers & Pages
12. Workers for Platforms
13. Al
14. R2
15. Stream
16. Images
17. Calls
18. Manage Account
19. Notifications
20. Bulk Redirects

Does this mean that we do not have the ability to add a list of IP addresses to the white list so that cloudflare protection against ddos is not carried out for them and the captcha is not displayed?

![image_2024-05-13_14_34_30](https://github.com/cloudflare/cloudflare-docs/assets/3509797/2d12a98f-9a6f-4448-b042-465a29f24da2)

**Comment by pedrosousa** [comment]
First, I would confirm which Cloudflare security product (and rule) is triggering the mitigation action: is it one of the [DDoS Attack Protection managed rulesets](https://developers.cloudflare.com/ddos-protection/managed-rulesets/), the [Web Application Firewall (WAF)](https://developers.cloudflare.com/waf/), or one of Cloudflare's [bot solutions](https://developers.cloudflare.com/bots/)?

You can use [Security Events](https://developers.cloudflare.com/waf/analytics/security-events/paid-plans/) for this purpose — check the details in the **Activity log** for requests that were recently blocked or challenged.

![image](https://github.com/cloudflare/cloudflare-docs/assets/680496/e9db3b05-fb01-487b-8d03-97f4dddf398f)

For the WAF, you can [create custom rules that skip certain security features](https://developers.cloudflare.com/waf/custom-rules/skip/), including WAF managed rules. The rule expression could include a custom [IP list](https://developers.cloudflare.com/waf/tools/lists/custom-lists/#ip-lists) with the IP addresses you wish to allow. Refer to [Use lists in expressions](https://developers.cloudflare.com/waf/tools/lists/use-in-expressions/) for instructions on referencing a list in a rule expression.

For DDoS protection, you can configure the L7 DDoS protection managed ruleset if one or more rules are causing false positives (that is, if there's legitimate traffic being blocked/challenged by a rule). Refer to [Handle a false positive](https://developers.cloudflare.com/ddos-protection/managed-rulesets/adjust-rules/false-positive/) for details.

For Bots, if you are on a paid plan, you can [create a WAF custom rule to skip Super Bot Fight Mode](https://developers.cloudflare.com/waf/custom-rules/skip/) for specific requests. However, if you are using the free Bot Fight Mode, [you cannot skip this security feature](https://developers.cloudflare.com/bots/get-started/free/#limitations) for specific requests, you can only [turn off Bot Fight Mode](https://developers.cloudflare.com/bots/get-started/free/#disable-bot-fight-mode) for the entire zone.

If you have additional questions, I suggest that you reach out to the [Cloudflare Community](https://community.cloudflare.com/) or contact [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/), if you're on a paid plan.
