### ISSUE TITLE
Cloudflare Architecture Icons

### ISSUE THREAD

**Issue by garysassano** [cloudflare/cloudflare-docs#14530]
### Proposed changes

It would be nice if Cloudflare could provide an official Architecture Icon Set, similarly to what other cloud providers do:
- [AWS](https://aws.amazon.com/architecture/icons/)
- [GCP](https://cloud.google.com/icons)
- [Azure](https://learn.microsoft.com/en-us/azure/architecture/icons/)

Even better, if Cloudflare could partner with draw.io to include them in the standard shape libraries.

The main purpose is to allow everyone to design diagrams like this one:
![image](https://github.com/cloudflare/cloudflare-docs/assets/10464497/5a9903f6-3282-4981-811d-15985c3a53d8)

In addition, it would be nice if Cloudflare could introduce additional icons for each resource within a service, like a R2 bucket for example.

### Subject Matter

Architecture diagram

### Content Location

New document

**Comment by kodster28** [comment]
Howdy @garysassano, flagged for another team internally and there's some progress on it... but this is a bit outside the scope of our normal "docs site" requests, so going to close out this issue.
