### ISSUE TITLE
Latest version of Altinity or Clickhouse plugins for Grafana does not work with Cloudflare Analytics Engine endpoint

### ISSUE THREAD

**Issue by spelexander** [cloudflare/cloudflare-docs#14532]
### Existing documentation URL(s)

- https://developers.cloudflare.com/analytics/analytics-engine/grafana/

### What changes are you suggesting?

The recommended plugin (Altinity) in the documentation no longer works for Cloudflare Analytics engine endpoints. Alternative plugins, such as the native Clickhouse plugin also do not work.

Please suggest an alternative in the documentation because this one sends readers down a dead end.

### Additional information

You can find the reported issue with the plugin here: https://github.com/Altinity/clickhouse-grafana/issues/558

**Comment by Slach** [comment]
Fixed in plugin version 3.1.0 (hope will release this week), sorry for the inconvenience

**Comment by kodster28** [comment]
Based on the comments + linked issue, it appears that this is solved?

**Comment by Slach** [comment]
yes, 3.1.1 recently released @spelexander please confirm issue resolved for you after upgrade
