### ISSUE TITLE
gRPC Support for Cloudflare Tunnel

### ISSUE THREAD

**Issue by devgig** [cloudflare/cloudflare-docs#14542]
### Proposed changes

gRPC Support for Cloudflare Tunnel

### Subject Matter

gRPC Support for Cloudflare Tunnel

### Content Location

gRPC Support for Cloudflare Tunnel

**Comment by ranbel** [comment]
Hi @devgig, thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo. [Cloudflare Tunnel does not currently support gRPC](https://developers.cloudflare.com/network/grpc-connections/#limitations), so this would be a feature request.
