### ISSUE TITLE
Add docs on bindings only supported with module format workers

### ISSUE THREAD

**Issue by penalosa** [cloudflare/cloudflare-docs#14540]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/reference/migrate-to-module-workers/#advantages-of-migrating

### What changes are you suggesting?

This should include a list of bindings that are only supported with module-format workers (which I think is D1/Vectorize/AI)

**Comment by KianNH** [comment]
Closed by https://github.com/cloudflare/cloudflare-docs/pull/14545
