### ISSUE TITLE
My company website is not working

### ISSUE THREAD

**Issue by vapcfmt** [cloudflare/cloudflare-docs#14559]
### Example URL(s)

https://amcvietnam.com.vn/

### Actual Behavior

Web server is down ( Error code 521)

### Expected Behavior

The website works normally

### Additional information

![521](https://github.com/cloudflare/cloudflare-docs/assets/169738264/06a96bb1-df55-460e-8e3f-794d539f9915)

**Comment by pedrosousa** [comment]
Hi @vapcfmt 
Unfortunately, there isn't much that Cloudflare can do about the issue you are having. Cloudflare is trying to reach your origin server, but the server is refusing connections.
If you are the site owner, you should reach out to your hosting provider to understand why your website is not available. 

For more information, refer to our [troubleshooting documentation](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-521-web-server-is-down) about this error.
