### ISSUE TITLE
Document mtls_cert and browser configuration support of Pages

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/cloudflare-docs#14573]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/functions/wrangler-configuration/

### What changes are you suggesting?

Document support for mtls_certificate and browser bindings in Pages wrangler.toml configuration.

**Comment by KimJ15** [comment]
Closed by https://github.com/cloudflare/workers-sdk/pull/5712
