### ISSUE TITLE
блокировка 

### ISSUE THREAD

**Issue by romanbadik** [cloudflare/cloudflare-docs#14576]
### Example URL(s)

https://platform.openai.com/playground?mode=chat&model=gpt-4o

### Actual Behavior

Добрый день . Моя попытка входа на сайт openai.com не увенчалась успехом по неизвестной мне причине. Прошу помочь в решении этой проблемы.

### Expected Behavior

Ожидал начать знакомство с chatgpt.

### Additional information

[IP:146.158.98.197 | Идентификатор луча: 88416c025b208ba1]

**Comment by kodster28** [comment]
Howdy @romanbadik, that's actually a setting controlled by OpenAI (not Cloudflare).

We can't do much on the Cloudflare side to stop anyone from getting flagged as potential bot traffic. Your best bet would be to reach out to the OpenAI support team.
