### ISSUE TITLE
Upgrading/Downgrading Cloudflare plans example uses old prices

### ISSUE THREAD

**Issue by Le0Developer** [cloudflare/cloudflare-docs#14614]
### Existing documentation URL(s)

https://developers.cloudflare.com/support/account-management-billing/billing-cloudflare-plans/cloudflare-billing-policy/#upgrade-or-downgrade-cloudflare-paid-plans

### What changes are you suggesting?

Currently the example is using the old prices for Pro (20$) and Business (200$) instead of the updated ones (25$ and 250$).

---

> Your invoice for the billing period of January 1 - January 30 in the amount of $110 will appear in the Cloudflare dashboard on January 31.

But the billing period should be Jan 1 - Jan 31? Using the correct number of days will make the numbers pretty messy, so probably a month with exactly 30 days should be used instead.

**Comment by KimJ15** [comment]
Thanks for the flag. Removed outdated $ from this page. Closed by https://github.com/cloudflare/cloudflare-docs/pull/17178
