### ISSUE TITLE
Moving from Page redirects to the ... https://developers.cloudflare.com/rules/reference/page-rules-migration/

### ISSUE THREAD

**Issue by dschroed** [cloudflare/cloudflare-docs#14634]
### Existing documentation URL(s)

Absolutely unclear on how I can create a redirect rule under the new governance model. kindly provide an example among the many praised new options... 

### What changes are you suggesting?

Absolutely unclear on how I can create a redirect rule under the new governance model. kindly provide an example among the many praised new options... 

### Additional information

currently I use the the Starting URL and map it to a new one. 

with the new rule settings, I stay clue less with way tooooo many options and lack of guidance in your documentation

**Comment by dschroed** [comment]
Using this: https://developers.cloudflare.com/rules/page-rules/

Took me 3 minutes, with the other options - I wasted 30 minutes - and went back to the old approach... which is working.

**Comment by kodster28** [comment]
I believe you're looking for https://developers.cloudflare.com/rules/reference/page-rules-migration/#migrate-forwarding-url?
