### ISSUE TITLE
Any suggestions how to use calls/turn with nextcloud

### ISSUE THREAD

**Issue by sbe-arg** [cloudflare/cloudflare-docs#14640]
### Existing documentation URL(s)

https://developers.cloudflare.com/calls/turn/ 

### What changes are you suggesting?

If there a known way to use the turn service with next cloud.
Currently gives the api token and a token id. I would be great if could provide a secret.

https://nextcloud-talk.readthedocs.io/en/latest/TURN/

It would open a new use case for market sales.

![image](https://github.com/cloudflare/cloudflare-docs/assets/23391642/97179707-03bc-4638-95ab-179a487eb5ea)

### Additional information

The contact section is missing calls under support :(

![image](https://github.com/cloudflare/cloudflare-docs/assets/23391642/0712b884-b355-4aff-9bac-83c0ff630e17)

**Comment by kodster28** [comment]
Howdy @sbe-arg, this sounds more like a feature request than a docs request.

I'd direct you towards the [Developer Discord](https://discord.cloudflare.com) as a better place for this sorta feedback (specifically the `calls` channel).
