### ISSUE TITLE
no mention of `--local` option in KV commands

### ISSUE THREAD

**Issue by PierBover** [cloudflare/cloudflare-docs#14703]
### Existing documentation URL(s)

https://developers.cloudflare.com/kv/reference/kv-commands/

### What changes are you suggesting?

Some KV commands have a `--local` option which is not docummented in the HTML docs.

The option works when doing eg:

> wrangler kv:key put some_key --path=file.json --binding=NAMESPACE --local

And it also appears in the documentation of the CLI:

![image](https://github.com/cloudflare/cloudflare-docs/assets/226483/96ea014f-8ce1-4455-9a24-b3295947c7f8)

**Comment by kodster28** [comment]
This has since been fixed, btw.
(apologies for the radio silence in the meantime)

https://developers.cloudflare.com/kv/reference/kv-commands/
