### ISSUE TITLE
Change [account_id] to [account_tag]

### ISSUE THREAD

**Issue by ewong-cloudflare** [cloudflare/cloudflare-docs#14710]
### Existing documentation URL(s)

Instructions to install custom root certificate in: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/custom-certificate/#deploy-a-custom-certificate

references account_id: curl "https://api.cloudflare.com/client/v4/accounts/{account_id}/mtls_certificates" \

### What changes are you suggesting?

To change it to:

curl "https://api.cloudflare.com/client/v4/accounts/{account_tag}/mtls_certificates" \

and for all subsequent documentation to align with terminology used internally

**Comment by kodster28** [comment]
Howdy @ewong-cloudflare, `account_id` is the term most appropriate for our external users -- b/c that's what it's called [in the dash](https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/) -- + that's the primary docs audience.

If you really think this is a change you'd want to see, you'd need to drive some internal change to align the dash terminology to `account tag`.
