### ISSUE TITLE
Include types of certificates supported for custom certificate deployment

### ISSUE THREAD

**Issue by ewong-cloudflare** [cloudflare/cloudflare-docs#14713]
### Proposed changes

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/custom-certificate/ does not currently have limitations or supported types of certificates and encryption algorithms. 

If they are all supported, then it should be called out as such, and if there are limitations, likewise.

### Subject Matter

Custom certificate limitations

### Content Location

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/custom-certificate/

**Comment by kodster28** [comment]
Closing this out as this is tracked internally by PCX-10982
