### ISSUE TITLE
Add "Random Canvas Fingerprint Unsupported" to Limitations of Turnstile

### ISSUE THREAD

**Issue by jyxjjj** [cloudflare/cloudflare-docs#14732]
### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/waf/reference/cloudflare-challenges.md
https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#limitations

### What changes are you suggesting?

https://community.cloudflare.com/t/658685

### Additional information

I can add it via pr directly but i think i should ask for your opinions.

**Comment by patriciasantaana** [comment]
Hi @jyxjjj! Thank you for bringing this to our attention. The limitation has been addressed in the [Challenges documentation](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/).
