### ISSUE TITLE
Update Page Rules migration guide with more information

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#14737]
### Existing documentation URL(s)

https://developers.cloudflare.com/rules/reference/page-rules-migration/

### What changes are you suggesting?

Currently this guide is missing information on the following examples. Many of these are where people struggle during migration and need extra care and attention:

## Matching paths

Matching paths is much more complex with other Rules products compared to Page Rules. For example:

Page Rule: `https://jross.dev/test/*/*.zip`
Equivalent Ruleset Engine: `http.host eq "jross.dev" and lower(http.request.uri.path) matches "^/test/[^/]+/.*\.zip$`
(or something more complex without regex)

The migration guide doesn't really go into matching paths at all and ideally should be extended to showcase some examples here.

## Regex

Regex is required for a lot of rules to match more complex paths, especially compared to wildcards previously.

Regex is also only available on paid plans though, so some functionality that was possible on free plans is not possible with other Rules products today, and this need to be described.

## Case Sensitivity

Page Rules were case insensitive (in matching). Other Rules products are case sensitive, and to match the same behaviour, you need to wrap any functions in `lower()` or similar before doing checks.

This difference should probably be mentioned so people don't hit any obscure edge-cases when migrating their rules.

## Wildcards

I have a thread on the forum that details this more: https://community.cloudflare.com/t/page-rules-are-now-deprecated-without-good-replacements/656245?u=cherryjimbo

But essentially recreating a Page Rules redirect with `www.jross.dev/*/downloads/*/*.txt` and `downloads-$2.jross.dev/texts/$1/$3.txt`, ends up looking something like this:
```json
{
  "name": "default",
  "phase": "http_request_dynamic_redirect",
  "kind": "zone",
  "rules": [
    {
        "expression": "http.host eq \"www.jross.dev\" and http.request.uri.path matches r\"^/.*/downloads/.*/.*\\.txt$\"",
        "action": "redirect",
        "action_parameters": {
          "from_value": {
            "target_url": {
              "expression": "regex_replace(http.request.uri.path, r\"^/(.*)/downloads/(.*)/(.*)\\.txt$\", \"https://downloads-${2}.jross.dev/texts/${1}/${3}\")"
            },
            "status_code": 301,
            "preserve_query_string": true
          }
        }
      },
    {
      "expression": "http.host eq \"www.jross.dev\" and http.request.uri.path matches r\"^/.*/downloads/.*\\.txt$\"",
      "action": "redirect",
      "action_parameters": {
        "from_value": {
          "target_url": {
            "expression": "regex_replace(http.request.uri.path, r\"^/(.*)/downloads/(.*)\\.txt$\", \"https://downloads.jross.dev/texts/${1}/${2}\")"
          },
          "status_code": 301,
          "preserve_query_string": true
        }
      }
    }
  ]
}
```

This is much more complex, and as far as I can tell, impossible today on plans that do not have access to Regex - wildcard support is coming, but isn't available to folks yet.

**Comment by pedrosousa** [comment]
Hi @Cherry 
Thank you for all the context. These future improvements are in our radar, and we will expand the migration guide in the upcoming weeks.

**Comment by pedrosousa** [comment]
Hello again!
Since this issue was opened, we've done numerous updates to our public documentation. We've also introduced wildcard matching support (with operators for case-sensitive and case-insensitive matching) on all Cloudflare plans so that rule expressions are easier to write.
Also, Page Rules are not going away for the time being. And when the time comes, Cloudflare will perform the migration for you.

This matter was also discussed in the following Community thread (which you created):
https://community.cloudflare.com/t/page-rules-are-now-deprecated-without-good-replacements/656245/1
