### ISSUE TITLE
Metric Type For UDP Total Session

### ISSUE THREAD

**Issue by tienhuynh5312** [cloudflare/cloudflare-docs#14744]
### Existing documentation URL(s)

[| `cloudflared_tcp_total_sessions` | Total number of TCP sessions that have been proxied to any origin. | COUNTER |  |
](https://github.com/cloudflare/cloudflare-docs/blob/1aef7f0fb17294f77466f00e9fc75e8239342088/content/cloudflare-one/connections/connect-networks/monitor-tunnels/metrics.md?plain=1#L44)

[| `cloudflared_udp_total_sessions` | Total number of UDP sessions that have been proxied to any origin. | GAUGE |  |](https://github.com/cloudflare/cloudflare-docs/blob/1aef7f0fb17294f77466f00e9fc75e8239342088/content/cloudflare-one/connections/connect-networks/monitor-tunnels/metrics.md?plain=1#L55)

### What changes are you suggesting?

Metric type for UDP Total Sessions should be `Counter`. If this gets reviewed and updated, the Prometheus endpoint of the tunnel will need to be updated as well.

### Additional information

File a bug issue over `cloudflared`
https://github.com/cloudflare/cloudflared/issues/1253

**Comment by ranbel** [comment]
thanks for flagging this issue!
