### ISSUE TITLE
Доброго времени суток! После замены DNS записей перестал работать сайт, до того работал! ПОМОГИТЕ ! Настраивал, как было предложено сайтом...

### ISSUE THREAD

**Issue by Piotr329** [cloudflare/cloudflare-docs#14758]
### Example URL(s)

https://tarkhass-hosting.ru/glavnaja
![скрин1](https://github.com/cloudflare/cloudflare-docs/assets/170864615/cc90d816-ab48-4a65-803d-f2ac524f8fa6)

### Actual Behavior

![скрин2](https://github.com/cloudflare/cloudflare-docs/assets/170864615/a0bb92d1-bbcb-468a-b839-aeebd235066f)

### Expected Behavior

Настройки выполнял как было предложено сайтом. 

### Additional information

![скрин3](https://github.com/cloudflare/cloudflare-docs/assets/170864615/acb5e5af-1827-4c9e-bf44-aec00fc92d99)
![скрин4](https://github.com/cloudflare/cloudflare-docs/assets/170864615/d2de5c62-2001-40d9-8e69-eee9930b649a)
![скрин5](https://github.com/cloudflare/cloudflare-docs/assets/170864615/26eb82d0-2ccc-4745-936e-ca44b785d1de)

**Comment by kodster28** [comment]
Howdy @Piotr329, I'd recommend reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or posting in the [Cloudflare Community](https://community.cloudflare.com/) about this issue.
