### ISSUE TITLE
Update or retire Cursor AI assistant

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#14773]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/ai/

### What changes are you suggesting?

The information provided by Cursor is often outdated or incorrect, and needs to be updated, or simply retired.

Some examples:

<details>
<summary>Is Workers AI stable?</summary>
Workers AI is currently in Open Beta and is not recommended for production data and traffic. Limits and access are subject to change.

SOURCE: workers-ai/
</details>
Workers AI was announced as GA back in Developer Week.

---

<details>
<summary>When should I use Workers Sites vs Cloudflare Pages?</summary>
For hosting full-stack applications, it is recommended to use Cloudflare Pages instead of Workers Sites. Workers Sites is suitable for deploying static applications directly to Workers, especially those built with static site generators like Hugo.

These sources might provide additional context:

https://developers.cloudflare.com/workers/configuration/sites/
</details>

Pages is the recommended solution for static site generators too. This is incorrect.

---

<details>
<summary>What's better? Module worker format, or service worker format?</summary>

The decision between the Module worker format and the Service worker format depends on your specific use case and requirements.

The Module worker format allows you to export a collection of files and modules, providing more flexibility in structuring your code. It also supports ES Modules syntax, which can be beneficial for organizing and managing complex projects.

On the other hand, the Service worker format requires a single file to be uploaded and relies on global variables for bindings. It may be simpler for smaller projects or those that do not require the modularity provided by ES Modules.

Ultimately, the choice between the two formats should be based on the complexity of your project, the need for modularity, and your familiarity with ES Modules.

These sources might provide additional context:
https://developers.cloudflare.com/workers/wrangler/migration/v1-to-v2/wrangler-legacy/configuration
</details>

This fails to include any information about new products that don't work without Module Workers, or that they're faster, and more secure. 

---

<details>
<summary>What's the available pricing models for Workers?</summary>
Workers are available under two Usage Models: Bundled and Unbound. Usage Models are settings on your Workers that specify how you are billed for usage, as well as the upper limits.

These sources might provide additional context:
https://developers.cloudflare.com/workers/platform/pricing

</details>
This is inaccurate, with Standard being the only current pricing model available for Workers.

---

<details>
<summary>Is D1 ready for production traffic?</summary>
D1 is currently in public beta, and while the D1 team expects breaking changes and issues to be minimal, they may still occur. The D1 team generally does not recommend running large production workloads on beta products.

These sources might provide additional context:

https://developers.cloudflare.com/d1/
</details>

---

These are just a few examples where the responses are out of date, inaccurate, unhelpful, and in some cases could be potentially harmful if a prospective customer used the data. It does come with a disclaimer about accuracy, but I think some effort needs to be made to keep this up to date and not (seemingly) abandoned. Or if that's unlikely, it should probably just be retired and folks can rely on the more useful Algolia search.

**Comment by Cherry** [comment]
The lack of any persistent context means you can get results like this too, where it completely changes what is actually being talked about:
![](https://i.james.pub/file/2024/05/2402ed3e-dc33-4ed9-9cc3-72255b0a026e.png)

**Comment by kodster28** [comment]
cc: @mhart for visibility

**Comment by mhart** [comment]
Hey @Cherry ! I appreciate the notes about certain answers being out of date, will look at improvements here.

But ultimately, let's not bury the lede:

> It does come with a disclaimer about accuracy

Let's not underplay this fact – the disclaimer is quite large and still 100% relevant. Unless we move this out of an experimental phase, this will still be the most important thing to keep in mind.

**Comment by Cherry** [comment]
Thanks @mhart, I appreciate the followup. It's good to hear that some things will be updated so answers aren't out of date.

> Let's not underplay this fact – the disclaimer is quite large and still 100% relevant. Unless we move this out of an experimental phase, this will still be the most important thing to keep in mind.

While I understand this, I think you overestimate how useful this disclaimer is, or how many people read it. More often than not, the feedback we see in Discord when someone uses this is something like "but the AI said X", and we have to tell them it's inaccurate and point them at the right documentation. A disclaimer and being experimental imo isn't an excuse to dismiss accuracy issues like this.

This is all especially true in my second reply to this issue about AI. I asked Cursor a question about AI, got an answer, then asked a followup question, expecting context to be retained. But I then got an answer completely unrelated to AI, about router models supported by magic network monitoring. Users familiar with other bots like ChatGPT or Gemini are very very used to this kind of contextual conversation where the answers are wayyy better, so are again likely to just ignore / dismiss any disclaimers. Is this really a good first impression for folks interacting with the docs, or seeing Cloudflare's AI offerings for the first time?

We've seen [in the news recently too](https://www.wired.com/story/air-canada-chatbot-refund-policy/) where a company had to honour what an AI chatbot said, despite it being incorrect, and despite it linking to the source documentation that did include the full policy. To play devil's advocate here for a second, if Cursor tells me that my Workers bill is going to just be $0.50 per additional million requests with no mention of other charges like CPU time with Standard for example, will Cloudflare honour that?

**Comment by mhart** [comment]
I've updated the index, the out-of-date answers should be a little better now. Thanks for the nudge!

Workers Sites is a tricky one, just because we do still document it. Eg https://developers.cloudflare.com/workers/configuration/sites/ does say:

> Workers Sites enables developers to deploy static applications directly to Workers. It can be used for deploying applications built with static site generators like Hugo and Gatsby, or front-end frameworks like Vue and React.

So the bot still references that in its answer.

**Comment by Cherry** [comment]
Thanks @mhart!

I think it would be great if the index updating could be automated in a github action workflow (or something) every week or so, to ensure the data never gets quite as out of date again. What do you think?

And I think adding persistent context in conversations would really help make Cursor's responses much more helpful for most users, as showcased in my questions around AI to it in the previous reply: https://github.com/cloudflare/cloudflare-docs/issues/14773#issuecomment-2134144353

**Comment by Cherry** [comment]
It looks like this was retired in the transition to the new docs platform.

This is great to see, with algolia search providing a way better user experience than Cursor AI was able to. 👏

**Comment by Cherry** [comment]
Nevermind. https://github.com/cloudflare/cloudflare-docs/pull/16801

I guess we'll continue to have to tell people to avoid the assistant when it reports invalid/out of date information.

**Comment by mhart** [comment]
Thanks for the feedback @Cherry

**Comment by Cherry** [comment]
Thanks @mhart. Does the closing of this issue indicate this is going to be retired, or regularly updated? What did you think about my feedback in a previous comment? https://github.com/cloudflare/cloudflare-docs/issues/14773#issuecomment-2137685913

Moving forward, would you like me to ping/alert you when people report issues/inaccuracies with Cursor throughout Discord and the forum, so you can provide them with support?

**Comment by mhart** [comment]
> Does the closing of this issue indicate this is going to be retired, or regularly updated?

Yep! It actually was being updated regularly and continues to be so – previously though there were stale document chunks in the vector index that were erroneously being fetched – that was all fixed in May.

There might be a brief period of things getting out of date right now as we update the document indexing to use the new content format/layout, but it shouldn't be too bad

> Moving forward, would you like me to ping/alert you when people report issues/inaccuracies with Cursor throughout Discord and the forum, so you can provide them with support?

Absolutely – so long as the inaccuracies are due to outdated content (and not just LLM hallucination), please let us know 🙏

**Comment by Cherry** [comment]
@mhart Thanks for the update.

> and not just LLM hallucination

When these hallucinations provide people with information that's wrong or inaccurate, is someone in the cf team available to answer these queries and point people in the right direction? Or are you expecting the community/discord/CSUP to correct these hallucinations? What about when people don't realise the information is wrong and waste time using bad code/results from this, provide others with now incorrect information, etc.?

What about when AI hallucinations are actually negatively impactful towards the business, despite disclaimers about being experimental? 

- https://futurism.com/the-byte/car-dealership-ai
- https://www.wired.com/story/air-canada-chatbot-refund-policy/

It's incredibly disappointing that you're not taking ownership for the responses this assistant might provide. It's on your website, and used by your users/customers. 

---

Here's an example question: `what's the best way to find and replace data using wildcards with transform rules?`. I would expect it to tell me about `wildcard_replace`, if it worked, but instead it tells me to use `prefix/.*` in transform rules directly, which doesn't work at all, and then links me to terraform and Pages sources?!

Or another: `is d1 global?`, which responds: `Yes, D1 is a global database service provided by Cloudflare. It automatically creates databases in locations close to where requests are made, optimizing data location based on user needs.`, and is completely inaccurate.

Or `what storage tiers does r2 offer`, which is just an "I don't know.".

Or `What's the R2 pricing for data retrieval?`, which is also an "I don't know.".

Or `What's the max CPU time for Queues?`, which reports `15 minutes` which is factually inaccurate and it's instead `30s`.

And then once again, the lack of context makes having a real discussion about docs to actually hone your questions and get better responses (like you can with real AI assistants), makes this even less useful:
![image](https://github.com/user-attachments/assets/c81b3ac8-5bf6-444e-aecd-575b511b2bc0)

**Comment by mhart** [comment]
I'm confident these tools will get better and better in time – these are industry-wide problems and we're all tackling them together.

**Comment by MattIPv4** [comment]
👀 I don't disagree with the notion they'll get better over time, but right now you have an assistant on the docs site that is spouting hallucinations containing false information that is damaging the business through lost and confused customers, and causing a headache for the community et al. who're having to let folks know not to trust this so-called assistant... No amount of disclaimer text is going to stop folks seeing a chat bot assistant and asking it questions, and expecting the answers to be correct, that's just not how it works (as evidenced by the links James shared where it didn't even hold up in a court of law).

**Comment by mhart** [comment]
This issue was to update or retire Cursor AI. We've updated it. We're not retiring it. We're going to continue to improve it.

**Comment by MattIPv4** [comment]
I do not believe it has been sufficiently updated to address the underlying issue here, see all the examples James provided where it is still providing false information about Cloudflare products...

**Comment by Cherry** [comment]
I completely agree with @MattIPv4. I appreciate the back and forth here @mhart, but this really hasn't been solved yet. Here's yet another example, about one of Cloudflare's most popular products:

![image](https://github.com/user-attachments/assets/9b9cd4d4-f66b-4c12-93a5-7804836d0cb0)

**Comment by mhart** [comment]
This issue isn't the right place to continue the conversation – you asked whether it's ok to bring up these issues in the forum / Discord and I said sure. We can continue to hone this tool there. Again, this particular issue has been completed, the updating issue was addressed. Gonna lock this now so we don't keep going back and forth on the same issues.
