### ISSUE TITLE
注册zero trust没有创建组织窗口

### ISSUE THREAD

**Issue by mutucun** [cloudflare/cloudflare-docs#14788]
### Example URL(s)

https://one.dash.cloudflare.com/598f6379c5a45abb2bc4884d7f19ac6d/home?tab=7d

### Actual Behavior

我在cloudflare里点击zerotrust没弹出创建组织窗口，我又在Access里找到了‘选择一个计划’选项，然而还是没有创建组织窗口。我无法创建组织。我尝试退出账号创建新账号后，在zerotrust里又可以创建组织了。但我在支付界面返回上一级，又无法创建组织了。貌似只有新注册用户第一次才能创建组织……我不清楚这是不是我的问题，希望能解答

### Expected Behavior

能帮我解决吗，如果不行，希望能为我解决。很抱歉打扰你们

### Additional information

![图片](https://github.com/cloudflare/cloudflare-docs/assets/141546596/19ffd07b-25a1-43eb-8703-ff71e027421b)

**Comment by kodster28** [comment]
Howdy @mutucun, unfortunately that's not something we (as a docs team) can help troubleshooting.

I'd recommend reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or posting in the [Cloudflare Community](https://community.cloudflare.com/) about this issue.
