### ISSUE TITLE
Add instructions to resolve common error "Statement too long"

### ISSUE THREAD

**Issue by t-rupe** [cloudflare/cloudflare-docs#14798]
### Existing documentation URL(s)

https://developers.cloudflare.com/d1/build-with-d1/import-data/#troubleshooting

### What changes are you suggesting?

I'd like to contribute to the Cloudflare D1 section "Importing Data" documentation. There's a common error I've experienced and many others being "Statement too long". While this message is concise and not wrong, inexperienced developers may not know how to fix this other than delete lines and lines of code, and hope their .SQL file will finally import successfully. This is due to the vast majority of people using some kind of database converter to convert their previous database to SQLite, which often will result in a single very long statement to CREATE data, for example. This can quickly be addressed by adding some simple instructions on how to reduce the statement by identifying an example of a too-long statement and illustrating how to split it up into numerous statements.

**Comment by Oxyjun** [comment]
Now tracking via https://github.com/cloudflare/cloudflare-docs/pull/17373

**Comment by Oxyjun** [comment]
Closing, as instructions have been added in.
