### ISSUE TITLE
QR code generator example is broken

### ISSUE THREAD

**Issue by lucasnad27** [cloudflare/cloudflare-docs#14797]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/tutorials/build-a-qr-code-generator

### What changes are you suggesting?

Cloudflare Pages is unable to build when importing  `qr-image`, due to the `zlib` dependency. This is true even if the `nodejs_compat` flag is set. Ideally, this example is updated to so it works on the CF runtime, or removed altogether to avoid wasted time by CF users :)

I found a workaround, using an unofficial port, [cf-qr-image](https://github.com/SteffTek/cf-qr-image) that uses pako in lieu of zlib.

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/2490636/20ae5230-522d-4187-abb8-f9ff0d301150)

**Comment by XpertForexTrade** [comment]
travisgahn:patch-7

**Comment by lucasnad27** [comment]
Thank you!!
