### ISSUE TITLE
Svelte guide not working due to NodeJS version

### ISSUE THREAD

**Issue by jp3492** [cloudflare/cloudflare-docs#1479]
### Expected Behavior
The page will be deployed as stated in the guide: [Guide](https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site)

### Actual Behavior
The pipeline failes due to old NodeJS version: 
`npm ERR! notsup Unsupported engine for @sveltejs/kit@1.0.0-next.113: wanted: {"node":"^12.20 || ^14.13.1 || >= 16"} (current: {"node":"12.18.0","npm":"6.14.4"})`

### Section that requires update
Either the guide needs to be updated to show a solution on this conflict or the pipeline needs to be upgraded to a newer version of NodeJS

**Comment by kristianfreeman** [comment]
cc @lukeed

**Comment by lukeed** [comment]
Ah ya, looks like it was changed here: https://github.com/sveltejs/kit/commit/261ee1cff9385feda45033ca7620ab2031e44e41#diff-0ac36eb0a5cc3505c582d3959e4bb51093770685d0de4a864f7cd9b68bd50b8f – beta things

I'll update the guide to reflect this
