### ISSUE TITLE
typo in  /learning-paths/workers/get-started/c3-and-wrangler/

### ISSUE THREAD

**Issue by d-sanderson** [cloudflare/cloudflare-docs#14822]
### Existing documentation URL(s)

https://developers.cloudflare.com/learning-paths/workers/get-started/c3-and-wrangler/

### What changes are you suggesting?

typo correction 

### Additional information

https://developers.cloudflare.com/learning-paths/workers/get-started/c3-and-wrangler/#source-of-truth

environment is mispelled as environemnt

**Comment by kodster28** [comment]
Howdy @d-sanderson, thanks for the fix!

Generally, no need to create an issue for a typo if you're going to fix it in a PR. Issues make more sense when it's an issue you don't know the cause of OR a much bigger change that needs attention or discussion.

**Comment by d-sanderson** [comment]
> Howdy @d-sanderson, thanks for the fix!
> 
> Generally, no need to create an issue for a typo if you're going to fix it in a PR. Issues make more sense when it's an issue you don't know the cause of OR a much bigger change that needs attention or discussion.

ok thanks for the quick response @kodster28 :) this was my first contribution so I wasn't sure if one was needed!
