### ISSUE TITLE
warp cannot be used with openvpn server

### ISSUE THREAD

**Issue by flowerseacar** [cloudflare/cloudflare-docs#14837]
### Example URL(s)

I want to let the traffic of openvpn server go through warp, but it seems that I can't do it on one machine

### Actual Behavior

cant work 

### Expected Behavior

can work

### Additional information

This is the openvpn server and warp on a vps. Note that it is the openvpn server server, not the client.

**Comment by kodster28** [comment]
Howdy @flowerseacar, that's more of a feature request than a docs update.

Will forward along internally, but closing out this issue in our repo.

**Comment by flowerseacar** [comment]
> Howdy @flowerseacar, that's more of a feature request than a docs update.
> 
> Will forward along internally, but closing out this issue in our repo.

thanks
