### ISSUE TITLE
Please document how to redirect all `*.pages.dev` domains in account with one Bulk Redirect

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/cloudflare-docs#14839]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/redirect-to-custom-domain/

### What changes are you suggesting?

I found [a really nice trick](https://community.cloudflare.com/t/custom-domain-issue-with-cloudflarepages/380126/16) for redirecting (effectively disabling) **ALL** `*.pages.dev` domains under an account with **one single Bulk Redirect**. This is especially important for Free accounts, [which only have 20 Bulk Redirects in total](https://developers.cloudflare.com/rules/url-forwarding/#availability).

This nicely addresses a pretty widespread pain point in the community, so it would be nice to document this as a way to save up a lot of Bulk Redirects and manual effort in setting them up.

### Additional information

This trick of course makes the "This will automatically redirect all of the preview URLs to your _[target location]_." part non-optional, but this is probably fine for most users.

**Comment by kodster28** [comment]
Howdy @Hexstream, that's actually [already noted](https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/how-to/redirect-to-custom-domain.md?plain=1#L26) in the page you listed.

Going to close this out as completed.

**Comment by Hexstream** [comment]
Disagree, the nice trick I am suggesting that page should document is **extremely useful and not obvious at all.**

**Comment by abohossny** [comment]
think you

**Comment by Manouchehri** [comment]
> Disagree, the nice trick I am suggesting that page should document is **extremely useful and not obvious at all.**

I have the same opinion. Spent nearly an hour fiddling with things until I realized I could do this.
