### ISSUE TITLE
AWS SaaS Application changes

### ISSUE THREAD

**Issue by kklapak** [cloudflare/cloudflare-docs#14832]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/saas-apps/aws-sso-saas/

### What changes are you suggesting?

AWS has overhauled their SSO settings UI and our instructions no longer map to the current AWS Dashboard.

### Additional information

Made this commit, haven't opened a pull request yet https://github.com/cloudflare/cloudflare-docs/commit/c1c21d350e978cec73ed833243fbcc66350cd5fa

**Comment by kodster28** [comment]
Feel free to PR it, @kklapak, we'd appreciate the submission!
(feel free to ping me internally if it's sitting there too long)
