### ISSUE TITLE
AI Gateway API

### ISSUE THREAD

**Issue by zqq-nuli** [cloudflare/cloudflare-docs#14836]
### Proposed changes

https://developers.cloudflare.com/ai-gateway/

### Subject Matter

Add, delete, modify and query AI gateway

### Content Location

I don't know whether it is possible to manage my AI gateway through API, so that I can easily add, delete, and query to my existing or future applications.

**Comment by kodster28** [comment]
Yep, at https://developers.cloudflare.com/api/operations/aig-config-list-gateway.

Question... where were you looking before? We have it linked at the top level of the docs + added to the [setup docs](https://developers.cloudflare.com/ai-gateway/get-started/creating-gateway/).... but it sounds like you were searching for somewhere else?

<img width="1296" alt="Screenshot 2024-05-30 at 8 00 09 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/26727299/bc4c8430-4771-4e8e-85d8-8cdf21ebe540">
