### ISSUE TITLE
Bulk Subscription Request for Phishing Reports

### ISSUE THREAD

**Issue by InfosecWyatt** [cloudflare/cloudflare-docs#14842]
### Existing documentation URL(s)

https://developers.cloudflare.com/email-security/reporting/phish-reports/

### What changes are you suggesting?

Currently, if you want to subscribe users to receive weekly/daily phishing reports, you would add them one by one.

I suggest that you add an option to bulk add a subscriber list via CSV or txt.

**Comment by kodster28** [comment]
Howdy @InfosecWyatt, going to close this out since we're a docs repo and this isn't really about the docs (more of a feature request).

I'll forward along to the PM internally though.

**Comment by abohossny** [comment]
احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
