### ISSUE TITLE
Alpha database migration guide inacuracies

### ISSUE THREAD

**Issue by LeviSchuck** [cloudflare/cloudflare-docs#14876]
### Existing documentation URL(s)

https://developers.cloudflare.com/d1/platform/alpha-migration/

### What changes are you suggesting?

In step 4, it references a table named `_cf_KV` in the database dump. It was by a different name in my dump: `d1_kv`. 
If there are multiple table names, maybe updating it to list all variants would be appropriate. The schema was the same as described in step 4.

In step 6, it references a flag `--remote`, for which I receive the following from wrangler.
```
✘ [ERROR] Unknown argument: remote
```

Removing the `--remote` flag allowed me to complete step 6. 
Wrangler has a `--local` flag and not a `--remote` flag in the `wrangler d1 execute <name>` command help text.

**Comment by joshthoward** [comment]
Newer versions of wrangler have the `--remote` argument since storage operations now default to local for safety (see https://github.com/cloudflare/workers-sdk/pull/4930). I'll look and see if there are more name variations for the kv table.

**Comment by elithrar** [comment]
For clarity, `wrangler@3.33.0` or later is required (released 2024-03-12) per https://developers.cloudflare.com/d1/platform/changelog/#change-in-wrangler-d1-execute-default

We'll add a note to the docs to catch anyone still on a older version of wrangler.
