### ISSUE TITLE
Clarify smart placement and D1 bindings

### ISSUE THREAD

**Issue by brettwillis** [cloudflare/cloudflare-docs#14883]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/configuration/smart-placement/#d1

### What changes are you suggesting?

The [docs](https://github.com/cloudflare/cloudflare-docs/blob/e06c9df3b34f835be13d1e7ca20220f78476e38c/content/workers/configuration/smart-placement.md?plain=1#L38) state:

> Workers with a D1 binding will always be placed in a data center near the location of the D1 database they are bound to. Subrequests to other back-end services are ignored by Smart Placement in this case.

It is unclear if "always" in this case means *always when Smart Placement is on* or just plain *always* (with or without smart placement). Can you clarify if the worker is always colocated with the D1 binding regardless if smart placement is configured? Or is it only colocated with the D1 binding when smart placement is on?

Furthermore, does the "one percent (1%) of requests are not routed with Smart Placement" still apply when a D1 binding is forcing the placement?

**Comment by gshirescf** [comment]
cc: @harshil1712

**Comment by Oxyjun** [comment]
The whole chapter is going through edits, this is now being tracked here: https://github.com/cloudflare/cloudflare-docs/pull/16697

**Comment by Oxyjun** [comment]
Relevant PR has been merged, closing this issue.
