### ISSUE TITLE
Login is impossible

### ISSUE THREAD

**Issue by ICT-Ronco** [cloudflare/cloudflare-docs#14904]
### Example URL(s)

https://dash.cloudflare.com/login

### Actual Behavior

The captcha challeng isn't showing up and I can't verify so I cannot log in 
![image](https://github.com/cloudflare/cloudflare-docs/assets/75335334/51faa32d-0df8-4b1e-bbc8-e80c83d14298)

### Expected Behavior

A captcha challenge appearing

**Comment by kodster28** [comment]
Howdy @ICT-Ronco, I'll forward along to our dash engineering team... but closing this out as it's unfortunately outside of the scope of our team's abilities (we're a docs repo).
