### ISSUE TITLE
Is brotli compression already gone?

### ISSUE THREAD

**Issue by xuhdev** [cloudflare/cloudflare-docs#14941]
### Existing documentation URL(s)

https://developers.cloudflare.com/speed/optimization/content/brotli/enable/

### What changes are you suggesting?

Remove or update steps to configure. I already can't see the brotli compression option by following the instructions.

### Additional information

Seems like it should be there based on a PR a couple of days ago: #14848

cc @ngayerie

**Comment by angelampcosta** [comment]
The page has been updated with https://github.com/cloudflare/cloudflare-docs/pull/15294
