### ISSUE TITLE
Cloudflare Tunnel Firewall missing IP

### ISSUE THREAD

**Issue by fredtj** [cloudflare/cloudflare-docs#14949]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/tunnel-with-firewall/

### What changes are you suggesting?

Remove `198.41.200.3` from `region2.v2.argotunnel.com`, as that address doesn't get returned in a DNS lookup
Add `198.41.200.33` to `region2.v2.argotunnel.com`, as that address does get returned in a DNS lookup, but isn't currently present in the documentation

**Comment by ranbel** [comment]
Thanks for flagging! This is indeed a typo.
