### ISSUE TITLE
APO Configuration Rule Reference & ZTNA

### ISSUE THREAD

**Issue by m8hu** [cloudflare/cloudflare-docs#14942]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/#product-compatibility
https://developers.cloudflare.com/rules/configuration-rules/
https://developers.cloudflare.com/rules/configuration-rules/settings/

### What changes are you suggesting?

Documentation Suggests that a rule can be used to turn off APO for a selfhosted Zerotrust APP url. (as is true for Zaraz & Automatic Signed Exchanges). However when going to documentation for rules, and rules setup itself, APO is not an option to turn off. 

If APO is entirely incompatible with Zero Trust, please update documentation to confirm on APO and on self hosted apps. 
If APO is compatible with specifically set rule, please add documentation on how to control APO into the configuration rule settings.

**Comment by ranbel** [comment]
Thanks for opening this issue! I've confirmed that APO cannot be disabled using a configuration rule.
