### ISSUE TITLE
Some Workers AI examples use outdated types

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#14967]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers-ai/models/llama-3-8b-instruct/ and many others

### What changes are you suggesting?

Many of the AI examples still use the following for their types:
```ts
export interface Env {
  AI: any;
}
```

![](https://i.james.pub/file/2024/06/e49a0569-d2db-4863-bf17-5bf1d3cc60f9.png)

This should instead be:
```ts
export interface Env {
  AI: Ai;
}
```

which will result in a much better developer experience.

**Comment by kodster28** [comment]
Thanks for flagging, @Cherry.

I'll push up a fix soon!
