### ISSUE TITLE
Documentation Prefixes (BYOIP)

### ISSUE THREAD

**Issue by schiederme** [cloudflare/cloudflare-docs#150]
Hey,
I notices multiple Prefixes on the BYOIP Docs to be none Cloudflare ones.

Maybe update them to Documentation Prefixes or Cloudflare owned.

For example 

- 162.211.156.0/24
- 1.2.3.4/24

**Comment by KimJ15** [comment]
Great suggestion @schiederme. We are actually working on strategies related to presenting consistent examples, so I will share your post with the team. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
