### ISSUE TITLE
About the sample code in d1-and-remix.md

### ISSUE THREAD

**Issue by aozou99** [cloudflare/cloudflare-docs#15016]
### Existing documentation URL(s)

- https://developers.cloudflare.com/d1/examples/d1-and-remix/

### What changes are you suggesting?

The `context.env as Env` part of the sample code below would not have worked in my environment unless it was `context.cloudflare.env as Env`

I assume that the version upgrade of one of the cloudflare libraries is probably affecting this, so please include the correct sample code for each version.

```
export const loader: LoaderFunction = async ({ context, params }) => {
  let env = context.env as Env;

  let { results } = await env.DB.prepare("SELECT * FROM users LIMIT 5").all();
  return json(results);
};
```

_package.json_
``` 
        "@remix-run/cloudflare": "^2.9.2",
        "@remix-run/cloudflare-pages": "^2.9.2",
        "@cloudflare/workers-types": "^4.20240605.0",
        "wrangler": "^3.60.0"
```

**Comment by Oxyjun** [comment]
@harshil1712 could you help me with this one?

**Comment by harshil1712** [comment]
Hey @aozou99, thank you for reporting this. Looks like it was already fixed!
