### ISSUE TITLE
Would like to add Chinese documents！

### ISSUE THREAD

**Issue by haoxiaoyueh** [cloudflare/cloudflare-docs#15057]
### Proposed changes

https://developers.cloudflare.com/

### Subject Matter

The existing documents only have one language, and the results of machine translation cannot express the intended meaning. So I hope to add Chinese language for more people to understand.

### Content Location

https://developers.cloudflare.com/

**Comment by kodster28** [comment]
Howdy @haoxiaoyueh, unfortunately multi-language support isn't on our immediate roadmap. In the interim, you might try Google Translate or another tool.
