### ISSUE TITLE
Sentry integration Docs

### ISSUE THREAD

**Issue by oscar-corredor** [cloudflare/cloudflare-docs#15052]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/observability/sentry-integration/

### What changes are you suggesting?

this integration is not available in the integrations tab of workers as shown below: 
![image](https://github.com/cloudflare/cloudflare-docs/assets/1540961/d7a2f2bd-906b-4eb8-97e8-48e213e17db8)

If it was removed/disabled the docs should be updated. If that's not the case then the Integrations tab has a bug where it is not showing all the available integrations.

**Comment by irvinebroque** [comment]
@oscar-corredor — I think this is the case because you are viewing this pages from a Cloudflare Pages project, and the Sentry integration is not supported in Cloudflare Pages today (only Workers)

Agree we can make this less confusing though, really appreciate the feedback

**Comment by jLynx** [comment]
Just came to say the same thing. I assumed it was broken since it wasn't showing up
