### ISSUE TITLE
Add instructions to install the CA certificate for Docker

### ISSUE THREAD

**Issue by lucasan1** [cloudflare/cloudflare-docs#15060]
### Proposed changes

- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/install-cloudflare-cert/

### Subject Matter

Instructions for Docker

### Content Location

A new section under "add-the-certificate-to-applications" listed here: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/install-cloudflare-cert/#add-the-certificate-to-applications

### Additional information

Docker is a widely used technology that by default will not work when TLS inspection is enabled, and require configuration steps to add Cloudflare CA certificate and make it works. As it's very popular, would be nice to have instruction to make the setup work for Docker along the other applications already listed in the page.
Thank you

**Comment by maxvp** [comment]
Closed to track internally. Thanks for the report!

**Comment by maxvp** [comment]
Tracking here: #17783
