### ISSUE TITLE
f string in Text Embeddings Doc Missing 'f' for AUTH_TOKEN constant

### ISSUE THREAD

**Issue by MAhmadW** [cloudflare/cloudflare-docs#15174]
### Existing documentation URL(s)

(All Python AI text embeddings examples)
https://developers.cloudflare.com/workers-ai/models/bge-small-en-v1.5/
https://developers.cloudflare.com/workers-ai/models/bge-base-en-v1.5/
https://developers.cloudflare.com/workers-ai/models/bge-large-en-v1.5/

### What changes are you suggesting?

Simply add f in this line:
  `headers={"Authorization": "Bearer {AUTH_TOKEN}"},`
so that it is:
  `headers={"Authorization": f"Bearer {AUTH_TOKEN}"},`
otherwise, the bearer takes '{AUTH_TOKEN}' as a string literal, leading to faulty auth

### Additional information

This is a pretty small issue, just don't want any beginners to end up scratching their head in confusion :) 
TIA!

**Comment by kodster28** [comment]
Thanks for the find + suggestion, @MAhmadW. Definitely agree it could trip up some newer folks.
