### ISSUE TITLE
www not redirecting to non-www

### ISSUE THREAD

**Issue by jrroofinglancs** [cloudflare/cloudflare-docs#15215]
### Example URL(s)

When trying to access my website via www.jrroofinglancs.co.uk it is appearing as not secure.

### Actual Behavior

It is appearing as not secure and not directing to non-www site.

### Expected Behavior

It should direct to https://jrroofinglancs.co.uk/

### Additional information

Page rule is set up in cloudflare. A records are both pointing to same IP. Your help would be much appreciated.

**Comment by kodster28** [comment]
Howdy @jrroofinglancs, we can't provide technical support here (it's a repo for our docs).

You might want to take a look at [our doc on this issue though](https://developers.cloudflare.com/fundamentals/setup/manage-domains/manage-subdomains/#set-up-redirects).

If that doesn't help, I'd encourage you to instead reach out in the [Cloudflare Community](https://community.cloudflare.com) or [Discord](https://discord.cloudflare.com).
