### ISSUE TITLE
Workers AI example scripts not functioning as expected

### ISSUE THREAD

**Issue by cheike569** [cloudflare/cloudflare-docs#15255]
### Example URL(s)

https://dash.cloudflare.com/xxxxxxxx/ai/workers-ai

### Actual Behavior

Clicking on any kind of Template, for example the "Build and deploy a Llama 2 Worker", will only reveal a page with a "Hello World" worker example.

![Screenshot 2024-06-21 at 9 43 49 PM](https://github.com/cloudflare/cloudflare-docs/assets/244036/1cf68e64-c102-4b64-bcc6-a683897bc986)

Clicking on "Build and deploy a Llama 2 Worker"

![Screenshot 2024-06-21 at 9 43 53 PM](https://github.com/cloudflare/cloudflare-docs/assets/244036/abed82c8-5fde-4ed0-81ed-96f1338ef4f1)

### Expected Behavior

The correct template should load, in this case a Llama 2 worker script

**Comment by kodster28** [comment]
Howdy @cheike569, thanks for raising!

Forwarding this along internally to our dashboard team to investigate.
