### ISSUE TITLE
https://alasemadecoor.com/

### ISSUE THREAD

**Issue by alasemahdekoor** [cloudflare/cloudflare-docs#15264]
### Example URL(s)

store 
https://alasemadecoor.com/
error
https://embade.alldaychat.com/
![error](https://github.com/cloudflare/cloudflare-docs/assets/173619714/4cfd03a9-7008-4569-ab00-462ea72e1fbe)

### Actual Behavior

Error 522 occurs when Cloudflare times out contacting the origin web server. Two different timeouts cause HTTP error 522 depending on when they occur between Cloudflare and the origin web server:

Before a connection is established, the origin web server does not return a SYN+ACK to Cloudflare within 15 seconds of Cloudflare sending a SYN.
After a connection is established, the origin web server doesn’t acknowledge (ACK) Cloudflare’s resource request within 90 seconds.
Resolution

Contact your hosting provider to check the following common causes at your origin web server:

(Most common cause)  Cloudflare IP addresses are rate limited or blocked in .htaccess, iptables, or firewalls. Confirm your hosting provider allows Cloudflare IP addresses.
An overloaded or offline origin web server drops incoming requests.
Keepalives are disabled at the origin web server.
The origin IP address in your Cloudflare DNS app does not match the IP address currently provisioned to your origin web server by your hosting provider.
Packets were dropped at your origin web server.
If you are using Cloudflare Pages, verify that you have a custom domain set up and that your CNAME record is pointed to your custom Pages domain.

If none of the above leads to a resolution, request the following information from your hosting provider or site administrator before contacting Cloudflare support:

### Expected Behavior

The store is running slow

https://github.com/cloudflare/cloudflare-docs/assets/173619714/e8804f21-7b92-439f-88ed-492fe16e0880

### Additional information

![error](https://github.com/cloudflare/cloudflare-docs/assets/173619714/a2fcf513-c15e-4344-8104-901ed2e60fcb)

https://github.com/cloudflare/cloudflare-docs/assets/173619714/ff988a41-13d5-49e2-8921-776ca1735a0a

**Comment by kodster28** [comment]
Howdy @alasemahdekoor, we can't do much on this end because this is a documentation repo.

I'd encourage you to reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or the [Cloudflare Community](https://community.cloudflare.com/) about your problem.
