### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Iannonesonoio** [cloudflare/cloudflare-docs#15262]
### Example URL(s)

Scanned.page/665300c6bae21

### Actual Behavior

Il codice qr non funzione mi da error 502, mi servirebbe che sto lavorando 

### Expected Behavior

Se é possibile ripristinare il sistema il prima possibile 

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/148378548/0c642f96-7c6e-4df7-a448-9721d6b9ea46)

**Comment by abohossny** [comment]
very good work
