### ISSUE TITLE
Unable to cancel subscription from Pro Plan

### ISSUE THREAD

**Issue by quantumexchange8** [cloudflare/cloudflare-docs#15272]
### Example URL(s)

luckyantfxasia.com

### Actual Behavior

Unable to cancel subscription from Pro Plan

### Expected Behavior

Unable to cancel subscription from Pro Plan

**Comment by kodster28** [comment]
Howdy @quantumexchange8, you might want to check out [this resource](https://developers.cloudflare.com/fundamentals/subscriptions-and-billing/change-plan/) for more info about changing your plan.

If that doesn't work, i'd encourage you to reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or the [Cloudflare Community](https://community.cloudflare.com/) about your problem.
