### ISSUE TITLE
my website is not working

### ISSUE THREAD

**Issue by Juan33j** [cloudflare/cloudflare-docs#15278]
### Example URL(s)

https://recoveryfunds.info

### Actual Behavior

it doesn't work

### Expected Behavior

All I need is to have my potential client read this page

**Comment by kodster28** [comment]
Howdy @Juan33j, we can't do much on this end because this is a documentation repo.

I'd encourage you to reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or the [Cloudflare Community](https://community.cloudflare.com/) about your problem.
