### ISSUE TITLE
Unable to subscribe for R2 for enterprise

### ISSUE THREAD

**Issue by Zero-dump** [cloudflare/cloudflare-docs#15279]
### Example URL(s)

https://dash.cloudflare.com/api/v4/accounts/9b4c5e4b64a462a6f82668290471d56f/bulk/subscriptions

### Actual Behavior

I am attempting to subscribe to the R2 service for our enterprise account (ID: 9b4c5e4b64a462a6f82668290471d56f) on TuneIn.com. However, I am encountering a 500 Internal Server Error with the following payload:

{subscriptions: [{rate_plan: {id: "r2_ent_paygo"}, frequency: "monthly", component_values: []}]}
subscriptions
: 
[{rate_plan: {id: "r2_ent_paygo"}, frequency: "monthly", component_values: []}]
0
: 
{rate_plan: {id: "r2_ent_paygo"}, frequency: "monthly", component_values: []}
component_values
: 
[]
frequency
: 
"monthly"
rate_plan
: 
{id: "r2_ent_paygo"}
id
: 
"r2_ent_paygo"

I am aware of the current issues related to subscription payments as mentioned on Cloudflare's status page (https://www.cloudflarestatus.com/). Could this error be associated with those issues? If so, could you please provide an estimated timeline for resolving this problem? Is there an alternative way to access the service in the meantime?

For your reference, I have verified that the payment
<img width="745" alt="Screenshot 2024-06-24 at 15 30 01" src="https://github.com/cloudflare/cloudflare-docs/assets/67919239/f47e9f46-8c07-4072-8adf-3f95b193e0e3">
 data is correctly specified. Additionally, I successfully subscribed to the R2 service using my personal account (1409verona@gmail.com) last Friday.

I have attached all relevant screenshots for your review.

Thank you for your assistance.
<img width="1108" alt="Screenshot 2024-06-24 at 15 29 38" src="https://github.com/cloudflare/cloudflare-docs/assets/67919239/44459881-07e0-4a44-aba5-bca6a700b7c9">

### Expected Behavior

be able to subscribe

**Comment by kodster28** [comment]
Howdy @Zero-dump, apologies for re-routing you here, but you should really reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) for this issue.

This repo tracks issues about documentation... and we really don't have much ability to update the dashboard or investigate bugs.

I'll also forward along internally, but moving forward with Support would be your best chance at getting this resolved quickly.
