### ISSUE TITLE
Can’t delete a Pages project

### ISSUE THREAD

**Issue by zwezheng** [cloudflare/cloudflare-docs#1528]
### Expected Behavior
Developer is supposed to delete the existing Page project.

### Actual Behavior
When deleting a project, it shows an error 800000. See screenshot.

### Section that requires update
<img width="1761" alt="Pages___Account___Cloudflare_-_Web_Performance___Security" src="https://user-images.githubusercontent.com/1361054/121285962-c57f1880-c911-11eb-836a-d343d248d256.png">

### Additional information
This guy has the same issue.
https://community.cloudflare.com/t/cant-delete-a-cloudflare-pages-project/269166

**Comment by KimJ15** [comment]
👋 Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! I would comment on the community.cloudflare.com for assistance!

**Comment by zwezheng** [comment]
@KimJ15 KimJ15  if you take a look at the **Additional information** You will notice another person has posted the exact same question a month ago, and no one replies. on **community.cloudflare.com** 

If you'd like to close this issue, do you mind sharing the proper channel Pages developers will reply to this bug?
maybe file a support ticket?


https://community.cloudflare.com/t/cant-delete-a-cloudflare-pages-project/269166
<img width="875" alt="Can_t_delete_a_cloudflare_pages_project_-_Developers___Workers_-_Cloudflare_Community" src="https://user-images.githubusercontent.com/1361054/121373289-87b1dc80-c971-11eb-8ae0-9eebf57f1f23.png">
