### ISSUE TITLE
i got blocked for no reason

### ISSUE THREAD

**Issue by Yarahassan1798** [cloudflare/cloudflare-docs#15284]
### Example URL(s)

https://portal.ustraveldocs.com/?language=English&country=Egypt

### Actual Behavior

I was completing my SLS account and I left the page open for a couple of days when I tried to continue today it said I'm blocked and I don't know why, you can check the attached file for the error 

[Attention Required! _ Cloudflare.pdf](https://github.com/user-attachments/files/15957337/Attention.Required._.Cloudflare.pdf)
said

### Expected Behavior

it should direct me to the next page

**Comment by kodster28** [comment]
Howdy @Yarahassan1798, unfortunately there's nothing we (as Cloudflare) or specifically this repo (run by our docs team) can do to help with your issue.

Your best bet is to reach out to the site owner letting them know that you've been blocked and provide any relevant information to them.
