### ISSUE TITLE
Docs-Getnet

### ISSUE THREAD

**Issue by tweetsakchutanee** [cloudflare/cloudflare-docs#1529]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by KimJ15** [comment]
👋 Thanks for opening this issue but we need more details to take action. I'm going to close it now, but feel free to open a new issue or ask any questions.
