### ISSUE TITLE
cloudflare  登录失败

### ISSUE THREAD

**Issue by manbuyunduan666** [cloudflare/cloudflare-docs#15308]
### Example URL(s)

https://dash.cloudflare.com/two-factor?type=email

### Actual Behavior

登录失败

### Expected Behavior

登录成功

### Additional information

![错误](https://github.com/cloudflare/cloudflare-docs/assets/77819356/eba6fadb-4457-4c31-b976-ae0649a3fc75)

**Comment by kodster28** [comment]
Howdy @manbuyunduan666, unfortunately we can't do much to help you via this docs repo.

I'd encourage you to post in the [Cloudflare Community](https://community.cloudflare.com) to report your issue.
