### ISSUE TITLE
Port issue in Terraform 

### ISSUE THREAD

**Issue by dautovri** [cloudflare/cloudflare-docs#15311]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/deployment-guides/terraform/ 

### Actual Behavior

The script will spin container kennethreitz/httpbin with  port 80 

<img width="1012" alt="Screenshot 2024-06-25 at 11 01 03 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/4597187/8fd2678d-d944-497b-bcee-33b4870b57cd">

However, ingress rules pointing using 8080: 
```
  ingress_rule {
     hostname = "${cloudflare_record.http_app.hostname}"
     service  = "http://httpbin:8080"
   } # pointing on 8080
```
<img width="1021" alt="Screenshot 2024-06-25 at 11 19 19 AM" src="https://github.com/cloudflare/cloudflare-docs/assets/4597187/5ef64204-13c0-4ca2-87da-b539fcabe1ac">

### Expected Behavior

Ingress rules should point on 80 

Like this: 

```
  ingress_rule {
     hostname = "${cloudflare_record.http_app.hostname}"
     service  = "http://httpbin:80"
   } 
```

**Comment by ranbel** [comment]
@dautovri thanks for flagging! The httpbin port was accidentally deleted in https://github.com/cloudflare/cloudflare-docs/commit/34b28d4e4a3649bee67f9722243c52959c8edf23#diff-07120380120146b45b25aa4c293310ab7d45a88e53432d42892c1ca51704cb8aL231.
I've opened a PR to get this fixed.

**Comment by dautovri** [comment]
@ranbel Thank you for a quick fix👍
