### ISSUE TITLE
cloudflare stream video How to close conversion m3u8  Multi bit rate,Keep only the original bitrate of the video

### ISSUE THREAD

**Issue by liushangqing9803** [cloudflare/cloudflare-docs#15310]
### Proposed changes

cloudflare stream video How to close conversion m3u8  Multi bit rate,Keep only the original bitrate of the video

### Subject Matter

cloudflare stream video How to close conversion m3u8  Multi bit rate,Keep only the original bitrate of the video

### Content Location

cloudflare stream video How to close conversion m3u8  Multi bit rate,Keep only the original bitrate of the video

**Comment by liushangqing9803** [comment]
@kodster28 Can you help me answer this question tks

**Comment by Khorous** [comment]
Good 👍👍👍👍

**Comment by liushangqing9803** [comment]
> Good 👍👍👍👍

help

**Comment by kodster28** [comment]
Howdy @liushangqing9803, found a couple of mentions of [bitrate](https://developers.cloudflare.com/search/?q=bitrate&product%5B0%5D=Stream) in our docs that _might_ be helpful.

Other than that, specific questions like this are best suited for either the [Discord](https://discord.cloudflare.com) or [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/).
