### ISSUE TITLE
Ms

### ISSUE THREAD

**Issue by Bridgette40816** [cloudflare/cloudflare-docs#15335]
### Example URL(s)

Cloudfair

### Actual Behavior

Failure! 

### Expected Behavior

Verified if I am human

### Additional information

Failure!

**Comment by kodster28** [comment]
Howdy @Bridgette40816, you may want to check out the guidelines in [this guide](https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#browser-support) that provide a few indications around what might be challenged.

If that doesn't help, I'd encourage you to post in the [Cloudflare community](https://community.cloudflare.com).
