### ISSUE TITLE
Need instructions for existing workers

### ISSUE THREAD

**Issue by rampatra** [cloudflare/cloudflare-docs#15343]
### Existing documentation URL(s)

Doc link - https://developers.cloudflare.com/d1/get-started/

This page lists nicely the steps when creating a worker from scratch but what if someone already has a worker defined and set up and are adding the D1 database to it. What node dependency to add, etc. can be mentioned.

For example, I have a nextjs app set up already and I want to add D1 database to it. So, how shall I do that?

Currently, the below is giving me an error (D1Database not found):
```
export interface Env {
    // If you set another name in wrangler.toml as the value for 'binding',
    // replace "DB" with the variable name you defined.
    DB: D1Database;
}
```

I ran this too `npm install @cloudflare/workers-types @cloudflare/d1` but no luck.

### What changes are you suggesting?

It should contain steps to do for existing worker.

**Comment by Oxyjun** [comment]
This issue will be closed when this PR https://github.com/cloudflare/cloudflare-docs/pull/17923 is merged in.

The PR adds a note to direct users with existing D1 database + Worker to start from step 3.

Note: The steps of adding a D1 database to an existing database is exactly the same as the steps outlined in the page. The specific error above may have originated from the binding name (e.g. "DB") not matching what it's being called in the code itself (e.g. the code will likely have to reference `env.DB`).
