### ISSUE TITLE
Stream Video "download" state clarification

### ISSUE THREAD

**Issue by byu** [cloudflare/cloudflare-docs#1537]
[Stream FAQ](https://developers.cloudflare.com/stream/faq) states that

```
By default, 120 videos can be in the inprogress, queued or downloading state at once. If videos are in error, ready or pendingupload states, they don't count towards this limit.
```

Does the `downloading` state mean that CloudFlare is ingesting the source video, or does it mean that an actual end user-agent is streaming the video?

Confusion arrises because there is an `pendingupload` state as enumerated in the [API Docs](https://api.cloudflare.com/#stream-videos-properties):

```
valid values: pendingupload, downloading, queued, inprogress, ready, error
read only
```

The clarification requested is if the 120 video limit is about the max concurrency of getting videos into CloudFlare's system, or if it's also describing the concurrency limits of serving/streaming videos to the public.

**Comment by marciocloudflare** [comment]
Hello @byu. Sorry for the late reply, but to clarify your question the 120 video limit is about the max concurrency of getting videos into CloudFlare's system. There are no limits for watching or for the amount of people you can have.
