### ISSUE TITLE
_cfuvid cookie shows as Other with description "Description is currently not available"

### ISSUE THREAD

**Issue by tester-squid** [cloudflare/cloudflare-docs#15382]
### Example URL(s)

https://winslowartcenter.com/privacy-policy/ scroll down and click "set your cookie preferences" and then customize to bring up the EU Cookie pop up with the categories available to allow or reject. 

### Actual Behavior

The CookieYes scanner which is used by our GDPR Cookie plugin (WebToffee) identifies cookie _cfuvid as other and no description, but when I googled it, it shows on Cloudflare Docs as necessary for rate limiting. 

### Expected Behavior

The expected behavior is that cookie would appear as necessary if it is necessary.

### Additional information

I don't know how cookie scanners work or how cookies get identified.  EU visitors may reject this cookie.  I don't think it's affecting us negatively, just wanted you to be aware of it in case you are able do something about it.  Thank you, have a good day.

**Comment by kodster28** [comment]
TY for flagging! Raised internally.

**Comment by KimJ15** [comment]
Closing given this has been raised internally with the team
