### ISSUE TITLE
WARP Local Network Exclusion "0 min" behavior

### ISSUE THREAD

**Issue by kei0** [cloudflare/cloudflare-docs#15414]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/warp-settings/#allow-users-to-enable-local-network-exclusion

### What changes are you suggesting?

Setting timer to '0 min' enables the local network exclusion until reconnect and timeout will not happen.
Please add this behavior to the content for administrative perspective.

**Comment by ranbel** [comment]
Thanks for flagging the issue! This was resolved in #15433.
