### ISSUE TITLE
Finding out on what account the money is payed

### ISSUE THREAD

**Issue by jmgranner** [cloudflare/cloudflare-docs#15452]
### Existing documentation URL(s)

I need a way to understand how to find out how to end a subscription. I had many emails and I have tryed them all. How can I find out what account is still active?

### What changes are you suggesting?

Missing info in cloudflare FAQ

**Comment by kodster28** [comment]
Howdy @jmgranner, your best bet might be trying [this process](https://developers.cloudflare.com/fundamentals/setup/account/account-security/login-and-account-issues/#free-pro-and-business-plans).

For any further support, I'd suggest you reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/), as this is a docs repo and our team doesn't have insight into any account info.
