### ISSUE TITLE
Password reset causing 500 error

### ISSUE THREAD

**Issue by liamlabuschagne** [cloudflare/cloudflare-docs#15473]
### Example URL(s)

https://dash.cloudflare.com/password-reset

### Actual Behavior

Both clicking the link in the email (with the reset code in the URL) as well as manually copying the code into the provided input produces this error. I can't reset my password.

![image](https://github.com/cloudflare/cloudflare-docs/assets/83798278/053ec27f-7f1d-459b-b219-0f3ea211157d)
![image](https://github.com/cloudflare/cloudflare-docs/assets/83798278/53ab0589-fa1a-4ebe-8da8-6dae63b5f833)

### Expected Behavior

Password reset should work.

**Comment by kodster28** [comment]
Howdy @liamlabuschagne, I've raised this internally but -- at the moment -- that's sorta all I can do.
(we're a docs team and don't have access / ability to fix any of this)
