### ISSUE TITLE
Pendent

### ISSUE THREAD

**Issue by keysuccess39** [cloudflare/cloudflare-docs#15477]
### Example URL(s)

www.allkindsneakers.com

### Actual Behavior

My website still shows Pendend

### Expected Behavior

Pendent status

### Additional information

Please let me know why still shows pendent
Thanks
Ginette J

**Comment by KianNH** [comment]
Hi there, this repository is for our documentation and we're unable to assist with site issues.

Please contact [Cloudflare support](https://support.cloudflare.com/hc/en-us) for issues like this.
