### ISSUE TITLE
liskportal

### ISSUE THREAD

**Issue by Cryptowoodright** [cloudflare/cloudflare-docs#15480]
### Example URL(s)

https://liskportal.pages.dev/

### Actual Behavior

Application error: a client-side exception has occurred (see the browser console for more information).

### Expected Behavior

link should open properly and fast 

### Additional information

![Uploading Screenshot 2024-07-04 223222.png…]()

**Comment by KianNH** [comment]
Hi there, this repository is for our documentation and we're unable to assist with site issues.

Please contact [Cloudflare support](https://support.cloudflare.com/hc/en-us) for issues like this.
