### ISSUE TITLE
Cloudflare plugin installed with my Wordpress website isn't working

### ISSUE THREAD

**Issue by bwhite8727** [cloudflare/cloudflare-docs#15490]
### Example URL(s)

It just displays a blank grey colored screen when I click on Settings -> Cloudflare within the Dashboard. https://www.wc.engineering/wp-admin/options-general.php?page=cloudflare

### Actual Behavior

would expect plugin to work

### Expected Behavior

I used to be able to clear my cache with this plugin. Also, I don't see where to clear the cache when I login to my Cloudflare account.

**Comment by KianNH** [comment]
Hi there, this repository is for our documentation and we're unable to assist with site issues.

Please contact [Cloudflare support](https://support.cloudflare.com/hc/en-us) for issues like this.
