### ISSUE TITLE
Build more than one product set at a time

### ISSUE THREAD

**Issue by aaron-ruby** [cloudflare/cloudflare-docs#155]
## User story

When contributing to Developer Docs, I want to build more than one product at a time so that

* I can develop content that spans more than one product area.
* I can validate links/navigation across product areas.

**Comment by signalnerve** [comment]
Hey @aaron-ruby, can you detail more what isn't working? AFAIK (@adamschwartz can correct me if I'm wrong) you should be able to run multiple projects by running `npm run develop` in the associated products. Gatsby should be able to pick a new localhost if the default is occupied. I haven't tested myself but generally this pattern works with most Gatsby apps — does it not here?

**Comment by adamschwartz** [comment]
@signalnerve is correct.

**Comment by aaron-ruby-df** [comment]
@signalnerve I didn't realize you could do that and, if so, that you would be able to validate links from one product to another.

Thanks!
