### ISSUE TITLE
Issue with CloudFlare Verification

### ISSUE THREAD

**Issue by maxw2302** [cloudflare/cloudflare-docs#15501]
### Example URL(s)

https://www.titan-airways.com/

https://www.cloudflare.com/en-gb/plans/enterprise/contact/

### Actual Behavior

When trying to access certain websites (e.g the URL in the example above) the verification just goes into an infinate loop and shows an error message reading 'Verification is taking longer then expected. Check your Internet Connection and refresh the page if the issue persists.' And not only that, but the verification issue even happens on a CloudFlare Official website! I cant even make an account for CloudFlare.

### Expected Behavior

Expected Behaviour is just for the website to load up, normally it takes a few seconds (being 4-5 secnds) but recently i cant even verify myself for the CloudFlare website itself!

### Additional information

![image (38)](https://github.com/cloudflare/cloudflare-docs/assets/171327108/62a16e1c-c396-4685-aee8-ae996fcb7967)

**Comment by kodster28** [comment]
Howdy @QuandaleDingl3e, unfortunately that's not something we -- as a documentation team -- can do much to help with.

Your best bet might be raising a topic in the [Cloudflare Community](https://community.cloudflare.com).

**Comment by maxw2302** [comment]
Hey @kodster28, thank you for the reply! I will try reaching out from there.
