### ISSUE TITLE
pnpx instead of pnpm

### ISSUE THREAD

**Issue by mchangrh** [cloudflare/cloudflare-docs#15515]
### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/41e88ae93882448701dee62ccbd3b7045ee6e3f5/content/workers/wrangler/commands.md?plain=1#L92
https://developers.cloudflare.com/workers/wrangler/commands/

### What changes are you suggesting?

```diff
- pnpm
+ pnpx
```

`pnpx` is the pnpm equivalent of `npx`

https://pnpm.io/cli/dlx

**Comment by penalosa** [comment]
Thanks for reporting this, but in this case `pnpm wrangler` is intended. It's an alias for `pnpm exec wrangler`, which will run the Wrangler version you have installed locally in your project, which is what we recommend.
