### ISSUE TITLE
cloudflare中国国内只能使用https，不能用http，翻墙使用国外的网络就支持http和https

### ISSUE THREAD

**Issue by Yhebbd** [cloudflare/cloudflare-docs#15531]
### Example URL(s)

emby.zas.pp.ua

### Actual Behavior

希望能解决

### Expected Behavior

希望能解决

### Additional information

希望能解决

**Comment by kodster28** [comment]
Howdy @Yhebbd, that's not really something we can help with (we're a documentation repo).

You may have better luck posting in the [Cloudflare Community](https://community.cloudflare.com).
