### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bigbob1958** [cloudflare/cloudflare-docs#15542]
### Example URL(s)

https://southwest.fm/summerofgosrq/

### Actual Behavior

looping

### Expected Behavior

to work

**Comment by kodster28** [comment]
Howdy @bigbob1958, unfortunately there's nothing we (as a docs team) or more broadly we (as Cloudflare) can do to help with that.

I'd encourage you to reach out to the site owner to share your experience with them (and provide the Ray ID)
