### ISSUE TITLE
"Using timingSafeEqual" documentation is vulnerable to timing attack

### ISSUE THREAD

**Issue by mastercoms** [cloudflare/cloudflare-docs#15564]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/examples/protect-against-timing-attacks/

### What changes are you suggesting?

The documentation states "Since the time taken to encode the values may reveal the length of our secret value, you should check the length of the strings before encoding."

However, this introduces another timing attack: the timing of the response will be different if the attacker guesses the length of the secret or not. I would suggest encoding with a false secret of the same length of the value given by the attacker, and then comparing timingSafeEqual, but forcing an unauthorized response anyway in case this is a false secret.

**Comment by kodster28** [comment]
Thanks for flagging, @mastercoms.

Opened an internal ticket on this (REVIEW-11306) to get some guidance.
