### ISSUE TITLE
Magic WAN - 3rd party Integrations - Updated health checks

### ISSUE THREAD

**Issue by nmoura-cf** [cloudflare/cloudflare-docs#15569]
### Existing documentation URL(s)

https://developers.cloudflare.com/magic-wan/configuration/manually/third-party/fortinet/

### What changes are you suggesting?

Documentation still is based on the legacy health checks (using the 172.64.240.0 range). New health checks use the tunnel IPs directly.

This causes confusion for customers, who end up creating convoluted PBR setups which are not necessary, while still not getting their health checks to work.

### Additional information

https://wiki.cfdata.org/display/CSUP/Troubleshooting+Magic+Transit+Healthcheck+failures

**Comment by marciocloudflare** [comment]
Addressed in PR-15860 and PR-15878
