### ISSUE TITLE
CF Tunnel docs need update

### ISSUE THREAD

**Issue by brianbienvenu** [cloudflare/cloudflare-docs#1557]
The Tunnel docs show different `config.yml` examples which seem to conflict.
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config
-> https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/connections/connect-apps/configuration/config.md

The example under **Example file** works.

The example under **File location** does not, and throws a warning when run:
> **WRN** The property `hostname` in your configuration is ignored because you configured a Named Tunnel in the property `tunnel` to run. Make sure to provision the routing (e.g. via `cloudflared tunnel route dns/lb`) or else your origin will not be reachable. You should remove the `hostname` property to avoid this warning.

All of the Tunnel documentation could do with a thorough re-reading and update.

Thanks!

**Comment by abracchi-tw** [comment]
Hey @brianbienvenu we've just changed the Config file docs (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file), as well as the structure of the Tunnel docs. Let us know if you have any further feedback. Thanks!

**Comment by uxduck** [comment]
Hey @abracchi-tw, it looks like the `config.yml` schema (keys and values) is **missing**. A link on that page ("Open vim and type in the necessary [keys and values](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file#keys-and-values).") is broken, and this schema is pretty important to configure stuff. I only successfully guessed that the `config.yml` contains a `url` option, but this isn't documented anywhere :).

**Comment by abracchi-tw** [comment]
hi there @ben-xD, thanks for flagging. #3414 should fix the keys and value link to the `Ingress rules` page. As for the `url` option, named tunnels do not need the `url` option to be specified — you can use [ingress rules](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress) to route traffic
