### ISSUE TITLE
Example doesn't actually work

### ISSUE THREAD

**Issue by Ciel-MC** [cloudflare/cloudflare-docs#15585]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/reference/migrate-to-module-workers/#migrate-a-worker

### What changes are you suggesting?

The example migration
```js
export default {
  fetch(request) {
    const base = 'https://example.com';
    const statusCode = 301;

    const destination = new URL(request.url, base);
    return Response.redirect(destination.toString(), statusCode);
  },
};
```
can't be deployed or used because the `fetch` function lacked an `async` keyword, with no further indication of what to change

**Comment by irvinebroque** [comment]
Thanks @Ciel-MC — you can always edit the docs directly by clicking the "edit" button from any page — PRs welcome!

https://github.com/cloudflare/cloudflare-docs/pull/15586

**Comment by KianNH** [comment]
This isn't an issue with the async keyword, that can be left out if you don't need it. It's because an absolute URL is being passed to the URL constructor so `base` isn't used. It just keeps redirecting to itself.

The fix would be making sure we only pass the path, instead of the full `request.url`.

```js
export default {
  fetch(request) {
    const base = "https://example.com";
    const statusCode = 301;

    const source = new URL(request.url);
    const destination = new URL(source.pathname, base);
    return Response.redirect(destination.toString(), statusCode);
  },
};
```
