### ISSUE TITLE
Deploy content to staging environment

### ISSUE THREAD

**Issue by aaron-ruby** [cloudflare/cloudflare-docs#156]
## User story

When submitting or updating a PR -> `master`, I want the option to trigger a build of that content to a staging environment, such as staging.developers.cloudflare.com, so that stakeholders can review rendered content without having to build locally.

* I want the staging environment to build all of the products so that stakeholders can review rendered content/updates in the context of the full Developer Docs site, mirroring the user experience of developers.cloudflare.com.

**Comment by adamschwartz** [comment]
@signalnerve and I have talked about this before. We could add a `staging` branch, and then break apart https://github.com/cloudflare/cloudflare-docs/blob/813e781b43f989e3a419b9060b812539f7946573/.github/workflows/deploy.yml into `deploy-staging.yml` and `deploy-production.yml` which build/deploy from the `staging` and `master` branches respectively. Maybe we could also rename the `master` branch `production` while we’re at it. ❤️

**Comment by adamschwartz** [comment]
We [tried this](https://github.com/cloudflare/cloudflare-docs/commit/f3c2e58e306d35235a9c23fbdb953c9d7865450a) and it works well, but then [decided to revert](https://github.com/cloudflare/cloudflare-docs/commit/087611bebaa2b3f713f59fc9e7a13adfa66b910f) for now to not change the process and keep things simple. We can take another stab at it next week.

**Comment by KimJ15** [comment]
We will work on an updated workflow that is more comprehensive. Not sure this is the right path at this time. Closing PR.
