### ISSUE TITLE
Cloudflare setup for DNS-O-Matic

### ISSUE THREAD

**Issue by airxzen** [cloudflare/cloudflare-docs#15603]
### Existing documentation URL(s)

[Dynamically update DNS records](https://developers.cloudflare.com/dns/manage-dns-records/how-to/managing-dynamic-ip-addresses/)

### What changes are you suggesting?

On Cloudflares [documentation](https://developers.cloudflare.com/dns/manage-dns-records/how-to/managing-dynamic-ip-addresses/#dns-o-matic) on how to setup DNS-O-MATIC, it does not say or imply that there is any setup required on Cloudflares end to have DNS-O-MATIC function. I only found out that there was more when DNS-O-MATIC did not work when I tested it, I then googled it and found more information [here](https://support.opendns.com/hc/en-us/community/posts/115000937008-How-to-set-up-DNS-O-MATIC-for-Cloudflare-and-the-other-way-around-and-a-FritzBox) I feel having information on how to setup DNS-O-MATIC on Cloudflare is important for the user. I believe either adding a link to said forum post or adding how to setup DNS-O-MATIC on Cloudflare to the Documentation will properly assist Cloudflare users.

**Comment by RebeccaTamachiro** [comment]
Thank you for reaching out! I don't have access to the guide you linked but, since this is a third-party, the source of truth should be DNS-O-Matic.
