### ISSUE TITLE
Warp client Linux download links don't work

### ISSUE THREAD

**Issue by n3m6** [cloudflare/cloudflare-docs#15610]
### Example URL(s)

https://pkg.cloudflareclient.com/

### Actual Behavior

Connection timeout while trying to connect to the linux app download website.

### Expected Behavior

It should be available at https://pkg.cloudflareclient.com/

**Comment by kodster28** [comment]
Howdy, this isn't exactly something our team can help with (since we're a docs repo)... but I'll forward along internally.
