### ISSUE TITLE
Portal incorrectly states: “None” means the request was served by the origin.

### ISSUE THREAD

**Issue by ohmanje** [cloudflare/cloudflare-docs#15616]
### Existing documentation URL(s)

https://developers.cloudflare.com/cache/concepts/cache-responses/#noneunknown

https://dash.cloudflare.com/*/analytics/traffic

### What changes are you suggesting?

In the portal at /analytics/traffic it shows this

![image](https://github.com/user-attachments/assets/04a96142-12ff-4c43-8049-0dbb903cb907)

That is incorrect, and should match https://developers.cloudflare.com/cache/concepts/cache-responses/#noneunknown

This can be confirmed by running the URL in Trace where it shows it hits cloudflare i.e. for a 301 redirect that has a status of None

**Comment by angelampcosta** [comment]
@ohmanje thank you for bringing this up. We will update the dashboard accordingly.
