### ISSUE TITLE
Please block on family filter 1.1.1.1 for Families all proxy website like https://www.blockaway.net/

### ISSUE THREAD

**Issue by orionp13** [cloudflare/cloudflare-docs#15625]
### Existing documentation URL(s)

Hi,

It can be great to block https://www.blockaway.net/ and all website like this unblocker and proxie on DNS filter 
1.1.1.1 for Families

It can be bypass to access porn website by using this unblocker

### What changes are you suggesting?

It can be bypass easily

**Comment by orionp13** [comment]
it's not a content edit but a feature request on DNS filter

**Comment by kodster28** [comment]
Howdy @orionp13, I'd encourage you to submit that feedback via the [Investigate](https://developers.cloudflare.com/security-center/investigate/) feature of Security Center w/in your Cloudflare account.

<img width="1012" alt="Screenshot 2024-07-16 at 8 18 20 AM" src="https://github.com/user-attachments/assets/9fea02ca-074e-48f9-b868-5dcaccbf2ced">

Apologies on redirecting you, but we're a docs repo and don't have any ability to change categorizations of what's included in 1.1.1.1 for Families.
