### ISSUE TITLE
Clarify FetchEvent lifecycle for ES modules

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/cloudflare-docs#1564]
### Expected Behavior
I'd expected the [FetchEvent Lifecycle page](https://developers.cloudflare.com/workers/learning/fetch-event-lifecycle) to have some sort of notice or warning about whether the ES modules format for workers supports equivalent functionality.

### Actual Behavior
The current docs provide examples of workers using ES Modules, and suggest they will be the future preferred format for workers (required to use Durable Objects).

The documentation on the [FetchEvent Lifecycle](https://developers.cloudflare.com/workers/learning/fetch-event-lifecycle) is missing any mention of modules, so it's not clear if there exists an equivalent to `waitUntil` when using modules (since modules have no `FetchEvent` object).

### Section that requires update
[FetchEvent Lifecycle](https://developers.cloudflare.com/workers/learning/fetch-event-lifecycle)

refs https://github.com/robertcepa/toucan-js/issues/72

**Comment by kristianfreeman** [comment]
@xortive would you be able to help document this?

**Comment by koeninger** [comment]
@Electroid where did the discussions on documentation of ES modules end up?  I think it makes sense for people to ask @xortive for context, but folks on the team supporting modules probably need to understand them enough to write the documentation.

**Comment by koeninger** [comment]
for the specific question about waitUntil, this is discussed in https://developers.cloudflare.com/workers/cli-wrangler/configuration#modules

**Comment by roselynalan87** [comment]
<a href="https://elearninginfographics.com/elearning-implementation-toolkit-infographic/" title="eLearning Implementation Toolkit Infographic"><img src="https://cdn-infographic.pressidium.com/wp-content/uploads/eLearning-Implementation-Toolkit-Infographic.jpg" alt="eLearning Implementation Toolkit Infographic"></a>
