### ISSUE TITLE
captcha not displaying for me to sign up

### ISSUE THREAD

**Issue by tmalo627** [cloudflare/cloudflare-docs#15668]
### Example URL(s)

https://dash.cloudflare.com/sign-up?pt=f&_gl=1*e0kog6*_gcl_au*MTkzNDc2NDg1Mi4xNzIxMjk1ODc5*_ga*ZWQyYWY1ZTktZWQxZi00MjI0LWIwNTMtYjFmYmRkNzQ2NzFh*_ga_SQCRB0TXZW*MTcyMTI5NTkwOS4xLjEuMTcyMTI5NzQ2Mi4wLjAuMA..

### Actual Behavior

CAPTCHA not displayed on sign up screen
<img width="929" alt="cloudflareNoCaptcha" src="https://github.com/user-attachments/assets/d65a3811-b99a-411e-bde2-79efebcc9363">

### Expected Behavior

CAPTCHA should be displayed on sign up screen

### Additional information

attempted on FireFox, Chrome, and Edge -- same results on all browsers, system info listed below

OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	TIMLAPTOP
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	ASUS Vivobook S 14 S5406MA_S5406MA
System Type	x64-based PC
System SKU	
Processor	Intel(R) Core(TM) Ultra 9 185H, 2500 Mhz, 16 Core(s), 22 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. S5406MA.304, 2/19/2024
SMBIOS Version	3.6
Embedded Controller Version	0.37
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	S5406MA
BaseBoard Version	1.0
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
User Name	TimLaptop\tmalo
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.6 GB
Available Physical Memory	7.63 GB
Total Virtual Memory	18.5 GB
Available Virtual Memory	9.65 GB
Page File Space	2.88 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Audit
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by kodster28** [comment]
Howdy, I'll raise this internally.
(this isn't an issue we can fix as a docs repo though, so it might take a bit)

**Comment by kodster28** [comment]
You may want to try using another browser or reaching out in the [Cloudflare Community](https://community.cloudflare.com) for help.

Closing out this issue b/c there's not much we can do from our side.
(though did flag internally)

**Comment by tmalo627** [comment]
thanks for the reply but i found the issue on my end...   brand new
computer. the automatic time zone setting didnt work for some reason and my
os clock did not match my system clock
