### ISSUE TITLE
problem ios not show site as secure but window and linix showing secure

### ISSUE THREAD

**Issue by AlFink57** [cloudflare/cloudflare-docs#15669]
### Example URL(s)

https://www.livemusicthisway.com
https://www.livemusicthisway.com/Spotlight

### Actual Behavior

problem ios not show site as secure but window and linix showing secure

### Expected Behavior

should be secure on all operating systems

**Comment by kodster28** [comment]
Howdy @AlFink57, unfortunately there's nothing we (as Cloudflare) can do to fix that.

It's really up to the site owner to solve it. If you are the site owner, you might want to try reaching out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or posting a topic in the [Cloudflare Community](https://community.cloudflare.com).
