### ISSUE TITLE
Dashboard order of Rules should match actual Traffic Sequence 

### ISSUE THREAD

**Issue by ohmanje** [cloudflare/cloudflare-docs#15686]
### Existing documentation URL(s)

https://developers.cloudflare.com/ruleset-engine/reference/phases-list/#request-phases
https://dash.cloudflare.com/*/rules/*

### What changes are you suggesting?

The settings for the different Ruleset phases should match the actual order of the phases. The traffic sequence graphic is terrific but the order of the phases under the Rules section in the dashboard isn't aligned. The order from top to bottom should match. 

i.e.  it doesn't make sense to have this 
![image](https://github.com/user-attachments/assets/381b0760-d57a-463b-aa4e-1d35c14cb5c3)

and then not have the settings order match

![image](https://github.com/user-attachments/assets/d41cf1be-fdbd-4dc7-8806-96677348e7ba)

**Comment by kodster28** [comment]
Howdy @ohmanje, we can't exactly solve this request b/c it's not related to our docs per se.

I'll forward along internally, but closing out since there's no work from our side.
