### ISSUE TITLE
Formatting of arithmetic operations

### ISSUE THREAD

**Issue by TKDev7** [cloudflare/cloudflare-docs#15714]
### Existing documentation URL(s)

https://developers.cloudflare.com/style-guide/

### What changes are you suggesting?

While reviewing the style guide, I couldn't find any guidance on formatting arithmetic operations. For example, is it 25/30 or 25 / 30?

**Comment by crwaters16** [comment]
Hi @MrHBS , thanks for flagging! We've added an entry to the style guide to address mathematical operations. To answer your specific question, we recommend using spaces around operators.
