### ISSUE TITLE
My website landing page is displaying blank(white background) after connecting to Cloudflare

### ISSUE THREAD

**Issue by JoeBlackish** [cloudflare/cloudflare-docs#15729]
### Example URL(s)

https://thesun.ng

### Actual Behavior

I connected my website that's hosted on AWS to Cloudflare because I want the website to load faster and have extra layer of security. I did the necessary setup and added the DNS records, and I noticed when trying to access the website, it loads but nothing is displaying, just a white background but one thing I also noticed is that the subdirectories are working, for example, https://thesun.ng/about-us/. I don't know why it's acting that way. 

### Expected Behavior

I'm expecting all pages would display correctly and load time will be x2.

**Comment by kodster28** [comment]
Howdy @JoeBlackish, sorry to redirect you, but this isn't a forum for tech support (it's meant to provide feedback on our docs).

I'd encourage you to reach out to [Cloudflare Support](https://developers.cloudflare.com/support/contacting-cloudflare-support/) or post in the [Cloudflare Community](https://community.cloudflare.com) if you were looking for tech support.
