### ISSUE TITLE
Migrate monorepo to deploy on Pages

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/cloudflare-docs#1574]
We should begin scoping out the work needed to port the entire monorepo into Cloudflare Pages. This will allow us to get deploy previews on PRs (HUGE quality-of-life improvement for reviewing PRs here) as well as allow `_redirect` file support, since [lilredirector](https://github.com/signalnerve/lilredirector) isn't well-suited for monorepos. We currently deploy 100+ Workers to our CF Developers Workers account, which is incredibly hard to manage -- this will effectively remove all of those Workers (unless a product team would like to define their own custom behavior for their docs sites via Workers).

The how is tricky: the best way to do this at the moment is going to be iterating through _each_ product, building them independently<sup>1</sup>, and then concatenating them into a single folder<sup>2</sup>, which can get pushed out to Pages. This may have significant build-time implications, so there may be some improvements we can make to the build script itself or some caching mechanisms to speed it up inside of Pages' build environment. If we can remove the build time limit for our own internal stuff on Pages and let the monorepo build, this could get us on Pages `~now` versus `~much-later`, but could mean sitting around for 1hr+ waiting for deploy previews to show up, but could have big resource implications.

When we get to the point where this is ready to deploy, it may be worth it to coordinate with each team that has `lilredirector` set up, so they can migrate to `_redirects` files -- here's a [probably up-to-date list of lilredirector users in this repo](https://github.com/cloudflare/cloudflare-docs/search?l=TOML&q=REDIRECTS). We'll also need to remove the associated Workers Sites deploy for each product after the initial Pages deploy, too -- happy to volunteer the Pages/Workers docs for that process.

Regardless, this work is IMO very worth doing, both from a feature perspective (deploy previews plz), and from a "let's explore the boundaries of Pages" perspective, so I'm opening this ticket to start the conversation ✌️ 

<sup>1</sup> Pseudo-code for this: "for each `$dir` in `products/*`, run `cd $dir && npm run bootstrap && npm run build`
<sup>2</sup> Pseudo-code: `mv products/*/build/$product-name build/$product_name`, which generates a folder structure containing each product as a directory inside of the root folder

**Comment by 684efs3** [comment]
Any idea when Cloudflare Pages will support monorepos?

**Comment by KimJ15** [comment]
Closing as complete. Here is the PR: https://github.com/cloudflare/cloudflare-docs/pull/3609
