### ISSUE TITLE
Clarification of Web Analytics data processing 

### ISSUE THREAD

**Issue by MerlinMason** [cloudflare/cloudflare-docs#15796]
### Existing documentation URL(s)

- https://developers.cloudflare.com/web-analytics/about/
- https://developers.cloudflare.com/web-analytics/faq/

### What changes are you suggesting?

We're trying to determine from a legal/compliance perspective how we should handle adding the analytics to our marketing site.

I notice the following in the docs:
> Cloudflare Web Analytics does not collect or use your visitors’ personal data.

But it would help if this was expanded upon for clarity.

- How are you defining 'personal data' here? Is this aligned with the GDPR definition?
- Do you collect IP addresses? 
- Is there any sort of device finger-printing?
- Are any cookies (or similar) placed on the users device? 

### Additional information

It seems as though the analytics get automatically initialised without having to wait for user consent. My assumption here is that they've been designed in a way that for legal purposes they don't require consent, however this is a bit vague... I understand the reluctance to offer legal advice but some high level guidance would be helpful here.

**Comment by kodster28** [comment]
Howdy @MerlinMason, guessing that the `What does privacy-first mean?` section of https://blog.cloudflare.com/privacy-first-web-analytics/ help address your questions?

If so, probably makes sense to port that over into our docs as well.

**Comment by MerlinMason** [comment]
Hey @kodster28, thanks for getting back to me! Ahh yes that's very helpful, I hadn't found that blog post... agree that porting over to the docs would be good 😃

**Comment by Le0Developer** [comment]
> How are you defining 'personal data' here? Is this aligned with the GDPR definition?

I think that's answered in the main umbrealla privacy policy for End Users: https://www.cloudflare.com/en-gb/privacypolicy/

> Is there any sort of device finger-printing?

There isn't (I unminified the code and checked myself).

> Are any cookies (or similar) placed on the users device?

Also nope
