### ISSUE TITLE
KV v2 Revalidation

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/cloudflare-docs#15822]
### Existing documentation URL(s)

- [How KV Works](https://developers.cloudflare.com/kv/reference/how-kv-works/)
- Maybe other places?

### What changes are you suggesting?

The *How KV Works* page makes the following statement:
> While reads are periodically revalidated in the background, requests which are not in cache and need to hit the centralized back end can experience high latencies.

This appears to be speaking about a feature of KV v2, background revalidation, which as far as I know, no longer exists(as KV v2 was put on hold). Should this section be removed then, as it is no longer the case?

**Comment by thomasgauvin** [comment]
Hey! (PM for KV here) KV actually does do background revalidation before the cacheTtl is elapsed. I've actually gone through that entire doc, line by line, to sniff out any inaccuracies, and the main nits I could find that might be remnants of KV v2 were https://github.com/cloudflare/cloudflare-docs/pull/15832

**Comment by helloimalastair** [comment]
Thanks for clarifying!
