### ISSUE TITLE
Enroll via the CLI guide is using obsoleted commands

### ISSUE THREAD

**Issue by Le0Developer** [cloudflare/cloudflare-docs#15829]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/manual-deployment/#enroll-via-the-cli

### What changes are you suggesting?

Running the 3rd step yields this deprecation warning:
```sh
$ warp-cli teams-enroll xxx
NOTICE:

Your organization is using Cloudflare for Teams, a security platform that makes
connections to the Internet and applications faster and safer.

What information is available to administrators of my organization?

The following information may be viewed by administrators from your
organization:

* the websites you visit
* the times you visited them

More information is available at:
- https://www.cloudflare.com/application/terms/
- https://www.cloudflare.com/application/privacypolicy/

Accept Terms of Service and Privacy Policy? [y/N] y

Warning: The "teams-enroll" command will be deprecated in a future release. Please use "registration initialize-token-callback" instead
```
^ last line

**Comment by stuart-c-moore** [comment]
using version `2024.9.346.0`, the `teams-enroll` command no longer exists, yet is still referenced by the documentation.

```shell
$ warp-cli teams-enroll
error: unrecognized subcommand 'teams-enroll'

Usage: warp-cli [OPTIONS] <COMMAND>

For more information, try '--help'.
```

**Comment by ranbel** [comment]
Thanks for opening/updating this issue. We are tracking this work in an internal ticket (PCX-14001).

**Comment by pfan94** [comment]
> using version `2024.9.346.0`, the `teams-enroll` command no longer exists, yet is still referenced by the documentation.
> 
> ```shell
> $ warp-cli teams-enroll
> error: unrecognized subcommand 'teams-enroll'
> 
> Usage: warp-cli [OPTIONS] <COMMAND>
> 
> For more information, try '--help'.
> ```

same there

**Comment by gatesry** [comment]
Also https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/ references `warp-cli account` and `warp-cli delete` which is also not recognized. Let me know if I need to open a separate issue for this.

![CleanShot 2024-10-11 at 15 06 06@2x](https://github.com/user-attachments/assets/4add1dd0-7de2-4cc6-bf75-ba218ba9111b)

**Comment by ranbel** [comment]
> Also https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/ references `warp-cli account` and `warp-cli delete` which is also not recognized. Let me know if I need to open a separate issue for this.

No need to open a separate issue -- we are in the process of removing these commands from the WARP Connector setup procedure (#16486).

**Comment by toby-j** [comment]
Replacement as far as I can tell for `wrap-cli teams-enroll` is `warp-cli registration new <team name>`

> user:~$ warp-cli registration
> Registration settings
> 
> Usage: warp-cli registration [OPTIONS] <COMMAND>
> 
> Commands:
>   show          Show information about the current registration
>   **new           Register this client (Must be run before first connection!)**
>   delete        Delete current registration
>   organization  Get the name of the current Teams organization
>   devices       Display the list of devices associated with the current registration
>   license       Attach the current registration to a different account using a license key
>   help          Print this message or the help of the given subcommand(s)
