### ISSUE TITLE
Green-power.vip Gambia Ltd

### ISSUE THREAD

**Issue by toyboyhd** [cloudflare/cloudflare-docs#15843]
### Example URL(s)

www.green-power.vip](url)

### Actual Behavior

error 522

### Expected Behavior

app and url should link directly to the login page and all functions should be in progress

### Additional information

_we are locvated in the _Gambia west africa __

**Comment by toyboyhd** [comment]
we highly anticipate your co-operation

**Comment by kodster28** [comment]
Howdy, we can't do much here as we're a docs repo.

You might have more success posting about this in the [Cloudflare Community](https://community.cloudflare.com).
