### ISSUE TITLE
Webister not opend

### ISSUE THREAD

**Issue by sachinacharyaa** [cloudflare/cloudflare-docs#15844]
### Example URL(s)

https://sachin-acharya.com.np

### Actual Behavior

This site can’t be reachedCheck if there is a typo in sachin-acharya.com.np.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN 

### Expected Behavior

website should be open

**Comment by kev-ac** [comment]
This is not a support channel. Please contact Support or join the [Cloudflare Discord](https://discord.cloudflare.com/).
