### ISSUE TITLE
"Tooltip" / Overlays are unreadable on Safari (macOS)

### ISSUE THREAD

**Issue by kev-ac** [cloudflare/cloudflare-docs#15852]
### Example URL(s)

ex.:
- https://developers.cloudflare.com/r2/pricing/

### Actual Behavior

The overlay is hidden behind the next content block on macOS Safari. 
On Chrome the content block becomes scrollable, which is also not optimal but usable. 

### Expected Behavior

The content should be visible

### Additional information

https://github.com/user-attachments/assets/7bd1cc40-7487-41e3-82f5-b1d5625f8d12

System: 
Safari 17.5 (19618.2.12.11.6)
macOS 14.5

**Comment by kodster28** [comment]
These should be removed, btw.

Apologies for the radio silence on the issue before this, as well.
