### ISSUE TITLE
Markdown not recognised with AI Assistant, Cursor

### ISSUE THREAD

**Issue by davidwrossiter** [cloudflare/cloudflare-docs#15895]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/ai/

### What changes are you suggesting?

AI Assistant, Cursor, does not render markdown correctly. It renders the markdown syntax instead of what should be displayed, for example it renders bold text like this \*\*this is bold text** instead of **this is bold text**.

### Additional information

Relevant screenshots 

<img width="966" alt="Screenshot 2024-07-30 at 21 05 58" src="https://github.com/user-attachments/assets/536e9e1a-5f2b-4449-ad7f-a5ac361d9cbc">
<img width="966" alt="Screenshot 2024-07-30 at 21 06 06" src="https://github.com/user-attachments/assets/23e6f310-9f9b-47c1-8b1b-b06ede9ecadd">

**Comment by KimJ15** [comment]
CC @mhart
