### ISSUE TITLE
SSL.com not being mentioned in CAA records

### ISSUE THREAD

**Issue by arunesh90** [cloudflare/cloudflare-docs#15902]
### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/caa-records/#caa-records-added-by-cloudflare

### What changes are you suggesting?

Hey 👋 

I noticed today in one of my CT transparency emails from Cloudflare that there's a mention of SSL.com being used for backup certificates. However, I do not see SSL.com being mentioned in the 'CAA records added by Cloudflare' section.
Would it be possible to get some clarification on whether SSL.com is being used or not to issue certificates?

![image](https://github.com/user-attachments/assets/4203ad2f-0186-4fa0-8f36-5397e42aac54)

**Comment by vg** [comment]
I am seeing ssl.com being added to my CAA records starting sometime this week. 

```
300    IN    CAA    0 issue "ssl.com"
300    IN    CAA    0 issuewild "ssl.com"
```
