### ISSUE TITLE
Intermittent disconnects

### ISSUE THREAD

**Issue by spookiyu** [cloudflare/cloudflare-docs#15914]
### Example URL(s)

- twitch.tv  (error code 2000)
- Final Fantasy XIV  (error code 90002)

### Actual Behavior

I've been getting random, super brief disconnects. Usual Internet usage isn't affected, only these services that require constant connection, and reconnecting works instantly (unlike if my actual Internet blinks out). It happened three times last night and once this morning — it started before that, but I only just realized these issues are likely connected so I wasn't tracking it.

Honestly I have no idea if Cloudflare is the problem or not yet; it's not frequent enough to test easily... but I'd like to get an idea of whether that sounds possible.

### Expected Behavior

Not disconnecting lol

### Additional information

Probably not that helpful, but just in case it is, here's a video of a disconnect happening https://drive.google.com/file/d/1U5vdB3ufc3rfpszi5kQ4rULoFDvghE7U/view?usp=sharing

**Comment by kodster28** [comment]
Howdy @spookiyu, you might have better luck with this by either reaching out in the [Cloudflare Discord](https://discord.cloudflare.com) or the [Cloudflare Community](https://community.cloudflare.com).

We're just a docs team (and repo), so we don't have much visibility into the performance or troubleshooting related to the broader Cloudflare network.
