### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by Bobetti** [cloudflare/cloudflare-docs#15927]
### Example URL(s)

localhost

### Actual Behavior

Can’t start the cloudflare worker on local machine: getting Uncaught ReferenceError: document is not defined.

I’m developing cloudflare worker which will be interacting with Azure Tables SDK:
https://learn.microsoft.com/en-us/javascript/api/overview/azure/data-tables-readme?view=azure-node-latest

I’m using honojs and typescript. It's definately has nothing to do with honojs. 
Tried the same library on vercel - and everything is working.

In order to connect to Azure Cosmos DB Table API I need to create table client:
`const tableClient = TableClient.fromConnectionString(this.db_connection_string, this.db_tabel_name);`

After adding this code, cloudflare worker can’t start on a local machine after calling ‘npm run dev’ and throws the error:
`[ERROR] service core:user:electro-backend: Uncaught ReferenceError: document is not defined`

![image](https://github.com/user-attachments/assets/0d4367a0-5a3c-418a-97ce-968eb48ef08c)

![image](https://github.com/user-attachments/assets/4091fe68-5e22-42e9-a8b1-1ea1de6956a4)

What’s happening here?

Appreciate the help.

### Expected Behavior

No errors

**Comment by kodster28** [comment]
Howdy @Bobetti, this isn't exactly a support forum (more a space for feedback on our docs).

Your best bet might be reaching out in the [Cloudflare Discord](https://discord.cloudflare.com).
