### ISSUE TITLE
Cloudflare TURNSTILE has ISSUES

### ISSUE THREAD

**Issue by KrowofAgony** [cloudflare/cloudflare-docs#15939]
### Example URL(s)

https://www.titostailgate.com
https://www.valpak.com/food#//
https://app.viralsweep.com/sweeps/full/078d68-183801?framed=1

### Actual Behavior

I have noticed that the turnstile has glitched on several sites that require it. The above are examples of sites that use this. On certain browsers such as Chromium, Vivaldi, and/or Comodo Dragon, this issue is very common. Cloudflare's turnstile (CAPTCHA) is very certain to mark FAILURE every time. 
![2024-07-30 15 06 12 app viralsweep com 0b29aa975a4a](https://github.com/user-attachments/assets/35bdd0d0-ba8e-4308-9aa8-0bb5eba7007c)
![2024-08-01 20 57 32 www valpak com 26f6eb358eb1](https://github.com/user-attachments/assets/131e725a-6c19-4297-bbed-dc75ef1d19d0)

This issue is NOT common among Firefox's Gecko-based engine browsers such as Waterfox, LibreWolf, etc. I would experiment with this issue at your own discretion.

The point being is that I am NOT recommending Cloudflare's TURNSTILE as a solve-all for Google's Recaptcha system. If anything, this makes the experience MUCH WORSE.

### Expected Behavior

I would expect the turnstile to mark this as SUCCESS! It would have a green check mark. This should be happening regardless of what browser one uses.

**Comment by CyebSloth** [comment]
womp womp

https://developers.cloudflare.com/waf/reference/cloudflare-challenges/#supported-browsers

**Comment by kodster28** [comment]
Howdy @KrowofAgony, I can forward along internally.... but as a docs team, we don't have much ability to solve product issues.

Closing this out as it's not something we can fix in our docs.
