### ISSUE TITLE
I have issue in customhost ssl handshake in cloudflare

### ISSUE THREAD

**Issue by Bharathims29** [cloudflare/cloudflare-docs#15944]
### Proposed changes

https://developers.cloudflare.com/ 

### Subject Matter

Issue in cloudflare ,i  have issue in ssl handshake

### Content Location

i host a saas project in cloudflare,one of my user have issue to connect with my custom domain of my site.He get a domain from namecheap.He correctly configure the CName and TxT records.but he have issue in ssl handshake .its still Certificate status : pending validation,Hostname status: active.

**Comment by kodster28** [comment]
Howdy @Bharathims29, you should move a question like this to another [support forum](https://developers.cloudflare.com/support/contacting-cloudflare-support/#methods-of-contacting-cloudflare-support) (we're a docs repo and can't help with product troubleshooting).
