### ISSUE TITLE
I've an Error 525 that I can't solve my self

### ISSUE THREAD

**Issue by ShowtimeProp** [cloudflare/cloudflare-docs#15947]
### Example URL(s)

https://minio.showtimeprop.com, https://s3.showtimeprop.com, https://coolify.showtimeprop.com   

### Actual Behavior

In all of the above sub type A DNS,  says (SSL handshake failed) -  Error code 525 

### Expected Behavior

Show the website correctly on the browsers as it shows on the main page https://showtimeprop.com and on https://cloud.showtimeprop.com

### Additional information

I want to use Cloudflare but I can't resolve this issue myself, please let me know if someone can help me with it even if they have to charge me for it.

**Comment by kodster28** [comment]
Howdy @ShowtimeProp, the closest I can get you would be pointing you to our troubleshooting section on [525 errors](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-525-ssl-handshake-failed).

If that doesn't work, your best bet would be to reach out in the [Cloudflare Community](https://community.cloudflare.com) (this is a docs repo and we can't help with product-specific troubleshooting).

**Comment by ShowtimeProp** [comment]
I've been there already but can't do that myself due to my poor unknowledge about all this, thanks any way I'll have to return to my original DNS where it was working fine.
