### ISSUE TITLE
Minebase.io

### ISSUE THREAD

**Issue by krjc** [cloudflare/cloudflare-docs#15975]
### Example URL(s)

https://app.minebase.io/login

### Actual Behavior

Troubleshooting
Error Code: 600010
RayId: 8ae7045399325c0f
For assistance, please visit Cloudflare's [Help Center](https://developers.cloudflare.com/turnstile/reference/client-side-errors/).
Report a problem
Submitting a report helps us fix bugs in Turnstile.

The widget fails all the time

### Expected Behavior

I would expect your turnstyle captcha to NOT FAIL.  But it does on this website. I am unable to login due to your error.

### Additional information

Also, the form on the website is placed in such a position that I cannot reach the bottom of the form, which is not visible.
Thanks
Ken Christie.

**Comment by krjc** [comment]
My email address is krjchris@gmail.com
Thank you.

**Comment by kodster28** [comment]
Howdy @krjc, there's not much we can do about this as a docs team (they don't give us access to that kinda stuff).

I'd suggest opening up a thread in the [Cloudflare Community](https://community.cloudflare.com).
