### ISSUE TITLE
Dashboard - My Profile - Missing

### ISSUE THREAD

**Issue by kd4e** [cloudflare/cloudflare-docs#15989]
### Example URL(s)

https://developers.cloudflare.com/fundamentals/setup/account/customize-account/communication-preference/

### Actual Behavior

That URL says to go to Dashboard then My Profile but no My Profile option appears there.

### Expected Behavior

Log into the [Cloudflare dashboard](https://dash.cloudflare.com/)
.
Go to My Profile.

**Comment by kodster28** [comment]
Howdy @kd4e, should be on the lefthand side of yoru account page.
![image](https://github.com/user-attachments/assets/51943d46-426f-4007-a2b9-d09557e0a74c)
