### ISSUE TITLE
Stupid App

### ISSUE THREAD

**Issue by dleiland** [cloudflare/cloudflare-docs#15993]
### Example URL(s)

https://taxonline.tarrantcounty.com/

### Actual Behavior

You can click the "Are You Human" box for hours. YES, I've closed browser (Chrome) - as that is your typical excuse for shoddy apps - cleared browser history, added URL to "Accept Cookies" etc. 

### Expected Behavior

I expect with cloud environment to get in within 2 seconds. My bank, credit union meets these criteria daily. And you struggle on a fairly "public" site - county records.

### Additional information

[CloudFlare.docx](https://github.com/user-attachments/files/16501668/CloudFlare.docx)

**Comment by kodster28** [comment]
Howdy @dleiland, unfortunately we can't help with that as we're a docs repo. Sorry that you're experiencing that issue... usually the best place to post about it might be in the [Cloudflare Community](https://community.cloudflare.com).
