### ISSUE TITLE
"Incoming request cf properties" should include information about minimum required plan levels

### ISSUE THREAD

**Issue by cfcloonan** [cloudflare/cloudflare-docs#16]
Reported on Community here, https://community.cloudflare.com/t/incoming-request-cf-properties/199908

I am finding out the correct plan for incoming request cf. I came from this article.

  developers.cloudflare.com

Request · Cloudflare Workers docs
Documentation for Cloudflare Workers, a serverless execution environment that allows you to create entirely new applications or augment existing ones without configuring or maintaining infrastructure.
 
As for the free plan -
I can get

request.cf.asn;
request.cf.colo;

but not city,latitude,longitude,continent,postalCode,metroCode,region,regionCode,timezone,region .
May I know pro plan of cloudflare can give which of these . Thank you.

These fields were typically only available on Business plans and higher

https://web.archive.org/web/20200414104608/https://developers.cloudflare.com/workers/reference/apis/request/ 
 
The current documentation does not mention that any more, however the limitation was not changed, rather the documentation needs updating.

So, Business plans and higher.

**Comment by Electroid** [comment]
Resolved by https://github.com/cloudflare/cloudflare-docs/pull/569
