### ISSUE TITLE
1688

### ISSUE THREAD

**Issue by wozg1688** [cloudflare/cloudflare-docs#1600]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @wozg1688, closing this out b/c there isn't any actionable info in this issue. Feel free to open another issue if you're seeing something though!
