### ISSUE TITLE
export-graphql-to-csv doesn't work

### ISSUE THREAD

**Issue by codesse** [cloudflare/cloudflare-docs#1601]
### Expected Behavior
https://github.com/cloudflare/cloudflare-docs/blob/production/products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md

### Actual Behavior
After inserting the values in the 'complete script' : 
api_email = '[your email here]'
api_token = '[your API token here]'
api_account = '[your account ID here]'

I try the execute the program and get : 

`ValueError: Invalid header name b'Authorization: Bearer'`

It seems that ':' isn't liked by the 'requests' module. If I delete the ':' then I get : 

`{"success":false,"errors":[{"code":9106,"message":"Missing X-Auth-Key, X-Auth-Email or Authorization headers"}]}`

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/analytics/src/content/graphql-api/tutorials/export-graphql-to-csv/index.md

### Additional information
No more info needed

**Comment by nnmalex** [comment]
Fixing the authentication issue in this tutorial leaves the query still not working with `KeyError: 'viewer'` error.

**Comment by victor-perov** [comment]
Thanks for the report, I will have a look.

**Comment by victor-perov** [comment]
I copied the script from **The final script** [part](https://github.com/cloudflare/cloudflare-docs/blob/65db1d09aa4c53b6501125b7764603fa0a60817c/content/analytics/graphql-api/tutorials/export-graphql-to-csv/index.md?plain=1#L229-L360) of the related tutorial as gql2csv.py (see below), replaced creds, and was able to successfully execute it (Darwin, was also able to run it on Debian):
```zh
viktor@machine cloudflare-docs % python3 gql2csv.py 
Successfully exported to network-analytics-2022-08-01-2022-08-08.csv
```

However, I can imagine the script does not catch all errors therefore `KeyError: 'viewer'` might appear. I will check that case later.

**Comment by victor-perov** [comment]
I can't reproduce this issue. Please let us know if you are still seeing it.
