### ISSUE TITLE
Missing Extended DNS error code

### ISSUE THREAD

**Issue by mtillberg** [cloudflare/cloudflare-docs#16050]
### Proposed changes

- https://developers.cloudflare.com/1.1.1.1/infrastructure/extended-dns-error-codes/

### Subject Matter

EDE Code 18

### Content Location

Placed in the table or error codes

### Additional information

I run my own primary nameserver, and I'm having issues with cloudflare reaching my DNS server.  In the responses, I'm seeing occasional "EDE: 18 (Prohibited)" in the responses, usually alongside a EDE: 23 (Network Error) timeout.  I can verify the packets are not being received on my end, so the timeout is reasonable.  However, I can't tell if the Prohibited code is coming from Cloudflare refusing to send the request, or if it's from my ISP refusing the packet.  My secondary DNS is at a third party, so the DNS request eventually gets handled.  It would be good to know in the documentation potential causes for the EDE:18 errors.

```
$ dig @1.1.1.1 inv.kyossystems.com

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> @1.1.1.1 inv.kyossystems.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 28241
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 18 (Prohibited)
; EDE: 23 (Network Error): (72.65.106.158:53 timed out for inv.kyossystems.com A)
```

**Comment by RebeccaTamachiro** [comment]
👋 @mtillberg! Thanks for reaching out. I've checked with the team and we are only forwarding this error from the upstream, so wouldn't have more to add to the docs. You can try and reach out to [community.cloudflare.com](http://community.cloudflare.com/) to ask for help with your specific setup.
