### ISSUE TITLE
Deleting page with 100+build

### ISSUE THREAD

**Issue by ShahinRockstarsIT** [cloudflare/cloudflare-docs#16094]
### Example URL(s)

https://developers.cloudflare.com/pages/platform/known-issues/#delete-a-project-with-a-high-number-of-deployments

### Actual Behavior

```
Error: Authentication error
```

full response:
```
{
	"success": false,
	"errors": [
		{
			"code": 10000,
			"message": "Authentication error"
		}
	]
}
```

### Expected Behavior

Should delete all the builds.

### Additional information

I used the Global API key

**Comment by WalshyDev** [comment]
As mentioned in the guide, you need to use the API token:
> To find your Cloudflare API token, log in to the [Cloudflare dashboard](https://dash.cloudflare.com/), select the user icon on the upper righthand side of your screen > go to My Profile > API Tokens.
