### ISSUE TITLE
'pages' in products are duplicated

### ISSUE THREAD

**Issue by b0unt9** [cloudflare/cloudflare-docs#16131]
### Example URL(s)

https://developers.cloudflare.com/products/?product-group=Developer+platform

### Actual Behavior

Duplicate 'pages' item on Products page
![cap](https://github.com/user-attachments/assets/134dbbd5-9560-4c59-a503-802af7ea946e)

### Expected Behavior

Only one 'pages' item appears on the Products page

**Comment by kodster28** [comment]
Addressed via #16136
