### ISSUE TITLE
Code Highlighting

### ISSUE THREAD

**Issue by ramiy** [cloudflare/cloudflare-docs#1620]
### Section that requires update

Markdown Code Highlight

https://developers.cloudflare.com/docs-engine/reference/markdown#highlight

### Additional information

You currently support `highlight: [5,6,7]`.

Do you support `highlight: [5-7]` ? 

Or multiple lines like `highlight: [5,7,15-20]` ?

I'm missing this data in your docs. Why? because our docs rely on multiple code examples.

It's ok if you don't support this, just mention that in the docs, it will help users make decisions.

**Comment by pedrosousa** [comment]
Hi @ramiy 
Currently, we don't support ranges of row numbers in `highlight`. We've updated the documentation to make this clear.
