### ISSUE TITLE
Cloudflare WARP client evergreen download URL

### ISSUE THREAD

**Issue by jamie-sandbox** [cloudflare/cloudflare-docs#16239]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/#windows

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/#macos

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/hexnode/#windows

### What changes are you suggesting?

Some users (e.g. organisations doing a managed deployment) need an evergreen URL to download the latest version of the WARP zero trust client.

The evergreen URL is needed to configure the application in a configuration management tool, such as Microsoft InTune, SCCM, a PowerShell script, etc.

There seem to be multiple links available and it is not clear which one should be used:

1. `https://1111-releases.cloudflareclient.com/win/latest`

2. `https://1111-releases.cloudflareclient.com/windows/Cloudflare_WARP_Release-x64.msi`

3. `https://www.cloudflarewarp.com/Cloudflare_WARP.msi`

Link #1 is currently referenced in various places and results in a file called `Cloudflare_WARP_xxxxxxxx.msi`. The name of the downloaded file varies depending on the current latest version. This can cause problems for some scripts as they need to know the name of the file in advance.

Link #2 is what I currently use. It gives you `Cloudflare_WARP_Release-x64.msi` with a static file name. However, this link seems to have been removed from the official documentation, so it is not clear if it is still supported? There are still various forum posts suggesting people to use this link, and it ranks highly in Google too.

Link #3 is only referenced on the Hexnode page. The link used to provide a download of an outdated version of WARP, but now it just redirects to the 1.1.1.1 homepage and provides no download at all, meaning that the Hexnode setup does not work.

Please can clarification be provided? We need an evergreen URL like link #2 which works reliably and is officially supported/documented.

**Comment by ranbel** [comment]
Link #1 is the supported link format. We changed the file name from Cloudflare_WARP_Release-x64.msi to Cloudflare_WARP_xxxxxxxx.msi because customers wanted to see which version they were downloading. 

Link #2 is not officially supported. The evergreen URL has been noted as a feature request, but it's unlikely to be prioritized in the near future. We're currently in the process of moving downloads off the App Center to a Cloudflare-hosted solution.

Link #3 is indeed outdated. I've opened an internal ticket (PCX-15032) to update the Hexnode page. Thanks for flagging!

**Comment by ranbel** [comment]
Hi @jamie-sandbox, we now have an evergreen URL for the latest Windows and macOS releases:
https://downloads.cloudflareclient.com/v1/download/windows/ga
https://downloads.cloudflareclient.com/v1/download/macos/ga

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/

**Comment by jamie-sandbox** [comment]
Fantastic, thanks @ranbel :)
