### ISSUE TITLE
.npmrc environment variable syntax error

### ISSUE THREAD

**Issue by safaalai** [cloudflare/cloudflare-docs#1623]
### Expected Behavior
In How To ==> Install Private Packages ==> Custom Registry Endpoints, the Environment 
variables TOKEN_FOR_NPM or TOKEN_FOR_GITHUB should expand correctly.

### Actual Behavior
Environment variables do not expand.

### Section that requires update
https://developers.cloudflare.com/pages/how-to/npm-private-registry#custom-registry-endpoints.

### Additional information
The syntax for the environment variables is wrong.
Update the environment variables from $TOKEN_FOR_NPM and $TOKEN_FOR_GITHUB to 
${TOKEN_FOR_NPM} and ${TOKEN_FOR_GITHUB}  .... notice the addition of squiggly brackets.

**Comment by lukeed** [comment]
Both variations work – what's in the current documentation was deployed via Pages to let me connect to a private registry. That said, I'll update the docs since it looks like npm recommends/prefers the `${VAR}` format.
