### ISSUE TITLE
Image Transformations Via Workers fit and Format have swapped Headers

### ISSUE THREAD

**Issue by theTyster** [cloudflare/cloudflare-docs#16277]
### Proposed changes

The documentation on "fit" and "format" have swapped content/headers.

The .mdx file only shows the Render component, so not sure how to go about making a PR.

### Subject Matter

Fit & Format

### Content Location

https://developers.cloudflare.com/images/transform-images/transform-via-workers/#fit

### Additional information

https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/images/transform-images/transform-via-workers.mdx#fit

**Comment by silto** [comment]
The regression was introduced in https://github.com/cloudflare/cloudflare-docs/pull/16233, the partials of fit and format should be swapped. Also the "fit" partial is missing the details on the various options that were in the docs previously.

**Comment by dcpena** [comment]
Thanks so much for filing this @theTyster and for the additional info @silto. Much appreciated!
