### ISSUE TITLE
Out of date / confusing Pages Hono demo apps

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#16445]
### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-hono-site/#demo-apps

### What changes are you suggesting?

Many of these examples aren't using Pages, and just Workers. Some are using `assets`, while others are using `pages_build_output_dir`. 

It's not clear how/if each of these use Pages, or in some cases, _why_ they use Hono for assets serving (if they do?) which could incur additional fees. Nor is it clear why they use Hono over Pages own Functions routing. Ergonomics? This was a confusion raised in the Developers Discord.

These demos should probably be audited and cleaned up / confusion reduced.

**Comment by yusukebe** [comment]
Hi @Cherry 

Quick response.

As you said, we have to update the Hono document. But for several reasons, we couldn't. 

We - Hono-side- has two types of templates for Cloudflare:

* `cloudflare-workers` - Using Wrangler as a dev server. You can use it via C3.
* `cloudflare-pages` - Using Vite as a dev server. It is not included in C3.

Ideally, I want to add a description using the `cloudflare-pages` template, and it is already created as the PR: https://github.com/cloudflare/cloudflare-docs/pull/15786

That is good, but the fact the C3 does not include the `cloudflare-pages` template has been a blocker for some reason. You can see the comment of [the PR](https://github.com/cloudflare/cloudflare-docs/pull/15786).

Either way, the document is out of date and needs to be updated.
