### ISSUE TITLE
Extend Pages Functions Redirects docs to mention file extensions

### ISSUE THREAD

**Issue by marcelgerber** [cloudflare/cloudflare-docs#16546]
### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/configuration/redirects/#placeholders

### What changes are you suggesting?

Mention support for file extensions in dynamic redirect rules with placeholders, like so:
```
/assets/:name.svg https://static-assets.example.org/svg/:name.svg 301
/assets/:name.png https://static-assets.example.org/png/:name.png 301
/assets/:name https://static-assets.example.org/other/:name 301
```

**Comment by ToriLindsay** [comment]
After consulting with the team, it was determined that this is too much of an edge case to add at this time, but thank you so much for your feedback @marcelgerber and we will certainly add it in the future if we receive additional similar feedback.
