### ISSUE TITLE
Consider adding Astro ViewTransitions for smoother page transitions

### ISSUE THREAD

**Issue by Sillyvan** [cloudflare/cloudflare-docs#16576]
### Example URL(s)

https://developers.cloudflare.com/

### Actual Behavior

Starlights dosent use ViewTransitions by default so every page change will have a loading spinner and the page flashes.

### Expected Behavior

Using the View Transitions API you could make these transitions smooth being a tiny bit nicer on the eye.

### Additional information

Some people were reporting their annoyance with the page flashing. They also referred to it as feeling slower. So i think this might fixes the issue. Unsupported browsers will just see the page as it is now.

https://docs.astro.build/en/guides/view-transitions/

I tested it locally and adding `<ViewTransitions />` to the `Head.astro` file already did the job.

**Comment by KianNH** [comment]
Hey there, thanks for making this issue and already testing it!

Unfortunately, whilst at first glance a simple `<ViewTransitions />` appears to be all it takes, there are some subtle breakages across Starlight currently: https://github.com/withastro/starlight/pull/694#issuecomment-2028715907

We tested it shortly after migrating and had a handful of those issues pop-up, so we're likely to wait until we can dedicate more time to making it work 100% with Starlight.

**Comment by KimJ15** [comment]
Closing this due to the comment above
