### ISSUE TITLE
Wrangler dev --remote command yields error in Browser Rendering Worker with Durable Objects tutorial

### ISSUE THREAD

**Issue by tbrooks007** [cloudflare/cloudflare-docs#16612]
### Existing documentation URL(s)

- https://developers.cloudflare.com/browser-rendering/get-started/browser-rendering-with-do

### What changes are you suggesting?

In section 7,  it instructs the user to `npx wrangler dev --remote` command. When I run this command via the terminal (MacOS Sonoma 14.6.1) it does not work. I get the error in the attached screenshot.

![ErrorScreenshot](https://github.com/user-attachments/assets/6b2e526b-453f-45bf-84f3-ce76622a11bd)

**Comment by kodster28** [comment]
Howdy @tbrooks007, it looks like the error might be with your local certificate setup, as opposed to the tutorial itself?

I'm more on the writing than engineering side, so could be wrong... but `SELF_SIGNED_CERT_IN_CHAIN` sounds like it's not a Wrangler issue per se.

**Comment by kodster28** [comment]
Checked internally with ENG and they validated my assumption. Closing out for now.

**Comment by tbrooks007** [comment]
Thanks responding. Could you please elaborate on what was actually confirmed or why it maybe happening? The issue only happens when I use the `--remote` command. It does not happen otherwise. I am aware of what the error means but it is not clear why it is happening when I use the `--remote` command as it is not happening with any other commands including `wrangler dev`.

**Comment by kodster28** [comment]
@danielgek, any insight into why it might be happening only in this case?

**Comment by danielgek** [comment]
Browser Rendering --remote works a bit different from the the other products, I will discuss this internally

Tho I can't reproduce this on my side, @tbrooks007 any way you can try this on a different machine ? 

I will follow up this once i discuss internally as well

**Comment by tbrooks007** [comment]
The issue was WARP being turned on. When I turned it off and tried again, all is good. Thank you for your help. We can close the ticket.

**Comment by tbrooks007** [comment]
The issue was WARP being turned on. When I turned it off and tried again, all is good. Thank you for your help. We can close the ticket.
