### ISSUE TITLE
Session Affinity page not rendering correctly

### ISSUE THREAD

**Issue by Vortexmind** [cloudflare/cloudflare-docs#16631]
### Example URL(s)

https://developers.cloudflare.com/load-balancing/understand-basics/session-affinity/#cookie

### Actual Behavior

The following template fails to render correctly when referencing an embedded template: https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/load-balancing/understand-basics/session-affinity.mdx

See the error "Syntax error in text"
![image](https://github.com/user-attachments/assets/32c683fb-659d-45d2-bf83-59a60ec8ab56)

### Expected Behavior

Template renders correctly

**Comment by kodster28** [comment]
Mind sharing what browser you're using?

It's rendering for me on Chrome.
