### ISSUE TITLE
Update the Helm Chart Deployment to new API Version

### ISSUE THREAD

**Issue by kasunsjc** [cloudflare/cloudflare-docs#167]
What I see from the Helm chart is the previous version of the deployment 
but now it's deprecated and it should update to apps/v1

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by KimJ15** [comment]
This issue appears to have been opened accidentally. We only take care of developers.cloudflare.com documentation requests in this repo! I'm going to close it now, but feel free to open a new issue or ask any questions.
