### ISSUE TITLE
Load Balancing reference architecture Figure 3 needs correcting

### ISSUE THREAD

**Issue by la-bala** [cloudflare/cloudflare-docs#16733]
### Existing documentation URL(s)

https://developers.cloudflare.com/reference-architecture/architectures/load-balancing/

### What changes are you suggesting?

Figure 3 in the Load Balancing reference architecture doesn't correspond to the text, which shares an example of 25ms x 20 = 500 ms, then 150ms x 20 = 3000 ms.

The figure repeats 25ms and 500 ms twice for both examples.

### Additional information

In the repo the reference architecture page is here:
https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/reference-architecture/architectures/load-balancing.mdx

and specifically the image is this:
https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/reference-architecture/architectures/~/assets/images/reference-architecture/load-balancing-reference-architecture-images/lb-ref-arch-3.svg

**Comment by securitypedant** [comment]
Image fixed.
