### ISSUE TITLE
DLP - Scan for sensitive data - Integrations section should be updated to include other DLP integrations

### ISSUE THREAD

**Issue by cdraper-cloudflare** [cloudflare/cloudflare-docs#16731]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/applications/scan-apps/casb-dlp/#supported-integrations

### What changes are you suggesting?

This page makes it look like DLP only has three integrations when it currently has 15+ integrations.

The "Scan for sensitive data" page should say something like: "DLP supports integrations across 15+ different SaaS applications including Google Workspace, Microsoft 365, and Salesforce, and many others. You can view the full list of integrations here: (link to https://developers.cloudflare.com/cloudflare-one/applications/scan-apps/casb-integrations/).

**Comment by cdraper-cloudflare** [comment]
Now that I'm thinking about it, I'm not 100% sure you can configure a DLP profile for every CASB integration. Maybe there are CASB integrations that don't allow Cloudflare users to add in a DLP profile? I'm still learning about Zero Trust, so it could be worth double checking with the DLP or CASB PM.

If turns out you can configure a DLP profile with every CASB integration, maybe that is also worth mentioning in the Developer Docs.

**Comment by crwaters16** [comment]
Hey Chris - closing this out to keep our issue backlog tidy. Feel free to follow up directly with @maxvp if you have any specific changes or ideas!
