### ISSUE TITLE
"cloudflare warp daemon" error when register the client

### ISSUE THREAD

**Issue by charityAMG** [cloudflare/cloudflare-docs#1688]
Hi, I use xubuntu 18.04. I installed warp client for ubuntu 16.04, I have an error when register the warp client:
```
pc@pc:~/Desktop$ warp-cli register
Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running, or is connected to another process?
```
How to solve it? Thanks.

**Comment by KimJ15** [comment]
👋 @charityAMG Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! Please reach out to community.cloudflare.com for assistance!
