### ISSUE TITLE
Deploy hooks API docs

### ISSUE THREAD

**Issue by pawelhenek** [cloudflare/cloudflare-docs#16969]
### Existing documentation URL(s)

https://developers.cloudflare.com/api/operations/pages-deployment-get-deployments
https://developers.cloudflare.com/pages/configuration/deploy-hooks/

### What changes are you suggesting?

Hello

Just wanted to ask if the is any reason why `Deploy hooks` are not documented in **Cloudflare API docs** and thus there is no cloudflare-go and cloudflare terraform provider support? I mean I'm considering contributing to the library (which version should I start with main or v2?) and then integrate it to terraform provider, but wondering why it's not even documented. Shouldn't be considered as stable so contributions are not good idea?
The endpoint I meant
`https://dash.cloudflare.com/api/v4/accounts/<ACCOUNT_ID>/pages/projects/<PROJECT_NAME>/deploy_hooks`
Thanks in advance

**Comment by haleycode** [comment]
Thanks for the feedback @pawelhenek! I've raised this internally and we're working on it.

**Comment by KimJ15** [comment]
CC @crwaters16

**Comment by crwaters16** [comment]
Hey @pawelhenek, thanks for raising this - we've let the Pages team know this endpoint is missing and are tracking the work to address internally. They'll follow up once this has been handled!
