### ISSUE TITLE
Verified Bot Categories should list possible values for `request.cf.verifiedBotCategory`

### ISSUE THREAD

**Issue by thexeos** [cloudflare/cloudflare-docs#16966]
### Proposed changes

- https://developers.cloudflare.com/bots/reference/verified-bot-categories/#categories

### Subject Matter

String values for `request.cf.verifiedBotCategory` are not declared

### Content Location

Categories section should be updated to include actual string values against which comparison can be made in code.

Workers include a variable `request.cf.verifiedBotCategory` ([docs](https://developers.cloudflare.com/bots/reference/bot-management-variables/#workers-variables)) and there is no way of knowing possible string values.

### Additional information

![image](https://github.com/user-attachments/assets/e21a01a8-1fad-49a1-988c-8c21aa70f706)

Current documentation lists "**Page preview**: Facebook, Slack, Twitter, or Discord Link Preview tools"

Note how "preview" starts with a lowercase "p" in documentation, but it starts with uppercase "P" when reading Worker variable.

**Comment by patriciasantaana** [comment]
Hey @thexeos ! Thank you for bringing this to our attention. We have an internal ticket to track the work on this so I will close it now. If you have any more concerns, please feel free to open another issue.
