### ISSUE TITLE
Limits on  subrequests with Unbound and Bundled worker plans

### ISSUE THREAD

**Issue by flexchar** [cloudflare/cloudflare-docs#16983]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/limits/#subrequests

### What changes are you suggesting?

This page tells about obsolete Unbound and Bundled worker plans, which are now long gone. Therefore it is unclear if my worker on a paid plan is allowed to make 1000 or 50 sub-requests. 

For example,
> The limit for subrequests a Worker can make is 50 per request on the Bundled usage model or 1,000 per request on the Unbound usage model

**Comment by ToriLindsay** [comment]
Thank you for the feedback!
The information has been added here: https://developers.cloudflare.com/workers/platform/limits/#unbound-and-bundled-plan-limits
From https://github.com/cloudflare/cloudflare-docs/pull/17574
