### ISSUE TITLE
Broken link to demo Hyperdrive app

### ISSUE THREAD

**Issue by gregmsanderson** [cloudflare/cloudflare-docs#16992]
### Existing documentation URL(s)

- https://developers.cloudflare.com/hyperdrive/demos/

### What changes are you suggesting?

The [Hyperdrive demo](https://github.com/cloudflare/hyperdrive-demo) link that's on that page 404s. Perhaps that demo app has been deleted.

There does seem to be _this_ demo app: https://hyperdrive-demo.pages.dev/ _but_ that does not link to _its_ repo. Else I'd submit a PR to update that link.

**Comment by KimJ15** [comment]
The link seems to be fixed. I was able to visit https://github.com/cloudflare/hyperdrive-demo without a 404

**Comment by gregmsanderson** [comment]
@KimJ15 Strange. Is that repo private? Perhaps only Cloudflare employees can see it?

I still get a 404:

![hyperdrive-404](https://github.com/user-attachments/assets/afcb7444-95e5-4e1c-b719-42ca71d251fc)

**Comment by pedrosousa** [comment]
@gregmsanderson The repository was in fact private. It is now public.
