### ISSUE TITLE
Wrangler Commands Page - r2 object put links to KV key put anchor

### ISSUE THREAD

**Issue by JFL110** [cloudflare/cloudflare-docs#17006]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/commands/

### Actual Behavior

On the right nav bar, click r2 Object -> put
Left pane scrolls to KV key -> put

### Expected Behavior

Left pane scrolls to r2 object -> put

### Additional information

Just a small UX bug, loving the docs!

**Comment by KimJ15** [comment]
Thanks for submitting this issue. I just tested the right nav and it looks like the anchors are now working as expected.
