### ISSUE TITLE
Update Supported cipher suites 

### ISSUE THREAD

**Issue by renatocron** [cloudflare/cloudflare-docs#17050]
### Existing documentation URL(s)

- https://github.com/cloudflare/cloudflare-docs/edit/production/src/content/docs/ssl/origin-configuration/cipher-suites.mdx
- https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/supported-cipher-suites/

### What changes are you suggesting?

The first page displays cipher names that are not accepted by the API endpoint. The second page includes the IANA name alongside the endpoint cipher name, as well as an improved Security Recommendation column in the table.

**Comment by RebeccaTamachiro** [comment]
Hi @renatocron! Thanks for raising this.
Those are actually two different docs. The first refers to cipher suites used between Cloudflare and origin servers and lives under [Origin server > Cipher suites](https://developers.cloudflare.com/ssl/origin-configuration/cipher-suites/). The second refers to cipher suites used between clients and Cloudflare, as explained in the overview page of the [Edge certificates > Additional options > Cipher suites](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/) section.
