### ISSUE TITLE
Changing redirect settings does not work.

### ISSUE THREAD

**Issue by isec-promotion** [cloudflare/cloudflare-docs#1712]
According this article, I put _redirects file in the build output folder.
[https://developers.cloudflare.com/pages/platform/redirects](https://developers.cloudflare.com/pages/platform/redirects)

Redirects worked fine.

Few day later, I found a mistake in the settings and I corrected it.

But the behavior remained the same.

### Expected Behavior
```
/sample https://www.example.com/sample 301
↓
/sample /sample2 301
```

The redirection will be changed to `/sample2`  instead of `https://www.example.com/sample`.

### Actual Behavior
The redirection did not work and access `https://www.example.com/sample`.

`Changes to redirects will be updated to your website at build time so make sure you commit and push the file to trigger a new build each time you update redirects.`

This is what the documentation says.

Are there any other settings that should be needed?

Or is this behavior a glitch?

**Comment by kristianfreeman** [comment]
@isec-promotion this is intended behavior! Your browser will cache a 301 redirect since a 301 is a "permanent redirect".

**Comment by lukeed** [comment]
[Indeed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) – you can purge your Cloudflare Cache and your local browser cache – but _all_ clients that have seen the `301` will remember that forever (unless forcibly cleared).

You should be using 302 redirects (temporary) unless/until you're confident in the behaviors & destinations.
