### ISSUE TITLE
Update queues status to no longer in beta

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#17179]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/wrangler/commands/#queues

### What changes are you suggesting?

queues is now in GA (https://github.com/cloudflare/workers-sdk/pull/6840). the beta indication should be removed.

**Comment by RamIdeas** [comment]
Done in https://github.com/cloudflare/cloudflare-docs/pull/17180
