### ISSUE TITLE
https://embed.videodelivery.net/embed/sdk.latest.js has error 

### ISSUE THREAD

**Issue by soypaduano** [cloudflare/cloudflare-docs#172]
When using that url to implement the API on my html, it has the following error:

<script src="https://embed.videodelivery.net/embed/sdk.latest.js"></script>

```
Uncaught TypeError: Cannot read property 'src' of null
    at u (sdk.latest.js:1)
    at (index):93

```

**Comment by xtuc** [comment]
is that still an issue? could you please provide a repro?

**Comment by KimJ15** [comment]
Hi there - Please reach out to community.cloudflare.com or support.cloudflare.com for assistance! Closing this PR.
