### ISSUE TITLE
Next.js create-cloudflare command is incorrect for Static Asset Workers

### ISSUE THREAD

**Issue by apeacock1991** [cloudflare/cloudflare-docs#17205]
### Existing documentation URL(s)

[This page](https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/) is wrong, the command doesn't work. It should be `npm create cloudflare@latest my-next-app -- --framework=next --experimental`.

### What changes are you suggesting?

Fixing the command.

**Comment by irvinebroque** [comment]
Thanks @apeacock1991!

https://github.com/cloudflare/cloudflare-docs/pull/17213
