### ISSUE TITLE
Record Tags in Free Plan?

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-docs#17215]
### Existing documentation URL(s)

https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/#record-tags

### What changes are you suggesting?

The current documentation states that record tags are not a feature of the Free Plan. However, my testing indicates that record tags are, in fact, available in this tier! If this is indeed the case, I'd like to confirm any specific limitations that might apply. Could the documentation be updated to reflect the availability of record tags in the Free Plan?

**Comment by hannes-cf** [comment]
Hey @favonia, can you send me your zone name or id to hannes@cloudflare.com please?

**Comment by favonia** [comment]
@hannes-cf Sent.

**Comment by KimJ15** [comment]
Closing this issue out given @hannes-cf has provided next steps.
