### ISSUE TITLE
Copying code block is not working properly

### ISSUE THREAD

**Issue by gprasanth** [cloudflare/cloudflare-docs#1725]
### Expected Behavior

Code in [this page](https://developers.cloudflare.com/workers/examples/cache-using-fetch) should copy code with out messing up new lines. 

### Actual Behavior

New lines are getting lost on copy.

### Section that requires update

Code block rendering needs to be fixed.

### Additional information
Copy
![Screenshot 2021-07-04 at 11 19 20 PM](https://user-images.githubusercontent.com/1318897/124394780-88465480-dd1e-11eb-947b-9cdbb95f0cfd.png)
Paste
![Screenshot 2021-07-04 at 11 21 04 PM](https://user-images.githubusercontent.com/1318897/124394784-8aa8ae80-dd1e-11eb-8f85-5db27bdfb9c4.png)

**Comment by danBamikiya** [comment]
What did you copy that block of code into? @gprasanth

**Comment by gprasanth** [comment]
Added a userscript to fix this for myself. Seems to be due to new line missing while converting a line of code to CodeBlock html elements.

```
Array.from(document.querySelectorAll('.CodeBlock--row-content')).forEach(rowContent => {
    const lastTokenPlain = rowContent.childNodes[rowContent.childNodes.length - 1];
    if (lastTokenPlain.className === "CodeBlock--token-plain" && !lastTokenPlain.innerHTML.endsWith("\n")) {
        lastTokenPlain.innerHTML += "\n";
    }
})
```

**Comment by lostpebble** [comment]
Same issue here- pasting it into anything gives undesired results. The copied clipboard contains no line breaks like is displayed in the docs- as @gprasanth has discovered and fixed with his script, seems to be an issue because the CSS is creating the line-breaks visually, but the raw text on the site actually has none.

**Comment by KimJ15** [comment]
A fix was merged a few days ago! https://github.com/cloudflare/cloudflare-docs-engine/pull/343 Closing this issue.
