### ISSUE TITLE
BUG DOS洪水功击

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#17268]
### Proposed changes

长期对本人PC进行Dos功击IP
104.16.80.230
162.159.137.105
162.159.138.105

### Subject Matter

BUG Dos洪水功击

### Content Location

长期对本人PC进行Dos功击IP

104.16.80.230
162.159.137.105
162.159.138.105

### Additional information

长期对本人PC进行Dos功击IP

104.16.80.230
162.159.137.105
162.159.138.105

**Comment by pedrosousa** [comment]
Hi! This repository is for our documentation only, and we're unable to assist with site issues. You can reach out to the [community](https://community.cloudflare.com/).
