### ISSUE TITLE
Errors in Workers NextJS framework guide

### ISSUE THREAD

**Issue by dan-massey** [cloudflare/cloudflare-docs#17291]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/

### What changes are you suggesting?

In step 2, the final suggested line is:
`experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }`

when it should in fact be
`assets = { directory = ".worker-next/assets", binding = "ASSETS" }`

In step 3, the instructions suggest adding to `package.json` :
> "deploy:worker": "npm run build:worker && wrangler deploy"

But this is later referred to incorrectly twice: 

First in the last bullet immediately following the `package.json` instructions:
>`npm run deploy: Builds your app, and then deploys it to Cloudflare` 

Then again in step 6:
> deploy via the command line:
> Terminal window
> `npm run deploy`

**Comment by mikenomitch** [comment]
@ToriLindsay, since you asked, yep this is a good change.

Let's also look for any other `experimental_assets` references and replace those with `assets` unless its specifically talking about the fact that it used to be experimental.

**Comment by GregBrimble** [comment]
No other references. #18433 should be enough :) Thanks for the report, @dan-massey!

**Comment by ToriLindsay** [comment]
Thank you @mikenomitch @GregBrimble ! I approved.
Tell me if I'm wrong, but I think the second part still needed to be addressed? I created that here #18443 
Can you confirm?
