### ISSUE TITLE
Beta client pictures in gateway docs

### ISSUE THREAD

**Issue by kkrum** [cloudflare/cloudflare-docs#173]
https://developers.cloudflare.com/gateway/connecting-to-gateway/with-client/DNS and https://developers.cloudflare.com/gateway/connecting-to-gateway/with-client/HTTP both show Cloudflare WARP client images with the BETA tag in them. Should be using the production version of the client for screenshots.

**Comment by KimJ15** [comment]
With the update to these docs earlier this year, this issue was resolved. Closing issue.
