### ISSUE TITLE
HTML characters being escaped in table of contents

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#17308]
### Example URL(s)

https://developers.cloudflare.com/workers/configuration/compatibility-dates/#htmlrewriter-handling-of-esiinclude

### Actual Behavior

HTML characters being escaped in table of contents

### Expected Behavior

Don't escape.

### Additional information

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/7efac6d5-b8c1-472a-9b89-7193b446740b">

**Comment by KianNH** [comment]
Fixed by https://github.com/cloudflare/cloudflare-docs/pull/17311
