### ISSUE TITLE
Add Logpush Third-party integration - Taegis

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#17307]
### Existing documentation URL(s)

https://developers.cloudflare.com/logs/get-started/enable-destinations/third-party/

### What changes are you suggesting?

Can we add Secureworks Taegis: https://docs.ctpx.secureworks.com/integration/connectCloud/cloudflare/
in addition to Axiom ?

### Additional information

Cloudflare employee, I don't know how to create a .mdx file.

**Comment by angelampcosta** [comment]
Hi @wolruf sure! I'll follow up on the ticket and tag you once the PR is merged.
