### ISSUE TITLE
D1 cloudflare console reads all rows - billing

### ISSUE THREAD

**Issue by UROjQ6r80p** [cloudflare/cloudflare-docs#17316]
### Proposed changes

According to: https://www.reddit.com/r/CloudFlare/comments/1c2a7im/comment/lotkv63/
```
D1 tracks your actions in the console when you open a table. For example, if your table has 40 million rows, just one click will result in D1 recording 80 million row reads, even though the console page doesn’t display all the data. I couldn’t find a place to set any limits on this.

As a result, I paid $1,300 as “tuition.” When I tried contacting Cloudflare for troubleshooting and assistance, apart from one response telling me the bill was accurate, I’ve heard nothing since—no replies via email, Twitter, or Discord.
```

If it's true it should be documented, and possibly fixed? No one wants to pay huge bill just for looking at console few times. Why is it not limited to x first rows?

### Subject Matter

D1 cloudflare console reads all rows

### Content Location

Anywhere.

**Comment by KimJ15** [comment]
Hi there - this repo is for technical content issues. 
I have passed along your feedback to the appropriate team.
