### ISSUE TITLE
Deploy a static WordPress site WP2Static plugin is still available

### ISSUE THREAD

**Issue by lukecav** [cloudflare/cloudflare-docs#1733]
### Expected Behavior
This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to WP2Static, try Simply Static. WP2Static plugin is closed for downloads on WordPress.org but is still available on their GitHub repo. https://github.com/leonstafford/wp2static
https://staticword.press/t/removal-of-wp2static-from-wordpress-org/159

### Actual Behavior
This tutorial is outdated. As of August 2020, the WP2Static plugin is no longer available. For a free alternative to WP2Static, try Simply Static. 

### Section that requires update
https://developers.cloudflare.com/workers/tutorials/deploy-a-static-wordpress-site At the top of doc

### Additional information
https://github.com/leonstafford/wp2static/releases

**Comment by kristianfreeman** [comment]
@lukecav would you be open to submitting a PR?

**Comment by lukecav** [comment]
@signalnerve K done https://github.com/cloudflare/cloudflare-docs/pull/1776
