### ISSUE TITLE
What is Application object mean?

### ISSUE THREAD

**Issue by kamontat** [cloudflare/cloudflare-docs#17370]
### Existing documentation URL(s)

- https://developers.cloudflare.com/fundamentals/setup/account/account-security/scim-setup/

### What changes are you suggesting?

The step 2 on `Configure user permissions on Okta` section. It's mention about application object, which doesn't have screenshot which application object does it mean. This cause a lot of confusion.

**Comment by patriciasantaana** [comment]
Hi @kamontat! The `application object` in this case is **not** a tab or link to navigate to. 

It is the specific SCIM application that you have created in Okta, where you want to add the user permissions. You can find this in your Okta App Integration Catalog. Clarifying this step in #17779.
