### ISSUE TITLE
Typo on "How Aegis works" page

### ISSUE THREAD

**Issue by ahobbs-cf** [cloudflare/cloudflare-docs#17387]
### Example URL(s)

https://developers.cloudflare.com/aegis/about/

There is a typo in "Cloudflare's global network":

![image](https://github.com/user-attachments/assets/ebe77298-6a8b-4497-856e-f12d31e0b495)

### Actual Behavior

There is a typo

### Expected Behavior

It should be "Cloudflare's global network"

**Comment by ahobbs-cf** [comment]
Have already created - PR https://github.com/cloudflare/cloudflare-docs/pull/17388

**Comment by haleycode** [comment]
Thanks very much!
