### ISSUE TITLE
Can no longer add multiple env variables at once

### ISSUE THREAD

**Issue by sabercoy** [cloudflare/cloudflare-docs#17498]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/configuration/environment-variables/

this states
```8. (Optional) To add multiple environment variables, select Add variable.```

### What changes are you suggesting?

There is now a sidebar that shows up to add **one variable at a time** and no options to add multiple
I would suggest allowing adding multiple

**Comment by markjmiller** [comment]
@sabercoy we just released the new multi-variable component 🎉
