### ISSUE TITLE
Arch - Linux

### ISSUE THREAD

**Issue by Jeiel0rbit** [cloudflare/cloudflare-docs#17543]
### Example URL(s)

- https://developers.cloudflare.com/warp-client/get-started/linux/
- https://pkg.cloudflareclient.com/

### Actual Behavior

The suggestion to download it on Linux doesn't work on 64 bit architecture. Because the suggestion makes the user download 32 bit architecture by default. Even if you tell Linux to work as 64 bit, it won't work correctly as for 32 bit.

### Expected Behavior

It will work or have an option to download 64 bit.

### Additional information

```bash
        `osssssssssssssssssssso`           jeiel@jeiel-pc 
       .osssssssssssssssssssssso.          -------------- 
      .+oooooooooooooooooooooooo+.         OS: Zorin OS 17.2 x86_64 
                                           Kernel: 6.8.0-45-generic 
                                           Uptime: 2 hours, 56 mins 
  `::::::::::::::::::::::.         .:`     Packages: 3182 (dpkg), 39 (flatpak), 
 `+ssssssssssssssssss+:.`     `.:+ssso`    Shell: bash 5.1.16 
.ossssssssssssssso/.       `-+ossssssso.   Resolution: 1920x1200 
ssssssssssssso/-`      `-/osssssssssssss   DE: GNOME 43.9 
.ossssssso/-`      .-/ossssssssssssssso.   WM: Mutter 
 `+sss+:.      `.:+ssssssssssssssssss+`    WM Theme: WhiteSur-Dark 
  `:.         .::::::::::::::::::::::`     Theme: WhiteSur-Dark [GTK2/3] 
                                           Icons: WhiteSur [GTK2/3] 
                                           Terminal: gnome-terminal 
      .+oooooooooooooooooooooooo+.         CPU: Intel Celeron J1800 (2) @ 2.582 
       -osssssssssssssssssssssso-          GPU: Intel Atom Processor Z36xxx/Z37 
        `osssssssssssssssssssso`           Memory: 2194MiB / 3812MiB 
```

**Comment by cf-rhett** [comment]
Zorin OS is not supported. See https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/#linux for a list of the supported Linux distros for WARP.

**Comment by Jeiel0rbit** [comment]
> Zorin OS is not supported. See https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/#linux for a list of the supported Linux distros for WARP.

ZorinOS It is based on Ubuntu.
