### ISSUE TITLE
X-XSS-Protection header being set when not recommended

### ISSUE THREAD

**Issue by daservajesus** [cloudflare/cloudflare-docs#1760]
### Expected Behavior
X-XSS-Protection header is deprecated according to the OWASP site and should no longer be set to anything but 0

### Actual Behavior
Example still lists the header being set to a non-zero value which is no longer recommended

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/security-headers.md

### Additional information
https://owasp.org/www-project-secure-headers/#x-xss-protection

**Comment by Albertozhao** [comment]
Thanks @daservajesus! Updated the code in this [PR](https://github.com/cloudflare/cloudflare-docs/pull/2175).
