### ISSUE TITLE
Add Fleet to the list of MDM partners

### ISSUE THREAD

**Issue by dherder** [cloudflare/cloudflare-docs#17607]
### Proposed changes

- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/

### Subject Matter

How to deploy Cloudflare WARP client with Fleet

### Content Location

A new document in the partners section with a callout to a new page with the Fleet instructions on the Overview page.

### Additional information

PR for review: https://github.com/cloudflare/cloudflare-docs/pull/17606

**Comment by crwaters16** [comment]
Hey @dherder, thanks for opening an issue! Since you've already opened a PR with this edit, going to close this issue so we aren't double-counting this work. We'll review the PR soon!
