### ISSUE TITLE
Add permissions policy header

### ISSUE THREAD

**Issue by daservajesus** [cloudflare/cloudflare-docs#1761]
### Expected Behavior
Example should include a section for the permissions policy header. Useful to control browser features as well as opting out of the FLoC tracking currently being tested in certain browsers.

### Actual Behavior
Example makes no mention of the header

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/security-headers.md

### Additional information
https://scotthelme.co.uk/what-the-floc/
https://geekflare.com/opt-out-floc-configuration/
https://perishablepress.com/opt-out-google-floc/

**Comment by Albertozhao** [comment]
Thanks for the resources, mentioned the header in this [PR](https://github.com/cloudflare/cloudflare-docs/pull/2175)! We might in the future add a headers section to the docs, explaining them in more depth, so we can expand this code example further.
