### ISSUE TITLE
1.1.1.1 iOS setup should mention official app

### ISSUE THREAD

**Issue by Ashton-W** [cloudflare/cloudflare-docs#1762]
### Section that requires update

I believe this page should mention the official 1.1.1.1 app which can perform the same function as the suggested third party app for free, namely provide DNS with a VPN profile, it also has WARP+ of course.
products/1.1.1.1/src/content/setting-up-1.1.1.1/iphone.md

**Comment by marciocloudflare** [comment]
Hi @Ashton-W. Closing this as we've added information on how to use 1.1.1.1 official app. Thanks!
