### ISSUE TITLE
Workers - HTMLRewriter - How to :last-child?

### ISSUE THREAD

**Issue by leoplct** [cloudflare/cloudflare-docs#1771]
How can I use the :last-child selector?

In the documentation looks supported only :first-child. I've tried using :last-child but it returns error not valid selector.

**Comment by kristianfreeman** [comment]
cc @harrishancock @ObsidianMinor do we support `last-child` in HTMLRewriter?

**Comment by ObsidianMinor** [comment]
No, it requires looking ahead which is not feasible in a streaming parser.

**Comment by kristianfreeman** [comment]
thanks! closing, as this is not supported
