### ISSUE TITLE
WARP Client Site-to-site

### ISSUE THREAD

**Issue by C018** [cloudflare/cloudflare-docs#17883]
### Existing documentation URL(s)

-https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/site-to-site/

### What changes are you suggesting?

When tailscale and warp work at the same time, warp Site-to-site fails. Traffic has been correctly routed to the warp, and there is no IP conflict, but CGNAT IPs cannot communicate with each other.

**Comment by ranbel** [comment]
Hi @C018, thanks for raising this issue. At this time, we are not prioritizing compatibility between WARP Connector and other third-party agents. If you figure out how to get the configuration working, feel free to open a PR.
