### ISSUE TITLE
Update Pages/Workers compatibility matrix with new Workers CI/CD

### ISSUE THREAD

**Issue by RihanArfan** [cloudflare/cloudflare-docs#17921]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/static-assets/compatibility-matrix/

### What changes are you suggesting?

Currently on the compatibility matrix, Workers is shown not to have certain CI features, but this has recently changed with Workers CI/CD. https://developers.cloudflare.com/workers/ci-cd/builds/build-caching/

![image](https://github.com/user-attachments/assets/1d8d2aa4-d42a-4b71-b32d-355950ce3f25)

**Comment by ToriLindsay** [comment]
Thank you @RihanArfan ! Build Caching has been updated to show that it's supported by Workers.
