### ISSUE TITLE
The Rules Templates documentation should mention how people can suggest new templates

### ISSUE THREAD

**Issue by quinncomendant** [cloudflare/cloudflare-docs#17940]
### Proposed changes

The [Rules Templates documentation](https://github.com/cloudflare/cloudflare-docs/edit/production/src/content/docs/rules/snippets/index.mdx) should include information on how people can suggest new templates to the list of those offered. Ideally, there is a link that opens a contact form where people can add their own suggestions. 

### Subject Matter

How to suggest new Rules Templates

### Content Location

https://github.com/cloudflare/cloudflare-docs/edit/production/src/content/docs/rules/snippets/index.mdx

**Comment by pedrosousa** [comment]
Hi @quinncomendant 
Thank you for your suggestion! 

While we work out a specific process for accepting and reviewing template contributions (which will probably only happen in 2025), the current process will be the following:
- Users can make rule template contributions to the [Rules Examples](https://developers.cloudflare.com/rules/examples/) section in the Rules documentation. Create a PR and we'll review the proposal and (eventually) accept the new example in the Developer Docs. If you want to discuss an example before proposing it in a PR, you may create an issue instead.
- On a regular basis, we will internally review the new examples and implement some of them as rules templates in the Cloudflare dashboard.
