### ISSUE TITLE
"env" should be "bindings" in the Workers fetch handler

### ISSUE THREAD

**Issue by vicb** [cloudflare/cloudflare-docs#17953]
Issue move to a discussion at https://github.com/cloudflare/workers-sdk/discussions/7180

**Comment by vicb** [comment]
Actually I missed one important thing in my initial post which has **security implications**.

It is possible to define [secrets](https://developers.cloudflare.com/workers/configuration/secrets/#secrets-on-deployed-workers)

Merging the `env` with `process.env` will expose the secrets to all of the node libraries used by the application.

**Comment by jamesopstad** [comment]
I agree that `env` as a name is confusing but inside `WorkerEntrypoint` and `DurableObject` you access bindings via `this.env` so I would think that changing this only for `ExportedHandler` would lead to more confusion. Changing `WorkerEntrypoint` and `DurableObject` to use `this.bindings` would be a bigger and breaking change.

**Comment by vicb** [comment]
> Changing `WorkerEntrypoint` and `DurableObject` to use `this.bindings` would be a bigger and breaking change.

Good point.

It don't think this requires a breaking change. We can add `this.bindings` and make `this.env` a deprecated alias.

That would be a breaking change only if the implementation already provides a `bindings` - we should be able to use a compatibility flag to solve that

**Comment by vicb** [comment]
Issue move to a discussion at https://github.com/cloudflare/workers-sdk/discussions/7180
