### ISSUE TITLE
Misleading feature avalibility of Rules (maybe more)

### ISSUE THREAD

**Issue by kLiHz** [cloudflare/cloudflare-docs#18135]
### Existing documentation URL(s)

As said on Rule's homepage:

- https://developers.cloudflare.com/rules/

it is "available on all plans". (Same situation also applies to some other products.)

But specific features like "'Host header' overriding" of "Origin Rules", although not introduced as a paid feature on its doc:

- https://developers.cloudflare.com/rules/origin-rules/

is actually only available on Enterprise plans, and won't appear on Free plan user's dashboard.

The fact that it's Enterprise-only is mentioned under "Page Rules" -> "How To" -> "Rewrite Host Headers", which makes me confused. And since there's no sign or description on dashboard either, I once had no idea why the feature is missing and even thought it's my display or network issue.

- https://developers.cloudflare.com/rules/page-rules/how-to/rewrite-host-headers/

### What changes are you suggesting?

I'd like a more clear notice about product / sub-product / feature availability (I think I've seen them before), like, on their "Overview" page.

It might be even better if there's an feature overview table on each Product's homepage.

**Comment by pedrosousa** [comment]
Hi @kLiHz 
Each type of rule has its own Availability section (for example, in [Origin Rules](https://developers.cloudflare.com/rules/origin-rules/#availability)), which provides details on which exact features are available per plan.

I'll check how we can make this more clear in the documentation of each rule type.

**Comment by kLiHz** [comment]
@pedrosousa Sorry I didn't notice that earlier... Thanks for pointing out that for me!

I think a simple badge (something like `Free × Pro ✓ Enterprise ✓`) at the very beginning (just under the title, for example) might help?

Or maybe add some emoji alongside the text in the availability table (which makes it easier for visitors to notice)?

**Comment by pedrosousa** [comment]
For now we won't be adding extra info per setting about what's supported in each plan. We'll revisit this choice if we get additional feedback, and in that case we'll take your suggestions into consideration.
