### ISSUE TITLE
Create a KV section under "Platform"

### ISSUE THREAD

**Issue by Albertozhao** [cloudflare/cloudflare-docs#1814]
Per Rita's comment in this [PR](https://github.com/cloudflare/cloudflare-docs/pull/1719) that adds an explanation of namespaces/bindings in the [Runtime API section for KV](https://developers.cloudflare.com/workers/runtime-apis/kv),

"It feels like we have a need for a section under Platform for "KV". Once we have that, we should just have a sentence in the beginning that says "Before creating a binding, you must create a namespace" and make "create a namespace" a link. I'm a bit worried about too much of this leaking into the runtime doc part of it."

**Comment by koeninger** [comment]
why not use https://developers.cloudflare.com/workers/learning/how-kv-works or rename it to "using kv"

There's a lot less detail on that page now than there is for the corresponding learning pages for durable objects, websockets, and streams.
