### ISSUE TITLE
Instructions for Private Packages for NPM Don't Work as Expected

### ISSUE THREAD

**Issue by mckalexee** [cloudflare/cloudflare-docs#1820]
Referencing the previous issue, which was closed. https://github.com/cloudflare/cloudflare-docs/pull/1334

## Expected Behavior
By using a `preinstall` script you should be able to copy an `.npmrc.pages` over the existing `.npmrc` file in order to authenticate to private packages on GitHub.

## Actual Behavior
npm does not reload the `.npmrc` settings after the `preinstall` script so copying the `.npmrc.pages` file to `.npmrc` has no effect.

### Replicating
To avoid any issues with permissions issues with tokens and specific environments I've replicated this issue in a new environment with a validated token. 

I've done three different tests do demonstrate the issue. Each test used the same `TOKEN_FOR_GITHUB` environment variable.

### Test One ✅
Directly commit the `.npmrc` with the `${TOKEN_FOR_GITHUB}` placeholder to the repository and deploy.

`.npmrc`:
```
@tailwind:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${TOKEN_FOR_GITHUB}
```

This test successfully installed npm packages from a private repository using the token.

This validates that the token is set correctly and that the configuration of the `.npmrc` file is correct.

Unfortunately this is not a tenable option, since it breaks all local development unless the environment has a `TOKEN_FOR_GITHUB` set.

### Test Two ❌
Commit an  `.npmrc` with only the registry information, and create a `.npmrc.pages` file that has the `${TOKEN_FOR_GITHUB}`.

Deploy these using the instructions provided `is-pages.js` and `prepublish` script from the documentation, along with using cat to dump the contents of the file.

`.npmrc`:
```
@tailwind:registry=https://npm.pkg.github.com
```

`.npmrc.pages`:
```
@tailwind:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${TOKEN_FOR_GITHUB}
```

`is-pages.js`:
```js
if (!process.env.CF_PAGES) process.exit(1);
```

`package.json`:
```json
  "preinstall": "node is-pages && mv .npmrc.pages .npmrc || echo \"Skipping Cloudflare Pages\" && cat .npmrc",
```

This failed to build because npm could not authenticate with Github. The contents of the `.npmrc` were correct and matched the contents of the checked in `.npmrc.pages`.

This shows that npm is not respecting changes to `.npmrc` after it has started the install process.

### Test Three ❌
Do not create an `.npmrc` and create a `.npmrc.pages` file that has the `${TOKEN_FOR_GITHUB}`.

Deploy these using the instructions provided `is-pages.js` and `prepublish` script from the documentation, along with using cat to dump the contents of the file.

`.npmrc.pages`:
```
@tailwind:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${TOKEN_FOR_GITHUB}
```

`is-pages.js`:
```js
if (!process.env.CF_PAGES) process.exit(1);
```

`package.json`:
```json
  "preinstall": "node is-pages && mv .npmrc.pages .npmrc || echo \"Skipping Cloudflare Pages\" && cat .npmrc",
```

This failed to build because npm could not authenticate with Github. The contents of the `.npmrc` were correct and matched the contents of the checked in `.npmrc.pages`.

This validates that there is no difference between having an existing `.npmrc` in the repository and having none.

## Section that requires update
The "Managing Multiple Environments" section of the documentation should be replaced with a disclaimer that this is not possible

https://developers.cloudflare.com/pages/how-to/npm-private-registry#managing-multiple-environments

This should be added to the "Known Issues" section.

https://developers.cloudflare.com/pages/platform/known-issues

## Additional information
I am able to replicate this consistently and reliably, and I believe the extend of my testing has covered all possibilities. 

I would be happy to provide access to a private github repository with private packages that is experiencing this issue if further evidence is needed.

Thanks.

**Comment by grinry** [comment]
Got a workaround .npmrc not being reloaded:

1. Create bash script (/bin/is-pages):
```bash
#!/usr/bin/env bash

[ -z ${CF_PAGES+x} ] && exit 0;

if [ -f ".npmrc.pages" ];
then
  mv .npmrc.pages .npmrc;
  exit 1;
fi
```

2. Change `preinstall` in package.json
```json
"preinstall": "bash ./bin/is-pages && echo \"Running normally.\" || yarn install"
```

If CF_PAGES env variable is set and .npmrc.pages exists bash file will move .npmrc.pages to .npmrc and will exit bash script with error. 
When preinstall picks up that bash script exited with error - it will stop execution and gets instruction to run yarn install again - when it's being runned second time .npmrc.pages doesn't exists anymore so bash script exits without error and installing starts normally.

**Comment by ShynRou** [comment]
Putting the access token definition in the .npmrc is bad, since it's a tracked file it's inevitable that someone will commit it with their token. Would be better to place it there with a env variable. And let the user set it on their machine. Also the .env.local files shouldn't be tracked for the same reason.

```
//npm.pkg.github.com/:_authToken=$GITHUB_NPM_PKG_TOKEN
```

**Comment by flohaider** [comment]
I had this problem today and can confirm that it is still an issue.

@grinry Thank you for this workaround! There is a small typo in your `preinstall` script, it should say `bash ./bin/is-pages` instead of `bash ./bin/gh-pack`. Also I had to go with npm instead of yarn, so in the end my script is:

```json
"preinstall": "bash ./bin/is-pages && echo \"Running normally.\" || npm ci"
```

**Comment by grinry** [comment]
> I had this problem today and can confirm that it is still an issue.
> 
> 
> 
> @grinry Thank you for this workaround! There is a small typo in your `preinstall` script, it should say `bash ./bin/is-pages` instead of `bash ./bin/gh-pack`. Also I had to go with npm instead of yarn, so in the end my script is:
> 
> 
> 
> ```json
> 
> "preinstall": "bash ./bin/is-pages && echo \"Running normally.\" || npm ci"
> 
> ```
> 
> 

Oh, thanks, fixed typo :)

**Comment by leviwolfe** [comment]
Unfortunately, neither the official directions or the bash script worked for me.  I have this in my Pages build logs:

```
> npm ERR! code E401
> npm ERR! Incorrect or missing password.
```

I think my problem may also be related to npm/cli#2660 which describes the preinstall script not running when expected for certain versions of npm. In particular, [this comment](https://github.com/npm/cli/issues/2660#issuecomment-868527152) indicates the strategy is broken for a number of cloud providers with similar private registry solutions.

**Comment by raffpaquin** [comment]
Same issue here. Thanks, @flohaider and @grinry for the workaround!

**Comment by 10p-freddo** [comment]
Another workaround is to set the environment variable `NPM_CONFIG_USERCONFIG` to `/opt/buildhome/repo/.npmrc.pages` - then no scripts are needed.

This solution also has the nice property that any config settings in .npmrc will override .npmrc.pages, so you don't need to have duplicated settings in both npmrc files.

**Comment by goaround** [comment]
@ghughes thank you, much better (and faster) :)

**Comment by derN3rd** [comment]
We are currently trying to solve this problem for our repo as well, but none of the mentioned solutions here seems to work for us.

We use Yarn Berry (3.2.0) and are trying to install scoped packages from Github (npm.pkg.github.com).
In our .yarnrc.yml we have the following
```
npmScopes:
  ourcompany:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
```

I tried it with different env vars, with the .npmrc.pages copying, with preinstall scripts, but it seems yarn berry is either ignoring all of these.

Did someone else had issues with yarn berry and found a way around them?

Thanks in advance

**Comment by danawoodman** [comment]
@ghughes thanks for the solution, this works in my case. Can I suggest this get added to the docs so people like me don't have to crawl through google results to find the solution? https://developers.cloudflare.com/pages/how-to/npm-private-registry/#custom-registry-endpoints

**Comment by 10p-freddo** [comment]
@danawoodman it's already documented on that page (as of #5894)

**Comment by danawoodman** [comment]
Lol, not sure how I missed that 🤦

**Comment by danawoodman** [comment]
Now I'm getting this on a project without a custom registry, just a private npm package 🤣 

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@myorg/my-package/-/my-package-0.67.0.tgz - Not found
```

(package def exists, using it in multiple other projects)

But `NPM_TOKEN` is set: 

![image](https://github.com/cloudflare/cloudflare-docs/assets/157695/bc843c09-7a2d-4061-ad74-02ad79e69988)

No `.npmrc` file, using a never expiring automation token

**Comment by danawoodman** [comment]
Funny when you hit the same issue 5 months later and see that you were the last one to comment on the top google result...
