### ISSUE TITLE
[workers] Document that files don't work in FormData

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/cloudflare-docs#1825]
Workers currently parses files uploaded as part of form data as UTF-8 strings, which doesn't conform with the File API. We should document this and present some workarounds (e.g. polyfills) as an alternative

**Comment by lukeed** [comment]
Needs a known issue item w/ a link out to example(s) for the workaround(s)

**Comment by kristianfreeman** [comment]
https://developers.cloudflare.com/workers/platform/compatibility-dates/#formdata-parsing-supports-file
