### ISSUE TITLE
SCIM Setup Dev Doc - Add clarification on case-sensitivity and matching usernames to emails

### ISSUE THREAD

**Issue by ahobbs-cf** [cloudflare/cloudflare-docs#18257]
### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/setup/account/account-security/scim-setup/

### What changes are you suggesting?

- The `user principal name` and `email` fields within Entra need to match in order for provisioning to be successful 
- Both of these values need to match exactly and are also case-sensitive 

Would it be possible to add a note to the dev doc to clarify this across both points?

**Comment by patriciasantaana** [comment]
Hi @ahobbs-cf! Thank you for bringing this to our attention. There is an internal ticket to track the work on this, so I will be closing the issue now.

**Comment by ahobbs-cf** [comment]
Thanks @patriciasantaana! Could you let me know what the ticket number is, or tag me in it?
