### ISSUE TITLE
[workers] Include `FormData` example(s)

### ISSUE THREAD

**Issue by lukeed** [cloudflare/cloudflare-docs#1827]
We don't currently have any in our [examples list](https://developers.cloudflare.com/workers/examples).

Potential Example: [Playground](https://cloudflareworkers.com/#91f10aa9e02b4e9a17134afe50b788be:https://tutorial.cloudflareworkers.com)

Should be added to the `/examples` list and maybe linked to from the [`Request`](https://developers.cloudflare.com/workers/runtime-apis/request) runtime API page?

---

- [x] Add example
- [ ] Link within Request API doc

**Comment by deadlypants1973** [comment]
@lukeed, if this requires a code block, it may be good to have someone technical assigned to this? I won't be able to write a code example.

**Comment by lukeed** [comment]
For sure, I'll self-assign, just can't get to it quite yet.

**Comment by haleycode** [comment]
Closing out this issue since it's pretty old at this point. We can always reopen if needed.
