### ISSUE TITLE
Inaccuracy: "5 GHz is better at going through walls"

### ISSUE THREAD

**Issue by robpottify** [cloudflare/cloudflare-docs#184]
On: https://developers.cloudflare.com/internet/wifi it says: 

> 5 GHz is literally a faster (higher) frequency. And because of the frequency, 5 GHz is better at going through walls.

But isn't the opposite true - 2.4Ghz is better at penetrating walls than 5Ghz and hence has a greater reach in most environments?

**Comment by frusznyak** [comment]
yes that is correct AFAIK the lack of "wall-penetration power" is also one of the bigger reasons that the 5 GHz Band is not as crowded as the 2.4 GHz band since most other radios will be separated by some amount of walls.
