### ISSUE TITLE
serializeAttachment and deserializeAttachment documentation are missing

### ISSUE THREAD

**Issue by zxch3n** [cloudflare/cloudflare-docs#18410]
### Proposed changes

- https://developers.cloudflare.com/durable-objects/api/websockets/

### Subject Matter

serializeAttachment and deserializeAttachment 

### Content Location

- https://developers.cloudflare.com/durable-objects/api/websockets/

### Additional information

They are very useful API methods when using hibernation.

The docs were added in https://github.com/cloudflare/cloudflare-docs/issues/11294 but removed afterward without any explanation.

**Comment by Wallacy** [comment]
FWIW: Its `serializeAttachment`  and `deserializeAttachment` whiout the 's'

And yes, the docs are missing, but the API works fine.

That was removed on this refactor: https://github.com/cloudflare/cloudflare-docs/pull/18344

**Comment by harshil1712** [comment]
Hey, we have a PR to add this back: https://github.com/cloudflare/cloudflare-docs/pull/18423

**Comment by Oxyjun** [comment]
The PR has been merged, so it should now be back in the docs.

The two methods can be found in Best Practices/Using WebSockets/, under the heading "Extended methods"
