### ISSUE TITLE
证书一直是待验证状态 不知道是为什么

### ISSUE THREAD

**Issue by Hao1617** [cloudflare/cloudflare-docs#18519]
### Example URL(s)

![image](https://github.com/user-attachments/assets/7920de13-8780-410d-a795-36d9beceff1b)

### Actual Behavior

ssl验证没通过

### Expected Behavior

验证通过

**Comment by RebeccaTamachiro** [comment]
👋 @Hao1617  I'm sorry, we only take care of [developers.cloudflare.com](http://developers.cloudflare.com/) documentation in this repo. For assistance with your specific case, you can reach out to [community.cloudflare.com](http://community.cloudflare.com/) or [support.cloudflare.com](http://support.cloudflare.com/).

The following pages could be helpful but will depend on your case: 
https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/troubleshooting/
https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/troubleshooting/
