### ISSUE TITLE
[logs] Rightmost table column hidden by layout

### ISSUE THREAD

**Issue by avandendorpe** [cloudflare/cloudflare-docs#1859]
### Expected Behavior
https://developers.cloudflare.com/logs/reference/log-fields/http_requests
https://developers.cloudflare.com/logs/reference/log-fields/spectrum_events
vs
https://github.com/cloudflare/cloudflare-docs/blob/production/products/logs/src/content/reference/log-fields/http_requests.md
https://github.com/cloudflare/cloudflare-docs/blob/production/products/logs/src/content/reference/log-fields/spectrum_events.md

I would expect to see the Type column in the default view.

### Actual Behavior
The Type column is invisible without scrolling the column even on a very wide browser because of an artificially narrow center div.

### Section that requires update
I'm not sure where the formatting is taking place without digging deeper

### Additional information
![Screen Shot 2021-07-23 at 10 51 38 AM](https://user-images.githubusercontent.com/669211/126821813-355663a6-b28e-4496-a729-55f12e400c55.png)
![Screen Shot 2021-07-23 at 10 51 45 AM](https://user-images.githubusercontent.com/669211/126821817-0af19aae-169e-4bdb-8fd6-8ad1ea561266.png)

**Comment by KimJ15** [comment]
Thanks for submitting the issue @avandendorpe.  The team that supports work like this does not work from this Github repo - I have created the appropriate ticket for that team. Closing this issue given an open source contributor can't work on this.
