### ISSUE TITLE
DNS resolver page does not conveniently link to compliance report

### ISSUE THREAD

**Issue by tchajed** [cloudflare/cloudflare-docs#1864]
### Expected Behavior
The page on 1.1.1.1 is supposed to link to a compliance report from a third-party accounting firm (KPMG).

### Actual Behavior
The link goes to a generic "Trust Hub" page for all of Cloudflare.

### Section that requires update
https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver has a link "The report is available here" 

### Additional information
The link should go to at least https://www.cloudflare.com/trust-hub/compliance-resources/ or the actual report at https://www.cloudflare.com/resources/assets/slt3lc6tev37/5xlHCvvNBrvrIoWbuk1vTy/e1058b0d366adf4e983aef99a6ed2a1f/Cloudflare_1.1.1.1_Public_Resolver_Report_-_03302020__2_.pdf.

**Comment by marciocloudflare** [comment]
Thanks for reporting this @tchajed. We've updated the docs, so I'm going to close this issue. Thanks!
