### ISSUE TITLE
examples/rewrite-links.md Is it invalid for text?

### ISSUE THREAD

**Issue by insoxin** [cloudflare/cloudflare-docs#1865]
https://github.com/itewqq/codeforces-reverse-proxy/blob/main/cf.js

```
const replace_dict = {
    '$upstream': '$custom_domain',
    'sta.cf.<YOUR-SUBDOMAIN>.workers.dev':'stacf.<YOUR-SUBDOMAIN>.workers.dev',
    'assets.cf.<YOUR-SUBDOMAIN>.workers.dev':'cfassets.<YOUR-SUBDOMAIN>.workers.dev'
}
```

no effect

**Comment by KimJ15** [comment]
👋  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or https://discord.com/invite/cloudflaredev. Thanks!
