### ISSUE TITLE
Broken link to SCIM

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#18663]
### Example URL(s)

https://developers.cloudflare.com/fundamentals/changelog/#dashboard-scim-is-now-fully-self-serve

### Actual Behavior

the link to SCIM documentation is a 404

### Expected Behavior

correct URL appears to be https://developers.cloudflare.com/fundamentals/setup/account/account-security/scim-setup/

**Comment by pedrosousa** [comment]
Preview:
https://pedro-issue18663-broken-link.cloudflare-docs-7ou.pages.dev/fundamentals/changelog/#2024-12-06
