### ISSUE TITLE
Cloudflare for SaaS Plans: Add custom hostname pricing

### ISSUE THREAD

**Issue by aaronadamsCA** [cloudflare/cloudflare-docs#18681]
### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/plans/

### What changes are you suggesting?

Each plan indicates how many hostnames are included (e.g. 100) and the maximum number of hostnames (e.g. 5,000), but there is no indication of how much we'll pay for each additional custom hostname beyond the first 100.

### Additional information

This forum post suggests it might be $0.10/month per additional custom hostname:

https://community.cloudflare.com/t/custom-hostname-limit/602136

But I can't find any mention of this anywhere in the docs.

**Comment by RebeccaTamachiro** [comment]
Hi @aaronadamsCA, thanks for reaching out! Pricing information is at https://www.cloudflare.com/plans/. You can find Cloudflare for SaaS on the list:

![Screenshot 2024-12-16 at 13 52 13](https://github.com/user-attachments/assets/41dec009-a615-4339-a51d-645d36eebfcf)
