### ISSUE TITLE
Visualise traffic from GraphQL

### ISSUE THREAD

**Issue by onderakbulut** [cloudflare/cloudflare-docs#1871]
Access to fetch at 'https://api.cloudflare.com/client/v4/graphql' from origin 'https://cdn.asdsad.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

How can I fix this error, Thanks

**Comment by KimJ15** [comment]
👋  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
