### ISSUE TITLE
Add best practices for security

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs#19]
https://github.com/cloudflare/workers-docs/issues/659

"EG to the security article add how to add 2FA, watch results in various browsers, search results, etc.

Reasoning; comprised accounts can become spam bots:
https://blog.sucuri.net/2020/02/abused-cloudflare-workers-service-used-to-inject-korean-seo-spam.html?utm_source=twitter&utm_medium=blog&utm_campaign=wyatt"

**Comment by cloudflere** [comment]
(removed)
