### ISSUE TITLE
extract-cookie-value.md example contains a bug

### ISSUE THREAD

**Issue by rikonor** [cloudflare/cloudflare-docs#1909]
### Expected Behavior
The [extract-cookie-value.md](https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/extract-cookie-value.md) contains an example to gets a cookie value from a given request.

### Actual Behavior
The example code contains a bug that matches on a cookie name's _suffix_ instead of making an exact match.

### Section that requires update
[extract-cookie-value.md?plain=1#L32-L33](https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/extract-cookie-value.md?plain=1#L32-L33)

### Additional information
The search should be for an exact match, accounting for either the cookie being the first in the list of cookies or second-or-later. See [this](https://stackoverflow.com/a/25490531) StackOverflow question for some examples.

**Comment by lukeed** [comment]
Closed by #2101
