### ISSUE TITLE
Vague

### ISSUE THREAD

**Issue by the-wazz** [cloudflare/cloudflare-docs#1913]
### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/registrar/src/content/transfer-instructions/namecheap.md
Step 4: Transfer to Cloudflare

### Additional information
Quote: "In the Cloudflare transfer screen, input the...". 

Problem: Where is this transfer screen? I can't find it.

**Comment by marciocloudflare** [comment]
Hey @the-wazz. I've updated the docs and it should be easier to understand now. Going to close this. Thank you for bringing this to our attention!
