### ISSUE TITLE
Improve default DNS suggestion

### ISSUE THREAD

**Issue by itsjoekent** [cloudflare/cloudflare-docs#1920]
### Expected Behavior
When setting up a new Cloudflare Worker that has a custom route but no true origin server, the documentation suggests adding the following DNS configuration

> If your route is configured to a hostname, you will need to add a DNS record to Cloudflare to ensure that the hostname can be resolved externally. If your Worker acts as your origin (the response comes directly from a Worker), **you should enter a placeholder (dummy) AAAA record pointing to 100::,** which is the reserved IPv6 discard prefix

https://developers.cloudflare.com/workers/get-started/guide

Unfortunately, a dummy `A` or `AAAA` record does not appear to work, only a dummy `CNAME`. Using the dummy record suggested leads to `DNS_PROBE_FINISHED_NXDOMAIN` errors. A quick google search for something such as _"Cloudflare Worker DNS_PROBE_FINISHED_NXDOMAIN"_ shows that numerous folks have potentially run into this issue.

### Actual Behavior
Update that line to suggest a dummy CNAME record.

### Section that requires update
https://developers.cloudflare.com/workers/get-started/guide

**Comment by lukeed** [comment]
I have production workers with an `A` record pointing to `192.0.2.1` – it definitely works. 

The main thing is that the record itself is orange-clouded, which looks like we're missing in the docs.

**Comment by itsjoekent** [comment]
@lukeed Gotcha, weird, I wonder if there is a delay with when it takes effect? (as in, maybe my original A was fine, but I tried accessing the worker too quickly?). If there is a scenario like that, could be useful to put that warning in the docs.

**Comment by lukeed** [comment]
So is it working now?

In the past I've noticed this before – adding a brand new zone & immediately attaching a Worker to it could have some delay issues. I'll try to find an answer on this, but it might come down to DNS propagation effects.

**Comment by BOYKHMER** [comment]
@itsjoekent

**Comment by itsjoekent** [comment]
@lukeed Yeah as soon as I went from the suggestion in the docs to a CNAME it worked fine. I'm gonna agree with you it probably had to deal something to do with it being a new domain.
