### ISSUE TITLE
[workers] Remove references to CF Tunnel in wrangler tail docs

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/cloudflare-docs#1934]
As of wrangler 1.19.0, [wrangler no longer requires or uses cloudflared for tail](https://github.com/cloudflare/wrangler/releases/tag/v1.19.0), so we should remove any reference to it in the `wrangler tail` documentation. We can also remove the `Aside` component we added in #1430 to help people use `wrangler tail` with existing `cloudflared` configurations.

https://github.com/cloudflare/cloudflare-docs/blob/4b2ca91388ef6b46ae4d1779927d990ea171061a/products/workers/src/content/cli-wrangler/commands.md#L266-L285

**Comment by deadlypants1973** [comment]
@signalnerve , should I remove this completely or should I add a note about the version? Because depending on what version people are using, they may still encounter this issue for some time?

**Comment by kristianfreeman** [comment]
good question! what do you think? I think you're right that we should reference the old version for the time being. maybe instead of removing, we can update to say "old versions of wrangler use cloudflared, which have issues with ... blah blah blah" and then encourage people to update?
