### ISSUE TITLE
[workers] Improve Environmental Variables & Secrets documentation + discovery

### ISSUE THREAD

**Issue by elithrar** [cloudflare/cloudflare-docs#1937]
### Expected Behavior

The documentation needs clearer examples on how users can reference Environmental Variables and/or Secrets created via Wrangler on the API/Dashboard.

### Section that requires update

https://developers.cloudflare.com/workers/platform/environments#environment-variables

Right now, the docs show `wranger secret ...` and `wrangler.toml` examples, and refer to _Bindings_ under https://developers.cloudflare.com/workers/platform/environments#environment-variables - but don't concretely show a user how to reference their Env Var or Secret in their Worker code.

If you look up "Bindings", you might discover [the KV docs](https://developers.cloudflare.com/workers/runtime-apis/kv#reading-key-value-pairs
), but accessing KV values is via `NAMESPACE.get(key)` - whereas an Env Var or Secret is simply `NAME` as a global variable.

We should provide clearer examples of:

1. How to set Env Vars and Secrets via the Dashboard (see https://blog.cloudflare.com/workers-secrets-environment/ from Feb 2020 - note that the blog post also doesn't have a code example!)
2. How to set them via Wrangler (already done)
3. How to _retrieve_ them in code
4. Why using Secrets and Env vars is better (more reusable, more secure) than hard-coding into your script 😉 

### Additional information

I would recommend breaking "Environmental Variables and Secrets" into their own docs, as they are buried in the "Environments" doc - I didn't find it particularly discoverable.

Having third-level headers (`###`) for `### Setting Environmental Variables and Secrets`, `### Getting Environmental Variables and Secrets`, and `### Environmental Variables vs. Secrets` would help users discover and use these features.

**Comment by elithrar** [comment]
We should also update the examples to follow this:

* https://developers.cloudflare.com/workers/examples/signing-requests
* https://developers.cloudflare.com/workers/examples/auth-with-headers

**Comment by lukeed** [comment]
@elithrar Hey, what do you mean by your follow-up comment? What examples need to change & what aspects of these two links do you want emulated?

**Comment by elithrar** [comment]
@lukeed 

On other platforms, "Environmental Variables" and "Secrets" are top-of-hierarchy terms & features that I can discover directly.

- For us, it feels like the former might be buried too deeply in Environments, and Secrets live in the wrangler docs.
- It's not clear that either of these can be configured in the UI
- We should make it clearer to users why Env Vars are better than just global constants in their script
- The same, but for Secrets. A user looking to use Env Vars should hopefully learn why they might want to use Secrets in some cases _as_ they learn about Env Vars.
- We can probably look to show more examples of accessing them from code - there is not an example of accessing an Env Var from a Worker here: https://developers.cloudflare.com/workers/platform/environments#environment-variables (it's very wrangler-centric)

Hope that's a bit clearer! 

![image](https://user-images.githubusercontent.com/18544/130133804-e0d6b9f7-2b45-40f7-a935-2cb2283e4d2a.jpeg)

**Comment by elithrar** [comment]
And sorry, for the examples: should they not direct users to use Secrets instead of putting key material in a global constant?

**Comment by lukeed** [comment]
Gotcha; totally agree & all your original points are addressed in the linked PR.

The examples can be updated in a future pass. We're reworking them now (-> TypeScript, -> Modules) and will revisit the contents of examples in this pass or in a future pass soon after this work.

**Comment by elithrar** [comment]
Got it - makes sense, and looking forward to modules-by-default! Thanks Luke!
