### ISSUE TITLE
How can I get list of all fields on a GraphQL dataset?

### ISSUE THREAD

**Issue by Ali-Yazdani** [cloudflare/cloudflare-docs#194]
I wanna get a list of all fields on a dataset (firewallEventsAdaptive) in GraphQL, Since in the API version we had some fields which are changed now (for example host, occurred_at, matches, ...) and now I can't find them in the GraphQL version. 
in the document, we have this page https://developers.cloudflare.com/analytics/graphql-api/tutorials/querying-firewall-events that mentioned some of the fields:
{
            action
            clientAsn
            clientCountryName
            clientIP
            clientRequestPath
            clientRequestQuery
            datetime
            source
            userAgent
          }

Thank you in advance

**Comment by twalwyn** [comment]
You can find this information via the `introspection` feature of GraphQL: https://developers.cloudflare.com/analytics/graphql-api/getting-started#querying-basics
