### ISSUE TITLE
Docs show the ability to select DNS category 1 -- "Ads" for Cloudflare Gateway DNS Policy (new)

### ISSUE THREAD

**Issue by 0dragosh** [cloudflare/cloudflare-docs#1950]
Docs show the ability to select DNS category 1 -- "Ads" for Cloudflare Gateway DNS Policy (new).

You cannot do that on dash.teams.cloudflare.com.

### Expected Behavior
Ability to block Ads as per DNS category 1 on L84: 

https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/policies/filtering/dns-policies-builder/dns-categories.md

### Actual Behavior
The "Ads" category doesn't show up.
<img width="1127" alt="Screenshot 2021-08-03 at 18 27 25" src="https://user-images.githubusercontent.com/39906742/128042681-4c83a659-eb3a-457d-b377-7f4871001759.png">

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/policies/filtering/dns-policies-builder/dns-categories.md

### Additional information
Any other details or screenshots you think are relevant.

**Comment by Winnah2** [comment]
Hello world

**Comment by haleycode** [comment]
Closing this out for now. If we need to revisit, a new ticket can be opened.
