### ISSUE TITLE
Code snippets are only partially searchable - need to make snippet window scrollable again

### ISSUE THREAD

**Issue by toinbis** [cloudflare/cloudflare-docs#1958]
### Expected Behavior
When I search using browser search in https://developers.cloudflare.com/workers/examples, I expect to find and quickly look through all the results found. 
![Screenshot 2021-08-03 at 22 46 40](https://user-images.githubusercontent.com/68685/128076926-f313bb1b-acc2-4086-9266-bbac025ad35f.png)

I.e. When I hover over the snippet with mouse, I need to be able to scroll and see all of it, without clicking actual snippet. That's how old CF Workers docs engine worked - it was very convenient way of look through all the recipes and find what you.

### Actual Behavior
Instead, now only the part that has been styled to be displayed initially can by visuallyu seen. Chrome search shows there is 61 occurances of `new resp` string pattern, but I can only locate 10 or 11 of them - they are, well, 'hidden' with css :) To my understanding, that is an UX anti-pattern. And this broke the flow that worked so well with old workers docs.

Thanks in advance for considering!

**Comment by KimJ15** [comment]
Great suggestion. We are actually working on improving search, so I will share your post with the team. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
