### ISSUE TITLE
[warp-client] Fix broken mailto: link in support_url for mdm-deployed warp clients

### ISSUE THREAD

**Issue by derekcwhite** [cloudflare/cloudflare-docs#1968]
### Expected Behavior
Using an MDM-deployed warp client 1.5.207-463 and macOS 11.5[.1], with the support_url parameter defined as per the documentation, clicking on the bug icon or `Send Feedback` menu item in settings, a mail client should open an email with the email address defined in support_url.

### Actual Behavior
Clicking on the bug icon or `Send Feedback` causes Chrome (Version 92.0.4515.107 (Official Build) (x86_64)) to open gmail in a new tab without the To: field being populated. I have not tested other mail clients or browsers. 

### Section that requires update
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/parameters#support_url

### Additional information
https://datatracker.ietf.org/doc/html/rfc6068

**Comment by kkrum** [comment]
Thanks for the fix Derek, this is all merged.
