### ISSUE TITLE
TLD Policies missing supported TLDs

### ISSUE THREAD

**Issue by burtybob** [cloudflare/cloudflare-docs#2002]
### Expected Behavior
https://www.cloudflare.com/en-gb/tld-policies/ shows .biz and .cloud

### Actual Behavior
https://www.cloudflare.com/en-gb/tld-policies/ doesn't show .biz or.cloud 

### Section that requires update
https://www.cloudflare.com/en-gb/tld-policies/

### Additional information
The dashboard shows .biz and .cloud are available but the TLD policy doesn't:
![image](https://user-images.githubusercontent.com/166198/128711289-fb9dfb76-b61c-44ec-88e7-8319d59221d6.png)

This page is linked to from the developers docs under "Domain Registration" -> "TLDs supported": https://developers.cloudflare.com/registrar/domain-registration/tlds-supported

**Comment by KimJ15** [comment]
We only take care of developers.cloudflare.com documentation requests in this repo, so I will share your post with the team responsible for cloudflare.com pages. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
