### ISSUE TITLE
[Teams] Broken image on the Device Serial Numbers Page

### ISSUE THREAD

**Issue by Kynson** [cloudflare/cloudflare-docs#2038]
### Expected Behavior
The images should be show correctly.

Affected images:
- https://developers.cloudflare.com/cloudflare-one/static/zero-trust-security/corp-device/list-start.png
- https://developers.cloudflare.com/cloudflare-one/static/zero-trust-security/corp-device/list-save-list.png

### Actual Behavior
The images can't be displayed, request failed with an 404 error

### Section that requires update
Teams > Identity > Device Posture > Device Serial Numbers
https://developers.cloudflare.com/cloudflare-one/identity/devices/corp-device

### Additional information
N/A

Thanks

**Comment by abracchi-tw** [comment]
thanks for pointing this out! should be fixed now.
