### ISSUE TITLE
[Workers] Improve pricing section 

### ISSUE THREAD

**Issue by deadlypants1973** [cloudflare/cloudflare-docs#2067]
via internal chat:

> people are consistently confused with how we've laid out the free and paid limits here - they think the 1GB limit is not associated with the free tier.  Any ideas on how we could fix this? I'm happy to make the actual change.

**Comment by kristian** [comment]
Wrong @kristian I am sorry. @signalnerve is the right @ I guess.

**Comment by kristianfreeman** [comment]
@greg-mckeon volunteered to do this in our internal chat :D @greg-mckeon happy to help if you'd like, let me know!

**Comment by shuklaalok7** [comment]
I am confused about this section as well, https://developers.cloudflare.com/workers/platform/limits#how-long-can-a-subrequest-take
What does it mean for the client to stay connected when a worker is triggered by an HTTP request?

Any help here is welcome. Thanks.

**Comment by deadlypants1973** [comment]
Updated by Greg.
