### ISSUE TITLE
Updates on default installation path of cloudflared on MacOS

### ISSUE THREAD

**Issue by yzs981130** [cloudflare/cloudflare-docs#2117]
### Expected Behavior
https://developers.cloudflare.com/cloudflare-one/tutorials/ssh#native-terminal

In this section, there is an example of installing cloudflared with homebrew and ssh config on MacOS. However, for m1-based Mac, the default installation path of cloudflared from homebrew is `/opt/homebrew/bin/cloudflared` rather than `/usr/local/bin/cloudflared`. It may be better to mention the both two installation path.

### Actual Behavior
There is only `/usr/local/bin` in the example ssh config, which would be misleading.

### Section that requires update
https://developers.cloudflare.com/cloudflare-one/tutorials/ssh#native-terminal

**Comment by ranbel** [comment]
Thank you for your feedback! We will add instructions once we officially support cloudflared builds for M1's.
