### ISSUE TITLE
Clarify that `cf: { cacheTtl: -1 }` is invalid

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/cloudflare-docs#2119]
### Expected Behavior
The "TTL interpretation" section [at the bottom of this page](https://developers.cloudflare.com/workers/examples/cache-using-fetch#ttl-interpretation) should make clear that only `cacheTtlByStatus` supports negative values.

`cacheTtl: -1` (or any negative number) has no defined meaning, and is currently ignored by Cloudflare's infrastructure (i.e., it does not even imply `cacheEverything`).

### Actual Behavior
It is unclear that the "TTL interpretation" section linked above only applies to `cacheTtlByStatus`. Many customers assume `cacheTtl: -1` has a defined meaning. A common assumption is that it means "bypass cache", which is not the case -- it in fact does nothing.

### Section that requires update
In addition to [the "TTL Interpretation section"](https://developers.cloudflare.com/workers/examples/cache-using-fetch#ttl-interpretation) linked above, we should probably document the valid values here as well: https://developers.cloudflare.com/workers/runtime-apis/request#requestinitcfproperties

**Comment by lmcarreiro** [comment]
I tested this today with an Enterprise account, and it doesn't look `cacheTtl: -1` is invalid or ignored.

My test was a fetch request from a cloudflare worker to GET a file 5.9 GB from Backblaze, using a byte-range request header, like `Range: bytes=0-10` to get just a piece of the file.

The results are:
- `cacheTtl: 0` makes Cloudflare to remove the `Range` header from my request when forwarding to the origin server, which causes the server to return a 200 response including the full content (5.9 GB)
- `cacheTtl: -1` makes Cloudflare to not touch my request to the origin server (so the `Range` header is forwarded), which causes the server to return a 206 partial content response containing only the 10 bytes I requested.

@deadlypants1973 That is not reflected in the docs, would it be possible to have them updated to clarify this? Can we rely on this behavior going forward?
