### ISSUE TITLE
Windows 7 issue

### ISSUE THREAD

**Issue by lalpriyantha** [cloudflare/cloudflare-docs#2127]
### Windows 7 issue
Not compatible with windows 7 or later versions. Can you fix it?

**Comment by kodster28** [comment]
Howdy @lalpriyantha, are you talking about a specific product? We don't really have enough info to address your comment with what you've provided.

**Comment by haleycode** [comment]
Given that we have not received additional information on this issue, I am closing it for now. Please feel free to submit a new ticket with more detailed info if you wish.
