### ISSUE TITLE
Confusion around Always Online cache times

### ISSUE THREAD

**Issue by mattlinares** [cloudflare/cloudflare-docs#2140]
### Expected Behavior
Expect clarity around the behaviour of this feature: https://github.com/cloudflare/cloudflare-docs/blob/production/products/cache/src/content/about/always-online.md

### Actual Behavior
Contradictory passages seem to indicate different caching lengths:

1)

`When you enable Always Online with Internet Archive integration, Cloudflare shares your hostname and popular URL paths with the archive so that the Internet Archive’s crawler stores the pages you want archived. When submitting targets to the crawler, Cloudflare identifies the most popular URLs found among GET requests that returned a 200 HTTP status code in the previous 5 hours.`

2)

`A Cloudflare crawler identifies resources to place in the Always Online cache. When Internet Archive integration is enabled, Cloudflare tells the Internet Archive what pages to crawl and how often. To ensure stability of service, Cloudflare limits the crawling interval. Limits vary by Cloudflare plan, and the Always Online crawler ignores robots.txt.
Free customers once every 30 days.
Pro customers once every 15 days.
Business and Enterprise customers once every 5 days.`

It's not clear that these paragraphs are describing different kinds of caching, and yet they have different caching period lengths.

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/cache/src/content/about/always-online.md

### Additional information
Any other details or screenshots you think are relevant.

**Comment by angelampcosta** [comment]
Thanks for letting us know @mattlinares. We're actually in the process of addressing this issue now, and you should see updated content soon!
