### ISSUE TITLE
Warp

### ISSUE THREAD

**Issue by Daniel1Diaz** [cloudflare/cloudflare-docs#2203]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @Daniel1Diaz, could you provide any more context around your issue? At the moment, we don't have anything to go off of.

**Comment by kodster28** [comment]
Closing for now, but feel free to open an issue with more details if there's more to the story here.
