### ISSUE TITLE
Update Rust Worker KV tutorial

### ISSUE THREAD

**Issue by nilslice** [cloudflare/cloudflare-docs#2216]
Hi @fkettelhoit - 

We're thinking we should update this tutorial, which you (very nicely) authored recently:
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/tutorials/workers-kv-from-rust/index.md

Since the launch of [`workers-rs`](https://github.com/cloudflare/workers-rs), which co-opts the original [rustwasm-worker-template](https://github.com/cloudflare/rustwasm-worker-template), the tutorial no longer really works / makes sense in the same way it did prior. 

If you're interested, would you like to update this tutorial to show KV usage from the point of view of a `workers-rs` user?

**Comment by fkettelhoit** [comment]
I will try to update the tutorial in the coming days or weeks. Given that `workers-rs` currently depends on the bleeding edge version of `wrangler`, I would assume that an updated tutorial will only be merged when a new `wrangler` version has been released, correct?

**Comment by kristianfreeman** [comment]
> Given that workers-rs currently depends on the bleeding edge version of wrangler, I would assume that an updated tutorial will only be merged when a new wrangler version has been released, correct?

@nilslice any thoughts on this?

**Comment by nilslice** [comment]
@fkettelhoit @signalnerve - `workers-rs` depends on a min. version of wrangler @ v1.19.2. Which is (at the time of this comment) the current stable release:

https://crates.io/crates/wrangler
https://www.npmjs.com/package/@cloudflare/wrangler

**Comment by fkettelhoit** [comment]
Sorry, my bad! The workers-rs readme assumes `>v1.19.2`, which I interpreted to mean that `v1.19.2` is not recent enough. I will try to update the tutorial as soon as I get the chance.

**Comment by nilslice** [comment]
Oops.. that's my bad. I have fixed the README now. Thanks for calling attention to that!

**Comment by kristianfreeman** [comment]
Hey @fkettelhoit, any interest in working on this still?

**Comment by fkettelhoit** [comment]
Hey @signalnerve, sorry for the delay!

Unfortunately I probably won't find the time to do it before the beginning of next year, so if you need it sooner then I can't contribute much to the process I'm afraid.

**Comment by kristianfreeman** [comment]
No problem. @nilslice Would you be interested in working on this? My team doesn't have a ton of Rust experience, so if we're unable to get this updated, we may want to just move towards deprecating the tutorial and linking to the workers-rs repository instead. What do you think?

**Comment by nilslice** [comment]
I can update it so it uses `workers-rs`, given that it's the recommended way to run Rust on Workers. It's going to be a _whole lot_ shorter of a tutorial though... which is a good thing?

**Comment by kristianfreeman** [comment]
Yep, that's ok @nilslice !

**Comment by kristianfreeman** [comment]
We unfortunately don't have the resources to update this right now, so I'm going to close this ticket. If someone from the community would like to contribute to this update, that'd be great, but pulling this off of the issue log for now
