### ISSUE TITLE
Isolate wrong definition

### ISSUE THREAD

**Issue by hyperandroid** [cloudflare/cloudflare-docs#2247]
Sorry if I sound bold, but for correctness, I think the Isolate definition in the documentation is not correct.

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/learning/how-workers-works.md#isolates

### Additional information
An `Isolate` is a fully independent Javascript VM instance with its own heap. Each `Isolate` can have multiple independent Javascript execution `Context`. Each context poses an independent, unrelated-to-other Context execution environment, like a sandbox, where different applications can run.

For example, v8 Inspector is defined per Isolate, and you have to select the current debugging Context since only one thread can be executing javascript on a given Isolate at a time.

**Comment by jkup** [comment]
This is interesting! What is it about the current definition that is incorrect? Both yours in this issue and the one on the doc read similarly to me.

**Comment by hyperandroid** [comment]
To me, the misleading word in this phrase:
`V8 orchestrates isolates: lightweight contexts that group variables with the code allowed to mutate them ...`
is `context`. 

As I said, by definition, a `v8::Isolate` is not a context. It is a full VM instance. This VM instance can have one or more `v8::Context`. Each v8::Context does not share anything with other contexts (lots of details here, but for simplicity, this would be the case) and hence can hold independent applications, much like a sandbox, or an execution context.

From a Cloudfare Worker perspective, I get the expectation of a user is that their code would run sandboxed.
Knowing nothing about how Cloudfare Workers are built, I'd assume Isolates are sitting around waiting for a client request, which would create a v8::Context, load the snapshot, which would account for maybe a few tens of milliseconds, and then run sandboxed client code. 

With all this, I think the offered Isolate definition is maybe quite simplified `Isolate !== lighweight context` ?

**Comment by kentonv** [comment]
In the implementation of Cloudflare Workers, `v8::Isolate` and `v8::Context` are mostly 1:1. We create a separate isolate for each script, and exactly one `v8::Context` within that isolate. (There are some cases where we create multiple contexts, but they are nitpicky details and we're moving away from doing that.)

We do _not_ create a new `v8::Context` for each request. Doing so is too expensive and provides little benefit. So, in our implementation, multiple requests for the same script on the same machine will generally run in the same isolate _and_ context.

The word "context" is vague and heavily overloaded. I think in the text "V8 orchestrates isolates: lightweight contexts", we did not intend "context" to mean specifically `v8::Context`, but rather it's the abstract meaning of the word "context". We could try using a different word to avoid confusion with `v8::Context`, but personally I don't think it's a big deal.

**Comment by hyperandroid** [comment]
It is not a big deal for sure.
For for a long time v8 embedder like me, it sounded like an over simplification of what an Isolate actually is.

Thanks for clarifying on the implementation details, but that's what i'd have expected anyway if a request ends un on the same box as the previous one and the execution script has not been modified. Since the context already exists, it should be able to handle another request on the same v8::Context. 
Definitely building a new context and running a new script can be a costly operation. Even after implementing script streaming, bytecode cache or context snapshot to name a few.
Out of curiosity, if we expect every request to a Cloudfare worker to be sandboxed, and as you describe the context is reused, how do you enforce global context leakage of data ? 
Is there any implementation-specific documentation I could jump on reading ?
