### ISSUE TITLE
1dot1 mode should not refer to URL filter

### ISSUE THREAD

**Issue by kkrum** [cloudflare/cloudflare-docs#225]
In at least this file: https://developers.cloudflare.com/warp-client/teams/parameters

1dot1 mode talks about support for URL filtering, but that only comes with WARP mode and only if configured in gateway. Need to fix.

**Comment by KimJ15** [comment]
@abracchi-tw some feedback about the content on https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/parameters

**Comment by abracchi-tw** [comment]
I think the page has now been updated. @kkrum feel free to reach out if you have any other remarks!
