### ISSUE TITLE
Is DURABLE_OBJECT.get an async function or not?

### ISSUE THREAD

**Issue by jobsort** [cloudflare/cloudflare-docs#2257]
### Expected Behavior
I don’t know what the expected behavior is because some part of the documentation says to use `DURABLE_OBJECT.get` and some says to use `await DURABLE_OBJECT.get`, so it’s unclear which one it is.

On [https://developers.cloudflare.com/workers/learning/using-durable-objects](https://developers.cloudflare.com/workers/learning/using-durable-objects):
```
let stub = await env.EXAMPLE_CLASS.get(id);
```

vs.

Template code on Github [https://github.com/cloudflare/durable-objects-template/blob/master/src/index.mjs](https://github.com/cloudflare/durable-objects-template/blob/master/src/index.mjs)

```
let obj = env.COUNTER.get(id);
```

### Actual Behavior
The documentation should be in sync with the example code from Github.

### Section that requires update
`https://developers.cloudflare.com/workers/learning/using-durable-objects`

### Additional information
N/A

**Comment by koeninger** [comment]
It's not necessary to await it, I'll open a PR to update that example
