### ISSUE TITLE
`CF_*` environment variables supported by wrangler

### ISSUE THREAD

**Issue by dlqqq** [cloudflare/cloudflare-docs#2260]
In the documentation, I've noticed that you can specify `CF_ZONE_ID` and `CF_ACCOUNT_ID` to dynamically change `zone_id` and `account_id` during deployment based on the environment. This is useful for having dynamic deployment behavior. However, there are also other Wrangler options. Namely `CF_NAME`, which we use to spin up a custom `wrangler.dev` subdomain for each branch in our serverless repository. For example, if I push to a branch `beta-fixes`, I get the `beta-fixes.[ORGANIZATION].wrangler.dev` subdomain allocated to that function.

 I can't find any mention of this in the docs; could somebody please point me to a source or add documentation to save the time of future users?

**Comment by dlqqq** [comment]
Related: https://github.com/cloudflare/wrangler/issues/1885

**Comment by jkup** [comment]
Added a note to the docs. Would love to get feedback on whether you feel this covers it or if there is more we should add! https://github.com/cloudflare/cloudflare-docs/pull/3178
