### ISSUE TITLE
Why when I tried to log in either web or app cluodfare have to veify

### ISSUE THREAD

**Issue by OzzOnn76** [cloudflare/cloudflare-docs#2269]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @OzzOnn76, can you provide any additional details about your request? At the moment, we don't have much to go off of.

**Comment by KimJ15** [comment]
This issue appears to have been opened accidentally. I'm going to close it now, but feel free to open a new issue or ask any questions.
