### ISSUE TITLE
Pages - Code reference not helpful

### ISSUE THREAD

**Issue by Triloworld** [cloudflare/cloudflare-docs#2271]
I try to re-align some project. If I try to remove Pages project then this error show up:

> Must delete custom domains before deleting project (Code: 8000028)

I do that by remove CNAME record. Problem exist, after time I finally found that this need to be removed from special tab that I forgot to check. I check documentary where this information should be added. 

### Expected Behavior
Nothing to find! Need some reference

### Actual Behavior
Find by google it and see that it need to be removed from special tab

### Section that requires update
How to or better FAQ with codes that type

### Additional information
Many codes `Code: XXXXXX` need they reference in documentation to be more self aware of problem

**Comment by BOYKHMER** [comment]
Hello
