### ISSUE TITLE
How to use c# to upload pictures?

### ISSUE THREAD

**Issue by bbhxwl** [cloudflare/cloudflare-docs#2332]
How to use c# to upload pictures?

**Comment by haleycode** [comment]
Hi there! If you could provide some additional context on which documentation you believe requires this update and why, we will be better able to address your comments. Thanks!

**Comment by Roselynalan** [comment]
<a href="https://elearninginfographics.com/elearning-implementation-toolkit-infographic/" title="eLearning Implementation Toolkit Infographic"><img src="https://cdn-infographic.pressidium.com/wp-content/uploads/eLearning-Implementation-Toolkit-Infographic.jpg" alt="eLearning Implementation Toolkit Infographic"></a>

**Comment by KimJ15** [comment]
I'm going to close this issue now, but feel free to open a new issue or ask any questions.
