### ISSUE TITLE
[Workers] Mention adding bindings as globals in TypeScript

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#2357]
### Expected Behavior
There should be documentation on declaring a global constant for KV, variables, and secrets. Right now while using TypeScript, editors will complain the variable does not exist. The way to sort this is by declaring a const like so:

```typescript
declare global {
  // KV binding
  const TODO: KVNamespace;

  // Secret binding
  const WEBHOOK_URL: string;
}
```

### Actual Behavior
Right now there is no documentation for this. There have been many questions about how to do this in Discord. 

### Section that requires update
* KV binding - https://developers.cloudflare.com/workers/runtime-apis/kv#kv-bindings
* General variables - https://developers.cloudflare.com/workers/platform/environment-variables

**Comment by lukeed** [comment]
Since this ticket opened, this is now documented on the `@cloudflare/workers-types` readme directly: https://github.com/cloudflare/workers-types#using-bindings
