### ISSUE TITLE
"Set up 1.1.1.1 for Families" should include DOT (DLS over TLS) information

### ISSUE THREAD

**Issue by Tenelia** [cloudflare/cloudflare-docs#2360]
### Expected Behavior
Link to the documentation: https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families
Current document **_should_** have instructions for DOT and to inform users to leave SPKI Fingerprint field blank.

### Actual Behavior
No instructions can be found on that currently.

### Section that requires update
1. https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families requires the update in a new section below DOH.
2. Any other doc or FAQ as needed may indicate "team is working on it".

**Comment by marciocloudflare** [comment]
Hi there @Tenelia. We will probably have something in the near future regarding this. Thanks!
