### ISSUE TITLE
dns-query explanation

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [cloudflare/cloudflare-docs#2381]
Hello.
On this page:
DNS over HTTPS (DoH)
https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families
where should i enter this URL?
https://security.cloudflare-dns.com/dns-query
In my Browser? But where?
Many people ddo not understand this.

Please would you describe this there or link to it? :)

Thanks.
:)

**Comment by BOYKHMER** [comment]
HELLO

**Comment by marciocloudflare** [comment]
Hi @Clemens-Ratte-Polle. In the docs we explain that the link is to be used with a DoH compliant client. This means that if you have one (like a compliant router) you'll se a place to insert that hostname. But we will update the language in the docs to make this clearer. Thanks!

**Comment by Clemens-Ratte-Polle** [comment]
Thanks. 
A Link directly after the URL to the relevant Doc would do it. :)
I do know where to put the DNS Query Link in my Browser Options, but many others not.

**Comment by marciocloudflare** [comment]
Solved in https://github.com/cloudflare/cloudflare-docs/pull/2497
