### ISSUE TITLE
Generating Blob Object URL Not Supported

### ISSUE THREAD

**Issue by MachineITSvcs** [cloudflare/cloudflare-docs#2382]
The example worker in "products/workers/src/content/examples/read-post.md" returns an error "TypeError: URL.createObjectURL is not a function" when no Content-Type header is defined because apparently generating a Blob Object URL is unsupported by workers at this time. Please see this discussion: https://community.cloudflare.com/t/blob-is-not-defined/233614/3

**Comment by jkup** [comment]
Hey! Sorry I didn't see this when it was assigned. We do have `Blob` support in Workers now, can you please let me know if there is any further issue!

**Comment by ImLunaHey** [comment]
@jkup did `createObjectURL` support ever get added to workers?
