### ISSUE TITLE
Cloudflare warp de-routes 127.0.0.1 How to return it?

### ISSUE THREAD

**Issue by keyadd** [cloudflare/cloudflare-docs#2384]
➜  ~ ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
ping: sendto: Can't assign requested address
ping: sendto: Can't assign requested address
Request timeout for icmp_seq 0
ping: sendto: Can't assign requested address
Request timeout for icmp_seq 1
ping: sendto: Can't assign requested address
Request timeout for icmp_seq 2
ping: sendto: Can't assign requested address
Request timeout for icmp_seq 3

mac os close warp can't ping 127.0.0.1 ?

**Comment by kkrum** [comment]
This was a product bug that should be resolved now
