### ISSUE TITLE
IPFS SSL Input Section has been removed.

### ISSUE THREAD

**Issue by pagreczner** [cloudflare/cloudflare-docs#2395]
### Expected Behavior
https://web.archive.org/web/20210922160400/https://www.cloudflare.com/distributed-web-gateway/
I expect there to be an input field at the bottom of this page that allows me to register ssl for a cloudflare dns ipfs link.

### Actual Behavior
https://www.cloudflare.com/distributed-web-gateway/
The above input field referenced in the archive link is no longer there. But the docs still point to this page: https://developers.cloudflare.com/distributed-web/ipfs-gateway/connecting-website#make-it-all-secure
```
Cloudflare will issue you a free SSL certificate for your.website, which allows users to load https://your.website. All you have to do is go to cloudflare-ipfs.com and scroll to the bottom, where it says "Connecting Your Website." Enter your domain into the text box and click Submit.
```

### Section that requires update
The above snippet requires update or the page it is pointing too needs to have the input field added back.

### Additional information
n/a

**Comment by haleycode** [comment]
This was resolved in the linked PR.
