### ISSUE TITLE
Document behavior and limits of calling `fetch()` to another Worker

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs#24]
"I couldn't find this in the docs currently.

We should document the behavior and limitations of making a fetch() call to a URL that matches a route that runs a Worker.

If the fetch URL is on the same zone as the original request, the request will go to the origin, and will not be handled by any other Worker.
If the fetch URL is on a different zone, the request will be handled by the Worker matching the route." https://github.com/cloudflare/workers-docs/issues/858

**Comment by kristianfreeman** [comment]
https://developers.cloudflare.com/workers/runtime-apis/fetch
