### ISSUE TITLE
[workers] Use esbuild templates as default

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/cloudflare-docs#2412]
As mentioned in this [HN thread](https://news.ycombinator.com/item?id=28643534), the default experience when using Wrangler with esbuild is significantly better than webpack, and since we no longer have a hard dependency on webpack for most projects in Wrangler, we should update the docs/templates (e.g. the [quickstarts page](https://developers.cloudflare.com/workers/get-started/quickstarts)) to use esbuild by default.

**Comment by koeninger** [comment]
I agree we should deprecate `type = "webpack"` in wrangler toml, but what on the linked page is referring to webpack?  The top suggestion is 

`wrangler generate my-app https://github.com/cloudflare/worker-template`

which makes a bare bones javascript project with no bundler.  

Please don't change that to esbuild.  Basic javascript is the lowest common denominator and can be used by anyone regardless of bundler, even if they're not aware of [custom builds](https://developers.cloudflare.com/workers/cli-wrangler/configuration#build) just by generating a single javascript file using whatever tooling they want.

**Comment by vlovich** [comment]
As someone not familiar with the intricacies of setting up custom builds, having a wrangler option to generate a default ESBuild config for me would save me some time.
