### ISSUE TITLE
[cloudflare-one] Device posture expects 11.6.0 instead of 11.6

### ISSUE THREAD

**Issue by cascadingstyletrees** [cloudflare/cloudflare-docs#2452]
### Expected Behavior
https://developers.cloudflare.com/cloudflare-one/identity/devices/os-version#on-macos

A command that returns `11.6.0`, since Device Posture configuration requires the patch version.

### Actual Behavior

```
$ defaults read loginwindow SystemVersionStampAsString
11.6
```

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/8b5e5836a1fb3d644bef9d36db4ee9e961990503/products/cloudflare-one/src/content/identity/devices/os-version.md#L34-L40

### Additional information

This command also will not work

```
$ sw_vers -productVersion
11.6
```

**Comment by kkrum** [comment]
Thanks for catching this error in our documentation! PR with Fix is linked.
