### ISSUE TITLE
Cloudflare Warp Setup Problem : There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected.

### ISSUE THREAD

**Issue by zezayne** [cloudflare/cloudflare-docs#2453]
I went to download the Setup file and then run it as a usual .msi package installer. After the UAC prompt (I choose yes ofc) , this error msg popped out. I went on YT for some quick troubleshooting but non of them worked. I tried changing the regedit key of the Msi.Package but it did not work. Pls help.  

Screenshot of the error : 
![image](https://user-images.githubusercontent.com/66861053/136141174-6357a4ec-bb70-4a0d-8dbc-3b6ea4f7db55.png)

**Comment by nort774** [comment]
Same problem 
Doesn't work in WINDOWS 11

**Comment by zezayne** [comment]
Pls help 😭

**Comment by phuho2020** [comment]
Vào 11:33, T.4, 6 Th10, 2021 zezayne ***@***.***> đã viết:

**Comment by kkrum** [comment]
Can you please follow up in https://community.cloudflare.com/ and via Send Feedback in the app?
