### ISSUE TITLE
Update 1.1.1.1 product logo

### ISSUE THREAD

**Issue by syeef** [cloudflare/cloudflare-docs#247]
https://github.com/cloudflare/cloudflare-docs/blob/afe84b90c45d1ed3c389153e44e6509c0318cd75/products/1.1.1.1/docs-config.js#L4

I think this should be using the 1^4 icon instead as that's the current app icon etc.
![image](https://user-images.githubusercontent.com/5339413/98278934-3089fa80-1f91-11eb-9b56-00192a345102.png)

**Comment by KimJ15** [comment]
@abracchi-tw can you confirm if this is an edit we should make? Thanks!

**Comment by abracchi-tw** [comment]
@syeef thanks for raising this. hope to get this changed ASAP

**Comment by abracchi-tw** [comment]
hi @syeef can you provide us with an .svg file? thanks!

**Comment by syeef** [comment]
`<svg width="20" height="26" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M16.899 6.598v1.98h1.65v-1.98h1.138v-1.43H18.55V.02h-1.553L13.28 5.009v1.59h3.619zm0-4.402v2.972h-2.25l2.213-2.972h.037zM2.778 5.102c-.82.143-1.652.214-2.485.213V8.5h6.105v17.483h4.437V1.209H7.534c-.142.755-.444 1.392-.905 1.911A5.59 5.59 0 014.96 4.394c-.65.33-1.378.567-2.182.708z" fill="#fff"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M16.899 6.598v1.98h1.65v-1.98h1.138v-1.43H18.55V.02h-1.553L13.28 5.009v1.59h3.619zm0-4.402v2.972h-2.25l2.213-2.972h.037zM2.778 5.102c-.82.143-1.652.214-2.485.213V8.5h6.105v17.483h4.437V1.209H7.534c-.142.755-.444 1.392-.905 1.911A5.59 5.59 0 014.96 4.394c-.65.33-1.378.567-2.182.708z" fill="url(#paint0_linear)"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M16.899 6.598v1.98h1.65v-1.98h1.138v-1.43H18.55V.02h-1.553L13.28 5.009v1.59h3.619zm0-4.402v2.972h-2.25l2.213-2.972h.037zM2.778 5.102c-.82.143-1.652.214-2.485.213V8.5h6.105v17.483h4.437V1.209H7.534c-.142.755-.444 1.392-.905 1.911A5.59 5.59 0 014.96 4.394c-.65.33-1.378.567-2.182.708z" fill="url(#paint1_linear)"/>
  <defs>
    <linearGradient id="paint0_linear" x1="9.99" y1=".02" x2="9.99" y2="25.983" gradientUnits="userSpaceOnUse">
      <stop stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="paint1_linear" x1="9.99" y1=".02" x2="9.99" y2="25.983" gradientUnits="userSpaceOnUse">
      <stop stop-color="#fff"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
  </defs>
</svg>`

@abracchi-tw this is the .svg code

**Comment by gganch** [comment]
Hi, @syeef I put the above svg and it renders like this: 

<img width="353" alt="Screen Shot 2021-04-15 at 8 26 47 PM" src="https://user-images.githubusercontent.com/19618017/114958590-ef8fef00-9e28-11eb-8e77-4954539d68ff.png">

Does this look good? In terms of size? If it is a little small would you mind providing me with an updated svg that would fit in a 48 x 48 px?

**Comment by syeef** [comment]
Hey @gganch - try this instead, thanks for quickly picking this up!

`<svg width="49" height="50" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M7 10.828c1.546.003 3.09-.129 4.612-.394 1.493-.263 2.844-.7 4.052-1.314a10.374 10.374 0 003.097-2.365c.856-.964 1.416-2.146 1.68-3.547h6.128v45.986h-8.236V16.74H7v-5.913zM37.825 16.888V13.21h-6.718v-2.95L38.007 1h2.882v9.555H43v2.656h-2.11v3.677h-3.064zm0-6.333V5.04h-.068l-4.108 5.515h4.177z" fill="#fff"/>
</svg>`

**Comment by syeef** [comment]
Looks like @gganch completed this. Will close. Thanks!
