### ISSUE TITLE
Setup repository for new Ubuntu release Hirsute 21.04 is not availbe 

### ISSUE THREAD

**Issue by EbrahimiAmirHosein** [cloudflare/cloudflare-docs#2487]
Just wanted to setup repository fore new Ubuntu version 21.04 Hirsute . and I ran this command `sudo apt install cloudflare-`
Turns out it's not available for new release : `hirsute release' does not have a Release file.`
[warp client - linux](https://github.com/cloudflare/cloudflare-docs/blob/production/products/warp-client/src/content/setting-up/linux.md)

**Comment by kkrum** [comment]
Take a look at https://pkg.cloudflareclient.com/packages/cloudflare-warp for the latest WARP Client for your distro. We'll be moving to a new mechanism for distribution in the future that will help with this.
