### ISSUE TITLE
[Warp Client] Cannot install .deb files on Pop OS

### ISSUE THREAD

**Issue by bitmamahq** [cloudflare/cloudflare-docs#2500]
### Expected Behavior
Install the .deb file successfully and i should be able to use the warp client.

### Actual Behavior
The .deb file has refused to install, i have tried installing all version for ubuntu and debian based linux distros. All of them keep throwing same error
![Screenshot from 2021-10-14 15-58-16](https://user-images.githubusercontent.com/43728975/137344549-d8136399-ebc4-4327-813e-78f2dad15108.png)

**Comment by haleycode** [comment]
Thanks for opening this issue, but we only take care of documentation improvements for developers.cloudflare.com in this repo. Please reach out to community.cloudflare.com for assistance.
