### ISSUE TITLE
CloudFlare Pages… support standard runtime.txt files in Python monorepo?

### ISSUE THREAD

**Issue by cmdlinebeep** [cloudflare/cloudflare-docs#2502]
(Filing this here, because there doesn't seem to be a place to file a ticket on the CloudFlare Pages build platform itself.  I posted roughly this same issue to the CloudFlare Developers Community but so far no traction on it.  I'm not really even sure that is the right place, there's no "Pages" sub-community).

**THE ISSUE**

I am trying to use a monorepo (to keep code DRY) that uses a Heroku backend (Python background worker task), but where the frontend is on CloudFlare Pages (using a custom build script). 

The problem is, CloudFlare Pages seems to have copied the Netlify build platform, which incorrectly parses ‘runtime.txt’ file contents. This file is a Python-specific file format invented by Heroku, which accepts the Python runtime in format like:

`python-X.Y`
 or
`python-X.Y.Z` 
(e.g. `python-3.7.11`)

However, the CloudFlare Pages build environment expects a format like:

`X.Y`

Where the `python-` string is removed and no minor revisions are supported.

This means I cannot use my monorepo for both services, and have to fork them to have one for Heroku where the file says like `python-3.7.11` and the CloudFlare Pages version says `3.7`

This seems silly since runtime.txt is a Heroku-invented concept.  If you guys copy that file, you should copy its existing syntax to not break projects that use it.  This is also extremely aggravating as a developer because, if you guys can't support the monorepo, now any code changes I make to one repo I have to go make the same changes in the other.

I cannot find that the CloudFlare Pages build system is open source, or I could submit a Pull Request.
If it is not open-source, is there any way the CloudFlare Pages build system could support the Heroku format so customers like me can keep their code DRY and not maintain edits in two otherwise-identical repos?

The fix for CloudFlare is easy and it's just to parse the `runtime.txt` file with regular expression `/(\d+\.\d+/` to limit it to the major and minor revision.  Can it get in?  Thank you.

**HISTORY**

FYI, I see that this "being-different-than-Heroku" has already caused some issue with confusion for your users (as well as noting this came from Netlify, which is who originally broke compatibility).

https://github.com/cloudflare/cloudflare-docs/issues/1119

**MORE HISTORY**

I have also filed a ticket with Heroku on this, but their basic argument is it doesn't make sense for them to back-modify their parser to be more flexible because it comes at the cost of less clarity to not have the `python-` prefix in there (i.e. without it there is no indication we are even talking about Python, since it's not in the filename either).  I think there is some resistance there too since they invented the format, they think the other companies should just be compatible.  I can't say I disagree! 

**DISCORD**
I've also searched on the Discord server for this and the closest activity I found was a CloudFlare employee said "looking up other providers it looks like they need to do python-3.7.x but x is actually filled in with a specific version number" but then instead of being compatible with those other providers, they just told the user to change it to just "3.7"

**Comment by Ekwuno** [comment]
Hey @cmdlinebeep I am so sorry it took so long to get back to you. We are aware of this issue and a ticket has been filed for it. Thank you so much for such a detailed explanation.

**Comment by jrf0110** [comment]
Hey folks. This is fixed in the Pages V2 Build System. I recommend if you need proper runtime.txt parsing, to use the V2 Build System
