### ISSUE TITLE
mTSL is available to all plans, outdated docs says otherwise

### ISSUE THREAD

**Issue by slig** [cloudflare/cloudflare-docs#2506]
### Expected Behavior
[This page](https://developers.cloudflare.com/firewall/cf-firewall-rules/api-shield) says that mTSL is available to all plans, but [this one](https://developers.cloudflare.com/cloudflare-one/identity/devices/mutual-tls-authentication?) (linked from the page before) says that it's available only to Enterprise plans.

### Section that requires update
Update this page https://developers.cloudflare.com/cloudflare-one/identity/devices/mutual-tls-authentication accordingly to state that mTSL is indeed available to all plans.

**Comment by abracchi-tw** [comment]
mTLS is available across plans with API Shield, but is only available for enterprise with Access. We've added a specification to both those pages to make it clearer, let me know if that helps.

Thanks!
