### ISSUE TITLE
[cloudflare-one] Improve instructions for trusting Cloudflare root cert in base macOS

### ISSUE THREAD

**Issue by derekcwhite** [cloudflare/cloudflare-docs#2512]
### Expected Behavior
There are four steps in [Install the Cloudflare certificate -> macOS -> Base Operating System](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert#base-operating-system). The first three show the reader how to install the Cloudflare root certificate into the macOS System keychain via the command line.

Not all applications use the System or login keychains, however, and the supplied versions of python3 and ruby, for example, were built using LibreSSL. The macOS version of LibreSSL expects all of your certificates to be in a single file, `/private/etc/ssl/cert.pem`

```
➜  ~ which ruby
/usr/bin/ruby
➜  ~ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
➜  ~ curl -Lks 'https://git.io/rg-ssl' | ruby
Here's your Ruby and OpenSSL environment:

Ruby:           2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
RubyGems:       3.2.28
Bundler:        2.2.28
Compiled with:  LibreSSL 2.8.3
Loaded version: LibreSSL 2.8.3
SSL_CERT_FILE:  /private/etc/ssl/cert.pem
SSL_CERT_DIR:   /private/etc/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       success ✅
ERROR:  SSL verification error at depth 1: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/ST=California/L=San Francisco/O=Cloudflare, Inc/CN=Cloudflare for Teams ECC Certificate Authority to your local trusted store
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅

Hooray! This Ruby can connect to rubygems.org. You are all set to use Bundler and RubyGems. 👌
```
Step 4 should instruct the reader how to add the Cloudflare root certificate to the macOS LibreSSL CA certificate store.

### Actual Behavior
The command in Step 4 is:

 ```bash
sudo cat Cloudflare_CA.crt >> /usr/local/etc/openssl/cert.pem
 ```
 
Here, we have a command that takes a binary .crt file, doesn't maintain the correct permissions while redirecting the output of the cat command, redirects the binary file onto a text-formatted .pem file, and finally, it's not even the correct CA certificate store. (For fresh macOS installs, /usr/local/etc/openssl/cert.pem won't even exist) 

### Section that requires update
The correct commands should be closer to: 

 ```bash
sudo cp /private/etc/ssl/cert.pem /private/etc/ssl/cert.pem.orig
sudo cp <Cloudflare_CA.pem> /private/etc/ssl/certs/Cloudflare_CA.pem
sudo sh -c "cat /private/etc/ssl/certs/Cloudflare_CA.pem >> /private/etc/ssl/cert.pem"
 ```

### Additional information
Setting SSL_CERT_DIR and SSL_CERT_FILE via environment variables is not supported in LibreSSL.

Anything that involves downloading alternate builds of ruby, python, openssl, etc should likely not be considered part of the base operating system and are addressed in other parts of install-cloudflare-cert.md. All of the Apple-supplied utilities that don't use the Trust Stores in the macOS keyschains are going to use `/private/etc/ssl/cert.pem`

PR to follow.

**Comment by abracchi-tw** [comment]
hey @derekcwhite we're tracking this internally. thanks!
