### ISSUE TITLE
Query on POST zones/{zone_id}/firewall/rules

### ISSUE THREAD

**Issue by spongenee** [cloudflare/cloudflare-docs#2516]
### Unclear Behavior

I was referring to the [documentation](https://developers.cloudflare.com/firewall/api/cf-firewall-rules/post) when trying out the API to perform actions on CloudFlare Firewall Rules.

I can successfully get the rules but could not figure out how to create a new rule.

Specifically, I have questions in what the **Filter identifier** refers to.

In the [example](https://github.com/cloudflare/cloudflare-docs/blob/production/products/firewall/src/content/api/cf-firewall-rules/post.md), id strings under filter object are required parameters, but I have no clue of the logic how they should be generated!
```
curl -X POST \
     -H "X-Auth-Email: user@cloudflare.com" \
     -H "X-Auth-Key: REDACTED" \
     -H "Content-Type: application/json" \
     -d '[
  {
    "filter": {
      "id": "b7ff25282d394be7b945e23c7106ce8a"
    },
    "action": "allow",
    "description": "do not challenge login from office"
  },
  {
    "filter": {
      "id": "c218c536b2bd406f958f278cf0fa8c0f"
    },
    "action": "challenge",
    "description": "challenge login"
  },
  {
    "filter": {
      "id": "f2a64520581a4209aab12187a0081364"
    },
    "action": "js_challenge",
    "description": "JS challenge site"
  },
  {
    "filter": {
      "id": "14217d7bd5ab435e84b1bd468bf4fb9f"
    },
    "action": "allow",
    "description": "allow API traffic without challenge"
  }
]' "https://api.cloudflare.com/client/v4/zones/d56084adb405e0b7e32c52321bf07be6/firewall/rules"
```

I appreciate any feedback from your side! Thank you very much.

**Comment by pedrosousa** [comment]
Hello, @spongenee 

Filters are API-only, separate objects that you will have to create beforehand using the Cloudflare Filters API:
https://developers.cloudflare.com/firewall/api/cf-filters/what-is-a-filter

When you [create a filter using a POST request](https://developers.cloudflare.com/firewall/api/cf-filters/post), the response will contain the filter identifier you need to create the firewall rule.

We'll review the documentation page you mentioned to highlight this relationship between filters and firewall rules.
