### ISSUE TITLE
API Example to create Spectrum App

### ISSUE THREAD

**Issue by msiherb** [cloudflare/cloudflare-docs#2537]
### Expected Behavior
https://developers.cloudflare.com/spectrum/how-to/cname-origins

On the above page, the API Example to create Spectrum Apps is:  

`curl -X POST 'https://api.cloudflare.com/client/v4/zones/{ZONE_ID}/spectrum/apps' \
-H "Content-Type: application/json" \
-H "X-Auth-Email: email" \
-H "X-Auth-Key: key" \
--data '{"dns":{"type":"CNAME","name":"spectrum-cname.example.com"},"ip_firewall":false,"protocol":"tcp/22","proxy_protocol":"off","tls":"off","origin_dns": {"name": "cname-to-origin.example.com", "ttl": 1200}, "origin_port": 22}'`

The `origin_dns`  field contains a FQDN but as per the following API Doc, the field `origin_direct` can take only `IP Addresses` 

https://api.cloudflare.com/#spectrum-applications-create-spectrum-application

Please advise which doc is accurate ? and can origin_direct take FQDN instead of an IP address.

Thank you,

**Comment by angelampcosta** [comment]
Thanks for letting us know @msiherb . We will address this issue, and you should see updated content soon!
