### ISSUE TITLE
Broken Link in cloudflared tunnel service docs

### ISSUE THREAD

**Issue by velocity23** [cloudflare/cloudflare-docs#2539]
### Expected Behavior
At https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service the link to the configuration file reference is broken, it should link to https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file.

### Actual Behavior
It links to https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config/ which does not exist.

### Section that requires update
"Before you start" section
https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/connections/connect-apps/run-tunnel/run-as-service.md

### Additional information
N/A

**Comment by KimJ15** [comment]
The broken link is now fixed. Closing as complete.
