### ISSUE TITLE
How to read part of the JSON response data after the POST request is sent

### ISSUE THREAD

**Issue by huajiqaq** [cloudflare/cloudflare-docs#2579]
Expected Behavior
When sending JSON data with POST (https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/post-json.md)
The Code data in the JSON data should be displayed. E.g. 200 or 404 
Actual Behavior
Return to the Response.code data and click the send button on the right to display it as empty.

Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/examples/post-json.md

**Comment by lukeed** [comment]
There's no reason to put a status code in the JSON request and/or response data. The purpose of the example is just to show how to parse a Request body, whatever it may contain.
