### ISSUE TITLE
How to read the data in json [ ]

### ISSUE THREAD

**Issue by huajiqaq** [cloudflare/cloudflare-docs#2593]
I previewed all your documents and found that there was no information about how to read the json data in json [ ] using JSON. parse to parse the key data in JSON [ ]. The following is the JSON parse data. Ask how to parse the key data. 
{"code":200,"num":1,"folder_id":"d","folder_path":"\/","results":[{"key":"f518619886","status":1}]}

**Comment by KimJ15** [comment]
For information about parsing json data, refer to https://developers.cloudflare.com/logs/tutorials/parsing-json-log-data. For additional support, you might visit community.cloudflare.com. For additional documentation feedback, feel free to open a new issue!
