### ISSUE TITLE
Content-Type header missing from QR Code Worker Example

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs#26]
"The QR code example located here: https://developers.cloudflare.com/workers/tutorials/build-a-serverless-function seems to be missing the correct Content-Type header.

Here's what the example code looks like:

const generate = async request => {
  // ...
  return new Response(qr_png, { headers })
}
The paragraph right above it mentions the header that should be there, but the code doesn't match.

By default, the QR code is generated as a PNG. Construct a new instance of Response, passing in the PNG data as the body, and a Content-Type header of image/png: this will allow browsers to properly parse the data coming back from your serverless function, as an image:"

https://github.com/cloudflare/workers-docs/issues/965

**Comment by kristianfreeman** [comment]
Closed with #296
