### ISSUE TITLE
Cloudflare Pages: Slow build initialization is an unlisted known issue

### ISSUE THREAD

**Issue by knupska** [cloudflare/cloudflare-docs#2606]
### Expected Behavior
The documentation lists known issues of the current Cloudflare Pages implementation:
https://developers.cloudflare.com/pages/platform/known-issues

This information is extremely helpful for saving time avoiding blockers when considering migrating from another provider.
It also prevents customers from repeatedly reporting such issues.

### Actual Behavior
The documentation does not list "slow build initialization" as an issue, which has been explicitly stated as a known issue here:
https://community.cloudflare.com/t/cloudflare-pages-build-so-slow/314832/12
> It’s a known issue that will be fixed at some point.

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/platform/known-issues.md

**Comment by lukeed** [comment]
While it's certainly not ideal, the slow build initialization is not _an issue_. Everything on this page is about unsupported features, default behaviors/values that may need tweaking, or DNS-related items. There's nothing that can be done or changed so avoid the boot-up time. It's being worked on now, though!

**Comment by knupska** [comment]
@lukeed I understand that it's possible to play semantics with "what it is", but I'd say that it's also "not ideal" to simply not mention it anywhere nor the fact that there are plans to improve it.

By leaving it up to developers to discover when they do their first comparison build between providers, they're obviously going to raise it as I did on the forums, and then they receive a less than friendly welcome when doing so (with the discussion being immediately shut down like I was "at fault" and then locked).

I understand that you may not want to inadvertently advertise competitor products as better (as you're very much working to improve the solution), but in my case a simple build takes 2+ minutes longer on Cloudflare, which for us anyway is "an issue", so much so that we can't consider using the service until it improves.

Ultimately, since I'd read the "known issues" list before doing my testing, had it been listed I would have been able to avoid spending that time only to "discover" something that Cloudflare are seemingly well aware of (no matter how it is categorised).

Perhaps a new section of the docs called "Not Ideal" or "Things we're working to improve".

**Comment by kaishiro** [comment]
As someone who is currently using other static hosts (e.g. Netlify, Vercel) on a daily basis and is always on the lookout for alternatives, I find this dismissal by @lukeed to be very concerning. I find it completely incongruous that you could state that it is both _not an issue_, while also stating that you're working on it. Which is it?

I'm a big fan of Cloudflare, and am excited about where things are heading with the advent of Pages and Workers - it's a powerful combination. But dismissing actual concerns like this doesn't seem the way to build confidence in your products.

**Comment by lukeed** [comment]
It's a high priority and it's something actively being worked on. But nothing is broken nor is anything at risk of being broken based on a configuration value...which is what the rest of the section is describing.

I can ask the Pages team if they want to list it here, but no one is hiding this or trying to sweep it away. Again, it's very well known. But, for me, it's not an "issue" in that it's not a missing feature or going to break your app.

**Comment by kaishiro** [comment]
Thanks @lukeed. I think the issue is one of audience. I believe you when you say it's well known within the Pages team - but surely the audience of this section is public facing users looking to use Pages as a product. Assuming that to be the case - and being directly in that target demographic - this is an issue that I would like to have known ahead of time without having to conduct the investigation on my own. Just my two cents.
