### ISSUE TITLE
External links not opening in new tabs

### ISSUE THREAD

**Issue by londonzhang** [cloudflare/cloudflare-docs#2629]
### Expected Behavior
Expected links to open in a new tab in Chrome.

### Actual Behavior
The link is currently opening in the existing tab.

### Section that requires update
https://developers.cloudflare.com/pages/

### Additional information
![image](https://user-images.githubusercontent.com/18485116/140187373-b6ddf387-128f-4a31-ac5f-0d1214385734.png)

**Comment by kodster28** [comment]
Howdy @londonzhang 👋 , I understand the thought, but our preference is to not make decisions that force the user into a specific way of doing tasks.

If we always set external links to open in a new tab, you don't have a choice about it. If we leave them as they are, you have a choice whether to open in your window or right click and open in a new tab.

Thanks for the feedback though! If we see enough comments like this, we'll re-evaluate our strategy.

**Comment by kodster28** [comment]
Some context on this issue.

This appears to be relatively common across other company's documentation and -- while not opening in a new tab -- seems to be useful b/c it indicates that it is external content:
- https://cloud.google.com/kms/docs/hsm
- https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-portal

**Comment by kodster28** [comment]
If we want to open those in new tabs, that'd involve some updates to the Docs Engine. Right now, we write 99% of our docs in Markdown... which doesn't allow us to specify new tab behavior w/o switching into HTML formatting.

**Comment by kodster28** [comment]
Not opposed to the idea of updating the Docs Engine... but I can tell you that'd likely be relatively low on our list of priorities for Marketing Engineering (who helps us with those sorts of things).

So, the end result would either be that we could submit a ticket to Marketing Engineering (with the caveat noted above) or your team could update the Docs Engine.

**Comment by kodster28** [comment]
Going ahead to close this, but feel to re-open if needed.
