### ISSUE TITLE
Documentation could be clearer about where noTLSVerify option can be used

### ISSUE THREAD

**Issue by kierenj** [cloudflare/cloudflare-docs#2649]
### Expected Behavior
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#noTLSVerify

Simply says you can have an option called `noTLSVerify`, doesn't say where it can be placed. 

### Actual Behavior
Googling has lots of people saying to use `no-tls-verify`, which is wrong. I tried 10 different combinations, each of which was silently ignored, before finding https://github.com/cloudflare/cloudflared/issues/277 .

### Section that requires update
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress

### Additional information
Perhaps an example with all options? Or each option could have a breakdown of which parts of the yaml structure they would be valid in?

**Comment by kierenj** [comment]
(It says "inside of an ingress rule" - not "inside the `originRequest` part of an ingress rule". I'm not sure if the latter is correct though?)

**Comment by abracchi-tw** [comment]
hey @kierenj thanks so much for flagging. we've now added more details about the `originRequest` rule being necessary for properties such as `noTLSVerify`, and added further explanations on the example config file we provide https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#origin-configuration 

Hope this helps!
