### ISSUE TITLE
When Universal SSL is disabled, it can not be enabled again.

### ISSUE THREAD

**Issue by beauwilliams** [cloudflare/cloudflare-docs#2650]
### Expected Behavior
I would expect I can enable it again

### Actual Behavior
Getting 1005 internal error trying to do so
### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by WalshyDev** [comment]
This sounds like an issue to be raised rather than an issue with documentation.

Can you please open a ticket and then post the ticket ID on the community forums (https://community.cloudflare.com) so it can be elevated.

**Comment by kodster28** [comment]
Howdy @beauwilliams, going ahead and closing this out since @WalshyDev provided the appropriate guidance.
