### ISSUE TITLE
Add line number to the exception in the log

### ISSUE THREAD

**Issue by amro80** [cloudflare/cloudflare-docs#2657]
### Section that requires update
https://developers.cloudflare.com/workers/learning/logging-workers#view-logs-from-the-dashboard

### Additional information
can you please add line number where the error / exception happened in the script. below is a example of the log from dashboard, where it shows part of the log in JSON format

  "outcome": "exception",
  "scriptName": null,
  "exceptions": [
    {
      "name": "SyntaxError",
      "message": "Unexpected token < in JSON at position 0",
      "timestamp": 1636402017010
    }
  ],

**Comment by irvinebroque** [comment]
Closing in favor of https://github.com/cloudflare/workers-sdk/issues/2613
