### ISSUE TITLE
Cloudflare Access/Teams multi-level subdomain protection doesn't work

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflare-docs#2667]
### Expected Behavior
cctv.secret.domain.com should be redirected to Cloudflare Access.

### Actual Behavior
`ERR_SSL_VERSION_OR_CIPHER_MISMATCH` on the browser.
![image](https://user-images.githubusercontent.com/298208/141041991-877203f0-872b-464d-b90f-d01a6b98d3fc.png)

### Section that requires update
[Protect multi-level subdomains
](https://developers.cloudflare.com/cloudflare-one/policies/zero-trust/app-paths#protect-multi-level-subdomains)

More like, it needs some update on the Cloudflare Server to facilitate multi-level subdomains.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kennyj42** [comment]
Hey Haneef,

I think this could be a deeper configuration issue. I'd recommend opening a support ticket. I'll double check that we're not missing something in our Documentation for this.

**Comment by haneef95** [comment]
Yes @kennyj42, Cloudflare Advanced Certificate Manager is required to achieve this:

> Cover more than one level of subdomain.
https://developers.cloudflare.com/ssl/edge-certificates/advanced-certificate-manager
