### ISSUE TITLE
transparent A/B on same URL?

### ISSUE THREAD

**Issue by avianna** [cloudflare/cloudflare-docs#2693]
https://github.com/cloudflare/cloudflare-docs/blob/2c7376e6aaf67e3778ad17932907f53157bafe7a/products/workers/src/content/examples/ab-testing.md?plain=1#L20

In the A/B example, it references the test as running on `/control/somepath`, and the control URL being `/control/sompath`. Not sure if this was an intentional typo. 

What would happen if I actually need the control to be `/control/somepath`? When it goes to fetch the control response, wouldn't it hit the worker again, and well, infinitely loop?

In my own testing, it seems like I need 3 different paths/URLs to accomplish an A/B test:
- entry URL (entry point for CF worker)
- test URL
- control URL

Am I doing something wrong?

**Comment by kristianfreeman** [comment]
Hey @avianna! This is great feedback. The example is definitely not as clear as it should be. I'm going to spend some time on making this example more approachable, as it's a use-case we definitely want to encourage people to explore on Workers. Thanks!
