### ISSUE TITLE
Document what happens on `wrangler publish` / when you upload a new script 

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs#27]
"(Based on experience with other platforms) lot of customers expect downtime or some sort of reboot time or significant cold start when a new Worker is uploaded. We should explain (either in the How it Workers section), or under the wrangler publish command what happens to existing Workers, or inflight requests when you upload a new script, and hence why users shouldn't experience downtime."
https://github.com/cloudflare/workers-docs/issues/654

**Comment by kristianfreeman** [comment]
https://developers.cloudflare.com/workers/learning/how-workers-works would be a good place for this - maybe link to the new section from `wrangler publish` docs
