### ISSUE TITLE
Add more info about AWS SSH

### ISSUE THREAD

**Issue by wifiuk** [cloudflare/cloudflare-docs#2700]
### Expected Behavior
Setting up SSH via Cloudflare, if you follow the guide, you are still unable to connect to AWS SSH due to needing the SSH Cert that is in authorised keys when setting up AWS SSH access.

You need to show additional steps to get the access working.

**Comment by haleycode** [comment]
Given the age of this ticket we're closing it out for now. Feel free to raise a new issue if needed. Thanks!
