### ISSUE TITLE
ES Modules Starter for Typescript and Durable Objects

### ISSUE THREAD

**Issue by danboyle8637** [cloudflare/cloudflare-docs#2736]
### Expected Behavior
https://developers.cloudflare.com/workers/learning/using-durable-objects

I am just referencing this part of the docs because it's the current documentation for Durable Objects. 

I was using the current Typescript starter: 
https://github.com/cloudflare/worker-typescript-template

But according to the docs you can't create a durable object in a service worker based worker and have them communicate.

I also followed the wrangler.toml file setup in the new blog post about es modules: 
https://blog.cloudflare.com/workers-javascript-modules/

And I can't get the TS starter to work with es module syntax and therefore can't use a durable object in this worker. 

There are no examples of referencing a durable object from another worker either... I'm confused about this.

I have played with this starter:
https://github.com/cloudflare/worker-typescript-template

This works for me. 

So is this the recommended starter now for es module syntax and durable objects?

I see some use webpack and the other uses rollup.

It's confusing as there seems to be no base way to get a es module worker with Typescript created. I am sure I'm missing something but some updated docs would be very helpful.

**Comment by koeninger** [comment]
Did you try https://github.com/cloudflare/durable-objects-typescript-rollup-esm ?

**Comment by kristianfreeman** [comment]
Hey @danboyle8637! The template that @koeninger linked above is a great place to start with TypeScript, ES Modules, and Durable Objects. It is linked in that guide, but I'd love to hear more if you have any feedback about how we can encourage developers to use that template for DO/TS/ESM projects.

**Comment by haleycode** [comment]
Given the age of this issue, I'm closing it out for now. Happy to reopen if we get more feedback!
