### ISSUE TITLE
OkHttp and certificate pinner 

### ISSUE THREAD

**Issue by munir700** [cloudflare/cloudflare-docs#2751]
I have successfully communicated with the server by using SSL the way you mentioned in the tutorial guide.  Here is the [link](https://developers.cloudflare.com/ssl/client-certificates/configure-your-mobile-app-or-iot-device) which I followed to the configuration on an Android device.

Now Android offers a short and flexible way for SSL interaction for OkHttp client. Developers need to put sha256 pins and make requests.  Can Cloudflare accept pins instead of the old school way by using TrustManager?
Here is an example for CertificatePinner
`val certificatePinner = CertificatePinner.Builder()
       .add(
               "www.example.com",
               "sha256/ZC3lTYTDBJQVf1P2V7+fibTqbIsWNR/X7CWNVW+CEEA="
       ).build()

val okHttpClient = OkHttpClient.Builder()
       .certificatePinner(certificatePinner)
       .build()`

**Comment by munir700** [comment]
@kodster28 is there any way how to make connections other than trust manager for Android applications

**Comment by kodster28** [comment]
Howdy @munir700, I'm looping in the engineering team b/c this is outside my area of expertise.

**Comment by maxnystrom** [comment]
> OkHttp client.

Your example code resembles the OkHTTP documentation here 
https://square.github.io/okhttp/https/#certificate-pinning-kt-java

The pins in these examples are for a server certificate and not a client certificate like what is used in the Cloudflare Developer Docs linked above (https://developers.cloudflare.com/ssl/client-certificates/configure-your-mobile-app-or-iot-device).

Pins are not a substitute for client certificates nor are they sent in a request. Cloudflare also strongly discourages pinning to Cloudflare-managed certificates, see
https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ#h_3k3bHm83HfwEKwYEeKg6v8

If you're looking to implement mTLS with API Shield issued certificates, the client authentication unit tests for OkHTTP should point you in the right direction. https://github.com/square/okhttp/blob/master/okhttp/src/test/java/okhttp3/internal/tls/ClientAuthTest.java
