### ISSUE TITLE
Cloudflare Access + Keycloak (SAML) Error

### ISSUE THREAD

**Issue by rileyjnevins** [cloudflare/cloudflare-docs#2760]
### Expected Behavior
The documentation (link below) for adding Keycloak as an identity provider for SAML via Cloudflare access does not work as wrote. Upon following the instructions users are left with an "invalid requester" error, which is often the result of improper configuration. I'm not positive at this time what the solution is, was wondering if anyone has had success doing this?

### Actual Behavior
When testing the new identity provider via Cloudflare Access dashboard, an "invalid requester" shows on Keycloak's end. 

https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/identity/idp-integration/keycloak.md

**Comment by jroyal** [comment]
Out of curiosity, does your log say anything more specific? From some random googling this looks like it might be related to signing but not sure.

**Comment by rileyjnevins** [comment]
Here are the most recent logs (generated after an unsuccessful login): 
![image](https://user-images.githubusercontent.com/64431703/143945095-b4ed48d1-9fbb-47aa-9681-7f40ebaa9237.png)

NoVNC makes it a bit hard to view the longer lines, if this image does not suffice I can try to export my log file to a pastebin. 

I'd agree it's signing related, looking at the error message.

**Comment by jroyal** [comment]
Thanks for confirming. I was able to get a test keycloak setup and figured out what was missing. If you turn on `Client signature required` in Keycloak and enable `Sign SAML authentication request` in the Access dashboard then you also need to upload our PEM so keycloak can verify the incoming request. 

Go to <teamdomain>.cloudflareaccess.com/cdn-cgi/access/certs and get the most recent public cert. You can import that into the SAML keys tab on keycloak.

I'll go figure out how to update the docs to include that.

**Comment by rileyjnevins** [comment]
> Thanks for confirming. I was able to get a test keycloak setup and figured out what was missing. If you turn on `Client signature required` in Keycloak and enable `Sign SAML authentication request` in the Access dashboard then you also need to upload our PEM so keycloak can verify the incoming request.
> 
> Go to .cloudflareaccess.com/cdn-cgi/access/certs and get the most recent public cert. You can import that into the SAML keys tab on keycloak.
> 
> I'll go figure out how to update the docs to include that.

Fantastic, thank you so much for the clarification!
