### ISSUE TITLE
Svelte getting started only produces half-working deployment

### ISSUE THREAD

**Issue by Hades32** [cloudflare/cloudflare-docs#2797]
### Expected Behavior
When I follow https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/framework-guides/deploy-a-svelte-site.md I expect the same features to work as when I run `npm run dev`.

### Actual Behavior
The static website and the counter work fine, but the TODO fails with an exception (in the console).

### Section that requires update
Probably more config needed for https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/framework-guides/deploy-a-svelte-site.md

### Additional information
The latest deployment I tried can be found here https://github.com/Hades32/the-long-poll/tree/f07bdf921baae9622a0dd8c86a4720e71a81b074

**Comment by kristianfreeman** [comment]
@lukeed can you take a look at this?

**Comment by mbanerjeepalmer** [comment]
Looked at https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/framework-guides/deploy-a-svelte-site.md today.

There are a couple of issues that suggest the page needs reworking for SvelteKit.
- SvelteKit's default adapter is now `adapter-auto`, not `adapter-static`.
- It's not been updated to reflect the new default SvelteKit settings.
- You still need to explicitly set the `NODE_VERSION` even after selecting SvelteKit by default. (Arguably this is a design flaw and should just be handled automatically by Cloudflare.) This isn't mentioned in the SvelteKit section, only in the plain Svelte section.

Additionally the overview page makes no mention of SvelteKit: https://developers.cloudflare.com/pages/platform/build-configuration/

Happy to help or provide further feedback.

**Comment by Ekwuno** [comment]
This issue has been resolved with our SvelteKit framework guide rewrite. https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/#deploying-with-cloudflare-pages. Here is a demo https://svelte-kit-test-app.pages.dev/todos
