### ISSUE TITLE
Webpack usage and npm dependencies could use more explanation

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/cloudflare-docs#28]
"The docs are not very clear on how to use npm dependencies.

The answer (I believe?) is to use webpack. There is a page on webpack:

https://developers.cloudflare.com/workers/tooling/wrangler/webpack/

But this page is also not very clear -- it seems to assume the reader is already deeply familiar with webpack, and only provides some advanced details.

We should improve the doc so that people new to webpack don't need to go learn webpack first, and highlight better than this is the way to use npm dependencies."

**Comment by kristianfreeman** [comment]
cc @xortive who might be best suited to rewriting this page w/ new custom builds support
