### ISSUE TITLE
Argo Tunnel "multiple-hostnames" page outdated/misleading

### ISSUE THREAD

**Issue by frusznyak** [cloudflare/cloudflare-docs#282]
The information on this page: [argo-tunnel -> multiple-hostnames](https://github.com/cloudflare/cloudflare-docs/blob/cb299aba47781a4969e3a15b2c10cdc2eeba019c/products/argo-tunnel/src/content/reference/multiple-hostnames.md) seems outdated, since [ingress rules](https://developers.cloudflare.com/argo-tunnel/routing-to-tunnel/ingress#matching-traffic) are a thing.

The outdated page in question does not seem to be linked anywhere in the docs (as far as i could find) but appears to still be accessible from the web:
https://developers.cloudflare.com/argo-tunnel/reference/multiple-hostnames

Since this is still the first result when you google for "argo multiple hosts", i think this should either be changed, removed or redirected to reflect the new possibilities with ingress rules.

_Update on 2020-12-04_: The URL for the ingress rules [has been changed](https://github.com/cloudflare/cloudflare-docs/commit/19b0bf39b3de3c184e2795d21bb20174516c62fa) as well, without adding an redirect, the new correct link is now [this](https://developers.cloudflare.com/argo-tunnel/configuration/ingress)

**Comment by abracchi-tw** [comment]
Hi @frusznyak, thanks for raising this issue. We will take down old documentation sections soon. Moving forward, for all questions regarding Argo Tunnel, please refer to this section of the Cloudflare for Teams documentation: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps.
