### ISSUE TITLE
Coinomi

### ISSUE THREAD

**Issue by Mtan6666666** [cloudflare/cloudflare-docs#2840]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by CEOSPFUTURE2** [comment]
Hello my name is warith akbar my name  warith akbar . I'm the owner of fact
News Network and owner of S&P 500 future.   I need a tec to my headquarters
asap to help secure my company.

**Comment by CEOSPFUTURE2** [comment]
I've tried all that. . Learning curve. Would take me a year to get up to
speed.  If you don't do more to help and I'm asking for your help send
someone to my headquarters asap so I don't have to out search the work. It
would be a good idea to do all you can. And get on the phone and make some
phone calls.  I got some passed of GOP trying to shut me down.
Check my LinkedIn post . A call of action is in it.  Please read.  This is
the time in your life to act

**Comment by kodster28** [comment]
Howdy @Mtan6666666, closing since there isn't enough info to take action on this ticket.
