### ISSUE TITLE
Typo in browser isolation docs

### ISSUE THREAD

**Issue by ryan-mars** [cloudflare/cloudflare-docs#2852]
https://github.com/cloudflare/cloudflare-docs/blob/e54ca77d4a228c2b7ecb050d629fa619a90016ce/products/cloudflare-one/src/content/policies/browser-isolation/configuration.md?plain=1#L44

I believe this sentence is a typo?

> Right-click context menu be simplified

**Comment by kodster28** [comment]
Howdy @ryan-mars, thanks for the comment!

That's actually a repo that's no longer maintained and we will be removing shortly. The updated docs are https://developers.cloudflare.com/cloudflare-one/policies/browser-isolation
