### ISSUE TITLE
Typo on WAF overview page

### ISSUE THREAD

**Issue by Andrew-Cottrell** [cloudflare/cloudflare-docs#2855]
There is consecutive repetition of the word "our" in the following sentence
> Our powerful web application firewall is integrated with the rest **our our** leading cloud-delivered application security portfolio.

I expect the sentence should actually say
> Our powerful web application firewall is integrated with the rest **of our** leading cloud-delivered application security portfolio.

### Section that requires update
Top section, 2nd paragraph, of https://www.cloudflare.com/en-gb/waf/

### Additional information
I'm doubtful this specific repository is the correct place to report this particular typo, but I couldn't find anywhere better.

**Comment by kodster28** [comment]
Howdy @Andrew-Cottrell, I created a ticket for the team that handles our main www website.

Thanks for the comment!
