### ISSUE TITLE
Looks like the 'understanding the fetch event lifecycle' link is broken, not sure if the page still exists under a different name?

### ISSUE THREAD

**Issue by jgentes** [cloudflare/cloudflare-docs#2863]
https://github.com/cloudflare/cloudflare-docs/blob/b8ed174d90dbde030d65727d78165c6b986c1312/products/workers/src/content/runtime-apis/request.md?plain=1#L46

**Comment by WalshyDev** [comment]
Was removed in this commit - https://github.com/cloudflare/cloudflare-docs/commit/eaa85c706ff0f766d0b18d31a701094ec41b5df5#diff-9edacaf362b9f68c98a9b8f22f2cd10ba34acf2a025d5b1c6859bb60c927a8a4

**Comment by haleycode** [comment]
@WalshyDev are we okay to close this issue? Thanks!
