### ISSUE TITLE
[Images] Framework integration docs for Images

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#2864]
### Expected Behavior
Images to also have a "Integration with Frameworks" section like Image Resizing (https://developers.cloudflare.com/images/image-resizing/integration-with-frameworks).

### Actual Behavior
It does not have this currently.

### Section that requires update
https://developers.cloudflare.com/images/cloudflare-images

### Additional information
Now that you can serve Images from `/cdn-cgi/imagedelivery` it also deserves a page so people know how to link this with frameworks like NextJS. Obviously, the width x height doesn't really matter here but the whole "serving optimized images" of `next/image` is suitable for Images.

**Comment by sejoker** [comment]
Cloudflare Images take different approach to Image Resizing in terms of handling resizing parameters. It's managed through [predefined variants](https://developers.cloudflare.com/images/cloudflare-images/resize-images). So the custom loader approach for Next.js is not applicable here. I don't see much value to provide something like:

```js
import Image from "next/image";

const MyImage = (props) => {
  return (
    <Image
      src="https://imagedelivery.net/ZWd9g1K7eljCn_KDTu_MWA/083eb7b2-5392-4565-b69e-aff66acddd00/public"
      alt="Picture of the author"
    />
  );
};
```

Even with the ability to serve images first-party through `/cdn-cgi/imagedelivery` we need the remaining of the image url:

``````js
import Image from "next/image";

const MyImage = (props) => {
  return (
    <Image
      src="/cdn-cgi/imagedelivery/ZWd9g1K7eljCn_KDTu_MWA/083eb7b2-5392-4565-b69e-aff66acddd00/public"
      alt="Picture of the author"
    />
  );
};
```
```
