### ISSUE TITLE
Link to access-rules in Stream => Securing your Stream is broken link

### ISSUE THREAD

**Issue by Theaxiom** [cloudflare/cloudflare-docs#289]
On this page: https://github.com/cloudflare/cloudflare-docs/blob/production/products/stream/src/content/viewing-videos/securing-your-stream.md

There is a link to the following URL, which is a broken link/missing page: https://developers.cloudflare.com/stream/viewing-videos/access-rules

**Comment by KimJ15** [comment]
This issue has been resolved and links are functioning. Closing this PR.
