### ISSUE TITLE
Features that are still in beta should be visually marked as such

### ISSUE THREAD

**Issue by saibotsivad** [cloudflare/cloudflare-docs#2901]
### Expected Behavior

Some time after hearing the internet abuzz about Pages Functions, I finally got around to looking at [the docs](https://developers.cloudflare.com/pages/platform/functions) and thought everything was ready for production.

Nothing on the immediate reading of the page hinted that it was in beta.

### Actual Behavior

After wasting most of a day trying to bang things together that seemed like they should work, I got on the Discord chat server and asked design questions, and was then told Functions was still in beta.

Is it on the actual page? Yes. If you do a search for "beta" you'll find it, at the very end, as an *aside* inside a sentence about pricing and limitations.

### Section that requires update

Any feature that is still in "open beta".

### Additional information

Developers should not need to do a ctrl+f and search for "beta" on every page of every feature to know if something is in beta or considered ready for production.

It should be made abundantly clear when features are still in beta. For example, you could just add a badge:

![image](https://user-images.githubusercontent.com/91254/145517844-9680aa61-b1d4-4a04-8733-1a87a865be04.png)

Being very clear about what features Cloudflare internally considers "production ready" vs still in "open beta" is critical to building trust in the service offerings.

# Critical change

While adding a simple "badge" text to feature headers is technically simple, I believe that this is an indicator of something that needs to be taken on and fully embraced by internal culture, and not considered a simple "docs tweak" that can be public crowd-sourced.

**Comment by kristianfreeman** [comment]
This is a great idea! Right now, we're working on some new improvements to our docs engine that will make implementing this sort of UI easier. Putting it on the backburner for now 💤

**Comment by KimJ15** [comment]
Thanks for the feedback! We have a feature already designed and as part of another project. Closing this issue as a duplicate.

**Comment by saibotsivad** [comment]
@KimJ15 is that a feature that can be followed on Github somewhere (issues/project/etc), or is there some way to know when it is released?

If there's not a publicly trackable issue, I would rather that this ticket stay open so that I can know when it is actually resolved.
