### ISSUE TITLE
Pages: architecture target for custom build executables?

### ISSUE THREAD

**Issue by StephenHaney** [cloudflare/cloudflare-docs#2913]
### Expected Behavior
The docs have a lot of information about what tooling is available in the build env, but it doesn't specify the OS / architecture / shell. I'm trying to use a Rust built executable as my build step (it's committed to my repo), but I get an error when I try to run it on the server.

I'm building on an ARM Mac, so I probably need to compile it for some sort of x86 linux environment? I can figure this out by trial an error, but I'm new to cross compiling Rust and it will take me some time to figure out... so it'd be nice to have the answer available in the docs. Or, if it's the case, to know it's not supported.

### Actual Behavior
Is it possible to run custom executables as the build command? If so, what OS/architecture should we target?

### Section that requires update
https://developers.cloudflare.com/pages/platform/build-configuration

### Additional information
The error I get is `./scripts/build_script: 1: ./scripts/build_script: Syntax error: word unexpected (expecting ")")` which I believe is the error that you receive if you have an executable built for the wrong architecture or with the wrong shell assumptions.

**Comment by StephenHaney** [comment]
I was able to get my binary to run on the Cloudflare build server by using `cargo build --release --target x86_64-unknown-linux-musl`, using the `x86_64-unknown-linux-musl-gcc` linker.

**Comment by lukeed** [comment]
I'm not sure on the specifics (will find out), but I've been able to run `*_linux_amd64.tar.gz` executables in the pipeline
