### ISSUE TITLE
Log4j2 vulnerability rules missing from Changelog

### ISSUE THREAD

**Issue by rrampage** [cloudflare/cloudflare-docs#2915]
### Expected Behavior
In [Cloudflare's response post](https://blog.cloudflare.com/how-cloudflare-security-responded-to-log4j2-vulnerability/) it is mentioned that 2 rules were added to WAF:
- 2021-12-10 09:56 UTC - First WAF rule shipped to Cloudflare Specials ruleset
- 2021-12-10 10:44 UTC - Second WAF rule is live as part of Cloudflare managed rules
Is there a planned changelog entry for the same?

### Actual Behavior
I am unable to see it [in developer docs](https://developers.cloudflare.com/waf/change-log) (as of 2021-12-20)

### Section that requires update
Page: https://developers.cloudflare.com/waf/change-log
New section with details of emergency rules added as part of the Log4j2 mitigation

**Comment by pedrosousa** [comment]
Hi @rrampage 
Thank you for the heads-up. This is already being addressed and we will have a change log update soon.

**Comment by pedrosousa** [comment]
The new change log page is now available:
https://developers.cloudflare.com/waf/change-log/2021-12-10---emergency-release
