### ISSUE TITLE
Document link from rendered ssh page is not found

### ISSUE THREAD

**Issue by George-Miao** [cloudflare/cloudflare-docs#2928]
### Expected Behavior
Been trying to use argo tunnel with ssh web rendering supported. While debugging the connection, I found the document link in the falied-to-connect page is invalid. It links to https://developers.cloudflare.com/cloudflare-one/faq/tunnel/.

### Actual Behavior
I believe the page has been moved to https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/

### Section that requires update
Docs is fine. Whoever in charge of the CF teams/tunnel should update their error page.

### Additional information
Here is a screenshot of the page I mentioned.

![image](https://user-images.githubusercontent.com/38549822/145863948-9eb98dd6-0bbc-4dcf-9804-ae8b05d2d5ab.png)

**Comment by abracchi-tw** [comment]
@George-Miao the link should now successfully redirect to the correct page. thanks for flagging!
