### ISSUE TITLE
ایمیل 

### ISSUE THREAD

**Issue by jakooborooj** [cloudflare/cloudflare-docs#2957]
https://github.com/alemuro/terraform-aws-ses-email-forwarding/blob/master/dns_aws.tf

**Comment by jakooborooj** [comment]
دی ان اس ایمیل

**Comment by kodster28** [comment]
Howdy @jakooborooj, it doesn't look like this is enough context for us to address this issue atm, so closing it out for now.

If you have more context, could you re-open the ticket and provide it?
