### ISSUE TITLE
Cloudflare Pages directs bug reports to location that doesn't exist

### ISSUE THREAD

**Issue by JasonCook599** [cloudflare/cloudflare-docs#2987]
### Expected Behavior
The Pages known issues page should direct people to a place that actually exists for filing bug reports.

[Known Issues](https://github.com/cloudflare/cloudflare-docs/blob/7c9e9de3b12c5b1400775bd192078c1ec3650096/products/pages/src/content/platform/known-issues.md)

### Actual Behavior
The documentation says to post bug reports in the #pages-help channel on discord. This channel either does not exist or is not visible to new members.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
I discovered this issue while attempting to file a bug report for Pages. If anyone could provide me with the correct place to file a bug report, that would be appreciated.

**Comment by WalshyDev** [comment]
The discord channel was updated yesterday. It's now named #pages-general

There is a whole Pages category now where you can find the channel most relevant to you.

**Comment by JasonCook599** [comment]
And that is the correct place for filing bug reports?
