### ISSUE TITLE
crypto.subtle

### ISSUE THREAD

**Issue by Tobats1992** [cloudflare/cloudflare-docs#2990]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.
- []()[]()@Tobats1992 _

**Comment by kodster28** [comment]
Howdy @Tobats1992, looks like we don't have quiet enough info to act on this issue, so going ahead and closing for now.

Feel free to re-open with more specific instructions and we can look at solving your issue.
