### ISSUE TITLE
No instructions for Pop_OS (Ubuntu Impish/Hirsuite/Deb-11)

### ISSUE THREAD

**Issue by FOSS-Archives** [cloudflare/cloudflare-docs#2993]
### Expected Behavior
To be able to install "Cloudflare-warp" either as deb package for Deb-11 or an Ubuntu one

### Actual Behavior
Says it installs but can't find nor launch application like on Windows.

### Section that requires update
N/A

### Additional information
Perhaps a method for installing latest Debian version on Ubuntu could help those using current impish version? and those using Pop_OS

**Comment by FOSS-Archives** [comment]
https://github.com/cloudflare/cloudflare-docs/blob/production/products/1.1.1.1/src/content/other-ways-to-use-1.1.1.1/index.md 

Could be a suitable place?

**Comment by kkrum** [comment]
You can download the package directly from https://pkg.cloudflareclient.com/packages/cloudflare-warp for now. Note that we will be moving to a new distribution mechanism in the future and will plan to properly fix this then.

**Comment by FOSS-Archives** [comment]
I know it's closed now but could make one version that works on both of Ubuntu's yearly releases (Since there are only two) and then call it Ubuntu-Based installer to avoid confusion? 

Although it doesn't seem perfectly compatible with 21.10 after using Warp+DoH with Malware protection as of writing :/
