### ISSUE TITLE
Sf

### ISSUE THREAD

**Issue by mdsaimun3** [cloudflare/cloudflare-docs#3022]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @mdsaimun3, we'll need a bit more info to take action on this issue. Closing for now, but feel free to re-open if needed.
