### ISSUE TITLE
[Question] Where should I submit an issue (potentially) with Cloudflare pages ?

### ISSUE THREAD

**Issue by kevinadhiguna** [cloudflare/cloudflare-docs#3026]
Hi, I know this is not a repo about Cloudflare pages, but where should I submit an issue regarding Cloudflare pages?

Thanks.

**Comment by WalshyDev** [comment]
Hey, the Discord server is the best place. Invite is: https://discord.gg/cloudflaredev

**Comment by kevinadhiguna** [comment]
Thanks @WalshyDev !
