### ISSUE TITLE
"Skip inspection" tutorial clarification

### ISSUE THREAD

**Issue by wlabarron** [cloudflare/cloudflare-docs#3031]
The [Skip inspection for groups of applications](https://developers.cloudflare.com/cloudflare-one/tutorials/do-not-decrypt) tutorial in the Cloudflare for Teams (Gateway) documentation says "By default, Cloudflare Gateway creates a rule that includes the hostnames used by certain client applications, like Zoom or Apple's services, that rely on certificate pinning." ([src](https://github.com/cloudflare/cloudflare-docs/blob/33e21108fe03be8f16d8fe17d7a934c31ac1a9dd/products/cloudflare-one/src/content/tutorials/do-not-decrypt.md?plain=1#L12)).

I'm not aware of this default policy appearing in my account, or if it did, I must've deleted it long ago and I can't get it back. The closest I can find is under Settings > Network > Integrated Experiences, but that only applies to Microsoft 365.

It would be good to clarify whether this should be visible within the Teams Dashboard or not, and perhaps to make this guide more obvious during the setup process -- I spent quite a lot of time working out why Windows update and endpoint protection stopped working as no services were logging anything useful, but it turns out that the steps in this tutorial were what I needed to solve the issue.

**Comment by wlabarron** [comment]
I think the "creates a rule" might be referring to the [Do Not Decrypt application category](https://developers.cloudflare.com/cloudflare-one/policies/filtering/http-policies/application-app-types#do-not-decrypt-applications) which exists, but I don't think the relevant Do Not Inspect policy exists by default.

**Comment by haleycode** [comment]
Given the age of this ticket, I'm closing it out for now. Feel free to reopen if there's still a need for this change and we can reassess!

**Comment by ckuehl** [comment]
I had this same question when setting this up just the other day.
