### ISSUE TITLE
Raise max value size in Durable Objects from 32 KiB to 128 KiB

### ISSUE THREAD

**Issue by its-jman** [cloudflare/cloudflare-docs#3039]
### Expected/Actual Behavior/Section that requires update
https://developers.cloudflare.com/workers/platform/limits#durable-objects - Indicates limit of 32 KiB even though release notes indicate higher limit of 128 KiB

Release notes: https://community.cloudflare.com/t/2021-12-10-workers-runtime-release-notes/334982

**Comment by deadlypants1973** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/3048
