### ISSUE TITLE
Indicate the maximum supported Zola version

### ISSUE THREAD

**Issue by dbanty** [cloudflare/cloudflare-docs#3043]
### Expected Behavior

The [Zola guide](https://developers.cloudflare.com/pages/framework-guides/deploy-a-zola-site) shows you how to set a `ZOLA_VERSION` but doesn't indicate anywhere which versions work with CloudFlare. Indicating that 0.14.0 is the latest supported version would have saved me a bit of time.

### Actual Behavior

I assumed 0.14.0 was an out-of-date example only and then had to figure out why I was getting `GLIBC` errors when trying to deploy my page.

### Section that requires update

https://developers.cloudflare.com/pages/framework-guides/deploy-a-zola-site

### Additional information

Not sure where/how/if I can request that newer versions of Zola be supported. I naively built my new site with the latest version and now have to figure out how to downgrade before deploying it (or find somewhere else to deploy it which supports 0.15).

**Comment by Ekwuno** [comment]
Thanks for pointing this out @dbanty

**Comment by mikekasprzak** [comment]
How can we raise the outstanding issue with the Pages team? It's been an problem for over 6 months, and we're 6 versions behind.

**Comment by lukehsiao** [comment]
This is once again a problem with the latest versions of `zola`. What is the maximum supported version?
