### ISSUE TITLE
Broken link on SafeSearch instructions

### ISSUE THREAD

**Issue by mrbluecoat** [cloudflare/cloudflare-docs#3045]
### Expected Behavior
I tried to follow instructions for SafeSearch but I don't see a "SafeSearch card" and the "these instructions" link is broken

### Actual Behavior
Broken link

### Section that requires update
https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/policies/filtering/dns-policies/safesearch.md

**Comment by abracchi-tw** [comment]
hi there @mrbluecoat, great catch. the information has moved here: https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies-builder#safesearch

the link you listed now points to this page. thanks!

**Comment by mrbluecoat** [comment]
@abracchi-tw would this also work?

![image](https://user-images.githubusercontent.com/382164/148009831-156553a1-ae3e-4a5a-8d39-b9505022d690.png)
