### ISSUE TITLE
Web Analytics Intro is confusing

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#3085]
### Expected Behavior
The messaging about looking at zone analytics should not be confusing.

### Actual Behavior
The messaging is quite confusing and isn't clear that it is talking about more in-depth zone analytics.

### Section that requires update
On this page: https://developers.cloudflare.com/analytics/web-analytics

At the bottom it says:
> To view similar analytics for domains using Cloudflare's proxy (orange-clouded), navigate to the Analytics app and select Web Traffic Analytics. Web Traffic Analytics are available for Pro, Business, and Enterprise plans.

Talking about "Web Traffic Analytics" on a page titled "Web Analytics" is quite confusing. It also should just be clear this is an _additional_ thing and doesn't mean Web Analytics itself is paid (or cannot be used). This has caused confusion on the forums.

Alongside that, the instructions don't really make sense. "Analytics app" I believe is meaning the tab however there are Cloudflare Apps that can cause confusion here. There is also no "Web Traffic Analytics" tab it's just the "Traffic" sub-menu/tab (new/old navigation)

**Comment by kodster28** [comment]
Thanks for the feedback, @WalshyDev. This incredibly helpful!

**Comment by marciocloudflare** [comment]
Thanks for the feedback @WalshyDev. This was clean up in [PR-3172](https://github.com/cloudflare/cloudflare-docs/pull/3172) and should be live soon.
