### ISSUE TITLE
IPFS Pinning?

### ISSUE THREAD

**Issue by agowa** [cloudflare/cloudflare-docs#311]
Hi, could you please clarify if cloudflare is offering a service to pin resources in IPFS? E.g. To vouch for them to be available with good performance?
Currently the [pages](../blob/production/products/distributed-web/src/content/ipfs-gateway/index.md) only talk about you providing TLS certificates, but not about what other services can be utilized together with IPFS.

**Comment by KimJ15** [comment]
👋 @agowa338 I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
