### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Imanmahmoodi** [cloudflare/cloudflare-docs#3128]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @Imanmahmoodi, going to close this as un-actionable since there's no detail. Feel free to re-open if you can share more info about your problem.
