### ISSUE TITLE
Adding Firebase App Check workers template to docs

### ISSUE THREAD

**Issue by chocolatkey** [cloudflare/cloudflare-docs#3134]
I've been using CF workers along with [Firebase App Check](https://firebase.google.com/docs/app-check) for a while now in production. This is sort of equivalent to a captcha, and is useful for preventing easy/excessive access to resources without first passing the check (an invisible captcha on the web, or Android/iOS attestation).

I thought it might be useful to share the code in the form of a template, available here https://github.com/chocolatkey/worker-appcheck-template , inspired by the current quickstart examples. Is it worth adding this as one?

**Comment by kristianfreeman** [comment]
Hey @chocolatkey - thanks for the idea! Would you mind opening a PR and adding the template to this page: https://developers.cloudflare.com/workers/get-started/quickstarts#example-projects

File in source is here: https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/get-started/quickstarts.md

**Comment by chocolatkey** [comment]
@codewithkristian Done, here: https://github.com/cloudflare/cloudflare-docs/pull/3365
