### ISSUE TITLE
Add wrangler installation note for windows users

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/cloudflare-docs#32]
We had a PR in the old Workers Docs repo here for additional instructions for Windows users: https://github.com/cloudflare/workers-docs/pull/738

Opening an issue to update.

**Comment by kristianfreeman** [comment]
Unable to recreate when installing Wrangler in Windows -- let's close this for now and we can pick this up again if Windows users write in here or in https://github.com/cloudflare/wrangler with problems
