### ISSUE TITLE
Framework Guide - Blazor - Build Command Fails

### ISSUE THREAD

**Issue by dagilleland** [cloudflare/cloudflare-docs#3242]
### Expected Behavior
The Framework Guide to [**Depoy a Blazor Site**](https://developers.cloudflare.com/pages/framework-guides/deploy-a-blazor-site) offers instructions to deploy a blazor site, including the specific build command of `./build.sh`. I expected the build to success.

### Actual Behavior
Instead, the build process failed at the "Building application" stage, reporting a permissions error in running the `./build.sh`.

```
14:30:12.069 | Executing user command: ./build.sh
14:30:12.070 | /opt/build/bin/build: line 39: ./build.sh: Permission denied
14:30:12.071 | Failed: build command exited with code: 126
```

### Section that requires update
It is on the *Deploy a Blazor Site* page under the Framework Guide at the section ["Deploying with Cloudflare Pages"](https://developers.cloudflare.com/pages/framework-guides/deploy-a-blazor-site#deploying-with-cloudflare-pages).

### Additional information
I found a solution and have opened a pull request with the proposed fix. The commit message on the pull request includes links to further documentation on the solution.

**Comment by jkup** [comment]
Let's chat about this in https://github.com/cloudflare/cloudflare-docs/pull/3243

**Comment by jkup** [comment]
Fixed this in https://github.com/cloudflare/cloudflare-docs/pull/4664
