### ISSUE TITLE
Pages Docs: Netlify migration guide misses many basic platform features

### ISSUE THREAD

**Issue by rathboma** [cloudflare/cloudflare-docs#3265]
Doc page in question:
https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/migrations/migrating-from-netlify/index.md

There are several aspects to even the most simple Netlify site. Your guide only covers the absolute basics (the html).

### Expected Behavior
The following core features of Netlify absolutely need a migration path, even for the most simple static sites:
1. The Netlify [_redirects file](https://docs.netlify.com/routing/redirects/)
2. The [Form endpoint API](https://docs.netlify.com/forms/setup/)
3. Any and all configuration specified in the [netlify.toml file](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file)

Plenty more features also need migration documentation:
3. [Their functions conventions](https://docs.netlify.com/functions/overview/)
4. The [identity provider](https://docs.netlify.com/visitor-access/identity/)
5. ...etc

### Actual Behavior
The only thing listed in the migration document is how to migrate a barebone static website with no dynamic features at all.

**Comment by kristianfreeman** [comment]
Thanks for filing the issue - indeed, we used to have a section in this page that documented what features we _didn't_ support. There's also a number of alternatives to Netlify features (`_redirects` file, serverless functions) that we _do_ support, so we should make sure to link to those here.

cc @Ekwuno to work on this

**Comment by deadlypants1973** [comment]
Closing this because 3677 addressed the need.
