### ISSUE TITLE
Domain transfer FAQ

### ISSUE THREAD

**Issue by aelij** [cloudflare/cloudflare-docs#3300]
https://developers.cloudflare.com/registrar/faq

I'd appreciate adding the following information to the Registrar FAQ:

Other registrars allows purchasing domain renewals for up to 10 years **in advance**.
- ~~Do you allow the same?~~ Sorry I see this has an answer [here](https://developers.cloudflare.com/registrar/account-options/renew-domains)
- What would happen when transferring a domain that already has 10 years? Will it become 11? (It says "Time purchased is never lost." but also "up to 10 years".)

**Comment by aelij** [comment]
Another small issue - [this page](https://developers.cloudflare.com/registrar/get-started/transfer-domain-to-cloudflare) says:

> Cloudflare Registrar does not currently support email forwarding

But I saw that Cloudflare now offers [email routing](https://developers.cloudflare.com/email-routing/).

**Comment by marciocloudflare** [comment]
Hi @aelij. Thanks for your input. This was corrected in [PR-3329](https://github.com/cloudflare/cloudflare-docs/pull/3329). We removed the reference to email forwarding as we now have Email Routing. And the FAQ also answers your question regarding the 10 years. Thanks! :)
