### ISSUE TITLE
Cloudfire

### ISSUE THREAD

**Issue by syahril920827** [cloudflare/cloudflare-docs#3304]
### Expected Behavior
Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior
Explain what actually happens when you follow the documentation.

### Section that requires update
Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information
Any other details or screenshots you think are relevant.

**Comment by haleycode** [comment]
No information in this issue. Feel free to resubmit with more detailed information and our team can take a look.
