### ISSUE TITLE
Separate Tunnel Docs from Cloudflare One/Zero Trust Docs

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/cloudflare-docs#3308]
## Issue
Currently the docs for [Cloudflare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps) are a part of the docs for [Cloudflare One/Zero Trust](http://developers.cloudflare.com/cloudflare-one). This is not ideal, because while some people are attempting to utilize Tunnel in conjunction with Zero Trust/Teams, many people that I have encountered were just starting using tunnels, and were confused by the fact that they had to dig into the Teams docs to find the answers they were looking for. Also, the Quick Tunnels Service is even harder to access from the docs, for those who are just prototyping or testing their projects, and thus do not want to spend a lot of time finding the relevant documentation.
## Solution
Spin off tunnel into its own product, allowing to have its own space. Then, in the Zero Trust docs, have the [Connect Resources](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps) section redirect to the Tunnel Docs, and maybe a tutorial on how to enable Teams on a Tunnel.

**Comment by abelinkinbio** [comment]
This is helpful feedback. We do view Tunnel as an important component of our Zero Trust suite (hence it's location in our Developer Documentation to your point). However, I can appreciate that it feels buried for use cases outside of Zero Trust. We'll give this more thought internally and identify a few ways to make these resources easier to find and use for first time users.
