### ISSUE TITLE
Default Cache behaviour (robots.txt)

### ISSUE THREAD

**Issue by samlin86** [cloudflare/cloudflare-docs#3335]
### Expected Behavior
Additionally, Cloudflare caches a website’s **robots.txt**.

### Actual Behavior
Additionally, Cloudflare caches a website’s robot.txt.

### Section that requires update
Default Cache Behavior > Default cached file extensions: https://github.com/cloudflare/cloudflare-docs/blob/production/products/cache/src/content/about/default-cache-behavior.md#default-cached-file-extensions

### Additional information
I believe the [standard](https://developers.google.com/search/docs/advanced/robots/intro) is robots.txt not robot.txt.

Kindly confirm whether this is just a typo on the documentation or if this is also the behaviour in Cloudflare Cache.

**Comment by dcpena** [comment]
Hi @samlin86, thanks for catching that! I made the update and it's merged in now.
