### ISSUE TITLE
[Pages] Update how-to to refer to bulk redirects instead of Page Rules

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#3372]
### Expected Behavior
We should be referring to the most up-to-date functionality where appropriate. We're now recommending folks use Bulk redirects instead of Page rules for redirecting domains/subdomains.

### Actual Behavior
Should provide guidance similar to the info present in the [Rules documentation](https://developers.cloudflare.com/rules/bulk-redirects) (or just link out).

### Section that requires update
https://developers.cloudflare.com/pages/how-to/www-redirect

### Additional information
Any other details or screenshots you think are relevant.

**Comment by WalshyDev** [comment]
As an additional thing to this, it would be cool to make another tutorial where we redirect from `*project.pages.dev/*` to your custom domain with Bulk Redirects. It's a common question asking how to do it
Out of scope for this PR but definitely something we should do.

**Comment by kristianfreeman** [comment]
cc @Ekwuno - would you like to do a quick update to this page with some details about Bulk Redirects, since we just implemented these ourselves?

**Comment by Ekwuno** [comment]
@codewithkristian sure! I can do that. @WalshyDev I think it's worth having such a tutorial, I will make a ticket for it right now.
