### ISSUE TITLE
Cannot uninstall Cloudfare Beta (1.2.1915.1)

### ISSUE THREAD

**Issue by huutuesn** [cloudflare/cloudflare-docs#339]
I follow the instruction but could not uninstall the beta version.

![image](https://user-images.githubusercontent.com/4954278/99865935-cd7aa380-2bdf-11eb-94ab-37dee0944d6c.png)

**Comment by KimJ15** [comment]
👋 @huutuesn   I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance if you are still have issues. Thanks!
