### ISSUE TITLE
workers...sites/start-from-worker wrangler.toml block unselectable

### ISSUE THREAD

**Issue by jclee** [cloudflare/cloudflare-docs#34]
On https://developers.cloudflare.com/workers/platform/sites/start-from-worker , the wrangler.toml block is unselectable.  I think this is because it is using "sh" formatting instead of "toml" formatting -- "sh" formatting seems to do this for everything to the left of a "$" prompt.

**Comment by adamschwartz** [comment]
![image](https://user-images.githubusercontent.com/154613/94872114-bd351c00-0419-11eb-8b01-08f194aebbab.png)
