### ISSUE TITLE
"Framework guides" nav is misordered 

### ISSUE THREAD

**Issue by willmartian** [cloudflare/cloudflare-docs#3408]
### Expected Behavior
The active link and link text match the appropriate URL. 

### Actual Behavior
Links in the "Framework guides" section of the side nav are not properly configured. For example, on the [Eleventy guide page](https://developers.cloudflare.com/pages/framework-guides/deploy-an-eleventy-site), the active styled link is "Deploy a Blazor site" rather than "Deploy an Eleventy site."  This is because the href of the link is set to the wrong resource. 

### Section that requires update
https://developers.cloudflare.com/pages/framework-guides/deploy-an-eleventy-site

### Additional information
![cloudfare-docs](https://user-images.githubusercontent.com/17113462/153319238-66906bd3-9839-4cf1-b3f0-3b062350fc8a.png)

**Comment by lukeed** [comment]
This is no longer happening as of #3609 with the new engine
