### ISSUE TITLE
Unban SaucyOfficial#3298 on Discord

### ISSUE THREAD

**Issue by SaucyOfficiale** [cloudflare/cloudflare-docs#3424]
Since I can't join the Discord on alt, and no one's seeing my Reddit posts, please unban me SaucyOfficial#3298. I want to be a good member of the community and I'm sorry about what I said and spamming. Thanks.

**Comment by Powelljl** [comment]
Hello @SaucyOfficiale. Feel free to appeal  the decision here - https://forms.gle/xbtAVfAQBSZv1MRt5
