### ISSUE TITLE
Content-length behavior in Workers isn't documented

### ISSUE THREAD

**Issue by vlovich** [cloudflare/cloudflare-docs#3444]
### Expected Behavior
The documentation should call out that the content-length header is ignored when constructing a custom response/request.
To have it set correctly, the body must be an instance of `FixedLengthStream`.

### Actual Behavior
`FixedLengthStream` is undocumented. The fact that content-length is ignored for custom streams isn't mentioned.

### Section that requires update
[Request](https://developers.cloudflare.com/workers/runtime-apis/request)
[Response](https://developers.cloudflare.com/workers/runtime-apis/response)
[TransformStream](https://developers.cloudflare.com/workers/runtime-apis/streams/transformstream) or as a separate page under [Streams](https://developers.cloudflare.com/workers/runtime-apis/streams)

**Comment by vlovich** [comment]
I assume forwarded requests/responses preserve the content-length. I assume a custom ReadableStream wrapping some custom underlying source doesn't work here & currently needs to be wrapped in FixedLengthStream. Probably a good idea to have examples on how to do this too.

**Comment by gregory** [comment]
OMG! I wasted so much time on this! Please update the doc 🙏
