### ISSUE TITLE
"Deploy a static Wordpress site" needs update

### ISSUE THREAD

**Issue by ppuschmann** [cloudflare/cloudflare-docs#3455]
### Expected Behavior
https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/tutorials/deploy-a-static-wordpress-site/index.md describes a complete how-to for deployment of static sites.

### Actual Behavior
The linked Wordpress-Plugin WP2Static is closed as of 10.08.2020

### Section that requires update
Configuration of Wordpress + Wrangler

### Additional information
Please update this doc to provide a working How-To.

**Comment by kristianfreeman** [comment]
Hey, thanks for filing this issue. We're planning a revamp of this content -- we recommend that people move to Pages now, instead of Workers Sites. We'll update this issue when we publish the new version of the guide!

**Comment by davidjeba** [comment]
> 

Can you consider enabling to deploy Gatsby, Strapi, Django like websites on cloudflare workers/plages?

**Comment by kodster28** [comment]
This seems to be addressed by https://developers.cloudflare.com/pages/how-to/deploy-a-wordpress-site/, as well as https://developers.cloudflare.com/pages/framework-guides/
