### ISSUE TITLE
ClientRequestSource possible value

### ISSUE THREAD

**Issue by Miaxos** [cloudflare/cloudflare-docs#3463]
Hello!

### Expected Behavior
Right now the `ClientRequestSource` identifies the source of the connection but we do not have access to what the value of this field can be. From my logs at CloudFlare, it seems it can be `eyeball` and `edgeWorkerFetch`. I would love to know if there are more and what is the expected values for this field.

Thank you so much :-)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1060101/153881812-d630299c-854e-4b56-9295-97a041bd49e1.png)

https://developers.cloudflare.com/logs/reference/log-fields/zone/http_requests

### Section that requires update
https://developers.cloudflare.com/logs/reference/log-fields/zone/http_requests

**Comment by tlozoot** [comment]
Thanks for raising this -- agree we should have this in dev docs. 

@CF folks -- I am tracking this internally as `PCX-3461`
