### ISSUE TITLE
Tutorial on Workers and Sentry integration

### ISSUE THREAD

**Issue by Albertozhao** [cloudflare/cloudflare-docs#347]
Under our Debugging Workers section of the Workers docs, we mention Sentry as an example of setting up a logging service. However, there is no straightforward API documentation on Sentry's site for integrating with Cloudflare Workers, and many customers (including ent.) still struggle to set up proper logging. 

We should anticipate this and write a tutorial, alleviating some burden on our support team and better preparing our customers to diagnose their own errors.

**Comment by haleycode** [comment]
Closing this out for now. If we need to revisit, a new ticket can be opened.
