### ISSUE TITLE
Incremental builds

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/cloudflare-docs#35]
The prior stand-alone Workers docs repo used to have incremental builds:

https://github.com/cloudflare/cloudflare-docs-engine/blob/19b0a89bd4b6cb37b8f965ed0213170c97945bad/.github/workflows/build.yml#L10-L21

https://github.com/cloudflare/cloudflare-docs-engine/blob/19b0a89bd4b6cb37b8f965ed0213170c97945bad/.github/workflows/deploy.yml#L15-L24

(The links are @cloudflare/cloudflare-docs-engine but this used to be the @cloudflare/workers-docs-engine repo.)

Should we re-implement that in this new Cloudflare docs repo?

https://github.com/cloudflare/cloudflare-docs/blob/2e1d11a6bdfaccb539ae3646d3d4dc5595a70996/.github/workflows/deploy.yml#L534-L560

Is it possible that this somehow come from https://github.com/cloudflare/cloudflare-docs-engine? I can’t think of a great way to handle this. Best I can think of is for the engine or its documentation to provide `build.yml` and `deploy.yml` templates...

**Comment by signalnerve** [comment]
iirc incremental builds were actually failing to deploy with the new docs engine. i had done incremental builds with the `build` workflow, but i don't know if i have high enough confidence in gatsby's incremental build stuff to say this is worthwhile for us to try and get working (imo it really exists just to upsell ppl into their cloud product)

happy to try and get it working if you think it's worthwhile but my prior experience with it has been... so-so. lol

**Comment by adamschwartz** [comment]
Happy to punt for now.
