### ISSUE TITLE
Unclear zaraz track usage

### ISSUE THREAD

**Issue by erikdemarco** [cloudflare/cloudflare-docs#3527]
With zaraz track you can pass event name and " optional free-form object ". 

https://developers.cloudflare.com/zaraz/web-api/zaraz-track

But its not explain how to use this " optional free-form object ". Can properties inside this object be used for custom field value? If yes how to access it? can we access it using something like  {{ client.PARAMETER }}? 

When reading current documentation it seems this " optional free-form object " doesnt have any purpose for now.

**Comment by marciocloudflare** [comment]
Hey @erikdemarco. We've updated the docs for Zaraz and dealt with this in [PR-3272](https://github.com/cloudflare/cloudflare-docs/pull/3732). Hopefully this is easier to understand. Thanks!
