### ISSUE TITLE
Fetch - document known differences from the spec

### ISSUE THREAD

**Issue by Aprillion** [cloudflare/cloudflare-docs#3578]
As of 2022-02-20, https://developers.cloudflare.com/workers/runtime-apis/fetch only points to MDN and does not mention any differences from the `fetch` specification.

I found 2 issues so far (while working on https://github.com/Aprillion/stampy-ui/commits/master), both worked fine in miniflare (which uses undici), but not after deployment to CF workers:
* `cache` options in the init parameter are not supported (originally reported in https://github.com/remix-run/remix/issues/2015):
  ```js
  await fetch(..., {cache: 'force-cache'})
  ```
* newlines are not removed from URL as per https://url.spec.whatwg.org/#concept-basic-url-parser
  ```js
  (await fetch(' \n\n\nhttps://\t\texa\nmple\n.com\n ')).url  // should be https://example.com
  ```

Please let me know if these are bugs to be fixed (and if so, where can I report more issues in the future, please), or if these differences happen on purpose and should be documented (if so, I can work on a PR, but let me also know whether to open a sister issue in [miniflare](https://github.com/cloudflare/miniflare) to make sure our local dev environment will match all these `fetch` quirks, debugging these differences in production was not ideal TBH)...

**Comment by Aprillion** [comment]
This sounds related: https://developers.cloudflare.com/workers/platform/compatibility-dates#new-url-parser-implementation, but it's not enabled by default (and not sure if it affects the first `fetch` parameter too), so the default DX might still be confusing (something works locally and breaks after deployment => it's open to hard to debug issues non-reproducible locally).

**Comment by hansede** [comment]
This is related: https://github.com/cloudflare/miniflare/issues/183
Undici's `fetch` removes `set-cookie` headers from the response, but Cloudflare's doesn't.

**Comment by hansede** [comment]
Another way in which Undici's `fetch` behaves differently from Cloudflare's `fetch` is that Cloudflare adds the `X-Forwarded-For` header, but Undici does not.

**Comment by jasnell** [comment]
Hey all, yeah there are a couple of places where the Workers `fetch()` does diverge from the standard. The goal will be to close those gaps fairly soon (no specific timeline yet but they're on my roadmap).

**Comment by jkup** [comment]
Hey @Aprillion! Thanks for reporting this. For context, @jasnell has been leading the charge on identifying and fixing these divergences. As he mentioned, we don't have a specific timeline for getting `fetch()` to 100% compliance but it's definitely on our list and we should be getting to it soon! Thanks again for reporting.
