### ISSUE TITLE
Domain management for Wix - Via Domain Pointing

### ISSUE THREAD

**Issue by davidjeba** [cloudflare/cloudflare-docs#3583]
Websites hosted in Wix doesnot have DNS management capabilities
Still, Wix based websites can be made to work via Domain Pointing

however, wix does not recommend/support the idea of users going out of their way

**Cloudflare Documentation Request for this Scenario:**
1.User is having a website on Wix
2.User is managing DNS on Cloudflare

acmedomain.com cms is managed in wix
client wants to use a thrid part application to be a part of the same domain

eg:
client wants to run blog on wordpress with URL in acmedomain.com/blog

**How to setup**
1.URL Rewrite for acmedomain.com/blog to point to blog IP/CNAME
2.anyother options?

**Comment by KianNH** [comment]
Wix don't support using Cloudflare in-front of their sites - https://support.wix.com/en/article/request-cloudflare-support - so I'm not too sure if having documentation for an unsupported situation (where Wix wouldn't help you out if it went wrong) is the best idea.

Do you currently have a Wix website behind Cloudflare?

**Comment by kodster28** [comment]
Howdy @davidjeba, brought this up with our PM and he said that -- if he understands your use case correctly -- you _might_ be able to use a [Resolve Override page rule](https://support.cloudflare.com/hc/en-us/articles/206190798-Using-Resolve-Override-in-Page-Rules).

That functionality is currently only for ENT customers, so not sure how helpful of a recommendation it is, but figured it was worth sharing.

**Comment by davidjeba** [comment]
> 

Yes, [creativebrandgurus.com](https://www.creativebrandgurus.com/?cf-gh) is mine running on wix with cloudflare
and likewise i have deployed wix websites pointing DNS to cloudflare
i manage all my domains and client domains in cloudflare

**Comment by davidjeba** [comment]
> Howdy @davidjeba, brought this up with our PM and he said that -- if he understands your use case correctly -- you _might_ be able to use a [Resolve Override page rule](https://support.cloudflare.com/hc/en-us/articles/206190798-Using-Resolve-Override-in-Page-Rules).
> 
> That functionality is currently only for ENT customers, so not sure how helpful of a recommendation it is, but figured it was worth sharing.

Thats a great solution.
so millions of people are assuming its not possible
Cloudflare should add atleast 1 URL rewrite in free plan so people get to know it is possible

If im not this desperate i wouldnt have come this far to discuss this issues in all possible forums
