### ISSUE TITLE
Change Naming From Distributed Web to Web3

### ISSUE THREAD

**Issue by ColeBennett** [cloudflare/cloudflare-docs#3601]
https://github.com/cloudflare/cloudflare-docs/tree/production/products/distributed-web

### Expected Behavior

Distributed Web documentation is currently referred to as "Distributed Web".

### Actual Behavior

All "Distributed Web" references should be changed to "Web3".

### Sections that requires update

- Change product name to web3
  - https://github.com/cloudflare/cloudflare-docs/tree/production/products/distributed-web (directory name)
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/docs-config.js  
- Change README titles to "Cloudflare Web3 Gateway Docs"
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/README.md
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/index.md
- Change distributed-web to web3 in wrangler.toml
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/wrangler.toml
- Change distributed web to web3 in
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/ipfs-gateway/index.md
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/ethereum-gateway/about-eth.md#going-further
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/ethereum-gateway/getting-started.md#getting-started
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/ethereum-gateway/interacting-with-the-eth-gateway.md#interacting-with-ethereum
  - https://github.com/cloudflare/cloudflare-docs/blob/production/products/distributed-web/src/content/ethereum-gateway/interacting-with-the-eth-gateway.md#cloudflare-supported-api

**Comment by kodster28** [comment]
Addressed by comment on #3603
