### ISSUE TITLE
Remove hard-coded PoP value

### ISSUE THREAD

**Issue by aynsof** [cloudflare/cloudflare-docs#3604]
### Expected Behavior
Docs should display accurate numbers of Cloudflare Points of Presence (PoPs).

### Actual Behavior
PoPs are listed as 193, which is inaccurate. Rather than replacing this with the current accurate value, this should be removed.

### Section that requires update
The number of Cloudflare PoPs is hard-coded into this image: https://github.com/cloudflare/cloudflare-docs/blob/production/products/magic-transit/src/content/static/magic-transit-anycast-2.png
Remove this value as it is not accurate - we're currently at 250+ PoPs.

**Comment by KianNH** [comment]
![image](https://blog.cloudflare.com/content/images/2022/03/image2-54.png) 

Maybe this image from https://blog.cloudflare.com/protect-all-network-traffic/ is a more appropriate image that the docs could use?

**Comment by dcpena** [comment]
Hi @aynsof, thanks for calling out the outdated number. I updated the screenshot to remove the number, and you can see that update on the [Tunnels & encapsulation](https://developers.cloudflare.com/magic-transit/about/tunnels-and-encapsulation/) page.
