### ISSUE TITLE
Add instructions for installing root certificate in Linux based OS

### ISSUE THREAD

**Issue by Rtizer-9** [cloudflare/cloudflare-docs#3606]
I'm using cloudflare teams in **Linux** distro but since http filtering requires root certificate installation I need to install it. 

Browsers run fine after installing the available certificate but the OS itself is giving ssl errors whether it's adding a repository or **python** or **git** (they all have dedicated instructions for both Windows and MacOS). 

I tried adding certificate through available options and it even shows installed but it somehow doesn't accept it when it comes to some major operations (adding a repository presents with an ssl certificate error).

Please add dedicated sections for **Linux** OS itself, **git** as well as **python** on **linux.**

### Section that requires update
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert

### Additional information

![warp2](https://user-images.githubusercontent.com/35103368/155312725-6b167b86-be39-447d-883e-ba962fbb327e.png)

![warp](https://user-images.githubusercontent.com/35103368/155312749-dac344ca-0dbe-452f-a6df-34a7800cb988.png)

**Comment by kkrum** [comment]
Thanks for feedback, pr attached and we'll get docs updated.

**Comment by Rtizer-9** [comment]
The instruction to copy pem file doesn't work (doesn't pick up in the `dpkg-reconfigure ca-certificates` window); crt works but it gives an error as shown below:


![Screenshot_20220303_151708](https://user-images.githubusercontent.com/35103368/156541183-db779a1e-0511-4211-9536-dbb06b531152.png)

`sudo apt update` and discover (kubuntu software updater) still throws `error in certificate verification` error.

I'm not aware about ubuntu options but on Kubuntu I also tried adding certificate to `ssl preferences` setting but it still doesn't help.

Python and git instructions works though.

OS : Kubuntu 21.10
