### ISSUE TITLE
The possible values of CF-Connecting-IP header

### ISSUE THREAD

**Issue by alphadum** [cloudflare/cloudflare-docs#3610]
### Expected Behavior
about https://developers.cloudflare.com/fundamentals/get-started/http-request-headers ,
- The documentation should provide all possible formats of the values of  `CF-Connecting-IP` header
  -  ipv4
  - ipv6 (if any)
  - both ipv4/ipv6 (if any)

### Actual Behavior
No information about the possible value formats for `CF-Connecting-IP` header regarding IPv6 values and possibility of getting ipv4, ipv6 values together

### Section that requires update
page: https://developers.cloudflare.com/fundamentals/get-started/http-request-headers
section: `CF-Connecting-IP`

**Comment by alphadum** [comment]
Can you kindly explain possible cases related to IPV6?
Can we get both IPv4, IPV6 in the same header?

**Comment by KimJ15** [comment]
👋  I'm sorry, we only take care of updates to developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com for assistance with your question.
