### ISSUE TITLE
WAF exceptions - is this actually available?

### ISSUE THREAD

**Issue by cen1** [cloudflare/cloudflare-docs#3617]
### Expected Behavior
This page: https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-dashboard
Point 2: Go to Firewall > WAF

There is no such sub-menu in our dashboard.

### Actual Behavior
No WAF submenu in dashboard.

### Section that requires update
https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-dashboard

### Additional information
I could not find any additional info whether this is a new feature not rolled out for all customers yet or reserved for enterprise? but whatever it is, could you update the docs to specify why this might not be visible?

**Comment by xmflsct** [comment]
Great question! I would refer to this section about WAF availability, https://developers.cloudflare.com/waf/#availability, it says as of today that `WAF ... is available for selected customers on paid plans`.
