### ISSUE TITLE
Broken link on Schema Validation

### ISSUE THREAD

**Issue by sgraden** [cloudflare/cloudflare-docs#3628]
### Expected Behavior

Expected to link to this url I believe: https://developers.cloudflare.com/api-shield/products/schema-validation/configure/

### Actual Behavior
Actually went to this link
https://developers.cloudflare.com/api-shield/configure/
![image](https://user-images.githubusercontent.com/6685872/155802591-1236db2b-5a83-4f8e-a0e3-5699b1a8b8bc.png)

### Section that requires update

https://developers.cloudflare.com/api-shield/products/schema-validation/
![image](https://user-images.githubusercontent.com/6685872/155802567-49c04384-165e-4130-9163-c2790cc2124e.png)

**Comment by kodster28** [comment]
Should be addressed with the attached PR.
