### ISSUE TITLE
Using Environment Variables 404

### ISSUE THREAD

**Issue by mattferderer** [cloudflare/cloudflare-docs#3631]
### Expected Behavior

In Cloudflare Workers > {Worker Name} > Settings > Variables, the Environment Variables has a [Using Environment Variables](https://developers.cloudflare.com/workers/reference/apis/environment-variables/) link that returns a 404. 

### Actual Behavior

I assume it should link to https://developers.cloudflare.com/workers/platform/environment-variables/

### Section that requires update

[Provide a link to the page that needs an update and be specific about which section requires the update.
](https://dash.cloudflare.com/{user-id?}/workers/services/view/{worker-name}/production/settings/bindings)

### Additional information

Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
@Ekwuno, I believe this is the same feedback we heard internally regarding these links, but correct me if I'm wrong.

**Comment by Ekwuno** [comment]
Sorry about the confusion. We are tracking 404 pages and fixing them. The link should work as expected now.
