### ISSUE TITLE
[Workers] Dashboard link to request metrics 404s

### ISSUE THREAD

**Issue by bkadatz** [cloudflare/cloudflare-docs#3667]
### Expected Behavior

Clicking on the documentation link should link you to correct documentation.
![Screen Shot 2022-03-02 at 12 43 24 AM](https://user-images.githubusercontent.com/591998/156327115-d1c9fb3e-3530-4d97-b71d-8edc535166ab.png)

### Actual Behavior

Link goes to https://developers.cloudflare.com/workers/about/metrics/#requests which 404s

### Section that requires update

When viewing the Summary page for a worker on a user's dashboard. The same issue applies to Requests, Duration, and Median CPU Time as they all link to different anchors on the same missing page.

**Comment by kristianfreeman** [comment]
Added a redirect to fix this.
