### ISSUE TITLE
[Workers] Security model architecture overview docs are broken

### ISSUE THREAD

**Issue by bkadatz** [cloudflare/cloudflare-docs#3668]
### Expected Behavior

Visiting https://developers.cloudflare.com/workers/learning/security-model/#architectural-overview should document the security architecture.

### Actual Behavior

That section has a broken image and the content is truncated.

### Section that requires update

https://developers.cloudflare.com/workers/learning/security-model/#architectural-overview

**Comment by lukeed** [comment]
Closed via #3757
