### ISSUE TITLE
[Railgun] Incorrect location of Key

### ISSUE THREAD

**Issue by kklapak** [cloudflare/cloudflare-docs#3687]
### Expected Behavior

https://developers.cloudflare.com/railgun/user-guide/set-up/configuration-activation says _"Business and Enterprise users can find the Railgun activation token listed on the Account Settings page"._ 

### Actual Behavior

It confused both the customer and Support.

Perhaps something like this in parentheses can be added for clarity:

`Manage Account` -> `Configurations` -> `Railgun` -> `Activation Key`

### Section that requires update

https://developers.cloudflare.com/railgun/user-guide/set-up/configuration-activation

### Additional information

Zendesk ticket #2369186

**Comment by marciocloudflare** [comment]
Solved in https://github.com/cloudflare/cloudflare-docs/pull/3813
