### ISSUE TITLE
Clarify Browser & Edge Cache TTL behavior

### ISSUE THREAD

**Issue by jochenhonig** [cloudflare/cloudflare-docs#3692]
### Expected Behavior & Actual Behavior

Customers often misunderstand the TTL value and are not aware that this is a max. value and a file can be purged at any time before TTL expires if it is not requested frequently enough.

### Section that requires update

[Edge & Browser Cache TTL Dev Docs](https://developers.cloudflare.com/cache/about/edge-browser-cache-ttl)

### Additional information

I have seen confusion about these TTL and their behavior repeatedly and think it makes sense to clarify the expected behavior.

**Comment by angelampcosta** [comment]
👋@jochenhonig Thank you for your feedback. We will take it into consideration for future changes in the documentation.
