### ISSUE TITLE
Please support zoom in/out on pictures

### ISSUE THREAD

**Issue by cicku** [cloudflare/cloudflare-docs#3708]
https://github.com/cloudflare/cloudflare-docs/blob/production/content/firewall/cf-firewall-rules/order-priority.md

![image](https://user-images.githubusercontent.com/686438/156596783-3daabe97-b12e-4bf3-b910-10a7e3c99020.png)

I have no idea how to clearly see the picture without opening it in a new tab. Please support clicking on the image and then displaying the original one.

**Comment by KimJ15** [comment]
Hi there - I was able to zoom in (Firefox and Chrome) by using keyboard shortcuts. Just hold control and the plus button at the end of your number keys and you can zoom in on the image.

**Comment by cicku** [comment]
This is not the answer I'm expecting.

The doc website should support zoom in when the mouse is hovering the images.

Telling me using the Chrome shortcut is like telling me to find a Cloudflare competitor when it does not satisfy my needs.
