### ISSUE TITLE
cloudflared install command for Debian type system fails

### ISSUE THREAD

**Issue by vsnine** [cloudflare/cloudflare-docs#3723]
### Expected Behavior
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#deb-install includes the steps to install the cloudflared agent on deb based systems, it is expected that either the package would simply be downloaded or that the package would be downloaded and installed.

### Actual Behavior
Grabbing the wget command for Linux "deb" includes the dpkg command to install the package, but it is missing the appropriate characters to allow the dpkg command to run, either semicolon or && operators. Running the command as-is appears to hang on Ubuntu 20.04.

### Section that requires update
The command in the docs is in the **.deb install** section:
```
$ wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb dpkg -i cloudflared-linux-amd64.deb
```
If it should call on dpkg to install it automatically then it could look like this, including the **&&** operator:
```
$ wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb
```
or, if in two steps, it could look like this:
```
$ wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 
$ dpkg -i cloudflared-linux-amd64.deb
```

### Additional information

Any other details or screenshots you think are relevant.

**Comment by fbrettnich** [comment]
PR #3905

**Comment by ranbel** [comment]
Thank you for the suggestion! PR has been approved and merged.
