### ISSUE TITLE
Cloudflare cache files which they shouldn't

### ISSUE THREAD

**Issue by UchihaYuki** [cloudflare/cloudflare-docs#3736]
### Expected Behavior

Cf-Cache-Status: REVALIDATED

### Actual Behavior

Cf-Cache-Status: HIT

### Section that requires update

I'm not sure

### Additional information

My Page Rule settings:
Origin Cache Control: enabled
Cache Level: Cache Everything

I tested two Cache Control header from my origin server:
1.Cache Control: no-cache
2.Cache Control: public, s-maxage=0, max-age=0, no-cache

I expect Cloudflare to revalidate my file just as it says in document:
https://developers.cloudflare.com/cache/about/cache-control/
no-cache Caches and always revalidates. Does not serve stale.
https://developers.cloudflare.com/cache/best-practices/customize-cache/
Resources that match a Cache Everything Page Rule are still not cached if the origin web server sends a Cache-Control header of max-age=0 , private , no-cache , or an Expires header with an already expired date.

But following is what happened to Cf-Cache-Status while I keep refreshing my chrome:
EXPIRED → REVALIDATED → HIT → HIT → HIT
and I do receive stale file

I asked in community, but get no-reply.

Any help is appreciated. Thank you so much.

**Comment by kodster28** [comment]
Howdy @UchihaYuki, sorry to hear you're having issues, but the Cloudflare community is probably your best place to get answers on topics like that.

We really only have the expertise to make updates to the documentation for these `Issues`, not to troubleshoot issues with implementation.

Going to cc: @dcpena as to whether the docs might need updates, but closing this issue out as it doesn't seem like it involves any doc updates.

**Comment by UchihaYuki** [comment]
Hope somebody and reply my community post:
https://community.cloudflare.com/t/cloudflare-cache-for-no-cache/367521
Thank you, guys.
@dcpena @kodster28
