### ISSUE TITLE
CREATING API

### ISSUE THREAD

**Issue by UNDC** [cloudflare/cloudflare-docs#3747]
### Expected Behavior

Link to the documentation or explain the expected outcome of following the documentation.

### Actual Behavior

Explain what actually happens when you follow the documentation.

### Section that requires update

Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information

Any other details or screenshots you think are relevant.

**Comment by kodster28** [comment]
Howdy @UNDC, going to close this out since there's not enough info for us to take action. Feel free to re-open with more details though!
