### ISSUE TITLE
Direct Creator Upload HTML example code is incorrect

### ISSUE THREAD

**Issue by fergusmeiklejohn** [cloudflare/cloudflare-docs#3748]
### Section that requires update

https://developers.cloudflare.com/images/cloudflare-images/upload-images/direct-creator-upload/

The method should be "post" not "put"
```html
<html>
 <body>
   <form
     action="INSERT_UPLOAD_URL_HERE"
     method="put"
     enctype="multipart/form-data"
   >
     <input type="file" id="myFile" name="file" />
     <input type="submit" />
   </form>
 </body>
</html>
```

Provide a link to the page that needs an update and be specific about which section requires the update.

### Additional information

Any other details or screenshots you think are relevant.

**Comment by marciocloudflare** [comment]
This is now fixed. Thanks!
