### ISSUE TITLE
Windows defender detected virus

### ISSUE THREAD

**Issue by dangtrungluong** [cloudflare/cloudflare-docs#3750]

**Comment by kodster28** [comment]
Howdy @dangtrungluong, can you provide more details on this?

**Comment by dangtrungluong** [comment]
![image](https://user-images.githubusercontent.com/3677310/157279600-3986e22d-02c3-493b-948a-532974789d90.png)
Windows Defender detector

**Comment by kodster28** [comment]
Apologies, but I still need more details to know whether this is an issue with us. Did that come up on a specific page in our docs? Or when did you see it?

**Comment by kodster28** [comment]
Howdy @dangtrungluong, I don't believe this is an issue with our docs... sounds like it might be a problem with your local machine?

Going to close since the issue doesn't appear to be related to us.
