### ISSUE TITLE
Zero Trust Gateway Categories - How long is "new" ?

### ISSUE THREAD

**Issue by linickx** [cloudflare/cloudflare-docs#3758]
### Expected Behavior

[categories.md](https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/policies/filtering/dns-policies/categories.md) -> New Domains & Newly Seen Domains

The definition of "new" is unclear, at what point does a domain stop being new?

### Actual Behavior

Please can some expectation be set, even a range would be great.

New Domains: How many days after registration does a domain stop being new? 0-7 days? 0-30 days? 0-90 days?

Newly Seen Domains: How long does "resolved for the first time stick" ... is it related to the TTL in someway? Or is it some fixed value?

### Section that requires update

Link provided above, the table under Security risk categories would IMHO be the best place to provide guidance and expectation to when something is new or stops being new.

### Additional information

Many Thanks! :)

**Comment by KianNH** [comment]
Looks like this is now specified? Sounds like it can be closed.

> | New Domains                  | Domains registered within the past 30 days                                                                                               |
| Newly Seen Domains           | Domains that were resolved for the first time within the past 30 days     

@ranbel (not sure who to tag about this haha, saw that you had a PR open relating to it ranbel)

**Comment by linickx** [comment]
👍🏼  yep, confirmed can see this on the public page now [[LINK](https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/dns-categories/)]

Many Thanks!
