### ISSUE TITLE
Pages Docs: Add detailed information on build image

### ISSUE THREAD

**Issue by iBug** [cloudflare/cloudflare-docs#3759]
### Expected Behavior

Be explicit about the build system environment / build system image (most importantly, OS version) in the documentation, as well as what software is available for choosing.

### Actual Behavior

I once specified `PYTHON_VERSION=3.9` as an environment variable for one of my Pages sites, which ended up with the following error message:

```text
Installing dependencies
/opt/build/bin/run-build-functions.sh: line 168: /opt/buildhome/python3.9/bin/activate: No such file or directory
Error setting python version from the PYTHON_VERSION environment variable
Please see https://github.com/netlify/build-image/#included-software for current versions
Failed: build command exited with code: 1
```

Furthermore, the link in the message is broken. It took me multiple tries to figure out the exact build environment and the correct documentation ([netlify/build-image@`xenial`/included_software.md](https://github.com/netlify/build-image/blob/xenial/included_software.md)).

### Section that requires update

<https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools>

### Additional information

Original thread: [Feature Request: Publish Cloudflare Pages build system version, and add a newer system for choosing - Cloudflare Community](https://community.cloudflare.com/t/feature-request-publish-cloudflare-pages-build-system-version-and-add-a-newer-system-for-choosing/368392)

**Comment by KianNH** [comment]
Should be on it's way in this draft PR: https://github.com/cloudflare/cloudflare-docs/pull/4074
