### ISSUE TITLE
CloudMagic

### ISSUE THREAD

**Issue by IvanMX13** [cloudflare/cloudflare-docs#3764]
### Product

Which Cloudflare product(s) does this pertain to?

### Subject Matter

What needs to be documented?

### Content Location

Where would you expect this addition to be placed?

For example, should this be a new document, a new section within an existing document, or a call-out within a section?

Please provide any URLs to existing documents.

### Additional information

Any other details or screenshots that may be relevant.

**Comment by kodster28** [comment]
Howdy @IvanMX13, going to close for now as there's not enough detail to take action on this ticket, but feel free to re-open with more details.
