### ISSUE TITLE
Notifications -> Configure webhooks seems outdated

### ISSUE THREAD

**Issue by ZaDarkSide** [cloudflare/cloudflare-docs#3768]
### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/notifications/create-notifications/configure-webhooks/

### Section that requires update

The whole page seems outdated.

### What needs to change?

Everything.

### How should it change?

It should clearly state how you can configure a new webhook and what types of webhooks are available.

### Additional information

None.

**Comment by KianNH** [comment]
Is there any specific part of the page you think is outdated?

There's a list of known supported webhooks, a step-by-step on adding a webhook and an example of a generic one too.

**Comment by ZaDarkSide** [comment]
The documentation doesn't match the current UI options on Cloudflare Dashboard.

Try to follow the steps in the documentation:

1. Log in to the Cloudflare dashboard and select your account.
2. Go to Notifications.
3. Click Destinations on the left side of your dashboard.
4. In the Webhooks card, click Create.
5. Give your webhook a name so you can identify it later.
6. In the URL field, enter the URL of the third-party service you previously set up and want to connect to your Cloudflare account.
7. If needed, insert the Secret. Secrets are how webhooks are encrypted and vary according to the service you are connecting to Cloudflare.
8. Click Save and Test to finish setting up your webhook.
9. The new webhook will appear in the Webhooks card.

As you can see the whole page is severely outdated and does not match reality.

**Comment by KianNH** [comment]
The only difference in those instructions is that Destinations isn't on the sidebar but rather just on the page content itself - is that the only thing you're referring to by severely outdated?

**Comment by KianNH** [comment]
The only difference in those instructions is that Destinations isn't on the sidebar but rather just on the page content itself - is that the only thing you're referring to by severely outdated?

**Comment by ZaDarkSide** [comment]
Did you follow the steps? There is no Webhook option anywhere in Notifications. There is no support for Slack, Discord etc that is present in Documentation.

I don't understand how can you not see this, please provide a screenshot how you added a Discord Webhook for example, the documentation says you can right?

**Comment by KianNH** [comment]
If you don't see that option in notifications, it's because your plan doesn't include it. The free plan does not include access to webhook notifications, as an example.

The instructions need a single amendment to step 3 in that 'destinations' isn't on the sidebar anymore, but that's about it?

![image](https://user-images.githubusercontent.com/94662631/163715612-e3c7b964-9100-4175-96ad-720370776f68.png)

It's documented [here](https://developers.cloudflare.com/fundamentals/notifications/) which plans can use webhooks.

![image](https://user-images.githubusercontent.com/94662631/163715696-9f03cb19-f17c-4168-b155-5d6f70fe7a5f.png)

**Comment by ZaDarkSide** [comment]
Okay, in that case it should be clarified further on each option what plan do you need to have, for each section to appear.
So if you land on the Webhooks documentation like I did, it must write big you need a paid plan for this.

**Comment by KianNH** [comment]
It could be done like the way it's done on the [Service Tokens](https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens/) page for Zero Trust - along the top of the [Configure webhooks](https://developers.cloudflare.com/fundamentals/notifications/create-notifications/configure-webhooks/) page.
 
![image](https://user-images.githubusercontent.com/94662631/163715844-94988a52-4cdc-4763-ba7b-06ab0d0067f9.png)

Would that work or do you think it's better placed elsewhere?

**Comment by ZaDarkSide** [comment]
The notification style seems perfect!
It should be added [here](https://developers.cloudflare.com/fundamentals/notifications/create-notifications/create-pagerduty/)  and [here](https://developers.cloudflare.com/fundamentals/notifications/create-notifications/configure-webhooks/)

**Comment by ZaDarkSide** [comment]
Anyway to clarify, I've searched Google for Cloudflare Webhook support, landed on [this](https://developers.cloudflare.com/fundamentals/notifications/create-notifications/configure-webhooks/) documentation page, and never researched further if you need a paid plan or not, basically my fault for not reading everything on the other pages, but this will help people like me 😄 a notification like that will clearly help to see that Webhooks are part of a paid plan and not available on free plans.

Another option is to show in the UI of the Dashboard the paid options also, but greyed out or disabled, and when you click on them to ask you to upgrade to a paid plan.

**Comment by KianNH** [comment]
Created #4131
