### ISSUE TITLE
Content Update Request

### ISSUE THREAD

**Issue by YipYup** [cloudflare/cloudflare-docs#3780]
### Existing documentation URL(s)

Page: [https://developers.cloudflare.com/firewall/cf-firewall-rules/order-priority/](https://developers.cloudflare.com/firewall/cf-firewall-rules/order-priority/)
Image on Page: [https://developers.cloudflare.com/firewall/static/firewall-rules-order-and-priority-1.png](https://developers.cloudflare.com/firewall/static/firewall-rules-order-and-priority-1.png)

### Section that requires update

Image and documentation describing the evaluation order of firewall components. ie IP access, WAF, Botnet Fighting...

### What needs to change?

The graphic doesn't include Botnet Fight / Super Botnet Fight into the flow chart, making it confusing about where this is occurring at in the evaluation logic.

### How should it change?

Flow chart image updated, and it would be nice to have some accompanying written documentation better describing these steps. As of now, the written documentation on the page is almost non-existent, and we only have the flow chart graphic to go off of.

### Additional information

The answer to all of life's questions is [42](https://www.youtube.com/watch?v=8190ziL5v-k).

Path in this github repo: content/firewall/cf-firewall-rules/order-priority.md

**Comment by pedrosousa** [comment]
Hi @YipYup 
Thank you for your feedback!
We're aware of this missing information. Documenting this execution flow is already part of our backlog.

Meanwhile, you may refer to the **Traffic Sequence** in the dashboard that offers a simplified execution flow (refer to the [blog post](https://blog.cloudflare.com/traffic-sequence-which-product-runs-first/) for more information) and the [Phases list](https://developers.cloudflare.com/ruleset-engine/reference/phases-list/) in the Ruleset Engine documentation that covers the execution order of all products based on the Ruleset Engine.

**Comment by kodster28** [comment]
This is now present in https://developers.cloudflare.com/ruleset-engine/reference/phases-list/#request-phases
