### ISSUE TITLE
How to run function with URL rewrite?

### ISSUE THREAD

**Issue by vivekpatt-whydonate** [cloudflare/cloudflare-docs#3789]
### Product

Functions in Cloudflare Pages and URL rewrite in Cloudflare's Transform rules section

### Subject Matter

How to make both work for the same URL

### Content Location

New document

Please provide any URLs to existing documents. NONE

### Additional information

Any other details or screenshots that may be relevant. NONE

**Comment by haleycode** [comment]
Hi @vivekpatt-whydonate, could you please provide some additional information to help us correctly address what is needed for this request? I understand you believe a new section of documentation should be created, but could you provide the URL of the pages you were browsing that did not contain the expected information, for example? Any additional details would be appreciated.

**Comment by haleycode** [comment]
As we haven't received additional details I'm closing this ticket for now. Feel free to submit a new ticket if you can supply additional information.
