### ISSUE TITLE
[Images] "Serving images from custom domains" needs update

### ISSUE THREAD

**Issue by ZE3kr** [cloudflare/cloudflare-docs#3794]
### Existing documentation URL(s)

- https://developers.cloudflare.com/images/cloudflare-images/serve-images/

### Section that requires update

Serving images from custom domains

### What needs to change?

The function of custom domains is limited. I found that only jpeg/png images are served, instead of AVIF.

For example, [this image on imagedelivery.net](https://imagedelivery.net/6T-behmofKYLsxlrK0l_MQ/d11b18fa-d6f4-4ac7-b145-ee3a59680900/extra) is served with AVIF and WEBP. However, [the same image using custom domain is not](https://console-en.tloxygen.com/cdn-cgi/imagedelivery/6T-behmofKYLsxlrK0l_MQ/d11b18fa-d6f4-4ac7-b145-ee3a59680900/extra)

### How should it change?

Please fix this bug, or the document should state the difference between the custom domain and the imagedelivery.net. 

### Additional information

I cannot submit anything on community. Could anyone help me remove the hold?

> An account could not be registered with the email address ze3kr@icloud.com

**Comment by ZE3kr** [comment]
https://developers.cloudflare.com/images/image-resizing/url-format/

`format=auto` or `f=auto`

Allows serving of the WebP or AVIF format to browsers that support it. **If this option is not specified, a standard format like JPEG or PNG will be used.**

There is no way to add this parameter to image delivery images for custom domains. Really disappointed

**Comment by sejoker** [comment]
Thanks for reporting it, custom domains should support AVIF, we will investigate.

**Comment by sejoker** [comment]
The issue is fixed.
