### ISSUE TITLE
Provide reference documentation for cdn-cgi/access/certs

### ISSUE THREAD

**Issue by jpeach** [cloudflare/cloudflare-docs#3809]
### Product

Zero Trust

### Subject Matter

Various documentation refers to and consumes the `/cdn-cgi/access/certs` endpoint. There should be formal reference documentation that specifies the format this endpoint returns, along with any semantics that a developer ought to know.

#### Where would you expect this addition to be placed?

At some long-lived persistent URL that I can reference from my code of configuration that consumes it.

#### Please provide any URLs to existing documents.

https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json/#manual-verification

**Comment by jpeach** [comment]
It would be great to have a reference documentation page for `/cdn-cgi/access/get-identity` as well.

**Comment by jpeach** [comment]
> It would be great to have a reference documentation page for `/cdn-cgi/access/get-identity` as well.

Ref https://github.com/backstage/backstage/pull/12234#issuecomment-1169862088

The response in this comment shows `id`, `name, `email` and other fields, but the docs only mention the `groups` array.

**Comment by ranbel** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/5349
