### ISSUE TITLE
Provide reference documentation for Zero Trust HTTP headers and cookies

### ISSUE THREAD

**Issue by jpeach** [cloudflare/cloudflare-docs#3810]
### Product

Zero Trust

### Subject Matter

Applications sitting behind zero trust need to know about various Cloudflare-specific HTTP fields.

At least the `Cf-Access-Jwt-Assertion` and `Cf-Access-Authenticated-User-Email` HTTP headers, and the `CF_Authorization`, but I wonder whether there are other fields that are part of the ABI?

It would be great to have formal reference documentation for these, specifying their format and semantics, and the circumstances under which an app should expect each field to be present or absent.

#### Where would you expect this addition to be placed?

At a permanent URL that I can reference from code or configuration that depends on this ABI.

#### Please provide any URLs to existing documents.

https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json/

### Additional information

Any other details or screenshots that may be relevant.

**Comment by immanetize** [comment]
+1.  In production now, the Zero Trust web UI for managing Applications' settings tab links out to https://developers.cloudflare.com/cloudflare-one/identity/users/session-management/#options-for-browser-cookies-configuration  and that page has no content describing the features.

**Comment by ranbel** [comment]
Thanks for pointing this out. I have notified the UI team that the link should point to https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/

Does the [application token](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/application-token/) page contain the information you are looking for?

**Comment by ranbel** [comment]
> +1. In production now, the Zero Trust web UI for managing Applications' settings tab links out to https://developers.cloudflare.com/cloudflare-one/identity/users/session-management/#options-for-browser-cookies-configuration and that page has no content describing the features.

This fix was merged on 9/15.
