### ISSUE TITLE
Insufficient information provided in deploying a Next.js site

### ISSUE THREAD

**Issue by oscarcao** [cloudflare/cloudflare-docs#3818]
### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#deploying-with-cloudflare-pages

### Section that requires update

> Deploying with Cloudflare Pages

### What needs to change?

Next.js has a dependency that requires node version 12.20.0 or higher. The version of node provided by the default Pages configuration is 12.18.0.

### How should it change?

There should be a paragraph added to inform users about this and how-to override the default node version setting by pointing the user to the documentation that covers this (https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools).

### Additional information

![existing-docs](https://user-images.githubusercontent.com/639649/158409519-7b85de3d-bfc4-41c5-9ad9-6f783df4cbc2.png)

**Comment by kristianfreeman** [comment]
@Ekwuno to implement a notice on `NODE_VERSION` on this page

**Comment by nativedone** [comment]
@codewithkristian @Ekwuno

I've just started with Cloudflare/Pages.

Am I missing something? I tried to find in the docs how to use next/image with Cloudflare Pages without luck.

I found this link in the Images service
https://developers.cloudflare.com/images/image-resizing/integration-with-frameworks/

but using it for images that are on **/public** gives me 404.

Would you be able to provide any guidance on that?

**Comment by KianNH** [comment]
We already have this notice on other frameworks - like [Astro](https://developers.cloudflare.com/pages/framework-guides/astro/)

![image](https://user-images.githubusercontent.com/94662631/163697901-fff0409d-f675-49cf-909c-7eac34bece4c.png)

Copied it over into the Next.js framework in https://github.com/cloudflare/cloudflare-docs/pull/4124
