### ISSUE TITLE
Text wraps outside bounding box

### ISSUE THREAD

**Issue by jpeach** [cloudflare/cloudflare-docs#3823]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens/#create-a-service-token

### Actual Behavior

<img width="1095" alt="Screen Shot 2022-03-16 at 2 18 10 pm" src="https://user-images.githubusercontent.com/9917/158509917-86e8cbd6-bfef-4374-8aa6-33c759df0e48.png">

**Comment by kodster28** [comment]
Howdy @jpeach, that's actually a bug that appeared with our recent migration to Pages (usually related to indentation). It's more of a `hunt down the bugs` instead of applying an ENG fix.

**Comment by jpeach** [comment]
Looks good 👍
