### ISSUE TITLE
WARP Split tunnel: excluding IP ranges 

### ISSUE THREAD

**Issue by GitStudying** [cloudflare/cloudflare-docs#3824]
### Product

WARP on Windows

### Subject Matter

Excluding IP ranges

### Content Location

[Where would you expect this addition to be placed?](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/exclude-traffic/split-tunnels/)

### Additional information

I am using Warp on Windows using the warp application.
When I have it turned on everything works as it should except for a local streaming service.
I can find the IP address using the network panel of dev tools. This IP does however change every time another video is started. I can exclude this IP but this is only for one video.
I have already excluded the domain itself but this does not help (as this differs from the ips used for video streaming). The IPs do seem to follow a pattern something like 184.82.xx.xx (only as example)
Where xx and xx can be all the numbers in the range. for domains a wildcard can be used: *.domain.com. Is there a possibility to use wildcards for IPs? 
If so update this in the documentation.
If not could you implement this?

I have looked at the documentation but couldn't find anything to solve my problem.

**Comment by haleycode** [comment]
Thanks for opening this issue! Given the problems you are experiencing, I believe reaching out to community.cloudflare.com for assistance may provide more support for you.
