### ISSUE TITLE
Zero Trust 

### ISSUE THREAD

**Issue by rosatea** [cloudflare/cloudflare-docs#3837]
### Product

Which Cloudflare product(s) does this pertain to?

### Subject Matter

What needs to be documented?

### Content Location

Where would you expect this addition to be placed?

For example, should this be a new document, a new section within an existing document, or a call-out within a section?

Please provide any URLs to existing documents.

### Additional information

Any other details or screenshots that may be relevant.

**Comment by kodster28** [comment]
Howdy @rosatea, closing this out since there's not really enough info to take action on this issue. Feel free to re-open if you have more details.
