### ISSUE TITLE
Minor update for Debian/Linux cert install docs

### ISSUE THREAD

**Issue by topher200** [cloudflare/cloudflare-docs#3844]
### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert/#debian--ubuntu

### Section that requires update

Debian/Ubuntu

### What needs to change?

The instructions are currently:
```
$ cp Cloudflare_CA.pem /usr/share/ca-certificates
```

However, I was having these issues:
1. I was getting "permission denied" errors when attempting to `cp` without `sudo`
2. I was not seeing the certificate show up in the `$ sudo dpkg-reconfigure ca-certificates` step if I didn't copy the `.crt` file as well.

### How should it change?

What I had to run instead:
```
$ sudo cp Cloudflare_CA.crt Cloudflare_CA.pem /usr/share/ca-certificates
```

### Additional information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

**Comment by ranbel** [comment]
Thank you for bringing this to our attention! Another user experienced the same issue. I have updated the instructions in PR #3894.
