### ISSUE TITLE
Styling issues in definition blocks

### ISSUE THREAD

**Issue by pedrosousa** [cloudflare/cloudflare-docs#3865]
### Example URL(s)

https://developers.cloudflare.com/waf/rate-limiting-rules/parameters/
https://developers.cloudflare.com/ruleset-engine/rules-language/functions/#transformation-functions
https://developers.cloudflare.com/waf/custom-rules/skip/options/

### Actual Behavior

Definition blocks have a few formatting issues:

* The first "inline code" in each paragraph of a definition item is displayed in **bold**.
* There's too much space between paragraphs.
* Bulleted lists inside a definition item don't display a circle (bullet) before each item.

### Expected Behavior

Unless explicitly formatted in a different manner, all inline code occurrences in a definition list should use the same formatting.
Paragraph spacing should be similar to normal paragraphs outside a definition context.
Bulleted lists in a definition item should display a bullet before each list item.

### Additional information

Screenshot of `https://developers.cloudflare.com/waf/rate-limiting-rules/parameters/`:

![image](https://user-images.githubusercontent.com/680496/159249552-dface0f2-4c7c-4209-a400-09cbec9f500a.png)

Screenshot of `https://developers.cloudflare.com/ruleset-engine/rules-language/functions/#transformation-functions`:

![image](https://user-images.githubusercontent.com/680496/159251065-1cdafa24-4655-4e69-90a5-02d5d17b79a3.png)

Screenshot of `https://developers.cloudflare.com/waf/custom-rules/skip/options/`:

![image](https://user-images.githubusercontent.com/680496/159250937-0f154261-197a-489b-bdda-e5d7f35775b7.png)

**Comment by lukeed** [comment]
Unfortunately this is carryover from the previous/existing CSS rules. I can still try to fix it, but (a) this is how this page would have looked using the previous framework; (b) it might affect other pages inadvertently

**Comment by pedrosousa** [comment]
These styling issues didn't exist before the migration. 

Here are the equivalent screenshots from the `old.developers.(...)` subdomain (some of the content is already different):

![image](https://user-images.githubusercontent.com/680496/159451155-4459ec92-f405-45aa-b06e-cf3f5583f4b7.png)

![image](https://user-images.githubusercontent.com/680496/159451871-3e587c86-9c44-49df-ba24-cda628e7494f.png)

![image](https://user-images.githubusercontent.com/680496/159451521-75ba98c2-a5f2-48a4-9e08-70dfd5613f95.png)

**Comment by KimJ15** [comment]
@kodster28 not sure if you want to take a look at this?

**Comment by kodster28** [comment]
You may need to use an incognito browser to make sure you're seeing the latest change, but verified that it's working correctly.

**Comment by pedrosousa** [comment]
We still need to fix the paragraph spacing and the missing bullets (in a separate PR).
