### ISSUE TITLE
Add "Bypass Edge TLS Certificate" as circumstance to not use proxied records

### ISSUE THREAD

**Issue by keithalpichi** [cloudflare/cloudflare-docs#3882]
### Product

DNS

### Subject Matter

Add Edge Certificate bypass as circumstance to not use proxied records.

### Content Location

A new section within [content/dns/manage-dns-records/reference/proxied-dns-records.md](https://github.com/cloudflare/cloudflare-docs/blob/production/content/dns/manage-dns-records/reference/proxied-dns-records.md)

### Additional information

We have a specific case where we don't want to serve the custom or universal Edge TLS certificate for our certificate authorities. We'd instead like to serve the TLS certificate from the origin. We're also on a non-Enterprise plan and cannot import a second custom certificate. In this case we have to disable the DNS proxy.

I propose to add the following Markdown text:

```
### Bypass Edge TLS Certificate

If you need to serve a TLS certificate at the origin of the DNS record rather than the one configured for Cloudflare's Edge Certificate. You may need to perform this if you're hosting your own certificate authority.
```

Please let me know if you have any questions or propose changes. I can make a PR for this.

**Comment by kodster28** [comment]
Howdy @keithalpichi, just need to run that wording by a few internal folks (currently on PTO, so might take a bit), but more than happy to add it to the docs.

**Comment by kodster28** [comment]
Howdy @keithalpichi, passing on this feedback from our PM.

We don't want to encourage customers to disable their Cloudflare proxy service if there are workarounds. Instead, customers can rely on the Cloudflare-issued certificate to keep the connection from the eyeball to the edge secure and then use origin certificates to ensure a secure connection between Cloudflare and the origin.
