### ISSUE TITLE
owner 

### ISSUE THREAD

**Issue by robertaq1998** [cloudflare/cloudflare-docs#3898]
### Existing documentation URL(s)

- link(s) to existing https://developers.cloudflare.com/... pages

### Section that requires update

Please specify which section requires the update.

> **NOTE:** Please name or describe the section as not all page sections have header-links and section IDs may change over time.

### What needs to change?

Explain the issue with the content, including any confusion it may be causing.

### How should it change?

For content clarification requests, please propose a way forward that would have helped you avoid any confusion.

### Additional information

Any other details or screenshots that may be relevant.

**Comment by kodster28** [comment]
Howdy @robertaq1998, doesn't appear like there's enough info for us to take action on this ticket. Closing out for now, but feel free to re-open with more details.
