### ISSUE TITLE
Will the hotlink protection firewall rule block traffic from search engine result?

### ISSUE THREAD

**Issue by diazsasak** [cloudflare/cloudflare-docs#3903]
Will the hotlink protection firewall rule block traffic from search engine result? the referrer will be "google.com" ?

https://github.com/cloudflare/cloudflare-docs/blob/233b70ce1406497badddec7cdf5ab21d196c420c/content/firewall/recipes/exempt-partners-hotlink-protection.md?plain=1#L33

**Comment by kodster28** [comment]
From looking at [our KB](https://support.cloudflare.com/hc/en-us/articles/200170026-Understanding-Cloudflare-Hotlink-Protection), it looks like it won't block SEO traffic
```Hotlink protection has no impact on crawling, but it will prevent the images from being displayed on sites such as Google images, Pinterest, etc.```

If you were concerned about the images, etc., it seems like this [community thread](https://community.cloudflare.com/t/enable-cloudflare-hotlink-protection-and-allow-google-bing-bot/293828/5) offers an answer (haven't verified it myself).
