### ISSUE TITLE
A viewed link is showing purple in dark mode

### ISSUE THREAD

**Issue by sgraden** [cloudflare/cloudflare-docs#3928]
### Example

https://developers.cloudflare.com/firewall/cf-firewall-rules/actions/#:~:text=1-,Bypass,-Allows%20user%20to

### Actual Behavior
Most links are not having this issue as far as I can tell, but there is at least one link on the linked page which is behaving as a default link coloring behavior 

A previously visited link in dark mode is doing the default purple coloring which makes it very hard to see.

### Expected Behavior

All links have appropriate colors to be visible in all light modes.

### Additional information
![image](https://user-images.githubusercontent.com/6685872/160144976-a254a2df-b8d8-4951-bc50-1f7b80f4b175.png)

**Comment by kodster28** [comment]
Howdy @sgraden, thanks for the callout. For more context for ENG here, I believe that happens to links we're rendering with html `<a>` tags. Doesn't happen super often, but somewhat common in html formatted tables.

**Comment by KimJ15** [comment]
Thanks for the feedback. Given we have a PR open for this (and other link colors), i'm going to close this issue as a duplicate.
