### ISSUE TITLE
Duckduckgo/bing search results linking to 404 pages

### ISSUE THREAD

**Issue by jkpe** [cloudflare/cloudflare-docs#3936]
### Example URL(s)

https://duckduckgo.com/?t=ffab&q=cloudflared+tunnel+quick+tunnel&atb=v296-1&ia=web
Click first result

### Actual Behavior

Results in a 404 page - https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/trycloudflare/index.d42a1d3683.html

### Expected Behavior

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/trycloudflare/index.html

### Additional information

Unsure if you are aware but there are lots of results on Duckduckgo/Bing that link to pages that do not exist. It has been like this for at least a couple of weeks now. Duckduckgo/Bing has indexed some random strings at the end of a few URLs. I have linked an example but there are many more.

**Comment by kodster28** [comment]
Howdy @jkpe, thanks for the callout! 

I _think_ it may have something to do with some old configurations getting indexed by Bing/DDG. I've deleted those entries + set up a transform rule to _hopefully_ send those requests to the correct pages.

I'll keep this issue open for a bit in case you find any additional problems, so let me know if we're missing specific URLs here.
