### ISSUE TITLE
Add Vercel to transfer instructions list

### ISSUE THREAD

**Issue by revelt** [cloudflare/cloudflare-docs#395]
Currently, one can purchase domains on Vercel and we're missing instructions how to migrate Vercel registrar domains into Cloudflare registrar:

<img width="377" alt="Screenshot 2020-12-01 at 08 44 42" src="https://user-images.githubusercontent.com/8344688/100717071-7d56ca80-33b1-11eb-98bb-ded39988cf0e.png">

https://developers.cloudflare.com/registrar/transfer-instructions

**Comment by marciocloudflare** [comment]
Thank you for your input. As there are thousands of registrars and tens of thousands of resellers we are unable to provide instructions for everyone. As such, I'll close this issue. Thank you :)
