### ISSUE TITLE
Downtime when making update from DNS Only to Proxied

### ISSUE THREAD

**Issue by RajasekarPR** [cloudflare/cloudflare-docs#3988]
Hi 

Just want to know do we have any downtime when the dns record proxy status is changed from DNS Only to Proxied in cloudflare. 

Searched through the documentation about my query. But i couldn't find it. 

Please address my query and if any documentation related to this . Please provide the link.

**Comment by stefanogramm** [comment]
No, there is no downtime expected @RajasekarPR.

> When you proxy an A, AAAA, or CNAME DNS record for your application (also known as orange-clouding), DNS queries for these records will resolve to Cloudflare Anycast IPs instead of their original DNS target.

That's pretty straightforward, you can find more info in different documentation and KBs.

- https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/
- https://developers.cloudflare.com/dns/faq/
- https://support.cloudflare.com/hc/en-us/articles/360020296512
- https://support.cloudflare.com/hc/en-us/articles/217912538
- https://support.cloudflare.com/hc/en-us/articles/360017421192
