### ISSUE TITLE
Hidden content

### ISSUE THREAD

**Issue by Lindalu79** [cloudflare/cloudflare-docs#4010]
### Product

Which Cloudflare product(s) does this pertain to?

### Subject Matter

What needs to be documented?

### Content Location

Where would you expect this addition to be placed?

For example, should this be a new document, a new section within an existing document, or a call-out within a section?

Please provide any URLs to existing documents.

### Additional information

Any other details or screenshots that may be relevant.

**Comment by Lindalu79** [comment]
> ### Product
> 
> Which Cloudflare product(s) does this pertain to?
> 
> ### Subject Matter
> 
> What needs to be documented?
> 
> ### Content Location
> 
> Where would you expect this addition to be placed?
> 
> For example, should this be a new document, a new section within an existing document, or a call-out within a section?
> 
> Please provide any URLs to existing documents.
> 
> ### Additional information
> 
> Any other details or screenshots that may be relevant.
>

**Comment by haleycode** [comment]
Hi there! I'm closing out this ticket as there is insufficient information for us to take action. Please feel free to resubmit a ticket with more info if you need further help.

**Comment by Lindalu79** [comment]
> ### Product
> 
> Which Cloudflare product(s) does this pertain to?
> 
> ### Subject Matter
> 
> What needs to be documented?
> 
> ### Content Location
> 
> Where would you expect this addition to be placed?
> 
> For example, should this be a new document, a new section within an existing document, or a call-out within a section?
> 
> Please provide any URLs to existing documents.
> 
> ### Additional information
> 
> Any other details or screenshots that may be relevant.
>
