### ISSUE TITLE
Cloudflare Stream with recording mode off

### ISSUE THREAD

**Issue by TheMrAmazing** [cloudflare/cloudflare-docs#4035]
### Product

Cloudflare Stream

### Subject Matter

When a live stream is started, you have a "recording" option. The only documented "mode" for recording is "automatic". I need to run livestreams without recording, and from playing around with the API I can see that there is an "off" option, but I can't find out how to retrieve the stream (specifically the .m3u8 manifest) when the recording mode is set to off.

### Content Location

https://developers.cloudflare.com/stream/stream-live/start-stream-live/

this should be documented on this page presumably

### Additional information

Here is what I send to the server for data:
'{"meta": {"name":"test stream 1"}}'

This is the result I get back:

{
  "result": {
    "uid": "d07afd262c940791feda7279992c4767",
    "rtmps": {
      "url": "rtmps://live.cloudflare.com:443/live/",
      "streamKey": "bea7b5d3fef14dee8c1760c7336f0d98kd07afd262c940791feda7279992c4767"
    },
    "srt": {
      "url": "srt://live.cloudflare.com:778",
      "streamId": "d07afd262c940791feda7279992c4767",
      "passphrase": "b61793fc45d2b307b15c52824eb4722akd07afd262c940791feda7279992c4767"
    },
    "created": "2022-04-06T11:29:24.303148Z",
    "modified": "2022-04-06T11:29:24.303148Z",
    "meta": {
      "name": "test stream 1"
    },
    "status": null,
    "recording": {
      "mode": "off",
      "requireSignedURLs": false,
      "allowedOrigins": null
    }
  },
  "success": true,
  "errors": [],
  "messages": []
}

Based on the documentation I would presume this URL would return the m3u8 mainifest:

https://videodelivery.net/d07afd262c940791feda7279992c4767/manifest/video.m3u8

however I get a message saying "Manifest not found"

**Comment by dcpena** [comment]
Hi @TheMrAmazing, thanks for filing the issue! Stream does not currently support live streaming without recording. Because this is not something we currently support, I'm going to close this issue.

**Comment by bakcxoj** [comment]
@dcpena Can there be documentation then for _why_ this is? It doesn't make sense to me (and probably doesn't to others) why we would _need_ to have our broadcasts recorded, especially if the space taken up by that recording is billed.
