### ISSUE TITLE
could not find subdir/index.html in your content namespace

### ISSUE THREAD

**Issue by GIThunte** [cloudflare/cloudflare-docs#4053]
Hi all, i had this error:
could not find subdir/index.html in your content namespace

After deployment worker to Cloud Flare by wrangler, 
my wrangler.toml:

-------
name = "worker-name"
type = "webpack"
route = "https://mydomain.com/subdir"
account_id = "id"
zone_id = "zone_id"

[site]
bucket = "./data"
entry-point = "workers-site"
-------

I think is problem in "route", because i want to use one domain for different url, for example:
https://mydomain.com/firt_proj
https://mydomain.com/second_proj
also i tried something like this - https://mydomain.com/subdir/*" and it has`nt work too

after visit the Cloudflare Dashboard - (worker keys) i saw my index.html was renamed to index.as4df32b28.html, who knows, why?
can i do like above? or it is wrong way?

Thanks a lot

**Comment by KimJ15** [comment]
Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! I think folks in the Discord channel or community.cloudflare.com might be able to provide assistance!
