### ISSUE TITLE
Ethereum Gateway missing `eth_feeHistory `

### ISSUE THREAD

**Issue by mloit** [cloudflare/cloudflare-docs#4057]
### Existing documentation URL(s)

- [Interacting with Ethereum](https://developers.cloudflare.com/distributed-web/ethereum-gateway/interacting-with-the-eth-gateway/)

### Section that requires update

Cloudflare supported API

### What needs to change?

missing is any mention of `eth_feeHistory` this method is required for working with transactions conforming to EIP-1559. 

### How should it change?

At a minimum it should be mentioned that it is not supported. Ideally the gateway should be updated to support the API call, as it is part of the standard and critical for anyone working with EIP-1559 transactions, and the documentation updated to reflect that.

### Additional information

Ref: [Ethereum RPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/execution-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false)

**Comment by kodster28** [comment]
As of now, this is not supported. Added that to the docs page + thanks for raising the issue.
