### ISSUE TITLE
Issue with the 'results in X seconds' text

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#4063]
### Example URL(s)

https://developers.cloudflare.com/search/#q=foo

### Actual Behavior

There is no space after the search query.

`Results 1-10 of 141 for fooin 0.26 seconds`

![image](https://user-images.githubusercontent.com/94662631/162528265-a65acdc9-7a39-4e29-8625-ab4f9eed0681.png)

### Expected Behavior

There is a space after the search query.

`Results 1-10 of 141 for foo in 0.26 seconds`

### Additional information

There's no space between the query & the 'in ?.? seconds' text.

![image](https://user-images.githubusercontent.com/94662631/162528346-b43368ec-3444-45ce-9852-fed438b50727.png)

https://github.com/cloudflare/cloudflare-docs/blob/60a4c5abdd40b4bd97a2a25f41c43c2bb15efe8c/content/search.html#L32

**Comment by kodster28** [comment]
For internal, we're tracking this in https://jira.cfops.it/browse/WDC-531
