### ISSUE TITLE
Problem with Split Tunnel on Warp

### ISSUE THREAD

**Issue by Mixadencik** [cloudflare/cloudflare-docs#4068]
### Product

Warp

### Subject Matter

Hello. Often there are problems with the work of Split tunnel. For a reason unknown to me, the settings are reset and there is not a single ip address for exclusion. Restore button does not solve this problem. Due to the lack of ip addresses, the local network and airdrop do not work.

My friend have this problem too. MacOS

<img width="701" alt="image" src="https://user-images.githubusercontent.com/103152942/162616131-e888e0b6-cb3e-4a2e-8877-a8a4179ed66e.png">

**Comment by KimJ15** [comment]
👋 Thanks for opening this issue but we only take care of documentation improvements for developers.cloudflare.com in this repo! Please reach out to community.cloudflare.com for assistance!
