### ISSUE TITLE
Stream & Randomness Beacon icons not showing on Firefox

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#4079]
### Example URL(s)

- https://developers.cloudflare.com/

### Actual Behavior

Stream and Randomness Beacon icons do not show on Firefox.

![image](https://user-images.githubusercontent.com/94662631/162838396-8df905ec-3e6e-4ce8-82a6-ee206af0f5e9.png)

### Expected Behavior

Stream and Randomness Beacon icons do show on Firefox.

![image](https://user-images.githubusercontent.com/94662631/162838472-b08d3cde-6a77-4067-a6c2-f0f5c769a4fe.png)

### Additional information

The 'expected behavior' is taken from my fork ~10 days ago so I believe this is the suspect commit.

https://github.com/cloudflare/cloudflare-docs/commit/a25e4540be0349d1507f09d73fd1ec36a6bbc564

The two icons that do not show on Firefox are below:

https://github.com/cloudflare/cloudflare-docs/blob/5901a29a91f5700012e72f5a82bd8ae6e94adf36/data/stream.yml#L2

https://github.com/cloudflare/cloudflare-docs/blob/5901a29a91f5700012e72f5a82bd8ae6e94adf36/data/randomness-beacon.yml#L2

**Comment by alex-mayorga** [comment]
¡Hola y'all!

I reported this on Mozilla's Bugzilla and per https://bugzilla.mozilla.org/show_bug.cgi?id=1765202#c8 the issue seems to be:

> the page contains a number of SVG elements that are clearly intended to be independent of each other, but several of them attempt to re-use the same ID attribute internally.

Hope this helps.

¡Gracias!
Alex

**Comment by KimJ15** [comment]
Hi @marciocloudflare Is this something you can take a look at? I think we might be able to fix given the additional info provided by Alex above. Thanks!!

**Comment by marciocloudflare** [comment]
Hi @KimJ15 I actually don't know how to solve this issue. Should we ping someone from the dev advocates?

**Comment by KianNH** [comment]
I can take a look in a bit - at first I disregarded it as a Firefox issue as copy/pasting the SVG HTML into stuff like W3's HTML try-it worked fine but I can probably make a compressed version of the original HTML (before the commit that caused this) that doesn't kill Firefox.
