### ISSUE TITLE
Title mismatch on content pages and main page

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/cloudflare-docs#4080]
### Existing documentation URL(s)

Main Page:
- https://developers.cloudflare.com/api-shield/

Content Pages:
- Basically every content page, for example https://developers.cloudflare.com/api-shield/

### Section that requires update

- On the main docs page (https://developers.cloudflare.com/) the title in the top right is Cloudflare Developers.
- However, on any subpages (for example, https://developers.cloudflare.com/api-shield/) the title in the top right is Cloudflare Docs.

### What needs to change?

- This is a small issue, but one or the other should likely be changed so they match.

### How should it change?

- Either Cloudflare Developers should change to Cloudflare Docs on the main page, or...
- Cloudflare Docs should change to Cloudflare Developers on the subpages.

**Comment by KimJ15** [comment]
Thanks for providing this feedback! This is a known issue and will be addressed through an update later this year. Thanks!
