### ISSUE TITLE
Set up 1.1.1.1 - Gaming-consoles. md

### ISSUE THREAD

**Issue by Limpisey168** [cloudflare/cloudflare-docs#4082]
# Set up 1.1.1.1 - Gaming consoles
## ​​PS4
Go to Settings > Network > ## Set Up Internet Connection.
Select ## WiFi or ## LAN depending on your ## Internet connection.
Select Custom.
Set IP Address Settings to Automatic.
Change ## DHCP Host Name to Do Not Specify.
Set ## DNS Settings to Manual.
Change Primary DNS and Secondary DNS to:
1.1.1.1
1.0.0.1
If you are able to add more # DNS servers, you can add the IPv6 addresses as well:
2606:4700:4700::1111
2606:4700:4700::1001
Set MTU Settings to Automatic.
Set Proxy Server to Do Not Use.
​​#Xbox One
Open the Network screen by pressing the Xbox button on your controller.
Go to Settings > Network > Network Settings.
Next, go to Advanced Settings > DNS Settings.
Select Manual.
#4081 Set Primary DNS and Secondary DNS to:
1.1.1.1
1.0.0.1
If you have the option to add more DNS servers, you can add the IPv6 addresses as well:
2606:4700:4700::1111
2606:4700:4700::1001
When you are done, you will be shown a confirmation screen. Press B to save.
​​#Nintendo
The following instructions work on New Nintendo 3DS, New Nintendo 3DS XL, New Nintendo 2DS XL, Nintendo 3DS, Nintendo 3DS XL, and Nintendo 2DS.
#4081 Assignees
Go to the home menu and choose System Settings (the wrench icon).
Select Internet Settings > Connection Settings.
Select your Internet connection and then select Change Settings.
Select Change # DNS.
Set Auto-Obtain # DNS to No.
##;Click Detailed Setup.
## Set Primary DNS and Secondary DNS to:
1.1.1.1
1.0.0.1
If you are able to add more DNS servers, #4081 
 can add the IPv6 addresses as well:
2606:4700:4700::1111
2606:4700:4700::1001
Click Save.
Click ##:OK.
​​# Nintendo Switch
Press the home button and select System Settings.
Scroll down and select Internet > ## Internet Settings.
#Select your Internet connection and then select Change Settings.
Click #4081 DNS Settings > Manual.
#4081 Set Primary DNS and Secondary DNS to:
1.1.1.1
1.0.0.1
## Press Save >  OK.

**Comment by marciocloudflare** [comment]
Hi @Limpisey168. Can you explain what the issue is exactly? Thank you.

**Comment by kodster28** [comment]
Howdy @Limpisey168, it looks like you're just copy/pasting existing instructions here?

Going to close for now, but feel free to re-open if needed.
