### ISSUE TITLE
Example DoH query is invalid

### ISSUE THREAD

**Issue by ag-michael** [cloudflare/cloudflare-docs#4092]
### Existing documentation URL(s)

- https://github.com/cloudflare/cloudflare-docs/blob/production/content/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json.md

### Section that requires update

Example request:

### What needs to change?

The example command `curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA'` does not work. The server returns `'no 'dns' query parameter found`

**Comment by KianNH** [comment]
The example command works for me.

```
➜  ~ curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA'
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"example.com","type":28}],"Answer":[{"name":"example.com","type":28,"TTL":84769,"data":"2606:2800:220:1:248:1893:25c8:1946"}]}
```

```
➜  ~ curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=AAAA' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   210  100   210    0     0   5526      0 --:--:-- --:--:-- --:--:--  5526
{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": true,
  "CD": false,
  "Question": [
    {
      "name": "example.com",
      "type": 28
    }
  ],
  "Answer": [
    {
      "name": "example.com",
      "type": 28,
      "TTL": 77242,
      "data": "2606:2800:220:1:248:1893:25c8:1946"
    }
  ]
}
```

Might be a platform/curl related bug - what OS & terminal are you running?

**Comment by vavrusa** [comment]
@ag-michael the example command seems correct to me, could you post your entire curl output? The 'dns' parameter is expected for the `application/dns-message` media type, not `application/dns-json`.

**Comment by marciocloudflare** [comment]
Any comment on this @ag-michael? I'll be closing this issue in a few days if not. Thanks! :)

**Comment by marciocloudflare** [comment]
Closing as there are no updates. Can reopen if needed. Thanks!

**Comment by ag-michael** [comment]
@marciocloudflare  apologies for the long delay. I was still having the problem but I found out the root cause, it was a middlebox intercepting DoH and attempting to resolve/mitm/proxy the request.

Thanks anyways.

**Comment by marciocloudflare** [comment]
Thanks for the update @ag-michael :)
