### ISSUE TITLE
Pages: update _redirects limit to 1000

### ISSUE THREAD

**Issue by myakura** [cloudflare/cloudflare-docs#4114]
### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/platform/redirects/

### Section that requires update

Please specify which section requires the update.

> **NOTE:** Please name or describe the section as not all page sections have header-links and section IDs may change over time.

### What needs to change?

https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/platform/redirects.md?plain=1#L38

### How should it change?

The document says:

> A project is limited to 100 total redirects.

However, according to a message in the Discord channel and [this tweet](https://twitter.com/chatsidhartha/status/1511809202829860874), it looks the limit is bumped up to 1000.
That's a great update and docs should mention that!

### Additional information

Any other details or screenshots that may be relevant.

**Comment by KianNH** [comment]
Will be resolved in https://github.com/cloudflare/cloudflare-docs/pull/4123
