### ISSUE TITLE
ACM Custom Origin Trust Store API doc links do not exist and developer docs needs expanding

### ISSUE THREAD

**Issue by centminmod** [cloudflare/cloudflare-docs#4120]
### Existing documentation URL(s)

- https://developers.cloudflare.com/ssl/origin-configuration/custom-origin-trust-store/ needs to expand the documentation beyond just the URL with an example similar to how Authenticated Origin Pull API instructions have at https://api.cloudflare.com/#zone-level-authenticated-origin-pulls-upload-certificate and https://developers.cloudflare.com/ssl/edge-certificates/custom-certificates/uploading/#using-the-api

### Section that requires update

The Cloudflare zone dashboard's expanded API links do not exist in API documentation at:

- https://api.cloudflare.com/#custom-origin-trust-store-post
- https://api.cloudflare.com/#custom-origin-trust-store-get-list
- https://api.cloudflare.com/#custom-origin-trust-store-get
- https://api.cloudflare.com/#custom-origin-trust-store-delete

### What needs to change?

The Cloudflare zone dashboard's expanded API links do not exist in API documentation at and developer documentation doesn't have enough info like the API doc examples.

**Comment by kodster28** [comment]
Tracking internally in https://jira.cfops.it/browse/SECENG-9570
