### ISSUE TITLE
Document `tsconfig.json` behavior with Pages Functions

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#4158]
### Product

Cloudflare Pages

### Subject Matter

A `tsconfig.json` in the root of a Pages project will affect how Pages Functions are build, unless a `functions/tsconfig.json` file is created to override. Omitting this and then accidentally using a front-end tsconfig is a common mistake and can break the build for reasons such as https://github.com/cloudflare/wrangler2/issues/764.

### Content Location

Functions (beta) in a "Using TypeScript" section.

https://pages-plugins.cloudflare-docs-7ou.pages.dev/pages/platform/functions/

**Comment by MeikyuuTrader** [comment]
This just screwed me up. If you're using default Nextjs boilerplate, the tsconfig is es5, which caused issues in functions/api when during async await, json stringify.
