### ISSUE TITLE
Transform Rules: URL Normalization (Cloudflare Docs)

### ISSUE THREAD

**Issue by Earthpersonatpt** [cloudflare/cloudflare-docs#4168]
### Existing documentation URL(s)

https://developers.cloudflare.com/rules/normalization/

### Section that requires update

Main section

### What needs to change?

I believe there needs to be a clear note or indication that the URL normalization feature doesn't change the URL for the Eyeball/Browser. URL normalization does not redirect externally (eg: to the eyeball) it just changes the URL internally for processing.

### How should it change?

Something like this:

**NOTE: URL normalization does not redirect externally (eg: to the browser), it just changes the URL internally for processing.
This feature does not externally redirect/rewrite the URL.**

**Comment by pedrosousa** [comment]
Thank you for your feedback!
This was addressed in PR #4203.
