### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by bbhxwl** [cloudflare/cloudflare-docs#4173]
How do I get a token? Follow the tutorial and you will always be prompted that the authorization is incorrect.

https://developers.cloudflare.com/images/cloudflare-images/upload-images/direct-creator-upload/

**Comment by marciocloudflare** [comment]
Hey @bbhxwl. Go to https://developers.cloudflare.com/images/cloudflare-images/upload-images/api-token/. It explains what you need to create a token for Images. Thanks!
