### ISSUE TITLE
White screen of death comes up when I enable APO

### ISSUE THREAD

**Issue by gkcccvvv** [cloudflare/cloudflare-docs#4191]
We are using Automatic Platform Optimization servcie for our corporate website "mentpack.com"

It was working fine till last week. Even we didn't update anything on Cpanel or Wordpress, we have noticed that our website gone to "White screen" known as "White screen of death".

When i disable the APO from wordpress settings menu, everything went back as usual (except cloudflare's sweet caching). Once I enable the APO, website went into white screen in 1-2 minutes.

**Comment by kodster28** [comment]
Howdy @gkcccvvv, that's probably more appropriate for a [support request](https://support.cloudflare.com/hc/en-us/articles/200172476-Contacting-Cloudflare-Support) since it sounds like a bug as opposed to a misconfiguration.

Tagging our assigned writer just in case I'm missing something here.

**Comment by gkcccvvv** [comment]
Thank you
