### ISSUE TITLE
Device serial numbers - Cloudflare Zero Trust

### ISSUE THREAD

**Issue by lfcassidy** [cloudflare/cloudflare-docs#4198]
### Existing documentation URL(s)

- [link(s) to existing https://developers.cloudflare.com/... pages](https://developers.cloudflare.com/cloudflare-one/identity/devices/corp-device/)

### Section that requires update

Under section - Determine the serial number

### What needs to change?

1. Blue box beginning "You must ensure..." seems to give details about OS version numbers, not serial numbers. This also applies to the part above this box - "...in a format matching what the OS Version posture check expects."
2. The suggested command for macOS doesn't return anything

### How should it change?

For the macOS command, the following could work:

`system_profiler SPHardwareDataType | grep 'Serial Number'`

### Additional information

Any other details or screenshots that may be relevant.

**Comment by ranbel** [comment]
Thank you for bringing this issue to our attention and for proposing a fix. #5550
