### ISSUE TITLE
[Mobile SDK] Crash iOS issue when using Cloudflare Mobile SDK with Carto Mobile SDK (Map SDK)

### ISSUE THREAD

**Issue by rumitspkt** [cloudflare/cloudflare-docs#420]
Hi Team, i got a weird crash when using Cloudflare Mobile SDK with Carto Mobile SDK.

Carto Mobile SDK is a mobile mapping SDK (like Google Map, Apple Map). Under the hood, it loads map data (map tile) from our server. Map tile is a static file, URL with format: `https://bmap-tiles-a.busmap.vn/data/vietnam/{z}/{x}/{y}.mvt`, x y z are ids of a tile, map layer is displayed when tiles map are loaded. This SDK written in native C++.

Reproduce crash: Open Map screen, move map (load tile) and crash.

Version Cloudflare Mobile SDK: 5.0.0.2. https://github.com/CocoaPods/Specs/tree/master/Specs/6/9/b/CloudflareMobileSDK/5.0.0.2

Device: Only iOS < 14. (iOS >= 14 and Simulator work fine).

It is weird that when I check Firebase Crashlytics, crash log only appears in another library in app:
![with soha](https://user-images.githubusercontent.com/24636165/101140299-5a444900-3645-11eb-8ec0-5aa8294f588f.png)

I remove this library from log, I got another crash log from another library again:
![remove soha](https://user-images.githubusercontent.com/24636165/101140505-a55e5c00-3645-11eb-9ab3-766f66b0e0d6.png)

After all, I remove all library that I got crash log:
![remove all](https://user-images.githubusercontent.com/24636165/101140577-bad38600-3645-11eb-8677-bb62085001ae.png)

One more thing, I downgrade to 3.1.1.2 Cloudflare Mobile SDK. No crash occurs.
https://github.com/CocoaPods/Specs/tree/master/Specs/6/9/b/CloudflareMobileSDK/3.1.1.2

Our team are trying to find out problem. I hope Cloudflare Team support and give some advise. Many thanks.

**Comment by KimJ15** [comment]
👋 @rumitspkt - I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
