### ISSUE TITLE
Explicit enumeration of certificate chain

### ISSUE THREAD

**Issue by andrewdunndev** [cloudflare/cloudflare-docs#422]
Would be nice if there was a cloudflare enpoint to pull the specific certificates required to verify their certificate chain for DoH. Or if there was link/documentation for that to upstream resources.

**Comment by Lekensteyn** [comment]
You can use your system CA list, AFAIK there is no commitment to a fixed CA root.

**Comment by KimJ15** [comment]
Lekensteyn responded with a fix. Closing PR.
