### ISSUE TITLE
Broken link to parameter plist file

### ISSUE THREAD

**Issue by securitygeneration** [cloudflare/cloudflare-docs#4220]
The link to the plist file is broken:

https://github.com/cloudflare/cloudflare-docs/blob/478cb6260585652434d6c8732fb89d30b8de9c39/content/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/_index.md?plain=1#L64

**Comment by kodster28** [comment]
Howdy @securitygeneration, should be fixed now. Apologies, we're rolling out a new transform rule and didn't account for that file ending.
