### ISSUE TITLE
documentation around Workers/Page Rule interaction is unclear

### ISSUE THREAD

**Issue by pclalv** [cloudflare/cloudflare-docs#4259]
### Existing documentation URL(s)

- developer docs page: https://github.com/cloudflare/cloudflare-docs/commit/297724d7890abd7124ee395dae17e144eeafab8a
- support page: https://support.cloudflare.com/hc/en-us/articles/218411427-Understanding-and-configuring-Cloudflare-Page-Rules-Page-Rules-Tutorial-#h_5lzcszkjqrZ2bZpZOtMQoP

### Section that requires update

* "Workers custom routes take precedence over Page Rules" in the support page
* "Disabled Page Rules" in the developer docs page

#### inconsistent/contradiction

These pages seem to contradict each other. 

The developer docs page reads: 
>3. Because this is a Worker route, Cloudflare disables a number of features, including some that would be set by Page Rules.
>4. Page Rules run as part of normal request processing with some features now disabled.
This suggests that some Page Rules may run for Worker routes.

The support page reads:
>If the URL of the current request matches both a Page Rule and a [Workers custom route](https://developers.cloudflare.com/workers/platform/routes), the Worker script assigned to the custom route will execute and the Page Rule will not be applied.
This suggests that no Page Rules will run for Worker routes.

#### "Page rules are disabled" is unclear

The developer docs page reads:
>The following Page Rules are disabled when an incoming request is matched to a Worker route:

"Disabled" seems ambiguous, to me. Does this mean that Page Rules cannot alter those settings for Worker routes? Or does this mean that those settings are always disabled for Worker routes? From my experience, it seems that the former is the case - that a Page Rule cannot, for example, be used to turn Rocket Loader off for a Worker route when Rocket Loader is globally on. 

### How should it change?

* Resolve the apparent contradiction between the support page and the developer docs page
* Use more precise and well-defined terminology in the "Disabled Page Rules" section of the developer docs page

**Comment by deadlypants1973** [comment]
Hi, thanks for bringing this to our attention! The support article has been updated, but the dev docs will take some time to update. You are correct that "this mean that Page Rules cannot alter those settings for Worker routes". We'll need to test before we publish a revised explanation.
