### ISSUE TITLE
Add docs for Workers `WebSocketPair` API

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#427]
As per https://github.com/cloudflare/workers-chat-demo:

> To accept the WebSocket request, we create a WebSocketPair (which is like a socketpair,
> i.e. two WebSockets that talk to each other), we return one end of the pair in the
> response, and we operate on the other end. Note that this API is not part of the
> Fetch API standard; unfortunately, the Fetch API / Service Workers specs do not define
> any way to act as a WebSocket server today.

https://linc.sh/blog/durable-objects-in-production#the-object also has some example code with these.

It appears this was added at the same time as Durable Objects, but has no documentation available yet. Is `WebSocketPair` considered unstable and not recommended for use yet, or has it simply not been documented at this point?

**Comment by deadlypants1973** [comment]
This issue has been resolved: https://developers.cloudflare.com/workers/runtime-apis/websockets

PR: https://github.com/cloudflare/cloudflare-docs/pull/1086
