### ISSUE TITLE
How to Block or Allow based on Resolved IP Geo Location?

### ISSUE THREAD

**Issue by ArcCal** [cloudflare/cloudflare-docs#4276]
About one week ago, Administrators can set DNS policies based on Resolved IP Geo Location?

Now the feature just disappears?

Cloud u please add this feature back?

This feature is really very useful

**Comment by kodster28** [comment]
Howdy @ArcCal, this sounds more like Product feedback than anything related to the Product documentation. Are you talking about functionality in Cloudflare Zero Trust or another product (can pass along feedback to the PM, but will close out this issue)?
