### ISSUE TITLE
Unable to resolve pkg.cloudflareclient.com

### ISSUE THREAD

**Issue by lrehmann** [cloudflare/cloudflare-docs#4337]
While connected to Cloudflare Warp on a linux machine, you're unable to update due to pkg.cloudflareclient.com not resolving
```
Err:1 https://pkg.cloudflareclient.com focal/main amd64 cloudflare-warp amd64 2022.4.235-1
  Temporary failure resolving 'pkg.cloudflareclient.com'
```

Adding the IP to /etc/hosts fixes the issue, indicating it's a DNS failure due to warp.

**Comment by ranbel** [comment]
Has this issue been resolved?

**Comment by kkrum** [comment]
Can you let us know if this is still an issue? I don't believe I've seen this problem on current builds since our DNS refactor.
