### ISSUE TITLE
Seemingly missing documentation on wrangler 2 environments

### ISSUE THREAD

**Issue by Frederik-Baetens** [cloudflare/cloudflare-docs#4346]
### Product

Wrangler 2

### Subject Matter

Environments

### Content Location

https://developers.cloudflare.com/workers/wrangler/environments/

### Additional information

The linked document currently states "This document describes the features and differences between the two.", but that's where it ends. There doesn't seem to be any explanation on features of wrangler 2 or differences between the two wrangler versions.

There is a feature comparison between the two here: https://developers.cloudflare.com/workers/wrangler/compare-v1-v2/, but that doesn't seem to be specific to environments.

**Comment by deadlypants1973** [comment]
Hi @Frederik-Baetens , this feature is currently in development, and we've updated the page to reflect this: https://developers.cloudflare.com/workers/wrangler/environments/

Thanks so much for pointing this out :)
