### ISSUE TITLE
Add documentation on How to add Zaraz to a web app/website that has been deployed to CF Pages

### ISSUE THREAD

**Issue by omarmosid** [cloudflare/cloudflare-docs#4348]
### Product

Zaraz (or maybe Pages?)

### Subject Matter

Adding Zaraz to a web app/website that has been deployed to CF Pages

### Content Location

A new section called How To? Just like how we have a similar section for Pages docs

If a new section is a bit too much, we could have it under Advanced Options

### Additional information

I did the following:

1. Set up Proxying (Orange cloud) for my pages website that has a custom domain attached to it. **I know this is not relevant to Zaraz, but is an important precursor that has a significant impact on the UX provided by Zaraz.**
2. Resolved SSL issues (TOO_MANY_REDIRECTS). I had to google to figure this out and stumbled upon this https://support.cloudflare.com/hc/en-us/articles/115000219871-Troubleshooting-redirect-loop-errors-

A lot of users will face this, especially if they are migrating from services like Netlify, Vercel, etc to CF Pages.

While having your domain proxied through CF is not mandatory, it is most certainly a huge plus to have it already setup and allows quick onboarding within Zaraz. As a frontend developer, I would want to avoid spending too much time figuring out how to get things to work and this seems like a common scenario that I'd run into if I work on Static/SPA/Server Rendered websites.

**Comment by omarmosid** [comment]
Please let me know if I can work on coming up with a short draft document and post it here, or if you prefer I can directly submit a PR for someone from the team to review.

**Comment by deadlypants1973** [comment]
> Please let me know if I can work on coming up with a short draft document and post it here, or if you prefer I can directly submit a PR for someone from the team to review.

Hi @omarmosid , would like to review the PR if you can submit one :)

**Comment by marciocloudflare** [comment]
I'll also ping the Zaraz team and see if there's anything we should be aware of for cases like this one

**Comment by omarmosid** [comment]
Thank you for your response @deadlypants1973 @marciocloudflare 
Will try and see if I can submit a PR by tomorrow

Will be my first contribution here, please feel free to assign this issue to me

**Comment by marciocloudflare** [comment]
We actually assign issues to the writer that works with that product. As this is a Zaraz issue, that will be me. I've also spoken with the Zaraz PM, and we'll be looking into creating something with the Pages PM regarding this. You can still open up a PR if you want or wait until we have a solution in-house :)

**Comment by marciocloudflare** [comment]
It seems this is more of a Pages issue. Unsure about urgency, though.
