### ISSUE TITLE
Missing jurisdiction in relation to policy legal statements

### ISSUE THREAD

**Issue by gitcnd** [cloudflare/cloudflare-docs#4350]
This URL: https://developers.cloudflare.com/1.1.1.1/privacy/public-dns-resolver/
fails to disclose the jurisdiction that apply to statements it makes, particularly those relating to the term "legal".

e.g. "We also commit to documenting any government request to block access in our semi-annual transparency report, unless legally prohibited from doing so."

If, for example, you're based in the USA, and you get an access demand from Australia along with a gag order, Australian law does NOT APPLY in the USA, so such a request would NOT "legally prevent" you from disclosing it.

Thus, it is important that your policy informs users what jurisdiction you are in, so we can understand the global extent of any gag orders you get.

**Comment by gitcnd** [comment]
p.s. It would be helpful if you added a hyperlink to "our semi-annual transparency report"

**Comment by gitcnd** [comment]
p.p.s - your archive page is out-of-date https://www.cloudflare.com/transparency/archive/

also - you are missing your most recent report (end of 2021)

**Comment by haleycode** [comment]
These questions should be answered in our H2 2021 transparency report here: https://www.cloudflare.com/transparency/

Closing the ticket out for now.

**Comment by gitcnd** [comment]
I did not ask any question - I pointed out a significant legal omission, and no - it's not "answered" in any report - so closing this issue was wrong, and marking is as "completed" was fraudulent.

**Comment by gitcnd** [comment]
Since you don't seem to want to be honest, let me point you directly at some of the laws involved:-

Overview:-
https://www.schneier.com/blog/archives/2015/03/australia_outla.html

Legislation:-
https://parlinfo.aph.gov.au/parlInfo/download/legislation/bills/r6195_first-reps/toc_pdf/18204b01.pdf;fileType=application/pdf

Search for the phrase "(ii) the existence or non-existence of a technical assistance request;"

The criminal penalty for the wording on your web site is 5 years prison and $11,000,000

The fact that you're willfully misleading all your users by failing to inform them of your actual legal inability to be transparent is IMHO a far more grave problem.

The fact that you locked my other report clearly indicates that you're utterly unwilling to be honest, to the point of censoring all discussion of your actions.  Shame on you.
