### ISSUE TITLE
Service binding configuration is missing in wrangler.toml documentation

### ISSUE THREAD

**Issue by moooji** [cloudflare/cloudflare-docs#4412]
### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/wrangler/configuration/

### Section that requires update

- Configure wrangler.toml

### What needs to change?

The shown wrangler.toml does not include entries for the new "service bindings" configuration

### How should it change?

I wish I would know :)

**Comment by janat08** [comment]
How do I make service worker bindings via wrangler.toml?
it doesn't say that in configuring wrangler.toml docs or service docs I think.

**Comment by janat08** [comment]
@deadlypants1973 a simple version posted here would be helpful.

**Comment by janat08** [comment]
Will it be available for pages?

**Comment by deadlypants1973** [comment]
> @deadlypants1973 a simple version posted here would be helpful.

hi @janat08 ! thank you for submitting this issue, @jkup is working on drafting a pr for this.

**Comment by ackushiw-rialtic** [comment]
Looks like Wrangler doesn't support service bindings yet

> As of January 2022, the dashboard is the only way to interact with Service environments. Support in Wrangler is coming in [v2.1](https://github.com/cloudflare/wrangler2/issues/27)

https://github.com/cloudflare/cloudflare-docs/pull/3175/files#diff-c048c632319cf7a192f49cdc44d574fd6a6c02499ef66551c9441c07892f1de4R24

**Comment by jkup** [comment]
@ackushiw-rialtic Service Bindings (being able to communicate between Workers)  is supported in Wrangler and I just need to update the docs!! Service Environments (being able to create staging or production environments and promote between them) is currently only supported in the Dashboard!
