### ISSUE TITLE
Environment Variables link broken in R2 Bindings section

### ISSUE THREAD

**Issue by paulantwilliams** [cloudflare/cloudflare-docs#4416]
### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/r2/#creating-a-binding

### Section that requires update

Creating a binding section has an aside with extra Bindings info. The link to Environment Variables documentation is currently a (broken) github.com URL, rather than the the cloudflare docs URL.

### What needs to change?

https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/runtime-apis/R2.md?plain=1

Replace link in line 20...

From: `[Environment Variables](https://github.com/workers/platform/environment-variables)`
To: `[Environment Variables](https://developers.cloudflare.com/workers/platform/environment-variables)`

**Comment by pedrosousa** [comment]
Thank you for submitting this issue, @paulantwilliams! The link URL has been fixed.
