### ISSUE TITLE
Pagination option on Manage Account > Configurations > Lists

### ISSUE THREAD

**Issue by angelperezleon** [cloudflare/cloudflare-docs#4418]
### Manage Account > Configurations > Lists

Which Cloudflare product(s) does this pertain to?
-> CloudFlare Websites
--> Manage Account > Configurations > Lists

### Can you add page numbers or Skip to end of the List due to fact only been able to traver per page means there is hundred of pages in worse scenario to get to the end.
In my case I have a List - with nearly 10,000 IP address that I block due to hack attempts detected from these networks.
And if i need to manage the list, i.e. remove a single IP from that list its practically impossible to browse to the IP in question and remove it if I wanted too.  I would have to click on the Next button hundred of times. Again in my case 400 times, hitting the next button.

What needs to be documented?

###Manage Account > Configurations > Lists

Pagination option/improvement
Also, ability to search the list for specific items/IP's in case one need to be removed for example.

Please provide any URLs to existing documents.

### Additional information

I have looked here for info on what can I do my end to make the above possible, but I cant see an option todo what I want.
https://api.cloudflare.com/#rules-lists-list-lists

**Comment by kodster28** [comment]
Howdy @angelperezleon, unfortunately this is a documentation repo, so we can't do much to fix this... but I'll pass along the feedback to the PM regardless.

**Comment by angelperezleon** [comment]
OK thanks Kody.
