### ISSUE TITLE
Fast-navigation missing

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/cloudflare-docs#4434]
### Example URL(s)

Missing:
- https://developers.cloudflare.com/pages/platform/functions

Still works:
- https://developers.cloudflare.com/pages/platform/branch-build-controls/

### Actual Behavior

- Fast-scroll navigation is missing. In the example given, there used to be links on the right to scroll to certain sections of the current page.
- Seems to only happen on some pages.
- My screen size did not change, but that sidebar has suddenly disappeared.
- Screenshot is attached of current behavior, seems to only occur on some pages:
<img width="1512" alt="Screen Shot 2022-05-14 at 12 02 39" src="https://user-images.githubusercontent.com/6243993/168439649-be2ff15a-387b-4a72-b0ea-a518e57cc4ca.png">

### Expected Behavior

- There used to be a sidebar to scroll to a certain section of the page (for example, in the Functions documentation, the Advanced Mode section).
- When clicked, it would change the page hash which would cause a browser scroll to that section.
- This issue only occurs on some pages. Screenshot of **working** page is attached:
<img width="1512" alt="Screen Shot 2022-05-14 at 12 03 45" src="https://user-images.githubusercontent.com/6243993/168439694-432b1ef5-4aec-4c8e-baf2-60f854c2e5f5.png">

### Additional information

OS: MacOS Monterey, 12.3.1
Browser: Firefox 101.0b3 (64-bit)

**Comment by isaac-mcfadyen** [comment]
Possibly because the linked page (Functions) is a "category page" with sub-pages under it. This is still likely unwanted behavior though.

**Comment by kodster28** [comment]
Should be addressed in ~10 min (once that PR build goes live).
