### ISSUE TITLE
Image ID has incorrect max length

### ISSUE THREAD

**Issue by ivoilic** [cloudflare/cloudflare-docs#4439]
### Existing documentation URL(s)

- https://api.cloudflare.com/#cloudflare-images-properties

### Section that requires update

CloudFlare Image Properties - Object definition

### What needs to change?

The object definition states that image IDs are a maximum of 32 characters. However, the values returned by the API are 36 characters (including dashes). This was tested with the endpoint: `https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/images/v1`

Edit: The max of 32 character for the filename seems to also be incorrect, 36 characters were accepted without issue.

### How should it change?

Either the API should follow the object definition in the docs of visa-versa. Also if these are UUIDs (which is what they look like), it would be nice to include that info in the definition as well.

### Additional information

~~If these are 36 characters is it possible the filename max of 32 might also be incorrect?~~ Confirmed: This max is also wrong! Would be great if that was also 36 so full UUIDs could be used there as well.

**Comment by KimJ15** [comment]
Thanks for the update! I am moving this issue to our API workflow where we will confirm with the product team that this update is still validate (given the time since the issue was open).
