### ISSUE TITLE
Coverage of presigned URLs/presigned POST requests

### ISSUE THREAD

**Issue by fomojola** [cloudflare/cloudflare-docs#4455]
### Existing documentation URL(s)

https://developers.cloudflare.com/r2/platform/s3-compatibility/api/
https://developers.cloudflare.com/r2/examples/aws-sdk-js/

### Section that requires update

The list of sample code showing the calls to listObjects() and listBuckets() doesn't provide any examples of presigned URLs 
 similar to 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

 or presigned POSTs like 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/HTTPPOSTExamples.html#HTTPPOSTExamplesFileUpload.

Are these even supported operations? The compatibility matrix at https://developers.cloudflare.com/r2/platform/s3-compatibility/api/ doesn't say whether or not these are supported.

### What needs to change?

Updates to clarify which operations are supported: the direct browser upload functionality is a staple of S3 usage, and as I (and probably many others) feverishly work to replace S3 usage with R2, this will speed up possible implementations. Browser presigned POSTs would be nice, but in a pinch presigned PUTs could be used as well. This is available for the Cloudflare Stream service, so it seems reasonable to expect it to be in the R2 implementation.

### How should it change?

List if these functions are supported and (possibly) provide samples of the right way to call them.

**Comment by fomojola** [comment]
Comments: I have the basic s3 sdk configured and working: I can upload and download files via the API. It is specifically when I am trying to generate presigned urls (so I can upload/download using curl) and signed POSTs (so I can upload from a browser) that I'm having difficulty. I'm uncertain if its CORS related (there isn't any CORS configuration available), and given that its still in beta maybe I'm just ahead of the curve here. But after about 7 hours of torturing my code I figured if I ask here maybe answers will have emerged by the time I wake up.

**Comment by KianNH** [comment]
R2 doesn't currently support presigned URLs - they're on the roadmap.

**Comment by fomojola** [comment]
Thank you! Will table my migration now and resume once those become available.

**Comment by Flynsarmy** [comment]
Are multipart uploads impossible without presigned URLs?

**Comment by KianNH** [comment]
No, you can still do them - just not by using presigned URLs

Authenticating at the time of the request with any AWS SDK or utility like rclone will work.

**Comment by st1992** [comment]
Any ETA/timeline on when presigned URLs will be supported by R2?

**Comment by Flynsarmy** [comment]
> Authenticating at the time of the request with any AWS SDK or utility like rclone will work.

This won't work client-side with an uploader like [Uppy](https://uppy.io/) as there's no secure way to get the keys client-side in order to authenticate right?. So no direct client-side uploads to R2 until presigned URLs are supported?

**Comment by KianNH** [comment]
R2 has just launched presigned URL support.

**Comment by Flynsarmy** [comment]
Is there a latest product updates news feed somewhere?

**Comment by KianNH** [comment]
Currently for R2? Your best bet is our developer discord, https://discord.gg/cloudflaredev

Going forward, I have made a retroactive changelog. https://github.com/cloudflare/cloudflare-docs/pull/4853/files

**Comment by Flynsarmy** [comment]
Oh the changelog will be super useful. Tyvm!

**Comment by Flynsarmy** [comment]
After the changes I'm still getting CORS errors:

> Access to XMLHttpRequest at 'https://mybucket.r2.cloudflarestorage.com/myfile.jpg?uploadId=some_id&partNumber=1&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=some_credential&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Signature=some_signature from origin 'https://mysite.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is there a way to set CORS policy for R2 or are client-side uploads still not possible?

**Comment by computerex** [comment]
Having same issue myself. I have managed to produce a pre-signed URL where I can `put` stuff with postman + requests:
```
response = cl.generate_presigned_url(
        ClientMethod = 'put_object',
        Params = {
            'Bucket': 'orbiter-mods',
            'Key': key,
        },
        ExpiresIn=3600
    )

file_size = os.path.getsize(filename)

    with open(filename, "rb") as f:
        with tqdm(total=file_size, unit="B", unit_scale=True, unit_divisor=1024) as t:
            wrapped_file = CallbackIOWrapper(t.update, f, "read")
            requests.put(response, data=wrapped_file)
```

This works flawlessly. 

Trying to PUT to the generated URL via ajax results in CORS issue like above. Trying to use form to put like this also fails:


```
<form action="https://<account_id>.r2.cloudflarestorage.com/orbiter-mods/foo/test1.JPG?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<credential>&X-Amz-Date=20220704T163733Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=<signature>" method="put" enctype="multipart/form-data">
      <!-- Copy the 'fields' key:values returned by S3Client.generate_presigned_post() -->
      <input type="hidden" name="X-Amz-Algorithm" value="AWS4-HMAC-SHA256" />
      <input type="hidden" name="X-Amz-Credential" value="<crednetial>" />
      <input type="hidden" name="X-Amz-Date" value="20220704T165618Z" />
      <input type="hidden" name="X-Amz-Expires" value="3600" />
      <input type="hidden" name="X-Amz-SignedHeaders" value="host" />
      <input type="hidden" name="X-Amz-Signature" value="<signature>" />
    File:
      <input type="file"   name="foo/test1.JPG" /> <br />
      <input type="submit" name="submit" value="Upload to Amazon S3" />
    </form>
```

Results in a `403`:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your secret access key and signing method. </Message>
</Error>
```

**Comment by brunoprietog** [comment]
I too have CORS errors using pre-signed URLs.

**Comment by focux** [comment]
Same, I'm experiencing CORS issues when trying to upload a file using a presigned post url.

**Comment by merlinaudio** [comment]
+1 for CORS issues on presigned urls -- would really appreciate some guidance!

**Comment by cpursley** [comment]
Is there any solution to this? Maybe there's way to use a worker as a proxy for presigned downloads/uploads?

**Comment by domi007** [comment]
> Is there any solution to this? Maybe there's way to use a worker as a proxy for presigned downloads/uploads?

If you are already using a worker then there is no need for a worker. Most of us want to skip the worker step, because it is not necessary or wanted.
In case you just want a worker proxying the bucket contents to the outside world there is an example in the documentation doing just that.

EDIT: and yes, I'm also struggling with CORS errors, so if somebody at CF could just ensure setting the ```Access-Control-Allow-Origin``` header to ```*``` we would be all very happy :)
