### ISSUE TITLE
Two fields in `R2Objects` have the same name.

### ISSUE THREAD

**Issue by balusch** [cloudflare/cloudflare-docs#4501]
### Example URL(s)

https://developers.cloudflare.com/workers/runtime-apis/r2/#r2objects

<img width="728" alt="image" src="https://user-images.githubusercontent.com/23381018/169291340-783f1b73-70df-412c-90aa-e2a34008c81b.png">

### Actual Behavior

Two fields in `R2Objects` have the same name.

### Expected Behavior

Explain the expected behavior.

### Additional information

Any other details or screenshots that may be relevant.

**Comment by KianNH** [comment]
Will be closed by https://github.com/cloudflare/cloudflare-docs/pull/4450

**Comment by KianNH** [comment]
This has been fixed in the R2 docs but looks like the Worker docs hasn't - will make a PR to fix

**Comment by KianNH** [comment]
@deadlypants1973 this was fixed by https://github.com/cloudflare/cloudflare-docs/pull/4662
