### ISSUE TITLE
S3 API compatibility: x-amz-checksum-algorithm

### ISSUE THREAD

**Issue by imjasonh** [cloudflare/cloudflare-docs#4508]
### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/platform/s3-compatibility/api/

### Section that requires update

`CopyObject` section

### What needs to change?

Add `❌ x-amz-checksum-algorithm`

### How should it change?

The header should be added to denote that it's not currently supported.

Or, if some values of the header are supported and others aren't, document it to make that clear.

### Additional information

When I try to copy an object using this header, I get the error response:

```
S3: CopyObject, https response error StatusCode: 501, RequestID: , HostID: , api error NotImplemented: Header 'x-amz-checksum-algorithm' with value 'SHA256' not implemented
```

The [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#) say:

> **Checksums**
> 
> When copying an object, if it has a checksum, that checksum will be copied to the new object by default. When you copy the object over, you may optionally specify a different checksum algorithm to use with the x-amz-checksum-algorithm header.

**Comment by KianNH** [comment]
Tested the 4 valid values and none worked so it appears to be fully unimplemented.
