### ISSUE TITLE
testing new issue workflow

### ISSUE THREAD

**Issue by lukeed** [cloudflare/cloudflare-docs#4524]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/
- https://developers.cloudflare.com/workers/platform/bindings/

### Section that requires update

foobar

### What needs to change?

socks

### How should it change?

quickly

### Additional information

kate should be assigned automatically via workflow

**Comment by lukeed** [comment]
woot

**Comment by kristianfreeman** [comment]
gonna miss you buddy 😭
