### ISSUE TITLE
URL format of background image resizing property is incorrect

### ISSUE THREAD

**Issue by kornelski** [cloudflare/cloudflare-docs#4532]
### Which Cloudflare product does this pertain to?

Image Optimization

### Existing documentation URL(s)

https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/#background

### Section that requires update

`background=#RRGGBB` syntax won't work in the URL, because `#` is a special character that starts a URL fragment.

### What needs to change?

`#` must be written as `%23`

### How should it change?

`#` must be written as `%23`

**Comment by marciocloudflare** [comment]
Fixed in #4534
