### ISSUE TITLE
The definition of `R2HeadOptions` is missing.

### ISSUE THREAD

**Issue by balusch** [cloudflare/cloudflare-docs#4572]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/runtime-apis

### Section that requires update

**Method-specific types**

### What needs to change?

The definition of `R2HeadOptions`.

### How should it change?

Add the definition of `R2HeadOptions` since other kinds of API options are explained.

**Comment by vlovich** [comment]
`head` doesn't take any options currently. https://github.com/cloudflare/workers-types/blob/92f8e38fc62e23801b9bd6cc153b6cb44b96834e/index.d.ts#L1007

**Comment by balusch** [comment]
@vlovich Or maybe the definition of `head` method is wrong.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/23381018/170504737-826d4e8e-204e-40c5-9540-ddb3d7536bf5.png">

**Comment by deadlypants1973** [comment]
> @vlovich Or maybe the definition of `head` method is wrong.
> 
> <img alt="image" width="689" src="https://user-images.githubusercontent.com/23381018/170504737-826d4e8e-204e-40c5-9540-ddb3d7536bf5.png">

@balusch `head` has been updated in #4650 :) let me know if this is still an issue.
