### ISSUE TITLE
Examples for Create a Spectrum application using a CNAME record

### ISSUE THREAD

**Issue by anjana2401** [cloudflare/cloudflare-docs#4595]
### Which Cloudflare product does this pertain to?

Spectrum

### Existing documentation URL(s)

https://developers.cloudflare.com/spectrum/get-started/

### Section that requires update

https://developers.cloudflare.com/spectrum/get-started/#create-a-spectrum-application-using-a-cname-record

### What needs to change?

Please include some examples mentioning what kind of CNAME records(Added Example screenshots)

### How should it change?

Origin here can be an IP/ domain name (If you put domain name as origin, you need to use a domain name that matches your zone because Cloudflare checks internal DNS records not external.  For example, **abcd.amazonaws.com** is the origin for the spectrum app, please create a dummy DNS record on your zone such as spectrum.example.com ( your zone is example.com) to CNAME to **abcd.amazonaws.com** and put **spectrum.example.com** as the origin in the Spectrum app.)

<img width="647" alt="Screen Shot 2022-05-26 at 5 10 25 PM" src="https://user-images.githubusercontent.com/89989820/170580824-689d6daf-bf78-4979-abf3-1d1cf32c2968.png">

<img width="874" alt="Screen Shot 2022-05-26 at 5 11 47 PM" src="https://user-images.githubusercontent.com/89989820/170580954-651838fe-6760-4e0a-b7d8-b658e3e9f482.png">

**Comment by angelampcosta** [comment]
Hi @anjana2401, you can find more information about how to use CNAME records here: https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/#create-dns-records 
 I'm going to close it now, but feel free to open a new issue or ask any questions.
