### ISSUE TITLE
MacOS system requirements - contradiction/clarification?

### ISSUE THREAD

**Issue by cdn-content** [cloudflare/cloudflare-docs#4617]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/warp-client/get-started/

### Section that requires update

The table entry for the MacOS system requirements is confusing. (Column 2 "MacOS," row 2 "OS version" under the operating system headings).

### What needs to change?

It appears someone left the word "High" in the "OS version" row but did not finish writing what appears to be "High Sierra." The entry instead reads "High Mojave+" (10.14+) leaving the prospective user uncertain as to whether 1.1.1.1/WARP Client requires a minimum of MacOS 10.14 (Mojave) or can also run on High Sierra (per the incomplete wording).

### How should it change?

If someone could clarify the minimum system requirements to run 1.1.1.1/WARP Client on MacOS, either by removing the word "High" and leaving only "Mojave," or completing "High Sierra" and then redoing the numerical OS version (which is 10.13, not 10.14), it would be appreciated. As of now I am not sure as to whether it can run on High Sierra or requires an OS no lower than Mojave.

### Additional information

![image](https://user-images.githubusercontent.com/58697911/170856644-a99487f3-6ae7-4541-94d3-db3c20d196bd.png)

**Comment by marciocloudflare** [comment]
Hey @cdn-content. The table should read Mojave+ (so 10.14 and up). Thanks for catching this. Will update soon.

**Comment by marciocloudflare** [comment]
Done. Thanks!

**Comment by Zibroff** [comment]
I'm sorry for unrelevant question:
Which version 1.1.1.1 suitable fo macOS Sierra?

**Comment by marciocloudflare** [comment]
Hey @Zibroff. You don't need a specific version of MacOS to use 1.1.1.1. You can just change your DNS servers directly in the OS and use 1.1.1.1. More info at https://developers.cloudflare.com/1.1.1.1/setup/macos/

**Comment by Zibroff** [comment]
Thank you very mach for answer!

I mean a version of WARP Client for macOS Sierra. May be I able to found one on this page?
https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-macos-1/distribution_groups/release

**Comment by marciocloudflare** [comment]
As far as I know, WARP doesn't support Sierra. I'm not sure which older version does, but I'd say it's not recommended to use older versions of any software. Maybe reach out to https://community.cloudflare.com/

**Comment by Zibroff** [comment]
@marciocloudflare 
Thank you again!
