### ISSUE TITLE
R2 Storgage Implementation with S3

### ISSUE THREAD

**Issue by tfidmmatthew** [cloudflare/cloudflare-docs#4619]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

How Secret Access Key and Access Key ID be implemented in Postman

### Content Location

https://github.com/cloudflare/cloudflare-docs/blob/production/content/r2/platform/s3-compatibility/tokens.md

### Additional information

Please illustrate how Secret Access Key and Access Key ID to be implemented in authorization section in an API call?

**Comment by KianNH** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/4653

**Comment by tfidmmatthew** [comment]
@KianNH Thanks for the help. Closing issue as it resolve.
