### ISSUE TITLE
Weird keys in `R2Objects`.

### ISSUE THREAD

**Issue by balusch** [cloudflare/cloudflare-docs#4630]
### Example URL(s)

https://developers.cloudflare.com/r2/runtime-apis/#r2objects

### Actual Behavior

I want to access some object listed by `BUCKET.list` like this:

```javascript
const listing = await BUCKET.list(undefined)
const o = listing.objects[0]
```

But then I met a runtime error `Cannot read properties of undefined` in `objects[2]`. Isn't `objects` a property of `R2Objects`? Then I printed the keys in `R2Objects`:

```javascript
console.log(Object.keys(listing))
```

and finally got `keys`, `isTruncated` and `nextContinuationToken` not `objects`, `truncated`, `cursor`, and `delimitedPrefixes` listed in the API manual. Maybe there was something wrong in my operation, but I haven't figured it out.

### Expected Behavior

```javascript
console.log(Object.keys(listing))
```
print all the fields of `R2Objects` listed in the API manual.

**Comment by KianNH** [comment]
Did you do this in the Quick Edit/Preview within the dashboard? It currently picks up the old, internal bindings - with the old parameters/etc that you've noticed.

Example (Quick Edit):

![image](https://user-images.githubusercontent.com/94662631/171738230-34603e85-dae2-4c9f-aebc-79e00a4369cf.png)

Example (Published):

![image](https://user-images.githubusercontent.com/94662631/171738290-5957ae9f-f552-4b55-9701-d60cfa106800.png)

The internal bindings that Quick Edit/Preview still picks up are deprecated and it's a known issue that will be fixed.

**Comment by KianNH** [comment]
Checked with the R2 team, the issue with Preview using old bindings should be on track to be fixed in the coming week.

**Comment by KianNH** [comment]
This should be fixed (old bindings in Quick Edit’s Preview)

**Comment by balusch** [comment]
> Did you do this in the Quick Edit/Preview within the dashboard? It currently picks up the old, internal bindings - with the old parameters/etc that you've noticed.

Yes the Quick Edit within the dashboard.

> The internal bindings that Quick Edit/Preview still picks up are deprecated and it's a known issue that will be fixed.

So you mean that currently it can still work with new bindings if not using the dashboard(i.e.; deployed with wrangler directly)?

**Comment by KianNH** [comment]
> This should be fixed (old bindings in Quick Edit’s Preview)

It'll be a non-issue now.

https://community.cloudflare.com/t/2022-6-3-workers-runtime-release-notes/388582

**Comment by balusch** [comment]
> It'll be a non-issue now.

👍 I'll have a try later.

**Comment by deadlypants1973** [comment]
closed with @KianNH 's feedback but lmk if we need to reopen

**Comment by balusch** [comment]
@deadlypants1973 Hi! I tried R2 again serveral minutes ago and it works well 👍. 

But some related docs seems not updated and thus the examples are still using the old bindings.
I opened a [new issue](https://github.com/cloudflare/cloudflare-docs/issues/4751) for that.
