### ISSUE TITLE
R2 how to implement in .net project?

### ISSUE THREAD

**Issue by OrhanAykac** [cloudflare/cloudflare-docs#4683]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

.Net Example

### Content Location

Hi,
How to use R2 in .net project.
I cant find any document or example anywhere.
Thanks.

**Comment by OrhanAykac** [comment]
Hi, any news?

**Comment by KianNH** [comment]
It'll be no different to any other S3-compatible provider. Point it to your endpoint with the proper tokens (https://developers.cloudflare.com/r2/platform/s3-compatibility/tokens/) and make sure the bucket region is `auto`, `us-east-1` or empty.

**Comment by vlovich** [comment]
Adding onto this, you can probably use any S3 SDK (e.g. https://aws.amazon.com/sdk-for-net/). We don't yet have examples for C# libraries it looks like. https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/quick-start-s3-1-cross.html is probably a fine initial guide. Note that you probably want to customize your creds either by adjusting the shared AWS credentials file as explained on that page (`~/.aws/credentials` on Linux and macOS systems, and `%USERPROFILE%\.aws\credentials` on Windows) or passing the creds to `new AmazonS3Client()` (I think the API docs are here https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Client.html)

**Comment by KianNH** [comment]
As an example until I finish it up & PR it to the docs:

```csharp
private static IAmazonS3 s3Client;

public static void Main(string[] args) {
  var accessKey = "<ACCESS_KEY_ID>";
  var secretKey = "<SECRET_KEY_ID>";
  var credentials = new BasicAWSCredentials(accessKey, secretKey);
  s3Client = new AmazonS3Client(credentials, new AmazonS3Config {
    ServiceURL = "https://<ACCOUNT_ID>.r2.cloudflarestorage.com",
  });

  PutObject().Wait();
}

static async Task PutObject() {
    var request = new PutObjectRequest {
      FilePath = @ "/Users/kian/Downloads/foo.dmg",
        BucketName = "sdk-example",
        DisablePayloadSigning = true // required otherwise it attempts to use streaming sigv4
    };

    var response = await s3Client.PutObjectAsync(request)

    Console.WriteLine(response.ETag);
}    
```

**Comment by gee1k** [comment]
This error also exists when using the swift library soto, does anyone know how to fix it?

https://github.com/soto-project/soto
