### ISSUE TITLE
https://github.com/cloudflare/cloudflare-docs/pull/3175#pullrequestreview-995410109

### ISSUE THREAD

**Issue by Greatshopping** [cloudflare/cloudflare-docs#4689]
Apply

_Originally posted by @Greatshopping in https://github.com/cloudflare/cloudflare-docs/pull/3175#pullrequestreview-995410109_

**Comment by kodster28** [comment]
Howdy @Greatshopping, not sure there's anything actionable for us to do w/ this issue, so closing for now.

Feel free to re-open with more details though.
