### ISSUE TITLE
Caching disabled ports mean that I can use SSL cloudflare certificate without proxy limitation?

### ISSUE THREAD

**Issue by openaspace** [cloudflare/cloudflare-docs#4690]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/

Caching disabled ports mean that I can use SSL cloudflare certificate without proxy limitation?

Thank you.

### Section that requires update

Caching is disabled for the following ports

### What needs to change?

It's not clear if caching disable means that I can till use SSL certificate on the origin server without proxy limitations and have all the benefits of the direct connections, like receive and send big files.

### How should it change?

The SSL certificate on the origin server will works also on not standards ports with direct connections client/server

**Comment by KianNH** [comment]
Traffic on non-standard ports still goes through Cloudflare - like it says, only caching is disabled.
