### ISSUE TITLE
"R2 get started guide" doesn't work as-written, steps are out of order?

### ISSUE THREAD

**Issue by catharsis71** [cloudflare/cloudflare-docs#4697]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/get-started/

### Section that requires update

3. Create your bucket

### What needs to change?

The commands "wrangler r2 bucket create" and "wrangler r2 bucket list" will not work if executed at this point due to no wrangler.toml existing

```
$ wrangler r2 bucket create test
Error: wrangler.toml not found
$ wrangler r2 bucket list
Error: wrangler.toml not found
```

### How should it change?

this probably needs to be moved later so that a wrangler.toml will already exist

**Comment by KianNH** [comment]
Similarly to https://github.com/cloudflare/cloudflare-docs/issues/4698, this only an issue with the old `wrangler` - `wrangler2` supports these commands with no `wrangler.toml` present.

If https://developers.cloudflare.com/r2/get-started/#1-install-wrangler is followed then you would have `wrangler2` but people might skip that if they already have 'wrangler', albeit the old one.

@deadlypants1973 Might be worth adding an aside to explicitly say that wrangler is assumed to be 2.0 or higher?
