### ISSUE TITLE
wrangler.toml update for R2 configuration

### ISSUE THREAD

**Issue by gkocyigit** [cloudflare/cloudflare-docs#4699]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/

### Section that requires update

R2 Bucket configuration section in `wrangler.toml` should be updated.

### What needs to change?

```
....
# Specifies R2 buckets that are bound to this Worker environment.
# @default `[]`
# not inherited
r2_buckets  = [{
  # The binding name used to refer to the R2 bucket in the Worker.
  binding = "TEST_BUCKET",
  # The name of this R2 bucket at the edge.
  bucket_name = "",
  # The preview name of this R2 used during `wrangler dev`
  preview_bucket_name =  ""
}]
....
```

### How should it change?

```
....
# Specifies R2 buckets that are bound to this Worker environment.
[[r2_buckets]]
# The binding name used to refer to the R2 bucket in the Worker.
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
# The name of this R2 bucket at the edge.
bucket_name = '<YOUR_BUCKET_NAME>'
# The preview name of this R2 used during `wrangler dev`
preview_bucket_name =  "<YOUR_TEST_BUCKET_NAME>"
....
```

### Additional information

Reference: https://developers.cloudflare.com/r2/get-started/

**Comment by KianNH** [comment]
Looks like there's a similar issue already open - https://github.com/cloudflare/cloudflare-docs/issues/4695
