### ISSUE TITLE
Bad to read links in infopanel [darkmode]

### ISSUE THREAD

**Issue by dabenzel** [cloudflare/cloudflare-docs#4706]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/

### Actual Behavior

When in darkmode, the links in the infobox on this specific page are bad to read. When in whitemode, they are good to read

### Expected Behavior

Easy to read links also in darkmode

### Additional information

Dark-Mode:
![image](https://user-images.githubusercontent.com/2480235/172144424-21fbc0b0-6ce8-4819-b5ca-e08d93b34195.png)

White-Mode:
![image](https://user-images.githubusercontent.com/2480235/172144453-1781b835-17c3-4b50-a95b-5053b81e4d2b.png)

**Comment by kodster28** [comment]
Looks like there's actually quite a few issues with the `Asides` on that page, beyond just those links (which I'd guess are specified as <a> tags instead of markdown.

**Comment by kodster28** [comment]
This has been addressed by other work.
