### ISSUE TITLE
CloudFlare for SaaS Apex Vanity URL Verification

### ISSUE THREAD

**Issue by jericopulvera** [cloudflare/cloudflare-docs#4714]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/ssl-for-saas/common-tasks/hostname-verification/#apex-verification

### Section that requires update

`To verify ownership, the IP returned for the hostname must reside in the IP prefix allocated to the account.`

I can't understand this. Where do I get the IP prefix allocated to the account? Is this only available for enterprises or for everyone?

### What needs to change?

Add more information

### How should it change?

Add more information

**Comment by KianNH** [comment]
Apex domains fall under `Apex proxing/BYOIP` - `BYOIP` is an Enterprise product.

https://developers.cloudflare.com/byoip/

**Comment by kodster28** [comment]
As @KianNH mentioned, yeah, it's related to ENT customers. Added a bit more info to the page to make that clearer in the associated PR.

**Comment by fariborz4** [comment]
Tanks
