### ISSUE TITLE
Add `durable_object_alarms` compatibility flag

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#4742]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/compatibility-dates/#change-history

### Section that requires update

"Change History"

### What needs to change?

Alarms in Durable Objects require the [`durable_object_alarms` flag](https://developers.cloudflare.com/workers/learning/using-durable-objects/#alarms-in-durable-objects) to be set. This should be documented to this page of compat dates/flags.

### How should it change?

New record in the list

**Comment by koeninger** [comment]
It's already documented for alarms here https://developers.cloudflare.com/workers/learning/using-durable-objects/#alarms-in-durable-objects , and we're planning on removing the requirement for the compatibility flag soon - I wouldn't add it here

**Comment by GregBrimble** [comment]
Cool. I'll close this out then :)
