### ISSUE TITLE
Old bindings are still used in the get-started doc of R2.

### ISSUE THREAD

**Issue by balusch** [cloudflare/cloudflare-docs#4751]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/get-started/

### Section that requires update

All code examples.

### What needs to change?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/23381018/172794892-a48ab372-4961-41cb-9cdc-f44c5f10dc0c.png">

### How should it change?

`object.value` should be replaced with `object.body`

### Additional information

Perhaps there are some similar problems in other documents, and you guys may need a thorough check-up 😄.

**Comment by KianNH** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/4754
