### ISSUE TITLE
[Workers] Request for clarification of anti-abuse protection

### ISSUE THREAD

**Issue by arunesh90** [cloudflare/cloudflare-docs#4764]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/platform/limits/#request

### Section that requires update

Request

### What needs to change?

The `Request` section does currently not mention that you'll see firewall entries with `worker` as rule ID when the Workers anti-abuse protection has kicked in.
Currently customers may be quite confused when they suddenly see a lot of `worker` firewall entries, as they won't know that it's caused by the anti-abuse protection.

Here's an recent example of a customer who suddenly saw a lot of `worker` firewall entries, but wasn't aware that it was caused by the anti-abuse protection:
<img width="1448" alt="Screenshot 2022-06-09 at 21 18 11" src="https://user-images.githubusercontent.com/5787588/172926749-bc461124-04be-4352-bbaf-2c446a423161.png">

Here's the response I gave for reference:
<img width="1444" alt="Screenshot 2022-06-09 at 21 20 27" src="https://user-images.githubusercontent.com/5787588/172927403-82e1d791-ec2e-45e1-b66a-8c59a404e894.png">

### How should it change?

The `Request` section should include that the internal `worker` firewall rule is used by the Workers anti-abuse protection. Currently the `worker` firewall rule is nowhere mentioned in the documentation, so customers running into it may be a bit confused and not know what to do about it.

### Additional information

Not necessarily related to the documentation, but I would suggest Cloudflare to implement some kind of automatic notification when the anti-abuse protection has kicked in for a customer.
If for example, a customer is using Workers a lot internally for mission-critical work, it would help a lot if Cloudflare immediately notified them of traffic being too high and that they should immediately contact Cloudflare for a limit raise. Currently, Cloudflare will just drop a lot of requests without any notification, leaving customers completely clueless.

**Comment by helloimalastair** [comment]
While I can't address your note in *Additional Information*, #6425 should address your requested documentation change.

**Comment by deadlypants1973** [comment]
This has been documented, and a feature request is being tracked internally.

**Comment by kodster28** [comment]
Since this is done from a documentation perspective, closing out the issue from our repo.

**Comment by deadlypants1973** [comment]
This issue has been documented, and a fix is being tracked internally.
