### ISSUE TITLE
`.dev.vars` for providing local vars/secrets to `wrangler dev` should be documented

### ISSUE THREAD

**Issue by Erisa** [cloudflare/cloudflare-docs#4770]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

The `.dev.vars` file used by `wrangler dev`

### Content Location

https://developers.cloudflare.com/workers/wrangler/configuration/

### Additional information

The comment in wrangler explains it quite well: https://github.com/cloudflare/wrangler2/blob/d0801b77c3d10526041e1962679b2fd2283a8ac4/packages/wrangler/src/dev/dev-vars.ts#L15

This is useful primarily because in `wrangler dev` local mode there is no other way to provide a variable or secret without adding it to the `wrangler.toml`  which in many cases is undesirable.

The undocumented `.dev.vars` file lets you specify these variables more securely, and should be documented.

**Comment by Ekwuno** [comment]
Thanks for pointing this out @Erisa. This will be documented soon. Currently, you can only use `.dev.vars` with the beta of wrangler `npx wrangler@beta`. It’ll be in the next proper release of wrangler with the updated docs.

**Comment by Erisa** [comment]
Hi @Ekwuno!

`.dev.vars` is available in the stable release of wrangler2 when used against Workers (`wrangler dev`), it's been there for a while:
- https://github.com/cloudflare/wrangler2/commit/f6943132a04f17af68e2070756d1ec2aa2bdf0be
- https://github.com/cloudflare/wrangler2/commit/d0801b77c3d10526041e1962679b2fd2283a8ac4

It's support for it in Pages where it's only available in `wrangler@beta`: https://github.com/cloudflare/wrangler2/pull/1274

**Comment by Ekwuno** [comment]
Ah, apologies I was referring to Pages. I'll get this documented

**Comment by lauragift21** [comment]
Thanks for calling this out @Erisa, I've created a PR for this issue. https://github.com/cloudflare/cloudflare-docs/pull/5123

**Comment by Erisa** [comment]
Cheers @lauragift21! PR looks good!

**Comment by mliakos** [comment]
Thanks @Erisa, was banging my head.

**Comment by jsomeara** [comment]
This still isn't documented for Cloudflare workers. 

The current documentation is definitely misleading: https://developers.cloudflare.com/workers/platform/environment-variables/

**Comment by mliakos** [comment]
It's only mentioned here: https://developers.cloudflare.com/workers/wrangler/configuration/#environmental-variables

I guess there's a deeper structural problem within the docs 😛
