### ISSUE TITLE
Improvement suggestions for Cloudflare Workers documentation: secrets and importing/requiring external libraries

### ISSUE THREAD

**Issue by pirate** [cloudflare/cloudflare-docs#482]
As a new user to CloudFlare Workers, these were the friction points I encountered that I was unable to find answers for in the docs here: https://developers.cloudflare.com/workers/.

- How do we define environment variables / secrets in one place that all our workers can use? (e.g. API Keys, passwords, config vars, etc.)
![image](https://user-images.githubusercontent.com/511499/101909636-c49c4280-3b8b-11eb-92d5-be4a80256560.png)

- How can we import 3rd party node libraries in our workers? E.g. we need to use the backblaze node API library to get file upload tokens issued, but were unable to figure out how to `import`/`require('backblaze-b2')` in our worker code
![image](https://user-images.githubusercontent.com/511499/101909663-cf56d780-3b8b-11eb-8762-0d805b6b0217.png)
![image](https://user-images.githubusercontent.com/511499/101909684-d847a900-3b8b-11eb-84c6-c849e1601f82.png)

Thanks, and sorry if these are easy questions, hopefully if there are easy answers we can add them to the (beautiful) sidebar to make it easier for new users to find.

**Comment by KimJ15** [comment]
👋 @pirate Thank you for the recommendation in improving search. We have another project to optimize keywords and SEO and your feedback has been captured. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
