### ISSUE TITLE
WARP client Windows installation command - Managed deployment

### ISSUE THREAD

**Issue by matt-matt-tmatt** [cloudflare/cloudflare-docs#4824]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/

### Section that requires update

"To install the WARP client, run the following command:"

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/#install-warp-on-windows

### What needs to change?

Command runs OK manually on a console, but fails with MDM. Test with Workspace ONE and installed successfully with `msiexec /i "Cloudflare_WARP_Release-x64.msi" /qn ORGANIZATION="exampleorg" SERVICE_MODE="warp" SUPPORT_URL="http://support.example.com"`

Not sure if it applies for 100% of MDMs but took me a good time to troubleshoot.

### How should it change?

To uninstall the WARP client, run the following command:
`msiexec /i "Cloudflare_WARP_Release-x64.msi" /qn ORGANIZATION="exampleorg" SERVICE_MODE="warp" SUPPORT_URL="http://support.example.com"`

**Comment by kkrum** [comment]
Thanks for letting us know that WS1 needed a slightly different syntax. I've updated the example with the one you provide and it should be good for all.
