### ISSUE TITLE
Non-urgent | Update Mozilla Firefox DOH instructions

### ISSUE THREAD

**Issue by jasonbrown1965** [cloudflare/cloudflare-docs#485]
Might trip up some non-tech people, fwiw:

This page:
https://github.com/cloudflare/cloudflare-docs/blob/production/products/1.1.1.1/src/content/dns-over-https/web-browser.md

Has instructions:
"Open Preferences: Click on the hamburger icon at the top right corner of your browser, and click on Preferences."

But, my copy of Firefox 83.0:
Refers to "**Options**" not '_Preferences_' 

New users might also benefit from advice in Step 2 to:
"**Use search box by typing in** _Network_" 

And step 3:
"**Use search box by typing in** _DNS_." 

Or similar, to take users to the actual link, helpfully highlighted in yellow, rather than visual searching dozens of items. Especially as both items are below-the-fold (?) or require scrolling to access. The need to scroll down may not be immediately apparent to techno-noobs i.e. the majority of users in my own noobish experience. 

thanks!

**Comment by abracchi-tw** [comment]
hey, thanks for raising this! I've walked through the Firefox (85.0) flow and updated instructions accordingly. #702 should fix this.
