### ISSUE TITLE
Configure Cloudflared Tunnel Virtual Networks with YAML Configuration files

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflare-docs#4859]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/tunnel-virtual-networks/

### Section that requires update

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/tunnel-virtual-networks/#enable-virtual-networks

### What needs to change?

The sample yaml config

### How should it change?

Example of how to link a vnet to a tunnel as an alternative to running this command:
`$ cloudflared tunnel route ip add --vnet staging-vnet 10.128.0.3/32 staging-tunnel`

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request for Cloudflare Tunnels. Feel free to open an feature request with that team at https://github.com/cloudflare/cloudflared/issues.
