### ISSUE TITLE
"wrangler generate my-app https://github.com/cloudflare/worker-template" fails with "Git Error: failed to clone into: ..."

### ISSUE THREAD

**Issue by gr2m** [cloudflare/cloudflare-docs#487]
sorry if this is not the right place to report this problem, I'm not sure where the problem lies and I don't know how to further debug it.

I followed the docs and did the following

```
npm install -g @cloudflare/wrangler
wrangler generate my-app https://github.com/cloudflare/worker-template
```

But it failed with the following error:

```
🔧   Creating project called `my-app`...
Error: ⛔   Git Error: failed to clone into: /Users/gregor/Projects/cloudflare-workers/my-appIrjVg4                                                                                         
Error: tried running command:
/Users/gregor/Library/Caches/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/cloudflare/worker-template --name my-app --force
exited with exit code: 1
```

**Comment by gr2m** [comment]
```
$ node -v
v14.15.1
$ npm -v
6.14.8
```

**Comment by gr2m** [comment]
same problem as https://github.com/cloudflare/wrangler/issues/1168. This workaround worked for me: https://github.com/ashleygwilliams/cargo-generate/issues/168#issuecomment-520065102

the cause of the problem seems to be an upstream issue which maenwhile has been resolved: https://github.com/ashleygwilliams/cargo-generate/issues/168

**Comment by volkanunsal** [comment]
I'm still experiencing this issue. 

Node v15, npm v7.

**Comment by volkanunsal** [comment]
Solved it with this: https://github.com/rust-lang/cargo/issues/3381#issuecomment-308460530
