### ISSUE TITLE
Logpush Filters - unsupported fields for firewall_events dataset is missing "Action"

### ISSUE THREAD

**Issue by cloudsucked** [cloudflare/cloudflare-docs#4870]
### Which Cloudflare product does this pertain to?

Logs

### Existing documentation URL(s)

https://developers.cloudflare.com/logs/reference/logpush-api-configuration/filters/

### Section that requires update

"For the Firewall events dataset, the following fields are not supported: Kind, MatchIndex, Metadata, OriginatorRayID, RuleID, Source."

### What needs to change?

Action is also not supported and needs to be added.

### How should it change?

For the Firewall events dataset, the following fields are not supported: Action, Kind, MatchIndex, Metadata, OriginatorRayID, RuleID, Source.

**Comment by angelampcosta** [comment]
👋 @cloudsucked  Thank you for the feedback about how we can make improvements with[ developers.cloudflare.com](http://developers.cloudflare.com/) documentation. I have just made the change.
