### ISSUE TITLE
How to uninstall Debian Linux?

### ISSUE THREAD

**Issue by zhiting9420** [cloudflare/cloudflare-docs#4872]
### Example URL(s)

https://developers.cloudflare.com/warp-client/get-started/linux/

### Actual Behavior

No

### Expected Behavior

No

### Additional information

The DPKG program will run automatically at every startup and cannot find the installation location

**Comment by cicku** [comment]
sudo apt remove cloudflare-warp

**Comment by KimJ15** [comment]
Based on the comment above, it looks like this issue appears is be resolved. I'm going to close it now, but feel free to open a new issue or ask any questions.
