### ISSUE TITLE
WARP client Windows - Managed deployment - disable updates

### ISSUE THREAD

**Issue by gharik** [cloudflare/cloudflare-docs#4885]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/

### Section that requires update

 Install WARP on Windows

### What needs to change?

In case there is any possibility to disable or delay automatic client updates, it should be described.

### How should it change?

Description how to disable or postpone automatic Client updates should be added.

### Additional information

Update of cloudflare Warp Client usually requires local admin permissions. Because of security reasons it is not advised to give all users Local admin rights. 

User without admin rights gets a prompt from the app to update. However Installation cannot complete because of missing permissions. This results in another prompt.

In case of managed deployment, the updates in Windows environments are managed over tools like MECM. Of course, not all users get the update at the same time. Thus it can happen, that the prompt from app comes before the deployed update.

**Comment by kkrum** [comment]
This is supported via a dash setting described here: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/warp-settings/#allow-updates

Note that the functionality to allow different users to have different settings via the dash will be coming in the next few monts.
