### ISSUE TITLE
Document `--name` arg on `wrangler secret` subcommands

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/cloudflare-docs#4892]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/commands/#secret

### Section that requires update

Each of the `secret put`, `secret delete` and `secret list` commands need updating

### What needs to change?

The arguments for each of these commands.

### How should it change?

Add documentation about the `--name` argument.

**Comment by KianNH** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/5254
