### ISSUE TITLE
apply content security policy with cloudflare _headers eleventy 

### ISSUE THREAD

**Issue by ornelasnarciso** [cloudflare/cloudflare-docs#4896]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

How to apply _headers on a eleventy website  

### Content Location

https://developers.cloudflare.com/pages/platform/headers/

### Additional information

I tried to follow the docs but they are unclear or I'm missing something. Also looked on the web for more information but could not find a solution.

The steps: 

I've placed the "_headers" file ( tried "_headers" and "_headers.txt" since the documentation is not clear about the file extension) inside my "_site" folder, deployed the new file to cloudflare pages and nothing happened. 

It would be nice to have an example in how to apply this to a eleventy website and a working example.

**Comment by deadlypants1973** [comment]
@ornelasnarciso could you drop this question in the Pages-General Discord page? https://discord.gg/abxudRMg 
We have someone who will be able to help you with this :)

**Comment by ornelasnarciso** [comment]
Thanks @deadlypants1973 (funny username) I'll take a look, thanks for the help. :)
