### ISSUE TITLE
[Pages] SvelteKit Adapter for Pages

### ISSUE THREAD

**Issue by sei0o** [cloudflare/cloudflare-docs#4940]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/#deploying-with-cloudflare-pages

### Section that requires update

"Deploying with Cloudflare Pages" and its subsection "SvelteKit Configuration"

### What needs to change?

The documentation suggests us to use `adapter-static` SvelteKit adapter, but I suppose this should be updated since [`adapter-cloudflare`](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare) has been introduced.

Quote from `adapter-cloudflare`'s README: 
> - adapter-cloudflare – supports all SvelteKit features; builds for
Cloudflare Pages
> - adapter-cloudflare-workers – supports all SvelteKit features; builds for
Cloudflare Workers
> - adapter-static – only produces client-side static assets; compatible with
Cloudflare Pages
> 
> Note: Cloudflare Pages' new Workers integration is currently in beta.
> Compared to adapter-cloudflare-workers, this adapter will be the preferred approach for most users since building on top of Pages unlocks automatic builds and deploys, preview deployments, instant rollbacks, etc.
> From SvelteKit's perspective, there is no difference and no functionality loss when migrating to/from the Workers and the Pages adapters.

### How should it change?

Since `adapter-cloudflare` is a built-in feature for the default adapter, `adapter-auto`, this subsection "SvelteKit Configuration" could be deleted entirely.

As for the build parameters mentioned in the section "Deploying with Cloudflare Pages", the build (output) directory should be `.svelte-kit/cloudflare/` and `NODE_VERSION` should be set to `16` if you are going to use later SvelteKit (https://github.com/sveltejs/kit/issues/3003#issuecomment-1059609542).

**Comment by Ekwuno** [comment]
#5081  addresses this.
