### ISSUE TITLE
[Pages] Document adding DKIM with Mailchannels plugin

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#4943]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/functions/plugins/mailchannels/

### Section that requires update

https://developers.cloudflare.com/pages/platform/functions/plugins/mailchannels/#usage

### What needs to change?

We need to document how to add the DKIM signature - https://mailchannels.zendesk.com/hc/en-us/articles/7122849237389

### How should it change?

Explain what DKIM is, why we use it and add it into the code example.

**Comment by KianNH** [comment]
Can be closed (https://github.com/cloudflare/cloudflare-docs/pull/5096) - resolved by @Ekwuno
