### ISSUE TITLE
import causes error

### ISSUE THREAD

**Issue by ourmaninindia** [cloudflare/cloudflare-docs#4979]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/module-system/
I try to import the mailgun.js installed with npm 

This leads to this error though:

 _text: 'A request to the Cloudflare API
  (/accounts/57267b529e6d603103c1a98d4e7aa9ae/workers/scripts/contact-us/edge-preview)
  failed.',
    notes: [
      {
        text: 'Uncaught ReferenceError: define is not defined\n' +
          '  at line 24 in node_modules/mailgun.js/mailgun.web.js\n' +_

### Section that requires update

module-system

### What needs to change?

your writing seems perfect as I am able to replicate it but not for mailgun.js

### How should it change?

no idea. Please advise

**Comment by deadlypants1973** [comment]
Hi @ourmaninindia , could you post this in the Discord under the #workers channel? Someone will be able to help you :) 

here's the link: https://discord.gg/sHCB6R8j

**Comment by ourmaninindia** [comment]
Hi Kate,

Don't worry, I deleted my Cloudflare account yesterday.

Regards, Alfred
