### ISSUE TITLE
Max file size limitations are unclear for R2

### ISSUE THREAD

**Issue by mikepianka** [cloudflare/cloudflare-docs#5011]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/get-started/
- https://developers.cloudflare.com/r2/platform/limits/

### Section that requires update

Limits and Getting Started

### What needs to change?

After following the getting started docs it is unclear how to upload large files to the R2 bucket with the worker. Trying to upload through the R2 dashboard GUI, it says to use the API or Wrangler to upload anything larger than 300 MB but that does not seem to be working. Uploading small files worked fine, but when I try to upload a 3 GB .zip file I get the following 413 error:

```
curl https://my-worker.my-project.workers.dev/deploy-20220701.zip -T "./deploy-20220701.zip" --header "X-Custom-Auth-Key: secretkey"
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

Is this some kind of issue with the 100 MB limit for workers? If that is the case, how are you supposed to upload large files since the docs say that R2 can hold files up to 5 GB in size?

### How should it change?

Clarify the process in the docs for uploading large files with the worker example.

**Comment by KianNH** [comment]
> Is this some kind of issue with the 100 MB limit for workers

Not specifically Workers, but yeah. Your *zone* has a request body limit in-line with your plan.

This is documented in the limits page that you linked.

> If you have a Worker, its inbound request size is constrained by [Workers limits](https://developers.cloudflare.com/workers/platform/limits). The max upload size limit does not apply to subrequests.

> If that is the case, how are you supposed to upload large files since the docs say that R2 can hold files up to 5 GB in size? 

Using the S3 API, with SDKs like aws-sdk-js or tools like rclone.

You can see examples of those tools here: https://developers.cloudflare.com/r2/examples/

> up to 5 GB in size

That's per upload - the max object size is ~5TB.

**Comment by mikepianka** [comment]
@KianNH thank you for the explanation, that makes sense
