### ISSUE TITLE
SvelteKit instructions are out of date and produce a broken build

### ISSUE THREAD

**Issue by craigdrayton** [cloudflare/cloudflare-docs#5020]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/#deploying-with-cloudflare-pages

### Section that requires update

deploying-with-cloudflare-pages

### What needs to change?

Following these instructions with the SvelteKit skeleton project deploys a broken app.

I needed to follow these instructions on the SvelteKit cloudflare adapter to deploy successfully: https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare

### How should it change?

Update to match a working configuration (as in https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare)

**Comment by Ekwuno** [comment]
Hi @craigdrayton thanks for opening this issue. This has already been reported #4940 and should be updated in the next few days.

**Comment by Ekwuno** [comment]
In the meantime by using the default `@sveltejs/adapter-auto` you should be able to deploy your SvelteKit app if you update the build configurations to 

```
Framework preset – None
Build command – npm run build or svelte-kit build
Build output directory – .svelte-kit/cloudflare
Environment variables
NODE_VERSION: 16 or 14
```

**Comment by Ekwuno** [comment]
#5081 addresses this, and the guide has been updated.
