### ISSUE TITLE
Enable Early Hints in Custom Hostname

### ISSUE THREAD

**Issue by coleplx** [cloudflare/cloudflare-docs#5079]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/cache/about/early-hints/
https://developers.cloudflare.com/ssl/ssl-for-saas/hostname-specific-behavior/

### Section that requires update

- Enabling Early Hints
- Metadata

### What needs to change?

Include something about being able to enable Early Hints per custom hostname instead of globally (the dashboard option). Today this information is only available in an output example in the API documentation.

### How should it change?

It is possible to enable Early Hints changing the custom hostname metadata, for example:
```
curl -X PATCH "https://api.cloudflare.com/client/v4/zones/xxx_zone_id_xxx/custom_hostnames/xxx_custom_hostname_id_xxxx" \
     -H "X-Auth-Email: xxxxx@xxxx.com" \
     -H "X-Auth-Key: xxxxxxxxxxxxx" \
     -H "Content-Type: application/json" \
     --data '{"ssl":{"method":"http","type":"dv","settings":{"http2":"on","min_tls_version":"1.2","tls_1_3":"on","early_hints":"on"}}}'
```

**Comment by kodster28** [comment]
Now live at https://developers.cloudflare.com/cloudflare-for-saas/related-products/early-hints-for-saas/, thanks for the suggestion @coleplx!
