### ISSUE TITLE
the .head method on an R2Bucket object is being called with two parameters

### ISSUE THREAD

**Issue by cannona** [cloudflare/cloudflare-docs#5105]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/examples/demo-worker/ 

### Section that requires update

The code:

```
const object = await env.MY_BUCKET.head(objectName, {
  onlyIf: request.headers,
})
```

### What needs to change?

both the docs at https://developers.cloudflare.com/r2/runtime-apis/ and the ts definition for the .head method claims that it only accepts a single parameter, but we're passing it two here.

### How should it change?

Remove the second parameter, or update the type definitions and docs to reflect that it can accept an options parameter.

**Comment by KianNH** [comment]
The Demo Worker is incorrect, yeah.

![image](https://user-images.githubusercontent.com/94662631/178473140-55f87ce8-cc65-4031-9bc1-6ed31becf2b8.png)

https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L1009

**Comment by KianNH** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/5121
