### ISSUE TITLE
pelican typo, no framework preset for sphinx

### ISSUE THREAD

**Issue by miron** [cloudflare/cloudflare-docs#5146]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/build-configuration/

### Section that requires update

When selecting the framework preset for pelican, the build command is 

`pelican content`

docs show `pelican $content`.

### What needs to change?

There is also no framework preset for sphinx.

**Comment by WalshyDev** [comment]
Closed by #5193
