### ISSUE TITLE
No connection to internet after WARP is connected

### ISSUE THREAD

**Issue by JFSYL** [cloudflare/cloudflare-docs#5153]
### Example URL(s)

-https://developers.cloudflare.com/warp-client/get-started/linux/

### Actual Behavior

I have followed the step above link. I have run WARP on Ubuntu 22.04 LTS and verified that warp=on. It is connected to WARP but no internet at all. If WARP is disconnected and able to access the internet. 

What Did I Do Wrong? how to fix this problem? Please help me

Thank You

### Expected Behavior

Once WARP is connected, should be able to access the internet.

**Comment by ranbel** [comment]
Hi, thanks for contacting the docs team.  I'm sorry to hear you are having issues with the WARP client. To resolve technical issues, I recommend contacting [Cloudflare Support](https://support.cloudflare.com/hc/en-us/articles/200172476-Contacting-Cloudflare-Support).  Feel free to re-open this issue once you know what needs to change in the documentation.
