### ISSUE TITLE
Wrong S3 policy documentation

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#5175]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://support.cloudflare.com/hc/en-us/articles/360037983412-Configuring-an-Amazon-Web-Services-static-site-to-use-Cloudflare

### Section that requires update

Configure bucket policies to allow Cloudflare IP addresses

### What needs to change?

When you go down the page to the "Configure bucket policies" step, the policy has the line "Effect": "Deny". This instructs S3 to deny all following IPs access to the bucket, but I understand the documentation page to have the policy in place to only allow access from the public Cloudflare IPs.

### How should it change?

So it has to say "Effect": "Allow".

**Comment by etec-masterofsynapse** [comment]
@ranbel I created this issue a while back. When I last checked, the doc has been updated to implement the fix I suggested. Why was this issue never updated and been left stale?

**Comment by haleycode** [comment]
Apologies for the delayed response. Since this has been resolved, I'm closing the issue.
