### ISSUE TITLE
Any plans to make Cloudflare WARP available on Microsoft Store?

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflare-docs#5179]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1, Cloudflare One, WARP Client

### Subject Matter

Cloudflare WARP Client

### Content Location

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/partners/intune/

### Additional information

It would make the installation and updates process a lot easier, rather than having to upload the MSI for each Cloudflare WARP update.

**Comment by KimJ15** [comment]
👋  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com for assistance with your question!
