### ISSUE TITLE
Multiple Cloudflared Access server connections

### ISSUE THREAD

**Issue by bangonkali** [cloudflare/cloudflare-docs#518]
Is there a way to have 1 config file describe multiple server connections under [`cloudflared access`](https://github.com/cloudflare/cloudflare-docs/blob/production/products/access/src/content/protocols-and-connections/arbitrary-tcp.md#2-connect-to-the-resource) maybe by just passing config file similar to the server side?

**Comment by KimJ15** [comment]
👋 @bangonkali  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo (and it doesn't look like this specific question is documented at this time)! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
