### ISSUE TITLE
Update Pages www -> apex tutorial for Bulk Redirects

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#5188]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/www-redirect/

### Section that requires update

The whole tutorial :)

### What needs to change?

We need to change this from using Page Rules -> Bulk Redirects. We have been advising people to use Bulk Redirects for quite a while now but continue to have a tutorial using Page Rules.

Simply need to update this.

**Comment by kodster28** [comment]
Maybe this should be combined with https://developers.cloudflare.com/pages/how-to/use-bulk-redirects/?
