### ISSUE TITLE
Document Dashboard speed test feature

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#5190]
### Which Cloudflare product(s) does this pertain to?

Analytics

### Subject Matter

Speed test isn't documented

### Content Location

Probably to the Dashboard section equivalent called "Speed".

### Additional information

Customers wonder which IP addresses (IPv4 and IPv6) as well as which HTTP User-Agent are used by the speed test feature.
Customers also would like to know if this speed test is part of "Known Bots" in the WAF Rules.

**Comment by marciocloudflare** [comment]
Hey @wolruf. This would be best handled with a Jira ticket on the PCX space. Could you open one? On the other hand, I know the team is working on restructuring this entirely, so this might be on the backlog for a while. Thanks!

**Comment by wolruf** [comment]
Filed PCX-4387
