### ISSUE TITLE
External link on Pages docs is broken

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare/cloudflare-docs#520]
“Pages home”

![image](https://user-images.githubusercontent.com/154613/102575687-bd13f680-40c1-11eb-931e-e6b37cd3c9f8.png)

Opens `pages.dev` which currently shows this:

![image](https://user-images.githubusercontent.com/154613/102575704-c8ffb880-40c1-11eb-8fb8-45bcbf3d5e92.png)

@rita3ko I guess pages.dev isn’t redirecting to http://pages.cloudflare.com

cc @signalnerve

**Comment by kristianfreeman** [comment]
fixed with #529
