### ISSUE TITLE
Getting list of LiveInputs

### ISSUE THREAD

**Issue by TheMrAmazing** [cloudflare/cloudflare-docs#5205]
### Which Cloudflare product does this pertain to?

Stream

### Existing documentation URL(s)

- https://developers.cloudflare.com/stream/stream-live

### Section that requires update

The Stream Live API documentation (the other related requests are in the "Start a live stream" section)

### What needs to change?

I looking for the API request to get a list of LiveInputs, if it exists (I would be surprised if it doesn't), I don't see it described in the API, only requests for PUT, POST and DELETE.

### How should it change?

It should be documented, with an example curl like the other requests, if possible

**Comment by kodster28** [comment]
This has been addressed by https://developers.cloudflare.com/api/operations/stream-live-inputs-list-live-inputs, which is linked to in that docs section.
