### ISSUE TITLE
Clear up use of ingress rules over command line

### ISSUE THREAD

**Issue by helge000** [cloudflare/cloudflare-docs#5208]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/migrate-legacy-tunnels/

### Section that requires update

1.  After configuring DNS/LB records for each zone you want to serve, follow the [Configure a Tunnel](/cloudflare-one/connections/connect-apps/configuration/local-management/configuration-file/) instructions to create a config file with ingress rules. The ingress rules describe how to dispatch requests to your origins based on hostname and path. For example, if you used to run:

    ```bash
    $ cloudflared tunnel --hostname tunnel.example.com --url https://localhost:3000
    ```

    You can have an equivalent ingress rule:

    ```yml
    ingress:
      - hostname: tunnel.example.com
        service: https://localhost:3000
      - service: http_status:404
    # Note that the last rule is the catch-all rule and is required.
    ```

### What needs to change?

The formatting and the wording does not make it clear enough that ingress rules should be used now instead of the command line args. It implies rather that command line args can be used as a replacement.

### How should it change?

1.  After configuring DNS/LB records for each zone you want to serve, follow the [Configure a Tunnel](/cloudflare-one/connections/connect-apps/configuration/local-management/configuration-file/) instructions to *create a config file with ingress rules*. The ingress rules describe how to dispatch requests to your origins based on hostname and path. For example, if in the past you used to run `cloudflared tunnel --hostname tunnel.example.com --url https://localhost:3000`, you need have an equivalent ingress rule now:

    ```yml
    ingress:
      - hostname: tunnel.example.com
        service: https://localhost:3000
      - service: http_status:404
    # Note that the last rule is the catch-all rule and is required.
    ```

### Additional information

https://support.cloudflare.com/hc/de/requests/2492348

**Comment by abelinkinbio** [comment]
Thank you for the feedback. I can understand how this might be confusing. I've opened PR #5393 and we'll get this up as soon as we can. Thanks for the contribution.
