### ISSUE TITLE
Typo in workers/wrangler custom domains docs

### ISSUE THREAD

**Issue by toinbis** [cloudflare/cloudflare-docs#5252]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/e4ffb45a7101a344d616584a1c58ccca20a85e54/content/workers/platform/routing/custom-domains.md?plain=1#L32, I suppose this should be `custom_domains` instead of `custom domain`, i.e. underscore is missing.

### Section that requires update

snippet.

### What needs to change?

Add underscore.

### How should it change?

custom_domains

**Comment by toinbis** [comment]
Ok, it turns out it actually has to be `custom_domain`.   

Also https://github.com/cloudflare/cloudflare-docs/blob/e4ffb45a7101a344d616584a1c58ccca20a85e54/content/workers/platform/routing/custom-domains.md?plain=1#L30 is currently written as `Route =`, whilst I believe it should just be `routes =`.

`routes = [{pattern="subdomain.domain.com", custom_domain=true}]` is what seems to be working for me.

**Comment by KianNH** [comment]
The TOML is also invalid since inline dicts must be opened & closed on the same line.

There's also smart quotes which TOML will reject.

**Comment by KianNH** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/5253
