### ISSUE TITLE
Switch to hard tabs for indentation

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#5260]
### Which Cloudflare product(s) does this pertain to?

All

### Subject Matter

Switch to hard tabs for indentation

### Content Location

`https://developers.cloudflare.com/*`

### Additional information

(I couldn't find a more appropriate issue form type, so apologies if this is not accurate)

Continuing from https://github.com/cloudflare/wrangler2/issues/1298 and https://github.com/cloudflare/templates/pull/76, it would be great to update this repo to also use hard tabs for indentation, both in code examples and any other TS/JS.

With the merge of https://github.com/cloudflare/cloudflare-docs/pull/5013 recently, there wouldn't be any visual change to how code samples are displayed, but when copied out to editors, would include tabs for better default accessibility.

I would very much encourage folks to read through https://github.com/cloudflare/wrangler2/issues/1298 for all of the reasons why switching to hard tabs for indentation on this repo would be a good thing.

Given the complexity and fast moving nature of this repo, I didn't want to simply submit a PR for this myself (since the diff would be massive), but am happy to do so if requested.

**Comment by kodster28** [comment]
Closing this out b/c it's tracked in the other associated issue.
