### ISSUE TITLE
Enabled UDP support missing from Trust

### ISSUE THREAD

**Issue by PirvuCatalin** [cloudflare/cloudflare-docs#5264]
### Example URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/connections/connect-apps/private-net/private-hostnames-ips.md

### Actual Behavior

I'm trying to follow the guide at https://github.com/cloudflare/cloudflare-docs/blob/production/content/cloudflare-one/connections/connect-apps/private-net/private-hostnames-ips.md, but I don't see the setting for enabling UDP support on Settings -> Network -> Firewall as explained above.
This is about https://dash.teams.cloudflare.com/.

### Expected Behavior

I expect to see that option or if this is only shown after I get into this (https://www.cloudflare.com/en-gb/zero-trust/lp/private-dns-waitlist/) , then I should see some info about that.

**Comment by kodster28** [comment]
This is shown once you enable the `Proxy` setting, which is called out in the existing instructions.

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/private-net/private-hostnames-ips#enable-udp-support
