### ISSUE TITLE
My cloudflare

### ISSUE THREAD

**Issue by Greatshopping** [cloudflare/cloudflare-docs#5265]
https://github.com/cloudflare/terraform-provider-cloudflare/commit/1e7da4c6ae8ed70e712e853eaaca6e7f3dc2de14

**Comment by kodster28** [comment]
Howdy @Greatshopping, can you provide more details about your ask?

**Comment by kodster28** [comment]
What page you think we should be changing and why? Linking a PR to our Terraform repo doesn't really give us enough information to make any chance.

**Comment by kodster28** [comment]
Feel free to re-open with more details, but closing as this isn't currently actionable for our team.
