### ISSUE TITLE
custom_hostnames API endpoint is mis-labeled as enterprise only

### ISSUE THREAD

**Issue by colinclerk** [cloudflare/cloudflare-docs#5277]
### Which Cloudflare product does this pertain to?

Cloudflare for SaaS

### Existing documentation URL(s)

The custom_hostname endpoint is listed as enterprise only in the docs:
https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname

However:
1. The api request works without a special entitlement
2. A blog in March indicated it should work without a special entitlement https://blog.cloudflare.com/waf-for-saas/
3. Cloudflare's plans page indicates custom hostnames are available for free, pro, and business plans: https://www.cloudflare.com/plans/#faqs

### Section that requires update

https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname
![Screen Shot 2022-07-25 at 9 35 40 AM](https://user-images.githubusercontent.com/51144033/180829631-e3e5e24a-f6e7-47a5-a33f-bb98067924ff.png)

### What needs to change?

Free, Pro, Business have Xs

### How should it change?

Free, Pro, Business should have checkmarks

**Comment by kodster28** [comment]
This has been addressed and the api docs are updated.

Sorry about the delay!
