### ISSUE TITLE
Include Documentation for Updating Video Titles

### ISSUE THREAD

**Issue by HBBrenum** [cloudflare/cloudflare-docs#5279]
### Which Cloudflare product(s) does this pertain to?

Stream

### Subject Matter

Updating Video Title

### Content Location

https://developers.cloudflare.com/stream/
https://api.cloudflare.com/#stream-videos-video-details

### Additional information

This feature is mentioned in [this thread](https://community.cloudflare.com/t/adding-metadata-to-videos-after-theyre-uploaded/362846/2) but not actually documented, and the suggestion calls out both `POST` and `PATCH` methods, though only `POST` worked when I tested.

Ideally, there would be an example curl request, such as 
```bash
curl \
-X POST \
-d '{"meta":{"name":"Updated Video Name"}}' \
-H "Authorization: Bearer $TOKEN" \
https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/stream/$VIDEOID
```
similar to the sections on updating creator ID and pulling/adding captions, maybe paired with the information for getting video details as documented in the [API documentation](https://api.cloudflare.com/#stream-videos-video-details).

**Comment by dcpena** [comment]
Hi @HBBrenum, this was updated in the docs in [PR 8930](https://github.com/cloudflare/cloudflare-docs/pull/8930). Thanks for filing the issue!
