### ISSUE TITLE
Pages custom domains if already using Cloudflare DNS

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#5294]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/custom-domains/

### Section that requires update

https://developers.cloudflare.com/pages/platform/custom-domains/#configure-nameservers

### What needs to change?

This may actually just be product feedback, but the current experience in the dash (and the options listed in the docs) are incomplete.

You could already have a domain using Cloudflare DNS **that does not need** to go through the add site flow. But if you select to "use Cloudflare DNS" w/in the dash, then it defaults you to that flow.

I believe the correct procedure would be to add the domain and choose **My DNS provider** and then manually add the CNAME DNS record you need, but even that's kinda unclear.

### How should it change?

Described above.

**Comment by marciocloudflare** [comment]
I think this ties with that ticket I created the other day @deadlypants1973 pertaining to this page https://developers.cloudflare.com/pages/how-to/custom-branch-aliases/. Also, I didn't know we had 2 places were we talk about custom domains. This might be something we need to address. If these two completely different situations, maybe link to the other page, so customers aware of them?
