### ISSUE TITLE
Custom builds document is mostly empty

### ISSUE THREAD

**Issue by jed** [cloudflare/cloudflare-docs#5324]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/custom-builds/

### Actual Behavior

Document `suggests some strategies for creating custom build commands`.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/4433/181400256-0ed8bfca-ca9b-4504-96d4-fb0381925a29.png">

### Expected Behavior

Document is mostly empty.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/4433/181400256-0ed8bfca-ca9b-4504-96d4-fb0381925a29.png">

**Comment by deadlypants1973** [comment]
Thanks for pointing this out! We have an internal ticket open for this, and it's in progress :)
