### ISSUE TITLE
[Design] Lowercase or uppercase D on docs?

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/cloudflare-docs#5355]
### Example URL(s)

- Any URL on the entire docs site (it's the header in question).

### Actual Behavior

First, loving the new site redesign! 😄 

Now, for the question:
- Currently, the header contains the words `Cloudflare docs` (two `span`s). Notice the lowercase `d` on docs.

### Expected Behavior

- This Issue is to discuss whether `docs` or `Docs` would look better (and conform to style guide, etc).
- Personally, I prefer `Docs` over `docs` just because things that aren't capitalized look wrong to me.
- But this is likely a matter of conforming to a style guide, or personal preference.
- If `docs` is preferred, nothing needs to happen. But if `Docs` is preferred, I (or someone else) can create a PR to change?

**Comment by kodster28** [comment]
Thoughts on this, @KimJ15?

It's a pretty easy change when you know [where to look](https://github.com/cloudflare/cloudflare-docs/blob/production/layouts/partials/logo.html#L9).

**Comment by kodster28** [comment]
Moving to uppercase
