### ISSUE TITLE
Delete Deploy older than a week seems confusing since we may worry it'll delete last build too

### ISSUE THREAD

**Issue by WebLeach** [cloudflare/cloudflare-docs#5372]
### Which Cloudflare product does this pertain to?

API

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/platform/api.md

### Section that requires update

Deleting old deployments after a week

### What needs to change?

In the explanation and the code, it doesn't guarantee that the last deployment will be preserved or deleted. For example if i don't deploy anything over a week, but the api still runs, is it possible to delete my latest build and turn the site into a 404 page?

### How should it change?

Update the js code and make sure (guarantee) at least the last build (deploy) is preserved.

### Additional information

You guys know what to do, I'm a simple man.

**Comment by KianNH** [comment]
The latest deployment for a branch can't be deleted as it is "active" for that branch alias.

**Comment by WebLeach** [comment]
Kindly mention that highlighted on the page 😅 and the issue is closed for good
