### ISSUE TITLE
Cloudflared integrated DoH Proxy configuration file options

### ISSUE THREAD

**Issue by jjpinom** [cloudflare/cloudflare-docs#5375]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1, Argo Smart Routing, Cloudflare One

### Subject Matter

Cloudflared DoH Proxy configuration keys and values

### Content Location

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/local-management/configuration-file/

### Additional information

I can't find any information on the developers regarding cloudflared daemon DoH configuration keys and flags .

I found two external sites explaining some details, but we need a formal cloudflared documentation section.

Some examples:

https://docs.pi-hole.net/guides/dns/cloudflared/
https://wiki.archlinux.org/title/Cloudflared

I'm using a Cloudflared tunnel for my OpenWRT Router and also with the DoH proxy. I would like to have a complete formal documentation on all keys and flags for Cloudflared daemon

**Comment by jjpinom** [comment]
I made a configuration file with a Tunnel AND a DoH proxy. This use case is not detailed on any cloudflared daemon document 

Example:

tunnel: <my tunnel id>
credentials-file: /root/.cloudflared/<my tunnel id>.json

ingress:
  - hostname: <my hostname>
    service: http://localhost:80
  - service: http_status:404

proxy-dns: true
proxy-dns-upstream:
 - <my DoH URL>
proxy-dns-port: 5300
proxy-dns-address: 0.0.0.0

**Comment by ranbel** [comment]
Hi, thanks for the feedback. We have some setup instructions here: https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/dns-over-https-client/
To see the configuration flags, you can run `cloudflared proxy-dns -help` in the terminal.
