### ISSUE TITLE
Captchas across docs site - possible to remove/reduce?

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#5394]
### Example URL(s)

https://developers.cloudflare.com/ (and every subpath)

### Actual Behavior

When hitting the docs site via any kind of automated client like `curl`, or even sometimes within a normal browser, you'll receive a managed captcha page. This notably breaks a lot of embeds for the docs in services that unfurl them, most notably in the forum such as here:

https://community.cloudflare.com/t/i-want-to-set-up-an-email-on-cloudflare/405984/2?u=cherryjimbo

Given that most of the docs site is static, are the captchas truly necessary?

### Expected Behavior

No captchas across the docs site except maybe on the `/search/*` endpoint.

**Comment by WalshyDev** [comment]
Can confirm I've been hit by a captcha in my browser. Chrome 103.0.5060.134, macOS 12.4

**Comment by kodster28** [comment]
That's something I'll need to discuss with some others about. We do have bot protection set up at relatively permissive thresholds (BS < 16) to trigger managed challenges... but, to your point, not sure how totally necessary that is (besides the search endpoint).

I'll do some digging internally to see whether our SE/CSMs have recommendations based on their experiences with other clients.

(funny side note about the /search endpoint... we actually get the majority of bad traffic as carryover from Cloudflare Challenge/5xx pages. Tons of actual end users who were searching for something else (porn, gambling, illegal movies, etc.) who then flood the search with whatever they were looking for previously)

**Comment by kodster28** [comment]
Quick update on this:

- Got the Bots team to upgrade us to the latest M/L model so theoretically should be better about labelling human vs bot traffic
- Broadened the Challenge Passage period to a month so -- if we do captcha someone -- it's less of a common thing
- Slightly lowered our threshold to BS < 10 based on bot analytics


That should help with the current setup... but I guess a broader question for @WalshyDev... if we're hosted on Pages, is there a risk of our site going down from automated traffic? Or is that not something we really need to worry about?

Don't know enough about the architecture to really make the decision whether we're okay or not to turn off bot protection, if that makes sense.

**Comment by WalshyDev** [comment]
> if we're hosted on Pages, is there a risk of our site going down from automated traffic? Or is that not something we really need to worry about?

I wouldn't worry at all no, I've tried to DDoS my own Pages site and even with like 6k requests per second it didn't even respond slower nevermind go down. CF's DDoS protection sadly stopped me hitting it harder

Workers can scale very, very well.

**Comment by kodster28** [comment]
Alright, I'll keep the FW rule logic just in case... but switch those rules off being active.
