### ISSUE TITLE
Link to List Access Rules API is invalid

### ISSUE THREAD

**Issue by kooba** [cloudflare/cloudflare-docs#5414]
### Which Cloudflare product does this pertain to?

WAF

### Existing documentation URL(s)

https://developers.cloudflare.com/waf/tools/ip-access-rules/create/

### Section that requires update

Using the API
Use the Cloudflare API to programmatically create IP Access rules. For more information, refer to List Access Rules.

### What needs to change?

Link under "List Access Rules"

### How should it change?

The link currently is pointing to non existent section of our API docs:
https://api.cloudflare.com/#firewall-access-rule-for-a-zone-list-access-rules
I think the most appropriate link should be:
https://api.cloudflare.com/#ip-access-rules-for-a-zone-get-ip-access-rules

**Comment by pedrosousa** [comment]
Thank you for reporting it, @kooba! The fix should be live in a couple of minutes.
