### ISSUE TITLE
R2Object.httpEtag contains W/, but R2Bucket.get throws TypeError when etag has W/

### ISSUE THREAD

**Issue by yonran** [cloudflare/cloudflare-docs#5469]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

https://developers.cloudflare.com/r2/examples/demo-worker/
https://developers.cloudflare.com/r2/runtime-apis/#conditional-operations

### Section that requires update

Either the demo needs to be updated, or the `R2Object.get({…, onlyIf: Headers})` API needs to be fixed or clarified.

### What needs to change?

[`R2Object`](https://developers.cloudflare.com/r2/runtime-apis/#r2object-definition).`httpEtag` returns a [weak validator](https://www.rfc-editor.org/rfc/rfc7232#section-2.1) prefixed with `W/`, but [`R2Object`](https://developers.cloudflare.com/r2/runtime-apis/#r2object-definition).`get` does not support reading this header value.

### How should it change?

R2Object.get should clarify whether it supports `onlyIf` `Headers` from the request.

### Additional information

When I tried the R2 worker demo and refreshed the page in the browser, it alternated between a success page an an error page:

<img width="764" alt="Screen Shot 2022-08-08 at 5 12 37 PM" src="https://user-images.githubusercontent.com/483060/183536707-b9942088-44cc-4101-92ed-063ffd666e83.png">

When I enabled the Real-time Logs, I observed that the call to `MY_BUCKET.get({…, onlyIf: request.headers})` threw a `TypeError`: “ETag in HTTP header needs to be wrapped in quotes W/"52af2bc97aef22023c97c7874b569d0d").”

<img width="821" alt="Screen Shot 2022-08-08 at 5 23 31 PM" src="https://user-images.githubusercontent.com/483060/183536884-e0f8c095-2b35-49f3-96d3-48ea4f966505.png">

The source of the worker module ([live](https://developers.cloudflare.com/r2/examples/demo-worker/), [github](https://github.com/cloudflare/cloudflare-docs/blob/05ef5947a9109f4c4979f022068833ec72d16205/content/r2/examples/demo-worker.md)) contains the following for handling GET requests to R2:

```
        const object = await env.MY_BUCKET.get(objectName, {
          range,
          onlyIf: request.headers,
        })
        …
        headers.set('etag', object.httpEtag)
```

If it matters, I used the S3 API to upload the object along with the etag.

**Comment by vlovich** [comment]
[R2Object](https://developers.cloudflare.com/r2/runtime-apis/#r2object-definition).httpEtag definitely never returns a weak ETag. Any weakening is going to come from Nginx applying decompression automatically based on the request from the client.

That being said, it is accurate that `R2Object.get` needs to be accepting of weak etags. We have it in our backlog of tasks.

**Comment by vlovich** [comment]
I think we can close the docs issue - this isn't a docs thing but a Workers runtime bug.
