### ISSUE TITLE
Copy btn in code snippets will copy the `$` sign at the beginning of a command line

### ISSUE THREAD

**Issue by CarmenPopoviciu** [cloudflare/cloudflare-docs#5474]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/get-started/
https://developers.cloudflare.com/workers/wrangler/commands/

### Actual Behavior

Copying code snippets such as 
<img width="732" alt="Screenshot 2022-08-09 at 13 42 29" src="https://user-images.githubusercontent.com/4638332/183641043-e214ceb7-52f5-44c6-8eab-f585a5723e7e.png">
will paste the command *including* the `$` at the beginning of the command line. If pasted in the terminal, users will have to first remove that character in order to run the command

### Expected Behavior

It would be nice if the `$` sign is trimmed, so that users can run the copied command directly in the terminal

**Comment by Ekwuno** [comment]
Thanks for opening this. I am currently improving on this feature here. #5467 I will address this issue here as well
