### ISSUE TITLE
Clarify required IPv6-only setting

### ISSUE THREAD

**Issue by Manouchehri** [cloudflare/cloudflare-docs#5478]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/
- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/hosting-requirements/

### Section that requires update

The tunnel creation process doesn't clarify how to run cloudflared in an IPv6-only setting. (This does work fine in my testing.)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/remote-management/

### What needs to change?

The "Install and run a connector" page doesn't warn you about being IPv4-only (because ` --edge-ip-version 4` is the default).

### How should it change?

Explaining that ` --edge-ip-version 6` must manually be added to the systemd service file.

**Comment by ranbel** [comment]
Thanks for the feedback! We are currently testing a default `auto` setting, which will make it so that users do not need to adjust the flag at all. In the meantime, we have added your note about defaulting to IPv4: #5569

**Comment by Manouchehri** [comment]
Thanks! Connecting over both IPv4 and IPv6 might be a good idea too, though that should probably be a separate ticket.
