### ISSUE TITLE
Keywork framework guide

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#5512]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Keywork framework

### Content Location

https://developers.cloudflare.com/pages/framework-guides/

### Additional information

https://keywork.app/modules/assets/cloudflare/pages/

We're working on adding framework to the dropdown list of presets in the dashboard.

**Comment by KimJ15** [comment]
Folks - I'm going to close out this issue given we have a draft PR with more details. https://github.com/cloudflare/cloudflare-docs/pull/8739

**Comment by kodster28** [comment]
Going to close this out as it's sat for quite a while w/o any activity.
(also, don't see in the list of pre-populated dropdowns)

Feel free to re-raise if this gets prioritized!
