### ISSUE TITLE
Missmatch: wrangler kv:key put with --path

### ISSUE THREAD

**Issue by POD666** [cloudflare/cloudflare-docs#5541]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/commands/#put

### Section that requires update

Reading from files using `--path` doesn't work as described.

### What needs to change?

Docs describe following usage:
```
$ wrangler kv:key put --binding=SECRETS my_secret --path=secret.txt
error: The following required arguments were not provided:
    <value>

USAGE:
    wrangler kv:key put <key> <value> --config <config> --path <--binding <binding>|--namespace-id <namespace-id>>

For more information try --help
```

### How should it change?

I was able to make it work using following:
```
$ wrangler kv:key put --binding=SECRETS my_secret secret.txt --path                                                     
✨  Success
```

### Additional information

Since there is a way to secretly set some values in KV, would be also nice to highlight encryption or any other related security features. Maybe It was already described elsewhere, so just a link.

**Comment by POD666** [comment]
```
$ wrangler --version
wrangler 1.19.12
```

**Comment by KianNH** [comment]
> $ wrangler --version
> wrangler 1.19.12

The documentation is for version 2 of wrangler - https://github.com/cloudflare/wrangler2

I don't believe version 1 will be receiving any future updates, so I would recommend switching over.

```
wrangler kv:key put <key> [value]

Writes a single key/value pair to the given namespace.

Positionals:
  key    The key to write to  [string] [required]
  value  The value to write  [string]

Flags:
  -c, --config   Path to .toml configuration file  [string]
  -h, --help     Show help  [boolean]
  -v, --version  Show version number  [boolean]

Options:
      --binding       The binding of the namespace to write to  [string]
      --namespace-id  The id of the namespace to write to  [string]
  -e, --env           Perform on a specific environment  [string]
      --preview       Interact with a preview namespace  [boolean]
      --ttl           Time for which the entries should be visible  [number]
      --expiration    Time since the UNIX epoch after which the entry expires  [number]
      --metadata      Arbitrary JSON that is associated with a key  [string]
      --path          Read value from the file at a given path  [string]
```

> would be also nice to highlight encryption or any other related security features.

This is in [How KV works](https://developers.cloudflare.com/workers/learning/how-kv-works/)

> All values are encrypted at rest with 256-bit AES-GCM, and only decrypted by the process executing your Worker scripts or responding to your API requests.
