### ISSUE TITLE
Clarify vague enterprise roles

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#5563]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/account-and-billing/account-setup/account-roles/

### Section that requires update

The enterprise roles section doesn't contain all available roles and it seems to be missing information related to R2 and D1. 
When adding a user with the `Trust And Safety` role, they can create new buckets, but they can't see other buckets that an administrator has created. 

These are the roles in our Enterprise Dashboard.
![image](https://user-images.githubusercontent.com/36166470/185392000-eb797605-4f29-43c5-8abc-14e972a7c6c8.png)

### What needs to change?

Clarify roles and which products those roles specifically enable. 
Clarify what the Trust And Safety role actually does (what are blocks viewed and requested)

### How should it change?

Each role should indicate specific portions of the Cloudflare Dashboard and API that will become accessible.
The current descriptions are somewhat vague and don't provide enough detail from security and role management perspectives. 

With regard to D1 and R2, roles that enable these products should also be able to limit read/write access to buckets/databases.

**Comment by kodster28** [comment]
(apologies on the lengthy delay here)

Howdy @joberthar, definitely hear that frustration, but that request isn’t something we can commit to maintaining in our documentation at this current point in time. 

It's something we've raised with the product team for internal discussions (to see if there's another way to provide this information that's more maintainable -- likely w/in the context of the dashboard itself).
