### ISSUE TITLE
Modify Amazon ASN from 7224 to 16509

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#5565]
### Which Cloudflare product does this pertain to?

Firewall

### Existing documentation URL(s)

https://developers.cloudflare.com/firewall/known-issues-and-faq/

### Section that requires update

"Block Amazon Web Services (AWS) and Google Cloud Platform (GCP) because of large volumes of undesired traffic"

### What needs to change?

The Amazon ASN value of 7224 should be changed to 16509 as this is, as far as I can see in their peering policy, the value to be used: https://aws.amazon.com/peering/policy/

7224 is used with AWS Direct Connect or VPN but public traffic, as far as I know, will use 16509.

### How should it change?

modify the value from 7224 to 16509

**Comment by pedrosousa** [comment]
Thank you for reporting this issue, @wolruf! The fix should be live a in couple of minutes.
