### ISSUE TITLE
Email for the distribution list returns error

### ISSUE THREAD

**Issue by hanskuhn** [cloudflare/cloudflare-docs#5580]
### Which Cloudflare product does this pertain to?

Time Services

### Existing documentation URL(s)

- https://developers.cloudflare.com/time-services/nts/

### Section that requires update

Section: Next steps

> If you would like to hear about the development of additional clients or updates on our service or would like to announce that your client supports NTS, email time-services@cloudflare.com to be added to our distribution list.

### What needs to change?

When I email time-services@cloudflare.com I get the following reply:

> Hello xx@xx,
> 
> We're writing to let you know that the group you tried to contact (time-services) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/cloudflare.com/bin/topic.py?topic=25838.
> 
> Thanks,
> 
> cloudflare.com admins

The documentation should likely be changed to reflect that this group doesn't exist or there's a different procedure to subscribe to the distribution list.

### How should it change?

The documentation should be updated with the correct procedure to subscribe to the distribution list.

**Comment by kodster28** [comment]
Howdy @hanskuhn, should work if you email to `time-services+subscribe@cloudflare.com`.
