### ISSUE TITLE
The documentation on how to deploy the Cloudflare demon not loading 

### ISSUE THREAD

**Issue by Blitz-Cloud** [cloudflare/cloudflare-docs#5596]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/docker/

### Actual Behavior

The web site is loading but it empty, there is no documentation on how to deploy it on a docker container 
![SharedScreenshot](https://user-images.githubusercontent.com/81566145/185988145-791373a8-aaab-45e2-a156-42a68c57bf85.jpg)

### Expected Behavior

I was expecting to get a full guide on how to deploy the cloudflare demon on a docker container

**Comment by ranbel** [comment]
Hi, thanks for the feedback! The Docker guide is under development and will be published soon. In the meantime, we have removed the blank page from the directory listing.

@amcconnellcloud @abelinkinbio
