### ISSUE TITLE
Broken URLs on stream docs

### ISSUE THREAD

**Issue by amaitu** [cloudflare/cloudflare-docs#5605]
### Example URL(s)

https://developers.cloudflare.com/stream/viewing-videos/

### Actual Behavior

Link to [Display thumbnails](https://developers.cloudflare.com/stream/viewing-videos/displaying-thumbnails/) is broken, both on the index for viewing videos, and in the sidebar.

### Expected Behavior

Link to [Display thumbnails](https://developers.cloudflare.com/stream/viewing-videos/displaying-thumbnails/) should resolve or redirect.

**Comment by kodster28** [comment]
Hey @dcpena, I think the issue is at https://github.com/cloudflare/cloudflare-docs/blob/production/content/_redirects#L562

**Comment by kodster28** [comment]
Looks like it's still broken. Maybe there's another redirect causing the issue?
