### ISSUE TITLE
Add info to Custom builds page

### ISSUE THREAD

**Issue by zachtil** [cloudflare/cloudflare-docs#5621]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

The docs page at https://developers.cloudflare.com/workers/wrangler/custom-builds/ seems incomplete.
A sentence there suggests that the page should provide a number of strategies but they seem to be missing.

### Section that requires update

There is only one section on the page.

### What needs to change?

This sentence "This document suggests some strategies for creating custom build commands and systems together with wrangler dev and wrangler publish." suggests that the page also contains strategies for using custom build commands and systems but these seem to be missing.

### How should it change?

Update the page to include the suggested strategies.

**Comment by deadlypants1973** [comment]
Thanks for flagging this. This page is in progress, so I am closing this for now as we are aware of the issue and tracking it on another ticket.

**Comment by deadlypants1973** [comment]
#6813
