### ISSUE TITLE
Infinite redirect issue on CF ZT page

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#5627]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/cors/

### Actual Behavior

Infinite redirect even though there's content on that CORS page

### Expected Behavior

Not an infinite redirect

**Comment by pedrosousa** [comment]
This line seems to be the cause:

https://github.com/cloudflare/cloudflare-docs/blob/30de88293baafd5389e89d12f4a40f599285b8c0/content/_redirects#L1055

**Comment by ranbel** [comment]
Thanks Pedro, must have been a copy/paste error. https://github.com/cloudflare/cloudflare-docs/pull/5628
