### ISSUE TITLE
Add details about disk encryption checks for Linux platform

### ISSUE THREAD

**Issue by billgatesfan** [cloudflare/cloudflare-docs#5632]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/devices/warp-client-checks/disk-encryption/

### Section that requires update

Hi, 
Could you please simply confirm, that only LUKS-encrypted volumes can be verified by the WARP client on Linux platform, or are there any other disk encryption solutions, that are supported?

For Windows and MacOS, you provided the commands to ensure encrytpion is active, but not for Linux ;-).

Thx!!

### What needs to change?

The section "How WARP checks for encryption" might be incomplete.

### How should it change?

Provide the command line that the WARP client is using on Linux platform, to verify disk encryption is active.

**Comment by ranbel** [comment]
Hi, unfortunately disk encryption checks for Linux are not supported at this time: https://github.com/cloudflare/cloudflare-docs/pull/5909
