### ISSUE TITLE
Update/Add alternate instructions for adding Cloudflare_CA.pem to OpenSSL CA Store

### ISSUE THREAD

**Issue by sam-heller** [cloudflare/cloudflare-docs#5636]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert/#base-operating-system

### Section that requires update

Same as above
<img width="786" alt="Screen Shot 2022-08-25 at 5 04 13 AM" src="https://user-images.githubusercontent.com/410320/186625180-1378b484-90fa-4b45-b0fb-e3794d46a156.png">

### What needs to change?

I'm guessing it's a MacOS Version, but on Monterey (12.5.1) the CA store is located at `/etc/ssl/cert.pem` not `/usr/local/etc/openssl/cert.pem` so the instructions as written didn't work for me

### How should it change?

I had to temporarily update the write permissions for the file to use the supplied command for updating it in the old location, altogether it looked like 

```bash
sudo chmod 666 /etc/ssl/cert.pem
sudo cat Cloudflare_CA.pem >> /etc/ssl/cert.pem
sudo chmod 644 /etc/ssl/cert.pem
```
I'm sure there's a slicker way to accomplish that, but that's what worked for me

### Additional information

There wasn't a "Zero Trust" option for the Cloudflare product dropdown so I went with the Warp client since that's what was nonfunctional on my end.

**Comment by ranbel** [comment]
Thanks for flagging the issue!
