### ISSUE TITLE
Add warp-cloudfare remove instructions for Linux

### ISSUE THREAD

**Issue by tanmay1024** [cloudflare/cloudflare-docs#5637]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

Linux commands for removing warp-cloudfare

### Content Location

[call-out within:
content/cloudflare-one/connections/connect-devices/warp/remove-warp.md](https://github.com/cloudflare/cloudflare-docs/blob/67ca32d78098433706daa2ad99b1b278dd56fea0/content/cloudflare-one/connections/connect-devices/warp/remove-warp.md)

**Comment by ranbel** [comment]
#7633
