### ISSUE TITLE
[CISkip] flag not stopping automatic build

### ISSUE THREAD

**Issue by RonStrauss** [cloudflare/cloudflare-docs#5638]
### Example URL(s)

https://developers.cloudflare.com/pages/platform/branch-build-controls/#skip-builds

### Actual Behavior

After pushing a commit with `[CISkip]` prefixed to the commit message, build wasn't automatically skipped.

### Expected Behavior

Expected to skip the build. `[CI-Skip]` worked, however.

### Additional information

![Screenshot 2022-08-25 180658](https://user-images.githubusercontent.com/82303541/186701820-9182dfbe-0613-4388-a196-fccd0343d41d.png)

**Comment by WalshyDev** [comment]
There should be a space there, `[CI Skip]`

This is an issue with the docs so keeping this open to track that
