### ISSUE TITLE
[workers] Move info on managing secrets for local environment to environment variables page

### ISSUE THREAD

**Issue by sam-heller** [cloudflare/cloudflare-docs#5639]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

Page needing update : https://developers.cloudflare.com/workers/platform/environment-variables/
Page with existing info: https://developers.cloudflare.com/workers/wrangler/configuration/#local-environments 

### Section that requires update

The [Environment Variables](https://developers.cloudflare.com/workers/platform/environment-variables/) page should be updated.

### What needs to change?

The  [Environment Variables](https://developers.cloudflare.com/workers/platform/environment-variables/) page is where the meat of the documentation about managing Secrets exists lives, but there is no mention of how to properly use them on a local development build ( `wrangler dev --local`). 

Instead that information is on the [Wrangler Configuration](https://developers.cloudflare.com/workers/wrangler/configuration/#local-environments) page, where it's the only explicit reference to secrets. 

That information should be moved to (or at least referenced by) the Environment Variables page.

### How should it change?

I'd personally vote for just picking up the entire local-environments section from the Wrangler Configuration page and adding it to the end of the Environment Variables page, but at the very least there should be some sort of clear callout that secrets do not function on a local environment, along with a link to the documentation on how to handle that situation.

**Comment by cupcakearmy** [comment]
Yes, this is much needed, head to search quite a bit for a solution. The PR looks good, would have saved me 30 minutes of searching :)
