### ISSUE TITLE
Unclear cloudflared update instructions for Zero Trust dashboard tunnels

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#5653]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#update-cloudflared

### Section that requires update

Update cloudflared

### What needs to change?

This section instructs users to execute `cloudflared update` to update the currently installed cloudflared instance.
However this doesn't work in two instances:

1. Cloudflared was installed by the package manager of the OS
2. Cloudflared was installed through the instructions in the Zero Trust Dashboard which utilize dpkg to deploy the package

In both cases, executing `cloudflared update` will lead to the error:
```
cloudflared was installed by a package manager. Please update using the same method.
```

When using method 1 with the OS package manager, all is well and you can just run its upgrade mechanism to update cloudflared.
But with method 2, dpkg can't update the cloudflared instance without manually downloading a new package.

### How should it change?

Explain how users of the installation way through the Zero Trust Dashboard can upgrade cloudflared.
One possibility would be to change the commands the Dashboard shows to the users so it adds the needed repository to the OS and installs cloudflared through that.
Afterwards, you could still supply the cloudflared instance the needed service key through a second command to connect to the dashboard for zero-touch provisioning.

**Comment by ranbel** [comment]
(From @abelinkinbio)
If cloudflared was installed via the dashboard, the customer can simply re-run the install script from the dashboard to update cloudflared.

**Comment by etec-masterofsynapse** [comment]
> (From @abelinkinbio) If cloudflared was installed via the dashboard, the customer can simply re-run the install script from the dashboard to update cloudflared.

Yes, that is correct, but the reason I opened the issue still stands, the docs are unclear. In addition, why would I rerun the commands provided by the dashboard instead of using the native package manager?


Also, there is no reason to not add the cloudflared repo for easy updates, so why not change the commands in the dashboard and change the docs accordingly?
Nothing is gained by doing the install via dpkg instead of using the package manager.

**Comment by obezuk** [comment]
Hi @etec-masterofsynapse - Thanks for providing this feedback and we agree that the package manager is easier to configure and manage. We're working towards to migrating all dashboard and developer instructions to use the package manager for install/update tasks.

**Comment by etec-masterofsynapse** [comment]
Hi @obezuk , Thanks for that info, I am excited for the changes. Let me know if I should assist in beta testing anything.

**Comment by R0yk3** [comment]
> (From @abelinkinbio) If cloudflared was installed via the dashboard, the customer can simply re-run the install script from the dashboard to update cloudflared.

This does not work. 
I f rerun the command i get this error

Preparing to unpack cloudflared.deb ...
Unpacking cloudflared (2023.5.1) over (2023.5.1) ...
Setting up cloudflared (2023.5.1) ...
2023-06-01T10:00:52Z INF Using Systemd
2023-06-01T10:00:52Z ERR error generating service template error="cloudflared service is already installed at /etc/systemd/system/cloudflared.service; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command"

you should not copy the whole, but leave the setup of the connector out 

curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 

sudo dpkg -i cloudflared.deb && 

STOP HERE WITH COPY

sudo cloudflared service install 
MysecretKEY###########

This way it gets updated without errors.

**Comment by etec-masterofsynapse** [comment]
> > (From @abelinkinbio) If cloudflared was installed via the dashboard, the customer can simply re-run the install script from the dashboard to update cloudflared.
> 
> This does not work. I f rerun the command i get this error
> 
> Preparing to unpack cloudflared.deb ... Unpacking cloudflared (2023.5.1) over (2023.5.1) ... Setting up cloudflared (2023.5.1) ... 2023-06-01T10:00:52Z INF Using Systemd 2023-06-01T10:00:52Z ERR error generating service template error="cloudflared service is already installed at /etc/systemd/system/cloudflared.service; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command"
> 
> you should not copy the whole, but leave the setup of the connector out
> 
> curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb &&
> 
> sudo dpkg -i cloudflared.deb &&
> 
> STOP HERE WITH COPY
> 
> sudo cloudflared service install MysecretKEY###########
> 
> This way it gets updated without errors.

Thanks for that input.
The info you discovered is also one of the reasons I pushed them towards changing the commands to work with the OS package manager, which they will now do.

**Comment by CaixaNegraPT** [comment]
The solution I used was to add the Cloudflare repo using the instructions located here:

https://pkg.cloudflare.com/index.html

**Comment by ranbel** [comment]
Here are the current update instructions for dashboard tunnels: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/update-cloudflared/

**Comment by etec-masterofsynapse** [comment]
> Here are the current update instructions for dashboard tunnels: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/update-cloudflared/

@ranbel Thanks for that, however, I do not understand why you closed this issue already?


> Hi @etec-masterofsynapse - Thanks for providing this feedback and we agree that the package manager is easier to configure and manage. We're working towards to migrating all dashboard and developer instructions to use the package manager for install/update tasks.

@obezuk told me that you want to transition to only using the package manager way.
And both the developer docs as well as the dashboard still show the old way via .deb today, with almost no mention of the package manager way.
That means there is still work to do, and so this issue isn't to be closed as completed.
