### ISSUE TITLE
Activating "Enable Binding Cookie" on an SSH application in Cloudflare Access causes "websocket: bad handshake" while accessing through cloudflared proxy

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#5654]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/tutorials/ssh/

### Section that requires update

Section doesn't exist yet

### What needs to change?

The mentioned page doesn't have any information about the error "websocket: bad handshake" that activating "Enable Binding Cookie" within an CF Access SSH application causes.
Additionally, this setting isn't explained clearly anywhere so we can't understand the implications of having it active or deactivating it for make "cloudflared access ssh" work.

### How should it change?

First, add a section to the mentioned page explaining that this option has to be disabled or else "cloudflared access ssh" won't work.
Second, document this option, its improvements and repercussions fully within the docs.

**Comment by ranbel** [comment]
Hello, you can find more information about the Binding Cookie setting on this page: https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/#cookie-settings

**Comment by etec-masterofsynapse** [comment]
Thanks for the information.
But I don't see this issue as completed however since I also suggested having a prominent info block within the SSH & RDP setup guides so the users now this limitation exists.

**Comment by ranbel** [comment]
Correct me if I'm wrong, but I believe the "Enable binding cookie" setting is disabled by default. I will bring this to the attention of the UI team so that we can call out this limitation next to the toggle.

**Comment by etec-masterofsynapse** [comment]
It is, however I believe many people would enable this setting since it increases the security of the application, without knowing this specific limitation.
