### ISSUE TITLE
No instructions on how to configure Windows OpenSSH to work with short-lived certificates

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#5655]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates#configure-your-client-ssh-config

### Section that requires update

Configure your client SSH config

### What needs to change?

The section mentioned only provides the commands and file contents of the .ssh/config file for *NIX systems.
Windows usually doesn't have bash and even if an Ubuntu instance is present through WSL, it doesn't have cloudflared installed since the MSI installs to the Windows system, not the WSL.

### How should it change?

Provide Windows instructions on how to implement short-lived certificates in Windows OpenSSH.

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request for Cloudflare Tunnels. Feel free to open an feature request with that team at https://github.com/cloudflare/cloudflared/issues.

**Comment by etec-masterofsynapse** [comment]
Hi @KimJ15 , please explain to me how this is a feature request?
The functionality of using the short-lived certs in Linux is documented, for Windows, it isn't.
Did you check with your colleagues if the function is there to know to redirect me to a FR on CF Tunnels?
