### ISSUE TITLE
CF Access Bookmarks only work with Application URLs starting with https://

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#5665]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/applications/bookmarks/

### Section that requires update

Enter your Application URL, for example https://mybookmark.com.

### What needs to change?

When I tested the Bookmark feature with an Application URL starting with http:// , my browser hyperlinked the tile in the launcher to https://http , which obviously doesn't work.

### How should it change?

Either state clearly in the Docs and in the UI for adding a bookmark, that only https is supported or correct the behavior that causes this error.

**Comment by ranbel** [comment]
@kennyj42 Do bookmarks only support `https` URLs?

**Comment by kennyj42** [comment]
Yes, only https at the moment

**Comment by kennyj42** [comment]
This is a bug. The team is investigating and will get a fix out.

**Comment by Justin-Holmes** [comment]
Hi @etec-masterofsynapse, we rolled out a fix for the issue above and it should be resolved now!

**Comment by etec-masterofsynapse** [comment]
Hi @Justin-Holmes , I can confirm that, I just retested with a fresh bookmark and the full http:// URL is now the correct a href target. Thanks for the quick fix ;)

**Comment by etec-masterofsynapse** [comment]
Did that change break something else?
I tested what happens when I change the application URL from http:// to https://, and also the other way round.
The conclusion is, that when I change it to https://, the a href stays at http://.
And when I change it from https:// to http://, the a href stays at https://.

Should that be the behavior?

**Comment by Justin-Holmes** [comment]
The `href` should change if you update the application's URL. It's possible app launcher took a bit to reflect the new changes or you ran into a caching issue -- but the href should eventually reflect the correct URL!
