### ISSUE TITLE
[Workers] Copying KV code examples no longer possible

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/cloudflare-docs#5690]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/workers-kv/#create-a-kv-namespace-with-wrangler

### Actual Behavior

Attempting to copy code highlights the line underneath: 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/3822106/187481303-22d552ca-5cfc-4059-ab19-8d2510d05520.png">

### Expected Behavior

It should be possible to copy code directly from the code example

**Comment by pedrosousa** [comment]
Thank you for reporting this issue, @rozenmd. The fix should be live in a couple of minutes.

**Comment by rozenmd** [comment]
Cheers @pedrosousa - there's still an issue with the first code block: https://github.com/cloudflare/cloudflare-docs/pull/5693/files#diff-d90c57a82ea0972784c9cbfc1bb4816dfe4073cf925ca471531f53e7b62aba1bR25

**Comment by pedrosousa** [comment]
We tend to use `sh` syntax highlighting (which blocks copying lines that do not start with a `$`) in code blocks with Terminal commands. This helps readers copy only the command and not some part of the output by mistake. (We do not follow this strategy for multi-line commands.)

Is this a case where copying the output is relevant? It seems to be available below for copying (step 2).

**Comment by rozenmd** [comment]
Good point @pedrosousa - all good 😄
