### ISSUE TITLE
Incorrect WebCrypto's getRandomValues signature

### ISSUE THREAD

**Issue by leandro-manifesto** [cloudflare/cloudflare-docs#57]
Both [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) and the [spec](https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues) state that the `crypto.getRandomValues()` function should return the passed `ArrayBuffer` with random values inside it, but the Cloudflare Workers docs says it returns a `Promise<ArrayBuffer>` instead.

I do hope this is just a typo.

**Comment by Electroid** [comment]
The documentation is incorrect, just confirmed the Workers runtime does conform to the spec. You're welcome to submit a PR to remove the unnecessary `await`
