### ISSUE TITLE
[R2] Change presigned PutObject to use --data-binary

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#5724]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- R2 Presigned URL examples

### Section that requires update

`curl` command to upload to a given PutObject presigned URL.

### What needs to change?

They currently use curl's FormData `-F` but this results in the FormData object being literally uploaded into R2.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/94662631/188018055-fb385531-fed7-4423-8d26-6f6c3c9e140b.png">

### How should it change?

Using `--data-binary` will give us the intended result.

Related: https://github.com/cloudflare/cloudflare-docs/pull/5706

**Comment by Belly78** [comment]
Hello 👋
