### ISSUE TITLE
Tunnels: does it support kubernetes autoscale?

### ISSUE THREAD

**Issue by holms** [cloudflare/cloudflare-docs#5755]
### Which Cloudflare product does this pertain to?

Cloudflare Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/kubernetes/
https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/

### Section that requires update

This is heavily unclear.

In [this](https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/) doc it says:

```
The same Tunnel can be run from multiple instances of cloudflared, giving you the ability to run many cloudflared replicas to scale your system when incoming traffic changes.
```

But in [this](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/kubernetes/
) doc it says:

```
Create two deployments with one replica each using cloudflared. Configure cloudflared to point to the service IP of the upstream service. 
```

### What needs to change?

So maybe tunnel service developer could explain does this autoscale is even supported with cloudflared or not? Because docs are controversial to each other. Also there are zero information on how to deploy the app, your helm chart is located in a wrong github repo, it should be in `cloudflare/helm-charts` and now it's in `cloudflare/argo-tunnel-examples` which makes it impossible to use with helm, not even .tgz version is available. 

### How should it change?

Clearly state in both documents that multiple replicas can or can't be used.

**Comment by ranbel** [comment]
Hi, thanks for the feedback on how to improve the docs! The Kubernetes guide https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/kubernetes/ was updated in #5791 to hopefully be more clear.
