### ISSUE TITLE
encodeBody `auto` -> `automatic`?

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#5763]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/response/#properties

### Section that requires update

Properties -> `encodeBody`

### What needs to change?

"auto" should be changed to "automatic".

"auto" and any other invalid value results in an error: `TypeError: encodeBody: unexpected value: auto`

### How should it change?

Swap out one word for another :)

**Comment by KianNH** [comment]
Amazed that this was in the documentation for so long but I think I've only ever people talk about setting it to `manual` since `automatic` is the default 🥴 Good catch!

Will be closed by https://github.com/cloudflare/cloudflare-docs/pull/5796
