### ISSUE TITLE
Clarify if `compatibility_date` and `compatibility_flags` can also be set via the dashboard

### ISSUE THREAD

**Issue by CetinSert** [cloudflare/cloudflare-docs#5775]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

Clarify if `compatibility_date` and `compatibility_flags` can also be set via the dashboard without `wrangler`.

### Content Location

https://developers.cloudflare.com/workers/platform/compatibility-dates/

### Additional information

We really hope this can be done purely via the dashboard.
If there is no way, please let us know whom to contact to request adding this as a new feature.

**Comment by KianNH** [comment]
They indeed cannot be set in the dashboard - they can be set with the API or [wrangler](https://github.com/cloudflare/wrangler2) (which just wraps the API anyways) - `wrangler` is the recommended way to develop and publish Workers.

Make a post on the community in the `Feature Request` category (https://community.cloudflare.com/c/feedback/feature-request/30) to request it for the dashboard.

**Comment by CetinSert** [comment]
My goodnes, the API! That covers all of our needs. We just have too many dashboard-only workers to replicate through wrangler. The idea of having to make a local copy just to upgrade the compatibility was scary. API will help us update them without making temporary `wrangler` copies. Thank you!

I personally strongly prefer when the web all just works inside the web browser. Having to drop down to CLI tooling for minor settings feels clumsy. API is a lot more convenient than wrangler though, mostly because there is no temporary local duplication of our dashboard-only workers just for `wrangler` and we can upgrade their compatibility date and flags in place!

API can also be conveniently frontend-ed by us to keep the web things in the web (browser).

Thank you for mentioning the API!

**Comment by CetinSert** [comment]
I have just confirmed that https://developers.cloudflare.com/workers/platform/compatibility-dates/ doesn't mention the compatibility date and flags can be set through the API.

Please mention the API in the docs too and we can close this issue.

**Comment by KianNH** [comment]
I should probably clarify - it can be used via the API in the same way that Wrangler can use it in the API.

Compatibility dates & flags are set at publish time, not like bindings (when using Quick Edit) that stay there. You would need to have the Worker script locally that you upload, including compatibility dates & flags as metadata.

https://github.com/cloudflare/wrangler2/blob/893830aaea4391f4b25841132c3cb0ab5d967c60/packages/wrangler/src/create-worker-upload-form.ts#L56

Quick Edit is pretty limited for anything more than super basic Workers.
