### ISSUE TITLE
Clarify how to create an API token for running Wrangler in CI/CD

### ISSUE THREAD

**Issue by avramch** [cloudflare/cloudflare-docs#5801]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/ci-cd/

### Section that requires update

Cloudflare API token

### What needs to change?

It's not really clear to me (a) how and where to get an API token, and (b) what token permissions are sufficient for https://github.com/cloudflare/wrangler-action

### How should it change?

1. Provide a link to this page https://developers.cloudflare.com/api/tokens/create/ with some context
2. Either create an API Token template specifically for [cloudflare/wrangler-action](https://github.com/cloudflare/wrangler-action), similarly to the "Edit Cloudflare Workers" template. Or, walk through all the required token permissions when creating a custom token (perhaps, show a screenshot of the token permissions section). Or, just tell me to choose the "Edit Cloudflare Workers" template and I'm good to go.

**Comment by kristianfreeman** [comment]
@lauragift21 I think that linking to the API Token creation page here would suffice, what do you think?

**Comment by lauragift21** [comment]
Yes that will fix this, will add it in the docs.
