### ISSUE TITLE
Any interest in a Vanillajs section in the Frameworks guides for Cloudflare Pages docs?

### ISSUE THREAD

**Issue by rishavs** [cloudflare/cloudflare-docs#5804]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

How to create a working site using plain vanillajs

### Content Location

Hi. Is there any interest in my adding a section for Vanillajs based web app in the Framework Guides https://developers.cloudflare.com/pages/framework-guides/deploy-anything/ ?

My plan is to explain how to

- add a tiny naive router
- add error handling
- use esbuild to generate a bundled _worker.js file

The deploy anything page is not sufficient IMO as people who might be interested in trying out plain JS may not know how to do these. 

As this would be a bit more elaborate compared to the other guides, before I send out a PR, I wanted to make sure this idea is fine with the maintainers.

**Comment by deadlypants1973** [comment]
@rishavs thank you for this! Happy to review if you submit a PR.
