### ISSUE TITLE
Typo `namespace` should be `broker`

### ISSUE THREAD

**Issue by nathanclevenger** [cloudflare/cloudflare-docs#5857]
### Which Cloudflare product does this pertain to?

Pub/Sub

### Existing documentation URL(s)

https://developers.cloudflare.com/pub-sub/get-started/guide/#5-create-a-broker

### Section that requires update

[5. Create a Broker](https://developers.cloudflare.com/pub-sub/get-started/guide/#5-create-a-broker)

### What needs to change?

```
$ wrangler pubsub namespace create example-broker --namespace=my-namespace
```

### How should it change?

```
$ wrangler pubsub broker create example-broker --namespace=my-namespace
```

**Comment by kodster28** [comment]
Not exactly sure when, but this is now updated at https://developers.cloudflare.com/pub-sub/get-started/guide/#5-create-a-broker.

Thanks for the typo catch!
