### ISSUE TITLE
wrangler.toml configuration page is confusing

### ISSUE THREAD

**Issue by vlovich** [cloudflare/cloudflare-docs#5876]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/

### Section that requires update

The example wrangler.toml appears to be trying to document every single possible combination of things you can do.
This is extremely complicated.

I think there should be multiple simpler examples with exposition as proper documentation.

### What needs to change?

For example: 

```
# A list of routes that your Worker should be published to.
# Only one of `routes` or `route` is required.
# Only required when `workers_dev` is false, and there is no scheduled Worker (refer to `triggers`)
routes = ["routes"] | [{ pattern = "*", zone_id = "ZONE_ID" }] | [{ pattern = "*", zone_name = "ZONE_NAME" }]

# The same as routes, but only one.
route = "routes" | { pattern = "*", zone_id = "ZONE_ID" } | { pattern = "*", zone_name = "ZONE_NAME" }
```

I think it's trying to write a pseudo set of options of what valid TOML can look like (but it's not clear if "routes" is the literal string `"routes"` or if it's an array of routes.

### How should it change?

I suspect this whole page needs an overhaul.

**Comment by KianNH** [comment]
> I suspect this whole page needs an overhaul.

https://github.com/cloudflare/cloudflare-docs/pull/5150
