### ISSUE TITLE
Wrangler.toml code snippet exceeds 80 characters requiring horizontal scrolling

### ISSUE THREAD

**Issue by vlovich** [cloudflare/cloudflare-docs#5878]
### Example URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/

### Actual Behavior

There are lines that are up to 139 characters requiring horizontal scrolling even on a very wide display. There's also a ton of wasted whitespace on larger displays which exacerbates the problem to this but I doubt that's something we'd want to change.

### Expected Behavior

Wrangler.toml configuration should fit without any horizontal scrolling on a normal display.

**Comment by KianNH** [comment]
I've rewritten all of the Wrangler configuration page (https://kian-wrangler-configuration.cloudflare-docs-github.pages.dev/workers/wrangler/configuration/) - just pending review in https://github.com/cloudflare/cloudflare-docs/pull/5150

**Comment by kodster28** [comment]
Howdy @KianNH, since that PR was merged in, can we close out this issue?

**Comment by KianNH** [comment]
Hi @kodster28 - yeah, the new page has some whitespace overflow but that's about it so all of the examples fit without needing to scroll.
