### ISSUE TITLE
cloudflared service install - clarify help text

### ISSUE THREAD

**Issue by Vortexmind** [cloudflare/cloudflare-docs#591]
Using `cloudflared` on `ubuntu`
```
$ cloudflared version
cloudflared version 2020.12.0 (built 2020-12-08-2302 UTC)
```
### Issue
When passing a config file to the `cloudflared service install` command, the help test shows the following
```
USAGE:
   cloudflared service install [command options] [arguments...]

OPTIONS:
   --legacy    Generate service file for non-named tunnels (default: false)
   --help, -h  show help (default: false)
```
However the `--config` option (not listed in the contextual help) must be typed immediately after `cloudflared` , for example
```
cloudflared --config ~/.cloudflared/my-config.yml service install
```

### Recommended solution
Clarify the contextual help to show the correct for the `--config` option, [in line with the documentation](https://developers.cloudflare.com/argo-tunnel/run-tunnel/run-as-service#linux).

**Comment by abracchi-tw** [comment]
closing this for the time being
