### ISSUE TITLE
[R2] Workers Runtime APIs layout & formatting

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#5917]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-reference/

### Section that requires update

Layout and formatting.

### What needs to change?

The current layout, whilst satisfactory for a type reference, will struggle to scale as the APIs gain more options and require more explanations/walkthroughs on how to properly utilise them.

As an example, the addition of the new checksums supported in `R2PutOptions` means that either:

1) Every checksum is listed on it's own, with an aside that only one can be used at a time.
2) The type for the 'checksum' in `R2PutOptions` becomes `md5 | sha1 | sha256 | sha384 | sha512`

Either way, it becomes very verbose and will easily confuse people.

### How should it change?

Taking inspiration from well-regarded documentation layouts such as `docs.rs` (i.e https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html), we should come up with a consistent structure on documenting Worker's Runtime APIs that we can then extend to refactoring the pages for KV, Durable Objects and the like.

We want a good middle-ground between providing a reference, and providing a how-to, without going too in-depth that the material would be better split off into it's own how-to page.

As an example of one potential layout that was discussed by myself and @Frederik-Baetens:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/94662631/191375548-9e5244fe-85be-4ca1-929a-4af793699941.png">

Using the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element, this allows us to:

1) Provide a lot of value without cluttering the rest of the page, as it's expandable.
2) Preserve the 'searchability' of the content, as CTRL+F on the majority of browsers will 'look inside' a `<details>` element.
3) Additionally include small examples, not in-depth or niche enough for their own page, under additional `<details>` elements.

The 'signature' of the function is shown to provide a type reference to those who 'know what they're doing' and just need a quick look at what the types are, with further explanations of what those types actually are further down.

The rest of the tab explains what dictates which type will be returned, and then goes on to include some bite-sized examples.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/94662631/191375800-c884bf3c-dade-43a3-8aed-f3e48f1d6b21.png">

### Additional information

Original discussion: https://github.com/cloudflare/cloudflare-docs/pull/5897

**Comment by KianNH** [comment]
As per some feedback in the Discord, I quite like the idea of having the overall 'method' element open **by default** but the examples collapsed.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/94662631/191379722-bafe65db-729f-414c-b0a1-11f28ea1ca25.png">

Makes it easier to skim at a glance.

**Comment by danielstoyanov99** [comment]
Здравейте,Може ли чат на живо?
