### ISSUE TITLE
Unable to check status of build if inprogress or is stucked using external webpack

### ISSUE THREAD

**Issue by VarunTwri** [cloudflare/cloudflare-docs#5920]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

How to check build logs

### Content Location

We are integrating  an application with cloud flare but its stucking build may be we are not sure even if build is running.
![image](https://user-images.githubusercontent.com/102298041/191439088-6b4e321f-2eca-4db4-aa80-42571019f05b.png)
 

### Additional information

Please check the wrangler.toml file
![image](https://user-images.githubusercontent.com/102298041/191439264-a573f2ac-8227-416b-bd15-d2cd78ec7af0.png)

**Comment by rozenmd** [comment]
Hi @VarunTwri, if this is a new project, you may want to look at https://github.com/cloudflare/wrangler2 - a lot of the configuration from wrangler 1 is no longer required, and should be easier to get started.

Closing this issue as unrelated to cloudflare-docs.
