### ISSUE TITLE
Add non WARP Client Setup path to DNS instructions

### ISSUE THREAD

**Issue by kkrum** [cloudflare/cloudflare-docs#5935]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/policies/filtering/initial-setup/dns/

### Section that requires update

Connect to Gateway

### What needs to change?

Add instructions for how to connect to Gateway without the WARP Agent (or link to other content we already have)

### How should it change?

Add instructions for how to connect to Gateway without the WARP Agent (or link to other content we already have)

**Comment by ranbel** [comment]
Hey Kyle, would you mind creating a Jira ticket? Usually we use GitHub Issues for external requests.

**Comment by helloimalastair** [comment]
@kkrum, can't deep-link to Zero-Trust dash, but maybe you could base off of/link to the setup instructions at https://dash.teams.cloudflare.com/?to=/:account/gateway/locations/:location/instructions ?

**Comment by ranbel** [comment]
We have a section on connecting locations: https://developers.cloudflare.com/cloudflare-one/policies/filtering/initial-setup/dns/#connect-dns-locations
What other on-ramps were you thinking of?

**Comment by ranbel** [comment]
Closing this issue because we already link to DoH instructions.
