### ISSUE TITLE
Privacy page not complete

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#595]
On the privacy page of the doc of Gateway (for team), 
you explain how long you kept Data but not why and if you do something with it : 

Cloudflare Gateway logs are stored for a varying period of time based on the service used:
- DNS logs corresponding to DNS filtering: up to six months
- HTTP logs corresponding to HTTP traffic filtering: up to 30 days
- Teams Free users will have the visibility into the last 24 hours of DNS activity logs. Teams Standard and Enterprise users have 30 days of visibility into both DNS and HTTP activity logs.

source : https://developers.cloudflare.com/gateway/privacy

**Comment by abracchi-tw** [comment]
hi @Macqael, thank you for raising this. We're working to improve the Analytics section of our new Cloudflare for Teams documentation, so keep an eye on [this page](https://developers.cloudflare.com/cloudflare-one/analytics/logs) for upcoming improvements. Thanks again!
