### ISSUE TITLE
Include IPv6 adresses in the section for network operators

### ISSUE THREAD

**Issue by xopez** [cloudflare/cloudflare-docs#5962]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/1.1.1.1/infrastructure/network-operators/

### Section that requires update

Available Endpoints

### What needs to change?

We should include the IPv6 adresses there

### How should it change?

The table should get a new seperator so we can differ from ipv4 and ipv6

**Comment by marciocloudflare** [comment]
Hi there. This was addressed in [PR-6072](https://github.com/cloudflare/cloudflare-docs/pull/6072). Thanks!
