### ISSUE TITLE
Workers: Missing docs for TextEncoderStream/TextDecoderStream & Release notes

### ISSUE THREAD

**Issue by vlovich** [cloudflare/cloudflare-docs#5970]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

It looks like sometime in July (`a448321204a80d06b52bdae86f0dc00c87e53291`) introduced `TextEncoderStream`/`TextDecoderStream` but there was a missing annotation in the commit so it was never included in the community post & seems like it never made it into the external release notes.

cc @jasnell 

### Section that requires update

[Workers changelog](https://developers.cloudflare.com/workers/platform/changelog/) for the appropriate release date

Maybe [Web Standards](https://developers.cloudflare.com/workers/runtime-apis/web-standards/#compression-streams). It's a little unclear what makes it onto that page.

Probably entries in https://developers.cloudflare.com/workers/runtime-apis/streams/

### What needs to change?

I'll leave that to @jasnell / tech writers.

### How should it change?

I'll leave that to @jasnell / tech writers.

**Comment by jasnell** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/6492
