### ISSUE TITLE
Cloning the developers' website.

### ISSUE THREAD

**Issue by abdulsohu** [cloudflare/cloudflare-docs#599]
Hi!

I'm trying to build a GatsbyJS website like https://developers.cloudflare.com/docs and was wondering what the best way to go about this would be? Ideally I would want to clone the developers website and play with it until I understand it fully and then go ahead tweaking it, but I don't quite understand how I'd clone that source code at https://developers.cloudflare.com/

Thanks!

**Comment by KimJ15** [comment]
Thanks for opening this issue. You can find information about setting up a development environment here: https://developers.cloudflare.com/docs-engine/contributing/development-setup
