### ISSUE TITLE
Custom ports for outgoing HTTPS requests from Workers are ignored

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#5998]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

Workers Known Issue

### Content Location

https://developers.cloudflare.com/workers/platform/known-issues/

### Additional information

In production, Workers currently silently ignores any custom ports when using HTTPS. For example:

```js
await fetch('https://example.com:1234/foo')
```

is the equivalent of:

```js
await fetch('https://example.com/foo')
```

443 is used instead.

This _isn't_ the case for the quick edit in the dashboard, or on cloudflareworkers.com, or when using HTTP. `wrangler dev` logs [a warning message](https://github.com/cloudflare/wrangler2/blob/ee6b4138121b200c86566b61fdb01495cb05947b/packages/wrangler/templates/checked-fetch.js#L11).

**Comment by AlbertSPedersen** [comment]
It's not as simple as Cloudflare Workers ignoring the custom port outright. I've dealt with custom ports in Cloudflare Workers quite a few times, and I feel like I have a pretty good understanding of how they behave. Here's a flowchart I made:
![image](https://user-images.githubusercontent.com/40433209/192508289-425b8006-eb7c-498b-a742-7403ca77b7bc.png)
In short, you cannot specify a custom port in requests to other domains - most likely for security reasons.
