### ISSUE TITLE
Missing Functions in the Ruleset Engine Documentation

### ISSUE THREAD

**Issue by itsmatteomanf** [cloudflare/cloudflare-docs#6017]
### Which Cloudflare product does this pertain to?

Ruleset Engine

### Existing documentation URL(s)

- https://developers.cloudflare.com/ruleset-engine/rules-language/functions/

### Section that requires update

The Transformation Functions sections.

https://developers.cloudflare.com/ruleset-engine/rules-language/functions/#transformation-functions

### What needs to change?

Some functions are undocumented, like `substring()`.

### How should it change?

Add all missing functions, and of course, fields if some are missing.

**Comment by pedrosousa** [comment]
Hi @itsmatteomanf 
Thank you for your patience. :) We've been gathering some internal info to be able to address the issue you reported. 
For tracking purposes, this is being addressed internally in PCX-4862.

**Comment by KimJ15** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/5826 closes out this issue
