### ISSUE TITLE
[Wrangler] Document --keep-vars

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/cloudflare-docs#6024]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/commands/#publish

### Section that requires update

https://developers.cloudflare.com/workers/wrangler/commands/#publish

### What needs to change?

add --keep-vars

### How should it change?

add --keep-vars

**Comment by Mk1206mk** [comment]
https://github.com/cloudflare/cloudflare-docs/issues/6024#issue-1389089178
