### ISSUE TITLE
[Logs] Custom fields should add more details of dashboard usage

### ISSUE THREAD

**Issue by cicku** [cloudflare/cloudflare-docs#6033]
### Which Cloudflare product(s) does this pertain to?

Logs

### Subject Matter

Dashboard instructions

### Content Location

https://developers.cloudflare.com/logs/reference/custom-fields/

### Additional information

Currently this page looks like an explanation of API. The feature is also available in the dashboard, we need to add this to the page as well.

---

```
## Manage via API
...
## Manage via Dashboard
...
```

**Comment by angelampcosta** [comment]
@cicku Thank you for reaching out. We'll follow up on this with an internal ticket.
