### ISSUE TITLE
Wrong documentation or implementation error in Turnstile `turnstile.getResponse(widgetId: string)` function

### ISSUE THREAD

**Issue by Haocen** [cloudflare/cloudflare-docs#6070]
### Example URL(s)

According to the [documentation](https://github.com/cloudflare/cloudflare-docs/blob/production/content/turnstile/get-started/client-side-rendering.md#access-a-widgets-state) , `turnstile.getResponse` should accept a string returned from ` turnstile.render`, namely `widgetId`.

### Actual Behavior

![image](https://user-images.githubusercontent.com/10842569/193151966-3b51ac20-cb6d-49cc-8fce-198e94cee35c.png)
It appeared Turnstile will throw error if the `widgetId` is passed into `turnstile.getResponse`.

After a little debugging it appeared `turnstile.getResponse` expect a `widgetId` without the `cf-chl-widget-` prefix.

### Expected Behavior

- `turnstile.getResponse` should accept `widgetId` returned from `turnstile.render`.
- `turnstile.getResponse` should not throw when unknown `widgetId` is passed in. It should return `undefined` or whatever deemed appropriate.

### Additional information

I believe this is more of an implementation error than documentation issue but I didn't find a place to report this bug.

**Comment by migueldemoura** [comment]
Hi @Haocen, we're going to fix the `turnstile.getResponse()` call so it behaves as expected. Appreciate the detailed report!

**Comment by isaumya** [comment]
Hey @migueldemoura,
Quick question: Currently in the Turnstile JS URL has a `/v0/` in the path: ` https://challenges.cloudflare.com/turnstile/v0/api.js`.

So, in the future when this product gets out of Beta or you guys update the code is there a chance of this URL to break? I mean let's say in the future you guys do `/v1/` replacing `/v0/` which will break the `api.js` path.

The only reason I'm asking this is because if this product gets pushed to many sites and then suddenly things break due to URL changes and we need to replace all the URLs again - just don't want to be in that situation.

**Comment by migueldemoura** [comment]
Hi @isaumya!

> So, in the future when this product gets out of Beta or you guys update the code is there a chance of this URL to break? I mean let's say in the future you guys do `/v1/` replacing `/v0/` which will break the `api.js` path.

We will keep the `/v0/` endpoint when Turnstile gets out of Beta. Even if we end up adding a `/v1/`, they'll both be available and thus your script won't break.
If at some point in the future we end up wanting to remove `/v0/`, we'll provide a migration path, notification to users and a reasonable timeframe to do said migration.

**Comment by isaumya** [comment]
Hi @migueldemoura,
I think it would be a smarter choice to remove the versioning number from the URL as soon as possible. That will mean people can implement it without worrying about changing the script URL in future. This will also increase trust in the dev community. It will also help your team to refine the code without worrying about asking users to change the script URL.

**Comment by isaac-mcfadyen** [comment]
API versioning is important. That version number helps them make sure that if they need to make a breaking change, they won't break existing scripts. As has been said here, they don't have plans yet to deprecate `/v0/` and if they do there will be an obvious alert/message to users.

Regardless, this Github Issue is unrelated to Turnstile's API versioning. I'd recommend you ask on the [Cloudflare Developers Discord](https://discord.gg/cloudflaredev) or the [Cloudflare Community](https://community.cloudflare.com) if you wish to keep discussing this.

**Comment by migueldemoura** [comment]
Hey folks, we've released an update for this that should have fixed the issue with `turnstile.getResponse()`.
Closing this, but feel free to reopen if the issue persists. Thanks again for the report!

**Comment by gplusdotgr** [comment]
@migueldemoura is there's a page in the documentation that shows the signature of getResponse? I wasn't able to find something.

**Comment by lealceldeiro** [comment]
Same as @gkatsanos , we need a better docs showing the response structure from calling `getResponse`. It's very hard to develop without this doc being available.
