### ISSUE TITLE
Highlight the differences between all the ways we can develop Workers

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/cloudflare-docs#6100]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

All the ways to develop Workers

### Content Location

https://developers.cloudflare.com/workers/

### Additional information

- Production Workers, Quick Edit, https://cloudflareworkers.com/, Remote Dev, Local Dev, Miniflare Raw, etc.? 

- Would be cool as a doc too. I've noticed some differences, but probably not everything.

from @helloimalastair

**Comment by KimJ15** [comment]
Hey there - I'm going to close this issue out in lieu of an effort to create specific, internal tutorial tickets that capture what we need for Workers. Feel free to open a PR if you have content! FYI @kristianfreeman and @rickyrobinett.
