### ISSUE TITLE
Public Bucket API

### ISSUE THREAD

**Issue by jlarmstrongiv** [cloudflare/cloudflare-docs#6109]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Public Bucket APIs

### Content Location

Content Locations:
- https://developers.cloudflare.com/r2/data-access/public-buckets/
- https://developers.cloudflare.com/r2/data-access/s3-api/api/
- https://api.cloudflare.com/#r2-bucket-properties

### Additional information

I cannot find the documentation for how to create a public bucket.

Ideally, mirror https://developers.cloudflare.com/r2/data-access/public-buckets/ but explain the same examples via the API

**Comment by Frederik-Baetens** [comment]
Hi, in the S3 api, creating public buckets through the API relies on ACLs, which are currently unsupported. We plan to support ACLs in the future though, at which point it will likely become possible to create public buckets through the S3 api.

**Comment by vlovich** [comment]
@Frederik-Baetens which API is that? I didn't see any. AFAIK they key of the bucket name & implicit ACLs and the way we do public buckets doesn't map well.

Probably what we want to do is formally document the APIv4 that the UI uses to control public buckets once we do an API review to make sure it's something we want to commit to supporting..

cc @mnewswanger-cloudflare

**Comment by Frederik-Baetens** [comment]
I think you can set the bucket-level ACL `public-read` in the `x-amz-acl` parameter of [PutBucketAcl](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketAcl.html#API_PutBucketAcl_RequestSyntax). You can also pass that parameter to [CreateBucket](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#API_CreateBucket_RequestSyntax)

I didn't consider how this would interact with the way we do public buckets. I just assumed (perhaps wrongly so) it was likely we could integrate our public buckets with the existing S3 ACL API.

**Comment by jlarmstrongiv** [comment]
@vlovich 

> Probably what we want to do is formally document the APIv4 that the UI uses to control public buckets once we do an API review to make sure it's something we want to commit to supporting..

That sounds like how Backblaze B2 works.  They allow making a public bucket through the Backblaze B2 API, but not their S3 compatible API.  

---

@Frederik-Baetens 

That’s cool!  I didn’t realize I could specify `public-read` in the `x-amz-acl` parameters.  

I normally make my bucket public by setting [`PutBucketCors`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html)

---

Either way, it’d be great to have a way to make public buckets programmatically with Cloudflare.

**Comment by jlarmstrongiv** [comment]
Related https://community.cloudflare.com/t/make-an-r2-bucket-public-via-wrangler-api/436202

**Comment by jlarmstrongiv** [comment]
Unfortunately, this issue is complicated by new `r2.dev` subdomain limitations:

> Public access through r2.dev subdomains are rate limited and should only be used for development purposes.
>
> To enable access management, Cache and bot management features, you must set up a custom domain when enabling public access to your bucket.
>
> https://developers.cloudflare.com/r2/buckets/public-buckets/

**Comment by jlarmstrongiv** [comment]
Closing issue.
