### ISSUE TITLE
[Terraform | Load Balancer Monitor] Invalid argument check_regions

### ISSUE THREAD

**Issue by rafaellucio** [cloudflare/cloudflare-docs#6114]
### Which Cloudflare product does this pertain to?

Load Balancing

### Existing documentation URL(s)

- https://github.com/cloudflare/cloudflare-docs/blob/production/content/terraform/tutorial/use-load-balancing.md

### Section that requires update

4. Switch to using Cloudflare's Load Balancing product

### What needs to change?

In the code sample of subitem **i. Define and create the health check ("monitor")**

```shell
$ git checkout step5-loadbalance
Switched to branch 'step5-loadbalance'

$ cat >> cloudflare.tf <<'EOF'

resource "cloudflare_load_balancer_monitor" "get-root-https" {
  expected_body  = "alive"
  expected_codes = "200"
  method         = "GET"
  timeout        = 5
  path           = "/"
  interval       = 60
  retries        = 2
  check_regions  = ["WNAM", "ENAM", "WEU", "EEU", "SEAS", "NEAS"] # this is invalid argument
  description    = "GET / over HTTPS - expect 200"
}
EOF
```

Looking [this documentation](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/load_balancer_monitor.md) the **check_regions** attribute don't exists, it can be removed

### How should it change?

The **check_regions** attribute can be added in other code sample in this documentation like: **ii. Define and create the pool of origins**

```shell
$ cat >> cloudflare.tf <<'EOF'

resource "cloudflare_load_balancer_pool" "www-servers" {
  name    = "www-servers"
  monitor = cloudflare_load_balancer_monitor.get-root-https.id
  origins {
    name    = "www-us"
    address = "203.0.113.10"
  }
  origins {
    address = "198.51.100.15"
    name    = "www-asia"
  }
  description        = "www origins"
  enabled            = true
  minimum_origins    = 1
  notification_email = "you@example.com"
  check_regions      = ["WNAM", "ENAM", "WEU", "EEU", "SEAS", "NEAS"] # valid argument
}
EOF
```

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/load_balancer_pool.md

**Comment by tc80** [comment]
Great catch, thanks for noticing @rafaellucio 💯 ! In summary, `check_regions` is a property for `cloudflare_load_balancer_pool`, _not_ a property for `cloudflare_load_balancer_monitor`.

Double-checking, I see that it is present in the pool schema [here](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/schema_cloudflare_load_balancer_pool.go#L48) but not in the monitor schema [here](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/schema_cloudflare_load_balancer_monitor.go).

**Comment by kodster28** [comment]
Closing this out as likely fixed @tc80, but feel free to re-open if I'm misunderstanding.
