### ISSUE TITLE
too much ram usage

### ISSUE THREAD

**Issue by Sapoose** [cloudflare/cloudflare-docs#612]
When i use this client for long time it uses too much ram.
![image](https://user-images.githubusercontent.com/60824904/103862123-8bde8300-50cf-11eb-9dce-edaaa8ae84d7.png)

**Comment by KimJ15** [comment]
👋 @Sapoose  I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
