### ISSUE TITLE
[R2] Add aws-sdk-net example

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#6133]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Document how to use the aws-sdk-net package

### Content Location

- R2 Examples

### Additional information

The `aws-sdk-net` package attempts to use streaming SigV4 so the operations need to be given the `DisablePayloadSigning = true` option.

The error you get back is a pretty cryptic 'STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented' and it's a pain point that users often run into - would be good to document this so users can see what they might need to get it working with R2 that they don't need for S3/B2/etc

**Comment by Gunes1111** [comment]
Berhenti mohon jangan ada lagi notifikasi ini

Pada tanggal Rab, 5 Okt 2022 2.52 PM, Kian ***@***.***>
menulis:

**Comment by gee1k** [comment]
This error also exists when using the swift library soto, does anyone know how to fix it?

https://github.com/soto-project/soto
