### ISSUE TITLE
Vary + Workers' Cache API

### ISSUE THREAD

**Issue by seeekr** [cloudflare/cloudflare-docs#6175]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/cache/

### Section that requires update

https://developers.cloudflare.com/workers/runtime-apis/cache/#invalid-parameters

Methods > Put > Invalid Parameters

### What needs to change?

<img width="645" alt="CleanShot 2022-10-07 at 12 11 36@2x" src="https://user-images.githubusercontent.com/302886/194530220-5346f8ee-0701-421b-b7f9-a9b6ce855701.png">

> the response passed contains the header Vary: * (required by the Cache API specification).

The linked document (at the top of the page! -- https://developer.mozilla.org/en-US/docs/Web/API/Cache) does not say anything about the Vary header having an influence on the required behavior of the Cache API.

The API, when used in CF workers, also does not seem to be throwing when given a response that does have a Vary header.

### How should it change?

There should be a link to a document that provides info specific to the Vary + Cache API interaction. Right now there's only the link to the MDN at the top of the page, but searching through those docs I cannot find any info on this interaction.

Other than that I'm not sure if/what needs to change, if at all. I am mostly still confused and just wanted to raise awareness that perhaps there's an issue here, if only with documentation not being 100% ideal.

Thanks for the great work on this!

**Comment by KianNH** [comment]
> The API, when used in CF workers, also does not seem to be throwing when given a response that does have a Vary header.

It looks like it throws for me.

`✘ [ERROR] Uncaught (in response) TypeError: Cannot cache response with 'Vary: *' header.`

Notably, the `*` isn't to say 'any value' but rather if the `Vary` header literally has the value of `*`.

**Comment by KianNH** [comment]
> The linked document (at the top of the page! -- https://developer.mozilla.org/en-US/docs/Web/API/Cache) does not say anything about the Vary header having an influence on the required behavior of the Cache API.

This is defined in the Service Worker spec - since the Cache implementation is a Service Worker API.

https://w3c.github.io/ServiceWorker/#cache-put

- If innerResponse’s [header list](https://fetch.spec.whatwg.org/#concept-response-header-list) contains a [header](https://fetch.spec.whatwg.org/#concept-header) [named](https://fetch.spec.whatwg.org/#concept-header-name) `Vary`, then:

  - Let fieldValues be the [list](https://infra.spec.whatwg.org/#list) containing the [items](https://infra.spec.whatwg.org/#list-item) corresponding to the [Vary](https://tools.ietf.org/html/rfc7231#section-7.1.4) header’s [field-values](https://tools.ietf.org/html/rfc7230#section-3.2).
  - [For each](https://infra.spec.whatwg.org/#list-iterate) fieldValue in fieldValues:

    - If fieldValue matches "*", return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) a TypeError.

**Comment by seeekr** [comment]
> Notably, the * isn't to say 'any value' but rather if the Vary header literally has the value of *.

Oh wow, thanks for pointing that out, I must have read that wrong then. Huh, I guess when interpreting this correctly now, this restriction makes a lot more sense. I guess caching literally makes no sense when the response could vary on anything that's allowed "to be varied on".

Perhaps your clarification could be added on to that part of the doc. There might be more folks like me not taking this as literal as we should, and their brains parsing '*' as some kind of glob expression :)

But I still cannot find any documentation on the web that states this 'Vary: *' requirement, don't even know where to find the specification. I think if the CF docs state it in this way it would make a lot of sense to be able to link to the source. I at least would appreciate that, and perhaps others who always want to learn more about the how and why of the workings of the web technologies.

EDIT: I see you've linked and quoted it, thanks! Right, Service Worker spec, makes sense.
