### ISSUE TITLE
Workers: Update all Examples to also include new Module Syntax Option

### ISSUE THREAD

**Issue by JustinGrote** [cloudflare/cloudflare-docs#6195]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

The new Module Syntax should be included alongside in the examples, just like it is in the tutorials

### Content Location

https://developers.cloudflare.com/workers/examples/

### Additional information

Example: For Return Small HTML Page, also include a module example that would look something like this:

```ts
const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;

async function handleRequest(request) {
  return new Response(html, {
    headers: {
      'content-type': 'text/html;charset=UTF-8',
    },
  });
}

export default {
  fetch: handleRequest
}
```

This is especially useful to new people who may not be comfortable with the syntax, and while this example is simple, other ones that involve things like waitUntil, etc. are kind of hard to translate if you're not comfortable with the module syntax, and it would be better to get people starting out to use module syntax as it is more intuitive, especially when using Typescript.

**Comment by helloimalastair** [comment]
@JustinGrote, this is currently being tracked in issue #5829.
Module Syntax(JS and TS) have been implemented on three pages so far:
* [103-early-hints.md](https://tab-switcher-demo.pages.dev/workers/examples/103-early-hints/)
* [ab-testing.md](https://tab-switcher-demo.pages.dev/workers/examples/ab-testing/)
* [accessing-the-cloudflare-object.md](https://tab-switcher-demo.pages.dev/workers/examples/accessing-the-cloudflare-object/)

and once a trial run is completed, the rest of the examples will be updated.
