### ISSUE TITLE
Add `width` and `height` attributes to images to reduce CLS

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#6199]
Cumulative Layout Shift happens when a page has to repaint things, and then all of a sudden things shift around the page. This can be very distracting and happens a lot on the docs site due to images not having any set dimensions and therefore no aspect ratios to adhere to.

Some good references:

- https://web.dev/optimize-cls/
- https://www.smashingmagazine.com/2021/06/how-to-fix-cumulative-layout-shift-issues/
- https://jakearchibald.com/2022/img-aspect-ratio/

### Actual Behavior

Take https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics/ for example. This is a page with an image at the top, and the CLS is `0.128`- WAY higher than the desired `0`.

Here's a quick video demonstrating this: https://up.jross.me/r15pv1c4
Notice how the "Code" section is bumped down the page as the image loads in? That's the layout shift occurring and is very jarring especially if the image takes a while to load and I'm already reading the doc. 

This impacts every page on the docs site that has images above the fold.

### Expected Behavior

Images should have a set `width` and `height` so that the browser can reserve space for them when rendering. Setting these values won't prevent the images from being downsized when needed either, it'll simply hint the browser of the image's aspect ratio so it can reserve the space needed to render it.

### Additional information

I started work on this a bit, but my lack of experience with Hugo is making it more difficult than I'd like.

Hugo offers [Render Hooks](https://gohugo.io/templates/render-hooks/) though, which should make this very possible. I started with a `layouts/_default/markup/render-image.html` file with this:
```
{{- $src := (.Destination | safeURL) -}}
{{- $alt := .Text -}}
{{- $title := .Title -}}
{{ $resource := .Page.Resources.GetMatch .Destination }}
<!-- handle external links -->
{{- if strings.HasPrefix $src "http" -}}
	<img
		src="{{ .Destination | safeURL }}"
		alt="{{ .Text }}"
		{{ with .Title}} title="{{ . }}"{{ end }}
	/>
<!-- handle absolute URLs-->
{{- else if not (strings.HasPrefix $src "..") -}}
  {{ $imageurl := print "content/" $src }}
  {{ $imageurl }}

  {{- $img := imageConfig $imageurl -}}

  {{ with $img}}
    <img
      src="{{ $src }}"
      alt="{{ $alt }}"
      {{ with $title}} title="{{ . }}"{{ end }}
      {{ with .Width}} width="{{ . }}"{{ end }}
      {{ with .Height}} height="{{ . }}"{{ end }}
    />
  {{ end }}
<!-- handle images with relative pathing -->
{{- else -}}
  {{ $url := urls.Parse .Destination }}
  {{ $combinedpath := (path.Join .Page.File.Dir .Destination)}}
  {{$combinedpath}}

  {{ $imageurl := print "content/" $combinedpath }}
  {{ $imageurl }}

  {{- $img := imageConfig $imageurl -}}

  {{ with $img}}
    <img
      src="{{ $src }}"
      alt="{{ $alt }}"
      {{ with $title}} title="{{ . }}"{{ end }}
      {{ with .Width}} width="{{ . }}"{{ end }}
      {{ with .Height}} height="{{ . }}"{{ end }}
    />
  {{ end }}
{{- end -}}
```

It mostly works, but errors on a couple of edge-cases and needs some more thought (handling remote `http` urls, other relative paths like `../`, etc.). It should be very possible with the `Resources` and/or `imageConfig` stuff though, for someone more familiar with Hugo than me.

I also tweaked the `.DocsMarkdown img` css rule to include `height: auto`, and with both the `height` and `width` attributes set on images, it reduces the CLS on pages to zero, resulting in a much nicer reading experience for any image-heavy pages as the content loads.

**Comment by WalshyDev** [comment]
These edge-cases/issues may be something @brycewray may know more about. I'm sadly a Hugo noob

**Comment by brycewray** [comment]
@WalshyDev I appreciate the compliment. But @Cherry is exactly right — about both the importance of using `aspect-ratio` to reduce CLS and the proposed method of implementing it in Hugo. Nicely done.

**Comment by brycewray** [comment]
@WalshyDev @Cherry In case it would help, I have a somewhat related article:

https://www.brycewray.com/posts/2022/06/responsive-optimized-images-hugo/

**Comment by kodster28** [comment]
Any thoughts on the approach in #8423? From my seat, the estimated width/height values feel better than nothing (could probably add in parsing for inputs too).

Also, thanks to @brycewray for even getting me this far. We're not looking for responsive images, exactly, but the approach + detailed notes in the article were incredibly helpful.

**Comment by brycewray** [comment]
> Also, thanks to @brycewray for even getting me this far. We're not looking for responsive images, exactly, but the approach + detailed notes in the article were incredibly helpful.

@kodster28 Thanks for the kind words! Glad the info was useful to you.

**Comment by Cherry** [comment]
This looks awesome @kodster28 - exactly what I was trying to do with `width` and `height` attrs. 🎉

I think this should be totally possible with `gifs` too - even though you can't optimise them, you should still be able to "load" them to get their width/height, like I kinda had working in my `render-image.html` example.

**Comment by kodster28** [comment]
Yeah, think so as well. Just wanted to exclude them for the time being.

Stay tuned on the PR improvements.
