### ISSUE TITLE
Give Feedback button doesn't work

### ISSUE THREAD

**Issue by dcpena** [cloudflare/cloudflare-docs#6223]
### Example URL(s)

https://developers.cloudflare.com/argo-smart-routing/ or any page where the Give Feedback button is shown.

### Actual Behavior

When the Give Feedback button is clicked, nothing happens.

### Expected Behavior

When the Give Feedback button is clicked, users should be able to submit feedback.

**Comment by kodster28** [comment]
Ooops, that might've been me given that it was working before I merged in #6183.

Will play around with it tomorrow.

**Comment by kodster28** [comment]
Confirmed that this is fixed in production (so long as you hard refresh)
