### ISSUE TITLE
Alert Handshake Failure on connect to endpoint s3 compatible

### ISSUE THREAD

**Issue by Tarcio-Rick** [cloudflare/cloudflare-docs#6252]
### Example URL(s)

https://<ACCOUNT_ID>.r2.cloudflarestorage.com

### Actual Behavior

When trying to connect with any s3 compatible drive be it nodejs, php, java it throws an SSL error

routines:ssl3_read_bytes:sslv3 alert handshake failure

### Expected Behavior

Being able to list saved objects

**Comment by nikitasius** [comment]
same issue

**Comment by sdnts** [comment]
Are y'all using the Cloudflare Warp app (https://cloudflarewarp.com) by any chance?

**Comment by kristianfreeman** [comment]
Closing this as I think this is unrelated to R2 and is a network issue. Please let us know if you need further help!

**Comment by nikitasius** [comment]
> Closing this as I think this is unrelated to R2 and is a network issue. Please let us know if you need further help!

yep. CF have a huge delay before enabling correct access to API. ~20 minutes
