### ISSUE TITLE
API token in Terraform config?

### ISSUE THREAD

**Issue by louwers** [cloudflare/cloudflare-docs#6298]
### Which Cloudflare product does this pertain to?

Terraform

### Existing documentation URL(s)

- https://developers.cloudflare.com/terraform/tutorial/initialize-terraform/

### Section that requires update

1. Define your first Terraform config file

### What needs to change?

Terraform config files are often checked into version control. I don't think they should contain API keys.

### How should it change?

A best practice for retrieving API keys inside Terraform config files should be used instead of putting it in the config file directly.

**Comment by louwers** [comment]
https://learn.hashicorp.com/tutorials/terraform/sensitive-variables

**Comment by ranbel** [comment]
Hi, thanks for your comment! The topic was not covered in Part 1 because Part 1 was intended as a simplified "getting started" guide.  Does [Part 2 of the tutorial](https://developers.cloudflare.com/terraform/tutorial/track-history/) provide the information you are looking for?

**Comment by louwers** [comment]
@ranbel Ah, thanks. Yes, that looks better.

Maybe a warning not to put API keys would still be a good idea, even though it is a _Getting Started_ guide?

Like MongoDB does here for example:

![image](https://user-images.githubusercontent.com/649392/197775081-34522bc5-276b-47b2-8c85-f31debfdb93a.png)

**Comment by ranbel** [comment]
#6524
