### ISSUE TITLE
Need more clarifications about `fetch(event.request)`

### ISSUE THREAD

**Issue by balusch** [cloudflare/cloudflare-docs#6299]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/fetch/

### Section that requires update

https://developers.cloudflare.com/workers/runtime-apis/fetch/

### What needs to change?

Need more clarifications about `fetch(event.request)`

### How should it change?

Need more clarifications about `fetch(event.request)`

### Additional information

The `event.request`(client request) is a little bit special compared to other `Request`, so I'm curious about whether it is allowed to apply 
`fetch` to it. And if it is allowed, what does it mean?  Will it result in recursion?

**Comment by KianNH** [comment]
You can fetch it and it'll just fetch the origin that the Worker is on.

**Comment by balusch** [comment]
> You can fetch it and it'll just fetch the origin that the Worker is on.

@KianNH  Thanks for your explanation and it seems reasonable.  But I'm wondering whether it fetches the origin via the CDN procedure or simply sends an HTTP request directly to the origin server.

I think in the former case, the rules configured in the Cloudflare dashboard still work but not the case in the latter.

Please correct me if there is any mistake.

**Comment by harrishancock** [comment]
> But I'm wondering whether it fetches the origin via the CDN procedure or simply sends an HTTP request directly to the origin server.

The subrequest from the Worker and the subresponse from the origin would have CDN features applied to them. You can control several of those features with the `request.cf` API: https://developers.cloudflare.com/workers/runtime-apis/request/#requestinitcfproperties

Since in your example you are passing through the FetchEvent's original Request (`fetch(event.request)`), then it must be going to your Worker's own zone's origin server. In this case, we disable the Workers feature on the subrequest, meaning it will not result in recursion.

If, on the other hand, you had two zones, `example-a.com` and `example-b.com`, and you had a Worker on each, and those Workers each made subrequests to the other zone, then it's possible that recursion could occur. In this case, we would eventually return an error (an HTTP message with a 5xx status code) after a certain number of recursions.

**Comment by balusch** [comment]
@harrishancock Thanks for your detailed explanation! 😄

> The subrequest from the Worker and the subresponse from the origin would have CDN features applied to them. You can control several of those features with the `request.cf` API: [developers.cloudflare.com/workers/runtime-apis/request/#requestinitcfproperties](https://developers.cloudflare.com/workers/runtime-apis/request/#requestinitcfproperties)

It seems that `fetch(event.request)` sends an HTTP request to the CDN server which does the job of visiting the origin server and thus traditional CDN features are applied. Am I right?

As per the [doc of Workers](https://developers.cloudflare.com/workers/platform/limits/), there are serveral runtime limits for subrequest:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/23381018/196942035-4897e363-6a17-44fa-b4f0-4878e0dc9626.png">

does the `fetch(event.reuqest)` also respect to these limits? After all, it's a little special compared with normal fetches, so I'm not quite sure.

> Since in your example you are passing through the FetchEvent's original Request (`fetch(event.request)`), then it must be going to your Worker's own zone's origin server. In this case, we disable the Workers feature on the subrequest, meaning it will not result in recursion.
> If, on the other hand, you had two zones, `example-a.com` and `example-b.com`, and you had a Worker on each, and those Workers each made subrequests to the other zone, then it's possible that recursion could occur. In this case, we would eventually return an error (an HTTP message with a 5xx status code) after a certain number of recursions.

I can understand the recursion-detection machanism but the concept of **zone** seems not that clear to me(but it doesn't matter).

**Comment by harrishancock** [comment]
> It seems that fetch(event.request) sends an HTTP request to the CDN server which does the job of visiting the origin server and thus traditional CDN features are applied. Am I right?

Yes.

> does the fetch(event.reuqest) also respect to these limits? After all, it's a little special compared with normal fetches, so I'm not quite sure.

Also yes. Note that `fetch(event.request)` is just a normal fetch -- I don't think there's anything special about it. `event.request` defaults to not follow redirects, and it uses the URL of the initiating request, but this could easily be constructed manually.

Lastly, the term _zone_ is a DNS term: https://www.cloudflare.com/learning/dns/glossary/dns-zone/ For our purposes here, you can consider it to be the apex domain(s) that you have onboarded onto Cloudflare.

**Comment by balusch** [comment]
> Also yes. Note that `fetch(event.request)` is just a normal fetch -- I don't think there's anything special about it. `event.request` defaults to not follow redirects, and it uses the URL of the initiating request, but this could easily be constructed manually.

Got it!

> Lastly, the term _zone_ is a DNS term: [cloudflare.com/learning/dns/glossary/dns-zone](https://www.cloudflare.com/learning/dns/glossary/dns-zone/) For our purposes here, you can consider it to be the apex domain(s) that you have onboarded onto Cloudflare.

I'll read it for more details.

Again, thanks for your patience. 😄

**Comment by kodster28** [comment]
Looks like this issue has been solved by the explanation, but feel free to re-open if I'm misjudging that.

**Comment by deadlypants1973** [comment]
@balusch this issue is being tracked internally. When testing is complete and documentation is updated, the new PR updating the docs will be linked to this issue.

**Comment by balusch** [comment]
@deadlypants1973 Hi Kate, actually my question has already been solved, but thanks anyway.
