### ISSUE TITLE
Wrong S3 policy documentation

### ISSUE THREAD

**Issue by Woitekku** [cloudflare/cloudflare-docs#6310]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://support.cloudflare.com/hc/en-us/articles/360037983412-Configuring-an-Amazon-Web-Services-static-site-to-use-Cloudflare

### Section that requires update

Configure bucket policies to allow Cloudflare IP addresses

### What needs to change?

In https://github.com/cloudflare/cloudflare-docs/issues/5175 the Effect has been changed from Deny to Allow, but still the condition says 'NotIpAddresses' which literally blocks IP addresses of CloudFlare

### How should it change?

The condition should be:  
```
"Condition": {
  "IpAddress": {
    "aws:SourceIp": [
```

**Comment by Woitekku** [comment]
There is even another bug, more important... S3 website does not provide https endpoint.

**Comment by kodster28** [comment]
Thanks for the catch, @Woitekku. The article is updated.

As far as your second concern, the article mentions multiple times to `use the domain URL without the https:// part`. I believe that's addressing the concern?

**Comment by kodster28** [comment]
Feel free to provide more detail, but closing for now since we've solve the immediate issue.
