### ISSUE TITLE
Outdated example in 'Migrating to module Workers'

### ISSUE THREAD

**Issue by Vladi-ed** [cloudflare/cloudflare-docs#6343]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/#configuring-your-wranglertoml

### Section that requires update

Configuring your wrangler.toml

### What needs to change?

[build.upload]
format = "modules"
dir = "./src"
main = "./worker.js" # becomes "./src/worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

### How should it change?

When you run Wrangler with this configuration you've got warnings:

    - Deprecation: "build.upload.format":
      The format is inferred automatically from the code.
      
    - Deprecation: "build.upload.dir":
      Use the top level "main" field or a command-line argument to specify the entry-point for the Worker.
      
    - Deprecation: The `build.upload.rules` config field is no longer used, the rules should be specified via the `rules` config field. Delete the `build.upload` field from the configuration file, and add this:
      ```
      [[rules]]
      type = "ESModule"
      ```

### Additional information

In my case (using TypeScript) I also got an error:
 [ERROR] [plugin wrangler-module-collector] Cannot read properties of undefined (reading 'map')

**Comment by mohammadzahoor** [comment]
In _data/chains/eip155-1111.json:

> + "chain": "WEMIX", + "rpc": ["https://api.wemix.com", "wss://ws.wemix.com"], + "faucets": [], + "nativeCurrency": { + "name": "WEMIX", + "symbol": "WEMIX", + "decimals": 18 + }, + "infoURL": "https://wemix.com", + "shortName": "wemix", + "chainId": 1111, + "networkId": 1111, + "explorers": [ + { + "name": "WEMIX Block Explorer", + "url": # "https://explorer.wemix.com",
