### ISSUE TITLE
Add how a public url would be after setting

### ISSUE THREAD

**Issue by ooyamatakehisa** [cloudflare/cloudflare-docs#6378]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

example of public url

### Content Location

In the setting page of a certain bucket (https://dash.cloudflare.com/<account_id>/r2/buckets/<bucket_name>/settings), it would be really thankfull if the example of a public url is shown in "Domain Access" section.

Now the following sentence is written in the "Domain Access" section.
> When Domain access is Allowed, websites can serve content from this bucket. 
Websites connected can also benefit from Cloudflare features such as bot management, Access, and Cache. 
[Learn more](https://developers.cloudflare.com/r2/data-access/public-buckets/#connect-your-bucket-to-a-custom-domain)

So, I think it would be better if the following sentence is added.
```
You can get the object publicly by accessing `https://<domain>/<object_name> `.
```

Is this information written anywhere in the document?
The public url is different form from the one of S3 and I think it's not explicit.

**Comment by kodster28** [comment]
Howdy @ooyamatakehisa,

I believe this is actually addressed by the screenshot in [this section](https://developers.cloudflare.com/r2/buckets/public-buckets/#enable-managed-public-access-for-your-bucket).

Visible directly at [this URL](https://developers.cloudflare.com/assets/public-buckets-allowed_hue2e31160d57b742535244312e173e08f_285671_1999x395_resize_q75_box_3-518a41e9.png).

Feel free to re-open if I'm misunderstanding your request here.
