### ISSUE TITLE
Clarify how Tunnel and Authenticated Origin Pulls interact

### ISSUE THREAD

**Issue by amluto** [cloudflare/cloudflare-docs#6381]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

 - https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull/
 - https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull/set-up/
 - https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns/

### Section that requires update

Both authenticated origin pull pages above probably need an update.

### What needs to change?

Cloudflare users who use Cloudflare Access or, more generally, anything that should require authorization to access a resource require that no other Cloudflare account can bypass the policy.  The requirements for achieving this should be clearly documented.
From the following text on the Tunnel page:

> Unlike publicly routable IP addresses, the subdomain will only proxy traffic for a DNS record in the same Cloudflare account. If someone discovers your subdomain UUID, they will not be able to create a DNS record in another account or system to proxy traffic to the address.

Tunnel seems like it should achieve this automatically, but this could be much, much clearer.

### How should it change?

See above.  If it's indeed the case that authenticated origin pulls are incompatible with Tunnel and unnecessary with Tunnel, the page should say so.

### Additional information

Even with Tunnel, the Authenticated Origin Pull settings and docs are a footgun.  See, for example:

https://medium.com/@ss23/leveraging-cloudflares-authenticated-origin-pulls-for-pentesting-565c562ef1bb

The section on Authenticated Origin Pulls should clarify what security properties the various settings give.  (Actually, this is a big enough footgun that I think enabling Access or any similar feature should warn loudly if you are not using Tunnel or a custom origin pull certificate.)

**Comment by RebeccaTamachiro** [comment]
Hi @amluto 👋  Thank you for raising this. 
I have followed up internally and updated the Dev Docs to provide more guidance regarding CF cert vs custom cert.
#10765
