### ISSUE TITLE
Document ASN for Certificates HTTP validation

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#6434]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/troubleshooting/

### Section that requires update

Universal SSL troubleshooting

### What needs to change?

Documentation doesn't indicate which BGP ASN the DigiCert, Let's Encrypt and other bots would come from. Many customers block all traffic but a few IPs when it comes to pre-production domains. Hence HTTP validation requests coming from Digicert bot fail.

### How should it change?

Document that a WAF rule should allow access to path containing /.well-known/pki-validation and a specific BGP ASN for example.
Document that some are verified bots already (for Bot Management customers).

**Comment by cicku** [comment]
You should look up the information from these CAs, they should provide up-to-date information.

Also, Cloudflare no longer uses DigiCert.

**Comment by RebeccaTamachiro** [comment]
Created PCX-7613 to address this

**Comment by RebeccaTamachiro** [comment]
Closing this one and will continue to work from the ticket referred above.
