### ISSUE TITLE
[KV] KV Modules Syntax Docs Confusing / Contradict Migration Docs

### ISSUE THREAD

**Issue by camsmith** [cloudflare/cloudflare-docs#6438]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/
- https://developers.cloudflare.com/workers/runtime-apis/kv/#referencing-kv-from-durable-objects-and-workers-using-modules-syntax

### Section that requires update

- The migrating to module workers tutorial
- The explanation of how to reference KV from a Worker using the Modules Syntax

### What needs to change?

I created a worker that uses KV and later decided to transition from the Service Worker Syntax to the Module Worker Syntax. As soon as I did this the binding for my KV stopped working `[ERROR] Uncaught (in promise) ReferenceError: KV is not defined`.  (The documentation states that "Durable Objects require the module syntax" but doesn't say anything about KV bindings breaking.)

I was able to figure it out and saw in the [KV documentation](https://developers.cloudflare.com/workers/runtime-apis/kv/#referencing-kv-from-durable-objects-and-workers-using-modules-syntax) that indeed using the module syntax is different for KV's. 

However, I find it pretty confusing that the _KV Documentation_ states as its explanation that "Durable Objects use Modules syntax." Presumably there are Workers written in the module syntax which do not use Durable Objects so it feels kind of odd to conflate the two in this way. The example given then goes on to `export class DurableObject`, which again I think is confusing because I'm writing KV code, not DO code. Inside this Class, another function is created to access the KV 
```
export class DurableObject {  constructor(state, env) {    this.state = state;    this.env = env;  }
  async fetch(request) {    const valueFromKV = await this.env.NAMESPACE.get("someKey");    return new Response(valueFromKV);  }
}

```
but it's unclear to me whether any requests made to KV need to be in this class or not. The [guide to switch from Service Worker syntax to Module Worker Syntax](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/) even says `"Module Workers replace the addEventListener syntax with an object definition, which must be the file’s default export (via export default)."` So, the example given in the KV docs is seemingly incompatible with the example given in the transition docs.

### How should it change?

1. Add the caveat to the "Migrating from Service Worker Syntax to Module Worker Syntax" tutorial that folks using KV will have to change their code to reflect to the new way of importing the namespace binding
2. Clarify the relationship between Module Worker Syntax and the class that the file exports. Does all code need to run in this class? Why is it called a Durable Object if it's in the KV docs? Is it implicitly using a DO? 
3. Create an example for KV that uses the Module syntax (without referencing DO if possible) that comports with the migration guide (which states to have an object be the default export) 

### Additional information

Let me know if I read anything in the docs incorrectly. I'm pretty new to the Workers ecosystem (as well as Node generally) and just found this a little bit confusing.

**Comment by KimJ15** [comment]
👋Hi there, we’re going to close this issue due to inactivity
