### ISSUE TITLE
Article Content out of date: "Deploy a static WordPress site"

### ISSUE THREAD

**Issue by Bojne** [cloudflare/cloudflare-docs#644]
Hi, 

I have some to across this post: [Deploy a static WordPress site](https://github.com/cloudflare/cloudflare-docs/blob/production/products/workers/src/content/tutorials/deploy-a-static-wordpress-site/index.md), but found out the [WP2Static](https://wordpress.org/plugins/static-html-output-plugin/) has been closed as of August 10, 2020, and is not available for download.

<img width="1109" alt="Screen Shot 2021-01-15 at 9 57 47 PM" src="https://user-images.githubusercontent.com/8368609/104735577-b5a54300-577c-11eb-8d77-16466bdc9c2d.png">

Maybe there's an alternative plugin for this tutorial? Or maybe we can add a flag to the blog post?

@saintmalik @adamschwartz 

Thanks! 🙏🏻

**Comment by saintmalik** [comment]
Check out the guide here in the WP2Static on how to compile the source code
of the plugin which is made available as Open Source.

https://wp2static.com/compiling-from-source/

Hope this helps.

**Comment by KimJ15** [comment]
Content will be updated to reflect the Aug 10 change. https://github.com/cloudflare/cloudflare-docs/issues/407 tracks the work. Closing as duplicate.
