### ISSUE TITLE
Superseded media type remains in DoH documentation

### ISSUE THREAD

**Issue by matttpt** [cloudflare/cloudflare-docs#6455]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

- https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/

### Section that requires update

- HTTP method

### What needs to change?

This section indicates that for `POST` requests, the HTTP `Content-Type` should be `application/dns-udpwireformat`. While [early drafts](https://datatracker.ietf.org/doc/html/draft-ietf-doh-dns-over-https-05#section-4.1) of the DNS-over-HTTPS specification did define this media type, [RFC 8484](https://datatracker.ietf.org/doc/html/rfc8484#section-6) settled on `application/dns-message` instead.

FYI, this is the only occurrence of `application/dns-udpwireformat` that I could find in the documentation. (The standard `application/dns-message` appears in the "Valid MIME types" section of the same page and on the ["DNS Wireformat"](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-wireformat/) sub-page.)

Cloudflare's DoH service accepts both media types. However, the inconsistency in the documentation may be confusing, and users who select `application/dns-udpwireformat` may find that other DoH servers do not accept it.

### How should it change?

Replace `application/dns-udpwireformat` with `application/dns-message` to match RFC 8484 and the rest of the documentation.

### Additional information

Thanks for your time with this!

**Comment by marciocloudflare** [comment]
Addressed in [PR-6758](https://github.com/cloudflare/cloudflare-docs/pull/6758)
