### ISSUE TITLE
[Pages Functions] Functions invocation routes `_routes.json` file location

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#6460]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/functions/function-invocation-routes/

### Section that requires update

Create `_routes.json` file

### What needs to change?

We should say that this file belongs in your build output directory

### How should it change?

We should say that this file belongs in your build output directory

**Comment by WalshyDev** [comment]
yup, we missed that
