### ISSUE TITLE
Gateway docs link to 'About' page which is blank

### ISSUE THREAD

**Issue by ScottHelme** [cloudflare/cloudflare-docs#648]
The Cloudflare for Teams page about Gateway links to a blank page here:

![image](https://user-images.githubusercontent.com/5352840/104763653-2721c900-575e-11eb-9a71-4746e7555fcf.png)

This is the URL in the link `https://developers.cloudflare.com/gateway/about`

The page you land on is blank:

![image](https://user-images.githubusercontent.com/5352840/104763761-4f112c80-575e-11eb-9b2a-3989a6bb67d3.png)

**Comment by abracchi-tw** [comment]
this issue has been fixed. thanks!
