### ISSUE TITLE
md code shell copy unselectable chars

### ISSUE THREAD

**Issue by bgbruno** [cloudflare/cloudflare-docs#6497]
### Example URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local

### Actual Behavior

for ` code shell ` - sh , bash
doesn't create element ` span .CodeBlock--token-unselectable `
https://github.com/cloudflare/cloudflare-docs/blob/019a32f673ea965b7eba3827796735a5bb22aa5f/assets/events.ts#L97

so copy block with ` button : Copy to clipboard ` means copy with text ` $ `

### Expected Behavior

copy code like here
https://developers.cloudflare.com/cloudflare-one/tutorials/cli

### Additional information

without it is difficult to reproduce the steps

**Comment by kodster28** [comment]
Thanks again for reporting, @bgbruno (and sorry this took so long to get to).

Confirmed the instance you referenced is fixed.
