### ISSUE TITLE
Wrangler Installation

### ISSUE THREAD

**Issue by kalpaj12** [cloudflare/cloudflare-docs#65]
In  "`2. Install the Workers CLI`", due to this [issue](https://github.com/cloudflare/wrangler/issues/240), provide link to alternative installation via yarn or by building locally.

**Comment by kristianfreeman** [comment]
https://developers.cloudflare.com/workers/get-started/guide#2-install-the-workers-cli

```sh
$ yarn global add @cloudflare/wrangler
```

**Comment by deadlypants1973** [comment]
fixed with 1502
