### ISSUE TITLE
Comparison / conversation around differences between Pages and Pages functions and Workers

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#6505]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

Comparsion of Pages functions and Workers

### Content Location

https://developers.cloudflare.com/pages/migrations/migrating-from-workers/

### Additional information

In the vein of #6397, maybe thinking we should have some conversation around using Pages Functions vs Workers in general.

One point from @lauragift21 would be that -- with Pages Functions -- it's easier to manage all your code in one place.

Not entirely sure who should take the lead on this, whether that's Gift / @codewithkristian / @GregBrimble / @WalshyDev, but figured I'd raise it as an idea.

**Comment by WalshyDev** [comment]
cc: @nevikashah on this too

Could be something we put in the rewrite

**Comment by deadlypants1973** [comment]
Already working on this with another ticket so closing this ticket
