### ISSUE TITLE
Fractional minutes charging in Stream

### ISSUE THREAD

**Issue by ambrt** [cloudflare/cloudflare-docs#651]
Can Stream minutes be billed for fraction of viewed minute?

If someone has 30 seconds videos can they be viewed 2000 times for $1?

**Comment by KimJ15** [comment]
👋 @ambrt I'm sorry, we only take care of developers.cloudflare.com documentation in this repo! Please reach out to community.cloudflare.com or support.cloudflare.com for assistance!
