### ISSUE TITLE
Code snippet shown to illustrate durable object's api should be revised

### ISSUE THREAD

**Issue by bkyerv** [cloudflare/cloudflare-docs#6538]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/learning/using-durable-objects/

### Section that requires update

Code snippet used to illustrate how to use DU seems to have an error. Compared to the github source code in the docs additional code has been added to the example

`let url = new URL(request.url);
  let name = url.searchParams.get("name");
  if (!name) {
    return new Response(
      "Select a Durable Object to contact by using" +
        " the `name` URL query string parameter. e.g. ?name=A"
    );
  }

`

above mentioned defensive logic that checks existence of `name` param in the url makes the rest of the api not usable. In other words when I attempt the '/increment' or '/decrement' apis counter doesn't work because before even hitting the counter logic I see the error that `name` parameter doesn't exist.

### What needs to change?

Either remove the added code snippet in the docs 
`let url = new URL(request.url);
  let name = url.searchParams.get("name");
  if (!name) {
    return new Response(
      "Select a Durable Object to contact by using" +
        " the `name` URL query string parameter. e.g. ?name=A"
    );
  }

` or update it so that DU api of '/increment' or '/decrement' are feasable

### How should it change?

Introduce changes in the code snippet shown to illustrate work of durable object

**Comment by Nuttapon43** [comment]
@deadlypants1973

**Comment by koeninger** [comment]
after copy-pasting https://developers.cloudflare.com/workers/learning/using-durable-objects/#example---counter  to a new wrangler project and publishing it, increment and decrement do seem to work with name query parameter

```
bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=alice
Durable Object 'alice' count: 1
bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=alice
Durable Object 'alice' count: 2
bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=bob
Durable Object 'bob' count: 1
bash-3.2$ curl https://using-durable-objects.cody.workers.dev/decrement?name=bob
Durable Object 'bob' count: 0
```

Can you clarify what commands you were running, what output you observed, and how that output differed from what you expected?

**Comment by bkyerv** [comment]
> after copy-pasting https://developers.cloudflare.com/workers/learning/using-durable-objects/#example---counter to a new wrangler project and publishing it, increment and decrement do seem to work with name query parameter
> 
> ```
> bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=alice
> Durable Object 'alice' count: 1
> bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=alice
> Durable Object 'alice' count: 2
> bash-3.2$ curl https://using-durable-objects.cody.workers.dev/increment?name=bob
> Durable Object 'bob' count: 1
> bash-3.2$ curl https://using-durable-objects.cody.workers.dev/decrement?name=bob
> Durable Object 'bob' count: 0
> ```
> 
> Can you clarify what commands you were running, what output you observed, and how that output differed from what you expected?

It was my mistake I was using the searchParam the wrong way - instead of adding it in the end (after '/increment') I was putting it before. In addition I inserted backslash(/) right before the question mark(?) like so '/?name=alpha'. Please accept my apologies. Thank you for taking time to show what the input in the url bar should look lilke
