### ISSUE TITLE
D1 in Development does not require local mode

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/cloudflare-docs#6559]
### Which Cloudflare product does this pertain to?

Workers (there's no D1 option in the issue select menu)

### Existing documentation URL(s)

https://developers.cloudflare.com/d1/get-started/#4-test-and-publish-with-wrangler

### Section that requires update

"Test and publish with wrangler"

### What needs to change?

The above docs link states that you must use `--local` when developing with a D1 Database, however this is not the case.

### How should it change?

Developers may use remote mode (i.e. no `--local`, developing on Cloudflare's edge), however, they will need to specify `preview_database_id` when doing so, otherwise they'll receive the message `✘ [ERROR] D1 bindings require dev --local or preview_database_id for now`

**Comment by rozenmd** [comment]
I think this was addressed in a re-write of https://developers.cloudflare.com/d1/get-started/
