### ISSUE TITLE
docs point to a dead link

### ISSUE THREAD

**Issue by pleabargain** [cloudflare/cloudflare-docs#656]
https://developers.cloudflare.com/distributed-web/ipfs-gateway/browsing-ipfs
points to
https://cloudflare-ipfs.com/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/
which is NOT working at least on Brave browser
![01⁄20⁄21](https://user-images.githubusercontent.com/640846/105143454-8ee06700-5b04-11eb-86f9-c8af63e6f6e1.png)

**Comment by KimJ15** [comment]
@kodster28 can you review and update the broken link? Thanks!

**Comment by kodster28** [comment]
It's working fine on Safari and Chrome. That leads me to assume the issue is with Brave as opposed to our link.
