### ISSUE TITLE
Better explain what happens when a cache tag purge occures with Cache Reserve enabled

### ISSUE THREAD

**Issue by davidbarratt** [cloudflare/cloudflare-docs#6567]
### Which Cloudflare product does this pertain to?

Cache

### Existing documentation URL(s)

- https://developers.cloudflare.com/cache/about/cache-reserve/#purge

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/2637c7216a37e8006c5a31eb730217036fd10e24/content/cache/about/cache-reserve.md?plain=1#L107

### What needs to change?

I'm not sure I fully understand what the documentation is saying here. 

is it saying that Cache Reserve will _immediaitly_ make a request to the origin server to revalidate the URLs, of which there could be thousands if not millions?
OR
is it saying that the resource will be marked as _stale_  rather than immediaitly being evicted?

### How should it change?

Clarify what happens (either immediialty or on subsequent requests)

**Comment by angelampcosta** [comment]
Hi @davidbarratt thank you for you feedback. We have updated the documentation.

**Comment by davidbarratt** [comment]
Awesome!

So it looks like from your changes https://github.com/cloudflare/cloudflare-docs/commit/d4ed07105cc869bafda6653027414d37e038b573 that it marks the resource as [stale](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#fresh_and_stale_based_on_age) which makes sense to me.
