### ISSUE TITLE
Automatic anchor scrolling is interrupted

### ISSUE THREAD

**Issue by artus** [cloudflare/cloudflare-docs#657]
When clicking on an anchor link in the documentation, the scroll animation is interrupted and you don't end up on the correct position. When clicking the anchor link repeatedly, the scroll animation continues (with interruptions) until you reach the correct position.

Issue does not occur on Chrome.

**Technical details**

Browser: Mozilla Firefox 84.0.2 (64-bit)
OS: Windows 10 Enterprise Version 1809

**Steps to reproduce**

1. Navigate to https://developers.cloudflare.com/workers/platform/limits
2. Click the 'CPU Usage' anchor link in the right column repeatedly, until reaching the correct position

**Video of issue**

https://user-images.githubusercontent.com/22665347/105150787-7a509e80-5b05-11eb-90b0-7b0bbee9a52b.mp4

**Comment by KimJ15** [comment]
Thank you for reporting this bug. I have created an internal ticket for our Engineering team to review. Closing this issue given we will work from an internal ticket.
