### ISSUE TITLE
DNS over HTTPS (Cloudflare Gateway/1.1.1.1) config for Chrome/Edge is outdated - Alternative options?

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflare-docs#658]
Hi,

I've tried following the steps from [here](https://developers.cloudflare.com/1.1.1.1/dns-over-https/web-browser):
https://github.com/cloudflare/cloudflare-docs/commit/c3a31d77ff0030f2e8967fc438f70ca3adaa2a3d#r46145365

However, the instructions here seems to be outdated. The option is no longer available.

Are there any extensions or alternative options available to be able to set a custom DNS over HTTPS (DoH) endpoint?

Thanks,

**Comment by abracchi-tw** [comment]
#702 should fix this. thanks for raising the issue!

**Comment by haneef95** [comment]
Thanks, found that option on Edge today...

However, I was interested as to what the fallback DNS IP Address would be?
