### ISSUE TITLE
Bulk redirect example is missing a trailing slash

### ISSUE THREAD

**Issue by michaelroper** [cloudflare/cloudflare-docs#6594]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/www-redirect/
https://developers.cloudflare.com/pages/how-to/media/create_a_new_bulk_redirect_list.png

### Section that requires update

The image (`create_a_new_bulk_redirect_list.png`) at step 7 of the list that shows the parameters to use when a new bulk redirect.

### What needs to change?

I think that the Target URL in the image should include a trailing slash, eg `https://example.com/`, because otherwise the redirect seems to drop any path suffix on redirect, and only redirects to the root of the site.

### How should it change?

Add a trailing slash to the Target URL in the image, eg `https://example.com/`.

### Additional information

If you follow the instructions per the current image, a request to `www.example.com/foo` will redirect to `https://example.com`, when the desired behaviour should be a redirect to `https://example.com/foo` instead.

**Comment by Erisa** [comment]
Bulk redirects should work without trailing slashes now, since it was identified as a bug and fixed:
https://community.cloudflare.com/t/bulk-redirects-preserve-path-not-including-paths/432163/11?u=erisa

Can you confirm this is the case for you?

**Comment by michaelroper** [comment]
Hi Erisa - I can't see what's behind that link, but if have the need to do another redirect, I'll test it that way for sure. Thanks!

**Comment by Erisa** [comment]
Oh hey my apologies there I accidentally sent a link to a private thread 😓

**Comment by michaelroper** [comment]
No worries - if it was a bug that's now fixed, and the docs should work as they originally were, should I just close this off?

**Comment by Erisa** [comment]
Yep it was determined this was a bug that should now be fixed - it should be safe to close this
