### ISSUE TITLE
Wrong Command Specified in 'install-cloudflare-cert/#git-on-windows'

### ISSUE THREAD

**Issue by gryphus1153** [cloudflare/cloudflare-docs#6617]
### Which Cloudflare product does this pertain to?

Cloudflare One

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/install-cloudflare-cert/#git-on-windows

### Section that requires update

Git On Windows Section
Step 3 

### What needs to change?

`gc .\Cloudflare_CA.crt | ac $(git config --get http.sslcainfo)`
Using the .crt file results in a malformed Cloudflare_CA.crt file as it is in a mismatched format.

In my windows install of git, the ca-bundle.crt file specified by `http.sslcainfo` is in format of
```
-----BEGIN CERTIFICATE-----
<cert contents>...
-----END CERTIFICATE-----
```

This is the same format of cert as specified in the Cloudflare_CA.pem download.

The command needs to be changed as using the Cloudflare_CA.crt results in a malformed ca-bundle.crt file

### How should it change?

The command should be change to refer to the .pem file instead
`gc .\Cloudflare_CA.pem | ac $(git config --get http.sslcainfo)`

**Comment by ranbel** [comment]
Thanks for the feedback! We have updated the docs.
