### ISSUE TITLE
No mention of Hugo Extended version

### ISSUE THREAD

**Issue by rterakedis** [cloudflare/cloudflare-docs#6630]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

- https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/platform/build-configuration.md

### Section that requires update

Language Support and Tools

### What needs to change?

In the Tools table, the row for _hugo_ mentions the ability to choose a specific version by using the HUGO_VERSION environment variable.   However, there are two versions of the hugo cli --> hugo, and hugo extended.    Some themes make use of sass/scss, which requires the use of the hugo extended binary to build correctly.

### How should it change?

Please include any environment variables required to force the Pages build configuration to leverage the extended version of the hugo binary.

### Additional information

Refer to the "Assets" section of each release:   https://github.com/gohugoio/hugo/releases/tag/v0.105.0

**Comment by jbergstroem** [comment]
I wonder, would there be any drawbacks to cloudflare using the extended version of Hugo for all builds? If not, coupled with improved documentation it seems like the best outcome.

**Comment by eih64225** [comment]
> I wonder, would there be any drawbacks to cloudflare using the extended version of Hugo for all builds? If not, coupled with improved documentation it seems like the best outcome.

No. In fact, Hugo is even recommending the extended version as the default! The other one is retained or some binaries that the extended version is not available for (usually do to post processing).

**Comment by WalshyDev** [comment]
Hey,

We're working on adding Hugo Extended in v2 of the build image (https://github.com/cloudflare/pages-build-image/discussions/1). When we do, we will make sure to call it out in the docs.

For now, closing this as there's no documentation work to do. Please show your support on the above issue :)

**Comment by chromer030** [comment]
@WalshyDev , Hey, any news on Hugo Extended in v2 ?
Maybe a Environment variable ?

**Comment by edeca** [comment]
I found this thread whilst trying to fix a related issue. The extended version is now used by default, as seen in the logs:

```
16:12:08.466 | hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
```

If you need a specific version of Hugo then set the environment variable. For example setting `HUGO_VERSION` to `0.124.0` will build with the specific version of Hugo extended:

```
16:16:47.368 | Detected the following tools from environment: hugo@extended_0.124.0
16:16:47.368 | Installing hugo extended_0.124.0
```

Documentation about setting this variable is available [here](https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site/#use-a-specific-or-newer-hugo-version).

**Comment by rterakedis** [comment]
I read a thread in the Cloudflare discord that said to use a build variable, `HUGO_VERSION`, and set it to something like this:  `extended_x.xxx.x` (whatever version you need)

**Comment by robinp** [comment]
> I read a thread in the Cloudflare discord that said to use a build variable, `HUGO_VERSION`, and set it to something like this: `extended_x.xxx.x` (whatever version you need)

As of 2025 January, specifying `extended_` prefix leads to error, but using the plain version will pull extended anyway according to build logs.

**Comment by turing0** [comment]
> I read a thread in the Cloudflare discord that said to use a build variable, `HUGO_VERSION`, and set it to something like this: `extended_x.xxx.x` (whatever version you need)

Thanks, it worked!

**Comment by mkantem** [comment]
I am setting the environment variable `HUGO_VERSION` to `0.146.4` but it seems that no matter what, cf is building with hugo `v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended.` 

I have tried `extended_x.xxx.x`.  How to get around this ?
