### ISSUE TITLE
Storage Pricing Clarification

### ISSUE THREAD

**Issue by garretcharp** [cloudflare/cloudflare-docs#6648]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/platform/pricing (KV & DO)
- https://developers.cloudflare.com/r2/platform/pricing

### Section that requires update

Storage pricing

### What needs to change?

Would be helpful to clarify how exactly storage is metered to be charged

### How should it change?

It should list any minimum storage charges if any
Should show any rounding done to storage time if any (i.e. rounded up to the nearest second/hour etc)

### Additional information

Not sure how true this is but what I have heard is that the storage is calculated by the peak amount of storage every day, it would be helpful to know exactly how the final calculation is made.

**Comment by KimJ15** [comment]
Hi there - Check out https://www.cloudflare.com/plans/developer-platform/ for more information about pricing.
