### ISSUE TITLE
Website not indexed

### ISSUE THREAD

**Issue by Onebested** [cloudflare/cloudflare-docs#6656]
### Example URL(s)

www.onebested.cc

### Actual Behavior

Nothing is displayed despite having created my site with google

### Expected Behavior

Display different elements placed on google site manager

**Comment by Cherry** [comment]
This repo is for the Cloudflare docs. If you're having issues with your own website, you'll find better assistance on the [Community ](https://community.cloudflare.com/) or [Discord](https://discord.gg/cloudflaredev).
