### ISSUE TITLE
Running argo tunnel only with JSON credentials file (no cert.pem file)

### ISSUE THREAD

**Issue by JanSchuerlein** [cloudflare/cloudflare-docs#669]
**Problem:** 

In some cases you want to share your JSON credentials file to another user or another machine, without full authenticating using the cloudflared tunnel login command.

In this case, you can use the JSON credentials file for only the tunnel. 

Executing a tunnel run command with the cloudflared service from terminal with only the tunnel JSON authentication file and a missing cert.pem will however not work.

**Error:**

INF Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared] originCertPath=
2:59PM ERR You need to specify the origin certificate path with --origincert option, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/arguments/ for more information. originCertPath=
2:59PM ERR Couldn't start tunnel error="Error getting origin cert: client didn't specify origincert path when running from terminal"

_____

**The documentation states**

"create a tunnel via cloudflared tunnel create this generates a JSON credentials file. That file can be distributed to other users (who do not have the cert.pem) and they will (only) be able to start connections to serve that tunnel origin."

"If you have deleted the cert.pem file, you must specify the UUID instead of the name.

cloudflared tunnel --config path/config.yaml run <UUID>"

**However, this will still not work.**

You need to link to an empty cert.pem file or create one at the default location with random content, then the command will execute fine. 

If you try to link to a none-existing file, the following error will occur:

**ERR Couldn't start tunnel error="Error getting origin cert: cannot read / to load origin certificate"**

**Solution:**

- This problem should be explained or corrected in the documentation/faq.
- Optional: Implement the option to run the cloudflared tunnel run command without a cert.pem file when only using a JSON credentials file

__

**Links to documentation:** 

- [1](https://github.com/cloudflare/cloudflare-docs/blob/production/products/argo-tunnel/src/content/faq/index.md)
- [2](https://developers.cloudflare.com/argo-tunnel/faq)

**Comment by abracchi-tw** [comment]
Hi! Thanks for raising this. We've updated how to run this as a service without the `cert.pem` [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service). We've also published a [tutorial](https://developers.cloudflare.com/cloudflare-one/tutorials/credentials-only) you could be interested in. 
Hope this helps.

**Comment by kbroughton** [comment]
"We've updated how to run this as a service without the cert.pem here https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service. 
We've also published a tutorial you could be interested in. https://developers.cloudflare.com/cloudflare-one/tutorials/credentials-only"

The credentials-only tutorial is closer to what @JanSchuerlein was asking for. However, neither doc mentions the error message (so searching google on error message won't bring you here) or using an empty file to eliminate the warning.

It seems to me like a really bad idea to have the official documentation not mention the security risk of leaving the cert.pem on the origin server. I bet that means that more than half do leave cert.pem around on all their tunneled hosts, which would give an attacker full admin to the CF Zone a.k.a game over.

The [official docs](https://developers.cloudflare.com/cloudflare-one/tutorials/rdp#authenticate-cloudflared) don't even mention the "credentials-only" tutorial, and I googled for days and never hit that page. You really need the official docs to point to "credentials-only" as necessary hardening for production, or just replace the existing tutorial with a credentials-only version. I also hit a problem that `cloudflared login` on the host did not present an SSO option for logging into CF, only username/password, so a guide that specifies 
* cloudflared login AND tunnel create on the CF admin laptop
* transfer credentials.json
would be more secure and avoid this problem of no SSO on `cloudflared login`.

Also, the docs don't indicate if running the tunnel with an empty cert.pem (to suppress warning) or without that will create an encrypted tunnel or not. It would be nice to be assured that cloudflared does find a cert somewhere and creates encrypted traffic regardless of whether the real cert.pem is there or not.

Finally, the official docs for creating the RDP tunnel don't mention that any public ingress should be closed off after the tunnel is established to avoid attackers bypassing CF by using the IP. It might be a common pattern for AWS admins to create a host with public IP temporarily protected by only a strong RDP password open to 0.0.0.0/0, or a large CIDR and weak password and think at the end of the tutorial they have CF + identity provider protections. But that's only true if the admin removes direct access (ingress) to the public IP after tunnel setup.

**Comment by valkmit** [comment]
The fix mentioned in this issue by the OP

> You need to link to an empty cert.pem file or create one at the default location with random content, then the command will execute fine.

no longer applies. I've set the environment variable `TUNNEL_ORIGIN_CERT=/dev/null` but get the following error

>  Error decoding origin cert: Cannot decode empty certificate

And of course, the same error message as OP if cert.pem does not exist.

Edit: please ignore, I realized I created my `{uuid}.json` credentials file secret incorrectly. Resolving that fixed the problem.
