### ISSUE TITLE
[Pages] Add additional language support

### ISSUE THREAD

**Issue by neynah** [cloudflare/cloudflare-docs#673]
@1000hz noticed that the section on Language support and tools [Language support and tools](https://pages.cloudflare-docs.workers.dev/pages/platform/build-configuration#language-support-and-tools) is missing  some languages. From what I can tell it looks like we're missing Go, Swift, and Rust.

cc @signalnerve

**Comment by kristianfreeman** [comment]
Closing this from #848. Rust and Swift aren't installed by default, so I've added a new ticket to document that and _how_ to install them: #849
