### ISSUE TITLE
Request Header Format

### ISSUE THREAD

**Issue by Naidile-P-N** [cloudflare/cloudflare-docs#6731]
### Which Cloudflare product does this pertain to?

Rules

### Existing documentation URL(s)

https://developers.cloudflare.com/rules/transform/request-header-modification/reference/header-format/

### Section that requires update

Alphanumeric characters: a-z and A-Z

### What needs to change?

Below section where it says alphanumeric but has only a-z and A-Z and doesn't specify numbers 

### How should it change?

It should say 0-9, a-z and A-Z

### Additional information

Please let me know, will raise a PR for the same

**Comment by pedrosousa** [comment]
Thank you for the heads-up! I've created PR #6732 to fix this.
