### ISSUE TITLE
Analytics Engine limits

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/cloudflare-docs#6748]
### Which Cloudflare product does this pertain to?

Analytics

### Existing documentation URL(s)

https://developers.cloudflare.com/analytics/analytics-engine/

### Section that requires update

We should add a new limits page and note down the 25 writes per request, 20 blobs/doubles, max size of 5120 bytes, etc.

### What needs to change?

Limits are not currently explained, we need to do that.

### How should it change?

Add a limits section for developers/teams to refer to.

**Comment by angelampcosta** [comment]
@WalshyDev Thank you for bringing this up. We'll follow up on this issue with a ticket.
