### ISSUE TITLE
Toml: Source of truth—copy update

### ISSUE THREAD

**Issue by londonzhang** [cloudflare/cloudflare-docs#6786]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth

### Section that requires update

It is a recommended best practice to treat wrangler.toml as a source of truth for your Worker configuration, **and avoid making changes via the Cloudflare dashboard**. This allows you to treat wrangler.toml as a form of Infrastructure as Code.

### What needs to change?

**and avoid making changes via the Cloudflare dashboard**

Something along the lines of **Changes can be made in the dash, but the wrangler.toml file needs to stay in sync.**

### How should it change?

Dashboard recently added Wrangler recommended snippets, it informs users to update their .toml file after they make changes. This will also help users projects stay in sync.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/18485116/203146884-27d92e62-c047-4656-9d2f-a980c510d1d6.png">

### Additional information

<img width="795" alt="image" src="https://user-images.githubusercontent.com/18485116/203145876-949430d6-4f2b-4f86-9dd5-93a6641947c3.png">

**Comment by penalosa** [comment]
How about:
> We recommend treating your `wrangler.toml` file as the source of truth for your Worker configuration, and to avoid making changes to your Worker via the Cloudflare dashboard. If you need to make changes to your Worker from the Cloudflare dashboard, it will generate a TOML snippet for you to copy into your `wrangler.toml` file, which will help ensure your `wrangler.toml` file is always up to date.

**Comment by londonzhang** [comment]
If we can remove "and to avoid making changes to your Worker via the Cloudflare dashboard." This can still come off a bit alerting.

**Comment by penalosa** [comment]
I'm not sure—the _intention_ is to be alerting (we also have similar warnings on the dashboard)

**Comment by JacobMGEvans** [comment]
> I'm not sure—the _intention_ is to be alerting (we also have similar warnings on the dashboard)

Strongly agree here.

**Comment by londonzhang** [comment]
How do we feel about

We recommend treating your wrangler.toml file as the source of truth for your Worker configuration. Modifying the Worker's configuration using the dashboard will generate a snippet for you to update your local wrangler.toml file. Keeping your wrangler.toml file up to date will prevent modifications made using the dashboard from being overridden.

**Comment by penalosa** [comment]
@deadlypants1973 It would be good to get some thoughts on this from your perspective:
> We recommend treating your `wrangler.toml` file as the source of truth for your Worker configuration, and to avoid making changes to your Worker via the Cloudflare dashboard if you're using Wrangler. If you need to make changes to your Worker from the Cloudflare dashboard, the dashboard will generate a TOML snippet for you to copy into your `wrangler.toml` file, which will help ensure your `wrangler.toml` file is always up to date. 

I think this is what would fit best with our intention of warning people not to use the dashboard in conjunction with Wrangler. 

An alternative (which avoids the word "avoid"), is:
> We recommend treating the wrangler.toml file as the source of truth for your Worker's configuration. If you deploy the Worker using Wrangler, we suggest making configuration changes directly in the wranlger.toml file. However, if you need to make any quick changes to the configuration using the dashboard, a snippet will be provided to update the Worker's wrangler.toml file on your local machine. 

cc @cloudflare/wrangler

**Comment by londonzhang** [comment]
This looks great, Thank you Samuel!

**Comment by JacobMGEvans** [comment]
I still feel the stronger language here more accurately captures the importance and effect of what we are trying to convey.

sidenote: once the JSON support lands we will need to go everywhere and replace `wrangler.toml` with `Wrangler configuration`
