### ISSUE TITLE
Modify authenticated origin pull diagrams

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#6796]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull/explanation/

### Section that requires update

The diagrams show a TLS exchange between a client and a server, as an example.

### What needs to change?

The diagram should be relating to the feature being configured, hence show the TLS exchange between Cloud flare and the origin server.

### How should it change?

Modify diagrams to remove the notion of client (or eyeball) and refer to Cloudflare towards origin server.

**Comment by kodster28** [comment]
Heyo, @wolruf. These diagrams were lifted from the [original blog post](https://blog.cloudflare.com/protecting-the-origin-with-tls-authenticated-origin-pulls/) introducing authenticated origin pulls.

Still think they could be inaccurate (to your suggestion above), but just wanting to clarify... does that mean the diagrams in the blog are inaccurate as well?

**Comment by wolruf** [comment]
The diagrams are accurate per se but I feel they don't completely reflect the topic being discussed: eyeball < TLS > Cloudflare < TLS authentication > Origin.
The diagram depicts the generic TLS authentication, it'd be nice to map it to an actual setup involving eyeball, Cloudflare, Origin with "authenticated origin pull" active.

**Comment by kodster28** [comment]
Gotcha... is that progression something you happen to know or is that something I should follow up with the SECENG team on?

**Comment by wolruf** [comment]
I don't believe it's being investigated, I initially raised this issue here as I'm never sure between PCX and an issue.

**Comment by kodster28** [comment]
We check both typically, though PCX tickets are typically a bit easier to track and take action on.

**Comment by kodster28** [comment]
Addressed by related PR.
