### ISSUE TITLE
Add custom cert properties to Authenticated Origin Pulls

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#6798]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/origin-configuration/authenticated-origin-pull/set-up/#per-hostname--customer-certificates

### Section that requires update

Custom certificate generation

### What needs to change?

The documentation doesn't mention if the custom certificate can be self signed or have to be signed using a public CA.
The documentation doesn't mention, when working per-hostname, if the certificate Common Name needs to match the exact hostname.

### How should it change?

Need to validate the two assumptions above.

**Comment by wolruf** [comment]
I learnt that, to get this to work, the cert used for TLS Client Authentificate requires "CA:FALSE".
This isn't documented.
How to check:
openssl x509 -in cf-client.crt -text -noout | grep "CA:"
What happens if not set ? The Cloudflare API https://api.cloudflare.com/client/v4/zones/$ZONEID/origin_tls_client_auth/hostnames/certificates will respond:
{"success":false,"errors":[{"code":1412,"message":"Only leaf certificate is allowed."}],"messages":[]}

**Comment by wolruf** [comment]
We may also hint at Cloudflare Tunnel, cloudflared, being an alternative.

**Comment by wolruf** [comment]
```
[ usr_cert ]
# These extensions are added when 'ca' signs a request.
# This goes against PKIX guidelines but some CAs do it and some software
# requires this to avoid interpreting an end user certificate as a CA.

basicConstraints=CA:FALSE
```

as per:
https://github.com/openssl/openssl/blob/master/apps/openssl.cnf

**Comment by RebeccaTamachiro** [comment]
Hi Olivier. Thanks for bringing this up and for the information provided. I've added this to my backlog as PCX-7615.
Will be addressing this and other tickets re AOP as soon as I have a chance.

**Comment by RebeccaTamachiro** [comment]
Closing this one and will continue to work from the ticket referred above.
