### ISSUE TITLE
[Wrangler] Add how to update Wrangler

### ISSUE THREAD

**Issue by admah** [cloudflare/cloudflare-docs#6820]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

How to update Wrangler

### Content Location

Maybe as a top-level page under https://developers.cloudflare.com/workers/wrangler/

### Additional information

This doc should address how users can update wrangler with links to any other relevant info regarding updates. @rozenmd mentioned that users often ask for this info.

**Comment by rozenmd** [comment]
If there is a package.json in the current directory, and wrangler is in it:
- `npm upgrade wrangler --save` or `npm update wrangler --save`

If outside of a project folder (and there is no parent directory containing a package.json with wrangler in it:
- `npm update -g wrangler`

Caveat: `npx wrangler@latest` will use the latest version of Wrangler *except* in the case where there's already a Wrangler version installed in the current folder, then it'll use that version instead.

**Comment by deadlypants1973** [comment]
closed by #6874
