### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sadektouati** [cloudflare/cloudflare-docs#6825]
### Which Cloudflare product(s) does this pertain to?

API, Image Optimization

### Subject Matter

full example of URL format

### Content Location

Hi,
Why there's no complete guide with examples or tutorial about the new images feature?

**Comment by marciocloudflare** [comment]
Hi @sadektouati. https://developers.cloudflare.com/images/ has a lot of examples for API endpoints. Could you explain what you mean exactly? Thanks

**Comment by sadektouati** [comment]
> Hi @sadektouati. https://developers.cloudflare.com/images/ has a lot of examples for API endpoints. Could you explain what you mean exactly? Thanks

Most of the Cloudflare documentation assumes the reader have some level of Cloudflare products understanding, a thing that is not true.

I have a website with a lot of images, I want to use Cloudflare images as storage and CDN for my website's images.
My idea is to use "Creator Upload" and "URL Format". 
Can you point out an example where everything (not bits and pieces) is demonstrated?

**Comment by marciocloudflare** [comment]
Well, I'm sure you understand that it would be impossible to have examples for every possible use case. However, we try to have generic examples of how to use features (like here https://developers.cloudflare.com/images/cloudflare-images/upload-images/direct-creator-upload/ and here https://developers.cloudflare.com/images/cloudflare-images/upload-images/upload-via-url/).  We also have tutorial that shows how to integrate Cloudflare Images with a website here https://developers.cloudflare.com/images/cloudflare-images/tutorials/integrate-cloudflare-images/

**Comment by marciocloudflare** [comment]
Hey @sadektouati. Happy new year. Closing this, but feel free to reopen with a specific request. Thanks! :)
