### ISSUE TITLE
Quasar not visible in drop down

### ISSUE THREAD

**Issue by moander** [cloudflare/cloudflare-docs#6845]
### Example URL(s)

- https://developers.cloudflare.com/pages/platform/build-configuration/

### Actual Behavior

Quasar (#2732) is mentioned in docs but it's not visible in dropdown on dash.cloudflare.com

<img width="716" alt="image" src="https://user-images.githubusercontent.com/380191/204016991-02879947-f16c-4c7d-a800-7d249147c4c0.png">

### Expected Behavior

Quasar should be visible in drop down

**Comment by kodster28** [comment]
@WalshyDev or @GregBrimble, this is actually a UI bug. Closing it out since we can't do anything about it in docs.
