### ISSUE TITLE
Revise for configuring short-lived certificates page

### ISSUE THREAD

**Issue by TheLegendarySpark** [cloudflare/cloudflare-docs#6849]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates#2-ensure-unix-usernames-match-user-sso-identities

### Section that requires update

2. Ensure Unix usernames match user SSO identities

### What needs to change?

The small tab describing _Advanced setup: Differing usernames_.

### How should it change?

The instructions under the section “Advanced Setup“ were imprecise, explaining how to allow users with different aliases to login as this “user“ and only allowing SSO users with their username to authenticate into Linux.; thus, redirecting me to the authentication page for browser SSH. The last method (_Allow all users_) created to a fatal error as shown below.

```
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-11-27 07:28:32 CET; 6s ago
       Docs: man:sshd(8)
             man:sshd_config(5)
    Process: 5187 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=255/EXCEPTION)
```

### Additional information

For instance, if I follow the first method _Username matches a different email_, it wouldn't allow me to use a different email alias name (e.g. `vim@myxyz.domain`) to sign in as `linuxuser` on my Linux server.

These were the lines I added onto the file `/etc/ssh/sshd_config`:
```
Match user 'linuxserver'
  AuthorizedPrincipalsCommand echo 'vim'
  AuthorizedPrincipalsCommandUser nobody
```

Aside from this current issue, I wasn't sure whether I was using the correct Linux distribution, _Ubuntu 20.04 LTS_ or the right OpenBSD version.

--
This issue follows up with pr #6589

**Comment by ranbel** [comment]
@itzoey Could you take a look at this issue?

**Comment by itzoey** [comment]
I can reproduce the crash from the options including `AuthorizedPrincipalsCommand bash -c "echo '%t %k' | ssh-keygen -L -f - | grep -A1 Principals"`, this one is an easy fix, we need to specify an absolute path to `bash` (`AuthorizedPrincipalsCommand /bin/bash ...`). I'll make a PR to fix that shortly.


---
The example config options you've given won't work, because you typoed the Linux username. Try these:

```
Match user 'linuxuser'
  AuthorizedPrincipalsCommand echo 'vim'
  AuthorizedPrincipalsCommandUser nobody
```

This should allow `vim@mydomain.xyz` to connect with `ssh linuxuser@linuxserver` (assuming they configured their SSH client correctly)

Did you also save the generated access SSH CA to the server, and include the `TrustedUserCAKeys` config line pointing to the saved file (step 4-5 on the page you linked)? That's necessary for this to work.

**Comment by TheLegendarySpark** [comment]
Yes, I already followed the necessary steps to SSH with short live certs.
However, I noticed that ***@***.***` would only work to SSH
instead of the aliases like `vim`.

**Comment by Blackbeetle447** [comment]
My authenticator is the problem right now
Sorry I’m not ignoring any one so I just wanted to make that clear 



Sent from App for Gmail


Monday, December 5, 2565 BE, 15:07 -0800 from ***@***.***  ***@***.***>:
>Yes, I already followed the necessary steps to SSH with short live certs.
>However, I noticed that ***@***.***` would only work to SSH
>instead of the aliases like `vim`.
>

**Comment by TheLegendarySpark** [comment]
Yes,, ideally this wouldn't work.

**Comment by TheLegendarySpark** [comment]
Follow up?

**Comment by itzoey** [comment]
Sorry about the delay, I've gone ahead and made the PR to fix the AuthorizedPrincipalsCommand examples (#7685).

@TheLegendarySpark Did you try the updated example config I provided? You specified the server's name instead of the user's name in the Match block.

Your additions to `/etc/ssh/sshd_config` should look like:
```
TrustedUserCAKeys /etc/ssh/ca.pub
```
and:
```
Match user 'linuxuser'
  AuthorizedPrincipalsCommand /bin/echo 'vim'
  AuthorizedPrincipalsCommandUser nobody
```

**Comment by TheLegendarySpark** [comment]
> /etc/ssh/ca.pub

I added those too. It iddn't work.

**Comment by TheLegendarySpark** [comment]
> Sorry about the delay, I've gone ahead and made the PR to fix the AuthorizedPrincipalsCommand examples (#7685).
> 
> @TheLegendarySpark Did you try the updated example config I provided? You specified the server's name instead of the user's name in the Match block.
> 
> Your additions to `/etc/ssh/sshd_config` should look like:
> 
> ```
> TrustedUserCAKeys /etc/ssh/ca.pub
> ```
> 
> and:
> 
> ```
> Match user 'linuxuser'
>   AuthorizedPrincipalsCommand /bin/echo 'vim'
>   AuthorizedPrincipalsCommandUser nobody
> ```

I tried, but it didn't work. Is it actually working on your end? Maybe my OpenBSD isn't compatible!?!?

**Comment by glennschler** [comment]
I have been fighting this same issue. Thanks, the `/bin/echo` detail was helpful. Though, now I realize the instructions referenced by this issue are still incomplete. At step 7 it should explain that the ssh client must set the User to be 'linuxuser', along with the understanding that the short-term certificate which is created by client `exec 'cloudflared access'`  sets the Principal to 'vim' (the names from your above example). With those two details, the sshd_config on server will use the match command explained in the instructions to correctly match for valid authentication.

If following your previous example for matching the linux userid named 'linuxuser', but authenticating at the client through `cloudflared` with 'vim@vm.example.com' 

* Step 7: https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates#7-connect-as-a-user
  * Should add this detail, or explain to add `User 'linuxuser'` to the ssh client config
  ```ssh linuxuser@vm.example.com``` 
  * Also a tip on how to confirm the short term certificate has the Principal set to 'vim':
  ```
  # test this after attempting the ssh client connect.
  ssh-keygen -L -f  ~/.cloudflared/vm.example.com-cf_key-cert.pub
  ```

To debug the server, first add LogLevel DEBUG3 to top of /etc/ssh/ssh_config,
 then command `log  stream --level debug  2>&1 | tee /tmp/logs.out | grep -i sshd`

This lets you confirm this section of log with a working connect:
```
2023-02-16 15:24:32.860569-0500   Debug  0x0   0    sshd: debug3: (command):1: matched principal "vim"
2023-02-16 15:24:32.860704-0500   Debug  0x0   0    sshd: debug2: process_principals: (command): processed 1/1 lines
2023-02-16 15:24:32.860779-0500   Debug  0x0   0    sshd: debug1: restore_uid: 0/0
2023-02-16 15:24:32.860839-0500   Debug  0x0   0    sshd: debug3: found certificate option "permit-agent-forwarding" len 0
2023-02-16 15:24:32.860861-0500    Debug  0x0   0    sshd: debug3: found certificate option "permit-port-forwarding" len 0
2023-02-16 15:24:32.860881-0500    Debug  0x0   0    sshd: debug3: found certificate option "permit-pty" len 0
2023-02-16 15:24:32.860898-0500   Debug  0x0   0    sshd: debug3: found certificate option "permit-user-rc" len 0
2023-02-16 15:24:32.860917-0500   Debug   0x0    0    sshd: debug1: cert: key options: agent-forwarding port-forwarding pty user-rc
2023-02-16 15:24:32.860938-0500   Debug  0x0   0    sshd: debug1: principals: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
2023-02-16 15:24:32.860958-0500 0xe2811f   Info  0x0  0    sshd: Accepted certificate ID "..." (serial ...) signed by ECDSA CA SHA256:... via /etc/ssh/ca.pub
```

* NEXT, the original issue I was having is in regards to the final section of this document to connect through a browser based terminal. Now that I see how `cloudflared access` handles short lived certs, I understand why they might not work in the Cloudflare Browser Based Terminal. There is no option in the browser based terminal for generating and sending short lived certificates, or at least not when attempting _Advanced setup: Differing usernames_. There is only one option to connect with a password, or second option to enter a private key.
https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates#connect-through-a-browser-based-terminal
  * Should I create a new issue or is this already known?

**Comment by itzoey** [comment]
> I tried, but it didn't work. Is it actually working on your end?

Yes, I've tested it just now, and it works correctly on my end.

> At step 7 it should explain that the ssh client must set the User to be 'linuxuser', along with the understanding that the short-term certificate which is created by client exec 'cloudflared access' sets the Principal to 'vim' (the names from your above example).

Good catch! I was doing this subconsciously, so I didn't think to mention it as a possible issue. I'll add this into the docs.

@TheLegendarySpark Have you tried `ssh linuxuser@linuxserver` (specifying the username)? Did you also configure your SSH client locally to generate the short-lived certs? (as described in [Step 7: Connect as a user: Configure your client SSH config](https://developers.cloudflare.com/cloudflare-one/identity/users/short-lived-certificates#configure-your-client-ssh-config))

> There is no option in the browser based terminal for generating and sending short lived certificates [...] Should I create a new issue or is this already known?

This issue is known, though I don't think it has any sort of priority currently. There's a slightly janky way to use short lived certs with the in-browser terminal, but it has to work on the first try, and the IDP username and SSH username have to match; otherwise it will dump you at the selection dialog (as you've seen), with no short-lived certs option.

**Comment by TheLegendarySpark** [comment]
Oh, that would've worked if I was on Visual Studio Code or any other SSH
client. I only tried to access through Browser SSH.

**Comment by glennschler** [comment]
> > At step 7 it should explain that the ssh client must set the User to be 'linuxuser', along with the understanding that the short-term certificate which is created by client exec 'cloudflared access' sets the Principal to 'vim' (the names from your above example).
> 
> Good catch! I was doing this subconsciously, so I didn't think to mention it as a possible issue. I'll add this into the docs.
> 
Yes, now that I think back, it should have been obvious to set the User to the linuxuser account on the server, like any other normal ssh connection attempt. Because this was a _Advanced setup: Differing usernames_ case it was less obvious, so I was setting User to the differing Principal name.
