### ISSUE TITLE
[Wrangler] Explicitly call out Route config warning

### ISSUE THREAD

**Issue by admah** [cloudflare/cloudflare-docs#6862]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/wrangler/configuration/
- https://developers.cloudflare.com/workers/wrangler/configuration/#source-of-truth

### Section that requires update

Source of Truth

### What needs to change?

I would like the following warning to be more explicit:

> If you change your routes in the dashboard, Wrangler will override them in the next deploy with the routes you have set in your wrangler.toml. Currently, there is no way to disable this behaviour.

### How should it change?

I'm not sure if we need a new section for this or if this should be added the the [v1 migration guide](https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/). Either way, this has the potential to cause issues and should be more visible.

**Comment by KianNH** [comment]
'Currently, there is no way to disable this behaviour.' is a little confusing since it's documented that you can in fact disable this behaviour.

https://developers.cloudflare.com/workers/wrangler/migration/deprecations/#other-deprecated-behaviour

> To manage routes via the Cloudflare dashboard only, remove any route and routes keys from and add workers_dev = false to your wrangler.toml file.

https://github.com/cloudflare/wrangler2/issues/972#issuecomment-1125359729

**Comment by admah** [comment]
@KianNH thanks so much for that link and the added context! It seems like the text needs to be updated here with a link back to the doc you shared.
