### ISSUE TITLE
Please upgrade the Zola version supported by Cloudflare Pages.

### ISSUE THREAD

**Issue by zhiyongpeng** [cloudflare/cloudflare-docs#6904]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-zola-site/

### Section that requires update

Deploying with Cloudflare Pages：
> Currently, Cloudflare Pages only supports ZOLA_VERSION: <=0.14.0 in builds.

### What needs to change?

Due to Zola continuous updates, several features in older versions have been deprecated, please upgrade the Zola version supported by Cloudflare Page to v0.16。

> **Breaking** （from [Zola v0.16.0](https://github.com/getzola/zola/blob/master/CHANGELOG.md#0160-2022-07-16)）
Switch to pulldown-cmark anchor system rather than ours, some (very niche) edge cases are not supported anymore, you can also specify classes on headers now
Now outputs empty taxonomies instead of ignoring them
Unify all pages sorting variable names in templates to lower/higher in order to make it easy to re-use templates and it was becoming hard to come up with names to be honest

Thank you.

### How should it change?

Upgrade the zola version (to latest) in Cloudflare Pages so that Cloudflare Pages supports building and deploying zola v0.16 files.

**Comment by WalshyDev** [comment]
This will be done in the new build image version, you can see details here: https://github.com/cloudflare/pages-build-image/discussions/1

**Comment by zhiyongpeng** [comment]
I have reviewed the recently updated Cloudflare Pages docs, but there is no indication of the highest supported version of Zola in the documentation. I have found that the current version of Cloudflare Pages still does not support Zola v0.16+ version. May I know what is the version of Zola currently supported by Cloudflare Pages?
