### ISSUE TITLE
[DoH] Add documentation on how to send multiple Questions for DoH

### ISSUE THREAD

**Issue by shadyabhi** [cloudflare/cloudflare-docs#698]
Reference: https://github.com/cloudflare/cloudflare-docs/blob/production/products/1.1.1.1/src/content/dns-over-https/request-structure.md

The response payload has `Question` as an array. How to send multiple questions in the query?

**Comment by marciocloudflare** [comment]
Hi @shadyabhi. Closing this as the docs have been updated with this info. Thanks!
