### ISSUE TITLE
Email Routing API has no ability to add a custom email address

### ISSUE THREAD

**Issue by Xarex** [cloudflare/cloudflare-docs#7035]
### Which Cloudflare product does this pertain to?

API

### Existing documentation URL(s)

https://developers.cloudflare.com/email-routing/
https://developers.cloudflare.com/api/operations/email-routing-destination-addresses-create-a-destination-address

### Section that requires update

There is the ability to create a custom destination address, but no ability to create a custom email address. It needs to be added.
![Screenshot 2022-12-15 2 51 37 AM](https://user-images.githubusercontent.com/756808/207828172-5b12a604-83c1-47a5-8530-913ac9e2b733.png)

### What needs to change?

The API is incomplete.

### How should it change?

API completion: 'custemail' => $customemail, 'destemail' => $destination

### Additional information

Trying to add email forwarding and on the dashboard, I must add a custom email address and a destination email address, but the API only has the ability to add a destination email address.

**Comment by Xarex** [comment]
I think I figured it out: https://developers.cloudflare.com/api/operations/email-routing-routing-rules-create-routing-rule

**Comment by celso** [comment]
What you want is a new rule https://developers.cloudflare.com/api/operations/email-routing-routing-rules-create-routing-rule
See:

```
  "matchers": [
    {
      "field": "to",
      "type": "literal",
      "value": "test@example.com"
    }
  ]
```

**Comment by Xarex** [comment]
I haven't figured this out. I'm stuck and getting this error:

{"result":null,"success":false,"errors":[{"code":7003,"message":"Could not route to /client/v4/zones/zone_identifier/email/routing/rules, perhaps your object identifier is invalid?"}],"messages":[]}

Using the PHP version of the API.

**Comment by marciocloudflare** [comment]
Hey @Xarex. From your message it seems you didn't replace `zone_identifier` with your zone identifier.
