### ISSUE TITLE
Build command without a framework

### ISSUE THREAD

**Issue by tschaub** [cloudflare/cloudflare-docs#7040]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/build-configuration

### Section that requires update

I'm confused by this part of the documentation: https://github.com/cloudflare/cloudflare-docs/blob/39925557d8f6f12ca568ce46754d55945a0ade79/content/pages/platform/build-configuration.md?plain=1#L33

My site is built with `npm run build`, and I'm not using one of the listed frameworks.  The documentation above makes it seem like I should leave the **Build command** blank.  But I don't see another way to tell Cloudflare to run `npm run build` to build the site.

### What needs to change?

When I try to leave the framework set to "None" and the **Build command** blank (as suggested by the documentation), I get "An unknown error occurred.  Please try again later."

<img width="944" alt="image" src="https://user-images.githubusercontent.com/41094/207935813-714b8ecd-84e0-4fa6-8996-af32f562f47c.png">

### How should it change?

If the **Build command** must be filled in when the framework is set to "None," then the documentation should explain this (and ideally a form validation error message would make this clear).

If the **Build command** should be left blank when the framework is set to "None" (as is currently documented), then it could be useful to provide a bit more detail on how the site is supposed to be built.

**Comment by deadlypants1973** [comment]
Hi @tschaub , the build command can be left blank and it seems like you ran into an unusual error in the dash. Closing this out but should you have issues, please report them in the Cloudflare Dev Discord.
