### ISSUE TITLE
# in Cloudflare Access Application URL doesn't work

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudflare/cloudflare-docs#7062]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/policies/access/app-paths/

### Section that requires update

Section doesn't exist yet

### What needs to change?

When using a # in the Cloudflare Access Application URL,, e.g. app.example.com/#settings, this app matches as if the part behind the / wasn't there, so on app.example.com alone.

### How should it change?

Either document clearly that a # in the application URL is not supported or correct the backend programming to support a # in the app URL.
Maybe the #settings is currently parsed as a comment in the code and therefore ignored.

I know however of some apps that use this URL scheme in production so supporting it in CF One would be great.

**Comment by KianNH** [comment]
`#` in URLs are not sent to the server - it is impossible for Cloudflare to have any knowledge of them.

https://datatracker.ietf.org/doc/html/rfc3986#section-3.5

**Comment by etec-masterofsynapse** [comment]
> `#` in URLs are not sent to the server - it is impossible for Cloudflare to have any knowledge of them.
> 
> https://datatracker.ietf.org/doc/html/rfc3986#section-3.5

In that case, how do apps like Uptime Kuma, Zammad or simple anchor links utilizing browsers using # in their URLs work?

**Comment by KianNH** [comment]
Anchor links are processed by the browser - this is not a server-side thing.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page

**Comment by etec-masterofsynapse** [comment]
> Anchor links are processed by the browser - this is not a server-side thing.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page

Still, my other statements still stand.

**Comment by ranbel** [comment]
@kennyj42 wdyt?

**Comment by jroyal** [comment]
As @KianNH mentioned we won't be able to truly support them because we don't get the # in the request. @ranbel Lets add some documentation to point that we won't support apps domains like `example.com/#settings`.

**Comment by ranbel** [comment]
#7666
