### ISSUE TITLE
FireWall Rule and Bot Fight Management 

### ISSUE THREAD

**Issue by Khnaz35** [cloudflare/cloudflare-docs#7074]
### Example URL(s)

I have whitelisted the user agent in CF firewall setting https://prnt.sc/BIKwwkNJfF0z (ALLOW) and place it on top (https://prnt.sc/uafhIvQztD9r) 
But still when trying to access my website via same user agent It is being block by BOT FIGHT SERVICE.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/43812103/208721987-c3efe0cc-7c3e-40b2-bec0-c495950dd769.png">

### Actual Behavior

I have whitelisted the user agent in CF firewall setting https://prnt.sc/BIKwwkNJfF0z (ALLOW) and place it on top (https://prnt.sc/uafhIvQztD9r) 
But still when trying to access my website via same user agent It is being block by BOT FIGHT SERVICE.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/43812103/208721987-c3efe0cc-7c3e-40b2-bec0-c495950dd769.png">

### Expected Behavior

User agent should be allow to access the website. 
<img width="194" alt="image" src="https://user-images.githubusercontent.com/43812103/208722533-35a742ba-b7aa-4397-8908-d3d7a47eebde.png">

### Additional information

This doesn't make sense at all. Since WAF rule says ALLOW it should be ALLOW!!!
How can I keep the BOT FIGHT MOD ON as well as allow specific user agent to access my website?

**Comment by pedrosousa** [comment]
Hello @Khnaz35,

In this repository we only handle issues with the documentation. Having said that, I'll try to provide some information about your specific situation. For additional assistance you should contact Cloudflare Support or, if you are on a Free plan, reach out to the [Cloudflare Community](https://community.cloudflare.com/tag/firewall).

As stated in the Firewall Rules documentation ([Actions](https://developers.cloudflare.com/firewall/cf-firewall-rules/actions/) page):

> The scope of the _Allow_ action is limited to firewall rules; matching requests are **not** exempt from action by other Cloudflare security products such as Bot Fight Mode, IP Access Rules, and Managed Rulesets.

The ability to customize the behavior of bot fight mode depends on your Cloudflare plan:
* Free plans cannot customize bot protection (you can only enable or disable Bot Fight Mode). 
* Customers on Pro/Business plans can customize protection for various types of traffic (defining how to handle verified bots, whether to perform static resource protection or not, and whether to enable JavaScript detections or not). 
* Enterprise customers with Bot Management can specify which traffic to protect from bots, and they can use specific [bot-related fields](https://developers.cloudflare.com/ruleset-engine/rules-language/fields/#dynamic-fields) in their Firewall Rules to include/exclude bots from those rules.

For more information on the different bot-related capabilities of each plan, refer to [Plans](https://developers.cloudflare.com/bots/plans/free/) in the Bots documentation.
