### ISSUE TITLE
Highlight data consistency model for R2 S3 API

### ISSUE THREAD

**Issue by kev-ac** [cloudflare/cloudflare-docs#7091]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/data-access/s3-api/

### Section that requires update

Maybe: https://developers.cloudflare.com/r2/data-access/s3-api/api/

### What needs to change?

There was a question / uncertainty about the data consistency model of R2 on Discord. The current state of S3 API documentation does not reflect its strongly consistent nature. 

As AWS S3 was not strongly consistent [until 2020](https://aws.amazon.com/de/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/) I can understand that someone can be uncertain about R2.

The only other place (I know of) which references it is the [beta announcement post](https://blog.cloudflare.com/r2-open-beta/) on the blog.

### How should it change?

The R2 S3 API documentation page should, like the [Workers API](https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-reference/#bucket-method-definitions), reflect the data consistency model of R2.
I would suggest to add a new section to the S3 API Compatibility page which describes the model. 

### Additional information

Discord topic: 
- https://discord.com/channels/595317990191398933/940663374377783388/1035560497036148877
- https://discord.com/channels/595317990191398933/940663374377783388/1055431286380044289

**Comment by elithrar** [comment]
@dcpena I have a PR in flight for this I’m about to push up for review.
