### ISSUE TITLE
[Railgun] Wrong railgun installation guide

### ISSUE THREAD

**Issue by jocel1** [cloudflare/cloudflare-docs#7092]
### Which Cloudflare product does this pertain to?

Railgun

### Existing documentation URL(s)

https://developers.cloudflare.com/railgun/user-guide/set-up/installation-overview/

### Section that requires update

The package repository section has a link to the cloudflared package installation.

### What needs to change?

The package repository link to the cloudflared package installation. Therefore after loading the cloudflared package repository the railgun-stable package doesn't exist anywhere.
The section "Other users will need to install the cloudflare-release RPM as described on the repository home page" is not relevant as well.
With the current documentation, I've no idea how to install railgun

### How should it change?

Put the right repository link

**Comment by cicku** [comment]
Railgun is no longer maintained. You should migrate to Cloudflare Tunnel.

**Comment by jocel1** [comment]
Well that's fine for me, but then Railgun should not be put on the Speed / Optimization page anymore, and the Railgun documentation should be updated so we stop losing time trying to use it :)

**Comment by marciocloudflare** [comment]
Closing this as there are no further actions here. Thanks!
