### ISSUE TITLE
Clarification on what `remoteip` does/why it would be needed.

### ISSUE THREAD

**Issue by alii** [cloudflare/cloudflare-docs#7114]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/turnstile/get-started/_index.md

### Section that requires update

The table under the heading "Accepted parameters"

### What needs to change?

The docs specify that `remoteip` is an optional param when verifying a token, but don't specify why it exists or what it can be used for. Does it benefit us to send it? Will it increase bot detection rate? Etc 

### How should it change?

Perhaps a short explanation in a paragraph afterwards clarifying what remoteip is used for and why it would benefit us to send it

**Comment by patriciasantaana** [comment]
Hi @alii ! Thank you for the feedback about how we can make improvements with [developers.cloudflare.com](http://developers.cloudflare.com/) documentation. I'm closing this as a duplicate of work already in-progress.

**Comment by alii** [comment]
Cool thank you!
