### ISSUE TITLE
Workers Quickstarts recommend deprecated cli command, deprecation notice link reported from cli broken

### ISSUE THREAD

**Issue by valgaze** [cloudflare/cloudflare-docs#7129]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/get-started/quickstarts/
https://developers.cloudflare.com/workers/wrangler/deprecations/#generate
https://github.com/cloudflare/wrangler2

### Section that requires update

Quickstarts

### What needs to change?

Quickstarts on main site uses deprecated `generate` command to scaffold projects

### How should it change?

Quickstarts should use modern wrangler commands

### Additional information

Deprecation url returned from **[wrangler CLI](https://github.com/cloudflare/wrangler2)** using commands from Quickstart docs is broken

CLI:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1396559/210151812-770636c4-c650-446e-a44b-26034553e0e2.png">

Link: https://developers.cloudflare.com/workers/wrangler/deprecations/#generate

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/1396559/210151833-73c454ed-d793-4bc8-b8b7-70fa081d7565.png">

**Comment by deadlypants1973** [comment]
This is being fixed by #7728

**Comment by deadlypants1973** [comment]
Hi @valgaze , this error was probably encountered when `generate` was temporarily deprecated. We have since restored the command and updated the quickstarts page to correct instructions following #7728.
