### ISSUE TITLE
Enabling durable objects is unclear

### ISSUE THREAD

**Issue by AngelOnFira** [cloudflare/cloudflare-docs#7133]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/learning/using-durable-objects/#using-durable-objects-1

### Section that requires update

Using Durable Objects

### What needs to change?

The sentence

> To start, enable Durable Objects for your account by logging in to [the Cloudflare dashboard](https://dash.cloudflare.com/) Workers > Durable Objects.

Seems to be unclear. There isn't a section under `Workers` for `Durable Objects`, and instead I found it inside a worker.

### How should it change?

It would be good to know what I'm exactly looking for, or where it might not be. For example, I'm not sure if it's visible if you aren't in a paid worker plan, though I did the upgrade in hopes it would show it for me.

**Comment by sh471** [comment]
drwxr-xr-x 1
