### ISSUE TITLE
New project docs

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#7148]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://circleci.com/developer/orbs/orb/circleci/browser-tools

### Section that requires update

None at this time

### What needs to change?

Documents need documentation.

### How should it change?

Projects are interesting.

**Comment by kodster28** [comment]
Howdy @Timoteo714, can you elaborate more on what you're expecting here?

The existing issue (just linking to another webpage), doesn't really give us enough context for anything actionable.

Feel free to re-open if you can provide more context.
