### ISSUE TITLE
[R2] Clearly explain allowed use-cases for R2 (Public Access)

### ISSUE THREAD

**Issue by kev-ac** [cloudflare/cloudflare-docs#7186]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Allowed use-cases for R2

### Content Location

https://developers.cloudflare.com/r2/data-access/public-buckets/

### Additional information

Public Access features for R2 allow distribution of Non-HTML content which is usually prohibited in the ToS.

There are regular uncertainties about whether one can deliver for example video content with R2 because there is no clear information about this being allowed in the documentation and the ToS documents are very hard to understand for the average person.

**Comment by KianNH** [comment]
For anyone coming across this in the interim:

https://www.cloudflare.com/en-gb/supplemental-terms/

> (iv) Workers KV, Durable Objects, and R2, storage offerings used to serve HTML and non-HTML content

https://twitter.com/Aly_Cabral/status/1571917591228325888

> Our developer platform TOS is meant to be inclusive of the cache api, and cache + our developer products.
