### ISSUE TITLE
Remove recommendation to use Deployments over Environments

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#7187]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/environments/

### Section that requires update

> We recommend using [Deployments](https://developers.cloudflare.com/workers/platform/deployments) in place of Environments. Deployments give you a powerful audit log of changes to your application, and will soon include integrated rollbacks and automated deployment.

### What needs to change?

Deployments aren't a substitute for Environments today. You can't separate bindings, env vars, etc. with them, and pointing people to Deployments is leading to confusion such as on this thread:

https://community.cloudflare.com/t/environments-vs-deployments/451036?u=cherryjimbo

I understand the intent is that they'll get there, but pointing people to use them early without the same functionality is only going to result in user confusion.

### How should it change?

I would recommend that this snippet be removed until Deployments are in a state that they can replicate the functionality of Environments.

**Comment by admah** [comment]
@Cherry thanks for pointing this out. I will take a look at this in order to remove confusion. What you said in the community thread is spot on. Thanks!
