### ISSUE TITLE
Change tunnel service's hostname to an actual IP address to be more intuitive

### ISSUE THREAD

**Issue by harsath** [cloudflare/cloudflare-docs#7208]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/ssh/#1-connect-the-server-to-cloudflare-1

### Section that requires update

Point 4 of "1. Connect the server to Cloudflare" section.

### What needs to change?

Change `localhost` to an IP address.

### How should it change?

Sorry if I am mistaken, but when adding a service tunnel (SSH, for example), I should specify my server's IP address, not `localhost`. I entered `localhost` on the tunnel configuration page and couldn't log in (I guess I was trying to log into one of CloudFlare's front-end servers by having `localhost` in there). Then, I tried entering my server's IP address, which worked as expected. It took me a while to figure out what was going on. I find it very confusing to say `localhost` when in reality, we should be entering the server's IP address.

### Additional information

The same goes for the tunnel configuration page, it's very confusing to say `localhost`. Here's my screenshot of tunnel configuration: 

![Screenshot 2023-01-10 at 4 15 03 PM](https://user-images.githubusercontent.com/30565388/211664619-94c95eef-ec1c-4e52-acda-c678988fa223.png)
the

**Comment by etec-masterofsynapse** [comment]
@harsath localhost points to the server the specific tunnel instance runs on.
If you are running the tunnel on a separate device and then want to access a different server via SSH, you of course have to input an IP address or an FQDN to reach that other server.

Otherwise, when running the tunnel on the same device as the service you want to access, localhost is completely fine.

**Comment by ranbel** [comment]
Hi , thanks for the feedback! Does this PR address the issue? #7634
