### ISSUE TITLE
GraphQL API CORS

### ISSUE THREAD

**Issue by mattlarson29** [cloudflare/cloudflare-docs#721]
Greetings.

The demo code here: https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics
fails with a CORS validation error:

`Access to fetch at 'https://api.cloudflare.com/client/v4/graphql' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by soheiokamoto** [comment]
CC: @twalwyn

**Comment by crwaters16** [comment]
Addressing in https://github.com/cloudflare/cloudflare-docs/pull/1322

**Comment by H1-N1** [comment]
2023 same issue 
graph api is bloking no same orgin request
