### ISSUE TITLE
Cloudflare Web Analytics API?

### ISSUE THREAD

**Issue by 684efs3** [cloudflare/cloudflare-docs#7237]
### Which Cloudflare product(s) does this pertain to?

Analytics

### Subject Matter

Cloudflare Web Analytics API

### Content Location

Within Cloudflare Web Analytics

### Additional information

Does Cloudflare Web Analytics have an API? If so, how do we use it? I do not see any documentation of this.

**Comment by cicku** [comment]
Already documented.

https://developers.cloudflare.com/analytics/graphql-api/
