### ISSUE TITLE
Document how `pages dev` works in conjunction with framework-provided dev server

### ISSUE THREAD

**Issue by yudai-nkt** [cloudflare/cloudflare-docs#7240]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/functions/local-development/

### Section that requires update

The part describing how to use a framework-provided development command:

> If you’re using a framework, you can pass through the framework provided dev command (i.e. npm run dev) to run development and benefit from the framework hot-reloading and any special build process around it. You can do this with:
>
>```
> $ wrangler pages dev -- <command>
>```

### What needs to change?

It would be nice to explain that wrangler will proxy the port opened by `<command>` for requests that don't match any of Functions' route so we only need to visit the wrangler's port, not the framework's one, to see the pages.

I didn't notice this and kept investigating port 5173 (Vite's default) only to waste several days. The `pages dev` command indeed says "Automatically determined the proxy port to be 5173.", but I didn't quite understand how wrangler works in this case.

### How should it change?

I'm not a native English speaker, so proofreading is much appreciated.

> If you’re using a framework, you can pass through the framework provided dev command (i.e. npm run dev) to run development and benefit from the framework hot-reloading and any special build process around it. You can do this with:
>
>```
> $ wrangler pages dev -- <command>
>```
>
> Note that wrangler will proxy requests that are not Functions to a port opened by your framework and serves the static assets. So you only need to visit wrangler's port, which is 8788 by default.

### Additional information

Another reason for my mistake is probably because `pages dev` doesn't show the port it listens on. An example console ouput of `pages dev` is

``````console
$ npm start

> inkuest@0.0.0 start
> wrangler pages dev --r2=MATCH_VIDEO --d1=MATCH_DB -- vite

🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Running vite...
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
To skip, specify the proxy port with --proxy.
[proxy]:
  VITE v4.0.3  ready in 228 ms


[proxy]:   ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

Automatically determined the proxy port to be 5173.
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-01-12.

  Pass it in your terminal:
  ```
  --compatibility-date=2023-01-12
  ```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more
  information.


Compiling worker to "/var/folders/43/14qb6f816gn4sgy_cz5p1l4h0000gn/T/functionsWorker-0.02554638021329847.mjs"...
Compiled Worker successfully.
╭────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:65425/bc0a2cf4-82f0-49b0-95c3-175796905186
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
``````

whereas that of `wrangler dev` is

```console
$ npm start

> homura@0.0.0 dev
> wrangler dev src/index.ts

 ⛅️ wrangler 2.0.2 (update available 2.7.1)
-----------------------------------------------------
⬣ Listening at http://localhost:8787
╭────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn on local mode, [c] clear console, [x] to exit  │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Development command for Workers shows us `Listening at http://localhost:8787`, but Pages's command doesn't show us `Listening at http://localhost:8788`. If there were something like that, I wouldn't have made the mistake.

Of course, this is not related to this repo, so I'll open an issue for this if changing wrangler's logging is preferred over documentation improvement.

**Comment by yudai-nkt** [comment]
This issue is migrated from a conversation w/ @Skye-31 in Discord.

**Comment by CarmenPopoviciu** [comment]
thank you for reporting this @yudai-nkt and for the proposed text changes. I will take this up to the Pages team and discuss what the best course of action is. Will return with an answer here shortly
