### ISSUE TITLE
In-depth explanation of 'visits' and 'page views' in web traffic analytics

### ISSUE THREAD

**Issue by MattIPv4** [cloudflare/cloudflare-docs#7245]
### Which Cloudflare product(s) does this pertain to?

Analytics

### Subject Matter

Web Traffic Analytics: Vists/Page views

### Content Location

https://support.cloudflare.com/hc/en-us/articles/360037684251-Understanding-Cloudflare-Site-Analytics#5r6cSJB0I9QPTk65qrmf5a currently exists which very briefly mentions what visits and page views are, but in rather vague terms (the dash also has limited explanations for these both, but also rather vague).

I imagine it'd be better under https://developers.cloudflare.com/analytics/ with a new 'Web Traffic Analytics' section (not to be confused with 'Web Analytics' which is different).

### Additional information

The dashboard says that a 'Page view' is 'A page loaded in a browser.'. The linked help article says it is 'a successful HTTP response with a content-type of HTML', which is very different. Clarification on what exactly determines a page view would be much appreciated (does it look for known browser UAs, etc.?).

For 'Visits', both give a similar explanation of a user visiting the site from somewhere else, and that a visit can consist of multiple page views. Clarification on how exactly page views are grouped into a single visit would be appreciated.

**Comment by angelampcosta** [comment]
@MattIPv4 thank for your comments. We'll follow up on this with an internal ticket.

**Comment by yamanidev** [comment]
Any updates on the ticket?

Edit: they added it to their Web Analytics documentation under [High-level metrics](https://developers.cloudflare.com/analytics/web-analytics/understanding-web-analytics/high-level-metrics/) section.
