### ISSUE TITLE
Where is bulk redirects?

### ISSUE THREAD

**Issue by kangarooo** [cloudflare/cloudflare-docs#7248]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/how-to/use-bulk-redirects/
Where is bulk redirects? Doesnt exist in my panel
![image](https://user-images.githubusercontent.com/73187/212226909-3b991ceb-f07f-4086-be9e-5642c9d30cdc.png)

### Section that requires update

https://developers.cloudflare.com/pages/how-to/use-bulk-redirects/

### What needs to change?

Where is bulk redirects?

### How should it change?

Where they are or where is new place of them?

**Comment by pedrosousa** [comment]
Hi @kangarooo 
Thank you for bringing this up. In fact, the instructions in the page you linked to are outdated. You can navigate to the Bulk Redirects configuration page using one of the following methods:
a) Go to Account Home > **Bulk Redirects**.
b) After having selected a zone, go to **Rules** > **Redirect Rules** and then select **Manage Bulk Redirect Rules** — this is just an accelerator that will take you to the account-level configuration page mentioned in a).

We will update these instructions soon.
