### ISSUE TITLE
Cors config not work

### ISSUE THREAD

**Issue by MeFelixWang** [cloudflare/cloudflare-docs#7250]
### Example URL(s)

https://cdn.qingcong.tech/favicon.png

### Actual Behavior

The resources can be accessed from any website or direct link.

### Expected Behavior

The resources can only be accessed from the given domains in cors config.

### Additional information

My cors config is :
```
[
  {
    ID: undefined,
    AllowedHeaders: [ '*' ],
    AllowedMethods: [ 'GET', 'HEAD' ],
    AllowedOrigins: [ 'https://*.qingcong.tech' ],
    ExposeHeaders: undefined,
    MaxAgeSeconds: undefined
  }
]
```

**Comment by KianNH** [comment]
![image](https://user-images.githubusercontent.com/94662631/212344120-e959586e-62b7-4fec-90de-4beb60b866e1.png)

This seems to be working as expected, or are you saying no domains are working?

**Comment by MeFelixWang** [comment]
@KianNH Thanks for reply, and sorry for the bother, I made the mistake myself.
