### ISSUE TITLE
D1 docs needs little update with Pages function

### ISSUE THREAD

**Issue by shinebayar-g** [cloudflare/cloudflare-docs#7261]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/d1/get-started/ 

### Section that requires update

Getting started 

### What needs to change?

Page needs to cover how to connect with Pages functions. Currently it only mentions workers. 

### How should it change?

With Pages functions, it's possible to connect to D1 database. But D1 docs doesn't mention this.

**Comment by WalshyDev** [comment]
It is documented under Functions in the Pages docs: https://developers.cloudflare.com/pages/platform/functions/bindings/#d1-databases

**Comment by shinebayar-g** [comment]
It assumes you already have a working D1 database. And if you go to D1 docs, it makes you create a worker project, not Pages. That's where I lost.
