### ISSUE TITLE
How long will be the domain data stored after it is deleted

### ISSUE THREAD

**Issue by alexlii1971** [cloudflare/cloudflare-docs#7262]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/manage-domains/remove-domain/

### Section that requires update

I just noted that the settings are still there after the domain is readded ?

So, How long will be the domain setting data stored after it is deleted for free plan.

### What needs to change?

Update.

how to trigger completely deleted the domain setting data?

### How should it change?

Support manually complete deleted settings immediately.

**Comment by cicku** [comment]
Your audit logs (which contains your configuration history) can stay there for up to 18 months.
