### ISSUE TITLE
Public Hostnames "Path" is appended to Service URL?

### ISSUE THREAD

**Issue by michaelweinold** [cloudflare/cloudflare-docs#7264]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

 - https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/

### Section that requires update

N/A

### What needs to change?

The `Public Hostname Page` for a Cloudflare Tunnel has three fields:

| (optional) Subdomain | (required) Domain | (optional) Path |
| --------------------- | ------------------ | ---------------- |

As the documentation clearly states, this can be used to expose http resources like so:

```
subdomain.domain.com >> http://localhost:1234
```

However, it seems that the beheviour is currently such that instead of:

```
subdomain.domain.com/path1 >> http://localhost:1234
subdomain.domain.com/path2 >> http://localhost:5678
```

we get:

```
subdomain.domain.com/path1 >> http://localhost:1234/path1
subdomain.domain.com/path1 >> http://localhost:1234/path2
```

### How should it change?

If this is expected behaviour, it should be added to the documentation. Otherwise, the setup of the `Public Hostname Page` in the tunnel dashboard might lead users to believe a routing like this is possible:

```
subdomain.domain.com/path1 >> http://localhost:1234
```

**Comment by michaelweinold** [comment]
@obezuk, is this an issue that is relevant to the documentation repo, or should I file this over at the [`cloudflared`](https://github.com/cloudflare/cloudflared) repo?

**Comment by michaelweinold** [comment]
@ranbel / @obezuk, any update on this?

**Comment by ranbel** [comment]
Hi @michaelweinold, apologies for the delay. I have talked to the product team and confirmed that this is not a documentation issue. Please open an issue in the [cloudflared](https://github.com/cloudflare/cloudflared) repo so that engineering can investigate this behavior.
