### ISSUE TITLE
Redirect loop for /pages/platform/serving-pages/

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#7343]
### Example URL(s)

https://developers.cloudflare.com/pages/platform/serving-pages/

### Actual Behavior

<img width="640" alt="image" src="https://user-images.githubusercontent.com/8484333/213779548-df1221f7-ed17-4551-a400-909dfa2607c9.png">

### Expected Behavior

No loop

**Comment by WalshyDev** [comment]
Resolved in #7345
