### ISSUE TITLE
Add a section regarding GeoDNS routing

### ISSUE THREAD

**Issue by callowaysutton** [cloudflare/cloudflare-docs#7354]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

1.1.1.1 support for GeoDNS based routing

### Content Location

https://developers.cloudflare.com/1.1.1.1/faq/#does-1111-send-edns-client-subnet-header

### Additional information

Just adding a section underneath the EDNS section to clarify how 1.1.1.1 still supports GeoDNS based routing without sending client IP information.

Here's a proposed edit:
## Does 1.1.1.1 break GeoDNS routing?
No, 1.1.1.1 does not break GeoDNS routing. Cloudflare uses the EDNS Client Subnet (ECS) section of the query to send the nearest unicast response to the client, ensuring that the client is directed to the closest and most optimal server. This improves the overall performance and security of the DNS resolution process. Additionally, Cloudflare's global Anycast network allows it to route traffic to the closest data center, further enhancing the GeoDNS routing capabilities of 1.1.1.1.

**Comment by callowaysutton** [comment]
Any update?

**Comment by kodster28** [comment]
Howdy @callowaysutton, flagged this for internal review and turns out that this issue / suggestion isn't factually accurate.

From earlier in the [current FAQ](https://developers.cloudflare.com/1.1.1.1/faq/#does-1.1.1.1-send-edns-client-subnet-header):

> 1.1.1.1 is a privacy centric resolver so it does not send any client IP information and does not send the EDNS Client Subnet Header to authoritative servers. The exception is the single Akamai debug domain whoami.ds.akahelp.net to aid in cross-provider debugging. However, Cloudflare does not send ECS to any of Akamai’s production domains, such as akamaihd.net or similar.
