### ISSUE TITLE
🐛 Docs BUG: no information about Durable Objects limitations on free plan.

### ISSUE THREAD

**Issue by rgb2hsl** [cloudflare/cloudflare-docs#7366]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Mac

### Describe the Bug

1. Create any CF worker.
2. Make it use Durable Objects
3. Publish it with Free Plan.

You'll got "In order to use Durable Objects, you must agree to pricing at" message with `https://dash.cloudflare.com/{account_id}/workers/overview?enable-durable-objects` link.

Link is broken: it leads to your workers dashboard with no messages about pricing on it. Looks like dashboard UI have changed but someone forgot to change the link in the error message.
![image](https://user-images.githubusercontent.com/3310192/198901127-97f335c5-cd61-44eb-90fa-f19ec94e7759.png)

Also there is NO info telling you that Durable Objects is fully unavailable for Free Plan users (KV storage, module Workers and a lot of other techs are available). The fact that your Worker will work locally with `wrangler dev` is making it just more unclear.

Here is the message you'll get in the console when you've tried to publish your Worker:
![image](https://user-images.githubusercontent.com/3310192/198901349-2ad53990-0b1a-4cfa-95ab-497b698f9c43.png)

Link goes to your dashboard. Okey, let's see the "Limits" page on Docs. All limitations is covered there. https://developers.cloudflare.com/workers/platform/limits/#durable-objects Not a single word about free plan limitations.
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3310192/198901433-9333d8b3-ee49-4df0-a747-e8f4c5b0181b.png">

There is NO info about Durable Objects in "Account Plan Limits" either. https://developers.cloudflare.com/workers/platform/limits/#account-plan-limits
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3310192/198901532-4aae93e9-9e46-4543-b219-8cd9bd8770ec.png">

Please, make it clear what techniques are available for free tests and what are not so people were ready to pay for their researches and tryouts.

**Comment by koeninger** [comment]
https://developers.cloudflare.com/workers/platform/pricing/#durable-objects

"Durable Objects are only available on the Workers Paid plan."

**Comment by koeninger** [comment]
We have an internal ticket for tracking the overview?enable-durable-objects link being broken

**Comment by lrapoport-cf** [comment]
moving this to docs repo as there isn't a wrangler-specific concern here

**Comment by rgb2hsl** [comment]
> https://developers.cloudflare.com/workers/platform/pricing/#durable-objects
> 
> "Durable Objects are only available on the Workers Paid plan."

Sure thing, but in must be listed in "Account Plan Limits" table anyway.

**Comment by kodster28** [comment]
This has been addressed by the associated PR.
