### ISSUE TITLE
[R2] Add presigned URL example to aws4fetch page

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#7398]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/data-access/s3-api/presigned-urls/#presigned-url-alternative-with-workers
- https://developers.cloudflare.com/r2/examples/aws4fetch/

### Section that requires update

- https://developers.cloudflare.com/r2/examples/aws4fetch/

### What needs to change?

Add an example on using aws4fetch to generate presigned URLs.

### How should it change?

Add the example from the [presigned URLs guide](https://developers.cloudflare.com/r2/data-access/s3-api/presigned-urls/#presigned-url-alternative-with-workers) onto the [aws4fetch guide](https://developers.cloudflare.com/r2/examples/aws4fetch/), like how it is for [aws-sdk-js-v3](https://developers.cloudflare.com/r2/examples/aws-sdk-js-v3/#generate-presigned-urls)

### Additional information

The example relies on https://github.com/cloudflare/cloudflare-docs/pull/7392 being merged as it is currently incorrect.

**Comment by KianNH** [comment]
When https://github.com/cloudflare/cloudflare-docs/pull/7417 is reviewed, I can pull across the updated Worker into the aws4fetch example.

**Comment by dcpena** [comment]
> When #7417 is reviewed, I can pull across the updated Worker into the aws4fetch example.

You're all set on #7147, Kian!
