### ISSUE TITLE
Document the JWT claims that Access makes with the various types of logins

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/cloudflare-docs#7412]
### Which Cloudflare product(s) does this pertain to?

Zero Trust

### Subject Matter

Access JWT claims

### Content Location

https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/application-token/#payload

### Additional information

I'd like a table like:

| Field | Description | Present in Identity JWT | Present in non-Identity JWT |
| --- | --- | --- | --- |
| `aud` | The audience tag for the application to which the token is used. | ✅ | ✅ |
| `email` | The email address of the authenticated user. | ❓ | ❌ |

etc.

Note, those values are just dummy. I don't know when these values are actually provided. I'm also guessing that the difference is between identity/non-identity, but there might be other circumstances that means a field is present/omitted.

**Comment by GregBrimble** [comment]
Related, we should also consider explicitly defining the fields that we should validate. Presumably I should error if `exp` is in the past. But should I error if it simply isn't present in the payload?

**Comment by ranbel** [comment]
Great idea! @jroyal if you have any info or guidance on this request, please add to PCX-5880.

**Comment by kodster28** [comment]
Moving to PCX-10029
(and closing out since the convo around this'll happen internally)

**Comment by ranbel** [comment]
Added service token payload to #16042
