### ISSUE TITLE
Instructions for manual configuration for Teams on iOS is broken link

### ISSUE THREAD

**Issue by crstauf** [cloudflare/cloudflare-docs#745]
1. https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/connections/connect-devices/warp/deployment/iOS-Teams.md#manually-configure-a-gateway-doh-subdomain
2. Find "these instructions" (links to https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/configuring-locations#find-a-locations-doh-subdomain)
3. 404

**Comment by abracchi-tw** [comment]
thanks for flagging this! #919 should fix the issue.

**Comment by crstauf** [comment]
Production link: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/iOS-Teams
