### ISSUE TITLE
Move Nuxt.js to Nuxt.js 2; Add Nuxt.js 3 framework preset for pages.

### ISSUE THREAD

**Issue by kashalls** [cloudflare/cloudflare-docs#7451]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

- https://developers.cloudflare.com/pages/platform/build-configuration#framework-presets

### Section that requires update

The current mention of Nuxt as a framework preset implies the latest version of Nuxt. However, Nuxt v3 was just released this year and although the build commands are similar, they need to be changed in order to build successfully.

Things to look at:
- https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-pages

### What needs to change?

Change the name of the framework preset Nuxt.js to Nuxt.js 2

**Nuxt 2**
- Output: `dist`
- Build Command: `nuxt generate`

Create a new framework preset called `Nuxt.js 3`

**Nuxt 3**
- Output: `.output/public`
- Build Command: `npx nuxi generate`

### How should it change?

I propose that two versions of the framework preset created:
- Nuxt 2
- Nuxt 3

In the near future, Nuxt 2 will be phased out of lifecycle, we can have Nuxt 2 preset removed.

### Additional information

Building for cloudflare pages requires the `nuxt.config.ts` configuration to have `ssr: false`.

**Comment by kashalls** [comment]
As per @WalshyDev asked in discord, you can build to also use cloudflare pages by removing `ssr:false` from your `app.config` and using the following:
```
  nitro: {
    preset: 'cloudflare_pages'
  }
  ```
  
The underlying nitro server will then allow that to function.

**Comment by deadlypants1973** [comment]
#7447

**Comment by kashalls** [comment]
Fixed in https://github.com/cloudflare/cloudflare-docs/pull/7447
