### ISSUE TITLE
1.1.1.1 Cloudflare Warp Network Share

### ISSUE THREAD

**Issue by muhanadali100** [cloudflare/cloudflare-docs#7454]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

Need a feature to share network from my linux or android to another Devices in my local network

### Content Location

I need this feature in 1.1.1.1 Warp to make all my device in the local network can safe in internet and encrypted why ? 
because i don't need to install the application in all devices just add a nat redirect in my router or via proxy

**Comment by Mehrdadmehrdadian** [comment]
struct apr_crypto_key_t { apr_pool_t *pool; const apr_crypto_driver_t *provider; const apr_crypto_t *f; const EVP_CIPHER * cipher; کاراکتر بدون امضا *key; int keyLen; int doPad; int ivSize; }; struct apr_crypto_block_t { apr_pool_t *pool; const apr_crypto_driver_t *provider; const apr_crypto_t *f; EVP_CIPHER_CTX *cipherCtx; int مقداردهی اولیه int ivSize; int blockSize; int doPad; }; static int key_3des_192 = APR_KEY_3DES_192; static int key_aes_128 = APR_KEY_AES_128; static int key_aes_192 = APR_KEY_AES_192; static int key_aes_256 = APR_KEY_AES_256; static int mode_ecb = APR_MODE_ECB; static int mode_cbc = APR_MODE_CBC;

**Comment by kodster28** [comment]
Howdy @muhanadali100, appreciate the suggestion, but this is just a repo for our product documentation and we can't do much about feature requests.
