### ISSUE TITLE
Turnstile invalid domain error not calling error callback

### ISSUE THREAD

**Issue by gnoyixiang** [cloudflare/cloudflare-docs#7479]
### Example URL(s)

I am trying to handle the invalid_domain error, but I realised the error-callback function is not triggered.

![image](https://user-images.githubusercontent.com/30717323/215702274-0e962859-f711-4f90-a6e4-4b43d4c75fcd.png)

![image](https://user-images.githubusercontent.com/30717323/215701781-09214d14-6e2b-4730-996e-b8d8ef47dce2.png)

I debugged and realised that line 163 calls function in line 42 and throws an error, causing lines 164 - 166 to skip execution. I believe the error callback is called in line 166 
```
let i = s.cbError;
i && i();
```

![image](https://user-images.githubusercontent.com/30717323/215702416-2c5f6c87-7ed0-4224-8c5f-af6f70e45c6e.png)
![image](https://user-images.githubusercontent.com/30717323/215702981-1dd5dba0-73c0-4167-84eb-3d779e7dfd93.png)

### Actual Behavior

Error-callback function is not triggered when any error occurs in turnstile render function.

### Expected Behavior

Error-callback function should be triggered when any error occurs in turnstile render function.

**Comment by kodster28** [comment]
@patriciasantaana, this sounds more like a bug for your ENG team.

**Comment by gnoyixiang** [comment]
Shouldn’t this be more of a bug than a feedback?
