### ISSUE TITLE
[Teams] Possible Out-dated Instruction on Session Management Doc

### ISSUE THREAD

**Issue by Kynson** [cloudflare/cloudflare-docs#753]
Hello everyone,

The [Per-user](https://developers.cloudflare.com/cloudflare-one/identity/users/session-management#per-user) section under session management of Cloudflare for Teams seems to be out-dated. 

**Page with issue:** https://developers.cloudflare.com/cloudflare-one/identity/users/session-management#per-user

The docs instruct user to navigate to Logs > Users on the team dashboard. However, I am not able to find the _Users_ tab under _Logs_. Instead, it is moved to _My Team_ (See screenshot below), and users' session can be revoked there.

<img width="1289" alt="Screenshot 2021-02-09 at 11 15 49" src="https://user-images.githubusercontent.com/46522440/107310978-7ee6f200-6ac8-11eb-9dde-c11ddb73c831.png">

**Comment by abracchi-tw** [comment]
thanks for raising this! #948 should fix it.
