### ISSUE TITLE
List Algorithm 13 alternative name

### ISSUE THREAD

**Issue by C3R3** [cloudflare/cloudflare-docs#7540]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/dns/additional-options/dnssec
https://dash.cloudflare.com -> DNSSEC Setup fields

### Section that requires update

https://developers.cloudflare.com/dns/additional-options/dnssec
---Step 2 - Add DS record to your registrar

https://dash.cloudflare.com -> DNSSEC Setup fields
--- Algorithm

### What needs to change?

This suggestion is also for the dashboard when enabling DSSEC on a website and it provides you with all the fields to enter on the registrar. Add alternative name for Algorithm 13.

### How should it change?

https://developers.cloudflare.com/dns/additional-options/dnssec
---Step 2 - Add DS record to your registrar
------ If algorithm 13 is not listed by your registrar, it may also be called "ECDSA Curve P-256 with SHA-256".

https://dash.cloudflare.com -> DNSSEC Setup fields
--- Algorithm: 13 aka "ECDSA Curve P-256 with SHA-256"

### Additional information

![C17dgHWEW9](https://user-images.githubusercontent.com/106290173/216656520-b7999beb-6aea-4c39-af2d-19c9283d3826.png)

**Comment by kodster28** [comment]
Howdy @C3R3, this is only a docs repo, so we don't have access to change the dashboard.

Did add your suggestion to the docs though, thanks!!
