### ISSUE TITLE
Issue with Mkdocs external hyperlink

### ISSUE THREAD

**Issue by rwehe** [cloudflare/cloudflare-docs#7552]
### Example URL(s)

- https://developers.cloudflare.com/pages/framework-guides/deploy-an-mkdocs-site/

### Actual Behavior

Top link goes to https://mkdocs.org/ which gives SSL error

### Expected Behavior

Link should go to: https://www.mkdocs.org/

**Comment by kodster28** [comment]
Thanks for raising, updated the link in the mentioned PR.
