### ISSUE TITLE
Add guidance when creating Domain lists via API

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#7557]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/policies/filtering/lists/

### Section that requires update

[​​](https://developers.cloudflare.com/cloudflare-one/policies/filtering/lists/#create-a-list-from-a-csv-file)
Create a list from a CSV file

### What needs to change?

The conditions doesn't detail what happens when using duplicate hostnames for a "Domain" list.
The API would simply return 409 with the message "A resource with this identifier already exists." and code 1204.
This is potentially misleading if it's the List name or a List item.

### How should it change?

Mention that all hostnames in a list are:
- converted from IDN to Punycode
- checked against existing duplicate hostname in Punycode format.

### Additional information

for e.g, passing a list with these two entries will fail with 1204 error because they're duplicate (though not obvious until you convert to Punycode):
www.españa.com
www.xn--espaa-rta.com

**Comment by maxvp** [comment]
Addressed here: [https://github.com/cloudflare/cloudflare-docs/pull/8361](https://github.com/cloudflare/cloudflare-docs/pull/8361
)
Thanks for reporting!
