### ISSUE TITLE
Wrong command 

### ISSUE THREAD

**Issue by wyg27** [cloudflare/cloudflare-docs#7563]
### Which Cloudflare product does this pertain to?

Workers / D1

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/wrangler/commands/#backup-download

### Section that requires update

backup download

### What needs to change?

The command is wrong:

> wrangler d1 backup restore <DATABASE_NAME> <BACKUP_ID>

It should be

> wrangler d1 backup download <DATABASE_NAME> <BACKUP_ID>

### How should it change?

wrangler d1 backup download <DATABASE_NAME> <BACKUP_ID>

**Comment by elithrar** [comment]
This appears to be fixed: https://developers.cloudflare.com/workers/wrangler/commands/#backup-download

<img width="615" alt="image" src="https://user-images.githubusercontent.com/18544/233637287-d7edb668-b0e7-4728-8143-1aefc47dec4d.png">
