### ISSUE TITLE
[Wrangler] Update v1 tutorials to v2

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#7610]
the following tutorials need updating to work with wrangler v2+:

- [x] https://developers.cloudflare.com/workers/tutorials/github-sms-notifications-using-twilio/: this tutorial assumes `type="webpack"` with polyfills for the built-in `node:crypto` module and `Buffer` global
- [x]  https://developers.cloudflare.com/workers/tutorials/hello-world-rust/: points to https://github.com/cloudflare/rustwasm-worker-template/, which has been updated to use `workers-rs`, but the tutorial is still assuming `type="rust"` (i.e. `worker/worker.js` doesn't exist anymore)
- [x]  https://developers.cloudflare.com/workers/tutorials/build-a-qr-code-generator/: `wrangler init` now puts `index.js` in a `src` directory, and this uses `type="webpack"`
- [x]  https://developers.cloudflare.com/workers/tutorials/handle-form-submissions-with-airtable/: includes redundant `type="javascript"`, and assumes outdated `wrangler init` output structure
- [x] #14414
- [x] #14415
- [x] #14417
- [x] #14418
- [x]  #12668
- [x] #14419

_Originally posted by @mrbbot in https://github.com/cloudflare/cloudflare-docs/issues/6925#issuecomment-1419254725_

**Comment by lauragift21** [comment]
I can take a look into this @lrapoport-cf and update the tutorials.

**Comment by LMallett8** [comment]
Yes

**Comment by kodster28** [comment]
Closing out #14406 will address bullet 1 as well.

**Comment by kodster28** [comment]
Very belated, but we're closing this out as all tutorials as updated.

🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆 🎆
