### ISSUE TITLE
Add module syntax to Environment Variables docs

### ISSUE THREAD

**Issue by jspspike** [cloudflare/cloudflare-docs#7624]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/environment-variables/

### Section that requires update

https://developers.cloudflare.com/workers/platform/environment-variables/

### What needs to change?

Some users attempt to use global environment variables with module syntax since there are no examples in the Environment Variables section.

### How should it change?

Add examples and more documentation about module syntax in this section

**Comment by kodster28** [comment]
Howdy @jspspike, has this been addressed? I noticed that now we have a few callouts to module syntax throughout the docs page.

If not, leave this open.

If so, mind closing the issue?

**Comment by jspspike** [comment]
Yes this seems to have been addressed
