### ISSUE TITLE
Examples are Vulnerable to Timing Attack

### ISSUE THREAD

**Issue by mikeball** [cloudflare/cloudflare-docs#7659]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/examples/auth-with-headers/
https://developers.cloudflare.com/workers/examples/basic-auth/

### Section that requires update

https://developers.cloudflare.com/workers/examples/auth-with-headers/
```js
if (psk === PRESHARED_AUTH_HEADER_VALUE) {
```

https://developers.cloudflare.com/workers/examples/basic-auth/
```js
if (BASIC_PASS !== pass) {
```

### What needs to change?

Isn't this method of string comparison not vulnerable to timing attacks? I'm new to JS and workers, so not sure what JS I could write to do the string comparisons that would be constant time.

### How should it change?

These string comparisons should be constant time. Even though these are examples, would be much better to show method that is secure because they will no doubt be copied and used often. Would also be great to build some sort of helper for constant time comparisons into the worker platform as I am trying to figure out how to do so now.

**Comment by KianNH** [comment]
You can use https://nodejs.org/docs/latest-v17.x/api/crypto.html#cryptotimingsafeequala-b in Workers

**Comment by armfazh** [comment]
> You can use https://nodejs.org/docs/latest-v17.x/api/crypto.html#cryptotimingsafeequala-b in Workers

https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#subtlecrypto-methods

**Comment by kristianfreeman** [comment]
Per @deadlypants1973 / @KianNH we should add a new example that shows how to do safeequal and link to it in both of these examples
