### ISSUE TITLE
Example how to read email subject / body?

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#7691]
### Which Cloudflare product(s) does this pertain to?

Email Routing

### Subject Matter

Example how to read email subject / body?

### Content Location

https://developers.cloudflare.com/workers/runtime-apis/email-event/
Can you please make more example to show how to parse email subject, body?

**Comment by KianNH** [comment]
https://github.com/edevil/email_worker_parser is a good example if you haven't already found it.
