### ISSUE TITLE
[time] Include info about Linux (chrony) config

### ISSUE THREAD

**Issue by armfazh** [cloudflare/cloudflare-docs#7723]
### Which Cloudflare product(s) does this pertain to?

Time Services

### Subject Matter

Explicit info about how to configure NTP/NTS in chrony

### Content Location

https://developers.cloudflare.com/time-services/ntp/usage/

### Additional information

Currently, there are links to NTP linux clients, but it would be handy to include a shorter description about how to configure these clients. More advanced configuration can be forwarded to the client's docs.

**Comment by kodster28** [comment]
Howdy @armfazh, would that look something like the first example on the [chrony docs](https://chrony-project.org/examples.html)?

**Comment by kodster28** [comment]
Closing this out due to a lack of information. If this is still an issue and I'm closing this out in error, feel free to re-open another issue (and tag me!).

**Comment by armfazh** [comment]
> Howdy @armfazh, would that look something like the first example on the [chrony docs](https://chrony-project.org/examples.html)?

Maybe, I would like to find such a documentation in the Cloudflare docs .
