### ISSUE TITLE
Please add migration documentation from Recaptcha V3

### ISSUE THREAD

**Issue by mrbm** [cloudflare/cloudflare-docs#7755]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/turnstile/get-started/migrating-from-recaptcha.md

### Section that requires update

The addition of migrating from v3 is needed

Currently the documentation only shows migration for v2.

V3 is more common and has been out since 10/29/1018...as in 5 years.

### What needs to change?

The addition of migrating from v3 is needed

Currently the documentation only shows migration for v2.

V3 is more common and has been out since 10/29/1018...as in 5 years.

### How should it change?

Add additional documentation for converting v3. Might require update to turnstile product (not sure) but v3 migration documentation similar to your documentation for v2 would be very useful

### Additional information

I'm requesting this because I'm updating existing code bases of a CMS that already implement the v3. So if I could simply switch out the end points of the current implementation rather than adjusting other portions of the code base that would be very helpful, and I'm sure others are in my situation.

**Comment by mrbm** [comment]
@patriciasantaana Hey Patricia, just seeing if you have a timeline on this, thanks!

**Comment by Le0Developer** [comment]
What part of the guide does not apply exactly?
I don't see why [programmatically invoking](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge) is incompatible?

**Comment by mrbm** [comment]
@Le0Developer @patriciasantaana 

https://developers.google.com/recaptcha/docs/invisible
vs
https://developers.google.com/recaptcha/docs/v3

(I have spent 0 time on this btw) It would be helpful to have the documentation demonstrate how to simply copy and replace endpoints to be able to quickly swap out recaptcha for turnstil in the event a project is already set up with recaptcha v3

**Comment by Le0Developer** [comment]
>  would be helpful to have the documentation demonstrate how to simply copy and replace endpoints to be able to quickly swap out recaptcha for turnstil

It does.....
![image](https://user-images.githubusercontent.com/40232557/224136430-31297d01-85d2-4e4f-a310-6c1467511b9b.png)

Also a 1:1 swap is impossible, because Turnstile does not score users. They either fail or they succeed, there is no inbetween.

> (I have spent 0 time on this btw)

Maybe do before complaining and repeatedly pinging people?

**Comment by mrbm** [comment]
@Le0Developer chill.

If there is to be adoption, and the majority of projects are in V3, then this will be valuable to do for the less technical people, agreed?

**Comment by Le0Developer** [comment]
Nowhere in the guide does it say it's specific to V2, and as I said before, I can't see any reason why it doesn't also apply to V3.

**Comment by mrbm** [comment]
@Le0Developer I tried dropping in the suggested endpoints that are mentioned into the Divi theme to see about replacing their reCaptcha V3 implementation that they have set up with their visual theme builder and it didn't work and resulted in an error. So if you have suggestions, they would be appreciated. I can send you the php files related to the reCaptcha that the Divi theme builder uses for your review.

**Comment by patriciasantaana** [comment]
Hi @mrbm ! Thank you for bringing this to our attention. I’ve verified with the team that we currently only support up to v2 of reCAPTCHA so I will make note of that on the docs. 
I’m going to close this issue now. Please feel free to open up a new issue or ask any questions

**Comment by mrbm** [comment]
> Hi @mrbm ! Thank you for bringing this to our attention. I’ve verified with the team that we currently only support up to v2 of reCAPTCHA so I will make note of that on the docs.
> I’m going to close this issue now. Please feel free to open up a new issue or ask any questions

Hey @patriciasantaana ! Little confused on the response. The request here is to bring attention that it would be more valuable to do what is necessary to make documentation and platform in line with recaptcha v3 because that implementation is far more pervasive and migration from that platform would be more widely used. Do you think you could bring this up to the team?
