### ISSUE TITLE
Aggregates in GraphQL Analytics API

### ISSUE THREAD

**Issue by spencerwilson** [cloudflare/cloudflare-docs#7756]
### Which Cloudflare product does this pertain to?

Analytics

### Existing documentation URL(s)

- https://developers.cloudflare.com/analytics/graphql-api/tutorials/querying-workers-metrics/
- revision: https://github.com/cloudflare/cloudflare-docs/blob/178466a099956e2f5c6ae134954fd1304243cf69/content/analytics/graphql-api/tutorials/querying-workers-metrics/index.md

### Section that requires update

"API Call"

### What needs to change?

I'm not 100% sure it's wrong, but it seems wrong that this query 1) is selecting aggregation fields (`sum`, `quantiles`), but also 2) is not a `...Groups` field.

I was under the impression that in order to access aggregations, the field would have had to be named something like `workersInvocationsAdaptiveGroups`? That's based on https://developers.cloudflare.com/analytics/graphql-api/features/data-sets/ stating
> Nodes that represent aggregated data include the Groups suffix. For example, the loadBalancingRequestsAdaptiveGroups node represents aggregated data for Load Balancing requests.

and suggesting that you _can't_ do aggregates on non-Groups data sets.

### How should it change?

Just ensure the query is right. If it is, maybe explain this example since AFAICT it's the only on across all the docs that does this.

**Comment by victor-perov** [comment]
Hey @spencerwilson! Thank you for finding time to express your concern!

Indeed, we do have "Groups" nodes that represent aggregates and we have a rule to carry that naming. However, `workersInvocationsAdaptive` is an exception from that rule as it has slipped from our eyes and became public before we enforced the naming convention.

I would like to make retire this node at some point, but as for now I think we should point that this node is exempt on data-sets page.
