### ISSUE TITLE
Adding Turnstile to Data Localization

### ISSUE THREAD

**Issue by throny** [cloudflare/cloudflare-docs#7783]
### Which Cloudflare product(s) does this pertain to?

Data Localization

### Subject Matter

Turnstile

### Content Location

Adding Turnstile to the Data Localization Overview.

Is it possible to use a EU endpoint? EU metadata boundary?
It seems that using Turnstile is currently not possible with Regional Services as the endpoint getting called is universal. What about metadata collection? Are these getting stored in Boundaries after site-key association?

**Comment by tlozoot** [comment]
Turnstile is not yet part of the Data Localization Suite - we can update documentation.
