### ISSUE TITLE
[firewall] understanding the cloudflare security level

### ISSUE THREAD

**Issue by kaznovac** [cloudflare/cloudflare-docs#7874]
### Which Cloudflare product does this pertain to?

Firewall

### Existing documentation URL(s)

- https://developers.cloudflare.com/support/firewall/settings/understanding-the-cloudflare-security-level/
- https://github.com/cloudflare/cloudflare-docs/blob/81ec7d8dde6ab6a7eb3da9cf8dec4f30b380cb45/content/support/Firewall/Settings/Understanding%20the%20Cloudflare%20Security%20Level.md

### Section that requires update

all

### What needs to change?

the section is essentially empty, please document the security levels and their implications

### How should it change?

add the documentation, this feels like a placeholder

**Comment by pedrosousa** [comment]
@jedecf - This seems to be a migration issue.

**Comment by kaznovac** [comment]
@pedrosousa & @jedecf
please, let me know if i can assist

**Comment by kodster28** [comment]
still a few formatting issues, but content was re-added in #7933
