### ISSUE TITLE
deploy-a-blazor-site.md Update (.NET7)

### ISSUE THREAD

**Issue by Laftek** [cloudflare/cloudflare-docs#7880]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/framework-guides/deploy-a-blazor-site/

### Section that requires update

Blazor WASM .NET7 cannot be update by following guideline and simply changing number 6 to 7.

### What needs to change?

Commands in .sh file.

### How should it change?

Something needs to be updated to make it work with .NET7.

**Comment by changingmission** [comment]
It's also not working in my case when I added a project reference.
