### ISSUE TITLE
cloudflared as a service on windows running with less system permissions.

### ISSUE THREAD

**Issue by LubomirH** [cloudflare/cloudflare-docs#7881]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/as-a-service/windows/

### Section that requires update

Run cloudflared as a service section
steps 2, 5, 6, 13+14

### 1. step 2 
 Putting the binary in its own folder is good habit, but one should also harden the default permissions, so nobody can replace the file with some malicious binary. especially if the service is configured to run under the SYSTEM account. If you create a folder in the root of the drive c:\ the default permissions usually are fine, but maybe it is worth to advise people to remove the inheritance and check the permissions to be sure. Much better would be to create an installer package which will place the file into the ProgramFiles folder, which is the right place for binaries.

### 2. step 5
 the command `cloudflared.exe service install` is registering the binary as a windows service, but it has few drawbacks.
 a) it creates a service which is running under SYSTEM account, thus getting unnecessarily the highest available permissions
 b) one needs to adjust the ImagePath later in step 13+14

### 3. step 6
 Putting the config, credentials and private key to an extra folder is a good idea. SystemProfile folder might be a good place for a service running under SYSTEM account, but maybe not if we choose to run the service under an account with less privileges.

### 4. step 13+14
 There are better methods than adjusting the service via regedit tool.
 

### 1. step 2
 one can use the ICACL tool to check and optionally remove the permissions

-  disable inheritance `ICACLS "D:\Cloudflared" /inheritance:d /T`
-  check the permissions `ICACLS "D:\Cloudflared"`
-  remove the unwanted permissions 
    `ICACLS "D:\Cloudflared" /remove:g "NT AUTHORITY\Authenticated Users" /T`
    `ICACLS "D:\Cloudflared" /remove:g "BUILTIN\Users" /T`
    `ICACLS "D:\Cloudflared" /remove:g "Everyone" /T`

### 2. step 5
-  Since Windows server 2008 R2 and Windows 7, there is a possibility to run a service under virtual account. See [MS documentation](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd548356(v=ws.10))
-  Maybe you could adjust the `cloudflared service install` command to use the virtual account instead of the SYSTEM one. See [StackOverflow article](https://stackoverflow.com/questions/14648710/installing-a-windows-service-to-run-as-virtual-user)

### 3. step 6
 The service virtual account needs to have permission to read the config file, the credential and private key files and to execute the binary.
 `icacls D:\CloudflaredTEST\TunnelName\ /grant "NT SERVICE\Cloudflared-TunnelName:(OI)(CI)(RX)"`

### 4. step 13+14
 below is a set of Powershell commands which can be used to create a service while setting the ImagePath as well and also do some further adjustments.
-  **Creating the service**
 `$TunnelName = "TunnelA.domain.tld"`
 `New-Service -Name "Cloudflared-$TunnelName" -DisplayName "Cloudflared Tunnel $TunnelName" -BinaryPathName "D:\Cloudflared\$TunnelName\cloudflared.exe tunnel --config D:\Cloudflared\$TunnelName\config-multi.yml run"`
-  **Setting the delayed start** might be also a good idea
 `Set-Service -Name "Cloudflared-$TunnelName" –StartupType "AutomaticDelayedStart" #works only with PS version 6`
 or with the sc tool
 `sc.exe config "Cloudflared-$TunnelName" start=delayed-auto`
 check if it was succesfully set  
 `Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Cloudflared-$TunnelName\' -Name DelayedAutostart`
-  **change the account under which the service will run**
 `sc.exe config "Cloudflared-$TunnelName" start=delayed-auto obj="NT SERVICE\Cloudflared-$TunnelName"`

### Additional information

I have personally decided to put everything on the D: drive, so I have a better overview, and keep track of the version of the binary and config files as well as the credentials and private keys.
So, I have created a main folder D:\Cloudflared\, where I put the downloaded binary. I have disabled the inheritance and removed the unnecessary permissions.
A subfolder D:\Cloudflared\<NameOfTheTunnell>\, where I copy an instance of the binary, put the config file, the credential and private key files, and where I have added the permissions to the service virtual account so it can read the files it needs to read and execute the binary. 

Hope it all makes sense ;)

LubomirH

**Comment by KimJ15** [comment]
Hi there - After looking through this issue, this looks like a feature request for cloudflared. Feel free to open a feature request with that team at https://github.com/cloudflare/cloudflared/issues.

**Comment by LubomirH** [comment]
There is nothing wrong with the cloudflared binary. It is the documentation which should be updated to reflect best practices.
