### ISSUE TITLE
Extensions in Browser Isolation: Add Chromium-based Browser Prerequisite

### ISSUE THREAD

**Issue by jdgregson** [cloudflare/cloudflare-docs#7884]
### Which Cloudflare product(s) does this pertain to?

Zero Trust

### Subject Matter

Desktop Chromium-based browser is required for extensions in Browser Isolation

### Content Location

https://developers.cloudflare.com/cloudflare-one/policies/browser-isolation/extensions/#prerequisite-isolate-chrome-web-store

### Additional information

Browser Isolation passes the user agent of the browser used to access the isolated session as the user agent of the isolated browser. This means that to install and use extensions, the client's browser itself needs to either support Chrome extensions or spoof its user agent to pose as a browser that supports Chrome extensions.

The documentation doesn't mention this, which leads to confusion when users try to install extensions in the isolated browser while using Safari or Firefox.

**Comment by jdgregson** [comment]
Just a quick update. Not sure if it's related to this request at all, but I've been using Browser Isolation nearly every day for seven months now and extensions have never been loaded in isolated sessions unless my user agent was Chromium-based. But as of tonight, my extensions are loading in Safari on iOS, which is fantastic!

I'm still not able to install new ones though unless I use a Chromium-based browser or user agent. Maybe Browser Isolation can be redesigned such that Chrome's user agent is always sent when users visit the Chrome Web Store? This would allow them to install extensions using any browser as the client, and still have an accurate user agent presented to every other website.

**Comment by KimJ15** [comment]
Hi there. This appears to be a feature request. I have shared this request with the team to be tracked internally as a feature request.
