### ISSUE TITLE
Updates examples for aws-sdk-js v2 -> v3

### ISSUE THREAD

**Issue by DeTeam** [cloudflare/cloudflare-docs#7894]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/examples/aws-sdk-js/

### Section that requires update

All of them. Installation, imports and usage are slightly changed.

### What needs to change?

https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/ here an info on what changed + how npm package structure has evolved.

### How should it change?

I could send a PR for use-cases already covered on the cloudflare R2 documentation page mentioned above 🤔

**Comment by dcpena** [comment]
@DeTeam if you wanted to fork the repo and submit a PR to make those updates, that would be much appreciated! 😀

**Comment by DeTeam** [comment]
Awesome @dcpena!
Give me a few days, I will tinker with a few examples today/tomorrow and then will submit a PR 🙏

**Comment by DeTeam** [comment]
Snaaaaap,  just found https://developers.cloudflare.com/r2/examples/aws-sdk-js-v3/!
The docs are up to date, missed this page @dcpena 👌 
However I still made a tiny PR with some linking v2 -> v3. 

\* Feel free to close both in case if you think it's irrelevant
