### ISSUE TITLE
[analytics] [graphQL] monthly rollup of request data not available through GraphQL API v4

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#790]
i am looking at the cloudflare APIs specifically the graphQL v4 API in order to extract dashboard metrics for my site. https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics

Here's the available queries available through the APIs, as follows you read the available rollups of data aggregated to the day, hour and minute.

```
httpRequests1dGroups
Daily rollups of request data

httpRequests1hGroups
Hourly rollups of request data

httpRequests1mGroups
Minutely rollups of request data
```

There doesn't seem to be a data rollup that aggregates data to the month so that I can retrieve monthly uniques - as cannot be computed by summing up the uniques of daily rollups

Is this still work in progress? is there any workaround to calculate or retrieve the monthly unique IP count from within the APIs?

Thanks in advance

**Comment by tlozoot** [comment]
Thanks for the report. We don't support "monthly uniques" and we have no plans to add support at this time.

You may want to check out sum(visits) in the `httpRequestsAdaptiveGroups` endpoint. 

A visit is a bit different from a unique; the definition is: `"The number of requests by end-users that were initiated from a different website (i.e. where the request HTTP Referer header does not match the host in the HTTP Host header)"`

**Comment by ghost** [comment]
thanks for the reply. unfortunately that path doesn't work it's probably now off-topic but this is just to share in case there is an obvious issue with the following request

```
query {
  viewer {
    zones(filter: {zoneTag: "<FILTERED>"}) {
      httpRequestsAdaptiveGroups(limit: 10000, filter: {date_gt: "2020-01-01"}, orderBy: [date_ASC]) {
        dimensions {
          date
        }
        sum {
          visits
        }
    }
  }
}
}
```

response

```
{
  "data": null,
  "errors": [
    {
      "message": "zone '<FILTERED>' does not have access to the path",
      "path": [
        "viewer",
        "zones",
        "0",
        "httpRequestsAdaptiveGroups"
      ],
      "extensions": {
        "code": "authz",
        "timestamp": "2021-02-24T15:47:19.488182662Z"
      }
    }
  ]
}
```

**Comment by tlozoot** [comment]
It's currently not available to customers on the Free plan.
