### ISSUE TITLE
Zero Trust for GitLab, but in an Unraid Container

### ISSUE THREAD

**Issue by Snipe3000** [cloudflare/cloudflare-docs#7980]
### Which Cloudflare product(s) does this pertain to?

Zero Trust

### Subject Matter

How Zero Trust can be setup in a GitLab Unraid Container

### Content Location

"Cloudflare Tunnel" section.
Doesnt need to change, but would be amazing it there was an additional section on how to do this properly if GitLab is running in an Unraid container.

### Additional information
https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab/

**Comment by tiimk** [comment]
There is a cloudflared container already for unraid. And you can use that in combination with something like nginx-proxy-manager to act as a reverse proxy with cloudflared and your other unraid apps.

**Comment by KimJ15** [comment]
Hi there - Thanks for the feedback. Based on the last comment, i'm closing out this ticket given there is a workaround.
