### ISSUE TITLE
[Wrangler] Add documentation on `--content` flag

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#8031]
Add documentation to wrangler commands on `--content` flag for `wrangler deployments view` command

See https://github.com/cloudflare/cloudflare-docs/pull/7994#discussion_r1136197700 for reference

**Comment by admah** [comment]
@deadlypants1973  can you close this? We decided not to have this flag for now.

**Comment by lrapoport-cf** [comment]
i can close 👍
