### ISSUE TITLE
Turnstile - Existing Sites - Docs incorrect

### ISSUE THREAD

**Issue by JonLaliberte** [cloudflare/cloudflare-docs#8065]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

https://developers.cloudflare.com/turnstile/get-started/

### Section that requires update

Existing sites

### What needs to change?

It says
> Log in to the [Cloudflare dashboard](https://dash.cloudflare.com/?to=/:account/turnstile) and select your account.
> Go to Turnstile.

There is no Turnstile option after selecting your site. If you select a site, then use the URL linked to, it brings you to the same page as if you had not selected your site first, so you have to Add Site no matter what

### How should it change?

Either the docs need to be updated as mentioned above, or the product needs to be fixed to match the docs.

**Comment by kodster28** [comment]
@patriciasantaana, sounds like something you might want to raise with your product team.

**Comment by patriciasantaana** [comment]
Hi @JonLaliberte ! Thank you for bringing this to our attention, since Turnstile is account level then you don't need to select a site first to access the tab. I'm going to close this issue now, but feel free to open a new issue or ask any questions.
