### ISSUE TITLE
Error 1000 also caused by CF-Connecting-IP header

### ISSUE THREAD

**Issue by tkiseleveb** [cloudflare/cloudflare-docs#8066]
### Which Cloudflare product does this pertain to?

Fundamentals

### Existing documentation URL(s)

https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-1xxx-errors/

### Section that requires update

#error-1000-dns-points-to-prohibited-ip

### What needs to change?

Error 1000 is also caused when a request has the CF-Connecting-IP header set. Usually this would indicate a proxy loop, but my team was doing something a little more complicated. I didn't find any reference to that header in connection to error 1000.

### How should it change?

Change the line to something like:

The request includes two X-Forwarded-For headers or a CF-Connecting-IP header.

Could also mention True-Client-IP, though I haven't tested that.

**Comment by ngayerie** [comment]
Hi @tkiseleveb 
Thanks for raising this issue.
I've created https://github.com/cloudflare/cloudflare-docs/pull/9413 to add this use case.
