### ISSUE TITLE
Update Network Error Logging to show that is a beta

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflare-docs#8080]
### Which Cloudflare product does this pertain to?

Network Error Logging

### Existing documentation URL(s)

https://developers.cloudflare.com/network-error-logging/get-started/

### Section that requires update

Get Started section

### What needs to change?

It that's that network error logging is available to users on all plan types but it is currently in a private beta

### How should it change?

Reflect that it is a private beta.

**Comment by dcpena** [comment]
Hi @Cyb3r-Jak3, Network Error Logging is available to users on all plan types which is why the beta note was removed.
