### ISSUE TITLE
HTMLRewriter does not have info about Content nor ContentOptions types

### ISSUE THREAD

**Issue by GeorgeTailor** [cloudflare/cloudflare-docs#8101]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#methods

### Section that requires update

https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#methods

### What needs to change?

Neither Content nor ContentOptions have information about what is the shape of those objects.

### How should it change?

Both Content and ContentOptions should have pages that describe their structure.

**Comment by irvinebroque** [comment]
Can you share what you're looking for beyond what is described here?

<img width="774" alt="Screenshot 2023-04-06 at 4 08 35 PM" src="https://user-images.githubusercontent.com/1221592/230509755-873c0248-2157-4802-a8ed-091b2c12423b.png">

**Comment by GeorgeTailor** [comment]
hello @irvinebroque 
it would be nice to have them linked as it is done, for example for `Response` on https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#supported-fetchevent-properties page. Maybe just linking to `https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#global-types` would be fine?

Neither `Content` nor `ContentOptions` are searchable with search in the top search bar.
