### ISSUE TITLE
rely on Github CLI (gh) to simplify Terraform tutorial section

### ISSUE THREAD

**Issue by mxschumacher** [cloudflare/cloudflare-docs#8104]
### Which Cloudflare product does this pertain to?

Terraform

### Existing documentation URL(s)

https://developers.cloudflare.com/terraform/tutorial/track-history/

### Section that requires update

"2. Store configuration in GitHub"

### What needs to change?

The current version relies on some "command line magic" like

"export GITHUB_URL=$(curl -H "Authorization: token $GITHUB_TOKEN" -d '{"name": "cf-config", "private": true}' "https://api.github.com/user/repos" 2> /dev/null | jq -r .ssh_url)"

which makes assumptions about curl and jq being installed and assumes that the user's terminal supports setting environment variables with the "export" command. Then the remote repo has to be connected to the local one.

### How should it change?

Instead, after the HCL files were written locally we can create create a Github repo and push our local code to it using the Github CLI (gh):

`gh repo create <repo_name> --source=. --remote=upstream`

Please find the relevant docs for gh here: https://cli.github.com/manual/

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request. Feel free to open a feature request with that team at https://github.com/cloudflare/cf-terraforming/issues.
