### ISSUE TITLE
Document OS permission to install WARP

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8110]
### Which Cloudflare product does this pertain to?

WARP Client

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp/

### Section that requires update

Table that summarize the memory requirement, version per OS.

### What needs to change?

The tables may feature a "permission required" or "admin permission required (Windows)" / "root permission required (Linux)" and state if this is needed or not.

### How should it change?

Add a line in the table for macOS, Windows and Linux installations.

**Comment by KimJ15** [comment]
Hi there - This is a request that the product team would need to determine as part of the product, not a documentation request! Closing this out and informing the product team of this request!
