### ISSUE TITLE
Redirection to support KB redirect to the Developer page

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8111]
### Example URL(s)

https://developers.cloudflare.com/support/ssl-tls/troubleshooting/troubleshooting-ssl-errors/

### Actual Behavior

All links below redirect to self:
https://developers.cloudflare.com/support/ssl-tls/troubleshooting/troubleshooting-ssl-errors/

-   [Redirect loop errors or HTTP 525 or 526 errors](https://support.cloudflare.com/hc/en-us/articles/200170566#h_7ec9ed4a-80ae-4fca-8be7-89a13c195d19)
-   [Only some of your subdomains return SSL errors](https://support.cloudflare.com/hc/en-us/articles/200170566#h_55e4d315-c60d-4798-9c4c-c75d9baed1b7)
-   [Your Cloudflare Universal SSL certificate is not active](https://support.cloudflare.com/hc/en-us/articles/200170566#h_122b94f3-ff14-4544-b5fa-8875e08ff5f0)
-   [OCSP response error](https://support.cloudflare.com/hc/en-us/articles/200170566#h_51354cf8-de93-4894-85e6-f0f7453d766d)
-   [SSL expired or SSL mismatch errors](https://support.cloudflare.com/hc/en-us/articles/200170566#h_c1a6e78e-150d-4db6-89ab-eec7cb1ab03f)

### Expected Behavior

Load the actual support KB articles or have they now been integrated into Developer doc ?

**Comment by Erisa** [comment]
The KB article those link to became that dev docs article, those links are trying to link to anchors on the same page and can be updated to anchor links accordingly.

**Comment by ngayerie** [comment]
Hi @wolruf , 
I've raised a PR fixing the links on this page:
https://github.com/cloudflare/cloudflare-docs/pull/9411
