### ISSUE TITLE
🐛 BUG: wrangler `mtls-certificate upload` fails when PEM contains public/private key pair

### ISSUE THREAD

**Issue by kamranayub** [cloudflare/cloudflare-docs#8114]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12.3

### What operating system are you using?

Windows

### Describe the Bug

I tried to use the mTLS upload for a PEM file that contained both the private/public key.

```sh
wrangler mtls-certificate upload --cert cert.pem --key cert.pem --name my_cert
```

I received a `unable to parse certificate` and finally figured out it needed to be split into separate files.

I know there's a separate `--key` argument but apparently [PEM files are non-standard](https://stackoverflow.com/a/7539644) and can contain either/or.

**Comment by penalosa** [comment]
Thanks for raising this! I'm going to transfer it to our docs repo, as it sounds like this is more of a documentation issue. Was there any specific reason you weren't able to use separate files?

**Comment by kamranayub** [comment]
@penalosa I think the issue is more that PEM files are allowed to contain the public _and_ private key, but the CLI was throwing an error trying to use it that way, which forced me to remove the private key from the PEM file.

For example, a `.pem` file like this:

```
-----BEGIN CERTIFICATE-----
cert contents
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY -----
cert contents
-----END RSA PRIVATE KEY -----

```

Should be accepted for both `--cert` and `--key` but instead I get:

```
unable to parse certificate
```

Even though it's a fully valid PEM file 😄 

Ideally, the CLI would accept a PEM file with `--cert` and `--key` and extract whatever it needs without any additional work on my part.

**Comment by penalosa** [comment]
@matthewdavidrodgers Could you take a look at this?

**Comment by matthewdavidrodgers** [comment]
Given that PEM files are indeed not a standard, I don't think it's a bug on Wrangler's part to only accept PEM files containing single entities. I will update the docs to reflect this - if we want to pursue parsing out certificate entities from PEM files that should be tracked as a feature request in Wrangler
