### ISSUE TITLE
impossible to delete project on Cloudflare Pages

### ISSUE THREAD

**Issue by Viteok** [cloudflare/cloudflare-docs#815]
impossible to delete project on Cloudflare Pages
Error Code:800013
![image](https://user-images.githubusercontent.com/9491631/108596536-5d222080-738e-11eb-9d1e-c62a9e1c07c3.png)

**Comment by rita3ko** [comment]
Hi @Viteok we're aware of this issue and working on fixing it (hopefully early next week). It's not related to the docs so going to close this issue. Thanks for reporting!
