### ISSUE TITLE
_redirects entries on /api do not work due to Function

### ISSUE THREAD

**Issue by Erisa** [cloudflare/cloudflare-docs#8161]
### Example URL(s)

https://developers.cloudflare.com/api/tokens/create/permissions

### Actual Behavior

https://developers.cloudflare.com/api/tokens/create/permissions Redirects to https://developers.cloudflare.com/api/ 

### Expected Behavior

`/api/` entries in `_redirects` should be respected.
That example URL should redirect to https://developers.cloudflare.com/fundamentals/api/reference/permissions

### Additional information

All the redirects listed here: https://github.com/cloudflare/cloudflare-docs/blob/production/content/_redirects#L132-L152
Do not work since /api is a Function now and `_redirects` entries do not work alongside Functions.

These old URLs are linked in the live Terraform docs: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/api_token#nested-schema-for-policy

**Comment by kodster28** [comment]
Damn, something was off in the logic that actually broke the api docs, so had to revert in #8274.

I'll ping @codewithkristian internally tomorrow.

**Comment by kodster28** [comment]
Re-addressed by #8279. Thanks again, @helloimalastair!
