### ISSUE TITLE
Convert Black Friday blog post into Ecommerce tutorial

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/cloudflare-docs#817]
We should make this a tutorial for Pages / Workers
https://blog.cloudflare.com/building-black-friday-e-commerce-experiences-with-jamstack-and-cloudflare-workers/

**Comment by kristianfreeman** [comment]
@rita3ko i think we should do an ecommerce tutorial, tho maybe it makes more sense to simplify it and not base it on this blog post - what do you think? also might be good tutorial for DA #3 🤔🤔

**Comment by rita3ko** [comment]
makes sense to me. closing.
