### ISSUE TITLE
Add meta data for files like pdf

### ISSUE THREAD

**Issue by eerison** [cloudflare/cloudflare-docs#8187]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Meta data in the headers 

### Content Location

- content/r2/objects/upload-objects.md
- https://developers.cloudflare.com/workers/wrangler/commands/#r2-object

### Additional information

I don't know if it's possible,
But are there anyway to set metadata for files like pdf?

Like

og:image
og:description 
And so on ...

It would be nice to share the file and have custom preview and description in social media platforms.

**Comment by KimJ15** [comment]
Hi there - Thanks for submitting this issue. This isn't possible today but i'll pass along this feedback to the R2 product team for future consideration. Thank you!
