### ISSUE TITLE
Remove references to captchas since not used anymore ?

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8300]
### Which Cloudflare product does this pertain to?

Firewall

### Existing documentation URL(s)

https://developers.cloudflare.com/support/firewall/settings/using-privacy-pass-with-cloudflare/

### Section that requires update

First two paragraphs under Overview

### What needs to change?

Parts of the Privacy Pass describe the ability to remove CAPTCHAs during a certain time.

### How should it change?

Either remove references to CAPTCHAs or update CAPTCHAs with Cloudflare challenges.

**Comment by worenga** [comment]
This has been adressed in https://github.com/cloudflare/cloudflare-docs/pull/8157 
Please re-open of you feel this was not properly addressed.
