### ISSUE TITLE
Google Trust Services & ECDSA certificates

### ISSUE THREAD

**Issue by vg** [cloudflare/cloudflare-docs#8304]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

- https://developers.cloudflare.com/ssl/reference/certificate-authorities/

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/0afe76c84b87ca95ff00814c51f1fcbba0e8afce/content/ssl/reference/certificate-authorities.md?plain=1#L20

### What needs to change?

Google Trust Services does support ECDSA certificates.
Example of such ECDSA cert is https://crt.sh/?id=8960795350 

### How should it change?

` | **Google Trust Services** | RSA and ECDSA certificates<br/><br/>Supports [validity periods](/ssl/reference/certificate-validity-periods/) of 14, 30, and 90 days.<br/><br/>[DCV tokens](/ssl/edge-certificates/changing-dcv-method/) valid for 14 days. | Punycode domains are not yet supported. | Currently trusted by Microsoft, Mozilla, Safari, Cisco, Oracle Java, and Qihoo’s 360 browser. All browsers or operating systems that depend on these root programs are covered.<br/><br/>In addition, some of Google Trust Services' [root CAs](https://pki.goog/faq/#faq-27) may rely on a cross-signature to ensure optimal support across a wide range of devices. | 
`

**Comment by RebeccaTamachiro** [comment]
Hi @vg! Thanks for creating this issue.
The page on certificate authorities has been updated. 
ECDSA with Google Trust Services is still not available but should start to be supported in the following months.
