### ISSUE TITLE
Can table be expanded to fill in unused space

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8344]
### Example URL(s)

https://developers.cloudflare.com/logs/reference/log-fields/zone/http_requests/

### Actual Behavior

On Firefox the 3-columns table has a fixed large first column then a scrollable list of 2 columns. By default, on a macOS laptop 13", the 3rd column isn't visible unless scrolled to the right. Although there's unused space on the right.

### Expected Behavior

Table to fill in space on the right. Eventually have a smaller first column with word wrapping.

**Comment by kodster28** [comment]
We'd need the frontmatter in the source template changed to be `layout: list`.
