### ISSUE TITLE
Dashboard link on Pages documentation

### ISSUE THREAD

**Issue by Meahaa** [cloudflare/cloudflare-docs#8353]
### Example URL(s)

https://developers.cloudflare.com/pages/

### Actual Behavior

the "Your Cloudflare Pages Dashboard" links to the product site and not your dashboard - not sure if it's a bug or by design

### Expected Behavior

Link to my dashboard

**Comment by kodster28** [comment]
Specifically, the 3rd button should link to https://dash.cloudflare.com/?to=/:account/pages
