### ISSUE TITLE
Make finding the Certificate Transparency Monitoring email toggle easier

### ISSUE THREAD

**Issue by RafaelCenzano** [cloudflare/cloudflare-docs#8395]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/additional-options/certificate-transparency-monitoring/

### Section that requires update

https://developers.cloudflare.com/ssl/edge-certificates/additional-options/certificate-transparency-monitoring/#opting-in-and-out
Opting in and out

### What needs to change?

Make more descriptive instructions to find the toggle, something like go to SSL/TLS > Edge Certificates then scroll down to Certificate Transparency Monitoring to toggle the option

### How should it change?

Add more descriptive instructions that follow something like this "SSL/TLS > Edge Certificates then scroll down to Certificate Transparency Monitoring to toggle the option"

**Comment by kodster28** [comment]
@RebeccaTamachiro, might be good to actually expand this into a folder and break out this info into separate pages.

One req is keeping the info related to `Emails to be concerned about` and `action steps` on the same page / prominently linked from the current page. This is important b/c we send out email notifications about cert transparency and that notification links to our doc. We want that doc to be actionable for folks receiving those notifications.

<img width="847" alt="Screenshot 2023-04-10 at 7 38 59 AM" src="https://user-images.githubusercontent.com/26727299/230912129-7645718c-ed49-4ebc-a0a7-f47f7240ccfa.png">

**Comment by RebeccaTamachiro** [comment]
Addressing this through PCX-6663. Should have an update to share here soon.

**Comment by RebeccaTamachiro** [comment]
Resolved by https://github.com/cloudflare/cloudflare-docs/pull/8733
