### ISSUE TITLE
Zero Trust Facebook Login instructions appear out of date

### ISSUE THREAD

**Issue by jordancrawford** [cloudflare/cloudflare-docs#8406]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/idp-integration/facebook-login/

### Section that requires update

Use these steps to set up Facebook as your identity provider.

### What needs to change?

The Cloudflare Zero Trust Facebook instructions appear to be out of date - it didn't seem to line up with how the developers.facebook.com dashboard was behaving.

### How should it change?

I had to login through a different page and the setup instructions were different. I had to go to the Products page to setup Facebook login and configure it to allow email address.

I believe adding the permission for email address requires additional verification - I don't know how to do that or if I can use Facebook for Zero Trust auth in the meantime.

**Comment by KimJ15** [comment]
Hi @jordancrawfordnz - If you're interested in opening a PR with suggestions, i've spoken to the dev team and they would be ok with reviewing your recommendations!
