### ISSUE TITLE
Missing docs on how to add custom headers to Pages

### ISSUE THREAD

**Issue by lawzava** [cloudflare/cloudflare-docs#841]
Either the docs are missing or the feature itself but in that case, I think it should be explicitly stated that adding custom HTTP headers is not supported.

**Comment by theamanbhargava** [comment]
Is there any update on this?

**Comment by ghost** [comment]
Any Updates on this?

**Comment by kristianfreeman** [comment]
We're working on a guide to show how you can build custom header support using Workers for your Pages project - more on that hopefully soon!

**Comment by ghost** [comment]
> We're working on a guide to show how you can build custom header support using Workers for your Pages project - more on that hopefully soon!

When will it be done without Workers?

**Comment by RafidMuhymin** [comment]
This feature should be available without workers. Because it's something that everyone must have to use.

**Comment by dustensalinas** [comment]
Documentation is incorrect for the referenced github page.

**Comment by deadlypants1973** [comment]
> Documentation is incorrect for the referenced github page.

@dustensalinas Can you please drop the incorrect section in the docs you are referencing so we can review?
