### ISSUE TITLE
Document DNS Firewall Rate Limiting via API

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8433]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/dns/dns-firewall/setup/

### Section that requires update

There's no section indicating that Rate Limiting can be done, via the API only.

### What needs to change?

Mention Rate Limiting in the setup, as an optional step.

### How should it change?

Point the API: https://developers.cloudflare.com/api/operations/dns-firewall-update-dns-firewall-cluster as a way to configure DNS Firewall rate limiting.

**Comment by RebeccaTamachiro** [comment]
Thanks for raising this. Should be updating soon. PCX-6664
