### ISSUE TITLE
[Pages] Sentry Documents Out of Date

### ISSUE THREAD

**Issue by sgoodluck** [cloudflare/cloudflare-docs#8464]
### Which Cloudflare product does this pertain to?

Pages

### Existing documentation URL(s)

https://developers.cloudflare.com/pages/platform/functions/plugins/sentry

### Section that requires update

`functions/_middleware.ts` is no longer how NextJS functions. Middleware exists on the root of the project. 

### What needs to change?

It should reflect the latest NextJS capabilities

### How should it change?

It should reference current NextJS practices. Namely `functions` folder is no longer relevant. https://nextjs.org/docs/advanced-features/middleware

**Comment by WalshyDev** [comment]
Pages is not only for Next.js. This is valid for how Pages Functions work. We are not Next.js.

next-on-pages (our Next.js adapter) should also support this as is.

So, closing this as invalid.
