### ISSUE TITLE
 Docs for `List Cloudflare Tunnels` api call missing information on allowed query parameters

### ISSUE THREAD

**Issue by pratheekrebala** [cloudflare/cloudflare-docs#8473]
### Which Cloudflare product does this pertain to?

API

### Existing documentation URL(s)

https://developers.cloudflare.com/api/operations/cloudflare-tunnel-list-cloudflare-tunnels

### Section that requires update

 `List Cloudflare Tunnels` api call.

### What needs to change?

The body section of the api request needs to include acceptable parameters that can be used for filtering the listed tunnels.

### How should it change?

The document doesn't list which parameters are accepted by the API endpoint. Looking [through the implementation on the `cloudflare-go` package](https://github.com/cloudflare/cloudflare-go/blob/master/tunnel.go#L178-L185), it seems like the API accepts filtering based on `name` and `uuid`. It would be great if the documentation can be updated to reflect this and any additional filtering criteria accepted by the endpoint.

### Additional information

I had originally assumed that all attributes are filterable since there was no params listed. However, the API silently returns all available tunnels if filtering on an unsupported field e.g. `status` or `remote_config`.

**Comment by kodster28** [comment]
Howdy @pratheekrebala, seems like this has been addressed b/c I now see a massive `Query Parameters` section in the [API docs](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-list-cloudflare-tunnels).
