### ISSUE TITLE
[pages] document Rust and Swift installation process

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/cloudflare-docs#849]
Document how to install Rust and Swift for your pages projects, since they aren't installed by default. Details that need to be tested and turned into docs here: https://pages.cloudflare-docs.workers.dev/pages/platform/build-configuration

```
Swift

Not installed by default. Supports any version that swiftenv can install later than 4.x. Versions 4.x and earlier will not work due to incompatible shared libraries. 5.2 is installed if Package.swift is present and no version is specified with SWIFT_VERSION or .swift-version.

Rust

Not installed by default. Supports any version that rustup can install.
```

**Comment by estrogently** [comment]
> ```
> Swift
> 
> Not installed by default. Supports any version that swiftenv can install later than 4.x. Versions 4.x and earlier will not work due to incompatible shared libraries. 5.2 is installed if Package.swift is present and no version is specified with SWIFT_VERSION or .swift-version.
> 
> Rust
> 
> Not installed by default. Supports any version that rustup can install.
> ```

It appears these docs were written for a newer version of Netlify's build-image than Pages uses? (TL;DR: on Pages, Swift IS installed by default, and Rust is not installable)

For Swift, a Pages build with neither `SWIFT_VERSION` set nor a `Package.swift` present outputs
> 19:24:49.376 | 5.2 is already installed.
> 19:24:49.380 | Using Swift version 5.2

So Swift 5.2 appears to be installed by default on Pages; this stopped being the case in https://github.com/netlify/build-image/commit/09c2cdcdf242cf2f57c9ee0fcad9d298fad9ad41.

As for Rust (first introduced in https://github.com/netlify/build-image/commit/53b83b6bede2920f236b25b6f5a95334320dc849), both cargo and rustup are included in Netlify's image—"not installed by default" refers to no Rust toolchain being present, which you'd install yourself either with a `rust-toolchain(.toml)` file or via prefixing the build command with a `rustup toolchain install`. Neither cargo nor rustup are present in Pages.

**Comment by kristianfreeman** [comment]
We've removed mentions of Rust and Swift in the docs, so this issue is out of date
