### ISSUE TITLE
Minor typo in request-rate documentation

### ISSUE THREAD

**Issue by Lytes** [cloudflare/cloudflare-docs#8493]
### Which Cloudflare product does this pertain to?

Rules

### Existing documentation URL(s)

https://developers.cloudflare.com/waf/rate-limiting-rules/request-rate/

### Section that requires update

Example A states that request 2 would be blocked if request 3 matches the rule expression

### What needs to change?

"Request 3 matches the rule expression and the same values for rule characteristics. Therefore, Cloudflare increases the value of the existing counter, setting it to 2. The counter value is now above the limit defined in Requests, and so **request 2** gets blocked."

### How should it change?

"Request 3 matches the rule expression and the same values for rule characteristics. Therefore, Cloudflare increases the value of the existing counter, setting it to 2. The counter value is now above the limit defined in Requests, and so **request 3** gets blocked."

### Additional information

Here's the line to edit in the github repo. 
https://github.com/cloudflare/cloudflare-docs/blob/a672c0eac4667b069f8f7c0932c2999ebd1ecf8c/content/waf/rate-limiting-rules/request-rate.md?plain=1#L64

**Comment by pedrosousa** [comment]
Thank you for reporting this issue, @Lytes, and also for the detailed description!
