### ISSUE TITLE
Traffic sequence section not visible at 100% view

### ISSUE THREAD

**Issue by kirtxn** [cloudflare/cloudflare-docs#8560]
### Example URL(s)

https://dash.cloudflare.com/e2354742c199e4f9309d5528b4a4b6a1/dtmsgoa.live/security/waf

### Actual Behavior

The issue is the Traffic sequence section is only visible if we zoom out the page to 50%. 
Please look into this issue.

### Expected Behavior

The traffic sequence section should be visible to all screen sizes or at 100% view or there should be a scrollbar to scroll it to the traffic sequence section.

### Additional information

The traffic sequence section can be found in 
Security-> WAF

At 100%:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/64327034/233258142-6195c545-1731-44bf-90c8-85b3852bc3cb.png">

At 50%:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/64327034/233258281-93023db1-8e85-4859-a371-ae6c64381735.png">

**Comment by kodster28** [comment]
I'll pass that along internally, @kirtxn, but this issue _technically_ doesn't apply to our documentation repo.

Thanks for letting us know (closing this out).

**Comment by xmflsct** [comment]
Hi @kirtxn, thanks for the report! We are aware that Traffic Sequence is not shown below certain view width. We are working on solutions to resolve this, stay tuned!
