### ISSUE TITLE
Swap domain name with example.com domain name

### ISSUE THREAD

**Issue by wolruf** [cloudflare/cloudflare-docs#8564]
### Which Cloudflare product does this pertain to?

SSL

### Existing documentation URL(s)

https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/methods/txt/#txt-dcv-method

### Section that requires update

The DCV examples include a domain name called best3 . com

### What needs to change?

swap best3 . com with example.com to avoid this being caught by search engines.

### How should it change?

move  both        "txt_name": "_acme-challenge.best3.com",
to
          "txt_name": "_acme-challenge.example.com",

**Comment by RebeccaTamachiro** [comment]
Hey there! Thanks for flagging this.
Addressed w/in https://github.com/cloudflare/cloudflare-docs/pull/8633
Ended up replacing with `_acme-challenge.<DOMAIN>.com` to make it consistent with the `"hosts":` value that is used earlier in this example.
