### ISSUE TITLE
Connect to SSH server with cloudflared access

### ISSUE THREAD

**Issue by Farmeurimmo** [cloudflare/cloudflare-docs#8566]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/ssh/#connect-to-ssh-server-with-cloudflared-access

### Section that requires update

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/ssh/#2-connect-as-a-user

"3. Input the following values; replacing ssh.example.com with the hostname you created."

### What needs to change?

How do we do if we have cloudflared installed with docker ?

### How should it change?

Explain if it's possible to work with docker cloudflared, and if possible how?

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request. Feel free to open a feature request with that team at https://github.com/cloudflare/cloudflared/issues.
