### ISSUE TITLE
using SPA with cloudflare worker website (react-router)

### ISSUE THREAD

**Issue by shmuel-web** [cloudflare/cloudflare-docs#857]
### we had an issue trying to deploy a react SPA using the CF worker website documentation 
[links to the docs](https://developers.cloudflare.com/workers/tutorials/deploy-a-react-app-with-create-react-app)

the manually typed URL routes fail and return a generic CF 404
so all routes configured in the react-router would fail!

eventually, we found the solution 
after a couple of hours of digging blogs and CF forums 

the solution was simple to implement 
copying the index.html and using it as a 404 so all routes that are not static files but the internal application routs would be redirected to 404.html (which would be a copied version of index.html )
that will kick the react-router into action and display the SPA routes, 
and there if the route doesn't exist the react-router will handle it 

this should be added to the docs 
because using an app router for a SPA is a really common use case 
regardless of framework 

I am attaching the equivalent configuration for the S3 website from the AWS console
![Screen Shot 2021-03-03 at 16 57 35](https://user-images.githubusercontent.com/13344801/109826237-43f95980-7c43-11eb-9cd7-4f9198196fc0.png)

**Comment by kristianfreeman** [comment]
Hey @shmuel-web - glad you got it working! I recommend switching to use the `serveSinglePageApp` function that we provide in our kv-asset-handler package, as it's designed for this exact usecase. We should make note of that in our Workers documentation. Thanks for filing an issue!

https://github.com/cloudflare/kv-asset-handler#servesinglepageapp

**Comment by KimJ15** [comment]
Closing issue given the last comment.
