### ISSUE TITLE
non-enterprise can create reverse dns zones

### ISSUE THREAD

**Issue by Tyler-OBrien** [cloudflare/cloudflare-docs#8604]
### Which Cloudflare product does this pertain to?

DNS

### Existing documentation URL(s)

https://developers.cloudflare.com/dns/additional-options/reverse-zones

### Section that requires update

**Enterprise** customers who control their own IP prefix(es) can set up reverse zones with PTR records to allow reverse DNS lookups.
...
 Availability

Any customer can create PTR records, but only **Enterprise** customers can create reverse zones.
...
The following Cloudflare customers can create reverse zones (for example, 2.0.192.in-addr.arpa):

**Enterprise** customers with an IPv4 or IPv6 address space can add the IPv4 or IPv6 reverse zone for their IP space to their account, and create the required PTR records for forward resolution.

### What needs to change?

Despite the documentation saying otherwise, non-enterprise users can create & activate reverse zones. I do not know when exactly this was allowed, but it's been a thing for at least the past few months, and I have an active ipv6 reverse dns zone in my non-enterprise account. I assume this goes for IPv4 Reverse Zones as well, as can I add them to my account without issue, but I cannot verify them as I do not own any IPv4.

### How should it change?

Drop all mentions of Enterprise being required ex. "Any customer can create PTR records and reverse zones"

### Additional information

A few hobbynet operators I know of have been turned away from using Cloudflare for Reverse DNS due to this confusing documentation, I hope this can be clarified so I can recommend Cloudflare to more of them!

**Comment by RebeccaTamachiro** [comment]
Thanks for flagging this. The documentation has been updated.
