### ISSUE TITLE
Pointing CNAME  to AWS ELB doesn't resolve

### ISSUE THREAD

**Issue by ETisREAL** [cloudflare/cloudflare-docs#8615]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/dns/advanced-topics/adding-vendor-specific-dns-records-to-cloudflare/

### Section that requires update

**Amazon ELB configuration**

### What needs to change?

How to set up the CNAME

### How should it change?

Just make it work

### Additional information

I followed the documentation on the required format to make it work:

_qlashMainNLB-863b8e5d5a7d670a.eu-central-1._elb.amazonaws.com

*Literally* the same format as in the documentation. Still the domain doesn't resolve

**Comment by ngayerie** [comment]
Hi there,
Sorry for the delay in getting back to you here @ETisREAL 
Would it be possible to raise this issue first in the Community:
https://community.cloudflare.com/c/website-application-performance/reliability/7
Or if you've done so, could you please share the link the thread?
Or the support ticket ID if you've raised one?
Thanks!

**Comment by ETisREAL** [comment]
Hi @ngayerie No worries. Eventually it worked by simply inserting the loadbalancer DNS as is from the console. Maybe the documentation should be updated?

**Comment by ngayerie** [comment]
In the documentation we mention the Target needs to be set as:
_<AWS HOSTNAME>.<REGION>._elb.amazonaws.com
Which seems to the format you used?
_qlashMainNLB-863b8e5d5a7d670a.eu-central-1._elb.amazonaws.com

Or did you have to enter a different target to make it work?

**Comment by ETisREAL** [comment]
I tried with that format and it wasn't working. I simply used the exact URL you get from AWS (ex. qmmcentrifugonlb-58ed12df1ce8432f.elb.eu-central-1.amazonaws.com) and it worked

**Comment by kodster28** [comment]
Oh..... I think this got messed up during the migration over to GitHub. The [previous version](https://web.archive.org/web/20210920144459/https://support.cloudflare.com/hc/en-us/articles/360020991331) in ZenDesk matched what @ETisREAL is suggesting.

cc: @jedecf

Let me push up a fix.

**Comment by ETisREAL** [comment]
I guess this will do it... Thanks guys :) cheers!
