### ISSUE TITLE
Telegram Bot not responsive

### ISSUE THREAD

**Issue by MHSEA** [cloudflare/cloudflare-docs#8623]
### Example URL(s)

1- https://t.me/onedotonedotonedotonedotBot

2- https://github.com/cloudflare/cloudflare-docs/blob/production/content/1.1.1.1/other-ways-to-use-1.1.1.1/dns-over-telegram.md

### Actual Behavior

Not responsive 

### Expected Behavior

To perform DNS lookups over Telegram

**Comment by kodster28** [comment]
Heyo, thanks for reporting and sorry you're experiencing issues.

Raised this internally as feedback. If there are updates to the docs, I'll address those, but going to go ahead and close for now.

**Comment by kodster28** [comment]
Raised this internally and you're correct that the bot isn't working correctly. Unfortunately, the response was to deprecate the bot, so removing this page in an associated PR.

Again, thanks for raising!
