### ISSUE TITLE
Add a separate page on known bugs for Cloudflare Pages

### ISSUE THREAD

**Issue by Albertozhao** [cloudflare/cloudflare-docs#868]
Now that Cloudflare Pages is in open beta, we should create a separate page in the Pages docs that shows the list of bugs we're actively working on. Here's a list that was sent to closed beta testers:

**Known Pages bugs:**
- Deleting a project with a custom URL may still show the old build in that URL. 
- Zone configurations are not working (such as running a Workers script in front, using Pages Rules, and enabling "Always HTTPS")
- No direct support for running routes or redirects in Pages (however, if your project contains a 404.html file, that's served first. If not, then your /index.html file is served)
- No Access integration yet to protect preview URLs
- Hugo builds automatically run an old version (Instructions: To run the latest version of Hugo 0.80.0, you'll need to add an environment variable. HUGO_VERSION as the variable name - and 0.80.0 as the value)

**Comment by kristianfreeman** [comment]
Closed with #875
