### ISSUE TITLE
Tab disappears after selection

### ISSUE THREAD

**Issue by Cherry** [cloudflare/cloudflare-docs#8695]
### Example URL(s)

https://developers.cloudflare.com/pages/platform/language-support-and-tools/

### Actual Behavior

- Scroll down to Build Environment section
- Click on the v1 tab
- It will disappear, and then never be able to be restored

### Expected Behavior

- Clicking on the v1 tab should not hide it. If there's a single tab, it probably shouldn't even act as if it's interactive.

### Additional information

https://user-images.githubusercontent.com/856748/235545910-0a185f74-6689-4d7d-8dbc-23fe811cc20d.mp4

**Comment by WalshyDev** [comment]
@GregBrimble ^
