### ISSUE TITLE
issues with site

### ISSUE THREAD

**Issue by Jdominguez736** [cloudflare/cloudflare-docs#8698]
### Example URL(s)

https://rt-btcmineaeros.site/profilecard.php

### Actual Behavior

there has been an error 522

### Expected Behavior

doeasnt load

### Additional information

no

**Comment by Cherry** [comment]
This doesn't appear to be an issue with the Cloudflare docs. If you have an issue with Cloudflare on your own website, I'd recommend you seek support on the community forum or discord server.
