### ISSUE TITLE
CF-Worker header info is wrong

### ISSUE THREAD

**Issue by Manouchehri** [cloudflare/cloudflare-docs#8761]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#cf-worker

### Section that requires update

The CF-Worker behavior is wrong.

### What needs to change?

How the CF-Worker header is explained

### How should it change?

It should mention that it'll always be `your_org.workers.dev`.

**Comment by Erisa** [comment]
In which cases does this not use the zone name and always use the `workers.dev`?

My Workers custom domain https://subrequest-headers.erisa.party/
and Workers Route https://erisa.party/subrequest-headers
both are sending `Cf-Worker: erisa.party` in subrequests to a non-cf origin

But on workers.dev it sends that: https://subrequest-headers.erisacf.workers.dev/
`Cf-Worker: erisacf.workers.dev`

**Comment by Manouchehri** [comment]
Oh. I guess I was mislead. =P

**Comment by Manouchehri** [comment]
Is it possible to have like `Cf-Worker: example.erisa.party` too?

**Comment by Erisa** [comment]
It's the zone name (what Cloudflare dashboard calls "websites"), so that would only happen if I added `example.erisa.party` as a separate subdomain zone: https://developers.cloudflare.com/dns/zone-setups/subdomain-setup/
