### ISSUE TITLE
[Docs Site] Change highlight frontmatter to accept ranges

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflare-docs#8765]
### Example URL(s)

- Everywhere

### Actual Behavior

Highlighting multiple lines currently looks like this:

```yaml
highlight: [15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
```

### Expected Behavior

It could be modified to take a range:

```yaml
highlight: ["15-31"]
```

### Additional information

Just makes it a bit nicer and easier to work with, imo.

**Comment by Cherry** [comment]
Something like https://www.npmjs.com/package/parse-numeric-range should make this pretty quick to implement.
