### ISSUE TITLE
[pages] - How to get a preview URL to create a comment in PR using this

### ISSUE THREAD

**Issue by rafaellucio** [cloudflare/cloudflare-docs#877]
Hi guys,

I need to create a new comment in GitHub with a preview URL generated by Cloudflare Pages, how I can get this preview URL after the build to create a comment using preview URL?

**Comment by kristianfreeman** [comment]
Hey @rafaellucio - Pages comments on PRs with a preview URL when a build completes. Here's an example below!

https://github.com/signalnerve/developer-discords/pull/4#issuecomment-796838467

**Comment by Disneimabong** [comment]
Why i cant review URL website Account  in browser

**Comment by Disneimabong** [comment]
Preview and productive proses access server active

Pada Sab, 27 Mac 2021 2:41 PTG Disneimabong ***@***.***>
menulis:

**Comment by KimJ15** [comment]
👋 @Disneimabong  Hi there - please feel free to reach out to community.cloudflare.com for additional support. Thanks!
