### ISSUE TITLE
Can Turnstile be implemented into a native iOS/Android app, using a WebView?

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/cloudflare-docs#8777]
### Which Cloudflare product does this pertain to?

Turnstile

### Existing documentation URL(s)

- https://developers.cloudflare.com/turnstile/frequently-asked-questions/ (https://github.com/cloudflare/cloudflare-docs/blob/production/content/turnstile/frequently-asked-questions.md#enroll-beta)

### Section that requires update

The main section

### What needs to change?

Can Turnstile be implemented into a native iOS/Android app, using a WebView?

### How should it change?

Add an explanation

**Comment by LinusU** [comment]
They are already mentioning React Native, whose `WebView` is a wrapper for the platforms native WebViews, so it should work:

<img width="907" alt="Screenshot 2023-05-09 at 14 11 16" src="https://user-images.githubusercontent.com/189580/237009180-16d423cf-8be6-43c6-b73c-deae4ff10c05.png">

Maybe some slightly tweaking of this question would make that more apparent...

**Comment by KimJ15** [comment]
Hi there - This looks like a feature request. We have shared your issue with the team so this is now being tracked internally. Closing this ticket.

**Comment by a-eid** [comment]
any updates on this ?

**Comment by creix** [comment]
+1
