### ISSUE TITLE
Add documentation for workers.dev under Routes

### ISSUE THREAD

**Issue by neynah** [cloudflare/cloudflare-docs#878]
To make it easier for users to understand what workers.dev is for especially in the context of routes we should add a "workers.dev" section to the [Routes documentation](https://developers.cloudflare.com/workers/platform/routes). We'll be linking directly to this content from the dashboard.

I can draft some content as a starting point. CC @sgraden @mpint

**Comment by kristianfreeman** [comment]
hey @neynah - still think this is worth doing? looking at the routes page, it looks like there may be a good opportunity to mention workers.dev at the beginning as an alternative to deploying to custom domains. did you want to take a stab at writing the content here, or am i misunderstanding what sort of copy you thought should be added here?

**Comment by neynah** [comment]
Sorry for the late follow up on this!

Yes, I think it's still worth adding to the routes page as we only mention the purpose of workers.dev once (during the onboarding flow). Borrowing some content from the getting started guide maybe something along the lines of:

`Your Cloudflare account comes with a workers.dev subdomain that is configurable during the Workers onboarding flow and from the dashboard sidebar. You can deploy Workers on this subdomain without any DNS configuration. The name field of a Worker is used as the secondary subdomain for the deployed script, e.g. my-worker.my-subdomain.workers.dev.`

**Comment by kristianfreeman** [comment]
cc @deadlypants1973 for adding this copy

**Comment by lovely69420** [comment]
![Uploading 11530_uhd.jpg…]()
