### ISSUE TITLE
Firewall Rules pages don't detail free/pro/enterprise restrictions on Fields

### ISSUE THREAD

**Issue by bulk88** [cloudflare/cloudflare-docs#8848]
### Which Cloudflare product does this pertain to?

Firewall

### Existing documentation URL(s)

https://developers.cloudflare.com/ruleset-engine/rules-language/fields/#dynamic-fields

### Section that requires update

Entire page.

### What needs to change?

Better info which fields are available to which CF plans, free/pro/enterprise/KV/workers/bot manangement/other add ons. Its too easy to write firewall rules for fields that are always NULL/empty/not present.

### How should it change?

All the JSON/ cf.someThing request fields for WAF rules, need tags describing if the field is free/pro/enterprise/other addons for every field, field by field, just like Boolean/String/Number/Array tags.

For example, 

About "cf.threat_score" or "cf.client.bot", for example, I'm not sure those fields, are or are not, available on free tier.

I do see that on Dynamic Fields page there is,

```
Notes
Access to cf.bot_management.* fields requires a Cloudflare Enterprise plan with [Bot Management](https://developers.cloudflare.com/bots/plans/bm-subscription/) enabled.
```
But I think that that Notes box isn't easy to find on that long docs page, and it can get out of date fast as CF adds new features and fields over the years.

**Comment by kodster28** [comment]
Howdy @bulk88, definitely hear that frustration, but that request isn’t something we can commit to maintaining in our documentation at this current point in time. As you mentioned, information on something as granular as fields per plan can get out of date quickly.

We'll take your feedback into account and discuss internally to see if there's another way we could provide this information in a way that's more maintainable.

Your best current workaround here is reviewing fields w/in the UI dropdown in specific zones and using that as your source of truth.
