### ISSUE TITLE
Pages: mdBook is in Framework preset but not supported yet

### ISSUE THREAD

**Issue by ontouchstart** [cloudflare/cloudflare-docs#885]
See screenshots.

<img width="481" alt="Screen Shot 2021-03-04 at 11 14 53 PM" src="https://user-images.githubusercontent.com/41637129/110066666-00d0e080-7d40-11eb-926c-9136fd2110a9.png">
<img width="807" alt="Screen Shot 2021-03-04 at 11 15 19 PM" src="https://user-images.githubusercontent.com/41637129/110066671-04646780-7d40-11eb-898c-7b20e2fec82f.png">
<img width="1067" alt="Screen Shot 2021-03-04 at 11 17 44 PM" src="https://user-images.githubusercontent.com/41637129/110066678-06c6c180-7d40-11eb-8246-b202fa65e9ea.png">

**Comment by bendoerry** [comment]
I've come across a similar issue for Zola

**Comment by bendoerry** [comment]
I've managed to fix the issue for Zola by adding the environment variable `ZOLA_VERSION = 0.13.0`.
You could potentially try the same thing with an equivalent `MDBOOK_VERSION`?

**Comment by JakeChampion** [comment]
> I've managed to fix the issue for Zola by adding the environment variable `ZOLA_VERSION = 0.13.0`.

Wow okay that worked for me as well! Thank you for figuring this out and for also posting the working solution onto this issue ☺️

**Comment by ontouchstart** [comment]
> I've managed to fix the issue for Zola by adding the environment variable `ZOLA_VERSION = 0.13.0`.
> You could potentially try the same thing with an equivalent `MDBOOK_VERSION`?

Thanks for the tip. 

Since I am adding more customized crates to the build step of my own [mdBook](https://ontouchstart.pages.dev) via a [Makefile](https://github.com/ontouchstart/cloudflare-page/blob/master/Makefile), unless CloudFlare offers a general purpose rust/cargo toolchain, I will stick to local build for the time being.

Look forward to more mature CF Pages build framework in the future. Thanks for the hard work of CF teams.

**Comment by whymehrotra** [comment]
Hi @ontouchstart
The problem you stated is still present. I was wondering why you closed the issue?

@JakeChampion Did you manage to get mdbook running? Adding MDBOOK_VERSION = 0.4.6 does nothing for me.

**Comment by whymehrotra** [comment]
Using the following build command, did the trick for me:
`curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build`

This way is not the cleanest (and operating under assumption that x86_64 is the backing architecture for Cloudflare Pages build infrastructure)

**Comment by qaqland** [comment]
Cloudflare Pages Offical should add this😫
