### ISSUE TITLE
Cloudflare Pages with custom domain not use strict https

### ISSUE THREAD

**Issue by Viteok** [cloudflare/cloudflare-docs#887]
Cloudflare Pages with a custom domain not use **strict SSL**

1. Custom domain is registered at Cloudflare
2. On Cloudflare pages I Deploy a Gatsby site (work fine)
3. After I add a CNAME record to my domain
4. Everything it's ok, but can't use strict SSL 

![ssl](https://user-images.githubusercontent.com/9491631/110129128-44732b00-7dd0-11eb-858c-a9f95cf75823.png)

**Comment by alexeyzimarev** [comment]
Choose your side from the dashboard left menu, then click on SSL (same dashboard menu where you click on DNS). Then, switch to the Edge Certificates tab.

Honestly, it's not the docs issue.

![image](https://user-images.githubusercontent.com/2821205/114178233-b72a7580-993d-11eb-9f54-d4ca2cf9241f.png)
