### ISSUE TITLE
Zero Trust tunnel config example uses resources from 

### ISSUE THREAD

**Issue by gtebbutt** [cloudflare/cloudflare-docs#8877]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/terraform/

### Section that requires update

Section "Configure Cloudflare resources", which covers the content of the `Cloudflare-config.tf` terraform file

### What needs to change?

The example is based around a `cloudflare_argo_tunnel` resource, which no longer exists as of version 4 of the terraform provider. 

### How should it change?

Update to use the current `cloudflare_tunnel` and `cloudflare_tunnel_config` terraform resources would be great - I haven't been able to find a worked example of `cloudflare_tunnel_config` with terraform anywhere online.

**Comment by ranbel** [comment]
addressed in #10442
