### ISSUE TITLE
Custom Player API Docs link dead

### ISSUE THREAD

**Issue by sebszocinski** [cloudflare/cloudflare-docs#89]
https://developers.cloudflare.com/stream/video-playback/player-api/

Linked to from [here](https://developers.cloudflare.com/stream/player-and-playback#building-a-custom-user-interface) and in google search results.

**Comment by renandincer** [comment]
https://developers.cloudflare.com/stream/player-and-playback/player-sdk is where the API is right now.

Sorry about this, we're moving the pages around this week to make docs more clear.

**Comment by renandincer** [comment]
Thank you for opening an issue! @sebszocinski
