### ISSUE TITLE
Fix Table of Contents clipping in R2 API docs

### ISSUE THREAD

**Issue by bthwaites** [cloudflare/cloudflare-docs#8901]
### Example URL(s)

https://developers.cloudflare.com/r2/api/s3/api/

Specifically this section: https://developers.cloudflare.com/r2/api/s3/api/#unimplemented-bucket-level-operations

The table is collapsed by default. Expand the table to see the problem.

### Actual Behavior

The Table of Contents on the right side of the page is clipping through the table of unimplemented bucket-level operations.

![image](https://github.com/cloudflare/cloudflare-docs/assets/29320367/ad1ec4bd-d2f5-491e-a55d-8f1c7bba02b8)

### Expected Behavior

The table of unimplemented bucket-level operations shouldn't clip through the Table of Contents.

**Comment by KimJ15** [comment]
We are actually working on strategies related to presenting consistent examples, so I will share your post with the team. That project is not in Github, so I will close this issue out since an open source contributor can't work on this.
