### ISSUE TITLE
CloudFlare protected Websites

### ISSUE THREAD

**Issue by GableTheSnail** [cloudflare/cloudflare-docs#8916]
### Which Cloudflare product(s) does this pertain to?

Magic Firewall

### Subject Matter

Cloudflare Websites

### Content Location

Not sure, any place, I guess.

### Additional information

Hi there!

It would be nice if there were a published list of websites protected by CloudFlare such that all the websites using CloudFlare could be bulk-banned from being browsed. Could such a list be made public? Perhaps even anonymized in some way such that we do not even need to care who exactly is using CloudFlare. Clearly, many times there are other websites that provide the exact same content, such that no website is worth your time going through Captcha prompts in order to access the same content.

Thank you!

**Comment by kodster28** [comment]
Heyo @cxtal, this is a documentation repo and that sounds more like a feature request to our product team.
(also, one I doubt they'd act on, as it'd make using CF on a site a nonstarter).

If you really wanted to keep track of something like that on your own, you could install the [Claire](https://chrome.google.com/webstore/detail/claire/fgbpcgddpmjmamlibbaobboigaijnmkl) extension in Chrome, though it's more on an individual level.
