### ISSUE TITLE
[missing documentation] Connecting Github

### ISSUE THREAD

**Issue by lanec** [cloudflare/cloudflare-docs#893]
In this section: https://github.com/cloudflare/cloudflare-docs/blob/production/products/pages/src/content/getting-started/index.md#connect-to-github

I am asked to connect to github. It does not specify a working URL that I should use for this. 

Can you expand on this step? 

Here is what I see when I click the link in this step: https://cloud.strapr.com/P8ukK5od

**Comment by KimJ15** [comment]
Hi @lanec - Thanks for contributing to our documentation. This doesn't look like an improvement to developers.cloudflare.com documentation! Please reach out to community.cloudflare.com for additional support. Thanks!
