### ISSUE TITLE
Updated screenshots for Sumo Logic integration

### ISSUE THREAD

**Issue by sumo-drew** [cloudflare/cloudflare-docs#8941]
### Which Cloudflare product does this pertain to?

1.1.1.1

### Existing documentation URL(s)

https://github.com/cloudflare/cloudflare-docs/blob/production/content/fundamentals/data-products/analytics-integrations/sumo-logic/index.md

### Section that requires update

All screenshots are now outdated. We have new screenshots available for each image in our updated documentation here - https://help.sumologic.com/docs/integrations/saas-cloud/cloudflare/#snapshot

### What needs to change?

Each screenshot on the index.md page

### How should it change?

With the new screenshots here - https://help.sumologic.com/docs/integrations/saas-cloud/cloudflare/#snapshot

**Comment by angelampcosta** [comment]
Thanks for letting us know @sumo-drew . We're actually in the process of addressing this issue now, and you should see updated content soon!
