### ISSUE TITLE
Testing multiple workers: Missing documentation

### ISSUE THREAD

**Issue by amiller68** [cloudflare/cloudflare-docs#8980]
### Which Cloudflare product(s) does this pertain to?

API

### Subject Matter

unstable_dev API

### Content Location

This documentation for testing multiple workers should note that ordering on initialization matters for parents and children: https://developers.cloudflare.com/workers/wrangler/api/#unstable_dev

i.e. starting parents -> then children will make your tests fail

**Comment by penalosa** [comment]
Thanks for raising this! The initialisation order shouldn't matter when using `unstable_dev` (or `wrangler dev` directly)—if it does that's a bug in Wrangler we should fix. Would you be able to open an issue on the https://github.com/cloudflare/cloudflare/workers-sdk repo with a minimal reproduction of the issue?
