### ISSUE TITLE
Ed25519 and X25519 documentation missing

### ISSUE THREAD

**Issue by chocolatkey** [cloudflare/cloudflare-docs#9018]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

2023-04-28 Secure Curves algorithms

### Content Location

https://developers.cloudflare.com/workers/runtime-apis/web-crypto/

**Comment by irvinebroque** [comment]
@fhanau can you update docs? refs https://github.com/cloudflare/workerd/pull/500

**Comment by fhanau** [comment]
Sure, I'll try to make a PR later today
