### ISSUE TITLE
update warp device posture check for manual deploy 

### ISSUE THREAD

**Issue by jeankhawand** [cloudflare/cloudflare-docs#9045]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/devices/warp-client-checks/device-uuid/
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/6d3615ae84f53738ec170a18e01e4ede237b3d00/content/cloudflare-one/identity/devices/warp-client-checks/device-uuid.md?plain=1#L22-L26

### What needs to change?

within  `1. Assign UUIDs to devices` step it is mentioned MDM which is related to automatic deploy while for manual deploy there is no clear path how to assign uuid for devices.

- having trouble setup warp client check specifically `Device UUID` - is it tight to automatic deployment ? if yes, what about manual deploy ?
- when referring to Device UUID isn't it enough the one mentioned in a specific device page (Registration Id) by heading to My Team > Devices > click on a specific device ? is there any other way to generate UUID for a device from warp client ?

### How should it change?

have two distinct path for both automatic and manual deploy when dealing with warp client check

**Comment by ranbel** [comment]
Hi, at this time device UUID is only supported for automated deployments. I have added a note in #9425.
