### ISSUE TITLE
Document I/O limitations

### ISSUE THREAD

**Issue by penalosa** [cloudflare/cloudflare-docs#9069]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/platform/limits/

### Section that requires update

A section should be added

### What needs to change?

Commonly, customers try and do things in the global scope which isn't allowed, and receive an error from the API like this:

```
Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request
```

As far as I can tell, this limitation isn't documented on the Limits page for Workers, or anywhere else on the Workers docs

### How should it change?

This error message should be explained, and the top-level I/O limits should be explained (especially in cases where it's non obvious, like constructing a `Response` object)

**Comment by KimJ15** [comment]
This is a pretty stale issue and I can't tell what's changed! If updates need to be made, can a PR opened in the docs on this page? https://developers.cloudflare.com/workers/platform/limits/
