### ISSUE TITLE
Better examples and common errors footnotes.

### ISSUE THREAD

**Issue by ayushchauhan101** [cloudflare/cloudflare-docs#9096]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/examples/return-html/
https://developers.cloudflare.com/workers/examples/cors-header-proxy/

### Section that requires update

Examples

### What needs to change?

Documentation

### How should it change?

- [ ] Create new workers examples
- [ ] Give more explainations
- [ ] Give common errors and fixes corresponding to the examples in a footnotes.

### Additional information

Being a first time user of cloudflare workers, the example and one liner explanation does not feel enough.
In the link [https://developers.cloudflare.com/workers/examples/return-html/](url)
>Deliver an HTML page from an HTML string directly inside the Worker script.

This does not outright explain if explicitly adding the **'Content-type'** is mandatory or not.
On hoppscoth, postman and other similar applications the response header still remain **'text/html'** even if not defined in the code.

In the link [https://developers.cloudflare.com/workers/examples/cors-header-proxy/](url)
>Add the necessary CORS headers to a third party API response

This documentation could also give a new and concise example in the beginning to show why  adding **CORS** is important.

 _While developing i encountered CORB and CORS error and a new example would have helped a lot, while also mentioning troubleshooting oppurtunities._

**Comment by penalosa** [comment]
Thanks for raising this, @ayushchauhan101!
- Setting the `content-type` header to `text/html` is mandatory if you want user agents to interpret your response as HTML. Without setting it explicitly, it will default to `text/plain`.
- For a general overview of CORS, [this MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_response_headers) is a good start. The CORS header proxy example is specifically for adding CORS headers to a third party API—if you just want your Worker to be accessible from different origins then you should be able to find the right headers for your use case in the MDN article. However, it's worth noting that returning HTML documents will likely not require any CORS headers
