### ISSUE TITLE
[Cache] External links lead to 404 page on content.cloudflare.com

### ISSUE THREAD

**Issue by kev-ac** [cloudflare/cloudflare-docs#9142]
### Example URL(s)

- https://developers.cloudflare.com/cache/cache-security/avoid-web-poisoning/

### Actual Behavior

(At least) on this page there are three external links which all lead to a 404 error page on `https://content.cloudflare.com/{some-random-id}`.

For example the "Symfony Security Advisories" leads to [https://content.cloudflare.com/o02lI00iN00c0X000CSZ0O0](https://content.cloudflare.com/o02lI00iN00c0X000CSZ0O0).

Page content:
```
404 Not Found

The redirect url is empty
```

### Expected Behavior

Link to external URL

**Comment by angelampcosta** [comment]
Thanks @kev-ac! Links were updated.
