### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-docs#9144]
### Example URL(s)

https://www.wlcp-db.com

Error- This page isn’t workingwww.wlcp-db.com redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

### Actual Behavior

I cannot get into administer the streaming services for www.wlcp-db.com

74.207.228.11

74.207.228.11
--

</body>
</html>RUNNING

Summary
2 CPU Cores

80 GB Storage

4 GB RAM

0 Volumes

IP Addresses
74.207.228.11

2600:3c02::f03c:93ff:fe75:e365

[View all IP Addresses](https://cloud.linode.com/linodes/45313524/networking#ips)

Access
SSH Access
ssh root@74.207.228.11

LISH Console via SSH
ssh -t daveterry1953@lish-us-southeast.linode.com azuracast-us-southeast-001

Plan:
Dedicated 4 GB

Region:
Atlanta, GA

Linode ID:
45313524

Created:
2023-04-20 01:08

Add a tag

74.207.228.11
--

</html>RUNNING

Summary
2 CPU Cores

80 GB Storage

4 GB RAM

0 Volumes

IP Addresses
74.207.228.11

2600:3c02::f03c:93ff:fe75:e365

[View all IP Addresses](https://cloud.linode.com/linodes/45313524/networking#ips)

Access
SSH Access
ssh root@74.207.228.11

LISH Console via SSH
ssh -t daveterry1953@lish-us-southeast.linode.com azuracast-us-southeast-001

Plan:
Dedicated 4 GB

Region:
Atlanta, GA

Linode ID:
45313524

Created:
2023-04-20 01:08

Add a tag
SMTP ports may be restricted on this Linode. Need to send email? Review our [mail server guide](https://www.linode.com/docs/email/best-practices/running-a-mail-server/), then [open a support ticket](https://cloud.linode.com/support/tickets).

[Analytics](https://cloud.linode.com/linodes/45313524/analytics)
[Network](https://cloud.linode.com/linodes/45313524/networking)
[Storage](https://cloud.linode.com/linodes/45313524/storage)
[Configurations](https://cloud.linode.com/linodes/45313524/configurations)
[Backups](https://cloud.linode.com/linodes/45313524/backup)
[Activity Feed](https://cloud.linode.com/linodes/45313524/activity)
[Settings](https://cloud.linode.com/linodes/45313524/settings)
Monthly Network Transfer

azuracast-us-southeast-001 (1.97 GB)

Remaining (3998 GB)

Network Transfer History (Mb/s)

Last 30 Days

Time	Public Outbound Traffic
4/30/2023, 12:00 AM	0.00Kb/s
4/30/2023, 2:00 AM	0.00Kb/s
4/30/2023, 4:00 AM	0.00Kb/s
4/30/2023, 6:00 AM	0.00Kb/s
4/30/2023, 8:00 AM	0.00Kb/s
4/30/2023, 10:00 AM	0.00Kb/s
4/30/2023, 12:00 PM	0.00Kb/s
4/30/2023, 2:00 PM	0.00Kb/s
4/30/2023, 4:00 PM	0.00Kb/s
4/30/2023, 6:00 PM	0.00Kb/s
4/30/2023, 8:00 PM	0.00Kb/s
4/30/2023, 10:00 PM	0.00Kb/s
5/1/2023, 12:00 AM	0.00Kb/s
5/1/2023, 2:00 AM	0.00Kb/s
5/1/2023, 4:00 AM	0.00Kb/s
5/1/2023, 6:00 AM	0.00Kb/s
5/1/2023, 8:00 AM	0.00Kb/s
5/1/2023, 10:00 AM	0.00Kb/s
5/1/2023, 12:00 PM	0.00Kb/s
5/1/2023, 2:00 PM	0.00Kb/s
5/1/2023, 4:00 PM	0.00Kb/s
5/1/2023, 6:00 PM	0.00Kb/s
5/1/2023, 8:00 PM	0.00Kb/s
5/1/2023, 10:00 PM	0.01Kb/s
5/2/2023, 12:00 AM	0.00Kb/s
5/2/2023, 2:00 AM	0.00Kb/s
5/2/2023, 4:00 AM	0.00Kb/s
5/2/2023, 6:00 AM	0.00Kb/s
5/2/2023, 8:00 AM	0.00Kb/s
5/2/2023, 10:00 AM	0.00Kb/s
5/2/2023, 12:00 PM	0.00Kb/s
5/2/2023, 2:00 PM	0.00Kb/s
5/2/2023, 4:00 PM	0.00Kb/s
5/2/2023, 6:00 PM	0.00Kb/s
5/2/2023, 8:00 PM	0.00Kb/s
5/2/2023, 10:00 PM	0.00Kb/s
5/3/2023, 12:00 AM	0.00Kb/s
5/3/2023, 2:00 AM	0.00Kb/s
5/3/2023, 4:00 AM	0.00Kb/s
5/3/2023, 6:00 AM	0.00Kb/s
5/3/2023, 8:00 AM	0.00Kb/s
5/3/2023, 10:00 AM	0.00Kb/s
5/3/2023, 12:00 PM	0.00Kb/s
5/3/2023, 2:00 PM	0.00Kb/s
5/3/2023, 4:00 PM	0.00Kb/s
5/3/2023, 6:00 PM	0.01Kb/s
5/3/2023, 8:00 PM	0.00Kb/s
5/3/2023, 10:00 PM	0.00Kb/s
5/4/2023, 12:00 AM	0.03Kb/s
5/4/2023, 2:00 AM	0.00Kb/s
5/4/2023, 4:00 AM	0.00Kb/s
5/4/2023, 6:00 AM	0.00Kb/s
5/4/2023, 8:00 AM	0.00Kb/s
5/4/2023, 10:00 AM	0.00Kb/s
5/4/2023, 12:00 PM	0.00Kb/s
5/4/2023, 2:00 PM	0.00Kb/s
5/4/2023, 4:00 PM	0.00Kb/s
5/4/2023, 6:00 PM	0.02Kb/s
5/4/2023, 8:00 PM	0.00Kb/s
5/4/2023, 10:00 PM	0.00Kb/s
5/5/2023, 12:00 AM	0.00Kb/s
5/5/2023, 2:00 AM	0.00Kb/s
5/5/2023, 4:00 AM	0.00Kb/s
5/5/2023, 6:00 AM	0.00Kb/s
5/5/2023, 8:00 AM	0.00Kb/s
5/5/2023, 10:00 AM	0.00Kb/s
5/5/2023, 12:00 PM	0.00Kb/s
5/5/2023, 2:00 PM	0.00Kb/s
5/5/2023, 4:00 PM	0.00Kb/s
5/5/2023, 6:00 PM	0.00Kb/s
5/5/2023, 8:00 PM	0.00Kb/s
5/5/2023, 10:00 PM	0.00Kb/s
5/6/2023, 12:00 AM	0.00Kb/s
5/6/2023, 2:00 AM	0.00Kb/s
5/6/2023, 4:00 AM	0.00Kb/s
5/6/2023, 6:00 AM	0.00Kb/s
5/6/2023, 8:00 AM	0.00Kb/s
5/6/2023, 10:00 AM	0.00Kb/s
5/6/2023, 12:00 PM	0.00Kb/s
5/6/2023, 2:00 PM	0.00Kb/s
5/6/2023, 4:00 PM	0.00Kb/s
5/6/2023, 6:00 PM	0.00Kb/s
5/6/2023, 8:00 PM	0.00Kb/s
5/6/2023, 10:00 PM	0.00Kb/s
5/7/2023, 12:00 AM	0.00Kb/s
5/7/2023, 2:00 AM	0.00Kb/s
5/7/2023, 4:00 AM	0.00Kb/s
5/7/2023, 6:00 AM	0.00Kb/s
5/7/2023, 8:00 AM	0.00Kb/s
5/7/2023, 10:00 AM	0.00Kb/s
5/7/2023, 12:00 PM	0.00Kb/s
5/7/2023, 2:00 PM	0.00Kb/s
5/7/2023, 4:00 PM	0.00Kb/s
5/7/2023, 6:00 PM	0.00Kb/s
5/7/2023, 8:00 PM	0.00Kb/s
5/7/2023, 10:00 PM	0.00Kb/s
5/8/2023, 12:00 AM	0.00Kb/s
5/8/2023, 2:00 AM	0.00Kb/s
5/8/2023, 4:00 AM	0.00Kb/s
5/8/2023, 6:00 AM	0.00Kb/s
5/8/2023, 8:00 AM	0.00Kb/s
5/8/2023, 10:00 AM	0.00Kb/s
5/8/2023, 12:00 PM	0.00Kb/s
5/8/2023, 2:00 PM	0.00Kb/s
5/8/2023, 4:00 PM	0.00Kb/s
5/8/2023, 6:00 PM	0.00Kb/s
5/8/2023, 8:00 PM	0.00Kb/s
5/8/2023, 10:00 PM	0.00Kb/s
5/9/2023, 12:00 AM	0.00Kb/s
5/9/2023, 2:00 AM	0.00Kb/s
5/9/2023, 4:00 AM	0.00Kb/s
5/9/2023, 6:00 AM	0.00Kb/s
5/9/2023, 8:00 AM	0.00Kb/s
5/9/2023, 10:00 AM	0.00Kb/s
5/9/2023, 12:00 PM	0.00Kb/s
5/9/2023, 2:00 PM	0.00Kb/s
5/9/2023, 4:00 PM	0.00Kb/s
5/9/2023, 6:00 PM	0.00Kb/s
5/9/2023, 8:00 PM	0.00Kb/s
5/9/2023, 10:00 PM	0.00Kb/s
5/10/2023, 12:00 AM	0.00Kb/s
5/10/2023, 2:00 AM	0.00Kb/s
5/10/2023, 4:00 AM	0.00Kb/s
5/10/2023, 6:00 AM	0.00Kb/s
5/10/2023, 8:00 AM	0.00Kb/s
5/10/2023, 10:00 AM	0.00Kb/s
5/10/2023, 12:00 PM	0.00Kb/s
5/10/2023, 2:00 PM	0.00Kb/s
5/10/2023, 4:00 PM	0.01Kb/s
5/10/2023, 6:00 PM	0.00Kb/s
5/10/2023, 8:00 PM	0.00Kb/s
5/10/2023, 10:00 PM	0.00Kb/s
5/11/2023, 12:00 AM	0.00Kb/s
5/11/2023, 2:00 AM	0.00Kb/s
5/11/2023, 4:00 AM	0.00Kb/s
5/11/2023, 6:00 AM	0.00Kb/s
5/11/2023, 8:00 AM	0.00Kb/s
5/11/2023, 10:00 AM	0.00Kb/s
5/11/2023, 12:00 PM	0.00Kb/s
5/11/2023, 2:00 PM	0.00Kb/s
5/11/2023, 4:00 PM	0.00Kb/s
5/11/2023, 6:00 PM	0.00Kb/s
5/11/2023, 8:00 PM	0.00Kb/s
5/11/2023, 10:00 PM	0.00Kb/s
5/12/2023, 12:00 AM	0.00Kb/s
5/12/2023, 2:00 AM	0.00Kb/s
5/12/2023, 4:00 AM	0.00Kb/s
5/12/2023, 6:00 AM	0.00Kb/s
5/12/2023, 8:00 AM	0.00Kb/s
5/12/2023, 10:00 AM	0.00Kb/s
5/12/2023, 12:00 PM	0.00Kb/s
5/12/2023, 2:00 PM	0.00Kb/s
5/12/2023, 4:00 PM	0.00Kb/s
5/12/2023, 6:00 PM	0.00Kb/s
5/12/2023, 8:00 PM	0.00Kb/s
5/12/2023, 10:00 PM	0.00Kb/s
5/13/2023, 12:00 AM	0.00Kb/s
5/13/2023, 2:00 AM	0.00Kb/s
5/13/2023, 4:00 AM	0.00Kb/s
5/13/2023, 6:00 AM	0.00Kb/s
5/13/2023, 8:00 AM	0.00Kb/s
5/13/2023, 10:00 AM	0.00Kb/s
5/13/2023, 12:00 PM	0.00Kb/s
5/13/2023, 2:00 PM	0.00Kb/s
5/13/2023, 4:00 PM	0.00Kb/s
5/13/2023, 6:00 PM	0.00Kb/s
5/13/2023, 8:00 PM	0.00Kb/s
5/13/2023, 10:00 PM	0.00Kb/s
5/14/2023, 12:00 AM	0.00Kb/s
5/14/2023, 2:00 AM	0.00Kb/s
5/14/2023, 4:00 AM	0.00Kb/s
5/14/2023, 6:00 AM	0.00Kb/s
5/14/2023, 8:00 AM	0.00Kb/s
5/14/2023, 10:00 AM	0.00Kb/s
5/14/2023, 12:00 PM	0.00Kb/s
5/14/2023, 2:00 PM	0.00Kb/s
5/14/2023, 4:00 PM	0.00Kb/s
5/14/2023, 6:00 PM	0.00Kb/s
5/14/2023, 8:00 PM	0.00Kb/s
5/14/2023, 10:00 PM	0.00Kb/s
5/15/2023, 12:00 AM	0.00Kb/s
5/15/2023, 2:00 AM	0.00Kb/s
5/15/2023, 4:00 AM	0.00Kb/s
5/15/2023, 6:00 AM	0.00Kb/s
5/15/2023, 8:00 AM	0.00Kb/s
5/15/2023, 10:00 AM	0.00Kb/s
5/15/2023, 12:00 PM	0.00Kb/s
5/15/2023, 2:00 PM	0.00Kb/s
5/15/2023, 4:00 PM	0.00Kb/s
5/15/2023, 6:00 PM	0.00Kb/s
5/15/2023, 8:00 PM	0.00Kb/s
5/15/2023, 10:00 PM	0.00Kb/s
5/16/2023, 12:00 AM	0.00Kb/s
5/16/2023, 2:00 AM	0.00Kb/s
5/16/2023, 4:00 AM	0.00Kb/s
5/16/2023, 6:00 AM	0.00Kb/s
5/16/2023, 8:00 AM	0.00Kb/s
5/16/2023, 10:00 AM	0.00Kb/s
5/16/2023, 12:00 PM	0.00Kb/s
5/16/2023, 2:00 PM	0.00Kb/s
5/16/2023, 4:00 PM	0.00Kb/s
5/16/2023, 6:00 PM	0.00Kb/s
5/16/2023, 8:00 PM	0.00Kb/s
5/16/2023, 10:00 PM	0.00Kb/s
5/17/2023, 12:00 AM	0.00Kb/s
5/17/2023, 2:00 AM	0.00Kb/s
5/17/2023, 4:00 AM	0.00Kb/s
5/17/2023, 6:00 AM	0.00Kb/s
5/17/2023, 8:00 AM	0.00Kb/s
5/17/2023, 10:00 AM	0.00Kb/s
5/17/2023, 12:00 PM	0.00Kb/s
5/17/2023, 2:00 PM	0.00Kb/s
5/17/2023, 4:00 PM	0.00Kb/s
5/17/2023, 6:00 PM	0.00Kb/s
5/17/2023, 8:00 PM	0.00Kb/s
5/17/2023, 10:00 PM	0.00Kb/s
5/18/2023, 12:00 AM	0.00Kb/s
5/18/2023, 2:00 AM	0.00Kb/s
5/18/2023, 4:00 AM	0.00Kb/s
5/18/2023, 6:00 AM	0.00Kb/s
5/18/2023, 8:00 AM	0.00Kb/s
5/18/2023, 10:00 AM	0.00Kb/s
5/18/2023, 12:00 PM	0.00Kb/s
5/18/2023, 2:00 PM	0.00Kb/s
5/18/2023, 4:00 PM	0.00Kb/s
5/18/2023, 6:00 PM	0.00Kb/s
5/18/2023, 8:00 PM	0.00Kb/s
5/18/2023, 10:00 PM	0.00Kb/s
5/19/2023, 12:00 AM	0.00Kb/s
5/19/2023, 2:00 AM	0.00Kb/s
5/19/2023, 4:00 AM	0.00Kb/s
5/19/2023, 6:00 AM	0.00Kb/s
5/19/2023, 8:00 AM	0.00Kb/s
5/19/2023, 10:00 AM	0.00Kb/s
5/19/2023, 12:00 PM	0.00Kb/s
5/19/2023, 2:00 PM	0.00Kb/s
5/19/2023, 4:00 PM	0.00Kb/s
5/19/2023, 6:00 PM	0.00Kb/s
5/19/2023, 8:00 PM	0.00Kb/s
5/19/2023, 10:00 PM	0.00Kb/s
5/20/2023, 12:00 AM	0.00Kb/s
5/20/2023, 2:00 AM	0.00Kb/s
5/20/2023, 4:00 AM	0.00Kb/s
5/20/2023, 6:00 AM	0.00Kb/s
5/20/2023, 8:00 AM	0.00Kb/s
5/20/2023, 10:00 AM	0.00Kb/s
5/20/2023, 12:00 PM	0.00Kb/s
5/20/2023, 2:00 PM	0.00Kb/s
5/20/2023, 4:00 PM	0.00Kb/s
5/20/2023, 6:00 PM	0.00Kb/s
5/20/2023, 8:00 PM	0.00Kb/s
5/20/2023, 10:00 PM	0.00Kb/s
5/21/2023, 12:00 AM	0.00Kb/s
5/21/2023, 2:00 AM	0.00Kb/s
5/21/2023, 4:00 AM	0.00Kb/s
5/21/2023, 6:00 AM	0.00Kb/s
5/21/2023, 8:00 AM	0.00Kb/s
5/21/2023, 10:00 AM	0.00Kb/s
5/21/2023, 12:00 PM	0.00Kb/s
5/21/2023, 2:00 PM	0.00Kb/s
5/21/2023, 4:00 PM	0.00Kb/s
5/21/2023, 6:00 PM	0.00Kb/s
5/21/2023, 8:00 PM	0.00Kb/s
5/21/2023, 10:00 PM	0.07Kb/s
5/22/2023, 12:00 AM	0.00Kb/s
5/22/2023, 2:00 AM	0.00Kb/s
5/22/2023, 4:00 AM	0.00Kb/s
5/22/2023, 6:00 AM	0.00Kb/s
5/22/2023, 8:00 AM	0.00Kb/s
5/22/2023, 10:00 AM	0.00Kb/s
5/22/2023, 12:00 PM	0.00Kb/s
5/22/2023, 2:00 PM	0.00Kb/s
5/22/2023, 4:00 PM	0.00Kb/s
5/22/2023, 6:00 PM	0.00Kb/s
5/22/2023, 8:00 PM	0.00Kb/s
5/22/2023, 10:00 PM	0.00Kb/s
5/23/2023, 12:00 AM	0.00Kb/s
5/23/2023, 2:00 AM	0.00Kb/s
5/23/2023, 4:00 AM	0.00Kb/s
5/23/2023, 6:00 AM	0.00Kb/s
5/23/2023, 8:00 AM	0.00Kb/s
5/23/2023, 10:00 AM	0.00Kb/s
5/23/2023, 12:00 PM	0.00Kb/s
5/23/2023, 2:00 PM	0.00Kb/s
5/23/2023, 4:00 PM	0.00Kb/s
5/23/2023, 6:00 PM	0.00Kb/s
5/23/2023, 8:00 PM	0.00Kb/s
5/23/2023, 10:00 PM	0.00Kb/s
5/24/2023, 12:00 AM	0.00Kb/s
5/24/2023, 2:00 AM	0.00Kb/s
5/24/2023, 4:00 AM	0.00Kb/s
5/24/2023, 6:00 AM	0.00Kb/s
5/24/2023, 8:00 AM	0.00Kb/s
5/24/2023, 10:00 AM	0.00Kb/s
5/24/2023, 12:00 PM	0.00Kb/s
5/24/2023, 2:00 PM	0.00Kb/s
5/24/2023, 4:00 PM	0.00Kb/s
5/24/2023, 6:00 PM	0.00Kb/s
5/24/2023, 8:00 PM	0.00Kb/s
5/24/2023, 10:00 PM	0.00Kb/s
5/25/2023, 12:00 AM	0.05Kb/s
5/25/2023, 2:00 AM	0.01Kb/s
5/25/2023, 4:00 AM	0.00Kb/s
5/25/2023, 6:00 AM	0.00Kb/s
5/25/2023, 8:00 AM	0.00Kb/s
5/25/2023, 10:00 AM	0.00Kb/s
5/25/2023, 12:00 PM	0.01Kb/s
5/25/2023, 2:00 PM	0.00Kb/s
5/25/2023, 4:00 PM	0.00Kb/s
5/25/2023, 6:00 PM	0.00Kb/s
5/25/2023, 8:00 PM	0.00Kb/s
5/25/2023, 10:00 PM	0.00Kb/s
5/26/2023, 12:00 AM	0.80Kb/s
5/26/2023, 2:00 AM	0.04Kb/s
5/26/2023, 4:00 AM	0.06Kb/s
5/26/2023, 6:00 AM	0.00Kb/s
5/26/2023, 8:00 AM	0.03Kb/s
5/26/2023, 10:00 AM	0.05Kb/s
5/26/2023, 12:00 PM	0.00Kb/s
5/26/2023, 2:00 PM	0.00Kb/s
5/26/2023, 4:00 PM	0.00Kb/s
5/26/2023, 6:00 PM	0.05Kb/s
5/26/2023, 8:00 PM	0.19Kb/s
5/26/2023, 10:00 PM	0.02Kb/s
5/27/2023, 12:00 AM	0.14Kb/s
5/27/2023, 2:00 AM	0.06Kb/s
5/27/2023, 4:00 AM	0.00Kb/s
5/27/2023, 6:00 AM	0.00Kb/s
5/27/2023, 8:00 AM	0.00Kb/s
5/27/2023, 10:00 AM	0.00Kb/s
5/27/2023, 12:00 PM	0.00Kb/s
5/27/2023, 2:00 PM	0.00Kb/s
5/27/2023, 4:00 PM	0.00Kb/s
5/27/2023, 6:00 PM	0.00Kb/s
5/27/2023, 8:00 PM	0.00Kb/s
5/27/2023, 10:00 PM	0.00Kb/s
5/28/2023, 12:00 AM	0.01Kb/s
5/28/2023, 2:00 AM	0.00Kb/s
5/28/2023, 4:00 AM	0.00Kb/s
5/28/2023, 6:00 AM	0.00Kb/s
5/28/2023, 8:00 AM	0.00Kb/s
5/28/2023, 10:00 AM	0.01Kb/s
5/28/2023, 12:00 PM	0.02Kb/s
5/28/2023, 2:00 PM	0.00Kb/s
5/28/2023, 4:00 PM	0.00Kb/s
5/28/2023, 6:00 PM	0.00Kb/s
5/28/2023, 8:00 PM	0.00Kb/s
5/28/2023, 10:00 PM	0.00Kb/s
5/29/2023, 12:00 AM	0.00Kb/s
5/29/2023, 2:00 AM	0.00Kb/s
5/29/2023, 4:00 AM	0.00Kb/s
5/29/2023, 6:00 AM	0.00Kb/s
5/29/2023, 8:00 AM	0.00Kb/s
5/29/2023, 10:00 AM	0.00Kb/s
5/29/2023, 12:00 PM	0.00Kb/s
5/29/2023, 2:00 PM	0.03Kb/s
5/29/2023, 4:00 PM	0.04Kb/s
5/29/2023, 6:00 PM	0.00Kb/s
5/29/2023, 8:00 PM	0.09Kb/s
DNS Resolvers

74.207.231.5

173.230.128.5

173.230.129.5

173.230.136.5

173.230.140.5

66.228.59.5

66.228.62.5

50.116.35.5

50.116.41.5

23.239.18.5

2600:3c02::3

2600:3c02::5

2600:3c02::4

2600:3c02::6

2600:3c02::c

2600:3c02::7

2600:3c02::2

2600:3c02::9

2600:3c02::8

2600:3c02::b

IP Addresses
Address		Default Gateway	Subnet Mask	Reverse DNS	
192.168.204.103	IPv4 – Private		255.255.128.0	
74.207.228.11	IPv4 – Public	74.207.228.1	255.255.255.0	74-207-228-11.ip.linodeusercontent.com
fe80::f03c:93ff:fe75:e365	IPv6 – Link Local	fe80::1	ffff:ffff:ffff:ffff::	
2600:3c

### Expected Behavior

I want to be able to work on each of the streaming services i created but I cannot get to the admin

**Comment by pedrosousa** [comment]
Hi @daveterry195310 

In this repository we only handle documentation issues. 

Having said that, I'll provide you with some resources that may help you troubleshoot the error you are getting.

You may have configured redirect rules in the Cloudflare dashboard that are causing this behavior. If you have made recent SSL/TLS changes, this could also be the cause of the ERR_TOO_MANY_REDIRECTS error.

Try following the instructions in this page:
https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/

If this doesn't solve your problem, you can reach out to the [Cloudflare Community](https://community.cloudflare.com/) (if you are on a Free plan) or contact Cloudflare Support (if you are on a paid plan).
