### ISSUE TITLE
Conditionally rendering Turnstile

### ISSUE THREAD

**Issue by sgoodluck** [cloudflare/cloudflare-docs#9157]
### Which Cloudflare product(s) does this pertain to?

Turnstile

### Subject Matter

Whether something is supported

### Content Location

At the root of the turnstile docs

### Additional information

It is not clear if the following is supported:

- On interaction required, the component is rendered
- If no interaction is required, the component is hidden 

Currently, it seems that 
```
options={{
  appearance: 'interaction-only'
}}
```

Causes the component to vanish on success which is unexpected behavior.

**Comment by patriciasantaana** [comment]
Hi @sgoodluck ! Looks like this is a bug and has been fixed. I'm going to close this issue now, but feel free to open a new one or ask any questions.
