### ISSUE TITLE
"Migrating to module Workers" should mention or link to "Environment variables with module Workers"

### ISSUE THREAD

**Issue by rhaksw** [cloudflare/cloudflare-docs#9160]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

- https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/
- https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-with-module-workers

### Section that requires update

"Migrating to module Workers"

### What needs to change?

This guide could use a brief note about environment variables since that behavior changes from Service Workers to Module Workers.

### How should it change?

Insert something like:

> When deploying a Module Worker, any [bindings](https://developers.cloudflare.com/workers/platform/environment-variables/) will not be available as global runtime variables. Instead, they are passed to the handler as a [parameter](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#parameters). For example...

**Comment by deadlypants1973** [comment]
Hello @rhaksw ! Does #9265 address your concern?

**Comment by rhaksw** [comment]
This is better, but a migration guide should connect both the old and new terminology, so the relevant sections should also mention "environment variables"

My first instinct when visiting the page to see the changes was to Ctrl-F for "variable"

Thanks for the follow up! I wasn't expecting that and I appreciate it.
