### ISSUE TITLE
Cloudflare connection check in endless loop

### ISSUE THREAD

**Issue by ber999** [cloudflare/cloudflare-docs#9178]
### Example URL(s)

Solcom job specification checkout
ING Germany Bank login

### Actual Behavior

Cloudflare connection check in endless loop

### Expected Behavior

Cloudflare connection check not in endless loop

**Comment by ber999** [comment]
Hallo,

nichts bekannt.

Im Web finden Sie Abhandlungen in großer Zahl. Zum Beispiel:
Zitat Anfang-----------------------------------------------------------------------------------
Viele Benutzer haben berichtet, dass ihr Browser beim Klicken auf einen Link zum Öffnen einer Website hängen geblieben ist und die folgende Meldung angezeigt wird:
Zusammenfassung
Was bedeutet Überprüfen Sie Ihren Browser vor dem Zugriff?<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#was-bedeutet-ueberpruefen-sie-ihren-browser-vor-dem-zugriff>
Browser bleibt beim Überprüfen Ihres Browsers vor dem Zugriff hängen<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#browser-bleibt-beim-ueberpruefen-ihres-browsers-vor-dem-zugriff-haengen>
1]Scannen Sie Ihren PC<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#1scannen-sie-ihren-pc>
2]Überprüfen Sie die Datums-/Zeitzone Ihres Computers<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#2ueberpruefen-sie-die-datumszeitzone-ihres-computers>
3]Deaktivieren Sie Add-Ons oder versuchen Sie es im Inkognito-Modus<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#3deaktivieren-sie-addons-oder-versuchen-sie-es-im-inkognitomodus>
4]VPN verwenden; Wenn Sie VPN verwenden, deaktivieren Sie es und sehen Sie nach<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#4vpn-verwenden-wenn-sie-vpn-verwenden-deaktivieren-sie-es-und-sehen-sie-nach>
Was ist Cloudflare DDoS-Schutz?<https://de.moyens.net/sicherheit/der-browser-bleibt-bei-der-meldung-ueberpruefen-ihres-browsers-vor/#was-ist-cloudflare-ddosschutz>
Überprüfen Sie Ihren Browser vor dem Zugriff….
Der Vorgang ist automatisch. Ihr Browser leitet in Kürze zu Ihrem angeforderten Inhalt weiter.
Bitte erlauben Sie bis zu 5 Sekunden.
DDos-Schutz durch Cloudflare.
[Überprüfen Sie Ihren Browser vor dem Zugriff]
Normalerweise ist dies kein Problem, da Sie nach einigen Sekunden zu der Webseite weitergeleitet werden, die Sie öffnen möchten. Aber es kann ein bisschen besorgniserregend sein, wenn der Browser bei dieser Fehlermeldung hängen geblieben ist. Daher werden wir in diesem Artikel Wege vorschlagen, wie dieses Problem angegangen werden kann.
Was bedeutet Überprüfen Sie Ihren Browser vor dem Zugriff?
Wenn Sie das sehen Überprüfen Sie Ihren Browser vor dem Zugriff Nachricht bedeutet, dass Cloudflare überprüft, ob Ihr Browser legitim ist und ob er einige bösartige Skripte ausführt.
Browser bleibt beim Überprüfen Ihres Browsers vor dem Zugriff hängen
Aus der Fehlermeldung selbst geht ziemlich klar hervor, dass auf der Website, mit der Sie Probleme haben, der Cloudflare-Schutz aktiviert ist. Der Cloudflare-Schutz wird verwendet, um die Website vor Hackern zu schützen und Distributed-Denial-Of-Service-Angriffe (DDoS) abzuschwächen.
Diese Meldung wird Ihnen möglicherweise besonders angezeigt, wenn der Websitebesitzer mit einem DDoS-Angriff konfrontiert ist und er die Option „Im Angriffsmodus‚-Einstellung, die Besuchern beim Besuch Ihrer Website eine JavaScript-Aufforderung anzeigt.
EIN Verteilter DDoS-Angriff ist, wenn Hacker versuchen, Anfragen an den Webserver zu bombardieren, um die Website zum Absturz zu bringen. Cloudflare-Schutz wird verwendet, um diese Angriffe abzuschwächen. Aber manchmal funktioniert das Protokoll nicht und Sie bleiben auf der Nachrichtenseite von Cloudflare hängen.
Sie können den Tab schließen oder den Browser neu starten und sehen, ob das hilft. Aber manchmal funktioniert das nicht und Sie müssen andere Dinge ausprobieren.
Wenn Ihr Browser bei ‚ hängen bleibtÜberprüfen Sie Ihren Browser vor dem Zugriff‚-Bildschirm beim Zugriff auf eine Website, versuchen Sie die folgenden Vorschläge:
1.     Scannen Sie Ihren PC
2.     Überprüfen Sie die Datums-/Zeitzone Ihres Computers
3.     Deaktivieren Sie Add-Ons oder versuchen Sie es im Inkognito-Modus
4.     Verwenden Sie VPN; Wenn Sie VPN verwenden, deaktivieren Sie es und sehen Sie nach.
Lassen Sie uns im Detail darüber sprechen.
1]Scannen Sie Ihren PC
Scannen Sie Ihren PC mit Ihrer Antivirensoftware. Vielleicht ist Ihr Computer tatsächlich infiziert! Verwenden Sie AdwCleaner, um sicherzustellen, dass Ihr Browser nicht entführt wurde.
2] Überprüfen Sie die Datums-/Zeitzone Ihres Computers
[Browser bleibt bei „Überprüfen Sie Ihren Browser vor dem Zugriff“ hängen]
Wenn das Datum und die Zeitzone Ihres Computers nicht korrekt sind, werden Sie mit einer Fülle von Anwendungen konfrontiert und der Dienst wird nicht mehr funktionieren. Und da das Internet auf die Zeitzone angewiesen ist, ist dieser Fehler unvermeidlich. Stellen Sie also sicher, dass Sie die Datums-/Zeitzone Ihres Computers überprüfen und auf automatisch stellen, um den Fehler zu beheben.
Sie können die angegebenen Schritte befolgen, um dasselbe zu tun.
1.     Offen Einstellungen durch Sieg + ich.
2.     Klicken Zeit & Sprache.
3.     Stellen Sie sicher, dass Sie eingeschaltet sind Terminzeit und verwenden Sie den Umschalter zu Uhrzeit automatisch einstellen und Zeitzone automatisch einstellen.
4.     Starten Sie jetzt Ihren Computer neu und prüfen Sie, ob das Problem behoben ist.
Hoffentlich wird dies das Problem beheben.
3]Deaktivieren Sie Add-Ons oder versuchen Sie es im Inkognito-Modus
Wenn Sie unzählige Add-Ons oder Erweiterungen haben, können diese Sicherheitsdienste unterbrechen. Dieses Problem tritt normalerweise in datenschutzbezogenen Erweiterungen auf. Deaktivieren Sie sie also und prüfen Sie, ob das Problem dadurch behoben wird.
Alternativ können Sie Ihren Browser im Inkognito-Modus starten und sehen, ob das funktioniert.
4]VPN verwenden; Wenn Sie VPN verwenden, deaktivieren Sie es und sehen Sie nach
VPN oder Virtual Private Network wird verwendet, um Ihren Computer sicher mit verschiedenen Orten auf der Welt zu verbinden. Wenn Sie also kein VPN verwenden, wählen Sie eines aus der Liste der besten kostenlosen VPNs für Windows aus.
Wenn Sie VPN verwenden, deaktivieren Sie es und sehen Sie nach.
Was ist Cloudflare DDoS-Schutz?
Der DDoS-Schutz von Cloudflare hilft, DDoS-Angriffe auf Websites, Anwendungen und Netzwerke abzuschwächen. Es ermöglicht ein reibungsloses Funktionieren und Ausführen von legitimem Datenverkehr und stellt sicher, dass die Website nicht kompromittiert wird.
Hoffe hier hilft dir etwas.
Zitat Ende:--------------------------------------------------------------------------------

Mit freundlichen Grüßen

Bernd Dreyer
Kirchenstraße 8
84478 Waldkraiburg
Bayern
Deutschland
***@***.******@***.***>
***@***.******@***.***> Bitte nicht mehr verwenden!
Festnetz: +49 8638 2036295
Mobiltel.: +49 177 5428627<tel:+491775428627>

Von: Mohsen ***@***.***
Gesendet: Donnerstag, 1. Juni 2023 12:09
An: cloudflare/cloudflare-docs ***@***.***>
Cc: ber999 ***@***.***>; Author ***@***.***>
Betreff: Re: [cloudflare/cloudflare-docs] Cloudflare connection check in endless loop (Issue #9178)


?

**Comment by kodster28** [comment]
Howdy, definitely sorry you're experiencing these issues... but this is a documentation repo. We can't do anything to fix an issue you're experiencing in your browser.

Best suggestion is to either reach out to the site owner to let them know or -- sometimes this works -- you could try clearing your cache and cookies.

**Comment by ber999** [comment]
Hello Kody,

unfortunately, I can't give you access to my ING bank account, so that you can test.
This is the other an address
Nur einen Moment... (solcom.de)<https://www.solcom.de/de/projektportal/bewerbung_85193>
May be that have to open account at first an then select a position as you would apply.
This is a MS Edge issue only. Opera works properly.

Mit freundlichen Grüßen

Bernd Dreyer
Kirchenstraße 8
84478 Waldkraiburg
Bayern
Deutschland
***@***.******@***.***>
***@***.******@***.***> Bitte nicht mehr verwenden!
Festnetz: +49 8638 2036295
Mobiltel.: +49 177 5428627<tel:+491775428627>

Von: Kody ***@***.***>
Gesendet: Donnerstag, 1. Juni 2023 15:47
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [cloudflare/cloudflare-docs] Cloudflare connection check in endless loop (Issue #9178)


Howdy, definitely sorry you're experiencing these issues... but this is a documentation repo. We can't do anything to fix an issue you're experiencing in your browser.

Best suggestion is to either reach out to the site owner to let them know or -- sometimes this works -- you could try clearing your cache and cookies.

-
