### ISSUE TITLE
cloudflare static s3 site missing instructions

### ISSUE THREAD

**Issue by alacy-centrl** [cloudflare/cloudflare-docs#9191]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/third-party-software/others/configuring-an-amazon-web-services-static-site-to-use-cloudflare/

### Section that requires update

Set up your site on Cloudflare

### What needs to change?

There needs to be instructions for adding page rules to the s3 domain in cloudflare to disable ssl as s3 does not support ssl. 

### How should it change?

Add a new section or append to the section listed above with at minimum a note talking about the need to disable ssl via page rules so the s3 site can work.

**Comment by ngayerie** [comment]
Hi @alacy-centrl 
I've raised a PR: https://github.com/cloudflare/cloudflare-docs/pull/10191
Would this extra step address your concerns?
Thanks!

**Comment by alacy-centrl** [comment]
Hey Nic I added a comment to the PR. Thank you for looking into this

**Comment by kodster28** [comment]
(feel free to re-open if you had additional comments on the merged in PR)
