### ISSUE TITLE
define why expression = "true" is needed in Terraform transform rule 

### ISSUE THREAD

**Issue by chris-martinelli** [cloudflare/cloudflare-docs#9204]
### Which Cloudflare product does this pertain to?

Rules

### Existing documentation URL(s)

https://developers.cloudflare.com/terraform/additional-configurations/transform-rules/

### Section that requires update

    expression = "true" is not defined in the documentation. On https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset it states:
    
    > expression (String) Criteria for an HTTP request to trigger the ruleset rule action. Uses the Firewall Rules expression language based on Wireshark display filters. Refer to the Firewall Rules language documentation for all available fields, operators, and functions.

Why would true be valid here?

See also https://github.com/cloudflare/terraform-provider-cloudflare/issues/2490#issuecomment-1572931439

### What needs to change?

Define what expression = "true" does and why it is needed.

### How should it change?

 This appears to be undocumented

**Comment by pedrosousa** [comment]
The expression at the top level is the [rule filter expression](https://developers.cloudflare.com/ruleset-engine/about/rules/), which decides whether the rule action will be applied or not for the current request. The filter expression is evaluated in the context of the current request. If the full expression evaluates to `true`, there is a rule match and the rule action is applied. If it evaluates to `false`, there is no match for the rule and the action will not be applied to the current request.

As stated in the [Rules language](https://developers.cloudflare.com/ruleset-engine/rules-language/) documentation:
> When evaluating a rule, Cloudflare compares values associated with an HTTP request to those defined in the rule’s [expression](https://developers.cloudflare.com/ruleset-engine/rules-language/expressions/). If the expression evaluates `true`, Cloudflare triggers the [action](https://developers.cloudflare.com/ruleset-engine/rules-language/actions/) for that rule.


The rule expression does not have to be `true`, but it _must_ evaluate to `true` or `false`. Using `true` in the filter expression means "apply this rule to every incoming request" (given the current scope, which can be zone or account).

In the example you provided in https://github.com/cloudflare/terraform-provider-cloudflare/issues/2490, you seem to be using a non-boolean field in the rule filter expression without an operator. In this case, the expression will not evaluate to `true` or `false`, which triggers the error.

**Comment by chris-martinelli** [comment]
Thank you very much @pedrosousa . Might some of this be useful in https://developers.cloudflare.com/terraform/additional-configurations/transform-rules/? Specifically the snippet from the Rules language page that you quoted, as well as a link?

**Comment by pedrosousa** [comment]
I'm tracking the future work about adding this information about filter expressions to Dev Docs in the following internal ticket: PCX-7188.
I'm closing this issue, since your question has been clarified.
