### ISSUE TITLE
Add documentation for ReadableStream.tee()

### ISSUE THREAD

**Issue by eminence** [cloudflare/cloudflare-docs#9285]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/streams/readablestream/

### Section that requires update

The "Methods" section

### What needs to change?

A new section for the `tee()` method.

### How should it change?

The `ReadableStream` type has a `tee()` method (which is well-documented in other places, like the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/tee) docs).

The MDN docs highlight potential for unbounded memory usage, in case one consumer is much slower than the other consumer.

However, Cloudflare's implementation of `ReadableStream` has special support for this case, as documented in [this README](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/streams/README.md#what-about-tees).  This README is unfortunately hard to discover (thanks to @KianNH who pointed it out to me).  

It would be nice if the [methods section](https://developers.cloudflare.com/workers/runtime-apis/streams/readablestream/#methods) of the docs included this important info about the specific Cloudflare implementation of `tee()`

**Comment by deadlypants1973** [comment]
Hi @eminence , thank you for the submission. Would you be able to take a first pass at this and PR it?

**Comment by KimJ15** [comment]
Closed per https://github.com/cloudflare/cloudflare-docs/pull/10026

**Comment by eminence** [comment]
I believe this is still not resolved.  The proposed enhancement in #10026 was not accepted.

I still think that improved documentation in this area would be beneficial to all Cloudflare customers
