### ISSUE TITLE
R2 Terraform example with cloudflare provider incorrect

### ISSUE THREAD

**Issue by skeletorXVI** [cloudflare/cloudflare-docs#9336]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/examples/terraform/

### Section that requires update

The example code needs to be updated.

### What needs to change?

The resource block incorrectly uses an `aws_s3_bucket` which causes the example to be unusable.

```terraform
resource "aws_s3_bucket" "cloudflare-bucket" {
  bucket = "my-tf-test-bucket"
}
```

### How should it change?

The resource block needs to be changed to a correct `cloudflare_r2_bucket`.

```terraform
resource "cloudflare_r2_bucket" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "my-tf-test-bucket"
  location   = "WEUR"
}
```

**Comment by dcpena** [comment]
@skeletorXVI thanks so much for contribution! much appreciated 😄
