### ISSUE TITLE
Linux package links broken

### ISSUE THREAD

**Issue by nathaniel-bubis-healthy** [cloudflare/cloudflare-docs#9348]
### Example URL(s)

https://pkg.cloudflareclient.com/packages/cloudflare-warp
https://pkg.cloudflareclient.com/install

### Actual Behavior

404 error

### Expected Behavior

A website where .deb or .yum packages may be downloaded

### Additional information

The links provided for package download are no longer updated and lead to a 404 error

**Comment by Cyb3r-Jak3** [comment]
I did find the install instructions on the wayback machine
https://web.archive.org/web/20230504044211/https://pkg.cloudflareclient.com/install

**Comment by kodster28** [comment]
Not sure if this is something @kkrum could help with?

**Comment by raovin** [comment]
Yes.
```
sudo apt install cloudflare-warp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cloudflare-warp
```
![image](https://github.com/cloudflare/cloudflare-docs/assets/22012508/fa91f9a2-c5fc-4008-86ee-5ed5d2e684c5)

**Comment by kkrum** [comment]
New link should just be "Package repository" which points to https://pkg.cloudflareclient.com/
