### ISSUE TITLE
Document dynamic import support in Wrangler

### ISSUE THREAD

**Issue by penalosa** [cloudflare/cloudflare-docs#9351]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

`--no-bundle` and dynamic imports

### Content Location

In the Wrangler section of the docs

### Additional information

See https://github.com/cloudflare/workers-sdk/issues/417

**Comment by KimJ15** [comment]
Closed per https://github.com/cloudflare/cloudflare-docs/pull/12980
