### ISSUE TITLE
Update billing article based on community thread

### ISSUE THREAD

**Issue by kodster28** [cloudflare/cloudflare-docs#9359]
### Which Cloudflare product does this pertain to?

Support

### Existing documentation URL(s)

https://developers.cloudflare.com/support/account-management-billing/billing-cloudflare-plans/troubleshooting-failed-payments/

### Section that requires update

Described below.

### What needs to change?

https://community.cloudflare.com/t/problems-on-top-of-problems-and-no-solutions/515308/11

### How should it change?

In line with community thread.

**Comment by JamieEE14** [comment]
Duplicate reference has been removed.
