### ISSUE TITLE
Q: Improving Cloudflare (TM) WARP

### ISSUE THREAD

**Issue by AKotov-dev** [cloudflare/cloudflare-docs#9416]
### Which Cloudflare product(s) does this pertain to?

1.1.1.1

### Subject Matter

Where to Find Cloudflare(TM) WARP Developers

### Content Location

In an accessible place

### Additional information

Q: Improving Cloudflare (TM) WARP
---
Hello colleagues. If this doesn't burden you too much, could you point me to a repository/section where exactly Cloudflare(TM) WARP is discussed? The matter is that I cannot orient here as there are a lot of repositories (I know English bad). I'd like to inform the Cloudflare(TM) WARP developers about two bugs I've found that relate to the start `warp-svc.service` and a missing dependency that could cause the `cloudflare-warp` package to not install from the Cloudflare(TM) WARP repository.

On the merits of the issue, I can report the following...

1. In the `[Service]` section of the `/etc/systemd/system/warp-svc.service` file, you need to add processing of the `ExecStop` event so that the interface is correctly released before the computer restarts and does not cause a network initialization error, since the network rises earlier than the `warp-svc.service`:
```
...
[Service]
ExecStop=/bin/rm -f /etc/sysconfig/network-scripts/ifcfg-CloudflareWARP
...
```
2. It is also very desirable to add the `libcap-utils` dependency, since the `setcap` instruction from this package is used in the `spec-file` at the %post step. If the package `libcap-utils` is not installed, then when installing `cloudflare-warp`, `/etc/systemd/system/warp-svc.service` is not created. This improvement will expand the list of distributions, in particular + `Mageia Linux`. 

Can you please tell me where I can post this message? Thank you.

Sincerely,
Alex

**Comment by ranbel** [comment]
👋 @AKotov-dev To report bugs or suggest improvements, please select the "bug" icon in the WARP GUI and submit a feedback form to the WARP team. 
![image](https://github.com/cloudflare/cloudflare-docs/assets/101146722/480a6af1-2d73-4ab7-b134-ee47a6d1e48f)
Thanks!
