### ISSUE TITLE
Workers example not working

### ISSUE THREAD

**Issue by kei0** [cloudflare/cloudflare-docs#9431]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/examples/signing-requests/#generating-signed-requests

### Section that requires update

Workers sample script in the section 'Generating signed requests'

### What needs to change?

https://developers.cloudflare.com/workers/examples/signing-requests/

>      base64Mac = base64Mac.replaceAll("+", "-");

If the line is removed from the generation code, it starts working with the verification code in the same page.

### How should it change?

Remove the two lines below from the sample script. 

>   // must convert "+" to "-" as urls encode "+" as " "
>   base64Mac = base64Mac.replaceAll("+", "-");

or make it appropriate.

**Comment by deadlypants1973** [comment]
#11104
