### ISSUE TITLE
Logpush filters and destination unclarity

### ISSUE THREAD

**Issue by TrueBrain** [cloudflare/cloudflare-docs#9436]
### Which Cloudflare product does this pertain to?

Logs

### Existing documentation URL(s)

https://developers.cloudflare.com/logs/get-started/api-configuration/#destination
https://developers.cloudflare.com/logs/reference/filters/

### Section that requires update

For the first link, the R2 bucket says there should be a `/` between `<BUCKET_PATH>/account-id=`. This turns out to be false, and it should be a `?`.
For the second link, nowhere it mentions the `where` is mandatory. It is strongly suggested that it is optional, but without it, it really isn't working. So although the `and` and `or` are optional, the `where` part is not.

### What needs to change?

See above

### How should it change?

See above

### Additional information

Was a bit frustrating to get this working :D Seems multiple people noticed the same in the terraform plugin of Cloudflare, but seems nobody made a ticket in this repo; so both issues remain unfixed, bringing the frustration forward to the next person. So here is me trying to break that loop :P

**Comment by angelampcosta** [comment]
Thanks for letting us know @TrueBrain. We will follow up on this issue.
