### ISSUE TITLE
Update reference to CORS configuration for public buckets

### ISSUE THREAD

**Issue by kev-ac** [cloudflare/cloudflare-docs#9458]
### Which Cloudflare product does this pertain to?

R2

### Existing documentation URL(s)

- https://developers.cloudflare.com/r2/buckets/public-buckets/

### Section that requires update

https://github.com/cloudflare/cloudflare-docs/blob/e2e12d866732bdb7ad69b87ff65968c0c45b8c16/content/r2/buckets/public-buckets.md?plain=1#L187-L189

### What needs to change?

Currently the page states that CORS configuration is only possible via the S3 API, but configuration via the Dashboard is possible like described [here](https://developers.cloudflare.com/r2/buckets/cors/).

### How should it change?

Add a reference to the CORS page or remove this paragraph as it may be redundant.

**Comment by dcpena** [comment]
Thanks for the catch @kev-ac! I removed the older reference because it's already listed in the Buckets section of the docs.
