### ISSUE TITLE
Instructions for updating wrangler from v2.20.0 to 3.1

### ISSUE THREAD

**Issue by mrbm** [cloudflare/cloudflare-docs#9463]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/migration/

### Section that requires update

there is no information regarding going from v2 to v3, i'm attempting to update from v2.20.0 to v3.1...errors that don't make sense.

### What needs to change?

it needs to exist

### How should it change?

it needs to exist

### Additional information

With v2.20.0 and latest version being 3.1.0 on latest mac os:

% sudo npm install -g wrangler                                                          
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /Users/dev/.nvm/versions/node/v19.0.1/lib/node_modules/wrangler/node_modules/better-sqlite3
npm ERR! command failed
....
leading to more errors

**Comment by DedsonDev** [comment]
I'm not trying to update wrangler, just clean install, but I'm getting a very similar error to yours.
I've got stuff in the middle referencing Python and Visual Studio, but nowhere in the docs are those labeled as prereqs.
Will not be using Workers if I can't develop locally.

**Comment by admah** [comment]
@mrbm are the errors that you're experiencing preventing you from installing or are they just errors in the output?

While there is a list of deprecations for v3 ([here](https://developers.cloudflare.com/workers/wrangler/deprecations/)) there are no special instructions from going from v2 to v3 that should require a migrations page. Added dependencies are a result of new functionality, and should be installed without needing user input. These should not prevent you from updating. If they do, please report a bug on the [workers-sdk repo](https://github.com/cloudflare/workers-sdk/issues).

**Comment by mrbm** [comment]
@admah yes they prevent me from installing, still rocking 2.20 over here. I gave up and haven't tried in the last month as my project seems to still work okay. I will try reporting there as well at some point

**Comment by admah** [comment]
@mrbm you may be running into a compatibility issue that we had prior to Wrangler v3.3.0. That has since been resolved if you want to retry. If that doesn't work please [file an issue](https://github.com/cloudflare/workers-sdk/issues).

We have added a doc for migrating from Wrangler v2 to v3 - https://developers.cloudflare.com/workers/wrangler/migration/update-v2-to-v3/ - so I'm going to close this issue as completed.

It mentions the deprecations as well as the compatibility issue with earlier versions of v3.

**Comment by mrbm** [comment]
don't close till i test!

**Comment by admah** [comment]
@mrbm if it still doesn't work, you'll need to file an issue in the workers-sdk repo since it's potentially a bug with Wrangler. I'm closing this issue since the documentation requested has been written.

**Comment by deadlypants1973** [comment]
#10151

**Comment by mrbm** [comment]
@admah please review

https://github.com/cloudflare/workers-sdk/issues/3531#issuecomment-1658588045

if you review this thread, you you will find there are now new system dependancies that didn't exist in v2, this needs to be updated in the documentation as I (and probably many others) struggled with this since June as a result of this not being documented

**Comment by mrbm** [comment]
Please note I created a new bug report with information on the method of the temporary fix to be used for mac m1/m2 that should be include until the new sqlite dependency is removed in a future v3 iteration: https://github.com/cloudflare/cloudflare-docs/issues/10230
