### ISSUE TITLE
Support newest Hugo version (0.81.0)

### ISSUE THREAD

**Issue by tinhspace** [cloudflare/cloudflare-docs#947]
Now, Pages only supports Hugo 0.54, and have a lot of bugs with Hugo 0.81.0, can't deploy my sites.

![image](https://user-images.githubusercontent.com/236967/111247264-3f1ca880-863a-11eb-80fe-59ef8c13c018.png)

**Comment by HelloFillip** [comment]
You can simply set the environment variable `HUGO_VERSION` to the appropriate version and this will work. 

Please see this pull request for more details: https://github.com/cloudflare/cloudflare-docs/pull/896.
