### ISSUE TITLE
Additional third-party integration

### ISSUE THREAD

**Issue by kei0** [cloudflare/cloudflare-docs#9584]
### Which Cloudflare product does this pertain to?

Magic WAN

### Existing documentation URL(s)

https://developers.cloudflare.com/magic-wan/third-party/

### Section that requires update

tutorial for third-party integrations

### What needs to change?

Add one new vendor's example to connect Magic-WAN

### How should it change?

I can get the working configuration from the vendor and share it with the page authors. 
So let me know how to proceed to add a new tutorial.

**Comment by marciocloudflare** [comment]
Hi @kei0. We only publish third-party integrations deemed necessary for our customers. Also, this is done by our Implementation Team. If you represent a third-party, I'd advise you to talk to your customer service manager. Closing this ticket for now.
