### ISSUE TITLE
Pages Language support and tools page has broken tabs

### ISSUE THREAD

**Issue by jrf0110** [cloudflare/cloudflare-docs#9604]
### Example URL(s)

https://developers.cloudflare.com/pages/platform/language-support-and-tools/

### Actual Behavior

When you first load the page, both v1 and v2 tabs are active on the tools,  frameworks, and environment tables:

<img width="717" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/767070/d3b0ec44-2f01-4fb3-b873-b589e04dd6b7">

Further, the v2 tab does not work when you click the "beta" tag - only when you click the v2 text does it activate

![pages-docs-tab-bug](https://github.com/cloudflare/cloudflare-docs/assets/767070/d6e3f2d9-f35c-450a-bc42-2cb98aeea4ac)

### Expected Behavior

- Only the v2 tab should be highlighted on page load.
- When you click any part of the v2 tab button, it should switch to the v2 tab.

**Comment by kodster28** [comment]
Howdy @GregBrimble, I believe this is b/c both tabs are in the active state on page load.

Appears like the Build Environments tabs further down the page works correctly.
