### ISSUE TITLE
Cloudflare Pages - Deploy a Hugo site - 'create-react-app' should be 'installing hugo'

### ISSUE THREAD

**Issue by BrendanSluke** [cloudflare/cloudflare-docs#965]
Section of doc referenced:
 [Cloudflare pages docs for Hugo- ​Deploying with Cloudflare Pages](https://developers.cloudflare.com/pages/how-to/deploy-a-hugo-site#deploying-with-cloudflare-pages)

This section of the Hugo doc has a reference to 'create-react-app' when it should read something like 'Hugo [Version ID]' or 'Hugo 0.80.0.

Current Screenshot of docs:
![image](https://user-images.githubusercontent.com/62220614/111716459-148e4380-8824-11eb-8c8c-cb75c4d02f8e.png)

This is what my Hugo logs look like on Cloudflare pages:
![image](https://user-images.githubusercontent.com/62220614/111716585-561eee80-8824-11eb-89e1-326b725f1280.png)

**Comment by BrendanSluke** [comment]
Pull Request - https://github.com/cloudflare/cloudflare-docs/pull/966

**Comment by KimJ15** [comment]
Thanks for submitting an issue and PR. Closing this issue - we will work from the referenced PR.
