### ISSUE TITLE
ScheduledEvent.type is undefined but is documented as "scheduled"

### ISSUE THREAD

**Issue by skepticfx** [cloudflare/cloudflare-docs#9670]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#syntax-es-modules

### What changes are you suggesting?

The documentation for ScheduledEvent's properties has a `type` field which is expected to be defined and always be set to "scheduled". However, this is not the case when run in a Worker.

From the [documentation](https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#properties),
```
event.type 

The type of event. This will always return "scheduled".
```

Not sure if this is a Workers regression or a documentation clarification.

FYI @irvinebroque 

### Additional information

Other fields like `event.scheduledTime` and `event.cron` are working as expected and is documented correctly.

**Comment by KimJ15** [comment]
https://github.com/cloudflare/cloudflare-docs/pull/9671/files appears to have resolved this issue. Closing as complete.
