### ISSUE TITLE
Zone Analytics for DNS does not match the actual product

### ISSUE THREAD

**Issue by Zaulao** [cloudflare/cloudflare-docs#9688]
### Which Cloudflare product does this pertain to?

Analytics

### Existing documentation URL(s)

- https://developers.cloudflare.com/analytics/account-and-zone-analytics/zone-analytics/#dns

### What changes are you suggesting?

The documentation for the DNS Queries topic says that `You can filter by one or several DNS records by entering record names (for example, www.example.com) in the dropdown near the top`. However such dropdown is not present in the product.

### Additional information

The only drop down that exists in the DNS analytics dashboard is the one that allows selection of the timeframe for viewing the _Queries By Response Code_ metrics

![image](https://github.com/cloudflare/cloudflare-docs/assets/29334377/8b16af72-e883-44ea-a9fb-2236430d388e)

**Comment by angelampcosta** [comment]
@Zaulao thank you for pointing this out. We will follow up on this issue.
