### ISSUE TITLE
[Workers] Update Workers Sites banner

### ISSUE THREAD

**Issue by lrapoport-cf** [cloudflare/cloudflare-docs#9739]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/platform/sites/

### What changes are you suggesting?

Update the warning banner at the top to more strongly suggest that Cloudflare Pages be considered instead of Workers Sites. Indicate that pages is the best choice for deploying sites with static assets. Perhaps the banner color can also be changed to orange to call more attention to it.

### Additional information

For reference, for applicable issues/PRs submitted to workers-sdk regarding Workers Sites, it will be noted that going forward the assets system will be overhauled as part of Pages/Workers convergence, and will inherit the benefits of the Pages assets system, and that in the meantime, [Pages](https://developers.cloudflare.com/pages/) is the best choice for deploying sites with static assets.

**Comment by KimJ15** [comment]
@lrapoport-cf - The color of the banner is standard so that can't change. We can change the language to say "Use [Cloudflare Pages](https://developers.cloudflare.com/pages/) for hosting static applications instead of Workers Sites" rather than "consider."

**Comment by lrapoport-cf** [comment]
@KimJ15 i think that works 👍 @admah how does this sound to you?

@KimJ15  could the banner also be changed from informational (blue) to warning (orange)?

**Comment by KimJ15** [comment]
@lrapoport-cf To make it a warning the text should be a warning. For example "Do not use Workers Sites to host static applications because [action and impact]."

**Comment by deadlypants1973** [comment]
@lrapoport-cf easy change but as per @KimJ15 's comment, what's the impact we want to convey on why we strongly encourage Pages over Workers sites?

**Comment by lrapoport-cf** [comment]
@deadlypants1973 we discussed internally and we're ok leaving it as info 👍 

@admah how do you feel about updating to the following messaging? 
"The assets system will be overhauled as part of the work to converge Pages and Workers, and will consequently inherit the benefits of the [Cloudflare Pages](https://developers.cloudflare.com/pages/) asset system. In the meantime,  [Cloudflare Pages](https://developers.cloudflare.com/pages/) is the best choice for hosting static applications.

**Comment by admah** [comment]
@lrapoport-cf  @deadlypants1973  how about this: 

"We recommend using [Cloudflare Pages](https://developers.cloudflare.com/pages/) to host your static applications.  While Workers Sites will work, the assets system mentioned below will be overhauled soon, and will inherit the benefits of the Cloudflare Pages asset system."

I think that makes the recommendation immediately, and removes reference to convergence since many users may not know what that is referring to.

Also cc: @nevikashah for visibility

**Comment by penalosa** [comment]
What about talking about the benefits of Pages? Something like:
> We recommend using [Cloudflare Pages](https://developers.cloudflare.com/pages/) to host your static applications, which gives you the benefit of:
> * Automatic git integration
> * Free hosting for static assets
> * Etc...
