### ISSUE TITLE
Typo in Azure AD Identity docs

### ISSUE THREAD

**Issue by bensaine** [cloudflare/cloudflare-docs#9800]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

- https://developers.cloudflare.com/cloudflare-one/identity/idp-integration/azuread/#1-obtain-azure-ad-settings

### What changes are you suggesting?

There is a transcription error in the CF docs from the wording in Azure.

Under `Set up Azure AD as an identity provider` > `1. Obtain Azure AD settings` > `6.`

> Select **Register an application to integration with Azure AD (App you’re developing)** and then select **Create**.

should be

> Select **Register an application to _integrate_ with Azure AD (App you’re developing)** and then select **Create**.

https://github.com/cloudflare/cloudflare-docs/blob/82def1a391c52a1887bc689a2d8c8993aeccb02d/content/cloudflare-one/identity/idp-integration/azuread.md?plain=1#L33

See screenshot.

### Additional information

<img width="584" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/34781348/004066c2-def8-4d7a-9aaa-1e5f32a8088b">

**Comment by ranbel** [comment]
Thanks for flagging this issue!
