### ISSUE TITLE
WRAP client check: Device serial numbers and Device UUID cannot be used in manual deploy

### ISSUE THREAD

**Issue by jeankhawand** [cloudflare/cloudflare-docs#9834]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/cloudflare-one/identity/devices/warp-client-checks/device-uuid/
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/manual-deployment/
https://developers.cloudflare.com/cloudflare-one/identity/devices/warp-client-checks/

### What changes are you suggesting?

referring again to #9045 – just want to understand that assigning UUIDs to devices is not possible for manual deployment, In this case configuring a policy from `Access > Applications` more specifically a policy with selector of type `Device Posture - serial number list` or `unique client id` does not have any sense right? cause currently followed the doc and used the registration id cause I do not have mdm setup won't help? which means that these sections in cloudflare docs need to be flagged for mdm only unless there is a workaround or way to get it working for manual deployment.
<img width="316" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/22157081/11549acb-3abf-4811-8280-11cd852bd53b">

<img width="970" alt="image" src="https://github.com/cloudflare/cloudflare-docs/assets/22157081/3837b2c5-9ef3-4781-9e2b-c0da85a22266">

**Comment by jeankhawand** [comment]
At least hide these selectors from the drop down if the user doesn't have mdm setup in place

**Comment by ranbel** [comment]
👋 @jeankhawand Thanks for the feedback. Unfortunately, Device UUID is only available for managed devices at this time. I am going to close this issue as completed because the doc calls out the following:

> You will need to use a [managed deployment tool](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/) to assign UUIDs. It is not possible to assign them manually.

As far as clarifying the MDM requirement in the dashboard, I will pass along the suggestion to the team.
