### ISSUE TITLE
Lists are showing up as "No valid options."

### ISSUE THREAD

**Issue by laserjobs** [cloudflare/cloudflare-docs#9910]
### Which Cloudflare product does this pertain to?

Zero Trust

### Existing documentation URL(s)

https://developers.cloudflare.com/learning-paths/modules/security/dns-filtering-create-policy/recommended-policies/?learning_path=dns-filtering#block-online-tracking

### What changes are you suggesting?

Are lists a paid option, every time I try to add anything "in list" all I get is "No valid options."

### Additional information

![image](https://github.com/cloudflare/cloudflare-docs/assets/9165736/500c955b-60a1-40ca-b69b-44642170ac57)

**Comment by ranbel** [comment]
Hi @laserjobs, did you already create a list? https://developers.cloudflare.com/learning-paths/modules/security/dns-filtering-create-policy/create-list/?learning_path=dns-filtering

**Comment by laserjobs** [comment]
> Hi @laserjobs, did you already create a list? https://developers.cloudflare.com/learning-paths/modules/security/dns-filtering-create-policy/create-list/?learning_path=dns-filtering

You are correct, I was thinking it was a preset list. Thanks for the clarification.
