### ISSUE TITLE
Documentation for Workers / MailChannels integration

### ISSUE THREAD

**Issue by zaccomode** [cloudflare/cloudflare-docs#9939]
### Which Cloudflare product(s) does this pertain to?

Workers

### Subject Matter

The MailChannels/Workers integration (as described [on the Cloudflare Blog](https://blog.cloudflare.com/sending-email-from-workers-with-mailchannels/))

### Content Location

Although not a fully-realized runtime API, it would make sense to have it in the [Runtime APIs section](https://developers.cloudflare.com/workers/runtime-apis/)
Otherwise, a [Tutorial](https://developers.cloudflare.com/workers/tutorials/) or [Example](https://developers.cloudflare.com/workers/examples/) in their respective sections of the Workers API would make sense.

### Additional information

I spent a bit of time today putting together what I would consider to be a good overview. Although it relates to more than specifically workers, I believe it would be useful to go into some depth about the DNS requirements, good practices, etc.
https://github.com/zaccomode/better-cfw-mailer-docs
I wouldn't consider this documentation to be the golden example and there is definitely more depth that could be explored in proper docs, but it covers more than any individual resource I could find online at the moment.

**Comment by KimJ15** [comment]
@codewithkristian @rickyrobinett Bringing your attention to this tutorial! Tagged as dev education for your review.

**Comment by kodster28** [comment]
@JacobMGEvans / @admah, also not sure if you'd be able to help with this one.

**Comment by kodster28** [comment]
Howdy @zaccomode, apologies for the delay here.... I believe this might be mostly addressed by the [Pages documentation](https://developers.cloudflare.com/pages/functions/plugins/mailchannels).

Closing this out as likely completed since it covers most of the points hit in your docs, but feel free to re-open another issue if this doesn't meet the spirit of your issue.
