### ISSUE TITLE
Cloudflare workers testing

### ISSUE THREAD

**Issue by huv1k** [cloudflare/cloudflare-docs#996]
I would like to see a section about testing Cloudflare workers, this is completely missing and should be part of any "production" ready solution. I can see a lot of junior developers need these kinds of resources.

**Comment by KimJ15** [comment]
Hi @huv1k The Workers developer documentation has a section for testing here: https://developers.cloudflare.com/workers/learning/debugging-workers#local-testing-with-wrangler-dev. If you have any specific documentation updates, please feel free to submit another issue. Thanks!
