### ISSUE TITLE
Add instructions for deploying a Deno Lume static site on Cloudflare Pages

### ISSUE THREAD

**Issue by leighmcculloch** [cloudflare/cloudflare-docs#9988]
### Which Cloudflare product(s) does this pertain to?

Pages

### Subject Matter

How to deploy Deno Lume static sites

### Content Location

https://github.com/cloudflare/cloudflare-docs/blob/production/content/pages/framework-guides/_index.md

aka

https://developers.cloudflare.com/pages/framework-guides/

### Additional information

Lume is a static site generator built on Deno:

https://lume.land

**Comment by kodster28** [comment]
Howdy @leighmcculloch, apologize this has been sitting so long.

Did a bit of poking around and -- at least based on the stats I'm seeing at [npmcharts](https://npmcharts.com/compare/lume,lume_cli?interval=30) -- creating a guide around Deno doesn't quite seem like the juice is worth the squeeze in terms of prioritization and maintenance here.

Obviously, we'd love to have 3rd party integration guides for every tool out there... but we have to prioritize our creation / maintenance for the more popular ones.

Thanks for raising + hope ^^^ helps in terms of understanding why I'm closing this out!

**Comment by oscarotero** [comment]
I only want to clarify that the Lume package in NPM is not the same as Lume SSG for Deno. 
Deno has a different package registry and Lume is here: https://deno.land/x/lume@v2.2.0
In Deno registry, you cannot see the number of downloads, so it's not possible to compare it with NPM packages.

Interestingly enough, the are instructions on Lume site for Cloudflare Pages: https://lume.land/docs/advanced/deployment/#cloudflare-pages

**Comment by rdela** [comment]
@kodster28 disappointed in this outcome and the lack of response to Óscar’s clarification from May. It shaped a large purchasing decision today away from Cloudflare, who I was advocating for.
